### ISSUE TITLE
Change the crc network bridge from 192.168.126.1 to 192.168.130.1

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#100]
As of now we are using the same network bridge as installer uses and it might be result into conflict if a user is run installer once and then try out the crc. It would be good for us to have that separation from beginning.

**Comment by anjannath** [comment]
@praveenkumar This was handled in https://github.com/code-ready/crc/commit/1e19504bf29e3238e8d8ee2d5bf9614347d4653b right? Should be closed!
