### ISSUE TITLE
Improve OpenShift status in `crc status`

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#1002]
Currently, `oc status` will report the OpenShift cluster is stopped if one of the operators from `oc get co` is not in the ready state.
If the `oc` command manages to get a list of operators, this means the cluster is not "stopped", but merely that it's not fully ready.
It would be less confusing to report its state as "degraded" (for example).

We'll need to document what 'degraded' means. Mostly that the cluster is running but that some operations are likely to have issues (for example, if the auth operator is not operational, oc login will fail)

**Comment by praveenkumar** [comment]
This is already fixed.
