### ISSUE TITLE
Operator Install Failed - No Such Host Error

### ISSUE THREAD

**Issue by yapnel** [code-ready/crc#1014]
### General information

  * OS: Windows 10 Enterprise 1909
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
``` crc version
# Put the output of `crc version`
``` crc version: 1.5.0+e1c8fb8 OpenShift version: 4.2.14 (embedded in binary)
  
## CRC status
```bash
# Put the output of `crc status`
``` CRC VM:          Running
OpenShift:       Running (v4.2.14-x86_64)
Disk Usage:      13.06GB of 32.2GB (Inside the CRC VM)
Cache Usage:     12.73GB
Cache Directory: C:\Temp\.crc\cache

## CRC config
```bash
# Put the output of `crc config view`
```- http-proxy: http://<USERNAME>:<SECRET>@<IP>:8080
- https-proxy: http://<USERNAME>:<SECRET>@<IP>:8080
- no-proxy: localhost,.cluster.local,.svc,.testing,10.128.0.0/14,127.0.0.1,172.30.0.0/16,192.168.126.0/24,api-int.crc.testing,api.crc.testing,etcd-0.crc.testing,localhost


## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```Host Name:                 <REDACTED>
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.18363 N/A Build 18363
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          <REDACTED>
Registered Organization:   <REDACTED>
Product ID:                00329-00000-00003-AA523
Original Install Date:     13/02/2020, 14:44:49
System Boot Time:          15/02/2020, 10:29:51
System Manufacturer:       HP
System Model:              ProLiant m710x Server Cartridge
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 94 Stepping 3 GenuineIntel ~3000 Mhz
BIOS Version:              HP H07, 26/02/2019
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-gb;English (United Kingdom)
Input Locale:              N/A
Time Zone:                 (UTC+00:00) Dublin, Edinburgh, Lisbon, London
Total Physical Memory:     16,253 MB
Available Physical Memory: 2,700 MB
Virtual Memory: Max Size:  19,197 MB
Virtual Memory: Available: 5,140 MB
Virtual Memory: In Use:    14,057 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    <REDACTED>
Logon Server:              \\<REDACTED>
Hotfix(s):                 9 Hotfix(s) Installed.
                           [01]: KB2693643
                           [02]: KB4534132
                           [03]: KB4513661
                           [04]: KB4516115
                           [05]: KB4517245
                           [06]: KB4521863
                           [07]: KB4537759
                           [08]: KB4538674
                           [09]: KB4532693
Network Card(s):           5 NIC(s) Installed.
                           [01]: Mellanox ConnectX-3 Pro Ethernet Adapter
                                 Connection Name: Embedded LOM 1 Port 1
                                 DHCP Enabled:    Yes
                                 DHCP Server:     N/A
                                 IP address(es)
                           [02]: Mellanox ConnectX-3 Pro Ethernet Adapter
                                 Connection Name: Embedded LOM 1 Port 1 2
                                 DHCP Enabled:    Yes
                                 DHCP Server:     N/A
                                 IP address(es)
                           [03]: Mellanox Virtual Miniport Driver
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     N/A
                                 IP address(es)
                           [04]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (Default Switch)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 192.168.137.1
                           [05]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (crc)
                                 DHCP Enabled:    Yes
                                 DHCP Server:     11.0.65.70
                                 IP address(es)
                                 [01]: 11.14.133.95
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

### Steps to reproduce
CRC is configured with External Virtual Switch (crc) and cluster is started successfully

  1. Configure Proxy Wide on the Cluster with custom CA as detailed [here](https://docs.openshift.com/container-platform/4.2/networking/enable-cluster-wide-proxy.html)
  2. Create a new project "dv-project"
  3. Create secret to pull from registry
> oc create secret docker-registry dv-pull-secret \
>   --docker-server=registry.redhat.io \
>   --docker-username=CUSTOMER_PORTAL_USERNAME \
>   --docker-password=CUSTOMER_PORTAL_PASSWORD \
>   --docker-email=EMAIL_ADDRESS
> 
> oc secrets link builder dv-pull-secret
> oc secrets link builder dv-pull-secret --for=pull
> 
  4. Create a new project "dv-project" and install the Data Virtualization Operator from OperatorHub
  5. oc get pods -n dv-project
  6. oc describe pod <POD>

### Expected
The newly operator pod started successfully using the proxy configuration

### Actual
The newly operator pod failed to start with error in pulling image. "error pinging docker registry registry.redhat.io: Get https://registry.redhat.io/v2/: dial tcp: lookup registry.redhat.io on 10.88.0.8:53: no such host"

### Logs
Events:
  Type     Reason     Age                    From                         Message
  ----     ------     ----                   ----                         -------
  Normal   Scheduled  29m                    default-scheduler            Successfully assigned dv-project/dv-operator-6d664d649d-rtw8r to crc-q4zfq-master-0
  Normal   Pulling    27m (x4 over 29m)      kubelet, crc-q4zfq-master-0  Pulling image "registry.redhat.io/fuse7-tech-preview/dv-rhel7-operator:1.5"
  Warning  Failed     27m (x4 over 29m)      kubelet, crc-q4zfq-master-0  Failed to pull image "registry.redhat.io/fuse7-tech-preview/dv-rhel7-operator:1.5": rpc error: code = Unknown desc = error pinging docker registry registry.redhat.io: Get https://registry.redhat.io/v2/: dial tcp: lookup registry.redhat.io on 10.88.0.8:53: no such host
  Warning  Failed     27m (x4 over 29m)      kubelet, crc-q4zfq-master-0  Error: ErrImagePull
  Warning  Failed     24m (x21 over 29m)     kubelet, crc-q4zfq-master-0  Error: ImagePullBackOff
  Normal   BackOff    4m16s (x110 over 29m)  kubelet, crc-q4zfq-master-0  Back-off pulling image "registry.redhat.io/fuse7-tech-preview/dv-rhel7-operator:1.5"

Thanks

**Comment by gbraad** [comment]
It seems there is no possibility to communicate with the DNS?

> lookup registry.redhat.io on 10.88.0.8:53: no such host

can you use `oc debug` to verify the containers are able to perform DNS queries? also, is `10.88.0.8` the expected server?

**Comment by gbraad** [comment]
> CRC is configured with External Virtual Switch (crc) and cluster is started successfully

When running with the override vswitch `crc` you have to make sure your VM is able to communicate correctly. That CRC starts is not an indication that all works; as it only means that the local host can communicate with the VM and that the self-contained OpenShift cluster started (it does not need to pull images from the internet) so it is not a full proof check that all is OK. Please verify the VM settings for network.

If you need to override the nameserver, please use `crc start -n [dns]`

**Comment by praveenkumar** [comment]
Couple of things from the logs.

**Comment by gbraad** [comment]
> Windows 10 Pro 1909

Note: this is reported for Enterprise

> `OS Name:                   Microsoft Windows 10 Enterprise`

**Comment by yapnel** [comment]
Hi,

I believe the networking on the external virtual switch and crc's VM are configured correctly. Inside the guest VM, i am able to ping the proxy server in the host's network and also performed a 
> curl --proxy XXX https://www.google.co.uk

Similarly, inside the openshift-marketplace POD, i'm also able to perform a 
> curl https://www.google.co.uk

This indicates the proxy and custom CA configurations have been set correctly on the cluster.

I could not perform an oc debug because the container is failing to start due to the error. So, i can't get more logs from it.

I have tried editing the /etc/resolvf.conf in guest VM to only have nameserver 8.8.8.8 and tried installing the operator again and got the below error which is different to the one i report earlier "no such host"

> Failed to pull image "registry.redhat.io/fuse7-tech-preview/dv-rhel7-operator:1.5": rpc error: code = Unknown desc = error pinging docker registry registry.redhat.io: Get https://registry.redhat.io/v2/: dial tcp: lookup registry.redhat.io on 8.8.8.8:53: read udp 11.14.133.106:43554->8.8.8.8:53: i/o timeout


I am inside a corporate network that has a proxy server that governs all requests to the outside world. The internal DNS server does not have connection to the outside world. I would have thought all HTTP(s) requests will go through the Proxy server and the proxy will perform the DNS lookup. Is it not the case? If this is correct, then i wonder why CRC is doing the DNS lookup internally first even with proxy setup?

Thanks

**Comment by cfergeau** [comment]
> Similarly, inside the openshift-marketplace POD, i'm also able to perform a
> 
> > curl https://www.google.co.uk
> 
> This indicates the proxy and custom CA configurations have been set correctly on the cluster.

I'm actually a bit surprised by this as I had this issue today with the openshift-marketplace operator https://github.com/code-ready/crc/issues/1019
If needed, it might be useful to reset the proxy variables manually for the operator:
```
oc set env  deployment marketplace-operator -n openshift-marketplace HTTP_PROXY=xxx
```
and same for HTTPS_PROXY and NO_PROXY
For now you also need to add the internal cluster IPs to NO_PROXY manually.

**Comment by yapnel** [comment]
> > Similarly, inside the openshift-marketplace POD, i'm also able to perform a
> > > curl https://www.google.co.uk
> > 
> > 
> > This indicates the proxy and custom CA configurations have been set correctly on the cluster.
> 
> I'm actually a bit surprised by this as I had this issue today with the openshift-marketplace operator #1019
> If needed, it might be useful to reset the proxy variables manually for the operator:
> 
> ```
> oc set env  deployment marketplace-operator -n openshift-marketplace HTTP_PROXY=xxx
> ```
> 
> and same for HTTPS_PROXY and NO_PROXY
> For now you also need to add the internal cluster IPs to NO_PROXY manually.

I remember I had to set the proxy manually for the operator too. I have left out this info on my report. 

However, this doesn't solve my original problem.

**Comment by cfergeau** [comment]
There might be more bugs to iron out with proxy support, I wanted to check if I can reproduce your bug, but hit/fixed issue #1019 first.

**Comment by gbraad** [comment]
> Is it not the case? If this is correct, then i wonder why CRC is doing the DNS lookup internally first even with proxy setup?

It should. CRC is not doing the lookup, but likely some of the proxy settings aren't propogated to all the containers. One of the issues is `proxy-inject` as this is handled by the Cluster Version Operator, which in our usecase had to be disabled. We will look into this ...

**Comment by yapnel** [comment]
Is there a workaround for now? ie enabling proxy for the required container/pods?

**Comment by cfergeau** [comment]
There are probably possible workarounds, but there are not known yet, this is why it needs to be looked into.

**Comment by praveenkumar** [comment]
@yapnel I tried following steps on my setup when there is a custom CA for proxy, can you also try those steps and let us know if that work?

Note: Please make sure you are using the latest version of CRC - 1.6.0 (since those steps are tested with this)

1. Start the CRC with proxy setting, like you are doing and wait till is started.

```
$ crc config view
- http-proxy                            : http://x.x.x.x:3128
- https-proxy                           : http://x.x.x.x.x:3128
```

2. Create a user-ca-bundle.yaml resource as instructed by openshift docs https://docs.openshift.com/container-platform/4.3/networking/enable-cluster-wide-proxy.html#nw-proxy-configure-object_config-cluster-wide-proxy I have created following.

```
$ cat user-ca-bundle.yaml 
apiVersion: v1
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDzTCCArWgAwIBAgIUaMJ4iWwx6y6d9com/S57V8JcOqwwDQYJKoZIhvcNAQEL
    BQAwdjELMAkGA1UEBhMCSU4xCzAJBgNVBAgMAk1IMQswCQYDVQQHDAJQVTEPMA0G
    A1UECgwGUmVkaGF0MQwwCgYDVQQLDANkZXYxCzAJBgNVBAMMAnBrMSEwHwYJKoZI
    hvcNAQkBFhJwcmt1bWFyQHJlZGhhdC5jb20wHhcNMjAwMjIwMDk0NzU1WhcNMjEw
    MjE5MDk0NzU1WjB2MQswCQYDVQQGEwJJTjELMAkGA1UECAwCTUgxCzAJBgNVBAcM
    AlBVMQ8wDQYDVQQKDAZSZWRoYXQxDDAKBgNVBAsMA2RldjELMAkGA1UEAwwCcGsx
    ITAfBgkqhkiG9w0BCQEWEnBya3VtYXJAcmVkaGF0LmNvbTCCASIwDQYJKoZIhvcN
    AQEBBQADggEPADCCAQoCggEBANXGJNkgmamxba5+i14BC+KsZdA6DqSzETKiWtt6
    MhgaMdsDQJUB6DOL3mFahTWHr1cbYfLDWrpyCJJiVbWeGrv17zsXNnl1GG08FMYI
    tw4AP0b//wpsuUNxc5pszAFwkT7OyQEkHknHsq4LJES/Z4/ghi+afNX8/X/Cbb8/
    JC679VEZjyApYCPERKywL..
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: user-ca-bundle
  namespace: openshift-config
```

3. Apply the resource to cluster

```
$ oc apply user-ca-bundle.yaml
```

4. Check the status of operators (most of then will go to progressing state and the come back as available

```
$ oc get co
```

SSH to crc VM and add the custom cert to `/etc/pki/ca-trust/source/anchors/openshift-config-user-ca-bundle.crt` file and run update-ca-trust

```
<host> $ crc ip
<host> $ ssh -i C:\Temp\.crc\machines\crc\id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null core@<crc-ip>
[core@crc-xxx-master-0 ~]$ sudo vi /etc/pki/ca-trust/source/anchors/openshift-config-user-ca-bundle.crt
[core@crc-xxx-master-0 ~]$ sudo update-ca-trust
[core@crc-xxx-master-0 ~]$ sudo systemctl restart crio
[core@crc-xxx-master-0 ~]$ sudo systemctl restart kubelet
```

Exit from the crc VM and then start you deployment steps.

**Comment by yapnel** [comment]
Hi

I have tried the steps you have provided and i'm still facing the same error message. I dont think it is a certificate issue here. It is related to this issue
[https://github.com/code-ready/crc/issues/1025]( #1025) raised.

Thanks,

**Comment by cfergeau** [comment]
When you say same error message, do you mean `  Warning  Failed     27m (x4 over 29m)      kubelet, crc-q4zfq-master-0  Failed to pull image "registry.redhat.io/fuse7-tech-preview/dv-rhel7-operator:1.5": rpc error: code = Unknown desc = error pinging docker registry registry.redhat.io: Get https://registry.redhat.io/v2/: dial tcp: lookup registry.redhat.io on 10.88.0.8:53: no such host` ? or another one?

**Comment by yapnel** [comment]
Same as the one you have posted

**Comment by yapnel** [comment]
The below error, would you know it is thrown by CRC or OpenShift? 

`error pinging docker registry registry.redhat.io: Get https://registry.redhat.io/v2/: dial tcp: lookup registry.redhat.io on 10.88.0.8:53: no such host`

**Comment by cfergeau** [comment]
It's most likely openshift, but proxy support in crc is still being refined, https://github.com/code-ready/crc/pull/1038 + the CA configuration documented by Praveen in this issue.

**Comment by yapnel** [comment]
Saw your comments on your PR for #1038. If I were to manually add the proxy for these PODs as a workaround, will it resolve the no host error? Or my specific error needs to be address in OpenShift instead? Thanks

**Comment by cfergeau** [comment]
> Saw your comments on your PR for #1038. If I were to manually add the proxy for these PODs as a workaround, will it resolve the no host error?

Maybe, worth trying.

**Comment by yapnel** [comment]
Hi - any update on a resolution for this error please?

**Comment by yapnel** [comment]
Reinstalled with the latest CRC 1.6 and used "default" switch and added the custom cert to /etc/pki/ca-trust/source/anchors/ seemed to have resolved the issue. 

This was different to my original setup on the switch using "external". Adding the custom CA to the VM also made a difference and suspect crio and kubelet didn't inherit the custom wide proxy setting with custom CA in OpenShift.
