### ISSUE TITLE
Split tray setup checks into individual checks

### ISSUE THREAD

**Issue by anjannath** [code-ready/crc#1022]
Right now different checks related to the tray are invoked as one unit, this issue is to decompose those into more fine grained individual checks like all other preflight checks/setups.

https://github.com/code-ready/crc/blob/8674e345a7f843aa01803fc261a2d7b6539bec37/pkg/crc/preflight/preflight_check_tray_darwin.go#L81-L99

**Comment by gbraad** [comment]
... and maybe a separate file / subset also ?

**Comment by anjannath** [comment]
Fived in #1029
