### ISSUE TITLE
ERRO Error creating host: Error creating new host: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s

### ISSUE THREAD

**Issue by mouadsaleh** [code-ready/crc#1040]
### General information

  * OS: macOS Catalina
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
# Put the output of `crc version`
crc version: 1.6.0+8ef676f
OpenShift version: 4.3.0 (embedded in binary)
```
  
## CRC status
```bash
# Put the output of `crc status`
Machine 'crc' does not exist. Use 'crc start' to create it.
```

## CRC config
```bash
# Put the output of `crc config view`
nothing is displayed
```

## Host Operating System
```bash
# put the output of `sw_vers` in case of Mac
ProductName:	Mac OS X
ProductVersion:	10.15.1
BuildVersion:	19B88
```
### Steps to reproduce

  1. crc setup
  2. crc start 
  3. crc start -p development/DevOps/openshift/pull-secret.txt --log-level=debug

### Expected
crc starts

### Actual
crc fails to start

### Logs
$ crc start -p pull-secret.txt --log-level debug
DEBU Unable to find out if a new version is available: Get https://mirror.openshift.com/pub/openshift-v4/clients/crc/latest/release-info.json: dial tcp: lookup mirror.openshift.com on [::1]:53: read udp [::1]:64950->[::1]:53: read: connection refused
INFO Checking if oc binary is cached
DEBU oc binary already cached
INFO Checking if running as non-root
INFO Checking if HyperKit is installed
DEBU Checking if hyperkit is installed
INFO Checking if crc-driver-hyperkit is installed
DEBU Checking if crc-driver-hyperkit is installed
DEBU Running '/Users/msaleh/.crc/bin/crc-driver-hyperkit version'
DEBU crc-driver-hyperkit is already installed in /Users/msaleh/.crc/bin/crc-driver-hyperkit
INFO Checking file permissions for /etc/resolver/testing
INFO Checking file permissions for /etc/hosts
Checking file: /Users/msaleh/.crc/machines/crc/.crc-exist
INFO Extracting bundle: crc_hyperkit_4.3.0.crcbundle ...
DEBU Uncompressing /Users/msaleh/.crc/cache/crc_hyperkit_4.3.0.crcbundle to /Users/msaleh/.crc/cache
INFO Creating CodeReady Containers VM for OpenShift 4.3.0...
Found binary path at /Users/msaleh/.crc/bin/crc-driver-hyperkit
Launching plugin server for driver hyperkit
ERRO Error creating host: Error creating new host: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s

**Comment by gbraad** [comment]
> mirror.openshift.com on [::1]:53: read udp [::1]:64950->[::1]:53: read: connection refused
> Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s

Please check your network setup. You are likely not able to connect properly. Are you running a VPN, anitivirus software or other network tools?

**Comment by mouadsaleh** [comment]
Thanks for the quick response, I'm not running a VPN or a network tool that I'm aware of. I do have "Endpoint Security for Mac" running but I'm not sure how to check if that is what's blocking crc from connecting. Do you have any suggestions on how trouble shoot that ?

**Comment by gbraad** [comment]
it likely does. Is there a way to disable this temporarily?

**Comment by mouadsaleh** [comment]
I will not be able to disable it , but I will try to setup crc on a different machine. Thank you!
