### ISSUE TITLE
'crc status' should show OpenShift's status as "Starting" instead of "Stopped"

### ISSUE THREAD

**Issue by dharmit** [code-ready/crc#1041]
When starting CRC, the OpenShift web console is available pretty soon but doing `crc status` shows that OpenShift is "Stopped". After a few minutes, it turns to "Running". The "Stopped" status is apparently because few Operators are still starting up while rest of the bits have started.

It would be helpful if the status of OpenShift shows as "Starting" or something other than "Stopped" so that it doesn't get misinterpreted by the end-user.

```sh
❯ crc status
CRC VM:          Running
OpenShift:       Stopped    <------   why is this "Stopped"?
Disk Usage:      10.11GB of 32.2GB (Inside the CRC VM)
Cache Usage:     22.99GB
Cache Directory: /home/dshah/.crc/cache

❯ crc version
crc version: 1.5.0+e1c8fb8
OpenShift version: 4.2.14 (embedded in binary)
```

**Comment by cfergeau** [comment]
This should be fixed by https://github.com/code-ready/crc/commit/960a6a2909ac9b187e6d8ac533cc27f5dd0a0a02

**Comment by karthik101** [comment]
What does it mean its fixed? do we need to download new crc version? Is there no alternate fix ?

**Comment by cfergeau** [comment]
Yes you'd need a newer crc version to benefit from that fix.
