### ISSUE TITLE
How to transfer and share the CRC deployment among multiple people

### ISSUE THREAD

**Issue by morningspace** [code-ready/crc#1043]
### General information

This is a general question applies to all supported OSes, Hypervisors.

### Steps to reproduce

I launched CRC and installed my applications on top of it

### Expected

I'd like to share my CRC image w/ other people, so that they don't have to relaunch the CRC from scratch and install the applications by themselves. The only thing they need to do is to run `crc start`, then wait for a while when all applications along w/ OCP up and running.

What I did so far is to manually copy the folder `machines/crc`, especially the `crc` image, `id_rsa` and `id_rsa.pub`, probably needs some stuff in `cache` folder (I forgot), w/ some tricks.

My question is:
* What's the best practice from CRC, e.g. probably documented?
* How CRC could support this more nicely?

**Comment by gbraad** [comment]
we currently have nothing in place for this, but it would be exactly as described; the folder `~/.crc/machines/crc` contains all you would need to distribute. the keys in cache are the initial keys and they should have ben replaced with a machine specific one.

**Comment by gbraad** [comment]
it could be possible to generate a new bundle from this directory and then use this again with the `-b` option to import it into a system. this way the machine could have the key replaced to be a user specific one again. Does not sound like a bad idea ...

**Comment by praveenkumar** [comment]
Is it because of large number of image? Does it help with image caching feature?

**Comment by morningspace** [comment]
@praveenkumar @gbraad 

> Does it help with image caching feature?

Not sure what you mean, but ... I'd think it's a nice scenario can broaden the CRC use. Since CRC is based on VM, naturally it gains the benefit as a sharable image w/ pre-installed user applications w/o need to re-install the whole staff in a new place. 

I don't know how CRC could assist in this scenario from code level to make it more easily, e.g. wrap as command such as, `crc export/import <image_file>`, or, it could be documented and highlighted as best practices, so people clearly know how to achieve it.

**Comment by gbraad** [comment]
usually people consider config as code, meaning that an application gets deployed according to a config or setup scripts. To accomodate a fast delivery we had an image caching feature that could help to prepopulate container images inside the VM (minishift). In that case the whole setup could be contained in a script and/or zip to pull and import images and then deploy the application. Would this work?

What you describe is a prepped customized image, such as a base image to continue work on, but with container images and configured application.

The second option is now skmpler, and possible if you just copy the directory over. You could try to create an imagebundle if you add the metadata as described in the snc repo. Note: does not a bundle override now. For now, and export/import does not exist.

**Comment by cfergeau** [comment]
> You could try to create an imagebundle if you add the metadata as described in the snc repo

We expect the disk image in the bundle to initially start with the kubelet service disabled, to not have a pull secret nor a cluster id, and `crc` configures all of this when creating a VM from the bundle. I don't know how well `crc` will behave if provided with a bundle where all of this is already set (in other words, testing and maybe fixes are needed if we want to offer such a possibility)

**Comment by gbraad** [comment]
> to not have a pull secret nor a cluster id, and crc configures all of this when creating a VM from the bundle

This would be replaced. But if somehow would do this internally, this would be the same as them sharing the pullsecret in a file. it is not something we can control, but only address.

**Comment by morningspace** [comment]
@gbraad I can understand your point to config as code:-) On the other hand, to accomodate a fast delivery is exactly what we need, which is also what a VM image naturally could provide. Actually, I'd think what we are trying to do w/ the software we are gonna deliver in form of a VM is quite a bit similar to what CRC is doing w/ OCP. It's just we are not starting from scratch, but instead, from CRC, because CRC has OCP embedded and our software needs to be run on top of OCP.

Regarding pullsecrect sharing, I see the situation, but I don't understand what the "replace" here means.

**Comment by gbraad** [comment]
On startup we replace certain values, like pullsecret, clusterid and ssh key.

**Comment by morningspace** [comment]
There's one more question. When I try to launch the image copied from another machine, what I did is that:
1) Install crc on machine A
2) Run `crc setup` but do not run `crc start`
3) Copy `~/.crc/machines/crc` and `~/.crc/cache` from machine B to machine A
4) Try to run `crc start` to launch the copied image

It will fail and report an error that can not find machine `crc`.

The right way to resolve this issue, is when on step 2), run `crc start` after `crc setup`, then run `crc stop`.

I know that there's something needs to be created first, before I have to use the copied image. But it will spend more time to launch it because I have to start and stop crc back and forth.

Any idea how can optimize/improve it? @gbraad @praveenkumar @cfergeau

**Comment by cfergeau** [comment]
you could `virsh -c qemu:///system dumpxml crc >crc.xml` on one end, and `virsh -c qemu:///system define crc.xml` on the other end, and potentially do the same with `net-dumpxml` and `net-define`, but this is starting to become very dependant on internal implementation details of crc...

**Comment by gbraad** [comment]
A possible bundle export or script that can help with generating metadata, archive, etc? Which results in a shareable .crcbundle, ... i could imagine this can bd useful in prepping for use in CI/CD

**Comment by morningspace** [comment]
> A possible bundle export or script that can help with generating metadata, archive, etc? Which results in a shareable .crcbundle

This is exactly what we need!

**Comment by gbraad** [comment]
I believe the focus should be on tooling to create the snc in a more efficient/convenient way. This might be reused for handling an image deployed with crc, but I do not believe this should be part of the generic command line tool
