### ISSUE TITLE
Fish Shell not supported for "crc oc-env" (macOS/Darwin)

### ISSUE THREAD

**Issue by mojoTX** [code-ready/crc#1047]
### General information

  * OS: macOS
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it (Yes/No)?   **YES**

## CRC version
```bash
crc version: 1.6.0+8ef676f
OpenShift version: 4.3.0 (embedded in binary)
```
  
## CRC status
```bash
CRC VM:          Running
OpenShift:       Running (v4.3.0)
Disk Usage:      9.122GB of 32.72GB (Inside the CRC VM)
Cache Usage:     10.73GB
Cache Directory: /Users/mjarvis/.crc/cache
```

## CRC config
_(empty)_

## Host Operating System
```bash
ProductName:	Mac OS X
ProductVersion:	10.15.3
BuildVersion:	19D76
```

### Steps to reproduce

  1. Install [fish shell](https://fishshell.com), e.g., `brew install fish`
  2. Run `crc oc-env`
  3. Roll eyes when bash is assumed 🙂
  4. 

### Expected

Something like this:
```fish
contains $HOME/.crc/bin $fish_user_paths; or set -U fish_user_paths $HOME/.crc/bin $fish_user_paths
# Run this command to configure your shell:
# eval (crc oc-env)
```

### Actual
```bash
export PATH="/Users/mjarvis/.crc/bin:$PATH"
# Run this command to configure your shell:
# eval $(crc oc-env)
```

### Logs

Logs not applicable

**Comment by gbraad** [comment]
We usually don't add support for a shell, as it would need testing and integration on our end. However, you provided a patch and since it is not part of a critical path I think this is OK ;-), but you would need to ensure this works as expected.

**Comment by mojoTX** [comment]
Thank you! Yes, this change should only affect people using the [fish shell](https://github.com/fish-shell/fish-shell), and it's only offering a suggestion on how to add the directory to their path, so thank you! I referenced the issue number in the commits.

**Comment by gbraad** [comment]
Merged! Thank you ... :-D
