### ISSUE TITLE
[BUG] CRC 1.6 fail to start with "Wrapper Docker Machine process exiting due to closed plugin server (unexpected EOF)"

### ISSUE THREAD

**Issue by jmazzitelli** [code-ready/crc#1052]
### General information

  * OS: Linux / macOS / Windows

RHEL 7.6

  * Hypervisor: KVM / Hyper-V / hyperkit

libvirt

  * Did you run `crc setup` before starting it (Yes/No)?

yes

## CRC version
```bash
$ crc version
crc version: 1.6.0+8ef676f
OpenShift version: 4.3.0 (embedded in binary)
```
  
## CRC status
```bash
$ crc status
Machine 'crc' does not exist. Use 'crc start' to create it.
```

## CRC config
```bash
There is no output of "crc config view"
```

## Host Operating System
```bash
 cat /etc/os-release 
NAME="Red Hat Enterprise Linux Workstation"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Workstation"
VARIANT_ID="workstation"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Workstation 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:workstation"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"
```

### Steps to reproduce

Run crc setup and then start and I get the error.

### Expected

CRC to start.

### Actual

ERRO Error creating host: Error creating the VM: Error creating machine: Error in driver during machine creation: unexpected EOF 

### Logs

https://gist.github.com/jmazzitelli/c6591e74a8d4085b34da2fb2c0dc0e3a

**Comment by jpkrohling** [comment]
Same happened to me on Fedora 31 with the latest updates as of yesterday.

**Comment by jmazzitelli** [comment]
This error does not happen on 1.5.0. So this is a problem that was introduced in 1.6.0.

**Comment by jmazzitelli** [comment]
I got 1.6.0 to start up. I think the missing piece was I think I had an older VM still in existence that CRC was trying to reuse.

If you have this problem, go in virt-manager and make sure you destroy any older CRC VMs.

I also deleted all content under $HOME/.crc (but I did that before and still got the error - I think its the old VM was the problem).
