### ISSUE TITLE
[BUG] Set `admin` context before using the kubeconfig to interact with cluster

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#1060]
Recently we found out if a user by mistake do following then our kubeconfig which is part of the bundle gets different context and also current context set to a different cluster.

```
$ export KUBECONFIG=~/.crc/cache/<bundle>/kubeconfig
$ run kind <= way to deploy a single cluster
-- Check the contexts of the kubeconfig file --
$ oc config get-contexts  --kubeconfig ~/.crc/cache/<bundle>/kubeconfig
CURRENT   NAME                                      CLUSTER                AUTHINFO                          NAMESPACE
          admin                                     crc                    admin                             
          default/api-crc-testing:6443/kube:admin   api-crc-testing:6443   kube:admin/api-crc-testing:6443   default
*         kind-kind                                 kind-kind              kind-kind        
```

With this if a user now run the crc cluster then he might get something following
```
Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"kubernetes\")"
```

As part of CRC we should always set the current context as `admin` even there is no other app consumed this kubeconfig to make sure it will not break.

**Comment by cfergeau** [comment]
Fixed by https://github.com/code-ready/crc/commit/f91d978eb2a225a8cd70baddd75f3f7ea5a8b2ca

**Comment by priyankakhetawat** [comment]
while running
crc start  facing the same issue
DEBU retry loop: attempt 11 out of 80
DEBU Running 'C:\Users\pkhetawat\.crc\bin\oc\oc.exe get csr --kubeconfig C:\Users\pkhetawat\.crc\machines\crc\kubeconfig --context admin --cluster crc'
DEBU Command failed: exit status 1
DEBU stdout:
DEBU stderr: Unable to connect to the server: dial tcp: lookup api.crc.testing: no such host
DEBU Unable to connect to the server: dial tcp: lookup api.crc.testing: no such host
DEBU error: Temporary Error: exit status 1 - sleeping 1s

windows version10 18363
