### ISSUE TITLE
Split out bundle identifiers to platform specific files

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#1061]
https://github.com/code-ready/crc/blob/3ba6f260e5276c814077706fde0789bc238ecfbf/pkg/crc/constants/constants.go#L51-L55

Unnecessary selection logic is introduced with a `map` and `runtime.GOOS` to select the correct name. this can be solved by moving the names into the `_linux.go`, etc files and use accordingly without the `ForOS` suffix.

**Comment by cfergeau** [comment]
No, this was intentionnally changed in d2aded2aac when adding the `crc-embedder` binary which usually runs on linux, but needs to generate binaries with embedded bundles for all 3 platforms.

**Comment by gbraad** [comment]
but I am not understanding why this needs to be solved in this fashion.
There is no comment to explain why the use of GOOS to choose this is needed, as this is now also used for the podman-remote embedding

**Comment by gbraad** [comment]
In reference to `podman-remote`: https://github.com/code-ready/crc/pull/1001/files/f18f02e4929eb587d584090df29314f7c30700c5#diff-ba68ecc1eb2378a0955ade767ee5c58cR52

**Comment by cfergeau** [comment]
We want a binary which will run on a single platform, and which ill generate binaries with embedded bundles for all 3 platforms (linux, windows, macos). This binary built for a single platform will thus need to know the bundle names for linux, windows and macos. It's also better if we don't need to duplicate the same constant in multiple places. We could probably instead use constants named `defaultBundleLinux`, `defaultBundleMacos` in a file which always gets built, and then a per-platform `GetDefaultBundle` which directly returns the right constant, and move the map to `crc-embedder` code if that feels better.

crc-embedder will also need to know the name of the podman binary for all 3 platforms when built on a single platform, so a similar approach is needed for it too.

**Comment by gbraad** [comment]
to be discussed later... needed changes for the embedder sound acceptable

**Comment by cfergeau** [comment]
One way around this is https://github.com/cfergeau/crc/commit/340b723161ceaebf5d1e4325e4fadad056fabd0b but this is quite a lot of changes for not much gain imo :)

**Comment by gbraad** [comment]
The gain is in the general codebase and moving this logic to the embedder.
