### ISSUE TITLE
CRC fails with unable to connect to api.crc.testing:6443

### ISSUE THREAD

**Issue by pthopa** [code-ready/crc#1065]
### General information

  * OS: Linux
  * Hypervisor: KVM 
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
# Put the output of `crc version`
crc version: 1.6.0+8ef676f
Openshift version: 4.3.0 (embedded in binary)
```
  
## CRC status
```bash
# Put the output of `crc status`
ERRO The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port?
```

## CRC config
```bash
# Put the output of `crc config view`
this command did not generate any output
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```RHEL 7.7 (Maipo)

### Steps to reproduce

  1. Did a new setup and install of crc. Did crc delete, crc setup and crc start. Everything seemed to work fine. Deployed a mongo image. Then suddenly i started getting the unable to connect to api.crc.testing:6443 errors. 

  2. I tried stopping and starting crc. But still getting the connection errors.
  3.  Sometimes when i run "crc status"  instead of the "unable to connect to api.crc.testing:6443", i see
CRC VM: Running
Openshift: Stopped
 Disk Usage: 10.08GB of 32.7 GB (Inside the CRC VM)
Cache Usage (10.57GB)
CacheDirectory:  /home/.crc/cache



### Expected


### Actual


### Logs

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by cfergeau** [comment]
This could be the VM not having enough memory for a mongodb deployment and being very slow.
Could you try to login as an admin with `oc` (instructions at the end of crc start), and then run `oc get co`?
Output of `crc start --log-level debug` could be useful too.

**Comment by pthopa** [comment]
Thanks @cfergeau ...  based on your comment,  i re-installed crc this time explicitly setting memory to 8G ( crc config set memory 8192) before doing a crc setup and crc start..  and this seems to make things more stable.. things seem to be fine so far

**Comment by cfergeau** [comment]
That's surprising, as 8G is the default memory size for crc, so it should not have made a difference :)

**Comment by pthopa** [comment]
interesting... things still seem to be fine after a couple of days.. havent run into any issues so far.. when i get an opportunity i will try reinstalling without setting the crc config and see if the problem recurs..

**Comment by gbraad** [comment]
> and this seems to make things more stable

> 8G is the default memory size

marking as invalid. Likely issues with `dnsmasq` or something else. however this can't be verified now... user reports `things still seem to be fine after a couple of days.` so I assume a reboot might have done the trick.
