### ISSUE TITLE
The image address and accessing crc from a remote machine

### ISSUE THREAD

**Issue by jeffsaremi** [code-ready/crc#1080]
### General information

  * OS: Windows
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
crc version: 1.6.0+8ef676f
OpenShift version: 4.3.0 (embedded in binary)
```
  
## CRC status
```bash
CRC VM:          Stopped
OpenShift:       Stopped
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     12.69GB
```

Question:
I am running CRC on a Windows machine
I am running oc on a ubuntu machine connecting to the Windows machine.
When I try to deploy a pod, where does the image url is referenced from? the oc client on Ubuntu? or the api server on the Windows machine?
For example:
```
  image: localhost:5000/repo_name/image_name:tag
```

**Comment by praveenkumar** [comment]
```
 image: localhost:5000/repo_name/image_name:tag
```

@jeffsaremi Is it a local registry which you run or something different, your pod is going to deploy on the same machine where crc is running so every bits going to happen there, your ubuntu machine just have a client binary which connect to running cluster on windows.

**Comment by gbraad** [comment]
See #705. This is however not the generic development usecase we support as this needs modifications to allow 'remote' access. This also introduces issues with security.

**Comment by gbraad** [comment]
I would call this invalid, as the `localhost` here refers to the OpenShift registry on the VM. @praveenkumar WDYT, close and label as such?

**Comment by praveenkumar** [comment]
yes I am going to close it since it nothing to do with CRC atm.
