### ISSUE TITLE
OS specific code could be moved to `pkg/os/...`; launchd

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#1082]
https://github.com/code-ready/crc/blob/8da5f70de857fbf1d94395bbc765359c1a5fab99/pkg/launchd/launchd.go#L1

**Comment by praveenkumar** [comment]
Or add the build tag for `darwin` on top of this file?

**Comment by gbraad** [comment]
... and/or name the file accordingly to the platform: `launchd_darwin.go`
