### ISSUE TITLE
[Epic] VPN support

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#1087]

**Comment by jlynchMicron** [comment]
@gbraad is this a coming fix for crc in the future?  I have cisco anyconnect installed by my company that I cannot disable, and I think it is causing me issues during "crc start" similar to this issue https://github.com/code-ready/crc/issues/908

**Comment by gbraad** [comment]
No timeframe is given as issues are encountered while implementing

**Comment by gbraad** [comment]
Planned to be reviewed again.

**Comment by gbraad** [comment]
@guillaumerose Do you have any suggestions on how to tackle this?

**Comment by guillaumerose** [comment]
Docker Desktop solves this by using vpnkit.

vpnkit runs as user on the host and connects to a small daemon inside the VM using named pipes/vsock. The daemon in the VM is in fact a tap interface. The daemon transfers all the traffic to vpnkit so that vpnkit handles all the traffic as the user. 

In this architecture, vpnkit is a client because of issue with vsock on older version of Windows. It could be reversed now.

**Comment by guillaumerose** [comment]
I started an experiment in https://github.com/guillaumerose/gvisor-tap-vsock. It reproduces vpnkit without ocaml code. For the moment, it's more a toolkit to solve the VPN issue than the solution itself.

**Comment by gbraad** [comment]
We should break down work in new tasks as the spike has concluded.

**Comment by guillaumerose** [comment]
https://github.com/code-ready/snc/pull/234 addresses the first two points.
For the 4th point, the host part is part of the daemon and the config to enable it is `network-mode=vsock`  https://github.com/code-ready/crc/pull/1526

**Comment by gbraad** [comment]
* https://github.com/code-ready/snc/pull/234
  * https://github.com/code-ready/crc/pull/1526
  * https://github.com/code-ready/machine/pull/43
  * https://github.com/code-ready/machine-driver-hyperkit/pull/20
  * https://github.com/code-ready/machine/pull/46

**Comment by guillaumerose** [comment]
First bits are in master branch. It can be used on the 3 platforms.

How to test it:
* cleanup everything, ~/.crc and hosts file
* `crc config set network-mode vsock`
* run `crc setup`
* run `crc daemon` in a second terminal
* run `crc start` as usual.

What is still missing:
* DNS records for apps created by user is not working. 
Workaround: manually add the dns record in the hosts file.
* Port forwarding is static. Only VM port 443, 22 (accessible through port 2222 on the host) and 6443 are reachable.
* Communication still happen between crc and his components using localhost and random ports.

**Comment by cfergeau** [comment]
> cleanup everything, ~/.crc and hosts file
which means `crc delete; crc cleanup; rm -rf ~/.crc`, and finally remove all `xxx.crc.testing` entries from `/etc/hosts`

**Comment by fasho** [comment]
bump

**Comment by gbraad** [comment]
@fasho why bump? Please look at https://github.com/code-ready/crc/wiki/VPN-support--with-an--userland-network-stack

**Comment by guillaumerose** [comment]
VPN support is available by default on macOS and Linux. 
It will be activated by default by the MSI on Windows in the next release. Until then, please refer to https://github.com/code-ready/crc/wiki/VPN-support--with-an--userland-network-stack 

Still, we are missing end-to-end tests for this.
