### ISSUE TITLE
Handle ca-cert for proxy and propagate to cluster

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#1088]
As of now we don't have any automated way to propagate the `ca-proxy` for the cluster and only manual document available https://github.com/code-ready/crc/issues/1014#issuecomment-589622267

**Comment by cfergeau** [comment]
Once we have the MCO enabled in 4.8, proxy integration should be much closer to regular OpenShift if I'm not mistaken?

**Comment by cfergeau** [comment]
This has been fixed by https://github.com/code-ready/crc/commit/2ac0901e70ac
