### ISSUE TITLE
[BUG] Networking anomalies when reaching out from the OC vm

### ISSUE THREAD

**Issue by jeffsaremi** [code-ready/crc#1091]
### General information

  * OS: Windows
  * Hypervisor: Hyper-V 
  * Did you run `crc setup` before starting it (Yes/No)?

## CRC version
```bash
crc version: 1.6.0+8ef676f
OpenShift version: 4.3.0 (embedded in binary)
```
  
## CRC status
```bash
# Put `crc status` output here
```

## CRC config
```bash
CRC VM:          Running
OpenShift:       Running (v4.3.0)
Disk Usage:      16.09GB of 106.8GB (Inside the CRC VM)
Cache Usage:     12.69GB
Cache Directory: C:\Users\jesaremi\.crc\cache
```

## Host Operating System
```bash
Host Name:                 JESAREMI-HP
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.18363 N/A Build 18363
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Product ID:                00330-80000-00000-AA800
Original Install Date:     7/30/2019, 11:45:53 AM
System Boot Time:          3/10/2020, 7:31:33 AM
System Manufacturer:       HP
System Model:              HP Z2 Tower G4 Workstation
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 10 GenuineIntel ~3192 Mhz
BIOS Version:              HP Q50 Ver. 01.05.04, 6/17/2019
Windows Directory:         C:\windows
System Directory:          C:\windows\system32
Boot Device:               \Device\HarddiskVolume4
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-08:00) Pacific Time (US & Canada)
Total Physical Memory:     65,387 MB
Available Physical Memory: 30,258 MB
Virtual Memory: Max Size:  75,115 MB
Virtual Memory: Available: 38,350 MB
Virtual Memory: In Use:    36,765 MB
Page File Location(s):     C:\pagefile.sys
Logon Server:              \\CY1-RED-DC-35
Hotfix(s):                 17 Hotfix(s) Installed.
                           [01]: KB4537572
                           [02]: KB4493478
                           [03]: KB4497727
                           [04]: KB4503308
                           [05]: KB4508433
                           [06]: KB4509096
                           [07]: KB4515383
                           [08]: KB4516115
                           [09]: KB4517245
                           [10]: KB4520390
                           [11]: KB4521863
                           [12]: KB4524569
                           [13]: KB4528759
                           [14]: KB4537759
                           [15]: KB4538674
                           [16]: KB4541338
                           [17]: KB4540673
Network Card(s):           2 NIC(s) Installed.
                           [01]: Intel(R) Ethernet Connection (7) I219-LM
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     10.221.228.18
                                 IP address(es)
                                 [01]: 10.91.90.45
                                 [02]: fe80::c835:f0c9:b01e:ef99
                                 [03]: 2001:4898:e0:bf:5cfa:1e1e:699e:7be
                                 [04]: 2001:4898:e0:bf:c835:f0c9:b01e:ef99
                           [02]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (Default Switch)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 192.168.142.177
                                 [02]: fe80::c95e:1cb9:7baa:9fe4
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```

### Steps to reproduce
oc cannot download any of our docker images
Resulting in image download backoff.
Tried to run this:

C:\temp>%SSH% "sh -c 'ping hlsaris.azurecr.io'"
Warning: Permanently added 'api.crc.testing,192.168.142.189' (ECDSA) to the list of known hosts.
ping: hlsaris.azurecr.io: Name or service not known

Where as if I run the same thing on the windows itself:
C:\temp>ping hlsaris.azurecr.io

Pinging r0225wus2.westus2.cloudapp.azure.com [40.78.250.102] with 32 bytes of data:

Another example:
C:\temp>%SSH% "sh -c 'ping www.microsoft.com'"
Warning: Permanently added 'api.crc.testing,192.168.142.189' (ECDSA) to the list of known hosts.
ping: www.microsoft.com: Name or service not known

From Windows:
C:\temp>ping www.microsoft.com

Pinging e13678.dspb.akamaiedge.net [2600:1409:a:38a::356e] with 32 bytes of data:

Let me know if you actually need the logs.

Additional Notes: I am using Default switch

**Comment by jeffsaremi** [comment]
It looks like the Vm does not have/inherit any nameserver information from the host

**Comment by gbraad** [comment]
This is a common problem with Hyper-V; it seems the host is not always passing the DNS information on (the guest resolves using a nameserver on the host).

you can provide the nameserver with `-n` / `-nameserver` when starting the cluster.

**Comment by jeffsaremi** [comment]
ok Thanks!

**Comment by gbraad** [comment]
did this resolve your issue?

**Comment by jeffsaremi** [comment]
Must I specify `-n address` on every invocation of `crc start`?
Or just the first time I'm creating the VM? Because it doesn't look like it remembers it
Admittedly I only checking after a crc stop/start
The /etc/resolv.conf shows no evidence of the nameserver I provided
Also it shows this address (10.88.0.8):
```
# Generated by CRC
search crc.testing
nameserver 10.88.0.8
nameserver 192.168.142.177
```
I have no idea where this comes from. Its not from my machine:

```
PS C:\Users\jesaremi> Get-DnsClientServerAddress

InterfaceAlias               Interface Address ServerAddresses
                             Index     Family
--------------               --------- ------- ---------------
Ethernet                            14 IPv4    {10.50.10.50, 10.50.50.50}
Ethernet                            14 IPv6    {}
Loopback Pseudo-Interface 1          1 IPv4    {}
Loopback Pseudo-Interface 1          1 IPv6    {fec0:0:0:ffff::1, fec0:0:0:ffff::2, fec0:0:0:ffff::3}
Teredo Tunneling Pseudo-I...         9 IPv4    {}
Teredo Tunneling Pseudo-I...         9 IPv6    {}
vEthernet (Default Switch)          18 IPv4    {192.168.142.179}
vEthernet (Default Switch)          18 IPv6    {}
```

Ultimately now that I have access to ssh I can add my entry to /etc/resolv.conf manually after each restart if that's my last resort

**Comment by praveenkumar** [comment]
> Must I specify -n address on every invocation of crc start?

@jeffsaremi you can use `crc config set nameserver <nameserver_ip>` so you don't need to specify as part of each `crc start`. 

> Or just the first time I'm creating the VM? Because it doesn't look like it remembers it
Admittedly I only checking after a crc stop/start
The /etc/resolv.conf shows no evidence of the nameserver I provided

It should work with `stop/start` scenario also, when you use `nameserver` parameter during the `start` you will also see something like `Adding <nameserver_ip> as nameserver to the instance ...` in the stdout.

**Comment by jeffsaremi** [comment]
I like that. I will use that the next time.
We can close this now.
