### ISSUE TITLE
How to debug DNS on macOS whe console not working

### ISSUE THREAD

**Issue by csantanapr** [code-ready/crc#1093]
### General information

  * OS: macOS 
```
uname -a
Darwin iMac.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
```
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Network using ethernet, Wifi turned off

## CRC version
```bash
crc version: 1.7.0+fa7e558
OpenShift version: 4.3.1 (embedded in binary)
```
  
## CRC status
```bash
CRC VM:          Running
OpenShift:       Running (v4.3.1)
Disk Usage:      14.35GB of 32.72GB (Inside the CRC VM)
Cache Usage:     12.46GB
Cache Directory: /Users/csantana23/.crc/cache
```

## CRC config
```bash
- cpus                                  : 6
- memory                                : 20480
```

## Host Operating System
```bash
sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.3
BuildVersion:	19D76
```
```bash
$ ls -l /etc/hosts
-rw-r--r--  1 csantana23  wheel  429 Mar 10 17:49 /etc/hosts

$ ls -l /etc/resolv.conf
-rw-r--r--  1 csantana23  wheel  360 Feb 28 18:21 /etc/resolv.conf

$ ls /etc/resolver/testing
/etc/resolver/testing
 ls -l /etc/resolver/testing
-rw-r--r--  1 csantana23  wheel  47 Dec 17 17:00 /etc/resolver/testing

$ cat /etc/resolver/testing
port 53
nameserver 192.168.64.27
search_order 1
```

### Steps to reproduce
  0. rm -rf ~/.crc
  1. crc setup
  2. crc config set cpus 6
  3. crc config set memory 2048
  4. crc start
  5. crc console
   

### Expected
Console and DNS working

### Actual
Console can't find host
```
curl https://console-openshift-console.apps-crc.testing -v
* Could not resolve host: console-openshift-console.apps-crc.testing
* Closing connection 0
curl: (6) Could not resolve host: console-openshift-console.apps-crc.testing
```

### Logs
```
INFO Checking if oc binary is cached
INFO Checking if podman remote binary is cached
INFO Checking if running as non-root
INFO Checking if HyperKit is installed
INFO Checking if crc-driver-hyperkit is installed
INFO Checking file permissions for /etc/resolver/testing
INFO Checking file permissions for /etc/hosts
INFO Starting CodeReady Containers VM for OpenShift 4.3.1...
INFO Verifying validity of the cluster certificates ...
INFO Network restart not needed
INFO Check internal and public DNS query ...
INFO Check DNS query from host ...
INFO Starting OpenShift cluster ... [waiting 3m]
INFO
INFO To access the cluster, first set up your environment by following 'crc oc-env' instructions
INFO Then you can access it by running 'oc login -u developer -p developer https://api.crc.testing:6443'
INFO To login as an admin, run 'oc login -u kubeadmin -p db9Dr-J2csc-8oP78-9sbmf https://api.crc.testing:6443'
INFO
INFO You can now run 'crc console' and use these credentials to access the OpenShift web console
Started the OpenShift cluster
WARN The cluster might report a degraded or error state. This is expected since several operators have been disabled to lower the resource usage. For more information, please consult the documentation
```

You can start crc with  to collect logs.

output of crc start with debug `crc start --log-level debug`
https://gist.github.com/csantanapr/d7b802baa75dc26a2ffb6f40ca512929

output of running `scutil --dns`
https://gist.github.com/csantanapr/6635f20f9963a648fad31f916d93f036

**Comment by csantanapr** [comment]
Any guidance or docs on how is this dnsmasq suppose to work, how to debug, or how to restart the dns service to make it work.

**Comment by csantanapr** [comment]
After restarting the computer twice. when it comes up VM is stopped.
Then I do `crc start` again and this time it works. 🤷‍♂ 

I would like to know how is this dns is suppose to work, so we can document and maybe provide debug steps like restarting a service on the OS vs. asking to restart the whole computer.

**Comment by gbraad** [comment]
This is likely due to how `/etc./resolver/` works. Sometimes a network restart is needed ...

**Comment by praveenkumar** [comment]
@csantanapr if you want to make sure that the dnsmasq running in the VM is working as expected or not you can use `dig console-openshift-console.apps-crc.testing @<CRC_VM_IP>`, if that works which means the issue is from host resolver side you can try to restart the Network and see if that resolve it on the host since some time resolver take effect only after restarting the network.

**Comment by csantanapr** [comment]
Hi @praveenkumar 
Thanks for the tips, I would like to add this info to the docs. 

How can I restart the network you are mentioning using the terminal to be automated ?

**Comment by cfergeau** [comment]
https://code-ready.github.io/crc/#dns-configuration-mac_gsg has a short description of the network setup expected by crc. We could expand it to mention the dnsmasq container running in the VM.
Regarding `/etc/resolver`, edit a file in this directory with sudo, or `sudo touch /etc/resolver/foo && rm /etc/resolver/foo` should trigger a reload of this directory's content. However, seeing `scutil` output, `/etc/resolver` seems to have been reloaded just fine:
```
resolver #8
  domain   : testing
  nameserver[0] : 192.168.64.27
  port     : 53
  flags    : Request A records
  reach    : 0x00000002 (Reachable)
  order    : 1
```

**Comment by csantanapr** [comment]
Hi @cfergeau 
I saw the docs section  https://code-ready.github.io/crc/#dns-configuration-mac_gsg

But it help me understand what are files suppose todo or what content should be in them, or any command to help debug or reset. 

As you said the output of scutil looked correct but still it was not working this is why is frustrating.

**Comment by csantanapr** [comment]
Now I can recreate the problem regularly. 

Having the VM in a tuning state with 6 cpus and 2048GB mem. 

Then do:
crc stop
crc delete
crc start

The VM DNS doesn’t work

**Comment by cfergeau** [comment]
> But it help me understand what are files suppose todo or what content should be in them, or any command to help debug or reset.

`crc setup` should be all that is needed to set things up ;) The only 2 things that will be changed is `/etc/resolver/testing` and `/etc/hosts` as explained in the documentation. As for their content, `crc setup` will ensure it's correct.
Did you try the command Praveen gave `dig console-openshift-console.apps-crc.testing @<CRC_VM_IP>` ? I would also experiment with `ping console-openshift-console.apps-crc.testing`

**Comment by csantanapr** [comment]
It happened again, here is the output of the recommended commands
console is not working or apps for console-openshift-console.apps-crc.testing

```
dig console-openshift-console.apps-crc.testing $(crc ip)

; <<>> DiG 9.10.6 <<>> console-openshift-console.apps-crc.testing 192.168.64.27
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 53647
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;console-openshift-console.apps-crc.testing. IN A

;; AUTHORITY SECTION:
.			10800	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2020031102 1800 900 604800 86400

;; Query time: 41 msec
;; SERVER: 192.168.1.254#53(192.168.1.254)
;; WHEN: Wed Mar 11 23:13:33 EDT 2020
;; MSG SIZE  rcvd: 146

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 21482
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;192.168.64.27.			IN	A

;; AUTHORITY SECTION:
.			10800	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2020031102 1800 900 604800 86400

;; Query time: 41 msec
;; SERVER: 192.168.1.254#53(192.168.1.254)
;; WHEN: Wed Mar 11 23:13:33 EDT 2020
;; MSG SIZE  rcvd: 117
```

```
 ping console-openshift-console.apps-crc.testing
ping: cannot resolve console-openshift-console.apps-crc.testing: Unknown host
```

What are the next steps to resolve or debug?

**Comment by praveenkumar** [comment]
@csantanapr you need to use `dig console-openshift-console.apps-crc.testing @192.168.64.27`, here `@` is required to make sure you are going to use the `crc ip` as nameserver. Also did you try to just restart the network (if you are using wifi, try turn off-on, same with wired one) ?

**Comment by csantanapr** [comment]
My bad @praveenkumar 

Here I ran with `@`
```bash
dig console-openshift-console.apps-crc.testing @$(crc ip)
```

How do I read the output, what's wrong, any clues in this output?

```
; <<>> DiG 9.10.6 <<>> console-openshift-console.apps-crc.testing @192.168.64.27
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13176
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;console-openshift-console.apps-crc.testing. IN A

;; ANSWER SECTION:
console-openshift-console.apps-crc.testing. 0 IN A 192.168.64.27

;; Query time: 0 msec
;; SERVER: 192.168.64.27#53(192.168.64.27)
;; WHEN: Thu Mar 12 08:16:04 EDT 2020
;; MSG SIZE  rcvd: 76
```
Do you know of a CLI command in the terminal I can restart the ethernet network?

@praveenkumar I'm using ethernet, Asking the end user to restart the network every time there is a problem with DNS with CRC is a not very good user experience.

If using dnsmaq is not reliable maybe the root cause?
Maybe we can look for an alternative more robust?

What about if I edit `/etc/resolv.conf` and add the VM ip $(crc ip) at the top of first option for DNS server, then the second one my external default like 8.8.8.8

Maybe I can have a script that takes the current value of DNS servers, and configures the DNS Server inside the CRC VM to forward to them.

just brain storming if there is no way to debug or make dnsmaq better in macOS

**Comment by csantanapr** [comment]
I can't restart network every time, I might be in the middle of something like a remote call, or downloading something. So restarting network is not a reliable solution.

**Comment by cfergeau** [comment]
At this point, we are trying to figure out why things are not working as expected on your system, we haven't suggested restarting the network as a permanent fix. If restarting it helps, then it gives us a clue as to what's going on. If this does not help, then this means the issue is elsewhere. Your `dig` indicates that name resolution is working fine as it resolved `console-openshift-console.apps-crc.testing.` to `192.168.64.27`

When running `dig console-openshift-console.apps-crc.testing`, it's `;; SERVER: 192.168.1.254#53(192.168.1.254)` which attempted to resolve it, while it should be resolved by `192.168.64.27`. I'm not sure why it's doing that. Does it change anything if you run `sudo touch /etc/resolver/dummy` and then try again?

**Comment by csantanapr** [comment]
ah cool thanks @cfergeau for the clarification on the network restart as permanent solution.

I was able to get the system to again DNS not working.
I was able to restart the network ethernet, I did via Network Settings. I have Wifi off
And then `crc console` and curl worked

Open Network Preferences 
![image](https://user-images.githubusercontent.com/1094878/76565710-8dc0c100-6481-11ea-9b59-207f0ca2965d.png)

Select Off from drop down
Click Apply
![image](https://user-images.githubusercontent.com/1094878/76565834-e1cba580-6481-11ea-8809-43314df8b95c.png)

Select DHCP original setting and click apply
![image](https://user-images.githubusercontent.com/1094878/76565792-c5c80400-6481-11ea-8c91-4ec00bf1bf5c.png)

**Comment by csantanapr** [comment]
Have not tried the `sudo touch /etc/resolver/dummy` but I will try next time

**Comment by csantanapr** [comment]
reproduce again
```
crc stop
crc delete
crc start
```
DNS doesn't work
Then try the dummy resolver
```
 sudo touch /etc/resolver/dummy
Password:
```
It didn't work

**Comment by csantanapr** [comment]
When to network preferences, turn off ethernet and turn back on. then it starts to work.

**Comment by cfergeau** [comment]
It's unexpected that creating a new file in /etc/resolver/ does not trigger a reload of the content of this directory :(

**Comment by csantanapr** [comment]
I have not seeing the problem lately with my typical workflow of crc delete and crc start

One thing I have different I have both Ethernet and Wi-Fi enable this time, in the past I have only Ethernet enable
