### ISSUE TITLE
Please Provide VM Image + Provisioning Script

### ISSUE THREAD

**Issue by jeffsaremi** [code-ready/crc#1098]
This is a request for enhancement on the CRC product.
I have had a chance to play with this on two platforms.
I have the following comments which I'd like to be considered.

I am not sure if deploying a VM (windows, ubuntu, ...) inside which one could create yet another VM for OCP is a good deployment model and a great use of resources.

We have our development machines in Ubuntu 16.04 for which CRC won't work anyway. Also our dev environment is already virtualized making it even harder to find a machine where you could have a nested VM inside.

What we ultimately need is a VM image (for proper hypervisor) to host the image which CRC eventually installs. And a provisioning script in Ansible or whatever else.

Example: I don't need to have a Ubuntu machine where I run CRC setup/start to create a Vm. I could just dedicate a VM directly to OCP bypassing Ubuntu installation!

This would give us maximum flexibility where we would continue to use our (incompatible) environments to do our development and when we need OCP we'd just create a VM specifically for that (remove one level of indirection which CRC mandates)

How hard is to get there from what you're already offering?
thanks

**Comment by gbraad** [comment]
I am not sure what you are requesting. You would like to have the scripts we use to create the cluster? They are at: https://github.com/code-ready/snc each executable of `crc` for a platform embeds the native disk image.

Understand the need to use a VM, like on Windows or macOS, as these platforms can not natively run Linux contains. For Linux the situation is different, as you could run a cluster directly on the host. this however woudl not be possible for the older version of Ubuntu as tyou describe ... it would be incompatible or functionality would just not be there.

This is what the engineers noticed when working on OpenShift 3.x. They offered a method to deploy on any docker runtime. This however caused issues with incompatibility and instability. A model of hosting on a known container runtime was needed; a container OS. This is a minimal linux environment with a known runtime that ensures stability. For OpenShift 4.x this is called RHCOS (Red Hat CoreOS). If you host this in a company environment, it would be possibile to run this on a hypervisor; like in the datacenter on baremetal, or hosted by a cloud provider. 

To allow this to be run on a desktop we have to resort to virtualization, just like the cloud provider model. This guarantees the same stability, and consolidates all assets to run the cluster (much easier to remove than when the host got provisoned directly).

The concerns for resource usage should not have to exist, but unfortunately OpenShift 4.x is at the moment not tailored to run with minimal resources, but we are working on this.

If you want to avoid this, and would prefer to run on Azure or baremetal, you would need to OpenShift installer: https://cloud.redhat.com/openshift/install/

**Comment by cfergeau** [comment]
I'm also having a hard time understanding your base setup and the issue you are having. Your devs are using Ubuntu 16.04, and this system is already running in a VM? Instead of running crc _inside_ the Ubuntu 16.04 VM, you would like a way of creating and running the crc VM alongside the Ubuntu VM? What is the hypervisor these VMs would be running on?

**Comment by jeffsaremi** [comment]
Yes. Correct. I don't want to create a VM only so I can create another VM inside it (OCP VM).
If I'm going the route of creating a VM, it might as well be the UBI for OCP and not some intermediary one. This way I won't get into the nested VM issues and whether they're supported or not.

**Comment by jeffsaremi** [comment]
@gbraad 
I haven't got a chance to check the links you sent me. 
But for the most parts you understood my problem well.
We want to go directly to hosting the CoreOS and not have to do that through yet another OS.
We don't have Mac's. We have racks of computers that our engineers use. 

We don't have a concern for resources. We're willing to throw whatever OC needs. But we don't want that to be spent on another "wrapper" VM.

I will get back to you with the hypervisors we have.
thanks

**Comment by gbraad** [comment]
Note: UBI is not an option as these are just container images, which exclude the kernel. RHCOS is used as it guarantees the existence of namespace support, etc on kernel level

We might look into dealing with the images for use with eg. OpenStack as this common used in a CI/CD environment and does not diverge a lot from our initial image generation and use on linux. Note: it could be possible to run on older versions with some minor tweaks

**Comment by jeffsaremi** [comment]
Sorry mixed things up. I meant CoreOS

**Comment by jeffsaremi** [comment]
@cfergeau 
Most hypervisors we're running turn out to be Hyper-v.
The following scenario would also work for us:
To run CRC on one machine however have CRC install the VM into another machine (if such thing make sense indeed)

**Comment by jeffsaremi** [comment]
@gbraad 
I'm just making sure that I understand what this does:
If I follow the instructions here, 
 https://github.com/code-ready/snc
at the end of that I will have an image that I could deploy instantly to Hyper-V or some other hypervisor?

Also if I created one using CRC on say Hyper-V, can I just use the Export/Import feature (along with some alterations afterwards)?
thanks

**Comment by gbraad** [comment]
Generating the image is a heavy process. Perhaps an export of an image might help? See how #1043 matches your intent.

**Comment by jeffsaremi** [comment]
I backed out of this requirement. Examined SNC and compared it CRC. The gap is wide.

I specifically looked at the logic for:
```
		err = RegenerateCertificates(sshRunner, startConfig.Name)
```
as well as the changes for DNS and that deterred me from attempting to try an install with Ansible and SNC.

The advantage of having a provisioning script plus a prepped vm image would be the following:

- We would not be bound by the CRC on the choice of platform. Currently CRC is available only on certain platforms/distributions.

- We'd be able to run the provisioning on any machine while installing the SNC/CRC vm on another machine.

This would really fit well with our current Ubuntu 16 development machines which may/may not be capable of hosting a VM and also are out of current purvey of CRC support.
