### ISSUE TITLE
Cache pull-secret in OS keyring

### ISSUE THREAD

**Issue by anjannath** [code-ready/crc#1104]
Now, if we don't configure `pull-secret-file` in crc config, we need to pass in the pull secret to start command always using `-p` flag or enter it later during the start process.

Earlier we used to cache it in `~/.crc/cache` during the first start, but removed later as the pull secret is sensitive and we thought its better to leave it to the user to manage it securely.

Alternatively we could store it in the OS credential store / keyring during the first start so that it is stored securely and user won't have to pass in the pull-secret for every start.

**Comment by gbraad** [comment]
This might be helpful for the tray, but let's do this as an improvement AFTER we got a basic Windows implementation

**Comment by gorkem** [comment]
I was about to file this. I am not sure why this is related to tray or windows.

**Comment by guillaumerose** [comment]
docker-credentials-helper is all about this: storing registry authentication details. Linux, macOS and Windows are all open source, pretty stable but not maintained that much. We could use it.

Perhaps there is already a solution with podman login? Apparently it uses keyctl. https://github.com/containers/image/pull/675

**Comment by guillaumerose** [comment]
done in 1.22.0
