### ISSUE TITLE
What is preventing CRC to run on Windows Server 2016?

### ISSUE THREAD

**Issue by jeffsaremi** [code-ready/crc#1106]
I tried running this on one of our Servers and I got this:

```
C:\Temp\crc-for-aris\crc-windows-1.6.0-amd64>crc setup
INFO Checking if oc binary is cached
INFO Caching oc binary
INFO Checking if CRC bundle is cached in '$HOME/.crc'
INFO Unpacking bundle from the CRC binary
INFO Checking if running as normal user
INFO Checking Windows 10 release
ERRO Please manually update your Windows 10 installation
FATA Please manually update your Windows 10 installation
```

Is there anyway to disable the check for Windows 10 and proceed with the install on a Windows Server? thanks

**Comment by gbraad** [comment]
You can skip the version check, but we can't be sure this will work as
expected. We are not able to test all versions... And since this isn't a
generic workstation targeted OS, it does not fit our first usecase for
testing. We are testing Windows 10 Enterprise at the moment.

**Comment by jeffsaremi** [comment]
Understood

I applied the skip-version flag
But I think there's more to play. I'm running below as myself who's a memeber of HyperV Admin groups and also Administrators on this machine
```
C:\Temp\crc-for-aris\crc-windows-1.6.0-amd64>crc setup --log-level debug
INFO Checking if oc binary is cached
DEBU oc binary already cached
INFO Checking if CRC bundle is cached in '$HOME/.crc'
INFO Checking if running as normal user
INFO Checking Windows 10 release
WARN Skipping above check ...
INFO Checking if Hyper-V is installed and operational
INFO Checking if user is a member of the Hyper-V Administrators group
INFO Checking if Hyper-V service is enabled
INFO Checking if the Hyper-V virtual switch exist
DEBU Virtual Switch not found
ERRO Unable to perform Hyper-V administrative commands. Please make sure to re-login or reboot your system
FATA Unable to perform Hyper-V administrative commands. Please make sure to re-login or reboot your system
```
```
C:\Temp\crc-for-aris\crc-windows-1.6.0-amd64>systeminfo

Host Name:                 SPE-DL380G9-13
OS Name:                   Microsoft Windows Server 2016 Datacenter
OS Version:                10.0.14393 N/A Build 14393
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Server
OS Build Type:             Multiprocessor Free
Registered Owner:          Windows User
```

**Comment by gbraad** [comment]
For windows server you need to add a costum virtual switch named crc and
likely disable user checks when you are using domain users.

**Comment by jeffsaremi** [comment]
Thanks.
After thinking I don't think this model would work for us either. Because then we would need multiple instances of the crc vm which I don't think is a supported or doable thing

**Comment by jeffsaremi** [comment]
I'll keep exploring other options. Closing this in the mean time

**Comment by gbraad** [comment]
> Because then we would need multiple instances of the crc vm which I don't think is a supported or doable thing

It is possible to do on a machine, but many workarounds are needed. While it would be easy to swap instances, by renaming the folders, you would like to run them at the same time; this would have issues with the DNS as all the instances use the same `crc.testing` and `crc-apps.testing`. This is due to the focus of solving the desktop/workstation use-case; convenience to get an environment up and running.

It feels more like you want to offer a large set of clusters to developers. Perhaps installing a development cluster using the installer might be a better fit.
