### ISSUE TITLE
Is there a way to increase the expiration time when run crc stop 

### ISSUE THREAD

**Issue by morningspace** [code-ready/crc#1107]
### General information

  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / Hyper-V / hyperkit

## CRC version
All versions
  
### Steps to reproduce

Run `crc stop` when crc is in running status.

### Expected

Usually, it will take for a while and finally stopped successfully.
```
$ crc stop
Stopping the OpenShift cluster, this may take a few minutes...
Stopped the OpenShift cluster
```
### Actual

But in some cases, if it takes much longer time to stop the machine, it will prompt user whether or not to force stop. This makes it a bit difficult to embed the crc launch into an automated process, e.g. CI/CD pipeline, or some automation scripts.

I did a quick check through the code and it looks there's no easy way to expand the expiration time and try to avoid the user prompt.

**Comment by gbraad** [comment]
you can stop the cluster as a background process or delete as such without waiting it to finish.

The reason is that the processes inside the VM are gracefully shutdown when they VM receives a shutdown request... and this can take time.

We have already increaed the time before... but this is based on the drivers (as they perform the action in unison with the hypervisor).

Note: I am confused about the question as the long stop time affects your CI/CD process, but you do want to wait until this happened? I would say you should do a `crc stop -f` instead ?

**Comment by praveenkumar** [comment]
`crc stop -f` is what we are using our CI which first wait for the cluster to gracefully shutdown and if that not happen then it will forcefully stop it.

**Comment by gbraad** [comment]
I guess the following, since you mention it is a CI/CD environment. You might start your script as:

```
set -o pipefail
set -e
```

if so, all commands that fail will error out and stop the build. If so, you can also do the following:

```
crc stop || true
```

which in that case will ignore the retrun code of the crc stop command

**Comment by morningspace** [comment]
@gbraad @praveenkumar Thanks for your comments and sorry for the confusion.

Basically, I don't want the user prompt behavior breaks the auto run script and I want to reuse/restart the stopped machine in a later phase during the script run. So, what I am really asking is just whether I could extend the expiration time a bit by myself, although I understand to increase the time may not always work:-)

One case just FYI, as an example, I want to resize a stopped image and restart it to install my applications.

On the other hand, I probably could use `-f`, but I'm not sure whether it will break something which makes me fail to restart the stopped VM later, especially when I install more applications on top of default OCP. I may need to double check this.

P.S.

* I cannot use the background process because I need to reuse the stopped VM, so I need to know when it's stopped.

* @gbraad When you said "we have already increased the time before", do you mean it's not recommended for crc user to do this because it depends on different Hypervisors?

**Comment by gbraad** [comment]
Right. Please changes have to be ported to each hypervisor specific ally. You can of course create your own version. See our org for the repo, named like machine- and look for a commit that talks about stop or timeout.
