### ISSUE TITLE
Add tests for setup config settings

### ISSUE THREAD

**Issue by jsliacan** [code-ready/crc#111]
Write tests for `crc config set`, `crc config get`, `crc config view`. The settings should be reflected in the behavior of `crc setup` and `crc start`. 

For instance, after `crc config set skip-check-crc-network true` one should see 
```
"skip-check-crc-network": "true"
```
in `~/.crc/crc.json` file. Hence, `crc config view` should display this property as set to `true` and `crc config get skip-check-crc-network` should return the same. Consequently, `crc setup` should skip the relevant check and `crc start` should not perform the check either. 

Ideally, this will work for all configurable properties (see output of `crc config --help`).

**Comment by gbraad** [comment]
Make sure the check fails once without the network existing... and
when skipped it should not error out of the command.

On Mon, May 6, 2019 at 5:20 PM jakub sliacan <notifications@github.com> wrote:
>
> Write tests for crc config set, crc config get, crc config view. The settings should be reflected in the behavior of crc setup and crc start.
>
> For instance, after crc config set skip-check-crc-network true one should see
>
> "skip-check-crc-network": "true"
>
> in ~/.crc/crc.json file. Hence, crc config view should display this property as set to true and crc config get skip-check-crc-network should return the same. Consequently, crc setup should skip the relevant check and crc start should not perform the check either.
>
> Ideally, this will work for all configurable properties (see output of crc config --help).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by praveenkumar** [comment]
Fixed by #121
