### ISSUE TITLE
[BUG] Starting CRC (1.7) hangs on NetworkAdapters state

### ISSUE THREAD

**Issue by chrismajewski** [code-ready/crc#1111]
# General information

  * OS: Windows
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it? Yes

## CRC version
```bash
crc version: 1.7.0+fa7e558
OpenShift version: 4.3.1 (embedded in binary)
```
  
## CRC status
```bash
Machine 'crc' does not exist. Use 'crc start' to create it.
```

## CRC config
```bash

```

## Host Operating System
```bash
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
...
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 10 GenuineIntel ~3696 Mhz
BIOS Version:              American Megatrends Inc. 2.B0, 2020-01-07
```

## Notes

Symptoms similar to #1035 but not likely caused by the same issue.

Also similar, crc 1.5.0 passes that start step without issue.

**Comment by chrismajewski** [comment]
And I forgot to describe the issue.

On crc start the process, at the debug logging, it'll get stuck in a loop between

```bash
(( Hyper-V\Get-VM crc )).networkadapters[0]).ipaddresses[0]
and
( Hyper-V\Get-VM ).state
```

I left it for hours at one point and it did not recover.

I've since moved to 1.5 but I can reproduce and post more detailed information upon request.

**Comment by gbraad** [comment]
> I've since moved to 1.5 

You mean 1.5 works, but 1.6+ not? This would be awkward as nothing has actually changed in the drivers that might cause this. Can you add the `--log-level debug` and also show what the VM is doing from the console: `hvc console crc` (screenshot)

**Comment by chrismajewski** [comment]
I made the mistake of assuming 1.6 from the previous ticket, I'll test that now and get you logs at the same time.

**Comment by chrismajewski** [comment]
And now 1.7 installed without issue.  Seems like the threat that you'd look into it was enough.

Same exact folder with this crc 1.7 executable, same machine, no changes to hyper-v or the environment.  I can't speak to what setting up the previous versions may have set/changed on this machine.

The only interaction with crc or hyper-v since the issues with 1.7 were:
* setting up and starting 1.5
* deploying to openshiftapps.com through 1.5
* setting up and starting 1.6
* setting up and starting 1.7

Close the ticket or would you like anymore information?

**Comment by gbraad** [comment]
The reason why this might fail has to do with the network. For instance, when you use a VPN you enable a route all rule which prevents DHCP or SSH to happen as expected.

Closing for now
