### ISSUE TITLE
[BUG] VM in emergency mode at first start when running crc start

### ISSUE THREAD

**Issue by gorantornqvist** [code-ready/crc#1115]
### General information

  * OS: Linux
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? YES

## CRC version
```
crc version: 1.7.0+fa7e558
OpenShift version: 4.3.1 (embedded in binary)
```
  
## CRC status
```
$ crc status
CRC VM:          Running
OpenShift:       Running (v4.3.1)
Disk Usage:      14.36GB of 32.72GB (Inside the CRC VM)
Cache Usage:     12.3GB
Cache Directory: /home/goran/.crc/cache
```

## CRC config
```
$ crc config view
- memory                                : 20480
- skip-check-crc-network                : true
```

## Host Operating System
```
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.1 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.1"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.1 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.1:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.1
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.1"
```

### Steps to reproduce

  1. crc setup ; crc start
  2. check console of VM, it will hang for a few minutes and then enter emergency mode
  3. reset VM, next boot is successful and setup continues

Verified twice with crc delete, crc setup and crc start and same result

### Expected

VM to start normally with crc start

### Actual

VM crashes in the initial boot when running crc start

### Logs

The crc command logs doesnt show anything.
Let me know what logs you need.

**Comment by gbraad** [comment]
> VM crashes in the initial boot when running crc setup

The VM is not run on `setup`.  You have likely started the VM before and got stuck somehow. Please run `crc delete -f` and `crc start` again.

**Comment by gorantornqvist** [comment]
Quite sure I did the crc start step, just mixed it up when writing it down

Let me verify once again ...

**Comment by gorantornqvist** [comment]
So verified now, the problem occurrs when I run **crc start** and the first time the VM starts.
I get this error:
https://imgshare.io/image/FAp2p

If I reset the VM, the next boot it will start OK.
If I do this quickly, the crc start command wont timeout

**Comment by cfergeau** [comment]
Do you still experience the same issue with newer releases?

**Comment by gorantornqvist** [comment]
Yes, just tried installing
```
$ crc version
CodeReady Containers version: 1.12.0+6710aff
OpenShift version: 4.4.8 (embedded in binary)
```
And same issue happened, the VM hangs in the middle of the first boot. If I force reset the VM it boots ok the following boots.

**Comment by cfergeau** [comment]
I can see such bugs happening if kernel command line/grub configuration are wrong. What is unexpected is that you'd be the only person hitting this. 1.12 is fine on my RHEL8 box.
I just checked again, and no boot issues with `crc delete/crc cleanup/crc setup/crc start`. kernel command line is :
`BOOT_IMAGE=(hd0,gpt1)/ostree/rhcos-8c7254bd3dfc7f84baa914225dd9d296a145ad65ff4f1c3e71894ad14014ab91/vmlinuz-4.18.0-147.8.1.el8_1.x86_64 rhcos.root=crypt_rootfs console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu rd.luks.options=discard ostree=/ostree/boot.1/rhcos/8c7254bd3dfc7f84baa914225dd9d296a145ad65ff4f1c3e71894ad14014ab91/0`

Can you check if the `ostree-prepare-root` error message refers to `8c7254bd3dfc7f84baa914225dd9d296a145ad65ff4f1c3e71894ad14014ab91/0` or to some other value?

**Comment by praveenkumar** [comment]
Closing this since there is no response from OP.
