### ISSUE TITLE
Separate unzipping vhdx into another crc command or mix with crc setup

### ISSUE THREAD

**Issue by jeffsaremi** [code-ready/crc#1118]
### General information

  * OS: Windows
  * Hypervisor: Hyper-V

## CRC version
```bash
latest
```

In the absence of desire to include disk size as a config param, I have this ask from you. This would significantly reduce the wait time when trying to increase the disk size during a CRC installation.

Currently, to increase the disk size one has to do 

- crc setup
- crc start (which takes a long time)
- crc stop
- Using hypervisor increase the size of vhdx
- crc start (which takes a long time)
- SSH into and run xfs_growfs

The reason for starting and stopping is we don't have access to the VHDX unless we run `crc start`. It is only during this step that the included zip file (bundle) is extracted

Had we had the ability to extract the bundle either during `setup` or using another command, we could have actually eliminated the need for a start/stop cycle like so:

- crc setup
- crc extract (new command)
- Using hypervisor increase the size of vhdx
- crc start (which takes a long time)
- SSH into and run xfs_growfs

thanks

**Comment by jeffsaremi** [comment]
Corollary:
CRC itself could have run the steps i mentioned towards the end without impacting the shipped size of the distribution therefore accommodating the storage size config param.

**Comment by gbraad** [comment]
You can use thew cached version of the bundle as a workaround to share this with others.

it would be unlikely a top level command as this clutters usability. a possible `crc setup -extract` ? but disk enlargement is still on the todo list...

so... #127 still applies

**Comment by jeffsaremi** [comment]
@gbraad 
So the work around if I'm understanding correctly is like this:

- Do crc setup/start once
- Do crc stop
- Increase the size of vhdx
- Overwrite the vhdx in %USERPROFILE%\.crc\cache\crc_hyperv_4.3.0
- For internal, repeated use, compress the above and use alongside crc.exe by expanding onto user's home

**Comment by gbraad** [comment]
Yep, especially as it feels like you want to share this within a team. Sounds like another usecase we saw by sharing prepped images as a bundle.

**Comment by jeffsaremi** [comment]
On further inspection I noticed that the compressed bundle is extracted from the `crc.exe` during `setup`. This is actually very beneficial for us. Because between the `setup` and `start` steps we could uncompress/untar the bundle to user's `.crc` folder and then have the vhdx resized.

The compression format is tar + xz if I'm not mistaking.

I think we can close this

**Comment by cfergeau** [comment]
> The compression format is tar + xz if I'm not mistaking.

That's correct!
