### ISSUE TITLE
Update podman-remote client download code to use Github releases

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#1126]
We will likely have all the clients downloaded from Github releases, based on a tagged release.
Waiting for #1083 to be resolved ...

**Comment by gbraad** [comment]
@zeenix how much time do you think this would take?

**Comment by zeenix** [comment]
> @zeenix how much time do you think this would take?

Assuming it's just a URL change, not long at all. Max a few hours (not including testing)?
