### ISSUE TITLE
INFO Will use root access: write NetworkManager config in /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf 

### ISSUE THREAD

**Issue by Amitninja12345** [code-ready/crc#1131]
crc setup
INFO Checking if oc binary is cached              
INFO Checking if podman remote binary is cached   
INFO Checking if CRC bundle is cached in '$HOME/.crc' 
INFO Checking if running as non-root              
INFO Checking if Virtualization is enabled        
INFO Checking if KVM is enabled                   
INFO Checking if libvirt is installed             
INFO Checking if user is part of libvirt group    
INFO Checking if libvirt is enabled               
INFO Checking if libvirt daemon is running        
INFO Checking if a supported libvirt version is installed 
INFO Checking if crc-driver-libvirt is installed  
INFO Checking for obsolete crc-driver-libvirt     
INFO Checking if libvirt 'crc' network is available 
INFO Checking if libvirt 'crc' network is active  
INFO Checking if NetworkManager is installed      
INFO Checking if NetworkManager service is running 
INFO Checking if /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf exists 
INFO Writing Network Manager config for crc       
INFO Will use root access: write NetworkManager config in /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf 
[sudo] password for abc:

**Comment by praveenkumar** [comment]
@Amitninja12345 This is expected, not sure what is the issue you are facing?

**Comment by Amitninja12345** [comment]
FATA Failed to write NetworkManager config file: /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf: Failed writing to file as root: /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf: Sorry, user abc is not allowed to execute '/bin/tee /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf' as root on abc.dd.ttt.
: exit status 1

**Comment by Amitninja12345** [comment]
it worked now.
