### ISSUE TITLE
[spike] Remove dns dependency on the host

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#1132]
Right now we are depending on different method on different platform to provide a dns resolver on the host to resolve the routes for crc `apps-crc.testing` and `api.crc.testing` . Current way of handling those depend on the platform and creating some issues which can be avoided if we completely remove it and depend on only `/etc/hosts` file using something like https://github.com/goodhosts/cli one.

**Comment by cfergeau** [comment]
>  some issues which can be avoided
Can this be specific about the exact issues this spike wants to solve?
Using https://github.com/goodhosts/cli would introduce a usability regression, and a difference in behaviour compared with a regular openshift install.

**Comment by gbraad** [comment]
Can you describe what is tried to be solved... and how the changed scenario woudl look like?
Especially, as we need to find a common approach if possible and when needed what the platform specific changes would be.

Especially on Windows, we need to avoid the use of UAC when possible. This is requesting to execute something as admin, which happens by a modal dialog blocking the user.

**Comment by gbraad** [comment]
Also see #926; the current solution for Windows is not optimal and causes issues outside the use of CRC

**Comment by gbraad** [comment]
#926 got resolved witn `cleanup`.

**Comment by anjannath** [comment]
Part of this was done in #1136 for macOS and Linux the windows part remains.

**Comment by cfergeau** [comment]
Only the basics were done, host DNS still needs to be configured for the user-created routes to work.

**Comment by guillaumerose** [comment]
The three platforms are now using the admin helper (which includes goodhost lib).
