### ISSUE TITLE
[BUG] crc binary fails to start if placed under /usr/local/bin

### ISSUE THREAD

**Issue by yanniszark** [code-ready/crc#1138]
### General information

  * OS: Linux
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
crc version: 1.8.0+0a318dc
OpenShift version: 4.3.8 (embedded in binary)
```
  
## CRC status
```bash
# Put `crc status` output here
```

## CRC config
```bash
# Put `crc config view` output here
```

## Host Operating System
```bash
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
```

### Steps to reproduce

  1. Start a CentOS 8 machine (mine is in GCP with nested virt enabled)
  2. Download crc and place it in a location like `/usr/local/bin/crc`: `sudo cp crc/crc /usr/local/bin`
  3. `crc setup`
  4. `crc start --log-level=debug`

### Expected
crc should work when owned by root in a path like /usr/local/bin, similar to other tools.

### Actual
crc start fails.
Inspecting the .crc files, I see the .crc/machines/crc/crc is owned by root instead of qemu.

I worked around this by moving the binary to $HOME/bin and changing owner to my user.
Are you aware of this issue? Maybe we could make a note of this in the docs?

**Comment by gbraad** [comment]
can you share the log outputs and more details? This has more likely to do with the fact the executable might be run as root instead of a user; have you set the suid bit or sticky bit?

Note: We perform checks to prevent the use of root, so it would be helpful if startup logs are shared.

**Comment by gbraad** [comment]
Note: today we have been on a call with a customer who actually ran `crc` from `/usr/local/(s)bin` but not experience issues doing this.

**Comment by gbraad** [comment]
@jsliacan can you give this a try too ?

**Comment by yanniszark** [comment]
@gbraad I ran everything as my normal user.
Once I get a chance to repeat this, I will gather all logs and share them here.

**Comment by gbraad** [comment]
OK. We will try to also run this.

Note: The vms are started as using libvirt as libvirt:///system, so the files are expected to be owned as root. I am currently focussed on the windows side, so hope my colleague can hint at this. @zeenix WDYT?

**Comment by jsliacan** [comment]
@yanniszark @gbraad I tried on RHEL8 bare metal and couldn't reproduce. I second the desire for more info please, thanks!

**Comment by gbraad** [comment]
Three colleagues have tried this, plus the customer who ran this... and so far we haven't seen a failure during startup.

https://pastebin.com/xjeqmgj2

**Comment by yanniszark** [comment]
@gbraad @jsliacan thanks a lot for looking into this.
At some point I interrupted the crc command, as it was hanging for a long time and I suspect the wrong permission was a side effect of that.
The real issue seems to be https://github.com/code-ready/crc/issues/1149, which we can reproduce consistently (I am working together with @ioandr who opened the issue)
The issue (https://github.com/code-ready/crc/issues/1149) contains instructions for reproducing it end-to-end, I would recommend shifting the focus there and closing this one.

**Comment by nimrodshn** [comment]
Currently getting the following error upon  `crc start`:
```
ERRO Error getting bundle metadata: xz: data is corrupt 
```
Using the latest (v.1.13) on Fedora 32.
```
tar -xvf crc-linux-amd64.tar.xz
sudp cp crc /usr/local/bin/
crc setup
crc start
```

**Comment by praveenkumar** [comment]
@nimrodshn I just tried it 1.15 on fresh RHEL-8.2 machine and it does work, can you try again and let us know if that still true for Fedora?
