### ISSUE TITLE
[BUG] crc start failed at "Adding user's pull secret ..."

### ISSUE THREAD

**Issue by morningspace** [code-ready/crc#1139]
### General information

  * OS: Linux
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
crc version: 1.5.0+e1c8fb8
OpenShift version: 4.2.14 (embedded in binary)
```
  
## CRC status
```bash
ERRO The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port?
 - exit status 1
```

## Host Operating System
```bash
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.7 (Maipo)"
```

### Steps to reproduce

I am using crc 1.5.0. It used to work, but start to fail yesterday even I cleanup all existing stuff, then download and install new crc.

  1. crc setup
  2. crc start

### Expected
crc can be launched successfully

### Actual
It failed at the step of "Adding user's pull secret ...".

But VM is launched, as I can ssh into it by running:
```shell
$ ssh -i ~/.crc/machines/crc/id_rsa core@$(crc ip)
```
And,
```shell
$ virsh -c qemu:///system list
setlocale: No such file or directory
 Id    Name                           State
----------------------------------------------------
 3     crc                            running
```

Also, api.crc.testing can be connected:
```shell
$ ping api.crc.testing
PING icp-console.apps-crc.testing (9.111.98.254) 56(84) bytes of data.
64 bytes from lab3-playground.cn.ibm.com (9.111.98.254): icmp_seq=1 ttl=64 time=0.169 ms
```

But, crc status returns failure:
```shell
$ crc status
ERRO The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port?
 - exit status 1
```

### Logs
```
WARN A new version (1.8.0) has been published on https://cloud.redhat.com/openshift/install/crc/installer-provisioned
INFO Checking if oc binary is cached
INFO Checking if running as non-root
INFO Checking if Virtualization is enabled
INFO Checking if KVM is enabled
INFO Checking if libvirt is installed
INFO Checking if user is part of libvirt group
INFO Checking if libvirt is enabled
INFO Checking if libvirt daemon is running
INFO Checking if a supported libvirt version is installed
INFO Checking if crc-driver-libvirt is installed
INFO Checking if libvirt 'crc' network is available
INFO Checking if libvirt 'crc' network is active
INFO Checking if NetworkManager is installed
INFO Checking if NetworkManager service is running
INFO Checking if /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf exists
INFO Checking if /etc/NetworkManager/dnsmasq.d/crc.conf exists
INFO Extracting bundle: crc_libvirt_4.2.14.crcbundle ...
INFO Creating CodeReady Containers VM for OpenShift 4.2.14-x86_64...
INFO Verifying validity of the cluster certificates ...
INFO Check internal and public DNS query ...
INFO Check DNS query from host ...
INFO Copying kubeconfig file to instance dir ...
INFO Cluster TLS certificates have expired, renewing them... [will take up to 5 minutes]
WARN API server is not ready after cert recovery process
INFO Adding user's pull secret ...
ERRO Error Setting cluster config: Failed to update user pull secret or cluster ID: Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
...
```

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
As per following error, looks like api server not even ready to serve the request :( can you delete it and run again but use `--log-level debug` and share the logs in a gist?

```
INFO Cluster TLS certificates have expired, renewing them... [will take up to 5 minutes]
WARN API server is not ready after cert recovery process
```

**Comment by morningspace** [comment]
Yeah, I just finished it and uploaded here: https://gist.github.com/morningspace/113a5f85110d6957242a66a6ff9776ec

And, do notice below errors and it looks it's failed to update the cert?
```
sudo oc adm certificate approve csr-fbgvr --kubeconfig /etc/kubernetes/static-pod-resources/recovery-kube-apiserver-pod/admin.kubeconfig
DEBU SSH cmd err, output: <nil>: certificatesigningrequest.certificates.k8s.io/csr-fbgvr approved
DEBU oc invocation failed: The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port?
DEBU error: Temporary Error: exit status 1 - sleeping 1s
DEBU retry loop 1
...
```

**Comment by gbraad** [comment]
Are you performing these steps on a baremetal machine or cloud service?

**Comment by morningspace** [comment]
It's a lab vm (VMWare) @gbraad

**Comment by praveenkumar** [comment]
@morningspace any chance you give the latest version a try which doesn't need cert recovery step and see if that works?

**Comment by morningspace** [comment]
Aha.. I see.. I was using an old version just because it's easy for me to expand the default 30GB disk size. Well, I can find time to try the latest one, which seem better since it doesn't need cert recovery, but I guess need to figure out the way to expand the disk size which I haven't tried yet.

**Comment by gbraad** [comment]
Nested virtualization is not recommended. We have only tested this kvm+kvm or hyperv+hyperv, not any other combination. From experience with Minishift we generslly do not recommend this setup as described

**Comment by gbraad** [comment]
Can we close this issue, as the used version is about 2+ months old (3 releases behind)

**Comment by morningspace** [comment]
Sure, let me do this...

**Comment by praveenkumar** [comment]
@morningspace Also can you confirm that latest release works as expected, disk resize manual process is discussed in https://github.com/code-ready/crc/issues/127 issue.

**Comment by morningspace** [comment]
Yeah, I just tried the latest one, it works w/ the resize manual process. I've updated #127 just now. @praveenkumar
