### ISSUE TITLE
How do I get the file crc_libvirt_4.3.8.crcbundle

### ISSUE THREAD

**Issue by olaf-meyer** [code-ready/crc#1145]
### General information

  * OS: Linux 
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? /

## CRC version
```bash
crc version: 1.8.0+0a318dc
OpenShift version: 4.3.8 (embedded in binary)
```
  
## CRC status
```bash
Machine 'crc' does not exist. Use 'crc start' to create it.
```

## CRC config
```bash
```

## Host Operating System
```bash
```

### Steps to reproduce
Hello, 

I would like to build crc on my local machine. If I run `make integration` I need to provide the path to the file `crc_libvirt_4.3.8.crcbundle`. Maybe I miss something in the documentation but I don't understand from where I can get that file? Can I build that from an other repo?

Thank you very much in advance,

Olaf

**Comment by cfergeau** [comment]
After running `crc setup`, you will find `crc_libvirt_4.3.8.crcbundle` in `~/.crc/cache`

**Comment by olaf-meyer** [comment]
This is true and this is what I did for running the tests. However I'm trying to build the crc binary which would include the bundle. How do you create a new version of the crc with a new bundle version?

**Comment by cfergeau** [comment]
See the `embed_bundle` target in the Makefile. You can workaround the missing bundles for macos/windows binaries by creating empty bundle files (but the resulting binaries won't be functional).

**Comment by olaf-meyer** [comment]
Thank you very much for your time. Is my understanding correct that with the target `embed_bundle` the bundles are added to the executable (I know that the name of target provides a strong indication for that). I'm sorry to tell you, but I still don't understand where the bundles are coming from. Can they be downloaded from another github repo, because I don't see a target in the crc makefile which is used to build them?

Again thank you very much for your help.

**Comment by cfergeau** [comment]
>  Is my understanding correct that with the target `embed_bundle` the bundles are added to the executable (I know that the name of target provides a strong indication for that)

Yes, that's correct, this target adds pre-existing bundles to the executable.

>  I still don't understand where the bundles are coming from. Can they be downloaded from another github repo, because I don't see a target in the crc makefile which is used to build them?

They are generated using https://github.com/code-ready/snc , but it's not trivial to get it to run successfully. I don't think the raw bundles (non-embedded) are available publicly. It's possible to extract them from the crc releases using https://github.com/code-ready/crc/tree/master/cmd/crc-embedder which is built when your run `make embed_bundle`.

**Comment by olaf-meyer** [comment]
Thank you very much. I missed that part. You helped me a great deal.
