### ISSUE TITLE
[BUG] crc start seems to randomly hang, leaving the cluster in half-baked state

### ISSUE THREAD

**Issue by ioandr** [code-ready/crc#1149]
### General information

  * OS: **Linux**
  * Hypervisor: **KVM**
  * Did you run `crc setup` before starting it (Yes/No)? **Yes**

## CRC version
```bash
crc version: 1.8.0+0a318dc
OpenShift version: 4.3.8 (embedded in binary)
```
  
## CRC status
**Depends**

## CRC config
**Depends**

## Host Operating System
```bash
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
```

_NOTE_

The host machine is a `n2-standard-8` GCP instance (8 CPUs, 32Gb RAM), that runs a CentOS image with nested virtualization enabled. To produce such image, we followed the [official Google Cloud guide on nested Virtualization](https://cloud.google.com/compute/docs/instances/enable-nested-virtualization-vm-instances). 

More specifically, we executed the following command to produce the VM image:
```bash
$ gcloud compute images create centos-8-v20200326-nested-virt --source-image=centos-8-v20200326 --source-image-project=centos-cloud licenses "https://compute.googleapis.com/compute/v1/projects/vm-options/global/licenses/enable-vmx"
```

### Steps to reproduce

  1. `wget 'https://mirror.openshift.com/pub/openshift-v4/clients/crc/latest/crc-linux-amd64.tar.xz'`
  2. `mkdir crc && tar xvf crc-linux-amd64.tar.xz -C crc --strip-components 1`
  3. `sudo cp crc/crc /usr/local/bin`
  4. `crc setup`
  5. `crc start --cpus 8 --memory 28672 --log-level debug`
  6. Paste image pull secret from https://cloud.redhat.com, once prompted
  7. Wait for step 5 to finish

### Expected

`crc start` should successfully terminate. Since the `crc start` program runs in the foreground, it should never hang (or block for too long) either on success or failure. 

### Actual

The `crc start` command seems to randomly hang (or at least block for too long) at times, leaving the cluster in half-baked state. As such, to get back at the prompt I have to either close the program with `CTRL+C` or suspend it with `CTRL+Z`.

We have seen the program hang **quite early**, at different steps, see gists `crc-start-1` and `crc-start-2` linked below.

Message-1:
> Wrapper Docker Machine process exiting due to closed plugin server (read tcp 127.0.0.1:54368- 
>127.0.0.1:40633: read: connection reset by peer)                                                                                                
> ERRO Error creating host: Error creating the VM: Error creating machine: Error in driver during 
> machine creation: read tcp 127.0.0.1:54368->127.0.0.1:40633: read: connection reset by peer

Message-2:
> ERRO Error Setting cluster config: Temporary Error: connection is shut down

We have seen the program hang **quite late**, even at the very end, with the normal success messages. In this case the OpenShift cluster seems operational, i.e., `oc` and `kubectl` work as expected.

Message:
> INFO                                              
> INFO To access the cluster, first set up your environment by following 'crc oc-env' instructions 
> INFO Then you can access it by running 'oc login -u developer -p developer https://api.crc.testing:6443' 
> INFO To login as an admin, run 'oc login -u kubeadmin -p kKdPx-pjmWe-b3kuu-jeZm3 https://api.crc.testing:6443' 
> INFO                                              
> INFO You can now run 'crc console' and use these credentials to access the OpenShift web console 

Let me know for any further information you might need.

### Logs

- CRC setup : https://gist.github.com/ioandr/66173ab519525a9d1a87125293346e1f
- CRC start 1: https://gist.github.com/ioandr/85d90b6aae4608bfdcb84099a029d083
- CRC start 2: https://gist.github.com/ioandr/91be58f1541d72fadc900d5fe23bf9d3

**Comment by ioandr** [comment]
In case you wish to spin a CentOS 8 VM on GCP with nested virtualization enabled, to fully emulate our environment, use the following command:

```bash
$ gcloud compute instances create \
    crc-openshift \
    --machine-type=n2-standard-8 \
    --image=centos-8-v20200326-nested-virt \
    --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append \
    --boot-disk-size=500GB \
    --boot-disk-type=pd-standard \
    --boot-disk-device-name=crc-openshift-disk \
```

_NOTES_

1. Read the **Host Operating System** section in the first comment to see how to create the image for the VM
2. You might need to specify the `--project` and `--zone` arguments in the `gcloud` command

**Comment by praveenkumar** [comment]
@ioandr we did try to run `crc` on the GCP using same machine-type, most of the time we see the crash of instance itself then `crc`.  The way we create the images for GCP using packer https://github.com/ironcladlou/openshift4-libvirt-gcp/tree/rhel8_host , we will try again to test latest version of crc on GCP to see if this is reproducible.

**Comment by ioandr** [comment]
Hi @praveenkumar thanks for taking a look at this!

We were not aware of the https://github.com/ironcladlou/openshift4-libvirt-gcp/tree/rhel8_host repo and simply followed the standard https://code-ready.github.io/crc guide, where no limitations related to nested virtualization are mentioned. Is there a  GCP-specifc guide we shall switch to?

TBH, we omitted to check the state of the underlying GCP instance when `crc` hanged, since we thought this was an issue with `crc` itself. We will also try to reproduce and inspect the GCP instance for logs or anything useful.

**Comment by praveenkumar** [comment]
> where no limitations related to nested virtualization are mentioned

@ioandr We are mostly targeted for user desktop/laptop which is not nested virtualized. Have a look to https://access.redhat.com/solutions/4974521 also.

> we omitted to check the state of the underlying GCP instance when crc hanged, since we thought this was an issue with crc itself. We will also try to reproduce and inspect the GCP instance for logs or anything useful.

Please do check, this is what we saw most of the time on GCP side, when run crc.

**Comment by danielmenezesbr** [comment]
@ioandr I created a repository that provides an automated way to provision CRC on GCP:

[https://github.com/danielmenezesbr/crc-on-gcp-terraform](https://github.com/danielmenezesbr/crc-on-gcp-terraform)
