### ISSUE TITLE
Document about how to login using kubeadmin user.

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#116]
As of now if you export the `KUBECONFIG` which is part of our bundle and then try using `oc login -u kubeadmin` it is going to fail with `x509: certificate signed by unknown authority` because it doesn't have ingress cert and also from openshift side it is advised that this kubeconfig file is only used for cluster admin work, not for normal user. 

If a user used `export KUBECONFIG` command then that need to be unset using `unset KUBECONFIG` after that user can start login using `oc login -u kubeadmin https://api.crc.tt.testing:6443`

**Comment by robin-owen** [comment]
@praveenkumar Would this make sense to document as a known issue?

**Comment by robin-owen** [comment]
Closing this issue. Per @praveenkumar, we do not want the user to use `KUBECONFIG` at all.
