### ISSUE TITLE
Failed to pull image - while deploying httpd-example from Red Hat Documentation

### ISSUE THREAD

**Issue by sundar-cs** [code-ready/crc#1161]
I have a CodeReady Container on CentOS 7.5 Guest OS on a Vmware esxi5.5 setup.

The cluster has been setup as per the steps mentioned in the link below and the cluster is up.

I am trying to add my first app and trying the basic httpd-example as per this link
https://developers.redhat.com/blog/2019/09/05/red-hat-openshift-4-on-your-laptop-introducing-red-hat-codeready-containers/

But the pods never come up.
When I try the describe command it shows it's unable to get to the quay.io server.
From my CentOS host I can access this URL and it returns me the proper html content (thru curl).

I have also tried "crc start -n 8.8.8.8" to make it go to the google DNS server but that did not help either.

Please see the details as below, for "oc  get all" and "oc describe  pod/httpd-example-1-build" commands.

(the outputs have been attached in the files with the respective names - for ease of reading)

I have attached the crc.log file also (though I can't see any errors relating to above in it)
[crc.log](https://github.com/code-ready/crc/files/4486849/crc.log)

[oc-get-all.txt](https://github.com/code-ready/crc/files/4486891/oc-get-all.txt)
[oc-describe.txt](https://github.com/code-ready/crc/files/4486893/oc-describe.txt)

**Comment by praveenkumar** [comment]
@sundar-cs This looks like network issue inside the VM (mostly dns) can you try following and see if that works for you. Also I noticed that `crc.log` is not fully uploaded to the issue, it doesn't contain information around pinging an external service like `quay.io`

```
$ crc delete
// Get the actual dns server which your host is using instead using the google one.
// Below command might give you a list of DNS IP, try to use one of them which
// able to resolve the dns query 
$ nmcli device show | grep DNS
 IP4.DNS[1]:                             192.168.10.1, 192.168.0.1

// Here for me 192.168.10.1 doesn't work
$ dig google.com @192.168.0.10 +short

; <<>> DiG 9.11.14-RedHat-9.11.14-2.fc31 <<>> google.com @192.168.0.10 +short
;; global options: +cmd
;; connection timed out; no servers could be reached

// For me 192.168.0.1 works so better to use this one with crc command
$ dig google.com @192.168.0.1 +short   
172.217.163.46

$ crc start -n <my_worked_dns_ip>
```

**Comment by sundar-cs** [comment]
Thank you.
(1)
Yes it sounded like a DNS issue and this message had been spotted in syslog (/var/log/messages)
"Apr 16 06:21:39 localhost dnsmasq[12160]: nameserver 192.168.20.17 refused to do a recursive query"
(though it has been logged only once in 2+ days despite repeated errors)
(2) In addition to above, the tips on issue #779 is what led me to the "-n" option
(3) Also crc.log still does not have the quay.io messages, the last log is when the cluster was started.
(Note that I had not started it with --log_level debug. Maybe this would have helped ?).

Anyway here's the output for the commands above.

-bash-4.2$ nmcli device show | grep DNS
IP4.DNS[1]:                             192.168.20.17
IP4.DNS[2]:                             8.8.8.8
IP4.DNS[3]:                             121.242.190.180
IP4.DNS[4]:                             202.71.140.36
IP4.DNS[5]:                             4.2.2.2
IP4.DNS[6]:                             121.242.190.211
-bash-4.2$ dig google.com @192.168.20.17 +short
-bash: dig: command not found

(Note : I installed bind-utils at this point).

-bash-4.2$ dig google.com @192.168.20.17 +short
172.217.18.46
-bash-4.2$ dig google.com @8.8.8.8 +short
216.58.196.78

It looks as though both are working ?
Hence I did not proceed with the "crc start -n a.b.c.d" yet.

**Comment by cfergeau** [comment]
`oc describe` output has:
```
  Warning  Failed     67m (x2 over 68m)      kubelet, crc-45nsk-master-0  Failed to pull image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:bd8351605aa225bb7affe8f0bd6c6bfc183f36991c22e87bc6b9ca888f54949d": rpc error: code = Unknown desc = error pinging docker registry quay.io: Get https://quay.io/v2/: dial tcp 54.84.104.249:443: i/o timeout
  Warning  Failed     65m                    kubelet, crc-45nsk-master-0  Failed to pull image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:bd8351605aa225bb7affe8f0bd6c6bfc183f36991c22e87bc6b9ca888f54949d": rpc error: code = Unknown desc = error pinging docker registry quay.io: Get https://quay.io/v2/: dial tcp 3.212.220.94:443: i/o timeout
  Warning  Failed     64m                    kubelet, crc-45nsk-master-0  Failed to pull image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:bd8351605aa225bb7affe8f0bd6c6bfc183f36991c22e87bc6b9ca888f54949d": rpc error: code = Unknown desc = error pinging docker registry quay.io: Get https://quay.io/v2/: dial tcp 18.208.7.119:443: i/o timeout
```
Note that this lists 3 distinct IP addresses which indeed correspond to quay.io, so I'm not sure this is a DNS issue
```
$ host quay.io
quay.io has address 18.208.7.119
quay.io has address 3.223.162.55
quay.io has address 3.212.220.94
quay.io has address 107.23.219.79
quay.io has address 54.165.181.134
quay.io has address 54.84.104.249
```

**Comment by sundar-cs** [comment]
Yes true thanks for pointing this out.

The dig commands above were at the CentOS Guest level but the problem seems to be that the container under the KVM layer is unable to get to the outside world ?
Is this a fair observation ?

If so, would ssh be a way to get into it to ascertain outside access provided the public key is available at the container ?
ssh -i ~/.crc/cache/crc_libvirt_4.1.11/id_rsa_crc core@192.168.130.11
(or as crc user ?)

**Comment by cfergeau** [comment]
>  `ssh -i ~/.crc/cache/crc_libvirt_4.1.11/id_rsa_crc core@192.168.130.11`

You could test this for example: `ssh -i ~/.crc/machines/crc/id_rsa core@192.168.130.11 nc -v quay.io 443`

**Comment by sundar-cs** [comment]
oh thank you, i had the wrong path (openssh key).

No it does not work ... 

-bash-4.2$ ssh -i ~/.crc/machines/crc/id_rsa core@192.168.130.11 nc -v quay.io 443
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connection to 54.84.104.249 failed: Connection timed out.
Ncat: Trying next address...
Ncat: Connection to 107.23.219.79 failed: Connection timed out.
Ncat: Trying next address...
Ncat: Connection to 54.165.181.134 failed: Connection timed out.
Ncat: Trying next address...
Ncat: Connection to 3.212.220.94 failed: Connection timed out.
Ncat: Trying next address...
Ncat: Connection to 18.208.7.119 failed: Connection timed out.
Ncat: Trying next address...
Ncat: Connection timed out.


-bash-4.2$ crc version
crc version: 1.8.0+0a318dc
OpenShift version: 4.3.8 (embedded in binary)


It was installed thru these links
https://access.redhat.com/documentation/en-us/red_hat_codeready_containers/1.8/html/getting_started_guide/index
which takes us to
https://cloud.redhat.com/openshift/install/crc/installer-provisioned

**Comment by cfergeau** [comment]
Is `nc -v quay.io 443` working from the host? Are you using a http proxy for networking?

**Comment by sundar-cs** [comment]
Yes it works.
-bash-4.2$ nc -v quay.io 443
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connected to 54.84.104.249:443.

As per the lab sys admin, yes the connection to the internet is thru a web proxy which forwards to a firewall
(But please note that the Guest OS is able to work seamlessly, the entire lab has access to internet, including this host, which is actually a CentOS VM on vmware as mentioned earlier)

**Comment by cfergeau** [comment]
But do you have to set `http_proxy`/... on the host to get outbound connectivity? or is this all seamless, and no need for any configuration? I don't know why the crc VM does not get external access. Maybe worth trying another VM to see if this is a generic issue with your system? (fedora livecd running in a VM created with virt-manager for example, or virt-builder)

**Comment by sundar-cs** [comment]
Thank you.
I tried this sequence (by retrieving images from getfedora.org).

(1) CentOS 7.5 as guest OS (like before) and then manually installed KVM
(yum install qemu-kvm qemu-img virt-manager libvirt libvirt-python libvirt-client virt-install virt-viewer bridge-util)

(2) virt-install to create a Fedora VM (server)
virt-install --debug --name falcon-1 --ram 16384 --disk path=/var/lib/libvirt/images/falcon1.img,size=64 --vcpus 1 --virt-type kvm --os-type linux --os-variant ubuntu18.04 --graphics none --location '/tmp/Fedora-Server-dvd-x86_64-31-1.9.iso' --extra-args "console=tty0 console=ttyS0,115200n8"

I guess os variant ("ubuntu") doesn't matter (& hasn't been updated in virt-install), as long as the location is proper.

(3) Above is successful and I can do "virsh console falcon-1" and then
cat  /etc/redhat-release
Fedora release 31 (Thirty One)

On this "ping google.com", "nc -v quay.io 443" etc work well.
i.e. this confirms that in the same lab VPN setup, again with a CentOS guest OS (under esxi 5.5), a KVM virtual machine is able to get to the outside world.
Is that correct ?

I presume in the case of CRC, the tgz file itself has the KVM installables along with the actual VM images etc which are what get installed when we do "crc setup" ?

Can i get into the CRC node and run above commands ?
I can't do "oc exec" as the pod itself doesn't get created (as we're stuck reaching quay.io to pull the image even before that).

I have attached the "ip addr" (ifconfig) and "ip route" (netstat) outputs from the CRC Host machine (CentOS GuestOS) and also the above setup (CentOS + Fedora VM) just to check if that gives any clues.
[ip-add-and-ip-route.Fedora-VM.txt](https://github.com/code-ready/crc/files/4545165/ip-add-and-ip-route.Fedora-VM.txt)
[ip-addr-and-ip-route.Fedora-Host.txt](https://github.com/code-ready/crc/files/4545166/ip-addr-and-ip-route.Fedora-Host.txt)
[ip-addr-and-ip-route.CRC-Host.txt](https://github.com/code-ready/crc/files/4545167/ip-addr-and-ip-route.CRC-Host.txt)

**Comment by cfergeau** [comment]
You can use `ssh -i ~/.crc/machines/crc/id_rsa core@192.168.130.11` to get ssh access

**Comment by sundar-cs** [comment]
yes thank you, I recollected we had tried this earlier too (in the same thread above).
However now I captured the "ip addr show" and "ip route" outputs etc as attached (also the nc output again but with the same results).
[ip-addr-and-ip-route-CRC-VM.txt](https://github.com/code-ready/crc/files/4550995/ip-addr-and-ip-route-CRC-VM.txt)

(Are there so many network interfaces due to multiple stop/start operations ?)

**Comment by cfergeau** [comment]
I believe it's the container networking stack which creates these interfaces, but never really looked closely ;)
Regarding your virt-install test from before, I suspect virtual networking was not configured the same way, `virsh dumpxml crc` has `<interface type='network'>`, I would not be surprised if the default with virt-install was something different.
One more random thing you could try (had issues with that a few times) is to stop the crc VM, and do `systemctl stop libvirtd.service && systemctl start libvirtd.service). I've seen libvirtd networking getting confused in the past.

**Comment by brightzheng100** [comment]
I encountered exactly the same DNS issue in MacOS and `crc delete` + `crc start -n 8.8.8.8` didn't work for me.

Luckily I learned how to SSH into the hyperkit VM from this thread and I realized that the `/etc/resolv.conf` didn't add my `8.8.8.8` there.

So I added it into it then hurrah it worked!

Attached is my manually updated `/etc/resolv.conf` content for your reference:

```
[core@crc-bq5fv-master-0 ~]$ cat /etc/resolv.conf
# Generated by CRC
search crc.testing
nameserver 8.8.8.8
nameserver 10.88.0.8
nameserver 192.168.64.1
nameserver fe80::184d:a91f:783c:1569%enp0s1
```

**Comment by sundar-cs** [comment]
Thank you (Christophe and Bright).
I tried the latter suggestion but in my case it didn't help, then recollected that in my case DNS was not the issue as discussed earlier in this thread too.
Then I tried the former suggestion about restarting libvirtd and yes it resolved it ! Thanks so much.

To sum it up : 
as described earlier in this thread, when I installed the KVM manually on fresh setups (yum install qemu-kvm qemu-img virt-manager libvirt libvirt-python libvirt-client virt-install virt-viewer bridge-util) and then tried virt-install the VM created within KVM hypervisor had no issues.
This suggested that there's no issue in the lab setup as such (but I had not tried CRC on these new setups yet)
Then on the same setup where I had CRC issues, I did the restart of libvirtd as per Christophe suggestion and that fixed it (Thank you !)
Subsequent to this, I installed CRC too on my other manually installed KVM setups and they too were fine.
Thus it boils down to 1 particular setup (which happened to be my 1st setup) having peculiar issues with libvirtd.
So the issue is now closed but I'm leaving this thread open in case there are other comments (and let it get closed by the Robot after idle period).
Thanks a bunch.

**Comment by cfergeau** [comment]
> Thus it boils down to 1 particular setup (which happened to be my 1st setup) having peculiar issues with libvirtd.

This happens to me about once a year on my laptop, I never tried to investigate since it's so rare and not hard to fix. This could be caused by upgrade of specific packages while libvirtd is running?

**Comment by sundar-cs** [comment]
Yes possibly ... Thank you.
