### ISSUE TITLE
crc start errors and developer log-in error

### ISSUE THREAD

**Issue by subbarb** [code-ready/crc#1166]
### General information

  * OS: Linux / macOS / Windows : Linux
  * Hypervisor: KVM / Hyper-V / hyperkit : KVM
  * Did you run `crc setup` before starting it (Yes/No)? : Yes

## CRC version
```bash
# Put `crc version` output here
```
crc version: 1.8.0+0a318dc
OpenShift version: 4.3.8 (embedded in binary)

  
## CRC status
```bash
# Put `crc status` output here
```
CRC VM:          Running
OpenShift:       Running (v4.3.8)
Disk Usage:      11.87GB of 32.72GB (Inside the CRC VM)
Cache Usage:     11.8GB
Cache Directory: /home/crcusr/.crc/cache

## CRC config
```bash
# Put `crc config view` output here
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"

# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```

### Steps to reproduce

  1. 
  2. 
  3. 
  4. 
follow steps from this doc
https://www.redhat.com/sysadmin/codeready-containers

### Expected
should not have any errors in crc start 

### Actual
having errors in crc start and Log in as the developer user:

---
oc login -u developer https://api.crc.testing:6443
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

error: dial tcp: lookup oauth-openshift.apps-crc.testing: no such host
---------------

### Logs

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.
[crc-start-log-linux.txt](https://github.com/code-ready/crc/files/4495183/crc-start-log-linux.txt)

**Comment by gbraad** [comment]
```
DEBU Running '/home/crcusr/.crc/bin/oc get pod --kubeconfig /home/crcusr/.crc/machines/crc/kubeconfig --context admin --cluster crc'
DEBU
DEBU Running '/home/crcusr/.crc/bin/oc delete pod --all -n openshift-apiserver --kubeconfig /home/crcusr/.crc/machines/crc/kubeconfig --context admin --cluster crc'
INFO Starting OpenShift cluster ... [waiting 3m]
DEBU Running '/home/crcusr/.crc/bin/oc get csr --kubeconfig /home/crcusr/.crc/machines/crc/kubeconfig --context admin --cluster crc'
DEBU NAME        AGE     REQUESTOR                        CONDITION
csr-48thb   3m24s   system:node:crc-45nsk-master-0   Pending
csr-lvrkc   4m36s   system:node:crc-45nsk-master-0   Pending
DEBU Running '/home/crcusr/.crc/bin/oc get csr -ojson --kubeconfig /home/crcusr/.crc/machines/crc/kubeconfig --context admin --cluster crc'
DEBU Approving csr csr-48thb
DEBU Running '/home/crcusr/.crc/bin/oc adm certificate approve csr-48thb --kubeconfig /home/crcusr/.crc/machines/crc/kubeconfig --context admin --cluster crc'
DEBU Approving csr csr-lvrkc
DEBU Running '/home/crcusr/.crc/bin/oc adm certificate approve csr-lvrkc --kubeconfig /home/crcusr/.crc/machines/crc/kubeconfig --context admin --cluster crc'
INFO
INFO To access the cluster, first set up your environment by following 'crc oc-env' instructions
INFO Then you can access it by running 'oc login -u developer -p developer https://api.crc.testing:6443'
INFO To login as an admin, run 'oc login -u kubeadmin -p kKdPx-pjmWe-b3kuu-jeZm3 https://api.crc.testing:6443'
INFO
INFO You can now run 'crc console' and use these credentials to access the OpenShift web console
Making call to close driver server
(crc) Calling .Close
Successfully made call to close driver server
Making call to close connection to plugin binary
Making call to close driver server
(crc) Calling .Close
Successfully made call to close driver server
Making call to close connection to plugin binary
Started the OpenShift cluster
WARN The cluster might report a degraded or error state. This is expected since several operators have been disabled to lower the resource usage. For more information, please consult the documentation
```

which shows no errors on startup. Can you share the actual error you are getting when trying to login?

**Comment by subbarb** [comment]
> ```
> DEBU Running '/home/crcusr/.crc/bin/oc get pod --kubeconfig /home/crcusr/.crc/machines/crc/kubeconfig --context admin --cluster crc'
> DEBU
> DEBU Running '/home/crcusr/.crc/bin/oc delete pod --all -n openshift-apiserver --kubeconfig /home/crcusr/.crc/machines/crc/kubeconfig --context admin --cluster crc'
> INFO Starting OpenShift cluster ... [waiting 3m]
> DEBU Running '/home/crcusr/.crc/bin/oc get csr --kubeconfig /home/crcusr/.crc/machines/crc/kubeconfig --context admin --cluster crc'
> DEBU NAME        AGE     REQUESTOR                        CONDITION
> csr-48thb   3m24s   system:node:crc-45nsk-master-0   Pending
> csr-lvrkc   4m36s   system:node:crc-45nsk-master-0   Pending
> DEBU Running '/home/crcusr/.crc/bin/oc get csr -ojson --kubeconfig /home/crcusr/.crc/machines/crc/kubeconfig --context admin --cluster crc'
> DEBU Approving csr csr-48thb
> DEBU Running '/home/crcusr/.crc/bin/oc adm certificate approve csr-48thb --kubeconfig /home/crcusr/.crc/machines/crc/kubeconfig --context admin --cluster crc'
> DEBU Approving csr csr-lvrkc
> DEBU Running '/home/crcusr/.crc/bin/oc adm certificate approve csr-lvrkc --kubeconfig /home/crcusr/.crc/machines/crc/kubeconfig --context admin --cluster crc'
> INFO
> INFO To access the cluster, first set up your environment by following 'crc oc-env' instructions
> INFO Then you can access it by running 'oc login -u developer -p developer https://api.crc.testing:6443'
> INFO To login as an admin, run 'oc login -u kubeadmin -p kKdPx-pjmWe-b3kuu-jeZm3 https://api.crc.testing:6443'
> INFO
> INFO You can now run 'crc console' and use these credentials to access the OpenShift web console
> Making call to close driver server
> (crc) Calling .Close
> Successfully made call to close driver server
> Making call to close connection to plugin binary
> Making call to close driver server
> (crc) Calling .Close
> Successfully made call to close driver server
> Making call to close connection to plugin binary
> Started the OpenShift cluster
> WARN The cluster might report a degraded or error state. This is expected since several operators have been disabled to lower the resource usage. For more information, please consult the documentation
> ```
> 
> which shows no errors on startup. Can you share the actual error you are getting when trying to login?

--------
Thank you,
below step having an error.
Log in as the developer user:
$ oc login -u developer -p developer https://api.crc.testing:6443
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

error: dial tcp: lookup oauth-openshift.apps-crc.testing: no such host

**Comment by gbraad** [comment]
> error: dial tcp: lookup oauth-openshift.apps-crc.testing: no such host

This indicates an issue with DNS

**Comment by subbarb** [comment]
> > error: dial tcp: lookup oauth-openshift.apps-crc.testing: no such host
> 
> This indicates an issue with DNS

Thanks @gbraad , i learn that system dns no issue.. this message is coming through crc.
could not find solution.

**Comment by gbraad** [comment]
What us in your /etc/resolv.conf and is dnsmasa running?

**Comment by cfergeau** [comment]
```
host -R 3 foo.apps-crc.testing
DEBU SSH cmd err, output: <nil>: foo.apps-crc.testing has address 192.168.130.11
```
This worked during startup though, so this hostname could be resolved?
