### ISSUE TITLE
[BUG] Not possible to start VM with DataVolumes 

### ISSUE THREAD

**Issue by suomiy** [code-ready/crc#1170]
### General information

  * OS: Linux
  * Hypervisor: KVM 
  * Did you run `crc setup` before starting it (Yes)?

## CRC version
```bash
crc version: 1.8.0+0a318dc
OpenShift version: 4.3.8 (embedded in binary
```
  
## CRC status
```bash
CRC VM:          Running
OpenShift:       Running (v4.3.8)
Disk Usage:      19.34GB of 32.72GB (Inside the CRC VM)
Cache Usage:     22.37GB
Cache Directory: /home/$USER/.crc/cache
```

## Host Operating System
```bash
NAME="Arch Linux"
BUILD_ID=rolling
```

### Steps to reproduce

  1. install latest HCO or just install standalone kubevirt v0.26.4 with CDI v1.15.0
  2. create a basic VM with blank 1Gi datavolume OR just attach a PVC which was created by standalone DataVolume
  3. wait for DV import to finish
  4. start VM
  5. VM gets started and the VMI is ready and running but it is impossible to connect to the console
  6. following error can be found in the events
```js
server error. command SyncVMI failed: "LibvirtError(Code=1, Domain=10, Message='internal error: qemu unexpectedly closed the monitor: 2020-04-20T13:00:23.723143Z qemu-kvm: -drive file=/var/run/kubevirt-private/vmi-disks/disk0/disk.img,format=raw,if=none,id=drive-ua-disk0: Could not open '/var/run/kubevirt-private/vmi-disks/disk0/disk.img': Permission denied')"
```

### Expected
The VM can use DataVolumes without permission errors.

**Comment by fabiand** [comment]
@aglitke @awels do you have any idea?

**Comment by masayag** [comment]
Also happens with 
```
crc version: 1.7.0+fa7e558
OpenShift version: 4.3.1 (embedded in binary)
CRC VM:          Running
OpenShift:       Running (v4.3.1)
Disk Usage:      23.1GB of 32.72GB (Inside the CRC VM)
```
And HCO based on https://github.com/kubevirt/hyperconverged-cluster-operator/commit/b40614886453c064be9eb8ba13384c32363ce0a6:
```
KUBEVIRT_VERSION="v0.26.0"
CDI_VERSION="v1.15.0"
NETWORK_ADDONS_VERSION="0.27.7"
```

**Comment by awels** [comment]
This is highly likely a permissions issue on the PV in CRC. AFAIK the PVs in CRC are hostpath based, and the owner is root, but the permissions are 644, so only root can write. Kubevirt is not running as root and thus cannot write to the disk. If you chown the PV directory and file to qemu, it should work.

**Comment by masayag** [comment]
I confirm that changing the permissions of `/var/run/kubevirt-private/vmi-disks/` to `qemu:qemu` allowed the console to open.

**Comment by awels** [comment]
I would change the permissions on whatever directory on the host in CRC the PV is associated with. Both CDI and Kubevirt, actually provide an fsGroup to automatically set the group correctly, however hostpath PVs don't respect this.

You can get the directory on the host from the PV yaml.

**Comment by suomiy** [comment]
> Is it possible to start VMs without DVs?

yes

> I would change the permissions on whatever directory on the host in CRC the PV is associated with. Both CDI and Kubevirt, actually provide an fsGroup to automatically set the group correctly, however hostpath PVs don't respect this.
>
> You can get the directory on the host from the PV yaml.

changing permission of `/mnt/pv-data` to qemu:107 works!

It would be nice if crc already came with these permissions or this issue be documented

**Comment by awels** [comment]
Well CRC is general purpose, you are installing specific kubevirt components that have the qemu:107 requirement. As I said both CDI and Kubevirt attempt to set the permissions correctly with an fsGroup, but unfortunately hostpath based PVs don't respect the fsGroup.

The question now is, where would we document this? CRC is general purpose and doesn't care in general about KubeVirt, so it doesn't make sense to document there. KubeVirt (and CDI) already attempt as best they can to set this correctly, but face the problem that some PVs don't respect the fsGroup (hostpath and NFS being the most visible ones). So should we document in KubeVirt that some storage doesn't respect fsGroup and thus requires some manual intervention to work?

**Comment by suomiy** [comment]
In that case, there could be some general info about this behaviour in CRC documentation, because it uses hostpath as a default - out of the box storage and might come as a suprise to users.

It could also say for example in kubevirt it behaves like this and can be fixed with following steps. But if CRC wants to be general purpose without kubevirt mention, then at least the first part would be helpful.

> So should we document in KubeVirt that some storage doesn't respect fsGroup and thus requires some manual intervention to work?

+1, this one would be also helpful

**Comment by anjannath** [comment]
>In that case, there could be some general info about this behaviour in CRC documentation, because it uses hostpath as a default - out of the box storage and might come as a suprise to users.

There's a document being worked on, that would mention all the modifications/configurations we do for a CRC cluster, and details about the PVs that are created by default will also be part of it i think.
/cc @praveenkumar

**Comment by cfergeau** [comment]
https://github.com/code-ready/crc/wiki/Dynamic-volume-provisioning

**Comment by praveenkumar** [comment]
Closing this since we have document around how to do dynamic volume provisioning for CRC.
