### ISSUE TITLE
[BUG] Error in start and after: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s

### ISSUE THREAD

**Issue by massimogentilini** [code-ready/crc#1171]
### General information
  * OS: Windows
  * Hypervisor: Hyper-V 
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
crc version: 1.8.0+0a318dc
OpenShift version: 4.3.8 (embedded in binary)
  
## CRC status
ERRO Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s

## Host Operating System
See attachment

### Steps to reproduce

  1. perform standard installation checks
  2. start does not finish or provide error
  3. following commands gives same error
 
### Expected
A working setup

### Actual
A non working one

### Logs
[ver.txt](https://github.com/code-ready/crc/files/4504653/ver.txt)
[crc.log](https://github.com/code-ready/crc/files/4504656/crc.log)
[win.txt](https://github.com/code-ready/crc/files/4504659/win.txt)

**Comment by praveenkumar** [comment]
@massimogentilini In the logs I can see `A CodeReady Containers VM for OpenShift 4.3.8 is already running` which means there is already a crc instance on hyper-V side. Can you do the following?

```
> crc.exe delete
> Stop-VM -Name "crc" -Force
> Remove-VM -Name "crc" -Force
> crc.exe start
```

**Comment by massimogentilini** [comment]
I've tried this but with no results.
Attach you can find two additional log files:
- log_before_delete.log: it's a full log from a started up PC, so without the VM running, same error
- log_after_delete.log: it's the log after deleting the VM (I had to turn it off from Hyper-V manager because the stop command does not work for the same error)

[log_before_delete.log](https://github.com/code-ready/crc/files/4515353/log_before_delete.log)
[log_after_delete.log](https://github.com/code-ready/crc/files/4515389/log_after_delete.log)


Do you know a way to add some log in the GO section without rebuilding everything (tried that but I'm unable to setup a PC dedicated to this) so that I can add some log in the go code that emit that error??? Or is someone able to do so and build it?

**Comment by massimogentilini** [comment]
As a general comment the commands given via the CRC command can be also given manually, like for example logging in the web console.

I still have a non-working CRC but I can access the cluster via the following operations:

Created two entries in the hosts file that refers to the IP address of the VM (can be found in the start logs, starting if via the --log-level debug option:
 172.17.124.226 console-openshift-console.apps-crc.testing
 172.17.124.226 api.crc.testing

Add the folder with OC in the path (userfolder \.crc\bin)

Then you can use the OC command given by the start command and login to the webconsole with the kubeadmin user (password is always written in the start logs) via browsing to
  https://console-openshift-console.apps-crc.testing/

My suggestion is to provide this way of working in the documentation.

**Comment by praveenkumar** [comment]
@massimogentilini that means the dns on the host is not working as expected, we are working on fallback method but it will take some time.

**Comment by anjannath** [comment]
Goodhosts as a fallback was added in https://github.com/code-ready/crc/pull/1136

**Comment by cfergeau** [comment]
This seems to be a hyperv issue, which does not have goodhosts support yet. And even if the issue would be worked around by the fallback, we still want to fix the non-fallback dns configuration isue. In my opinion this means we should keep this bug open if we plan to figure out the non-fallback use case.
