### ISSUE TITLE
CRC won't start on RHEL 8.1 - cannot find /dev/kvm

### ISSUE THREAD

**Issue by shuawest** [code-ready/crc#1172]
### General information

  * OS: Linux 
  * Hypervisor: KVM 
  * Did you run `crc setup` before starting it (Yes/No)?  **Yes**

## CRC version
```bash
crc version: 1.8.0+0a318dc
OpenShift version: 4.3.8 (embedded in binary)
```
  
## CRC status
```bash
Machine 'crc' does not exist. Use 'crc start' to create it.
```

## CRC config
```bash
- cpus                                  : 8
- enable-experimental-features          : false
- memory                                : 10240
- pull-secret-file                      : /home/jowest/dev/apps/crc/crc180/pull-secret.txt
```

## Host Operating System
```bash
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.1 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.1"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.1 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.1:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.1
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.1"
```

### Steps to reproduce
  1. install NetworkManager and libvirt on RHEL 8.1 
  2. crc setup; crc start on RHEL 8.1

### Expected
expected CRC to start successfully

### Actual

$ crc start
INFO Checking if oc binary is cached
INFO Checking if podman remote binary is cached
INFO Checking if running as non-root
INFO Checking if Virtualization is enabled
INFO Checking if KVM is enabled
FATA kvm kernel module is not loaded

### Logs

$ crc start
INFO Checking if oc binary is cached
INFO Checking if podman remote binary is cached
INFO Checking if running as non-root
INFO Checking if Virtualization is enabled
INFO Checking if KVM is enabled
FATA kvm kernel module is not loaded
[jowest@jowestvivo2 repos]$ crc start --log-level debug
DEBU No new version available. The latest version is 1.8.0
INFO Checking if oc binary is cached
DEBU oc binary already cached
INFO Checking if podman remote binary is cached
DEBU podman remote binary already cached
INFO Checking if running as non-root
INFO Checking if Virtualization is enabled
DEBU Checking if the vmx/svm flags are present in /proc/cpuinfo
DEBU CPU virtualization flags are good
INFO Checking if KVM is enabled
DEBU Checking if /dev/kvm exists
DEBU kvm kernel module is not loaded
FATA kvm kernel module is not loaded

# Notes
CRC works on my RHEL 7.6 box, but fails on RHEL 8.1. Even though I'm able to create kvm based VMs on the host, CRC preflight checks isn't able to detect that kvm is available on RHEL 8.1. 

RHEL 8.1 either 
a) needs some additional prereq install directions, or 
b) the preflight check for kvm (looking for the presence of `/dev/kvm') is not valid for 8.1

**Comment by cfergeau** [comment]
This is working fine for me on 8.1 so this is not a global crc on 8.1 issue.
Do you have /dev/kvm? Does `lsmod |grep kvm`. You can also try `virt-host-validate` if you have this installed.

**Comment by shuawest** [comment]
I found the root cause. virtualization wasn't enabled in my bios, but thought It was due to the kvm module showing up, and the vmx flag showing up in /proc/cpuinfo.  Once I enabled it the `kvm_intel' module showed up as well

# Before
$ lsmod |grep kvm
kvm                   761856  0
irqbypass              16384  1 kvm

# After
$ lsmod |grep kvm
kvm_intel             290816  0
kvm                   761856  1 kvm_intel
irqbypass              16384  1 kvm

Based on your advice the virt-host-validate helped me get to this conclusion. 
$ virt-host-validate
  QEMU: Checking for hardware virtualization                                 : PASS
  QEMU: Checking if device /dev/kvm exists                                   : FAIL (Check that the 'kvm-intel' or 'kvm-amd' modules are loaded & the BIOS has enabled virtualization)
  QEMU: Checking if device /dev/vhost-net exists                             : PASS
  QEMU: Checking if device /dev/net/tun exists                               : PASS
  QEMU: Checking for cgroup 'cpu' controller support                         : PASS
  QEMU: Checking for cgroup 'cpuacct' controller support                     : PASS
  QEMU: Checking for cgroup 'cpuset' controller support                      : PASS
  QEMU: Checking for cgroup 'memory' controller support                      : PASS
  QEMU: Checking for cgroup 'devices' controller support                     : PASS
  QEMU: Checking for cgroup 'blkio' controller support                       : PASS
  QEMU: Checking for device assignment IOMMU support                         : WARN (No ACPI DMAR table found, IOMMU either disabled in BIOS or not supported by this hardware platform)

Thanks!
