### ISSUE TITLE
default serviceNetwork range clashes with internal network range

### ISSUE THREAD

**Issue by byroncollins** [code-ready/crc#1173]
### General information

  * OS: Linux
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it: (Yes)

## CRC version
```bash
crc version: 1.8.0+0a318dc
OpenShift version: 4.3.8 (embedded in binary)
```
  
## CRC status
```bash
CRC VM:          Running
OpenShift:       Running (v4.3.8)
Disk Usage:      18.15GB of 32.72GB (Inside the CRC VM)
Cache Usage:     11.8GB
Cache Directory: /home/byronc/.crc/cache
```

## CRC config
```bash
- cpus                                  : 6
- http-proxy                            : http://172.30.18.80:3128
- https-proxy                           : http://172.30.18.80:3128
- memory                                : 20480
- no-proxy                              : localhost,.datacom.co.nz,datacom.net.nz,.testing
- pull-secret-file                      : /home/byronc/temp/redhat-pull-secret.yaml
```

## Host Operating System
```bash
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
```

### Steps to reproduce

I'm standing up a code ready containers cluster on a private network that clashes with the default serviceNetwork of  172.30.0.0/16. I'm unable to route or pull down images via our proxy server which is in the same range.

```bash
[~]$ oc get events
LAST SEEN   TYPE      REASON    OBJECT                         MESSAGE
14m         Normal    Pulling   pod/crc-45nsk-master-0-debug   Pulling image "registry.redhat.io/rhel7/support-tools"
14m         Warning   Failed    pod/crc-45nsk-master-0-debug   Failed to pull image "registry.redhat.io/rhel7/support-tools": rpc error: code = Unknown desc = error pinging docker registry registry.redhat.io: Get https://registry.redhat.io/v2/: proxyconnect tcp: dial tcp 172.30.18.80:3128: connect: no route to host
14m         Warning   Failed    pod/crc-45nsk-master-0-debug   Error: ErrImagePull
13m         Normal    BackOff   pod/crc-45nsk-master-0-debug   Back-off pulling image "registry.redhat.io/rhel7/support-tools"
13m         Warning   Failed    pod/crc-45nsk-master-0-debug   Error: ImagePullBackOff
[~]$
```

### Expected

Is it possible to override the default serviceNetwork with another /16 range to avoid the clash with our internal network ranges?

```yaml
#oc get network/cluster -o yaml
apiVersion: config.openshift.io/v1
kind: Network
metadata:
  creationTimestamp: "2020-03-27T15:07:53Z"
  generation: 2
  name: cluster
  resourceVersion: "1718"
  selfLink: /apis/config.openshift.io/v1/networks/cluster
  uid: 8d443d00-96f1-4450-89af-dc88ef7d6a9b
spec:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  externalIP:
    policy: {}
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
status:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  clusterNetworkMTU: 1450
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
```

**Comment by praveenkumar** [comment]
@byroncollins we never tried that and this is more of like openshift related issue then CRC. As per docs https://docs.openshift.com/container-platform/4.3/networking/cluster-network-operator.html#nw-operator-cr_cluster-network-operator should be configurable but when I tried then looks like network operator become in degraded state which says you can't change `ServiceNetwork`

```
status:
  conditions:
  - lastTransitionTime: "2020-04-21T04:36:41Z"
    message: 'Not applying unsafe configuration change: invalid configuration: [cannot
      change ServiceNetwork]. Use ''oc edit network.operator.openshift.io cluster''
      to undo the change.'
```

**Comment by byroncollins** [comment]
Thanks @praveenkumar 
According to this Red Hat solution you can't modify the network after deployment
https://access.redhat.com/solutions/4873171

> Note: Network configuration cannot be changed after deployment:  https://docs.openshift.com/container-platform/4.3/installing/install_config/customizations.html#informational-resources_customizations:

If you want to configure different network settings you have to configure it before installation

**Comment by gbraad** [comment]
We do not allow customization when starting as we 'pre-deploy' the cluster. A possible way around this would be to generate your own images 'code-ready/snc'

**Comment by praveenkumar** [comment]
@byroncollins yes, CRC is kind of a cached cluster so not possible for it. Closing this one.

**Comment by byroncollins** [comment]
@gbraad  thanks for the info on code-ready/sync I'll have a look at generating my own images.
Cheers
