### ISSUE TITLE
Changing CRC hostname from the default (api.crc.testing and apps-crc.testing)

### ISSUE THREAD

**Issue by shuawest** [code-ready/crc#1182]
### General information

I'm running multiple CRCs on some extra hosts at home, and [accessing them remotely](https://gist.github.com/tmckayus/8e843f90c44ac841d0673434c7de0c6a). I'd like to change the hostname from the default. As I understand there used to be a `--public-hostname` configuration setting for minishift and/or CRC.  

Is there a config setting, or steps I can take, to change the hostname from the default `api.crc.testing` and `apps-crc.testing`?

**Comment by cfergeau** [comment]
You can find some discussion related to what you are asking in https://github.com/code-ready/crc/issues/705
As crc provides a pre-installed openshift cluster which was configured to use these domains at installation time, these domain names cannot be changed.

**Comment by praveenkumar** [comment]
Closing this one is currently out of scope of CRC and #705 is mostly to track it if something changes.
