### ISSUE TITLE
[BUG]Win32 internal error "Access is denied" 0x5 occurred while reading the console output buffer

### ISSUE THREAD

**Issue by jeffsaremi** [code-ready/crc#1184]
### General information

  * OS: Windows
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
crc version: 1.8.0+0a318dc
OpenShift version: 4.3.8 (embedded in binary)

```

## Host Operating System
```bash
Windows Server 2019
```
We're running the installation steps under OpenSSH and under an administrative account.
UAC is tuned off.
The installation goes successfully until we get the following error. At this time, the "crc" VM appears to be running:

```
(crc) Starting VM...
(crc) DBG | [stdout =====>] :
(crc) DBG | [stderr =====>] :
(crc) DBG | [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Hyper-V\Start-VM crc
(crc) DBG | [stdout =====>] :
(crc) DBG | [stderr =====>] : Hyper-V\Start-VM : Win32 internal error "Access is denied" 0x5 occurred while reading the console output buffer.
(crc) DBG | Contact Microsoft Customer Support Services.
(crc) DBG | At line:1 char:1
(crc) DBG | + Hyper-V\Start-VM crc
(crc) DBG | + ~~~~~~~~~~~~~~~~~~~~
(crc) DBG |     + CategoryInfo          : NotSpecified: (:) [Start-VM], VirtualizationException
(crc) DBG |     + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.StartVM
(crc) DBG |
(crc) DBG |
Making call to close driver server
(crc) Calling .Close
Successfully made call to close driver server
Making call to close connection to plugin binary
```

I'd like to know if anyone else has run into this issue?

**Comment by jeffsaremi** [comment]
The access-denied message seems to be related to the issue of calling crc start from an SSH session. It seems that regardless of the admin privileges of the ssh user and UAC being turned off one can still get this error.

For now we have got around the issue by running crc start as a Windows scheduled task (but on demand)

**Comment by johannesthoma** [comment]
Hi I found this issue when I searched for the issue caption. I ran across this bug when running a powershell script via ssh (more precisely via virter vm ssh). The solution I found is to disable rhe progress bar. To disable the progress bar, run

`$ProgressPreference = "SilentlyContinue"`

in powershell before doing anything else. It would be interesting to know if that also solves also the issue you observe.

**Comment by JKTraining** [comment]
Worked like a charm - damn progress bar !

**Comment by davidmatson** [comment]
FYI - the root cause of this error may be the same as mentioned here:
https://github.com/chef/chef/issues/7765#issuecomment-2033454208

**Comment by Myst95** [comment]
> Worked like a charm - damn progress bar !

Very fucking progress bar !

**Comment by 111100001** [comment]
> Hi I found this issue when I searched for the issue caption. I ran across this bug when running a powershell script via ssh (more precisely via virter vm ssh). The solution I found is to disable rhe progress bar. To disable the progress bar, run
> 
> `$ProgressPreference = "SilentlyContinue"`
> 
> in powershell before doing anything else. It would be interesting to know if that also solves also the issue you observe.

ran into this issue when running a poweshell script from a sandbox environment in Sandboxie. this solution fixed it.
