### ISSUE TITLE
[BUG] ERRO Failed to query DNS from host: lookup api.crc.testing: no such host

### ISSUE THREAD

**Issue by sr4kaushal** [code-ready/crc#1185]
### General information

  * OS: Linux
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
# Put `crc version` output here

crc version: 1.9.0+a68b5e0
OpenShift version: 4.3.10 (embedded in binary)
```
  
## CRC status
```bash
# Put `crc status` output here
```
$ crc status
ERRO error: stat /home/ubuntu/.crc/machines/crc/kubeconfig: no such file or directory
 - exit status 1 

## CRC config
```bash
# Put `crc config view` output here
```
Empty

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

### Steps to reproduce

  1. Installed as per Red_Hat_CodeReady_Containers-1.9-Getting_Started_Guide-en-US.pdf

### Expected
Success

### Actual
ubuntu@controller:~$ crc start
INFO Checking if oc binary is cached              
INFO Checking if podman remote binary is cached   
INFO Checking if running as non-root              
INFO Checking if Virtualization is enabled        
INFO Checking if KVM is enabled                   
INFO Checking if libvirt is installed             
INFO Checking if user is part of libvirt group    
INFO Checking if libvirt is enabled               
INFO Checking if libvirt daemon is running        
INFO Checking if a supported libvirt version is installed 
INFO Checking if crc-driver-libvirt is installed  
INFO Checking if libvirt 'crc' network is available 
INFO Checking if libvirt 'crc' network is active  
INFO Checking if NetworkManager is installed      
INFO Checking if NetworkManager service is running 
INFO Checking if /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf exists 
INFO Checking if /etc/NetworkManager/dnsmasq.d/crc.conf exists 
? Image pull secret [? for help] **************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************

INFO Loading bundle: crc_libvirt_4.3.10.crcbundle ... 
INFO Checking size of the disk image /home/ubuntu/.crc/cache/crc_libvirt_4.3.10/crc.qcow2 ... 
INFO Creating CodeReady Containers VM for OpenShift 4.3.10... 
INFO Verifying validity of the cluster certificates ... 
INFO Check internal and public DNS query ...      
INFO Check DNS query from host ...                
ERRO Failed to query DNS from host: lookup api.crc.testing: no such host 
ubuntu@controller:~$ 

### Logs

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

https://gist.github.com/sr4kaushal/24e93a2db1a4d3257c217c6285c68f4d

**Comment by praveenkumar** [comment]
Since you are running it on ubuntu can you please take a look to #549 and add comment there if you face any issue. I am closing this one.

**Comment by rogerywoo** [comment]
For me, this issue was Verizon's DNS Assistance.  I had to opt out of DNS Assistance.  Basically change the DNS from  ...12 to ...14:

You look up the DNS information and the server numbers are:

    123.123.123.12 primary DNS
    123.123.123.12 secondary DNS

You would change the addresses to the following:

    123.123.123.14 primary DNS
    123.123.123.14 secondary DNS
