### ISSUE TITLE
nothing in oc -n openshift-monitoring get pods ( no promtheus module) 

### ISSUE THREAD

**Issue by doyoungim999** [code-ready/crc#1191]
### General information

  * OS: Linux 
  * Hypervisor: KVM 
  * Did you run `crc setup` before starting it (Yes/No)?

## CRC version
```bash
# Put the output of `crc version`
```
crc version: 1.9.0+a68b5e0
OpenShift version: 4.3.10 (embedded in binary)
  
## CRC status
```bash
# Put the output of `crc status`
```

## CRC config
```bash
# Put the output of `crc config view`
```
[user1@bm3 ~]$ crc status
CRC VM:          Running
OpenShift:       Running (v4.3.10)
Disk Usage:      14.14GB of 32.72GB (Inside the CRC VM)
Cache Usage:     11.94GB
Cache Directory: /home/user1/.crc/cache

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```
[user1@bm3 ~]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

### Steps to reproduce

1. how can I have monitoring pods in openshift-monitoring ? 
[user1@bm3 ~]$ oc -n openshift-monitoring get pods
No resources found in openshift-monitoring namespace.

 

### Expected
prometheus pods are deployed in namespace "openshift-monitoring"

### Actual
Nothing there 

### Logs

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by cfergeau** [comment]
https://code-ready.github.io/crc/#starting-monitoring-alerting-telemetry_gsg explains how to enable these. They are disabled due to their quite high memory usage.

**Comment by doyoungim999** [comment]
Hi 
I configured as the manual provides. I got an error with "no domain selected!". Is there any guidance?
![image](https://user-images.githubusercontent.com/6082088/80364581-c8bd5f00-884b-11ea-8b14-d3c080575462.png)

**Comment by doyoungim999** [comment]
I fixed this issue by adding the route name in /etc/hosts again. 

thank you

**Comment by cfergeau** [comment]
If DNS is correctly configured on the machine running `crc`, you should not need to manually edit `/etc/hosts`
