### ISSUE TITLE
Crc is taking long time to boot up...

### ISSUE THREAD

**Issue by ManikantaMaddipati** [code-ready/crc#1199]
CRC is taking long time to boot up.

using : `crc start -p pull-secret. to start`

Is there way to Directly start the cluster?

```
WARN A new version (1.9.0) has been published on https://cloud.redhat.com/openshift/install/crc/installer-provisioned 
INFO Checking if oc binary is cached              
INFO Checking if podman remote binary is cached   
INFO Checking if running as non-root              
INFO Checking if Virtualization is enabled        
INFO Checking if KVM is enabled                   
INFO Checking if libvirt is installed             
INFO Checking if user is part of libvirt group    
INFO Checking if libvirt is enabled               
INFO Checking if libvirt daemon is running        
INFO Checking if a supported libvirt version is installed 
INFO Checking if crc-driver-libvirt is installed  
INFO Checking if libvirt 'crc' network is available 
INFO Checking if libvirt 'crc' network is active  
INFO Checking if NetworkManager is installed      
INFO Checking if NetworkManager service is running 
INFO Checking if /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf exists 
INFO Checking if /etc/NetworkManager/dnsmasq.d/crc.conf exists 
INFO Starting CodeReady Containers VM for OpenShift 4.3.1... 
INFO Verifying validity of the cluster certificates ... 
INFO Check internal and public DNS query ...      
INFO Check DNS query from host ...                
INFO Starting OpenShift cluster ... [waiting 3m]  
INFO                                              
INFO To access the cluster, first set up your environment by following 'crc oc-env' instructions 
```

Regards

**Comment by gbraad** [comment]
> Is there way to Directly start the cluster?

Not really understanding what you mean.

> Crc is taking long time to boot up... 

You are starting a VM with a full production-like cluster, which needs time to reconcile state before it becomes usable, hence the

> INFO Starting OpenShift cluster ... [waiting 3m]

The total start up time can take over 5minutes due to this. Even if the VM was 'pre-heated' (hot start - by having it run ALL the time), the startup would still take 3 minutes for OpenShift itself to get into a full working state. Note: having memory consumption when not using is a no-go, so this scenario can not be persued.

What are you suggesting?

**Comment by gbraad** [comment]
> CRC is taking long time to boot up.

  * How much time? 
  * Which platform? Windows, macOS, or Linux?
  * What are the specs of your machine? Brand, memory, CPU, etc
  * What else is running in the background?

**Comment by ManikantaMaddipati** [comment]
Time 10 minutes 

Linux Ubuntu

Dell, 4 core cpu, 8gb ram

Intellij running in background 

Thanks for the reply

**Comment by cfergeau** [comment]
As the crc virtual machines needs 8GB of RAM by itself, I'm afraid 8GB of total RAM on the system is not going to be enough, and will contribute to the perceived slowness.

**Comment by gbraad** [comment]
> Dell, 4 core cpu, 8gb ram

As mentioned, this is using the defaults already... the VM actually needs 8GB of free memory, besides the OS overhead and such.

Note: 10 minutes is long, but sounds about the top end of the cases we have seen. Usually it is around 3 to 5 minutes. But it depends really on the machine and hwo resource intensive it is being used in the meantime.

We are looking into optimizations, but they might take some time. If you do not mind, I will close the issue as there have been several along the same lines, but with slightly more details or discussions.
