### ISSUE TITLE
Offer a simple dynamic storage provisioner in CRC?

### ISSUE THREAD

**Issue by brightzheng100** [code-ready/crc#1205]
### General information

  * OS: macOS
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
# Put the output of `crc version`
crc version: 1.9.0+a68b5e0
OpenShift version: 4.3.10 (embedded in binary)
```
  
## CRC status
```bash
# Put the output of `crc status`
CRC VM:          Running
OpenShift:       Running (v4.3.10)
Disk Usage:      13.06GB of 32.72GB (Inside the CRC VM)
Cache Usage:     12.09GB
Cache Directory: /Users/brightzheng/.crc/cache
```

### Steps to reproduce

I saw there is a list of pre-provisioned PVs:

```
NAME                      CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                                                 STORAGECLASS   REASON   AGE
persistentvolume/pv0001   100Gi      RWO,ROX,RWX    Recycle          Bound       openshift-image-registry/crc-image-registry-storage                           15d
persistentvolume/pv0002   100Gi      RWO,ROX,RWX    Recycle          Available                                                                                 15d
...
persistentvolume/pv0030   100Gi      RWO,ROX,RWX    Recycle          Available                                                                                 15d
```

But no `storageclass` is available now.

### Expected

There should be at least one StorageClass embedded to make a lot of things easier.
May refer to `Kind`'s hostpath to bundle one?
https://github.com/kubernetes-sigs/kind/issues/118

### Actual

No dynamic storage available

**Comment by praveenkumar** [comment]
@brightzheng100 can you try https://github.com/code-ready/crc/wiki/Dynamic-volume-provisioning one as let us know if that manual steps working for you and able to use for you workloads.

**Comment by brightzheng100** [comment]
Yup, for now I'm using [rancher/local-path-provisioner](https://github.com/rancher/local-path-provisioner.git):

```sh
$ oc apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
$ oc annotate storageclass/local-path storageclass.kubernetes.io/is-default-class=true
$ oc get sc
NAME                   PROVISIONER             AGE
local-path (default)   rancher.io/local-path   8m28s
```

Maybe it's just one of the FAQ items so the user can know what potential solutions can be used, or simply make one of the solutions embedded, as selectable add-ons, think of `minikube`?

**Comment by praveenkumar** [comment]
@brightzheng100 yes, we are going to embed the kubevirt hostpath provisioner by default so user can use it for stroage classes. I am going to keep this issue open till we figure out where it would be.

**Comment by grdryn** [comment]
> yes, we are going to embed the kubevirt hostpath provisioner by default so user can use it for stroage classes. I am going to keep this issue open till we figure out where it would be.

@praveenkumar did this ever happen? In crc 1.28.0+ I don't see it at least, so it's not clear to me what provisioner to use for a StorageClass.
