### ISSUE TITLE
[BUG] crc setup corrupts rootless podman

### ISSUE THREAD

**Issue by tanwald** [code-ready/crc#1208]
### General information
* OS: Linux / macOS / Windows
Linux 5.6.8-300.fc32.x86_64
* Hypervisor: KVM / Hyper-V / hyperkit
KVM
* Did you run `crc setup` before starting it (Yes/No)?
Yes

## CRC version
```bash
crc version: 1.9.0+a68b5e0
OpenShift version: 4.3.10 (embedded in binary)
```
  
## CRC status
```bash
CRC VM:          Stopped
OpenShift:       Stopped
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     11.94GB
Cache Directory: /home/tanwald/.crc/cache
```

## CRC config
```bash
- cpus                                  : 10
- memory                                : 51200
```

## Host Operating System
```bash
NAME=Fedora
VERSION="32 (Workstation Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

### Steps to reproduce

  1. run `podman info` (works)
  2. run `crc setup`
  3. run `podman info` (doesn't work any more)

### Expected
Output of `podman info`
### Actual
Output: `Error: could not get runtime: dial unix /run/podman/io.podman: connect: permission denied`

### Logs
NA

**Comment by cfergeau** [comment]
By any chance, did you also add `~/.crc/bin` to your `PATH`? It's a known issue that `crc setup` caches an older version of podman to `~/.crc/bin`. You can use `which podman` to make sure it's your distro version which is used in both cases.

**Comment by tanwald** [comment]
Thank you very much. Yes, removing `~/.crc/bin` from `PATH` solved the issue. Sorry, I thought it's a good idea to use the `~/.crc/bin/oc` to avoid incompatibilities but now I've symlinked to `~/.local/bin`.

**Comment by cfergeau** [comment]
We'll be addressing this issue with podman in the next release(s), it's indeed good to use `oc` from `~/.crc/bin/`.
