### ISSUE TITLE
"udannalmos.app" cannot be opened because the developer cannot be verified

### ISSUE THREAD

**Issue by ariwib** [code-ready/crc#1209]
Hi all, i want to ask about our problem on OS X Catalina after i installed

The problem is always appear **"udannalmos.app" cannot be opened because the developer cannot be verified**

Please help us how to fix that probelm

Thanks

**Comment by Ginevra94** [comment]
I have the same problem. Please help!

**Comment by praveenkumar** [comment]
This is duplicate to https://github.com/code-ready/crc/issues/836 , can you try steps provided in that issue and close this one?

**Comment by sammyze** [comment]
I also have this problem, does anyone know how to fix this?

**Comment by cfergeau** [comment]
Have you checked https://github.com/code-ready/crc/issues/836 ? Is the application really called "udannalmos.app"? Or is it "crc"?

**Comment by Ginevra94** [comment]
![image](https://user-images.githubusercontent.com/64864386/82694785-bea73a00-9c18-11ea-8ec9-466bc7b014d5.jpg)

**Comment by Ginevra94** [comment]
Yes it is called udannalmos, can’t figure out how to fix it

**Comment by anjannath** [comment]
@Ginevra94 @sammyze The issue is that our binaries are not signed, we are already working on it, you guys can follow the instructions in https://github.com/code-ready/crc/issues/836#issuecomment-557585330 for a workaround, closing this as duplicate, please keep an eye on the other issue, Thank!
