### ISSUE TITLE
Create "myproject" for developer

### ISSUE THREAD

**Issue by gorkem** [code-ready/crc#1223]
Create an initial project `myproject` for the `developer` user. Minisihft had this functionality which makes the getting started easier.

**Comment by gbraad** [comment]
Do we want to remain production-like or handhold and create a minishift-like preppulated environment? I am asking as I believe this should be more for documentation maybe... the overal developer story from beginning... to deploy the cluster, to using odo and actually deploy your first application to running and maintaining it on the cluster from the dashboard/oc command.

**Comment by gbraad** [comment]
one of the things we discussed a long time ago, and still think is doable and maybe preferred, is a 'first use experience'. A popup from the systray or something, like maybe a first app we deploy and open the browser to, that will tell you "Welcome to OpenShift. .... blab lah. Now, login usin the developer user. oc login and create your first project.", etc.

**Comment by gbraad** [comment]
as @kowen mentioned, there is a need of documentation that is a bit more generic; the overall developer story that lives above the tools (developer tools?) and creates this seamless flow among them...

**Comment by gorkem** [comment]
You do not need to own all the developer story on crc documents. It is not practical,  tools will make changes/improvements on their flow at their own pace that you will not be able to follow. Also developers will not use CRC only with tools that we provide, they will use other tools as well. For that being able to utilize agreed interfaces such as `kubeconfig` becomes important. Besides our tools also depends on such interfaces too.

**Comment by gbraad** [comment]
> For that being able to utilize agreed interfaces such as kubeconfig becomes important. 

This means that the issue is actually around setting up a `kubeconfig` with a predefined context and not per se the "myproject"

**Comment by gorkem** [comment]
I suppose namespace can be anything. It is just a continuation of minishift. Also I believe `odo` uses the same name on docs/help.

**Comment by gorkem** [comment]
Still valid

**Comment by anjannath** [comment]
If we want to ship with this initial "myproject" namespace created, this probably should be done in snc.

**Comment by praveenkumar** [comment]
@anjannath I agree, let's migrate it to snc repo and have a copy here also because in last meeting we thought to have default context for crc is `crc-developer` so we need to switch to the project also when it happen.
