### ISSUE TITLE
CRC internal login registry issue .

### ISSUE THREAD

**Issue by devopskarthikeyan** [code-ready/crc#1226]
Hi CRC Team,

*We are running CRC on Windows 10 pro.
* Trying docker build and push binaries to internal CRC  registry for deployment , But we can able to build and not able to push the image to CRC internal registry & Also not able to do docker login with help of " Kubeadmin" & " Developer" user.  Given VM logs below.

=========
C:\Users\karthi> crc setup                                                                                                                                                              INFO Checking if oc binary is cached
INFO Checking if podman remote binary is cached                                                                                                                                                INFO Checking if CRC bundle is cached in '$HOME/.crc'                                                                                                                                          INFO Checking if running as normal user                                                                                                                                                        INFO Checking Windows 10 release                                                                                                                                                               INFO Checking if Hyper-V is installed and operational                                                                                                                                          INFO Checking if user is a member of the Hyper-V Administrators group
INFO Checking if Hyper-V service is enabled
INFO Checking if the Hyper-V virtual switch exist
INFO Found Virtual Switch to use: Default Switch
Setup is complete, you can now run 'crc start' to start the OpenShift cluster
C:\Users\karthi> crc start -n 8.8.8.8                                                                                                                                                   WARN A new version (1.10.0) has been published on https://cloud.redhat.com/openshift/install/crc/installer-provisioned
INFO Checking if oc binary is cached
INFO Checking if podman remote binary is cached
INFO Checking if running as normal user
INFO Checking Windows 10 release
INFO Checking if Hyper-V is installed and operational
INFO Checking if user is a member of the Hyper-V Administrators group
INFO Checking if Hyper-V service is enabled
INFO Checking if the Hyper-V virtual switch exist
INFO Found Virtual Switch to use: Default Switch
INFO Starting CodeReady Containers VM for OpenShift 4.3.8...
INFO Verifying validity of the cluster certificates ...
INFO Adding 8.8.8.8 as nameserver to the instance ...
INFO Will run as admin: add dns server address to interface vEthernet (Default Switch)
INFO Check internal and public DNS query ...
INFO Check DNS query from host ...
INFO Starting OpenShift cluster ... [waiting 3m]
INFO
INFO To access the cluster, first set up your environment by following 'crc oc-env' instructions
INFO Then you can access it by running 'oc login -u developer -p https://api.crc.testing:6443'
INFO To login as an admin, run 'oc login -u kubeadmin -p  https://api.crc.testing:6443'
INFO
INFO You can now run 'crc console' and use these credentials to access the OpenShift web console
Started the OpenShift cluster
WARN The cluster might report a degraded or error state. This is expected since several operators have been disabled to lower the resource usage. For more information, please consult the documentation
fiedErrorId : CommandNotFoundException

C:\Users\karthi> crc oc-env                                                                                                                                                             $Env:PATH = "C:\Users\karthi\.crc\bin;$Env:PATH"
# Run this command to configure your shell:
# & crc oc-env | Invoke-Expression

C:\Users\karthi> $Env:PATH = "C:\Users\karthi\.crc\bin;$Env:PATH"                                                                                                                   C:\Users\karthi> oc login -u kubeadmin -p kKdPx-pjmWe-b3kuu-jeZm3 https://api.crc.testing:6443                                                                                          Login successful.

You have access to 54 projects, the list has been suppressed. You can list all projects with 'oc projects'

Using project "axisodc".

C:\Users\karthi> crc config view                                                                                                                                                        C:\Users\karthi> crc config                                                                                                                                                             Modifies crc configuration properties.
Configurable properties (enter as SUBCOMMAND):

 * bundle
 * cpus
 * disable-update-check
 * enable-experimental-features
 * http-proxy
 * https-proxy
 * memory
 * nameserver
 * no-proxy
 * pull-secret-file
 * skip-check-administrator-user
 * warn-check-administrator-user
 * skip-check-bundle-cached
 * warn-check-bundle-cached
 * skip-check-hyperv-installed
 * warn-check-hyperv-installed
 * skip-check-hyperv-service-running
 * warn-check-hyperv-service-running
 * skip-check-hyperv-switch
 * warn-check-hyperv-switch
 * skip-check-user-in-hyperv-group
 * warn-check-user-in-hyperv-group
 * skip-check-windows-version
 * warn-check-windows-version

Usage:
  crc config SUBCOMMAND [flags]
  crc config [command]

Available Commands:
  get         Get a crc configuration property
  set         Set a crc configuration property
  unset       Unset a crc configuration property
  view        Display all assigned crc configuration properties

Flags:
  -h, --help   help for config

Global Flags:
  -f, --force              Forcefully perform an action
      --log-level string   log level (e.g. "debug | info | warn | error") (default "info")

Use "crc config [command] --help" for more information about a command.
C:\Users\karthi> oc policy add-role-to-user registry-viewer kubeadmin                  clusterrole.rbac.authorization.k8s.io/registry-viewer added: "kubeadmin"
C:\Users\karthi> oc policy add-role-to-user registry-editor kubeadmin
clusterrole.rbac.authorization.k8s.io/registry-editor added: "kubeadmin"
C:\Users\karthi> oc project openshift-image-registry
Now using project "openshift-image-registry" on server "https://api.crc.testing:6443".
C:\Users\karthi> oc get pods
NAME                                              READY   STATUS    RESTARTS   AGE
cluster-image-registry-operator-5c4dc465b-ncpkf   2/2     Running   10         41d
image-registry-7fc96b9dc4-tcb4j                   1/1     Running   4          41d
node-ca-crff4                                     1/1     Running   5          41d
C:\Users\karthi> oc getall
Error: unknown command "getall" for "oc"
Run 'oc --help' for usage.
C:\Users\karthi> oc get all
NAME                                                  READY   STATUS    RESTARTS   AGE
pod/cluster-image-registry-operator-5c4dc465b-ncpkf   2/2     Running   10         41d
pod/image-registry-7fc96b9dc4-tcb4j                   1/1     Running   4          41d
pod/node-ca-crff4                                     1/1     Running   5          41d

NAME                              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)     AGE
service/image-registry            ClusterIP   172.30.10.177   <none>        5000/TCP    41d
service/image-registry-operator   ClusterIP   None            <none>        60000/TCP   41d

NAME                     DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
daemonset.apps/node-ca   1         1         1       1            1           kubernetes.io/os=linux   41d

NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/cluster-image-registry-operator   1/1     1            1           41d
deployment.apps/image-registry                    1/1     1            1           41d

NAME                                                        DESIRED   CURRENT   READY   AGE
replicaset.apps/cluster-image-registry-operator-5c4dc465b   1         1         1       41d
replicaset.apps/image-registry-7fc96b9dc4                   1         1         1       41d
replicaset.apps/image-registry-f5d7599cc                    0         0         0       41d

NAME                                     HOST/PORT                                                 PATH   SERVICES         PORT    TERMINATION   WILDCARD
route.route.openshift.io/default-route   default-route-openshift-image-registry.apps-crc.testing          image-registry   <all>   reencrypt     None
C:\Users\karthi> docker login -u kubeadmin -p $(oc whoami -t) default-route-openshift-image-registry.apps-crc.testing --tls-verify=false
unknown flag: --tls-verify
See 'docker login --help'.
C:\Users\karthi> docker login -u kubeadmin -p $(oc whoami -t) default-route-openshift-image-registry.apps-crc.testing --engine-tlsverify=false
unknown flag: --engine-tlsverify
See 'docker login --help'.
C:\Users\karthi> docker login -u kubeadmin -p $(oc whoami -t) default-route-openshift-image-registry.apps-crc.testing
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://default-route-openshift-image-registry.apps-crc.testing/v2/: x509: certificate signed by unknown authority

C:\Users\karthi> docker login -u kubeadmin -p $(oc whoami -t) default-route-openshift-image-registry.apps-crc.testing TLSVerifyClient=never
"docker login" requires at most 1 argument.
See 'docker login --help'.

=============================

**Comment by praveenkumar** [comment]
```
C:\Users\karthi> docker login -u kubeadmin -p $(oc whoami -t) default-route-openshift-image-registry.apps-crc.testing TLSVerifyClient=never
"docker login" requires at most 1 argument.
```

`docker login` doesn't support ` --tls-verify=false` or any other options for tls verification, what you need to do is open your docker for desktop perference and add `default-route-openshift-image-registry.apps-crc.testing` as insecure registry and then following should works.
```
$ docker login -u kubeadmin -p $(oc whoami -t) default-route-openshift-image-registry.apps-crc.testing
```

**Comment by devopskarthikeyan** [comment]
Thanks Praveen. Its working now .
