### ISSUE TITLE
Add JSON output to commands to support IDE integration

### ISSUE THREAD

**Issue by mohitsuman** [code-ready/crc#1227]
### Enhancement Request
~~To improve CRC integration with IDEs, we can leverage `crc daemon` command to be consumed directly from IDE.~~

- ~~Currently the daemon is started along with the system tray, there needs to be a way to start the daemon without loading the tray.~~

----

See #13. We will add support to allow the basic commands `status`, `start`, `stop` and `version` to output JSON for use by the IDE integration.

**Comment by praveenkumar** [comment]
@mohitsuman `crc daemon` already exist, what did you try and doesn't work or what more you want as part of daemon, it will help us to prioritize this issue. Do update it once you have more details.

**Comment by gbraad** [comment]
@anjannath provided some code to be able to talk to the daemon:

```
const net = require('net');
const homedir = require('os').homedir();
const path = require('path');

const SOCKET_PATH = path.join(homedir, ".crc", "crc.sock");

function sendCommand(command, args) {
    if (command === "") {
        console.log("Command is required!!")
        return
    }

    sock = net.createConnection(SOCKET_PATH, () => {
        sock.on('error', (e) => {
            console.error(e)
        })

        cmd = {
            "command": command,
            "args": args
        }

        console.log(JSON.stringify(cmd))

        sock.write(JSON.stringify(cmd));

        // receive json response
        sock.on('data', (d) => {
            console.log(d.toString())
        })

        sock.on('error', (e) => {
            console.log(e)
        })

    })
}

sendCommand("version")
```

However, we need to plan a follow-up meeting for this. Originally we did not intent to run a daemon process on Linux, but this might be needed?

**Comment by dgolovin** [comment]
This specific feature we can implement as a vscode status line extension. It would look exactly the same as implementation for system tray on windows. 
Thank you for example @gbraad. I like that is is possible to detect if demon is running. That would let to initialize status line element after vscode is started.

If linux and macos implementation could just provide the same functionality except system tray. That would let vscode to provide this feature on all supported platforms: win, mac and linux.

**Comment by gbraad** [comment]
Windows woukd likely have to use named pipes
See #1384 for more info and related PR

**Comment by gbraad** [comment]
The daemon at the moment only exists for Windows and macOS.
You would prefer to run this without systray?

**Comment by gbraad** [comment]
Modified the issue to relfect the discussion we had. We will add JSON putput to the commands as origjnally proposed by #13.

**Comment by cfergeau** [comment]
So IDEs will run the `crc` binary directly with the parameters they need, and they'll get json output? json input is not required, it's ok for the IDE to build the command line 'manually'?

**Comment by mohitsuman** [comment]
I think https://github.com/code-ready/crc/pull/1429 changes will be in next release then. for `crc version -ojson`

**Comment by guillaumerose** [comment]
Most commands support it now.
