### ISSUE TITLE
[BUG] Events seem to be missing from my pod/namespace

### ISSUE THREAD

**Issue by jeffsaremi** [code-ready/crc#1229]
### General information

  * OS:  Windows
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it (Yes/No)?
  * Running CRC on: VM

My pod crashed for no reason in the middle of my testing. Now I'm trying to find out what's going on. Here are the weird things I see:

- oc describe reports no events for the pod
- oc get events reports no events for the namespace

Is there a trick to getting these?

**Comment by gbraad** [comment]
Please refer to OpenShifts documentation or ask on StackExchange/StackOverflow. This is not the right place for generic OpenShift questions.

**Comment by gbraad** [comment]
https://stackoverflow.com/questions/tagged/openshift

**Comment by gbraad** [comment]
Note: you might want to get the logs instead
