### ISSUE TITLE
Document possibility to access container registry using docker/podman locally

### ISSUE THREAD

**Issue by maxandersen** [code-ready/crc#1230]
### General information

https://github.com/code-ready/crc/issues/147 says access to container registry is possible but that seems to not be the case - at least it is not documented.

Ask is to be able to get container registry access so can use docker, podman, jib, etc. to build and push containers locally without requiring remote quay etc.

**Comment by gbraad** [comment]
https://github.com/code-ready/crc/issues/147#issuecomment-577151340

**Comment by gbraad** [comment]
Rather make this dependent on the clients beinmg available and the podman functionality going GA.

**Comment by maxandersen** [comment]
thanks for link to the comment - I didn't spot it as I was looking the docs ;) 

it would be nice with a `crc env docker` command or similar one could use to do the login/setup docker env etc.

> Rather make this dependent on the clients beinmg available and the podman functionality going GA.

Not following what you mean here? I don't need any custom clients or podman to push to registry; lots of things can do push, including maven/gradle builds.

**Comment by gbraad** [comment]
> it would be nice with a crc env docker command or similar one could use to do the login/setup docker env etc.

We will likely not be introducing a `docker-env` command, but `podman-env` would be possible to set values for this.

**Comment by maxandersen** [comment]
container-env Or registry-env works If goal is to avoid product/project specific names.

**Comment by cfergeau** [comment]
`container-env` goes nicely with the `Containerfile` naming alternative (to `Dockerfile`)
