### ISSUE TITLE
How to run under FIPS mode?

### ISSUE THREAD

**Issue by ScrapCodes** [code-ready/crc#1231]
### General information

  * OS: Linux / macOS / Windows Linux : RHEL FIPS Enabled.
  * Hypervisor: KVM / Hyper-V / hyperkit : KVM 
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop / Baremetal-Server / VM: Baremetal-Server

Is this already documented, I was not able to find any details around it. If I am running on a FIPS enabled system, does crc runs Openshift under FIPS mode?

**Comment by ScrapCodes** [comment]
How to verify?

**Comment by cfergeau** [comment]
Do you know if OpenShift FIPS mode can be toggled after OpenShift install? I know that you can enable it at install time, but I don't know if that's the only possibility.
If it can only be enabled at OpenShift install time, then it's not going to be possible to use FIPS mode with crc. If it can be enabled on a running cluster (ie if you can do it manually), then crc could automatically enable it when detected, however at the moment it does not do anything related to fips.

**Comment by gbraad** [comment]
This is an install time option for OpenShift and therefore is not applied to CRC:

   To install a cluster in FIPS mode, follow the instructions to install a customized cluster on your preferred infrastructure. Ensure that you set fips: true in the install-config.yaml file before you deploy your cluster.

Ref: https://docs.openshift.com/container-platform/4.3/installing/installing-fips.html#installing-fips-mode_installing-fips

**Comment by gbraad** [comment]
But can you explain to me why you would like this enabled? It seems unrelated to development practices, but rather runtime and security. For example, it guaranteesthat when users SSH into OpenShift Container Platform clusters and containers, those connections are properly encrypted.

**Comment by ScrapCodes** [comment]
Well, I needed it for development and testing.

I wanted to write some validations specific to FIPS mode, for the software I am going to run on top of Openshift deployment. Openshift can be FIPS compliant, but we need to make sure that anything that runs on top of that should also be FIPS compliant/validated. For this, It is sort of important that, underlying stack is also FIPS compliant.

**Comment by gbraad** [comment]
It is a very specific usecase so I would suggest you to run the installer instead to create a small test environment. You can use the scripts at code-ready/snc for this if you prefer a single node cluster setup.
