### ISSUE TITLE
[BUG] horizontalpodautoscaler.autoscaling not working

### ISSUE THREAD

**Issue by slashTPA** [code-ready/crc#1232]
### General information

  * OS: Linux 
  
  * Did you run `crc setup` before starting it - Yes
  * Running CRC on: Laptop

## CRC version
crc version: 1.10.0+9025021
OpenShift version: 4.4.3 (embedded in binary)

  
## CRC status
```[__tpa@p5540 ~]$ crc status --log-level debug
DEBU Running '/home/__tpa/.crc/bin/oc get co -ojson --kubeconfig /home/__tpa/.crc/machines/crc/kubeconfig --context admin --cluster crc' 
DEBU About to run SSH command:
df -B1 --output=size,used,target /sysroot | tail -1 
DEBU SSH cmd err, output: <nil>: 32719437824 13025239040 /sysroot 
CRC VM:          Running
OpenShift:       Running (v4.4.3)
Disk Usage:      13.03GB of 32.72GB (Inside the CRC VM)
Cache Usage:     23.84GB
Cache Directory: /home/__tpa/.crc/cache
[__tpa@p5540 ~]$ 



## CRC config
``[__tpa@p5540 ~]$ crc config view
- cpus                                  : 64
- memory                                : 32768
`

## Host Operating System
[__tpa@p5540 ~]$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.2"
[__tpa@p5540 ~]$ 

### Steps to reproduce
simply crc start and then set e.g. like in DO101 class:
[__tpa@p5540 ~]$ oc autoscale dc/scale --max=3 --cpu-percent=20
horizontalpodautoscaler.autoscaling/scale autoscaled

### Expected
Adjustment of Pod's due to heavy load.

### Actual
No adjustment is happening - all the load is handled by one pod only :-(
[__tpa@p5540 ~]$ oc get pods
NAME                      READY   STATUS      RESTARTS   AGE
scale-1-8vmmq             1/1     Running     0          15m
scale-1-build             0/1     Completed   0          16m
scale-1-deploy            0/1     Completed   0          15m
stress-1-build            0/1     Completed   0          5m44s
stress-5f844d9664-z462w   1/1     Running     0          31s


Also no status metrics, such as CPU Usage,... are available in the Web-UI. 

Thanks for looking into it.

**Comment by gbraad** [comment]
Based on the description it is not possible to determine if the autoscaling does not work. I miss some information. It seems you are targeting this with a stress test that has run for 31secs? What does the test do, what kind of load does it introduce. The test perhaps influence the cluster as it also runs alongside... would it be possible to run this outside of the cluster?

> Also no status metrics, such as CPU Usage,... are available in the Web-UI. 
But yes, as you can see from the release notes and [documentation](https://github.com/code-ready/crc/blob/master/docs/source/topics/con_differences-from-production-openshift-install.adoc), we have disabled monitoring. This might be the reason for the behaviour? Can you try to enable this and see if this affects the results.

Also, provide the information to check if the HPA is created/active: https://docs.openshift.com/container-platform/3.9/dev_guide/pod_autoscaling.html#viewing-a-hpa

**Comment by slashTPA** [comment]
Hi,

 

How would I enable monitoring in crc?

 

Cheers,
Thomas

 

Von: Gerard Braad <notifications@github.com> 
Gesendet: Sonntag, 10. Mai 2020 11:07
An: code-ready/crc <crc@noreply.github.com>
Cc: slashTPA <thomas.paetzold@magenta.de>; Author <author@noreply.github.com>
Betreff: Re: [code-ready/crc] [BUG] horizontalpodautoscaler.autoscaling not working (#1232)

 

Based on the description it is not possible to determine if the autoscaling does not work. I miss some information. It seems you are targeting this with a stress test that has run for 31secs? What does the test do, what kind of load does it introduce. The test perhaps influence the cluster as it also runs alongside... would it be possible to run this outside of the cluster?

Also no status metrics, such as CPU Usage,... are available in the Web-UI.
But yes, as you can see from the release notes and documentation <https://github.com/code-ready/crc/blob/master/docs/source/topics/con_differences-from-production-openshift-install.adoc> , we have disabled monitoring. This might be the reason for the behaviour? Can you try to enable this and see if this affects the results.

Also, provide the information to check if the HPA is created/active: https://docs.openshift.com/container-platform/3.9/dev_guide/pod_autoscaling.html#viewing-a-hpa

**Comment by slashTPA** [comment]
What I tried:

[__tpa@p5540 ~]$ oc get clusterversion version -ojsonpath='{range .spec.overrides[*]}{.name}{"\n"}{end}' | nl -v 0
     **0	cluster-monitoring-operator**
     1	machine-config-operator
     2	etcd-quorum-guard
     3	machine-api-operator
     4	cluster-autoscaler-operator
     5	insights-operator
     6	prometheus-k8s
     7	cloud-credential-operator
     8	csi-snapshot-controller-operator
     9	cluster-storage-operator
    10	kube-storage-version-migrator-operator

So next step - enable monitoring:
[__tpa@p5540 ~]$ oc patch clusterversion/version --type='json' -p '[{"op":"remove", "path":"/spec/overrides/0"}]' -oyaml
I get metrics now in Web-UI :-)

Next step - enable the cluster-autoscaler-operator
[__tpa@p5540 ~]$ oc get clusterversion version -ojsonpath='{range .spec.overrides[*]}{.name}{"\n"}{end}' | nl -v 0
     0	machine-config-operator
     1	etcd-quorum-guard
     2	machine-api-operator
     **3	cluster-autoscaler-operator**
     4	insights-operator
     5	prometheus-k8s
     6	cloud-credential-operator
     7	csi-snapshot-controller-operator
     8	cluster-storage-operator
     9	kube-storage-version-migrator-operator

[__tpa@p5540 ~]$ oc patch clusterversion/version --type='json' -p '[{"op":"remove", "path":"/spec/overrides/3"}]' -oyaml

Nothing changes :-( After 
[__tpa@p5540 ~]$ oc autoscale dc/scale --max=3 --cpu-percent=5
horizontalpodautoscaler.autoscaling/scale autoscaled

still the same - no scaling of running pod 'scale' happens, althrough load is climbing high (see pictures attached)
![scale-2](https://user-images.githubusercontent.com/29278443/81503326-4faa1700-92e3-11ea-98ac-8adf9d14bccf.png)


[__tpa@p5540 ~]$ oc get pods
NAME                      READY   STATUS      RESTARTS   AGE
scale-1-8vmmq             1/1     Running     0          8h
scale-1-build             0/1     Completed   0          8h
scale-1-deploy            0/1     Completed   0          8h
stress-1-build            0/1     Completed   0          7h50m
stress-5f844d9664-vh55c   1/1     Running     0          3m8s



Not sure if that is intended like this:

[__tpa@p5540 ~]$ oc get hpa/hpa-resource-metrics-cpu
Error from server (NotFound): horizontalpodautoscalers.autoscaling "hpa-resource-metrics-cpu" not found

**Comment by gbraad** [comment]
> Not sure if that is intended like this:

That should be verified against an actual cluster and a single node cluster before 'disabling' the operators.

**Comment by praveenkumar** [comment]
As per https://docs.openshift.com/container-platform/4.4/nodes/pods/nodes-pods-autoscaling.html#nodes-pods-autoscaling-creating-cpu_nodes-pods-autoscaling does the prerequisite section says states `PodMetrics` should be enabled before you can use the autoscaler, not sure if you checked this. Also as @gbraad stated does those steps works with real cluster (multiple master and worker) ?

**Comment by slashTPA** [comment]
As this is a demo case from the official RH Training DO101 it was showcased to be working in the class with OpenShift cluster. On my OKD4 I failed now as well to get auto scaling...and simply hit the 80% CPU load on a the single pod. So I guess these are premium features only.

**Comment by cfergeau** [comment]
Let's reopen this, CodeReady Containers tries to be as close to an actual OpenShift cluster as possible, so it would be good to understand why something in OpenShift training material is not working on crc.

**Comment by gbraad** [comment]
> So I guess these are premium features only.

I can assure you that this is not the case with OpenShift. The development cluster of CRC should behave like any other installed OpenShift 4.x cluster. There are exceptions due to resource usage, but they could be enabled (and are documented). For this we simply do not understand yet why this does not work, hence the question to test this on AWS. Not meaning we force you to, but rather if you had experience with this before or not. We will certainly look into this, but at the moment not the highest priority (so feedback appreciated).

**Comment by slashTPA** [comment]
Lost track due to other issues.
