### ISSUE TITLE
Registry not accessible: Image pull back error

### ISSUE THREAD

**Issue by devopskarthikeyan** [code-ready/crc#1235]
Hi Team,

I am using CRC on Windows 10 pro, Whenever i try to run below command we are getting " Image pull error" and not able to do deployment .

1. Docker build - working fine
2. Docker Push<CRC internal registry> -- working fine
3. oc new-app -i <iam-mxcomponentapi:1.0> -- **### Getting error** (getting imagepullback 
error)

Logs:

```
PS C:\Users\\DevOps-Release\kafka> oc describe pod iamapi-1-deploy
Name:         iamapi-1-deploy
Namespace:    axisodc
Priority:     0
Node:         crc-45nsk-master-0/
Start Time:   Fri, 08 May 2020 17:29:26 +0530
Labels:       openshift.io/deployer-pod-for.name=iamapi-1
Annotations:  k8s.v1.cni.cncf.io/networks-status:
              openshift.io/deployment-config.name: iamapi
              openshift.io/deployment.name: iamapi-1
              openshift.io/scc: restricted
Status:       Failed
Reason:       DeadlineExceeded
Message:      Pod was active on the node longer than the specified deadline
IP:           10.128.0.55
IPs:
  IP:  10.128.0.55
Containers:
  deployment:
    Container ID:
    Image:          quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:07601faa48f9042bb7a7336a8bed5de9249bd3f3d1509c6f4a65b0d
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Environment:
      OPENSHIFT_DEPLOYMENT_NAME:       iamapi-1
      OPENSHIFT_DEPLOYMENT_NAMESPACE:  axisodc
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from deployer-token-stl7r (ro)
Volumes:
  deployer-token-stl7r:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  deployer-token-stl7r
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```

Kindly check and help on this please .

Thanks,
P.Karthikeyan

**Comment by praveenkumar** [comment]
@devopskarthikeyan check https://github.com/code-ready/crc/issues/821#issuecomment-555862714 one you just can't use the imagestream as it is.

**Comment by devopskarthikeyan** [comment]
Hi Praveen,
we are running CRC on windows 10 &  whenever we do " crc start " with out "-n 8.8.8.8" getting below issue.

PS C:\Users\Tagitdemo2\DevOps-Release\today\IAM> crc stop
Stopping the OpenShift cluster, this may take a few minutes...
Stopped the OpenShift cluster
PS C:\Users\Tagitdemo2\DevOps-Release\today\IAM> crc setup
INFO Checking if oc binary is cached
INFO Checking if podman remote binary is cached
INFO Checking if CRC bundle is cached in '$HOME/.crc'
INFO Checking if running as normal user
INFO Checking Windows 10 release
INFO Checking if Hyper-V is installed and operational
INFO Checking if user is a member of the Hyper-V Administrators group
INFO Checking if Hyper-V service is enabled
INFO Checking if the Hyper-V virtual switch exist
INFO Found Virtual Switch to use: Default Switch
Setup is complete, you can now run 'crc start' to start the OpenShift cluster
PS C:\Users\Tagitdemo2\DevOps-Release\today\IAM> crc start 
WARN A new version (1.10.0) has been published on https://cloud.redhat.com/openshift/install/crc/installer-provisioned
INFO Checking if oc binary is cached
INFO Checking if podman remote binary is cached
INFO Checking if running as normal user
INFO Checking Windows 10 release
INFO Checking if Hyper-V is installed and operational
INFO Checking if user is a member of the Hyper-V Administrators group
INFO Checking if Hyper-V service is enabled
INFO Checking if the Hyper-V virtual switch exist
INFO Found Virtual Switch to use: Default Switch
INFO Starting CodeReady Containers VM for OpenShift 4.3.8...
INFO Verifying validity of the cluster certificates ...
INFO Adding 192.168.86.122 as nameserver to the instance ...
INFO Will run as admin: add dns server address to interface vEthernet (Default Switch)
INFO Check internal and public DNS query ...
WARN Failed public DNS query from the cluster: ssh command error:
command : host -R 3 quay.io
err     : Process exited with status 1
output  : ;; connection timed out; no servers could be reached
 :
INFO Check DNS query from host ...

============================

2. Hence we tried the option " crc start -n 8.8.8.8"  now crc statrd with out any issues but we are getting error on deployment . Below are logs.

Events:
  Type     Reason     Age                  From                         Message
  ----     ------     ----                 ----                         -------
  Normal   Scheduled  <unknown>            default-scheduler            Successfully assigned axisodc/iam10-1-deploy to crc-45nsk-master-0
  Warning  Failed     3m16s                kubelet, crc-45nsk-master-0  Failed to pull image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:07601faa48f9042bb7a7336a8bed5de9249bd3f3d1509c6f4a65b0d80684a47e": rpc error: code = Unknown desc = error pinging docker registry quay.io: Get https://quay.io/v2/: dial tcp 54.152.57.199:443: i/o timeout
  Normal   Pulling    94s (x3 over 4m16s)  kubelet, crc-45nsk-master-0  Pulling image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:07601faa48f9042bb7a7336a8bed5de9249bd3f3d1509c6f4a65b0d80684a47e"
  Warning  Failed     34s (x3 over 3m16s)  kubelet, crc-45nsk-master-0  Error: ErrImagePull
  Warning  Failed     34s (x2 over 2m1s)   kubelet, crc-45nsk-master-0  Failed to pull image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:07601faa48f9042bb7a7336a8bed5de9249bd3f3d1509c6f4a65b0d80684a47e": rpc **error: code = Unknown desc = error pinging docker registry quay.io: Get https://quay.io/v2/: dial tcp 54.145.51.104:443: i/o timeout**
  Normal   BackOff    5s (x4 over 3m16s)   kubelet, crc-45nsk-master-0  Back-off pulling image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:07601faa48f9042bb7a7336a8bed5de9249bd3f3d1509c6f4a65b0d80684a47e"
  **Warning  Failed     5s (x4 over 3m16s)   kubelet, crc-45nsk-master-0  Error: ImagePullBackOff**

we are working on windows and there is no solution around it .. All sloution about into Linux.
Please check and help me resolve the above issues.

Thanks,
P.Karthikeyan

**Comment by devopskarthikeyan** [comment]
Hi Team,

Is there any update on this request please.

**Comment by anjannath** [comment]
@devopskarthikeyan Did you try out what praveen suggested in https://github.com/code-ready/crc/issues/821#issuecomment-555862714 and that solves your issues?

The issue with dns looks like a different one, did you push your image to the internal registry or quay.io?
