### ISSUE TITLE
Retain the pull secret information 

### ISSUE THREAD

**Issue by gorkem** [code-ready/crc#1239]
Can we retain the pull secret information after a `crc delete`? The idea is to persist the pull secret after a successful start of cluster automatically so that we do not need to send the user to pull secret download as often.

**Comment by gbraad** [comment]
Use `crc config set pull-secret-file`:

https://github.com/code-ready/crc/blob/master/cmd/crc/cmd/config/config.go#L18

... When implementing the config dialogs for Windows and macOS we weill consider using trhe native keystores: #1104

**Comment by gbraad** [comment]
Marking as duplicate of #1104
