### ISSUE TITLE
How to retrieve kubeadmin password?

### ISSUE THREAD

**Issue by csantanapr** [code-ready/crc#1240]
How to retrieve kubeadmin password?

If this is already available using `crc` cli please let me know, I was not able to find a way I expected sometingin `crc config` or `crc kubeadmin` to give me the initial password that prints when running `crc start`
```
INFO To login as an admin, run 'oc login -u kubeadmin -p jh3kL-Te6cD-BKDG7-3rvSu https://api.crc.testing:6443'
```

**Comment by gorkem** [comment]
`crc console --credentials` as described on https://code-ready.github.io/crc/#accessing-the-openshift-web-console_gsg

**Comment by csantanapr** [comment]
@gorkem your telling me to RTFM? 😄

**Comment by csantanapr** [comment]
I'm looking for the credentials so I can `oc login` never cross my mind to look under `console`

Can we have `crc login` to log me in. or `crc credentials` and print what `crc console --credentials` prints?

**Comment by csantanapr** [comment]
TIL
```shell
cat ~/.crc/bin/oc-credentials
#!/usr/bin/env sh
crc console --credentials
```
```shell
oc credentials
To login as a regular user, run 'oc login -u developer -p developer https://api.crc.testing:6443'.
To login as an admin, run 'oc login -u kubeadmin -p jh3kL-Te6cD-BKDG7-3rvSu https://api.crc.testing:6443'
``

**Comment by gbraad** [comment]
> initial password

An initial password can be provided as this is done of the image genration. If we add logic for this, the start procedure would take longer. Would that be acceptable?

**Comment by gorkem** [comment]
> I'm looking for the credentials so I can `oc login` never cross my mind to look under `console`

@gbraad This sentence is the actual issue. I have seen multiple people fall into this, last time we have added the docs but the command is not intuitive and docs are not a replacement for good UX. I think ` --credentials` flag needs to move to its own command.

**Comment by gbraad** [comment]
> I think --credentials flag needs to move to its own command.

And I think we should avoid having the user to look for this in the first place. Either make this static, but this led to security concerns, or make this VERY abvious each time CRC is used. Like enriching the start output and `oc-env`:

```
$ eval `crc oc-env`
Note: the kubeadmin password is: "Ge*$#((@d". This is also stored as $CRC_KUBEADMIN_PASSWORD
```

and also stored in an environment variable for use.

The problem does not get solved by just a command, as when the system tray flow is considered, we would also have to deal with this is in a reasonable fashion. The use of `developer/developer` is OK, why not `kubeadmin/kubeadmin` to avoid all of this and rely on a mental model.

**Comment by gorkem** [comment]
> And I think we should avoid having the user to look for this in the first place.

We shoulf take advantage of the _kubecontext_. All k8s related tools use kubecontext.  Setting the _kubecontext_  #1216 should help with most cases, except for actually visiting the console

**Comment by csantanapr** [comment]
@gbraad Can you explain why “crc credentials” increase the time ? Is the same command as “crc console —credentials” 

It will take the same amount of time if “crc credentials” calls “crc console —credentials”

**Comment by gbraad** [comment]
> Can you explain why “crc credentials” increase the time ?

That is not what I implied:

> An initial password can not be provided as this is done of the image genration. If we add logic for this, the start procedure would take longer.

as a means to provide `crc config kubeadmin-password` to reconfigure this password.

**Comment by csantanapr** [comment]
@gbraad 

Thanks for the explanation. 

I don’t want to reconfigure the kubeadmin password my requirement is just easy to find and read only the current kubeadmin password. 

I agree 💯 that if the password is static kubeadmin/kubeadmin that would be even a better solution.

**Comment by gbraad** [comment]
this should be part of the image generation, as 'updating'/'changing' the secrets will considerably influence the startup time: https://docs.openshift.com/container-platform/3.7/dev_guide/secrets.html#secrets-and-the-pod-lifecycle as the pods that use the secret needs to be deleted and recreated.

**Comment by anjannath** [comment]
What remains to be done here? the OP 's issue is fixed as he's able to find the command, do we want to add a top level command to make it more discoverable or add static password for kubeadmin too?

**Comment by csantanapr** [comment]
I would like to see something done to be more discoverable

Today I type "crc console" and it opens the browser and would never guess that "console" has more flags to get the password. 

What about a top level command to alias to "crc console --password" ?

Not sure where is best
"crc config get password"
"crc password"

**Comment by praveenkumar** [comment]
We again discussed this during one of the meeting but no conclusion, we should able to decide soon and fix it.

**Comment by csantanapr** [comment]
If we end up implementing a command like `crc credentials`  I think we should print a message about the command at the end of `crc start` in there we print out the credentilas to `oc login` but we can add something like `to retrieve the kubeadmin credentias use the command` `crc credentials`

**Comment by taylormgeorge91** [comment]
I was brought to this issue for a similar concern. For those that may be interested in a way to retrieve the crc's oc login command for the kubeadmin user can use something similar to this (tested on MacOS 10.14.6 and CRC `1.20.0+ef3f80d`):

`crc console --credentials | grep kubeadmin | awk -F"'" '{print $2}'`

**Comment by csantanapr** [comment]
@taylormgeorge91 

the main problem is usability and discoverable 

No one is going to use “crc console help” to find the CLI credentials for kubeadmin 

but there is better chance that people use “crc help” and find a toplevel command to get kubeadmin password even if it’s one is static 

having a command like “crc kubeadmin” that just prints is a good start and advertise the command at the end of “crc start”

**Comment by jotak** [comment]
+1 with the idea of a command `crc credentials`. This is what I typed intuitively before googling and landing on this page.

**Comment by cameronkerrnz** [comment]
+1 with a top-level command; I certainly was not expecting to find this under crc console when I went to look for it (because I'm training myself to do most of my work using 'oc', and declarative styles of deployment (oc apply -k)

I would be against static configuration of kubeadmin password. Partly because it reinforces sloppy security awareness which is highly dangerous in a K8S environment, and CRC is useful from a admin/security training perspective. A user's CRC experience should therefore be very similar to a production cluster. It's good that TCP/6443 is only reachable on loopback (I'm in vsock mode, so not sure if that is always the case).

On a similar manner, I see that the Kubernetes contexts are being used, but I take it that only keeps the token (which presumably expires) and not the password, as I find I have to 'oc login -u ...' about once a day.

**Comment by gbraad** [comment]
This has moved to the end of the start command as a summary. When the command is rerun, the summary will be shown again.
From the telemetry we can already see people have adopted to use this pattern. We will keep `console --credentials` around for the `-ojson` option

**Comment by ringerc** [comment]
For usability it'd be great to:

* make this more obvious in the `crc` command's help output; and
* make this more search-discoverable in the docs

because

```
$ crc --help

...

Available Commands:
  ...
  console     Open the OpenShift Web Console in the default browser
  ...
```

is _really_ non-obvious as a place to look for

```
$ crc console --help
...
Flags:
      --credentials     Print the credentials for the OpenShift Web Console
```
