### ISSUE TITLE
Possible to run 2 crc instances parallel on same host?

### ISSUE THREAD

**Issue by disposab1e** [code-ready/crc#1250]
Is it possible to run two crc instances paralle on one host?

**Comment by disposab1e** [comment]
Primarly with Centos 8.1...

**Comment by gbraad** [comment]
Technically possible, but not on our todolist as this will cause harm due to conflicts with domain names, resource usage, etc. Duplicate of earlier issue, closing as such

**Comment by gbraad** [comment]
Duplicate of #935
