### ISSUE TITLE
Rename PDF file in archive bundle

### ISSUE THREAD

**Issue by jkopriva** [code-ready/crc#1251]
### General information

  * OS: macOS (But I suppose its in all archives)

## CRC version
1.10 archive

PDF file in archive has name doc.pdf. I think it would be better, if the file have better name like: GettingStarted.pdf or GettingStartedGuide.pdf. Current filename is too generic(Is it guide? Is it release notes?.....).
![image](https://user-images.githubusercontent.com/17871936/82786549-205be400-9e65-11ea-9e6c-c3bef3400a12.png)

**Comment by gbraad** [comment]
@robin-owen suggestions?

**Comment by robin-owen** [comment]
I don't really have a particular opinion on this. Using a name such as "getting-started-guide.pdf" works for me.

**Comment by praveenkumar** [comment]
This should be a easy fix from the makefile.

**Comment by guillaumerose** [comment]
The PDF is gone :tada:
