### ISSUE TITLE
[Enhancement] Handling DNS for CRC

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#1258]
As of now, we create the required configuration on different platform to work with `*.apps-crc.testing` and `api.crc.testing` domains. With https://github.com/code-ready/crc/pull/1136 now an fallback mechanism added to add some of known fqdn to /etc/hosts files for different platform (right now linux/mac). There is also request from some the users that crc shouldn't do any configuration for dns to work and let user handle it. To incorporate all the options we need a way to skip the dns configuration completely or partially. 

This issue is to track what way we want to handle the DNS for CRC.

**Comment by bavibm** [comment]
I would very much appreciate this enhancement, currently I am experiencing slow DNS resolutions when I have CRC running on Windows 10 Enterprise 2004

I am finding the optimal work around for this, if I prioritize my primary network by fixing the time metrics then my DNS resolution works like normal but the web console for CRC becomes slow to resolve,

**Comment by praveenkumar** [comment]
This is now resolved by usermode networking so closing it.
