### ISSUE TITLE
differences between Linux and Windows

### ISSUE THREAD

**Issue by kfrendrich** [code-ready/crc#1259]
### General information

  * OS: Windows
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it: Yes

## CRC version
```bash
crc version: 1.10.0+9025021
OpenShift version: 4.4.3 (embedded in binary)
```
  
## CRC status
```bash
CRC VM:          Running
OpenShift:       Running (v4.4.3)
Disk Usage:      13.9GB of 32.72GB (Inside the CRC VM)
Cache Usage:     14.27GB
Cache Directory: C:\Users\myuser\.crc\cache
```

## CRC config
```bash
- memory                                : 12000
```

## Host Operating System
```bash
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18363 N/A Build 18363
```

Hi.

This is more a question than a bug report.

I experimented with CRC on Linux and Windows.
On Linux, my containers started with the restricted user id that the OpenShift gave them.
That's fine and it worked as I expected.
On Windows they started with the docker image defined user id.
I expected that it should work in the same way as on Linux.
I haven't changed any scc.

I tried to find about differences in the documentation without success.

Is this a known difference or is it possible to reach the same functionality on Windows like on Linux considering these user id?

Thank you for the answers.

**Comment by gbraad** [comment]
Are you sure and not an issue with the client configuration? The images are identical with the exception that we add the hyperv userspace modules.

Can you detail more about the steps and client versions used

**Comment by kfrendrich** [comment]
As I see it was a misunderstood from my side.

When I directly logged-in as a `developer` user (instead of logging in with the administrator and change to developer) it worked as I expected.
