### ISSUE TITLE
Change libvirt driver version info from stderr to stdout after new driver release.

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#126]
As of now https://github.com/code-ready/crc/blob/master/pkg/crc/preflight/preflight_checks_linux.go#L223 we use stderr but since https://github.com/code-ready/machine-driver-libvirt/pull/5 merged so we need to update about version side info when have new driver binary released.

**Comment by gbraad** [comment]
@praveenkumar when to handle the release and this modification?

**Comment by praveenkumar** [comment]
This is done.
