### ISSUE TITLE
Permissions needed for running the daemon service under normal user

### ISSUE THREAD

**Issue by anjannath** [code-ready/crc#1286]
To run the daemon service under the user that is logged in, we need _LogOnAsService_ permission for the user (steps: https://www.opcsupport.com/s/article/How-do-I-configure-a-user-account-to-have-logon-as-a-service-permissions) We do this because we want to use the same `crc` homedir both for our CLI tool and the daemon.

Adding this permission is a security risk as pointed out in slack, another concern is about resource consumption, in the sense that the daemon process can keep running even when the user is logged out. (microsoft link: https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/log-on-as-a-service#vulnerability)

The alternative is to use the `LocalSystem` account to run the daemon service, but since `crc` uses the `%USERPROFILE%/.crc` as the crc homedir, using the `LocalSystem` account creates the `.crc` dir inside `C:\Windows\system32` which we don't want.

Now to fix this we either need to modify our `GetHomeDir()` to decide the homedir based on if its the daemon process (provided we decide to go with using the `LocalSystem` account)
or we keep using the current user, but find a way to automate the addition of _LogOnAsService_ privilege after considering the security and resource consumption concerns.

**Comment by gbraad** [comment]
localsystem is preferred and modify the gethomedir to be using a daemon specific implementation?

**Comment by anjannath** [comment]
Instead of using the `LocalSystem` account, it was suggested to use the current user to run the daemon service, as the `LocalSystem` account has elevated privilages.

To use the current user account, we need to add log on as a service permission for that user, it can be done by using `secedit.exe` tool.

To add the log on as service permission, we first need the current users SID
```posh
> (Get-LocalUser -Name _userName_).Sid.Value
```

Then a security template file like the following is needed `sec.inf`:
```ini
[Unicode]
Unicode=yes
[Version]
signature="$CHICAGO$"
Revision=1
[Privilege Rights]
seservicelogonright = *S-1-5-21-3938078522-2608308634-3841203849-1001,*S-1-5-83-0
```
The above SID `*S-1-5-83-0` is the users SID in this case which is added to the `seservicelogonright` config key

Then run the following command:

```posh
> secedit.exe /configure /db c:\windows\system32\defltbase.sdb /cfg sec.inf /areas USER_RIGHTS
```

**Comment by gbraad** [comment]
Can you list of pros and cons between LocalSystem and a local user with Service login 

Paying attention to:
  * ease of setup
  * running commands with higher privilege
  * ...

**Comment by anjannath** [comment]
`LocalSystem` vs local user account:

|LocalSystem   | Local user  |
|--------------------|----------------|
| Setup is easier as no additional permissions are needed  | Log on as a service permission has to be added as local user account doesn't have this permission by default  |
|  the service can run commands with admin privilegs without UAC prompts | can do the same if the User is also an administrator, if not, execute as admin will just fail, as UAC prompts cannot be shown by services |
|Cleanup doesn't need to do anything | Cleanup has to remove log on as a service right from the local user|
|Doesn't need addtional checks as LocalSystem can always be used to run services | need to actually check if the local user account has the required permissions to run a service |
| Higher (root) level privilege| privileges as defined by the user/admin|

**Comment by cfergeau** [comment]
|Tray starting the daemon |
|----------------------------------|
| No additional permissions are needed during setup, but the tray needs to be aware of the path to the crc binary |
| UAC prompts will be shown when needed (?) |
| Cleanup doesn't need to do anything |
| Doesn't need addtional checks |
| Same privileges as the system tray (user?) |

**Comment by gbraad** [comment]
@cfergeau not sure what you are suggesting. Can you elaborate a little bit more. You are suggesting to have the tray start the daemon?

Take note that we woudl like to achieve some consistency between the implementations too. Does the macOS solution have the tray start the daemon?

The tray process on Windows would still have to be started as a scheduled task or windows/startup to be autostarting.

This would not affect UAC, as the daemon would still run in the background and would not have direct access (like -NoNewWindow)

**Comment by cfergeau** [comment]
> @cfergeau not sure what you are suggesting. Can you elaborate a little bit more. You are suggesting to have the tray start the daemon?

Given the other options (either run the daemon privileged or add a few hundred lines of code for starting the daemon and still have some annoying limitations), yes I'm suggesting having the daemon being started on demand by the tray when needed. Seems much simpler than the alternatives, we don't risk them getting out of sync (tray is autostarted but not the daemon, or the opposite)

> Take note that we woudl like to achieve some consistency between the implementations too. Does the macOS solution have the tray start the daemon?

Apparently not, it's starting it using launchd. However, how to start a service is so OS-specific that it's hard to be that consistent. And nothing prevents us from moving to "tray starts the daemon" on macos too if it makes sense there.


> The tray process on Windows would still have to be started as a scheduled task or windows/startup to be autostarting.

I'm assuming the tray process is already auto-started, which is expected for a tray icon.
