### ISSUE TITLE
Can the kubeadmin password be changed?

### ISSUE THREAD

**Issue by jeffsaremi** [code-ready/crc#1291]
CRC Any Version
Any Platform

Can we change the kubeadmin password? How? thanks

**Comment by gbraad** [comment]
Please see the discussion on: #1240

**Comment by VGerris** [comment]
@gbraad that does not answer the question? I read it is set on image boot time and cannot? 
The thread shows commands for retrieving it, that is not an answer either.
FYI : I am trying to run OKD in CRC and the output of the command does not work for the kubeadmin account.

**Comment by gbraad** [comment]
Running OKD with is another issue. That is being worked on to resolve. Currently some code paths are disabled when not compiling okd-crc.

**Comment by cfergeau** [comment]
When `crc start` creates a VM, it sets a random kubeadmin password, and prints it at the end of the startup process. Once the crc VM is started, changing the kubeadmin password should be possible using OpenShift APIs/tools. The relevant crc code is in https://github.com/code-ready/crc/blob/main/pkg/crc/cluster/kubeadmin_password.go
