### ISSUE TITLE
Commands can be configured to print output in json

### ISSUE THREAD

**Issue by LalatenduMohanty** [code-ready/crc#13]
CRC should be able to give command output in json  if required.

**Comment by gbraad** [comment]
command are expected from `pkg`-level to return a struct to `cmd` level. in that case the cmd can decide the format that is needed from the issues command

**Comment by LalatenduMohanty** [comment]
Here is the odo user experience 
```
$ ./odo  list -o json
{"kind":"List","apiVersion":"odo.openshift.io/v1alpha1","metadata":{},"items":[{"kind":"Component","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"nodejs-ex-nodejs-usjq","creationTimestamp":null},"spec":{"type":"nodejs","source":"file:///home/lmohanty/go/src/github.com/redhat-developer/odo/nodejs-ex"},"status":{"active":true}}]}


$ ./odo  list
ACTIVE     NAME                      TYPE
*          nodejs-ex-nodejs-usjq     nodejs
```

**Comment by gbraad** [comment]
In https://github.com/code-ready/crc/pull/63 I use input arguments for functions what performn the actual action, and return a structured result. This way the `cmd` layer is thin; mostly validation and argument preparation like default values, and all actions happen from `pkg` which return the state using a structure. This way it is possible to host commands using a rest-like API over HTTP, which receives function input arguments as a POST message and return the results to structured JSON.

**Comment by gbraad** [comment]
We are currently implementing this for specific commands that are exposing a daemon
