### ISSUE TITLE
Cluster does not get created with Persistent Volumes

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#130]
Tools like ODO expect Persistent Volumes to exist. the current single node cluster configured as part of the alpha release does not have any set up.

**Comment by praveenkumar** [comment]
https://github.com/code-ready/snc/issues/16

**Comment by heiko-braun** [comment]
Fuse Online deveopment also depends largely on the availability of persistent volumes. It would nice if this could make into one of the next releases.

**Comment by gbraad** [comment]
This is currently being looked into. Will move it to in-progess, but tracking will happen on the issue in the code-ready/snc repo

**Comment by gbraad** [comment]
This is now part of the image bundle
