### ISSUE TITLE
[OperatorHub] Current images have `openshift-marketplace` disabled

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#133]
The current images from code-ready/snc have `openshift-marketplace` disabled, which causes the OperatorHub UI console to be unavailable.

https://github.com/code-ready/snc/blob/01902ef9c51d1183981d2a1d53444a488be9fed9/snc.sh#L100-L101
```
# Disable the deployment/replicaset/statefulset config for openshift-marketplace namespace
${OC} scale --replicas=0 deployment --all -n openshift-marketplace
${OC} scale --replicas=0 replicaset --all -n openshift-marketplace
```

**Comment by gbraad** [comment]
This means that scaling this back to `--replicas=1` would enable the marketplace again.

**Comment by praveenkumar** [comment]
this is already fixed on snc side and now `marketplace` is by default enabled.
