### ISSUE TITLE
Initialize monitoring pipeline for CRC resource consumption

### ISSUE THREAD

**Issue by jsliacan** [code-ready/crc#1333]
Track changes in resource requirements/consumption over time and between CRC editions based on different OCP versions. For this purpose, create a job that will collect and aggregate such data.

### Main aspects

1. Implement in the form of a test feature file. Give it own tag to allow for triggering it in isolation.
2. Data should form a time series tracking variables such as: crc version, ocp version, date+time, cpu + mem requirement, host OS, hypervisor, etc.
3. Data should be uploaded to accessible location.
4. The job should run daily and be more-or-less automated.

**Comment by praveenkumar** [comment]
@jsliacan Shouldn't you already have it with all those aspects?

**Comment by jsliacan** [comment]
Renamed this issue to a specific task. Created project "Monitoring" and move this issue to `Done`. Can be closed now.
