### ISSUE TITLE
[BUG] Using more memory than allocated

### ISSUE THREAD

**Issue by yohanswanepoel** [code-ready/crc#1337]
### General information

  * OS: Linux (Fedora 32)
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)?
  * Running CRC on: Laptop / Baremetal-Server / VM
  * CPU Model name: Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
  * 40GB of RAM

## CRC version
```bash
# Put `crc version` output here
```
CodeReady Containers version: 1.12.0+6710aff
OpenShift version: 4.4.8 (embedded in binary)

  
## CRC status
```bash
# Put `crc status --log-level debug` output here
```
--- Before starting CRC
DEBU CodeReady Containers version: 1.12.0+6710aff 
DEBU OpenShift version: 4.4.8 (embedded in binary) 
CRC VM:          Stopped
OpenShift:       Stopped
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     36.14GB
Cache Directory: /home/johanswanepoel/.crc/cache

## CRC config
```bash
# Put `crc config view` output here
```
- memory                                : 12480

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```
NAME=Fedora
VERSION="32 (KDE Plasma)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (KDE Plasma)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="KDE Plasma"
VARIANT_ID=kde

### Steps to reproduce
-- Memory before starting CRC with top
MiB Mem :  39854.4 total,  34691.3 free,   2744.3 used,   2418.8 buff/cache
MiB Swap:  19992.0 total,  19992.0 free,      0.0 used.  36111.1 avail Mem 

  1. Start CRC
  2. Deploy standard S2I template Python
  3. 
  4. 

### Expected
12GB of memory usages + a bit for KVM

### Actual
MiB Mem :  39854.4 total,  11929.3 free,  16935.0 used,  10990.1 buff/cache
MiB Swap:  19992.0 total,  19992.0 free,      0.0 used.  21816.4 avail Mem 

22GB of memory usage

This after a fresh boot of the machine, but the second time starting the clusters. The first time starting the cluster the memory usage was around 30GB.

Stopping CRC does not return all the memory: 
MiB Mem :  39854.4 total,  25480.5 free,   3349.0 used,  11024.9 buff/cache
MiB Swap:  19992.0 total,  19992.0 free,      0.0 used.  35394.4 avail Mem 

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by gbraad** [comment]
You could first try: `ps aux --sort -rss`, but even `ps` is not the right command as it only shows the reserved amount of memory.

**Comment by praveenkumar** [comment]
Following is what I tried on my system and when I delete the crc it does return the mem back.

```
$ free -g
              total        used        free      shared  buff/cache   available
Mem:             31           8          13           1           9          21
Swap:            15           0          15

$ ./crc start -b ~/Downloads/crc_libvirt_4.4.8.crcbundle
[...]

 $ free -g
              total        used        free      shared  buff/cache   available
Mem:             31          16           0           1          13          12
Swap:            15           0          15

$ crc delete

$ free -g
              total        used        free      shared  buff/cache   available
Mem:             31           8          12           1          10          21
Swap:            15           0          15
```

**Comment by gbraad** [comment]
@praveenkumar are you running a GUI ?

**Comment by yohanswanepoel** [comment]
I did another test -  this time to starting with a fresh cluster (memory consumption doing this is normally worse than it is when restarting a cluster). Steps and results are as per below. 

crc delete
(before starting crc)
free -g
              total        used        free      shared  buff/cache   available
Mem:             38           2          33           0           2          35
Swap:            19           0          19

(assigned 16GB of RAM)
crc start -c 4 -m 16480 -p ./pull-secret.txt

(crc running)
              total        used        free      shared  buff/cache   available
Mem:             38          14           0           0          24          23
Swap:            19           0          19

 ps aux --sort -rss
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
qemu        5989  348 29.3 21093276 11978000 ?   Sl   17:45  20:27 /usr/bin/qemu-system-x86_64 -name guest=crc,debug-threads=on -S -object secret,id=masterKey0,

pmap shows about 21GB used by the proccess - this does not explain where the rest went. That may be virtio-balloon?
sudo pmap 5989 | tail -n 1
 total         21093280K


---------------------------------------------------
crc stop

              total        used        free      shared  buff/cache   available
Mem:             38           2          12           0          23          34
Swap:            19           0          19

**Comment by cfergeau** [comment]
For what it's worth, the numbers before crc start and after crc stop seem consistent to me, I think the relevant numbers are either `available` or `free + buff/cache`, which are close enough before/after. As for the numbers during the run, there's probably some memory consumption from some disk caches, or other things, but which is memory which can be reclaimed by the kernel if needed. You could experiment with https://unix.stackexchange.com/questions/17936/setting-proc-sys-vm-drop-caches-to-clear-cache for example.

**Comment by yohanswanepoel** [comment]
Ah interesting - looks like it is the caches that is hanging around. I see what you mean around "available" vs "free" memory. Available looks okay, whereas free does not. 

So to summarize seeing free memory at zero should be okay as long as available has a healthy number? 

I played around with virtio  autodeflate='on', which seemed to be more memory frugal - but I am not sure if that hinders performance so switched it off again.

Thank you for the helping me understand what is going on.

**Comment by praveenkumar** [comment]
@yohanswanepoel Can we then close this issue?

**Comment by yohanswanepoel** [comment]
Yes thanks.
