### ISSUE TITLE
Bundle compression/decompression takes too much time

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#1340]
The crcbundle is currently compressed using `xz`. This format is not natively supported by Golang and we have to use github.com/xi2/xz library.

On my machine, it takes 3m47s to decompress a bundle using xi2/xz. With `xz` command line tool, it takes 2m20s. 
xi2/xz documentation says:
``` 
// On the author's Intel Ivybridge i5, decompression speed is about
// half that of the standard XZ Utils (tested with a recent linux
// kernel tarball).
``` 
I also tried with https://github.com/ulikunitz/xz and it doesn't finish in less than 5min.

Given that the compression step in snc takes also a huge amount of time (about 30min by bundle if I'm correct), maybe we should investigate an other format.

```
crc_libvirt_4.4.6.crcbundle
xz: 2.0GB
zip (default level): 2.8GB
gzip (default level): 2.8GB
zstd: 2.6GB
```

**Comment by gbraad** [comment]
See #994

**Comment by gbraad** [comment]
Decompression takes even more time on Windows

**Comment by cfergeau** [comment]
On an idle 6 cores/12 threads machine, using threaded compression in snc makes a big difference:
```
$ time xz --keep --threads=0 /home/teuf/.crc/cache/crc_libvirt_4.4.8/crc.qcow2
real    4m36.255s
user    54m17.698s
sys     0m3.416s

$ time xz --keep /home/teuf/.crc/cache/crc_libvirt_4.4.8/crc.qcow2
real    34m48.959s
user    34m46.237s
sys     0m2.710s
```

**Comment by anjannath** [comment]
https://github.com/code-ready/crc/issues/1340#issuecomment-653589793 Improves compression time for our bundle generation. 

The concern with the decompression time on crc side still remains.

**Comment by cfergeau** [comment]
Additional data from https://github.com/code-ready/crc/issues/1893#issuecomment-769067339
`zstd --ultra -22 -T0` gives me a 2.2G tarball which decompresses in 10 seconds
The corresponding crcbundle (4.6.9) is 2.6G and takes 2 minutes to decompress.
(figures to be double checked/confirmed)

**Comment by cfergeau** [comment]
A few more datapoints with zstd, default settings gave me a 3.6GB tarball, so not interesting, `zstd -19` gives a 2.7GB tarball, so it's comparable in size with xz. Decompression time is 13 seconds.

**Comment by cfergeau** [comment]
> `zstd -19` gives a 2.7GB tarball, so it's comparable in size with xz. Decompression time is 13 seconds.

"Decompression time" is only `zstd -d`. You then need to untar the archive, which adds 15 more seconds.
