### ISSUE TITLE
[Integration] Installing operators changed in OCP 4.5

### ISSUE THREAD

**Issue by jsliacan** [code-ready/crc#1344]
### General information

  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / Hyper-V / hyperkit

## CRC version
```bash
CodeReady Containers version: 1.12.0+5a4ca94
OpenShift version: 4.5.0-rc.4 (not embedded in binary)
```

### Steps to reproduce

  1. Run integration tests in `story_marketplace.feature`

### Actual
```bash
bash: oc apply -f etcdop-csc.yaml
stderr: error: unable to recognize "etcdop-csc.yaml": no matches for kind "CatalogSourceConfig" in version "operators.coreos.com/v1"
```
### Logs

[pipeline run](https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/crc_pipeline/503/artifact/crc/test/integration/out/test-results/integration_2020-6-29_12-21-05.log)

**Comment by praveenkumar** [comment]
This is already fixed and now part of integration tests.
