### ISSUE TITLE
crc cleanup on macOS doesn't remove existing crc vm

### ISSUE THREAD

**Issue by anjannath** [code-ready/crc#1346]
On the other platforms (windows and linux) `crc cleanup` removes an existing crc vm but not in the case of macOS

**Comment by praveenkumar** [comment]
It is because we don't have any management cli for hyperkit like we have for libvirt and hyperV, in this case we might need to grab the running hyperkit process and make sure it is crc related then kill it.

**Comment by anjannath** [comment]
Ahh, just checked the `removeCrcVM()` for windows, and it manually deletes the vm without using the machine api, can we not use `machine.Delete()` from the cleanup function?

**Comment by gbraad** [comment]
@anjannath this is referenced by e2f2062. Anything still to be done?

**Comment by cfergeau** [comment]
> Ahh, just checked the `removeCrcVM()` for windows, and it manually deletes the vm without using the machine api, can we not use `machine.Delete()` from the cleanup function?

More than a year later, I'm wondering the same thing, why this ends up duplicating code preexisting in the machine drivers ;)
