### ISSUE TITLE
specifiy a different path for crc so that should not occupy space from the home directory

### ISSUE THREAD

**Issue by ksingh7** [code-ready/crc#1347]
### General information

  * OS: Linux
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Baremetal-Server

## CRC version
```bash
crc version: 1.11.0+883ca49
OpenShift version: 4.4.5 (embedded in binary)
```
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
```

## CRC config
```bash
# Put `crc config view` output here
```

## Host Operating System
```bash
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### Steps to reproduce

  This may not be a bug report rather a question.

Question : the home directory filesystem has a limited space, when i run crc it works but it takes a lot of space for VM and stores that under ~/.crc directory. Is there a way i can specifiy a different path for crc so that should not occupy space from the home directory ?

**Comment by cfergeau** [comment]
You could do that with a symlink or `mount --bind`

**Comment by ksingh7** [comment]
@cfergeau  do you have any example of this by any chance ( related to crc )

**Comment by uril** [comment]
I too encountered this problem, and I used a symbolic link to overcome it:
```
$ U=$USERNAME
$ D=/opt/crc/users/$U # change this as you want
$ sudo mkdir -p $D
$ sudo chown ${U}:${U} $D # on Fedora
$ mkdir $D/.crc
$ ln -s $D/.crc $HOME/.crc
$ crc setup
$ crc start
...
```

**Comment by praveenkumar** [comment]
@ksingh7 hope the steps provided by @uril works for you, also this is not specific to crc issue. Closing this.
