### ISSUE TITLE
macos: waitForNetwork in dns_darwin.go does not deal with ipv6 addresses

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#1349]
On my macos machine, `/etc/resolv.conf` seems to be updated first with ipv6 addresses, and then a bit later with ipv4 addresses.
This causes crc wait to stop when it only contains ipv6 addresses, and try to ping them. Unfortunately, on macos, ping does not seem to know how to deal with ipv6 addresses, ping6 must be used for that.
This result in a (non-fatal) `ERRO Host is not connected to internet.` message during startup.

**Comment by guillaumerose** [comment]
This code is not triggered anymore with the new network stack. I guess we can close this.

**Comment by cfergeau** [comment]
Was minor at the time, and is indeed no longer the default networking mode. Closing now.
