### ISSUE TITLE
Red Hat CodeReady Containers on ppc64le architecture?

### ISSUE THREAD

**Issue by ticlazau** [code-ready/crc#1356]
Hello,

has anyone been able to run Red Hat CodeReady Containers on ppc64le architecture (Power Server with or without GPUs?)

Thank you,
FM

**Comment by gbraad** [comment]
Please see #957 and #1281 for related discussions.

But in short, we do not have the bandwidth and possibility to test this. Though, I heard from @ Prashanth684 they have been able to generate the SNC images, but not sure about the CRC tooling around this.

**Comment by ticlazau** [comment]
The CRC is a great tool for development, and will be very good to be ported on ppc64le.
@Prashanth684 can you share some of your experience?

**Comment by Prashanth684** [comment]
@ticlazau refer to https://github.com/code-ready/snc/pull/209. There is work being done to support ppc64le for snc. This means that a single node cluster can be created pretty easily in a libvirt environment. In fact we have tried it and it works successfully. As for CRC - i'm not sure what the exact use case would be. If the argument is that it provides a great development environment, snc can do the same as well. I mean sure it would be nice to have a minishift like environment for ppc64le/s390x, but CRC was mainly desgned with laptop environments in mind.I don't see a very strong argument for CRC on ppc64le/s390x.

**Comment by mtarsel** [comment]
hello there- please reach out to me on slack (username: mick) or look me up in IBM directory and send an email if you'd like to further discuss this. I'm helping prashanth drive this multi-arch effort but would like to better understand the use case as well.

**Comment by cfergeau** [comment]
> As for CRC - i'm not sure what the exact use case would be. If the argument is that it provides a great development environment, snc can do the same as well.

At this point, I see `snc` as an internal tool targetted at generating crc bundles. Using it for something else may or may not work, but it's likely to be a bit rough around the edges. We've been having some discussions about maybe extending it to more usecases, but no specific plan yet.

**Comment by anjannath** [comment]
@ticlazau @mtarsel This can be closed right, as https://github.com/code-ready/snc/pull/209 was merged! or is there more to be done here?

**Comment by mtarsel** [comment]
I'm ok with closing this out while we focus on snc for ppc64le. This specific issue could always be re-opened at a later time.

@ticlazau if ok with you, close this out?
