### ISSUE TITLE
Developer user cannot login to crc console

### ISSUE THREAD

**Issue by Marisa5373** [code-ready/crc#1371]
[crc.log](https://github.com/code-ready/crc/files/4891758/crc.log)
 After installing crc v 1.12 on macOS Catalina 10.15.5,  the kubeadmin can login to console but the user developer with its default password "developer" cannot login to console.

**Comment by gbraad** [comment]
Make sure to select the htpasswd provider for login

If this still does not work. confirm you can login using the `oc` command: https://github.com/code-ready/crc/blob/76443767aba4925288ae523e9279c67afe7164f3/docs/source/topics/proc_accessing-the-openshift-cluster-with-oc.adoc#accessing-the-openshift-cluster-with-oc

**Comment by Marisa5373** [comment]
after selecting the htpasswd provider, the login with the user developer worked
thanks

**Comment by gbraad** [comment]
This should have been part of the documentation. Was overlooked by accident.

**Comment by robinhood-me** [comment]
How do you use the htpasswd provider when logging into the console?
