### ISSUE TITLE
Image pull fails when creating pods in crc 1.12: certificate signed by unknown authority

### ISSUE THREAD

**Issue by jlerm** [code-ready/crc#1376]
I'm trying to leverage a CodeReady Container 1.12 Openshift instance to deploy an application that otherwise can be deployed on a "real" Openshift 4.3 cluster.
Unfortunately the creation of pods fail with this type of error:
 

  Type     Reason     Age        From                         Message
  ----     ------     ----       ----                         -------
  Normal   Scheduled  <unknown>  default-scheduler            Successfully assigned zen/cpd-install-operator-6cf757d9b5-tkh6j to crc-rtgqw-master-0
  Normal   Pulling    1s         kubelet, crc-rtgqw-master-0  Pulling image "default-route-openshift-image-registry.apps-crc.testing/zen/cpd-operator-init:v1.0.1-x86_64"
  Warning  Failed     1s         kubelet, crc-rtgqw-master-0  Failed to pull image "default-route-openshift-image-registry.apps-crc.testing/zen/cpd-operator-init:v1.0.1-x86_64": rpc error: code = Unknown desc = error pinging docker registry default-route-openshift-image-registry.apps-crc.testing: Get https://default-route-openshift-image-registry.apps-crc.testing/v2/: x509: certificate signed by unknown authority
  Warning  Failed     1s         kubelet, crc-rtgqw-master-0  Error: ErrImagePull
  Normal   BackOff    1s         kubelet, crc-rtgqw-master-0  Back-off pulling image "default-route-openshift-image-registry.apps-crc.testing/zen/cpd-operator-init:v1.0.1-x86_64"
  Warning  Failed     1s         kubelet, crc-rtgqw-master-0  Error: ImagePullBackOff

I was able to successfully expose the internal registry, I can log into it via podman:

$ podman login -u developer -p x1bSkISkc9HHbSyFI1GqtVuv2umgil902OlOATSsT6I --tls-verify=false default-route-openshift-image-registry.apps-crc.testing
Login Succeeded!

I have not replaced the cluster certificate, at all.

Can anyone offer a work around so images can be successfully pulled from the internal registry when pods are created?

The portion of the application related to the error above consists of one deployment, which creates one replicat set (1 replica), which in turn creates a single pod (which in turn fails with the error listed above).

### General information

  * OS: Linux 
  * Hypervisor: KVM 
  * Did you run `crc setup` before starting it (Yes/No)? YES

## CRC version

CodeReady Containers version: 1.12.0+6710aff
OpenShift version: 4.4.8 (embedded in binary)

  
## CRC status

CRC VM:          Running
OpenShift:       Running (v4.4.8)
Disk Usage:      14.37GB of 32.72GB (Inside the CRC VM)
Cache Usage:     12.27GB
Cache Directory: /home/jlerm/.crc/cache

## CRC config

$ crc config view
$

## Host Operating System

Red Hat Enterprise Linux Server release 7.8 (Maipo)

**Comment by praveenkumar** [comment]
@jlerm can you take a look to https://github.com/code-ready/crc/issues/821#issuecomment-555862714 one.

**Comment by anjannath** [comment]
@jlerm Did you follow the instructions in https://github.com/code-ready/crc/issues/821#issuecomment-555862714 and did that work for you?

**Comment by praveenkumar** [comment]
Closing this issue since there is no response form reporter.
