### ISSUE TITLE
Failed to propagate proxy settings to cluster

### ISSUE THREAD

**Issue by jeet1990** [code-ready/crc#1378]
### General information

  * OS: Linux 
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it -YES

## CRC version
```bash
# Put the output of `crc version`
```
[saan@localhost ~]$ crc version
CodeReady Containers version: 1.12.0+6710aff
OpenShift version: 4.4.8 (embedded in binary)
[saan@localhost ~]$

  
## CRC status
```bash
# Put the output of `crc status`
```

[saan@localhost ~]$ crc status
CRC VM:          Running
OpenShift:       Running (v4.4.8)
Disk Usage:      12.15GB of 32.72GB (Inside the CRC VM)
Cache Usage:     12.27GB
Cache Directory: /home/saan/.crc/cache
[saan@localhost ~]$

## CRC config
```bash
# Put the output of `crc config view`
```

[saan@localhost ~]$ crc config view
- cpus                                  : 6
- http-proxy                            : 1x.1xx.xxx.xxx:8080
- https-proxy                           : 1x.1xx.xxx.xx:8080
- memory                                : 12000
- no-proxy                              : localhost,127.0.0.1,192.168.*.*,*.apps-crc.testing

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```
[saan@localhost ~]$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.2"

### Actual
getting the error.
\par \cf15\highlight0 DEBU\cf0  Running '/home/saan/.crc/bin/oc/oc set env deployment redhat-operators --list -n openshift-marketplace --kubeconfig /home/saan/.crc/machines/crc/kubeconfig --context admin --cluster crc'\cf1\highlight2 
\par \cf15\highlight0 DEBU\cf0  Proxy changes for cluster in progress\cf1\highlight2 
\par \cf15\highlight0 DEBU\cf0  error: Temporary Error:  - sleeping 2s\cf1\highlight2 
\par \cf15\highlight0 DEBU\cf0  RetryAfter timeout after 60 tries\cf1\highlight2 
\par \cf15\highlight0 DEBU\cf0  Failed to propagate proxy settings to cluster\cf1\highlight2 
\par \cf7\highlight0 INFO\cf1\highlight2 

### Logs

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

detailed error can be found here.
<script src="https://gist.github.com/jeet1990/69516300f1d4fedbc46a5b323cba0725.js"></script>

**Comment by praveenkumar** [comment]
@jeet1990 you do need to provide `http://` for proxy as mentioned in docs https://code-ready.github.io/crc/#starting-codeready-containers-behind-proxy_gsg so proxy should be `http://1x.1xx.xxx.xxx:8080` for both proxies.

**Comment by jeet1990** [comment]
> 
> 
> @jeet1990 you do need to provide `http://` for proxy as mentioned in docs https://code-ready.github.io/crc/#starting-codeready-containers-behind-proxy_gsg so proxy should be `http://1x.1xx.xxx.xxx:8080` for both proxies.


@praveenkumar @guillaumerose, thanks for help here.

1.
if my understanding is right; these values are set and pushed to crc_vm. so these are used within vm. right?
do i need to set no-proxy for localhost,crc_vm ip, host machine ip and *.testing  ? like the one below

:   localhost,127.0.0.1,192.168.*.*,*.apps-crc.testing


2. should the host-vm no-proxy setting and crc config view no-proxy setting should be same?

thank you in advance

**Comment by jeet1990** [comment]
Hi experts,

im still facing the same issue. proxy settings are set as suggested

i have set the host env variable.

[saan@localhost ~]$ cat /etc/environment
http_proxy="http://10.xxx.xxx.xx:8080"
https_proxy="https://10.xxx.xxx.xx:8080"
no_proxy=localhost,10.30.1.*,127.0.0.1,192.168.*.*,*.apps-crc.testing,https://api.crc.testing:6443



[saan@localhost ~]$ crc config view
- cpus                                  : 6
- http-proxy                            : http://10.xxx.xxx.xx:8080
- https-proxy                           : http://10.xxx.xxx.xx:8080
- memory                                : 16000
- no-proxy                              : localhost,127.0.0.1,192.168.130.*,*.apps-crc.testing,*.testing,https://api.crc.testing:6443



DEBU Approving pending CSRs
DEBU Running '/home/saan/.crc/bin/oc/oc get csr -ojson --kubeconfig /home/saan/.crc/machines/crc/kubeconfig --context admin --c                               luster crc'
INFO Waiting for the proxy configuration to be applied ...
DEBU Running '/home/saan/.crc/bin/oc/oc set env deployment redhat-operators --list -n openshift-marketplace --kubeconfig /home/                               saan/.crc/machines/crc/kubeconfig --context admin --cluster crc'
DEBU Proxy changes for cluster in progress
DEBU error: Temporary Error:  - sleeping 2s
DEBU retry loop 1



DEBU stderr: The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port?
DEBU Error getting proxy setting for openshift-marketplace operator exit status 1
DEBU error: Temporary Error: exit status 1 - sleeping 2s
DEBU retry loop 38


DEBU retry loop 59
DEBU Running '/home/saan/.crc/bin/oc/oc set env deployment redhat-operators --list -n openshift-marketplace --kubeconfig /home/                               saan/.crc/machines/crc/kubeconfig --context admin --cluster crc'
DEBU Proxy changes for cluster in progress
DEBU error: Temporary Error:  - sleeping 2s
DEBU RetryAfter timeout after 60 tries
DEBU Failed to propagate proxy settings to cluster

**Comment by gbraad** [comment]
I see:

```
https_proxy="https://10.xxx.xxx.xx:8080"
```

```
[saan@localhost ~]$ crc config view
    https-proxy : http://10.xxx.xxx.xx:8080
```

to my knowledge `https` is not supported, but this is also not reflected in your config. I see `DEBU stderr: The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port?` which would mean your DNS configuration might not be correct. can you try the same scenario from a clean environment: `crc cleanup; crc setup; crc start` and make sure you are not connected to a VPN.

**Comment by praveenkumar** [comment]
@jeet1990 if the host is bit slow it might be possible that proxy propagation take some time (currently we have 2 mins timeout) can you also try to execute the following command and put output once you hit this issue (after 60 retries). Also I can see you mention the `https://api.crc.testing:6443` in no proxy which is not required since `*.testing` suppose to handle it.

```
$ /home/saan/.crc/bin/oc/oc set env deployment redhat-operators --list -n openshift-marketplace --kubeconfig /home/ saan/.crc/machines/crc/kubeconfig --context admin --cluster crc'
```

**Comment by gbraad** [comment]
> https://api.crc.testing:6443

Could even cause issues when parsed. Please remove this addition.

**Comment by cfergeau** [comment]
I would only set no_proxy to `no-proxy : localhost,127.0.0.1`, both in `crc config` and `/etc/environment`, and see if this helps.

**Comment by praveenkumar** [comment]
@jeet1990 ping? Can you let us know if it is fixed for you?

**Comment by praveenkumar** [comment]
Closing this since there is no response from the reporter.
