### ISSUE TITLE
ssh key 'id_rsa' not available if initial start fails

### ISSUE THREAD

**Issue by anjannath** [code-ready/crc#1389]
### General information

  * OS: Windows
  * Hypervisor: Hyper-V

If the initial `crc start` fails due to some dns error or other errors, _before the ssh keys are updated_ the vm still exists, so in the later `crc start` runs we get the id_rsa key missing error because we look for the ssh key in `~/.crc/machine/crc/id_rsa` which was not created.

In case of windows most of the time its because external dns resolution fails in the initial start, so i pass `--nameserver` flag and this solves the issue.

Or when a `crc start` fails, one should run `crc delete` before doing `crc start` again.

**Comment by gbraad** [comment]
This should not be Windows specific. If the lookup of `quay.io` fails, the startup will be marked as failed. This cause a partial VM creation to exist. When started again, it will conclude the ssh key is not available (the key exchange happens after the lookup).

**Comment by cfergeau** [comment]
Ideally, we'd detect startup failures, and get back to the state before the start attempt (ie either run `crc stop` or `crc delete` depending on whether a VM existed or not). Something easier to achieve short term would be to do a more thorough check of `~./crc/machines/crc` when using content of this directory, and make sure ssh keys, kubeconfig, ... are all present. If not, error out early and give a better error message.

**Comment by gbraad** [comment]
the question is also, is the 'quay.io' check supposed to be so strict?
I might warn first, and allow the VM to be properly created and then check that state and error out.

But I agree that the tests about a possible restart (of an incomplete setup) is (more) important.

**Comment by anjannath** [comment]
6083a7ca4076b000ad32123a4172f57737e590d6 doesn't address the issue like suggested in https://github.com/code-ready/crc/issues/1389#issuecomment-658623182 it just moves the key generation a bit earlier (as soon as ssh is available) so that any errors that occur after won't impede ssh access to the vm on the next run (stop => start).

**Comment by praveenkumar** [comment]
This is already fixed #1427
