### ISSUE TITLE
[RFE] Allow to customize DNS search domains in /etc/resolv.conf in CRC VMs

### ISSUE THREAD

**Issue by fasho** [code-ready/crc#1394]
This is a request for enhancement to add domains to the CRC VM.

## CRC version   // Applicable to other versions as well
```
$ crc version
crc version: 1.8.0+0a318dc
OpenShift version: 4.3.8 (embedded in binary)
```
  
Currently adding the domain is possible by editing the /etc/resolv.conf in the CRC VM but it is not persistent. Adding domain suffix will help the pods  running on CRC to access short names. 

If implemented, this will add the domain to the pods(running on crc) /etc/resolv.conf as well.  

Adding extra domain in search field automatically is requested here.

Thanks.

**Comment by cfergeau** [comment]
Would this kind of changes be doable and acceptable on a production openshift cluster? Maybe through the Machine Config Operator? Have they considered handling this through an intermediate DNS server which would add the suffixes itself?

**Comment by fasho** [comment]
Yes, in OCP 4 this is possible : https://access.redhat.com/solutions/4518671
But will that work for crc? Didn't check the intermediate DNS approach.
