### ISSUE TITLE
[BUG] crc status should report useful error codes

### ISSUE THREAD

**Issue by whitel** [code-ready/crc#1399]
### General information

  * OS: Linux / macOS / Windows
Fedora 32

  * Hypervisor: KVM / Hyper-V / hyperkit
kvm

  * Did you run `crc setup` before starting it (Yes/No)?
yes

  * Running CRC on: Laptop / Baremetal-Server / VM
N/A

## CRC version
```bash
CodeReady Containers version: 1.13.0+8070bae
OpenShift version: 4.5.1 (embedded in binary)
```
  

### Steps to reproduce

  1.  crc status
  2.  echo $?

### Expected
"0" when "Running," other codes when not. Could be sophisticated to indicate state or could just be a "1"

### Actual

Always "0"

Not having this means i have to grep the output in order to automate follow on work after `crc start`

**Comment by gbraad** [comment]
Error codes are about the execution of the programming, not the state of the VM.

**Comment by gbraad** [comment]
See #1227, closing as the referenced issue will solve the'grep' problem

**Comment by gbraad** [comment]
> Could be sophisticated to indicate state or could just be a "1"

This would have to be a flag as multiple combinations are possible;

  * VM is (NOT) running
  * OpenShift is (NOT) running
  * Operator(s) is/are (NOT) running
  ... etc

Note: if you insist on this, we can reconsider

**Comment by cfergeau** [comment]
We could follow what `systemctl` is doing https://man7.org/linux/man-pages/man1/systemctl.1.html#EXIT_STATUS and at least report cluster running/cluster not running/(if possible)cluster in a degraded state, with "cluster" being very generic and meaning VM + OpenShift.
