### ISSUE TITLE
Convert test documentation to AsciiDoc

### ISSUE THREAD

**Issue by robin-owen** [code-ready/crc#140]
Currently, the documentation for the tests is written in Markdown. Convert these docs to AsciiDoc using the same general format as the rest of the documentation.

**Note:** Right now, this only consists of the `test/integration/README.md` file.

**Comment by gbraad** [comment]
@jsliacan @tsedmik Will you guys be able to handle this. Pleade contact @robin-owen if you have questions.

**Comment by jsliacan** [comment]
@gbraad @robin-owen @tsedmik It seemed straightforward so I changed it to `.adoc`. Please take a look at PR #250 when you find time. Cheers!

**Comment by robin-owen** [comment]
This was fixed by #250.
