### ISSUE TITLE
crc setup - Virtualization is not available For your CPU 

### ISSUE THREAD

**Issue by tarungupta001** [code-ready/crc#1411]
### General information

  * OS: Linux 
  * Hypervisor: KVM / Hyper-V / hyperkit (Don't know)
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
# Put the output of `crc version`
```
$CodeReady Containers version: 1.13.0+8070bae
$OpenShift version: 4.5.1 (embedded in binary)

  
## CRC status
```bash
# Put the output of `crc status`
```
$Machine 'crc' does not exist. Use 'crc start' to create it.

## CRC config
```bash
# Put the output of `crc config view`
```
- cpus                                  : 4
- memory                                : 9216

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.8 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.8"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.8:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.8
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.8"

### Steps to reproduce

  1. Run crc setup
  2. 
  3. 
  4. 

### Expected
1. No error

### Actual
INFO Checking if oc binary is cached
INFO Checking if podman remote binary is cached
INFO Checking if goodhosts binary is cached
INFO Checking if CRC bundle is cached in '$HOME/.crc'
INFO Checking if running as non-root
INFO Checking if Virtualization is enabled
INFO Setting up virtualization
**FATA You need to enable virtualization in BIOS**

### Logs

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

INFO Checking if oc binary is cached
DEBU Running '/home/TarunGupta/.crc/bin/oc/oc version --client'
DEBU oc binary already cached
INFO Checking if podman remote binary is cached
DEBU Currently podman remote is not supported
INFO Checking if goodhosts binary is cached
DEBU goodhost binary already cached
INFO Checking if running as non-root
INFO Checking if Virtualization is enabled
DEBU Checking if the vmx/svm flags are present in /proc/cpuinfo
DEBU Virtualization is not available for your CPU
FATA Virtualization is not available for your CPU

**Comment by gbraad** [comment]
We can not determine if VTX or SVM is possible for your CPU. This is why the question is to enable this in the BIOS if possible as some manufactures still put this behind a feature. This happens even if the flags are available on the CPU, they might be prevented from being used.

**Comment by anjannath** [comment]
@tarungupta001 Please verify and enabled virtualization in your BIOS settings as suggested, and feel free to reopen if the issue still remains.
