### ISSUE TITLE
Use another hypervisor on MacOS

### ISSUE THREAD

**Issue by pplch** [code-ready/crc#1413]
I'm sorry, but I don't know where to ask - so this is not an issue.

**Would it be possible to use another hypervisor on MacOS?**

I use _Parallels_ by default and I have a better experience with them than with _hyperkit_.
Alternatively, _Virtualbox_.
What should I do if I want to make my version of CRC that uses a different hypervisor?

I would imagine it as it was in the minikube:
`minikube start --driver=parallels`

**Comment by gbraad** [comment]
We want to offer an OOTB option to the user without having to install or purchase additional software licenses (like the hypervisors you suggest) to make this work. VirtualBox support has been dropped for reasons and I expect the same situation for parallels.
