### ISSUE TITLE
[BUG] CRC docs missing information about how to use container registry

### ISSUE THREAD

**Issue by rexroof** [code-ready/crc#1418]
Sorry if this is the wrong place for this:

minishift had pretty good documentation about how to use the internal container registry, I can't find that documentation for CRC.

here are some questions I've been trying to figure out:

should I use 
**image-registry.openshift-image-registry.svc:5000** for my registry address or should I use **default-route-openshift-image-registry.apps-crc.testing** ?
I notice that I have varying success with getting the SSL certificates on these hostnames to be recognized. 
I understand the issues around self-signed certificates but I am trying to work out the "best practices" as suggested by this project.  do I need to manually change the internal settings of my CRC cluster to allow insecure registries?  
Do I need to use one of these for docker push/pull and another for my image urls in my container manifests?
Do I need to create an imagePullSecret to use this registry?  How is that best accomplished?

I'm wondering if the lack of documentation around the internal container registry means that I shouldn't be pushing my custom containers to this registry and I should be using some other method to deploy my application on openshift 4 / CRC.

**Comment by praveenkumar** [comment]
@rexroof Thanks for pointing it out, we will try to put note https://docs.okd.io/3.11/minishift/openshift/openshift-docker-registry.html like this one.

**Comment by robin-owen** [comment]
@praveenkumar I'll need more information about how to document this as outlined in the original issue (great questions, by the way).

It seems to me that we could use a dedicated procedure for this task.

**Comment by robin-owen** [comment]
Fixed by #1418.
