### ISSUE TITLE
Can't create additional users in CRC!!

### ISSUE THREAD

**Issue by nilanu** [code-ready/crc#1432]
I am learning OpenShift. I deployed CRC 1.12. on Ubuntu 18.04 LTS (KVM). I can login to the cluster using kube:admin / developer both from cui & gui. I can see, form gui, that htpasswd is setup as identity provider. 
My question is how can I add additional users to my cluster? With htpasswd, I need local access to the crc vm to be able to add user, change password. But local access to the crc vm over ssh is not permitted I guess.

I did not find any option to add user in the GUI either although it shows the existing developer user there.

**Comment by praveenkumar** [comment]
@nilanu Check https://github.com/code-ready/crc/wiki/Add-another-user-to-cluster one but this is very specific around how auth works in the Openshift, not something crc specific.

- https://docs.openshift.com/container-platform/4.2/authentication/identity_providers/configuring-htpasswd-identity-provider.html#add-identity-provider_configuring-htpasswd-identity-provider 

closing this issue.
