### ISSUE TITLE
Inject SSH keys during initial start

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#145]
At the moment we are (re-)using a single set of SSH keys for the creation of the images, and they are also used for login/configuring during start of the VM.

We should however move to a way in which keys are assigned to an instance on initial start, eg. create the keys, create a disk image (or ISO), mount to the VM, and on initial start replace the SSH keys to be unique to this instance.

**Comment by gbraad** [comment]
would we want to inject the users SSH key as a possibility? If so, we allow access to the VM ... and this is like the behaviour of the installer... just wonder, do we want this?

**Comment by praveenkumar** [comment]
@gbraad what if a user doesn't have SSH key setup and also this will be problematic for windows, I want to go with what we had in minishift, attaching the userdata as a separate disk and consume it as a part of script which run with a unit file.

**Comment by gbraad** [comment]
I would not go down this route as this is tremendously slow on Windows as the image will have to be written three times.

> We have removed that that logic during the refactor 8b1b441 and need to
> be added back since we want to send ssh keys as part of user data.

Inject can be done by using the generic key and then replace them on first connection with SSH with a new key. This key generation can happen within CRC and passed to the driver (but can also be completely contained within CRC). I do not believe the driver axctually has to know about SSH and user to connect with. The driver should ONLY have to deal with hypervisor related interaction.

**Comment by gbraad** [comment]
a datadisk means there needs to be logic inside the VM to handle the extraction of a bitstream... it also needs to have this implementation of 'creation' happening in at least 4 different implementation (libvirt, hyperv, hyperkit and virtualbox), while a replacement from just CRC by connecting to the VM, replacing with a new key, can be shared among all implementations (without having to write support for a non-supported platfom like vbox)

**Comment by cfergeau** [comment]
This one has been fixed by the commit listed in that issue.
