### ISSUE TITLE
Error running post start: Restarting the host network failed: : exit status 14

### ISSUE THREAD

**Issue by sumitpuri** [code-ready/crc#1456]
### General information

  * OS:  macOS
  * Hypervisor:hyperkit
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop 

## CRC version
```bash
CodeReady Containers version: 1.14.0+36ad776
OpenShift version: 4.5.4 (embedded in binary)
```
  
## CRC status
```bash
DEBU CodeReady Containers version: 1.14.0+36ad776 
DEBU OpenShift version: 4.5.4 (embedded in binary) 
DEBU                                              
ERRO Cannot get root partition usage: stat /Users/sumit.puri@us.ibm.com/.crc/machines/crc/id_rsa: no such file or directory 
Cannot get root partition usage: stat /Users/sumit.puri@us.ibm.com/.crc/machines/crc/id_rsa: no such file or directory
```

## CRC config
```bash
--empty--
```

## Host Operating System
```bash
ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101
```

### Steps to reproduce

  1. Download crc zip file and extract and place crc in the $PATH.
  2. Run crc setup 
  3. Run crc start
  4. The installation fails with the above error

### Expected
Installation should succeed

### Actual
Installation failing

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

https://gist.github.com/sumitpuri/b881e72e08ed07c9722243655b3d0a63

**Comment by praveenkumar** [comment]
@sumitpuri Gist which you share is not the complete one, we are not able to identify using this gist what failed for you, please share the complete gist as mention in the issue template.

**Comment by sumitpuri** [comment]
Thanks Praveen, it has started to work automatically now when I was trying to create a new gist.
