### ISSUE TITLE
subscription-manager repos --enable rhel-7-server-cnv-2.4-rpms

### ISSUE THREAD

**Issue by doyoungim999** [code-ready/crc#1459]
### General information

  * OS: Linux / macOS / Windows 
Linux
  * Hypervisor: KVM / Hyper-V / hyperkit
KVM
  * Did you run `crc setup` before starting it (Yes/No)?
Yes 

## CRC version
```bash
# Put the output of `crc version`
```
[user1@bm01-redhat ~]$ crc version
CodeReady Containers version: 1.14.0+36ad776
OpenShift version: 4.5.4 (embedded in binary)
  
## CRC status
```bash
# Put the output of `crc status`
[user1@bm01-redhat ~]$ crc status
CRC VM:          Running
OpenShift:       Running (v4.5.4)
Disk Usage:      19.01GB of 32.72GB (Inside the CRC VM)
Cache Usage:     12.93GB
Cache Directory: /home/user1/.crc/cache


## CRC config
```bash
# Put the output of `crc config view`
```
[user1@bm01-redhat ~]$ crc config view
- cpus                                  : 4
- memory                                : 16000

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
[user1@bm01-redhat ~]$ crc config view
- cpus                                  : 4
- memory                                : 16000
[user1@bm01-redhat ~]$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.8 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.8"
PRETTY_NAME="Red Hat"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.8:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.8
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.8"

# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```

### Steps to reproduce

  1. #subscription-manager repos --enable rhel-7-server-cnv-2.4-rpms
  2. Error: 'rhel-7-server-cnv-2.4-rpms' does not match a valid repository ID. Use "subscription-manager repos --list" to see valid repositories.
  3. [root@bm01-redhat ~]# subscription-manager repos --list|grep cnv
[root@bm01-redhat ~]#

  4. 

### Expected
enable repo ID and run "#yum install rhel-7-server-cnv-2.4-rpms" sucessfully

### Actual

subscription-manager repos --enable rhel-7-server-cnv-2.4-rpms
Error: 'rhel-7-server-cnv-2.4-rpms' does not match a valid repository ID. Use "subscription-manager repos --list" to see valid repositories.
### Logs
Error: 'rhel-7-server-cnv-2.4-rpms' does not match a valid repository ID. Use "subscription-manager repos --list" to see valid repositories.

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

Can I use virtualization  with CRC ?

**Comment by praveenkumar** [comment]
@doyoungim999 This is clearly not the CRC issue, you might want to check cnv side how to enable the repo or check your subscription if it allows you to enable those.
