### ISSUE TITLE
[BUG] was not able to use docker images in host machine(laptop)

### ISSUE THREAD

**Issue by thotz** [code-ready/crc#1466]
### General information

  * OS: Linux 
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop

## CRC version
```bash
#  crc version
CodeReady Containers version: 1.14.0+36ad776
OpenShift version: 4.5.4 (embedded in binary)
```
 
## CRC status
```bash
#crc status
CRC VM:          Running 
OpenShift:       Running (v4.5.4)
Disk Usage:      14.33GB of 32.72GB (Inside the CRC VM)
Cache Usage:     12.93GB
```

## CRC config
default values

## Host Operating System
```bash
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
```

### Steps to reproduce

I was trying to use docker images build on locally in my laptop to crc environment. I tried following steps.
```bash
docker login -u kubeadmin -p $(oc whoami -t) default-route-openshift-image-registry.apps-crc.testing
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://default-route-openshift-image-registry.apps-crc.testing/v2/: x509: certificate signed by unknown authority
```
Then I tried to add [an insecure registry](https://github.com/code-ready/crc/wiki/Adding-an-insecure-registry) to crc vm and executed similar steps 
```bash
docker login -u kubeadmin -p $(oc whoami -t) my.insecure.registry.com:8888
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://my.insecure.registry.com:8888/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
Also tried to execute podman, but throws an unsupported error(I have given option for experimental features while crc setup)

Please note I don't have much hands on experience with minishift or crc or openshift. For my dev environment I usually play around with minikube running on vm1`(minikube start --vm-driver=none)`.
 
And I might miss the basic steps, please correct me if I am wrong
### Expected
Consume docker images from host laptop

### Actual
Not able to add local registry

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
@thotz Since you are using the centos-8 which have podman by default it would be better to use something following then using docker.

```
$ podman login -u kubeadmin -p $(oc whoami -t)  --tls-verify  false default-route-openshift-image-registry.apps-crc.testing
```

> Then I tried to add an insecure registry to crc vm and executed similar steps

This is not something you try it on the host, insecure registry you add on the crc can be used to deploy an app which uses image from that insecure registry.

**Comment by thotz** [comment]
I was able to login into container registry via podman with option `--tls-verify=false`. Hence closing this bug
