### ISSUE TITLE
[BUG] Remove openshift-openstack-infra, openshift-ovirt-infra, openshift-vsphere-infra from the *libvirt* CRC

### ISSUE THREAD

**Issue by mykaul** [code-ready/crc#1468]
### General information

  * OS: Linux
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop 

## CRC version
```[ykaul@ykaul crc-linux-1.14.0-amd64]$ ./crc version
CodeReady Containers version: 1.14.0+36ad776
OpenShift version: 4.5.4 (embedded in binary)
```

I was surprised to see 57(!) projects for the simple out of the box CRC for Linux installation. I'm not sure how many are needed, but it's quite clear to me there's no need for OSP, oVirt or vSphere infra there.

**Comment by praveenkumar** [comment]
@mykaul These are just the namespaces created by installer I think but doesn't contain any resources, I don't see any harm having it there because same will be present in case of real cluster. Also this need to be part of code-ready/snc repo where we create the bundle.

**Comment by mykaul** [comment]
ACK.
