### ISSUE TITLE
Connect to host port 22: Connection refused

### ISSUE THREAD

**Issue by jeffsaremi** [code-ready/crc#1472]
### General information

  * OS: RHEL8
  * Hypervisor: KVM 

## CRC version
```bash
CodeReady Containers version: 1.14.0+36ad776
OpenShift version: 4.5.4 (embedded in binary)
```
  
I'm pretty sure this is my own doing however I need some help fixing this.

My host is a RHEL 8 machine.
I'm running CRC on that.
At the same time, I'm running another VM with my test client in Ubuntu 16.04. We can't run this on RHEL.

Problem 1:
When I try to create the Ubuntu VM on the same network as crc (network=crc) I never get an IP assigned.
Therefore I'm running Ubuntu on the `default` network.

Problem 2:
Connecting to CRC from my Ubuntu VM has issues. First the subnet. For that I have added a route option like below.
The route change seems to be working since traceroute returns success.
However ssh'ing into CRC seems to be blocked.
Is there a firewall rule or something on the CRC Vm that needs to be adjusted here?

```
[root@SPE-SAG4HP-43 ~]# virsh list
 Id    Name                           State
----------------------------------------------------
 2     crc                            running
 19    vsts-agent                     running

[root@SPE-SAG4HP-43 ~]# virsh net-list
 Name                 State      Autostart     Persistent
----------------------------------------------------------
 crc                  active     yes           yes
 default              active     yes           yes

[root@SPE-SAG4HP-43 ~]# virsh domifaddr crc
 Name       MAC address          Protocol     Address
-------------------------------------------------------------------------------
 vnet0      52:fd:fc:07:21:82    ipv4         192.168.130.11/24

[root@SPE-SAG4HP-43 ~]# virsh domifaddr vsts-agent
 Name       MAC address          Protocol     Address
-------------------------------------------------------------------------------
 vnet1      52:54:00:41:aa:4b    ipv4         192.168.122.209/24

[root@SPE-SAG4HP-43 ~]# ssh -i ~/.ssh/id_rsa ubuntu@192.168.122.209
Welcome to Ubuntu 16.04.7 LTS (GNU/Linux 4.4.0-187-generic x86_64)

ubuntu@vsts-agent:~$ ip route show
default via 192.168.122.1 dev ens3
192.168.0.0/24 via 192.168.122.1 dev ens3
192.168.122.0/24 dev ens3  proto kernel  scope link  src 192.168.122.209
192.168.130.0/24 via 192.168.122.1 dev ens3

ubuntu@vsts-agent:~$ !trace
traceroute -p 22 192.168.130.11
traceroute to 192.168.130.11 (192.168.130.11), 64 hops max
  1   192.168.122.1  0.779ms  0.086ms  0.095ms
  2   192.168.122.1  0.138ms  0.053ms  0.051ms

# failing to connect from Ubuntu vm
ubuntu@vsts-agent:~$ ssh -i ~/.ssh/id_rsa core@192.168.130.11
ssh: connect to host 192.168.130.11 port 22: Connection refused

# successful connection from the host:
[root@SPE-SAG4HP-43 ~]# ssh -i /home/jesaremi/.crc/machines/crc/id_rsa core@192.168.130.11
Red Hat Enterprise Linux CoreOS 45.82.202007240629-0
  Part of OpenShift 4.5, RHCOS is a Kubernetes native operating system
  managed by the Machine Config Operator (`clusteroperator/machine-config`).

```

**Comment by praveenkumar** [comment]
> When I try to create the Ubuntu VM on the same network as crc (network=crc) I never get an IP assigned.
Therefore I'm running Ubuntu on the default network.

This is because `crc` network doesn't have dhcp range defined like default network have, so to use crc network you can edit it and add the range something like and then you should get IP to your ubuntu VM.



```xml
<network connections='1'>
  <name>crc</name>
  <uuid>49eee855-d342-46c3-9ed3-b8d1758814cd</uuid>
  <forward mode='nat'>
    <nat>
      <port start='1024' end='65535'/>
    </nat>
  </forward>
  <bridge name='crc' stp='on' delay='0'/>
  <mac address='52:54:00:fd:be:d0'/>
  <ip family='ipv4' address='192.168.130.1' prefix='24'>
    <dhcp>
      <range start="192.168.130.100" end="192.168.130.254"/>
      <host mac='52:fd:fc:07:21:82' ip='192.168.130.11'/>
    </dhcp>
  </ip>
</network>
```

**Comment by praveenkumar** [comment]
> Is this behavior intended? Is there a way to have a happy median here?

Yes we do check exactly how the network definition looks, if you want to avoid this check then use `crc config set skip-check-crc-network true` and then this check will be ignored and it should work.

**Comment by praveenkumar** [comment]
@jeffsaremi Does this above workaround able to solve the issue?

**Comment by jeffsaremi** [comment]
Sorry for the delay. I haven't got a chance to test this. But I'm pretty sure it'll solve my problem.
