### ISSUE TITLE
CodeReady Containers (CRC) - global/SA pull-secret doesn't work with digest tag and mirroring

### ISSUE THREAD

**Issue by rajones27** [code-ready/crc#1474]
### General information

  * OS: Linux - RHEL 7.7 on Bare-Metal
  * Hypervisor: KVM (CRC)
  * Did you run crc setup before starting it (Yes/No)? Yes

## CRC version
```
crc version
CodeReady Containers version: 1.14.0+36ad776
OpenShift version: 4.5.4 (embedded in binary)
```
  
## CRC status
```
crc status
CRC VM:          Running
OpenShift:       Running (v4.5.4)
Disk Usage:      22.23GB of 193.8GB (Inside the CRC VM)
Cache Usage:     12.93GB
Cache Directory: /home/test/.crc/cache
```

## CRC config
```
 crc config view
- cpus                                  : 20
- memory                                : 72000
- pull-secret-file                      : /home/test/Downloads/1.5/crc-linux-1.5.0-amd64/pull-secret
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```

### Steps to reproduce

  1. Created a mirror using the instructions at  [here](https://github.com/code-ready/crc/wiki/Adding-an-insecure-registry ).
     example from /etc/container/registries.conf:
```
     [[registry]]
       location = "docker.io/ibmcom"
       insecure = false
       blocked = false
       mirror-by-digest-only = true
       prefix = ""

    [[registry.mirror]]
      location = "abc-docker-local.artifactory.swg-devops.com"
      insecure = false

    [[registry.mirror]]
      location = "jkl-docker-local.artifactory.swg-devops.com/builds"
      insecure = false

   [[registry.mirror]]
     location = "xyz-docker-local.artifactory.swg-devops.com"
     insecure = false
```    
  2. Create secrets to be added to the global pull-secret:
```
      oc create secret docker-registry xyz-secret-key --docker-server=xyz-docker-local.artifactory.swg-devops.com --docker-username=my-email.com --docker-password=<docker_password> --docker-email=my-email.com --dry-run=true --output="jsonpath={.data.\.dockerconfigjson}" | base64 --decode > myregistryconfigjson
```
```
      oc get secret pull-secret -n openshift-config --output="jsonpath={.data.\.dockerconfigjson}" | base64 --decode > dockerconfigjson
```
``` 
     jq -s '.[0] * .[1]' dockerconfigjsbe on myregistryconfigjson > dockerconfigjson-merged
```
```
    oc set data secret/pull-secret -n openshift-config --from-file=.dockerconfigjson=dockerconfigjson-merged
```
  3. Then `oc create -f catalogsource.yaml` with the digest tag  - `image: docker.io/ibmcom/datapower-operator-catalog@sha256:xxxxxxxxxxxxx`

### Expected
The catalogsource to be deployed using the registry secret defined in the global pull-secret to authenticate against the remote docker registry mirror.

### Actual
Authentication failed:
```
Events:
  Type     Reason     Age                From                         Message
  ----     ------     ----               ----                         -------
  Normal   Scheduled  101s               default-scheduler            Successfully assigned openshift-marketplace/ibm-datapower-operator-catalog-7d85p to crc-rtgqw-master-0
  Normal   Pulling    49s (x3 over 96s)  kubelet, crc-rtgqw-master-0  Pulling image "docker.io/ibmcom/datapower-operator-catalog@sha256:626ca3f20124ae3b873a09dfcb21a22d8faefd7495952428d096bb7aaf8c1e2d"
  Warning  Failed     45s (x3 over 92s)  kubelet, crc-rtgqw-master-0  Failed to pull image "docker.io/ibmcom/datapower-operator-catalog@sha256:626ca3f20124ae3b873a09dfcb21a22d8faefd7495952428d096bb7aaf8c1e2d": rpc error: code = Unknown desc = (Mirrors also failed: xyz-docker-local.artifactory.swg-devops.com/datapower-operator-catalog@sha256:626ca3f20124ae3b873a09dfcb21a22d8faefd7495952428d096bb7aaf8c1e2d: unable to retrieve auth token: invalid username/password: unknown: Authentication is required]

```
Also extended the setup to create the registry secret and linked it to the default service account in the openshift-marketplace project, and authentication still failed.

The issue seems to be mirroring with digest only  
### Logs

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by predragmaksimovic** [comment]
I observed the same issue. I am using CRC 1.14.0 on Windows (Hyper-V). I SSH-ed to CRC VM, defined registry mirroring from registryX to registryY in `/etc/containers/registries.conf`. I added auth information for registryY to the global `pull-secret` in the `openshift-config` namespace, and also tried adding it to the default pull secret in my project.

When I deploy workload that references image in registryX to my namespace, it fails to pull the image and reports that authentication failed. The mirroring appears to be taking place since the error message lists both registries and says “Mirrors also failed”. But it doesn’t seem to be using the auth info I provided for registryY, no matter how I provide it. I also double checked the auth info to make sure it is correct, and if I deploy the workload and reference the image in registryY directly, then it pulls the image correctly, so that is additional assurance that the auth info is correct.

**Comment by praveenkumar** [comment]
@rajones27 @predragmaksimovic Any chance have you tried same with real openshift cluster, I am going to have a look into this tomorrow and put the finding issue here.

**Comment by predragmaksimovic** [comment]
@praveenkumar Thanks for looking into this. Yes, I was deploying to a RHOCP cluster where mirroring + auth worked, but I wasn’t the one who configured the cluster. Pretty sure though they used ImageContentSourcePolicy object to define the mirroring and had it automatically propagated to the worker nodes, and also pretty sure they used global pull-secret in the openshift-config namespace to provide the auth info for the mirror registry. 

**

Please note that I was able to get the following to work, which I hope can help with the troubleshooting:

1. SSH to CRC VM and edit `/etc/containers/registries.conf` to define mirroring from locationX to locationY. Note that registries for both locationX and locationY require authentication, but they use different credentials.

2. Issue  `podman pull --creds user:passwd locationX/image@sha256:digest`
Where `user` and `passwd` are for locationY and `image@sha256:digest` is the image name and digest of the image. The image physically resides under locationY but the podman command above intentionally refers to it under locationX with the hope of mirroring+auth taking place. This does NOT work, fails just like when I try to apply a deployment manifest with the same image reference via kubectl.

3. Issue `export REGISTRY_AUTH_FILE=/var/home/core/auth.json`
Issue `podman login --username user --password passwd  registryY`
Where `user` and `passwd` are for registryY. This works and login succeeds and auth info for registryY is stored in auth.json.
Now issue: `podman pull locationX/image@sha256:digest`
This works. The image is successfully pulled from locationY where it resides even though the podman pull command refers to it under locationX.

**Comment by praveenkumar** [comment]
@predragmaksimovic In the section 3 

> Issue export REGISTRY_AUTH_FILE=/var/home/core/auth.json
Issue podman login --username user --password passwd registryY
Where user and passwd are for registryY. This works and login succeeds and auth info for registryY is stored in auth.json.
Now issue: podman pull locationX/image@sha256:digest
This works. The image is successfully pulled from locationY where it resides even though the podman pull command refers to it under locationX.

Can you try `podman pull --authfile /var/home/core/auth.json locationX/image@sha256:digest` instead login to the registry with username and password and see if that works also?

**Comment by predragmaksimovic** [comment]
@praveenkumar Yes, that appears to be working too.

Before issuing `podman pull --authfile /var/home/core/auth.json locationX/image@sha256:digest` I closed the SSH session and started a new one, made sure to podman logout from registryY (it said it wasn't logged in), made sure that `REGISTRY_AUTH_FILE` is not set, and then issued the podman pull command above and it pulled the image. I then also tried the same command but without the `--authfile` flag and that failed with authentication error, so `--authfile` indeed seems to be utilized when provided. 

And yes, I looked in `auth.json` and it contains creds for registryY only, no mention of registryX there.

**Comment by praveenkumar** [comment]
@predragmaksimovic Thank you for validation, I will do more debugging and post it here.

**Comment by rajones27** [comment]
@praveenkumar Any results yet from your testing?

**Comment by praveenkumar** [comment]
@rajones27 Hi, I was on PTO and just come back, I will try to again start looking into this.

**Comment by praveenkumar** [comment]
@rajones27 @predragmaksimovic Finally I have something which is working for CRC as part of mirror registry, this need to be part of document since there are some manual steps are required, I will draft the doc tomorrow and share it with you folks to try it out.

**Comment by praveenkumar** [comment]
@rajones27 I also got the same issue ` Warning  Failed     45s (x3 over 92s)  kubelet, crc-rtgqw-master-0  Failed to pull image "docker.io/ibmcom/datapower-operator-catalog@sha256:626ca3f20124ae3b873a09dfcb21a22d8faefd7495952428d096bb7aaf8c1e2d": rpc error: code = Unknown desc = (Mirrors also failed: xyz-docker-local.artifactory.swg-devops.com/datapower-operator-catalog@sha256:626ca3f20124ae3b873a09dfcb21a22d8faefd7495952428d096bb7aaf8c1e2d: unable to retrieve auth token: invalid username/password: unknown: Authentication is required]` during the testing so I think what you are missing is adding same pull secret in the VM which is in the `/var/lib/kubelet/config.json` file which should have pull secret which content should be  `dockerconfigjson-merged` file. Can you update and then try if that works?

**Comment by praveenkumar** [comment]
https://github.com/code-ready/crc/wiki/Add-mirror-registry is what I have documented.

**Comment by rajones27** [comment]
@praveenkumar Thanks for the new updated data. Will let you know soon if this works out for us.

**Comment by predragmaksimovic** [comment]
@praveenkumar Worked perfectly for me! So turns out the only piece I was missing was that update of `/var/lib/kubelet/config.json` in the VM. Once I did that, I restarted CRC, and mirroring started working.
This is great, thank you !!!

**Comment by praveenkumar** [comment]
Great to hear, will wait for @rajones27 test and then close this.

**Comment by rajones27** [comment]
@praveenkumar I've tried the suggestion as stated below, and it did fix the authentication issue, it is working now. I have not tried to use the doc link that you have provided, https://github.com/code-ready/crc/issues/1474#issuecomment-691290462. Not sure if you want us to give any feed back.

Thanks!
> 
> 
> @rajones27 I also got the same issue ` Warning Failed 45s (x3 over 92s) kubelet, crc-rtgqw-master-0 Failed to pull image "docker.io/ibmcom/datapower-operator-catalog@sha256:626ca3f20124ae3b873a09dfcb21a22d8faefd7495952428d096bb7aaf8c1e2d": rpc error: code = Unknown desc = (Mirrors also failed: xyz-docker-local.artifactory.swg-devops.com/datapower-operator-catalog@sha256:626ca3f20124ae3b873a09dfcb21a22d8faefd7495952428d096bb7aaf8c1e2d: unable to retrieve auth token: invalid username/password: unknown: Authentication is required]` during the testing so I think what you are missing is adding same pull secret in the VM which is in the `/var/lib/kubelet/config.json` file which should have pull secret which content should be `dockerconfigjson-merged` file. Can you update and then try if that works?

**Comment by praveenkumar** [comment]
Thanks for testing out, closing this issue.
