### ISSUE TITLE
How to remove cached docker images in CRC

### ISSUE THREAD

**Issue by aceeric** [code-ready/crc#1493]
## CRC version
```bash
$ ./crc version
CodeReady Containers version: 1.13.0+8070bae
OpenShift version: 4.5.1 (embedded in binary)
```

## Host Operating System
```bash
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
```

### This is just a question
I have a case where docker images are being cached in CRC and I would like to be able to completely or selectively purge the image cache. It looks to me like one of the crio containers must be serving as the internal registry and caching these docker images. My question is - is there a way or some documentation that would show me how to do the equivalent of: `docker images -q | xargs docker image rm -f` ?

When I ssh into the pod like so:
```
$ ssh -i ~/.crc/machines/crc/id_rsa core@$(~/codeready/crc ip)
Red Hat Enterprise Linux CoreOS 45.82.202007062333-0
  Part of OpenShift 4.5, RHCOS is a Kubernetes native operating system
  managed by the Machine Config Operator (`clusteroperator/machine-config`).
...
```
Then:
```
$ sudo find /var/mnt/pv-data/pv0001/docker/registry/v2
```
I don't see any images in there that match Kubernetes `Event`s that I see like: `Container image "gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0" already present on machine`. (That's not the image I want to purge it's just an example.)

Thank you

**Comment by cfergeau** [comment]
If you are already logged in into the VM, you could run `docker images -q | xargs docker image rm -f` with `s/docker/sudo podman/`
For a more 'openshifty' way using `oc`, I don't know if it's covered in OpenShift documentation? Maybe something with `oc delete`?

**Comment by aceeric** [comment]
You prompted me to try something and - logged into the VM:
```
[core@crc-nsk8x-master-0 ~]$ sudo docker images
sudo: docker: command not found

[core@crc-nsk8x-master-0 ~]$ podman images --all
REPOSITORY   TAG   IMAGE ID   CREATED   SIZE

[core@crc-nsk8x-master-0 ~]$ sudo podman images --all
REPOSITORY                                                            TAG                  IMAGE ID       CREATED        SIZE
quay.io/openshift-release-dev/ocp-v4.0-art-dev                        <none>               f6a02aceec0b   2 months ago   343 MB
quay.io/openshift-release-dev/ocp-v4.0-art-dev                        <none>               02ec8d0b4afa   2 months ago   237 MB
quay.io/openshift-release-dev/ocp-v4.0-art-dev                        <none>               6b4bed9335d4   2 months ago   289 MB
docker.elastic.co/eck/eck-operator                                    1.1.2                2670694f5eb5   3 months ago   262 MB
docker.io/strimzi/kafka                                               0.18.0-kafka-2.5.0   1db6b6b5a55e   3 months ago   607 MB
docker.io/strimzi/operator                                            0.18.0               c66b8181331d   3 months ago   470 MB
registry.opensource.zalan.do/acid/postgres-operator                   v1.5.0               4d59f46f66ba   3 months ago   64.9 MB
...
```
So the key was to use sudo.
