### ISSUE TITLE
how to add worker node with CRC in same machine

### ISSUE THREAD

**Issue by doyoungim999** [code-ready/crc#1497]
### General information

  * OS: Linux / macOS / Windows
Linux (centos7.8)
  * Hypervisor: KVM / Hyper-V / hyperkit
KVM 
  * Did you run `crc setup` before starting it (Yes/No)?
Yes

## CRC version
```bash
# Put the output of `crc version`
```
  [user1@centos7 ~]$ crc version
CodeReady Containers version: 1.15.0+e317bed
OpenShift version: 4.5.7 (embedded in binary)

## CRC status
```bash


# Put the output of `crc status`
```
[user1@centos7 ~]$ crc status
ERRO Cannot get root partition usage: ssh command error:
command : df -B1 --output=size,used,target /sysroot | tail -1
err     : exit status 255
output  :
Cannot get root partition usage: ssh command error:
command : df -B1 --output=size,used,target /sysroot | tail -1
err     : exit status 255
output  :

## CRC config
```bash
# Put the output of `crc config view`
```
[user1@centos7 ~]$ crc config view

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
[user1@centos7 ~]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```

### Steps to reproduce

  1.  want to add  CoreOS/ RHEL VM in same server and make it worker node with CRC. 
  2.  updated crc network with <range start...end /> 
<network>
  <name>crc</name>
  <uuid>49eee855-d342-46c3-9ed3-b8d1758814cd</uuid>
  <forward mode='nat'>
    <nat>
      <port start='1024' end='65535'/>
    </nat>
  </forward>
  <bridge name='crc' stp='on' delay='0'/>
  <mac address='52:54:00:fd:be:d0'/>
  <ip family='ipv4' address='192.168.130.1' prefix='24'>
    <dhcp>
      **<range start='192.168.130.21' end='192.168.130.254' />**
      <host mac='52:fd:fc:07:21:82' ip='192.168.130.11' />
    </dhcp>
  </ip>
</network>

  3. After I virsh net-destroy/net-define/net-start crc with above <range ...> , 
I cannot access crc vm.

  4. I got destination Host Unreachable. 
[root@centos7 download]# ping 192.168.130.11
PING 192.168.130.11 (192.168.130.11) 56(84) bytes of data.
From 192.168.130.1 icmp_seq=1 Destination Host Unreachable
From 192.168.130.1 icmp_seq=2 Destination Host Unreachable
From 192.168.130.1 icmp_seq=3 Destination Host Unreachable
From 192.168.130.1 icmp_seq=4 Destination Host Unreachable
^C
--- 192.168.130.11 ping statistics ---
5 packets transmitted, 0 received, +4 errors, 100% packet loss, time 4000ms
pipe 4
[root@centos7 download]# ping 192.168.130.1
PING 192.168.130.1 (192.168.130.1) 56(84) bytes of data.
64 bytes from 192.168.130.1: icmp_seq=1 ttl=64 time=0.056 ms
64 bytes from 192.168.130.1: icmp_seq=2 ttl=64 time=0.059 ms
^C
--- 192.168.130.1 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1000ms
rtt min/avg/max/mdev = 0.056/0.057/0.059/0.007 ms

### Expected
Can ping crc vm by "ping 192.168.130.11"

### Actual
[root@centos7 download]# ping 192.168.130.11
PING 192.168.130.11 (192.168.130.11) 56(84) bytes of data.
From 192.168.130.1 icmp_seq=1 Destination Host Unreachable
From 192.168.130.1 icmp_seq=2 Destination Host Unreachable
From 192.168.130.1 icmp_seq=3 Destination Host Unreachable
From 192.168.130.1 icmp_seq=4 Destination Host Unreachable
^C
--- 192.168.130.11 ping statistics ---

### Logs

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

This is only for self testing in one machine with CRC.  
I would appreciate your opinion about virtual network configuration in CRC environment.

**Comment by gbraad** [comment]
CRC is supposed to be used as a SNC (Single-node Cluster). A MNC (Multi-node Cluster) is not supported at the moment and feels more like a usecase for the OpenShift installer.
