### ISSUE TITLE
Enhance the troubleshooting guide

### ISSUE THREAD

**Issue by robin-owen** [code-ready/crc#150]
We could use examples of how to gather information to be used for troubleshooting purposes.

**Comment by gbraad** [comment]
one would be #160, but also commands like `oc get co`

**Comment by robin-owen** [comment]
Seems we could also use `crc delete && crc start --log-level debug`. We could at least mention this in docs as part of the suggestion to open a new issue in this repo.

**Comment by cfergeau** [comment]
If you mention `crc delete`, you need to make it very clear it's going to lose all changes which were done to the CodeReady Containers instance.

**Comment by robin-owen** [comment]
As far as I'm concerned, this is done.
