### ISSUE TITLE
[BUG] Install fails with looping .crc/machines/crc/id_rsa

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [code-ready/crc#1501]
### General information

  * OS: Linux, Fedora 32
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes, sure
  * Running CRC on: Laptop

## CRC version
```bash
$ crc version
CodeReady Containers version: 1.15.0+e317bed
OpenShift version: 4.5.7 (embedded in binary)
```
  
## CRC status
```bash
$ crc status --log-level debug
DEBU CodeReady Containers version: 1.15.0+e317bed 
DEBU OpenShift version: 4.5.7 (embedded in binary) 
DEBU                                              
ERRO Cannot get root partition usage: stat /home/user/.crc/machines/crc/id_rsa: no such file or directory 
Cannot get root partition usage: stat /home/user/.crc/machines/crc/id_rsa: no such file or directory
```

## CRC config
```bash
$ `crc config view`
an empty output...
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
$ cat /etc/os-release 
NAME=Fedora
VERSION="32 (Thirty Two)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Thirty Two)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"

```

### Steps to reproduce

  1. crc setup
  2. In the .bashrc I have a little shell method to start crc:
```
crc-start() {
    crc start -c 4 -m 20000 -p ${HOME}/system/crc-linux-1.15.0-amd64/pull-secret.txt
}

```
So command to start in the terminal:

```bash
$ crc-start
```
 First crc start was good, but...
  3.Turn off laptop:
```
$ shutdown now
```
  4. Turn on and try to start crc again:
```
crc-start
```

### Expected
crc started and works without any critical errors.

### Actual
crc failed in loop with an error.

### Logs
crc-start 
INFO Checking if oc binary is cached              
INFO Checking if podman remote binary is cached   
INFO Checking if goodhosts binary is cached       
INFO Checking minimum RAM requirements            
INFO Checking if running as non-root              
INFO Checking if Virtualization is enabled        
INFO Checking if KVM is enabled                   
INFO Checking if libvirt is installed             
INFO Checking if user is part of libvirt group    
INFO Checking if libvirt daemon is running        
INFO Checking if a supported libvirt version is installed 
INFO Checking if crc-driver-libvirt is installed  
INFO Checking if libvirt 'crc' network is available 
INFO Checking if libvirt 'crc' network is active  
INFO Checking if NetworkManager is installed      
INFO Checking if NetworkManager service is running 
INFO Checking if /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf exists 
INFO Checking if /etc/NetworkManager/dnsmasq.d/crc.conf exists 
INFO Starting CodeReady Containers VM for OpenShift 4.5.7... 
ERRO Failed to connect to the CRC VM with SSH -- host might be unreachable: Temporary Error: stat /home/user/.crc/machines/crc/id_rsa: no such file or directory
Temporary Error: stat /home/user/.crc/machines/crc/id_rsa: no such file or directory

These step fix crc:
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

output of `crc start --log-level debug`  on https://gist.github.com/AndrienkoAleksandr/a8b1f4fb754f7004effa432e1e7cb860

**Comment by cfergeau** [comment]
Could you check the content of `/home/user/.crc/machines/crc/` (in particular whether `id_rsa` exists) before/after shutting down the laptop? It would be unexpected that this file goes away on reboots :)
