### ISSUE TITLE
DNS Query Fails During CRC Start And Unable to Create New App From Image

### ISSUE THREAD

**Issue by dixonwhitmire** [code-ready/crc#1506]
Hello, 

I began having DNS related issues with my local CRC install yesterday. I had previously used CRC without issue about two weeks ago. 

The error which appears during startup is
```
WARN Failed public DNS query from the cluster: ssh command error:
command : host -R 3 quay.io
err     : exit status 1
output  : ;; connection timed out; no servers could be reached
```

Once the cluster is started, and I have logged in, I am unable to use oc to create a new app using an image from docker hub.
```
dixons-mbp Dixon.Whitmire@ibm.com$ oc new-project test-project
Now using project "test-project" on server "https://api.crc.testing:6443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app ruby~https://github.com/sclorg/ruby-ex.git

to build a new example application in Ruby. Or use kubectl to deploy a simple Kubernetes application:

    kubectl create deployment hello-node --image=gcr.io/hello-minikube-zero-install/hello-node

dixons-mbp Dixon.Whitmire@ibm.com$ oc new-app openshift/hello-openshift --name=hello-openshift
W0903 18:09:18.651716    8009 dockerimagelookup.go:237] container image registry lookup failed: docker.io/openshift/hello-openshift:latest: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 172.25.0.10:53: server misbehaving
error:  local file access failed with: stat openshift/hello-openshift: no such file or directory
error: unable to locate any images in image streams, templates loaded in accessible projects, template files, local docker images with name "openshift/hello-openshift"

Argument 'openshift/hello-openshift' was classified as an image, image~source, or loaded template reference.
```
After I received the error I removed CRC and installed the latest version, since I hadn't used it in a while. The error/issue still occurs.

Current CRC version
```
dixons-mbp Dixon.Whitmire@ibm.com$ crc version
CodeReady Containers version: 1.15.0+e317bed
OpenShift version: 4.5.7 (embedded in binary)
```

I am running on OS 10.15.6 (Catalina). My CLI output and crc.log files are attached.

[crc-cli-commands.log](https://github.com/code-ready/crc/files/5171657/crc-cli-commands.log)

[crc.log](https://github.com/code-ready/crc/files/5171659/crc.log)

Any suggestions would be greatly appreciated. Thanks!

**Comment by cfergeau** [comment]
It looks like the VM does not have external connectivity, or DNS. Can you try to use the `--nameserver 1.1.1.1` argument with `crc start`? Are you on a VPN?

**Comment by IRQs** [comment]
First-time CRC user here. I just ran into exactly the same issue on my first ever CRC start with the same build, albeit on Windows 10. Restarting CRC with the additional nameserver seems to have resolved the DNS issues. Before that change, I was also getting `dial tcp: lookup quay.io on 172.25.0.10:53: server misbehaving` all over the place.

**Comment by dixonwhitmire** [comment]
Hi @cfergeau, 

Including the ``--nameserver 1.1.1.1` argument allows me to provision my applications using Docker Hub images. I am not on a VPN, but I am using a mesh network with my home's wi-fi. When I bypass the mesh network the DNS startup check passes, but I am still unable to provision my applications, unless I use the nameserver argument.

Thank you for the help!

**Comment by praveenkumar** [comment]
Since it is fixed by adding the nameserver, I am going to close this now.

**Comment by ckvtvm-arch** [comment]
It doesnt solve in my case :

**Comment by ckvtvm-arch** [comment]
Internal error occurred: registry.redhat.io/rh-sso-7/sso74-openshift-rhel8:latest: Get "https://registry.redhat.io/v2/": dial tcp: lookup registry.redhat.io on 172.25.0.10:53: server misbehaving

**Comment by ckvtvm-arch** [comment]
Internal error occurred: registry.hub.docker.com/jboss/keycloak:latest: Get "https://registry.hub.docker.com/v2/": dial tcp: lookup registry.hub.docker.com on 172.25.0.10:53: server misbehaving

**Comment by cfergeau** [comment]
Can you file a new issue with logs so that it can be investigated properly?
