### ISSUE TITLE
Support VM snapshots

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#1507]
It will be really great to be able to snapshot the VM easily. 
One use case is OpenShift QA.

```
$ crc snapshots create
$ crc snapshots list
etc..
``` 

cc @veillard

**Comment by praveenkumar** [comment]
@guillaumerose I am not sure if hyperkit have functionality to create the snapshots, for libvirt and hyperV should be easy.

**Comment by gbraad** [comment]
Hyper-V has, but can you explain more about what you want to gain from this?
the OS is supposed to be immutable and therefore only container images and projects (actual OpenShift data is kept in `/var`).
Is this allow export and distribution of these artifacts and/or easy rollbacks to a state for use in CI?
