### ISSUE TITLE
Package crc in a MSI for Windows and pkg for macOS

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#1516]
Native packaging is important if we want to provide a good user experience.

Pros:
* crc setup can be run during the install.
* admin. rights are handled by default.
* it will be easier to sign/notarize on macOS
Cons:
* more code to maintain and test.

For Linux, I don't have a good answer.

**Comment by guillaumerose** [comment]
We can use https://github.com/mh-cbon/go-msi

**Comment by cfergeau** [comment]
https://wiki.gnome.org/msitools may also be an option if we want something which can be run on linux.

**Comment by guillaumerose** [comment]
pkg is WIP. msi will come right after.

**Comment by guillaumerose** [comment]
msi and pkg exist now. Keeping #16 until the MSI is used by default.
