### ISSUE TITLE
Install CRC without having to login to Redhat?

### ISSUE THREAD

**Issue by magick93** [code-ready/crc#1525]
Hello

I'm wondering if there is a way to install CRC that doesnt require having to login to Redhat?

Is there another location where the binaries can be downloaded that is public?

Thanks

**Comment by gbraad** [comment]
Please see #977 (duplicate)

**Comment by gbraad** [comment]
CRC can not be provided without registration as it uses RHEL CoreOS and the OpenShift Container Platform (OCP). Even if you would download the binaries from mirror.openshift.com, you can not use them without the necessary pull-secret.

A registration free version has to use OKD, which is based on Fedora CoreOS... work on this has been done, but images aren't publicly offered yet (no download location is available).
