### ISSUE TITLE
Issues with network operator and custom certificate

### ISSUE THREAD

**Issue by daronhudson** [code-ready/crc#1531]
### General information

  * OS: Linux
  * Hypervisor: KVM 
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
# Put the output of `crc version`
1.16.0-4.5.9
```
  
## CRC status
```bash
# Put the output of `crc status`
In project default on server https://api.crc.teamnx.net:6443

svc/openshift - kubernetes.default.svc.cluster.local
svc/kubernetes - 172.25.0.1:443 -> 6443
```

## CRC config
```bash
# Put the output of `crc config view`
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://api.crc.teamnx.net:6443
  name: crc
contexts:
- context:
    cluster: crc
    user: admin
  name: admin
current-context: admin
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### Steps to reproduce

  1. install the openshift crc platform using snc
  2. replace the ingress certificates following [this guide](https://docs.openshift.com/container-platform/4.5/security/certificates/replacing-default-ingress-certificate.html)
  3. cluster network operator fails to verify

### Expected
it should just accept the ca-bundle trust

### Actual

![image](https://user-images.githubusercontent.com/26112933/93661580-dd7ed700-fa26-11ea-89c9-81857b9c4457.png)

### Logs

https://gist.github.com/daronhudson/bc11b3ec7c51468d6de1fc6eb2dc633e

**Comment by cfergeau** [comment]
The message seems to indicate your custom-ca is not in the right format.

**Comment by daronhudson** [comment]
It's in plain readable format, as far as I'm aware PEM is just plain text and not binary and all that like DER

**Comment by praveenkumar** [comment]
@daronhudson what is your motive here, to change the default ingress domain and use something different?
