### ISSUE TITLE
Add TLS CAs to json output

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#1556]
Any json output which returns an https URL should also
contain the TLS CAs which are going to be used when connecting 
to this https endpoint, as it's likely to be using a custom CA.

**Comment by gbraad** [comment]
What would you include? the CN, the fingerprint or the actual content?

**Comment by cfergeau** [comment]
It must be the actual content so that one can do `curl --cacert xxx https://api.crc.testing:6443` after extracting the CA from the JSON data.

**Comment by guillaumerose** [comment]
PR merged
