### ISSUE TITLE
Implement preflights for  f33

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#1572]
Fedora 33 is using systemd-resolved by default https://fedoraproject.org/wiki/Changes/systemd-resolved 
We need to test how this impacts crc DNS setup

**Comment by childofthewired** [comment]
Internal Wildcard DNS setup via DNSMasq is ends up broken.

**Comment by cfergeau** [comment]
https://fedoramagazine.org/systemd-resolved-introduction-to-split-dns/ might be useful.

**Comment by dgolovin** [comment]
@praveenkumar I have the same issue, just installed Fedora 33 and crc seems to run fine OOTB, but nothing can be deployed to the cluster with odo. Will have to swithc back to deb until this is fixed.

**Comment by cfergeau** [comment]
Can you be a bit more specific about 'nothing can be deployed to the cluster with odo'? I  would expect that application deployment goes fine with odo, but then the URL to which you deployed the application would not be reachable. 
So far I've only tested f33 up to "the cluster starts up and `oc get co` is good", I'll have to run more tests with odo.

The goodhosts fallback code is apparently enough to get a cluster working reasonably well (`oc get co` is fine, but `WARN Wildcard DNS resolution for apps-crc.testing does not appear to be working` is shown during startup)

**Comment by childofthewired** [comment]
@cfergeau after deploying CRC we are able to log into the console with "crc console" and we can deploy an application in the UI, but the wildcard DNS is not setup properly for the route.

When logging in from the console, we can 'oc get project' and get a list of our projects including the ones that we created, and all the objects in it.

**Comment by cfergeau** [comment]
ok, if it's only wildcard DNS which is not working, this is good news as this was the part most likely to break. This can be worked around by adding manually entries in /etc/hosts if needed, though Praveen is working on a better fix.

**Comment by jlyle** [comment]
> @cfergeau after deploying CRC we are able to log into the console with "crc console" and we can deploy an application in the UI, but the wildcard DNS is not setup properly for the route.
> 
> When logging in from the console, we can 'oc get project' and get a list of our projects including the ones that we created, and all the objects in it.

@cfergeauI I am working with @childofthewired  and added the application name and ip of the cluster to my /etc/hosts and it resolved properly, thank you

**Comment by cfergeau** [comment]
An alternative which worked fine for me is:
```
sudo resolvectl domain crc ~testing
sudo resolvectl dns crc 192.168.130.11
sudo resolvectl default-route crc false
```

**Comment by dgolovin** [comment]
> Can you be a bit more specific about 'nothing can be deployed to the cluster with odo'? I would expect that application deployment goes fine with odo, but then the URL to which you deployed the application would not be reachable.

@cfergeau sorry for not being clear, you are correct here, I can create components with odo, push them to the crc managed cluster, but cannot reach them.

**Comment by cfergeau** [comment]
I'm currently having success  with adding
```
$ cat 10-crc
#!/bin/sh
# This is a NetworkManager dispatcher script to configure split DNS for
# the 'crc' libvirt network.
# The corresponding bridge is recreated each time the system reboots, so
# it cannot be configured permanently through NetworkManager.
# Changing DNS settings through nmcli requires the connection to go down/up,
# so we directly do the change through resolvectl

export LC_ALL=C

if [ "$1" = crc ] && [ "$2" = up ]; then
        resolvectl domain crc ~testing
        resolvectl dns crc 192.168.130.11
        resolvectl default-route crc false
fi

exit 0
```
in `/etc/NetworkManager/dispatcher.d/10-crc` and making the file executable. This will need a destroy/start of the libvirt `crc` network, or a reboot of the host as this is only triggered when the `crc` NM interface state changes to `up`

**Comment by tanwald** [comment]
Thank you @cfergeau, your dispatcher script resolves the wildcard dns issue on Fedora 33.

Cosmetics: If you put the script into `/etc/NetworkManager/dispatcher.d/pre-up.d` it works too and you can omit the second condition (`[ "$2" = up ]`). I just discovered the subdirectories and thought that this would be the designated directory...

**Comment by cfergeau** [comment]
Another usecase for systemd-resolved support https://github.com/code-ready/crc/issues/1663#issuecomment-727201187
But if this is not the default RHEL setup (I don't think it is), then distro checks won't be enough to manage this.

**Comment by cfergeau** [comment]
> Cosmetics: If you put the script into `/etc/NetworkManager/dispatcher.d/pre-up.d` it works too and you can omit the second condition (`[ "$2" = up ]`). I just discovered the subdirectories and thought that this would be the designated directory...

Ah that's a good point, I saw the directory as well, but did not notice any difference in behaviour, so I stuck with the main one. Did not occur to me to remove the `up` check ^^ Thanks!

**Comment by cfergeau** [comment]
Manual steps to configure f33 for crc:
- If you ran crc previously, start with:
```
$ crc delete
$ crc cleanup
```
- To configure DNS resolution for f33:
-- Disable NetworkManager dnsmasq configuration:
```
$ crc config set skip-check-network-manager-config true
$ crc  config set skip-check-crc-dnsmasq-file true
```
-- Create a `/etc/NetworkManager/dispatcher.d/99-crc` file with this content:
```
 $ cat 10-crc
#!/bin/sh
# This is a NetworkManager dispatcher script to configure split DNS for
# the 'crc' libvirt network.
# The corresponding bridge is recreated each time the system reboots, so
# it cannot be configured permanently through NetworkManager.
# Changing DNS settings through nmcli requires the connection to go down/up,
# so we directly do the change through resolvectl

export LC_ALL=C

if [ "$1" = crc ]; then
        resolvectl domain crc ~testing
        resolvectl dns crc 192.168.130.11
        resolvectl default-route crc false
fi

exit 0
```
-- Make this file executable:
```
$ chmod 755 /etc/NetworkManager/dispatcher.d/99-crc
```
- Start `crc` as usual:
```
$ crc setup
$ crc start
```

**Comment by jlyle** [comment]
@cfergeau This worked perfectly!  Thank you!

**Comment by childofthewired** [comment]
Of note - users should probably also ensure:
# systemctl enable libvirtd --now 
has been performed on the system as well to ensure that the networks start on boot.

**Comment by cfergeau** [comment]
I believe a default install of libvirt will start any required systemd unit at boot time. With libvirtd socket activation, it's a bit hard to know exactly which unit should be enabled (libvirtd.service, libvirtd.socket, one of the split systemd units?), so we only warn if nothing libvirtd-related is enabled.

**Comment by guillaumerose** [comment]
Available in 1.20.0

**Comment by wdrdres3qew5ts21** [comment]
Hello CRC Teams I'm using Fedora 33 with 1.20.0 but I still encounter this problem.
I still need to using solution from @cfergeau does it have anyway to debug ? Or how can I learn more about this behavior ?
```
sudo resolvectl domain crc ~testing
sudo resolvectl dns crc 192.168.130.11
sudo resolvectl default-route crc false
```
If I using above command I will can access Routes without problem.

##### WARN Wildcard DNS resolution for apps-crc.testing does not appear to be working 
```
crc version
CodeReady Containers version: 1.20.0+ef3f80d
OpenShift version: 4.6.6 (embedded in executable)


INFO Loading bundle: crc_libvirt_4.6.6.crcbundle ... 
INFO Verifying bundle crc_libvirt_4.6.6.crcbundle ... 
INFO Creating CodeReady Containers VM for OpenShift 4.6.6... 
INFO CodeReady Containers VM is running           
INFO Generating new SSH Key pair ...              
INFO Updating authorized keys ...                 
INFO Copying kubeconfig file to instance dir ...  
INFO Starting network time synchronization in CodeReady Containers VM 
INFO Adding 8.8.8.8 as nameserver to the instance ... 
INFO Check internal and public DNS query ...      
INFO Check DNS query from host ...                
WARN Wildcard DNS resolution for apps-crc.testing does not appear to be working 
INFO Adding user's pull secret to instance disk... 
INFO Verifying validity of the kubelet certificates ... 
INFO Starting OpenShift kubelet service           
INFO Configuring cluster for first start          
INFO Adding user's pull secret to the cluster ... 
INFO Updating cluster ID ...                      
INFO Starting OpenShift cluster ... [waiting 3m]  
INFO Updating kubeconfig                          
WARN The cluster might report a degraded or error state. This is expected since several operators have been disabled to lower the resource usage. For more information, please consult the documentation 
```
![image](https://user-images.githubusercontent.com/25000903/103449738-1a718f80-4cdf-11eb-8f86-b33bc21c716b.png)
![image](https://user-images.githubusercontent.com/25000903/103449805-eba7e900-4cdf-11eb-8015-cc892811729d.png)
![image](https://user-images.githubusercontent.com/25000903/103449839-71c42f80-4ce0-11eb-8fab-2178f07ba6af.png)

I'm using Fedora 33 with CRC 1.20 should this problem still insist ? If you need any logs to investigate please let me know :100:

**Comment by cfergeau** [comment]
I would first try `crc delete && crc cleanup && crc setup`, and check if right after that things are working. There is a known issue with 1.20 where the network configuration is lost if you enable a vpn (or I guess plug/unplug an ethrenet cable, or connect to a wifi network, ...)

**Comment by wdrdres3qew5ts21** [comment]
I had try it already because I encounter this problem with my fresh installation Fedora 33 also had try to delete cluster multiple time but still encounter this problem does it have anyway to bebug or found logs of this behavior ?

**Comment by cfergeau** [comment]
`crc delete && crc cleanup && crc setup --log-level debug && crc start --log-level debug` would be a good start.

**Comment by rhtevan** [comment]
@wdrdres3qew5ts21 Try this as a workaround to the issue, as enable/disable VPN will wipe out the settings.
```
sudo nmcli connection down crc && nmcli connection up crc
```

**Comment by cfergeau** [comment]
I'd recommend `virsh -c qemu:///system net-destroy crc; virsh -c qemu:///system net-start crc` rather than nmcli interactions.

**Comment by DE110283** [comment]
Facing same issue on Fedora 33 and fresh installed CRC 1.20. Also tried the 99-crc.sh workaround but still not working.

> INFO Checking if podman remote executable is cached 
INFO Checking if goodhosts executable is cached   
INFO Checking minimum RAM requirements            
INFO Checking if running as non-root              
INFO Checking if Virtualization is enabled        
INFO Checking if KVM is enabled                   
INFO Checking if libvirt is installed             
INFO Checking if user is part of libvirt group    
INFO Checking if libvirt daemon is running        
INFO Checking if a supported libvirt version is installed 
INFO Checking if crc-driver-libvirt is installed  
INFO Checking if systemd-networkd is running      
INFO Checking if NetworkManager is installed      
INFO Checking if NetworkManager service is running 
INFO Checking if dnsmasq configurations file exist for NetworkManager 
INFO Checking if the systemd-resolved service is running 
INFO Checking if /etc/NetworkManager/dispatcher.d/pre-up.d/99-crc.sh exists 
INFO Checking if libvirt 'crc' network is available 
INFO Checking if libvirt 'crc' network is active  
INFO Starting CodeReady Containers VM for OpenShift 4.6.6... 
INFO CodeReady Containers VM is running           
INFO Starting network time synchronization in CodeReady Containers VM 
INFO Check internal and public DNS query ...      
INFO Check DNS query from host ...                
WARN Wildcard DNS resolution for apps-crc.testing does not appear to be working 
INFO Verifying validity of the kubelet certificates ... 
INFO Starting OpenShift kubelet service           
INFO Starting OpenShift cluster ... [waiting 3m]  
INFO Updating kubeconfig                          
WARN The cluster might report a degraded or error state. This is expected since several operators have been disabled to lower the resource usage. For more information, please consult the documentation 


resolvectl workaround is working fine:

> sudo resolvectl domain crc ~testing
sudo resolvectl dns crc 192.168.130.11
sudo resolvectl default-route crc false

**Comment by paul-snively** [comment]
For what it's worth:

```
psnively@oryx-pro:~/duck|⇒  crc version
CodeReady Containers version: 1.21.0+68a4cdd7
OpenShift version: 4.6.9 (embedded in executable)
psnively@oryx-pro:~/duck|⇒  uname -a
Linux oryx-pro 5.4.0-64-generic #72~18.04.1-Ubuntu SMP Fri Jan 15 14:06:34 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
psnively@oryx-pro:~/duck|⇒  lsb_release -a
No LSB modules are available.
Distributor ID: elementary
Description:    elementary OS 5.1.7 Hera
Release:        5.1.7
Codename:       hera
```

I consistently get:

```
INFO Check DNS query from host ...                
DEBU api.crc.testing resolved to [192.168.130.11] 
WARN Wildcard DNS resolution for apps-crc.testing does not appear to be working 
```

when `setup` and `start`ing `crc`. I think something is likely looking for an Ubuntu distribution, which Elementary is based on, but missing it, so maybe missing a `setup` step around dnsmasq/NetworkManager, maybe?

**Comment by cfergeau** [comment]
`crc cleanup && crc setup --log-level debug` should provide more information regarding what it's doing. Is Elementary using systemd-resolved + systemd-networkd, or systemd-resolved + NetworkManager? (`systemd status systemd-networkd` shoud help)

**Comment by paul-snively** [comment]
> `crc cleanup && crc setup --log-level debug` should provide more information regarding what it's doing.

I think the issue here is that it doesn't introspect on how the underlying infrastructure resolves DNS, to your next point:

> Is Elementary using systemd-resolved + systemd-networkd, or systemd-resolved + NetworkManager? (`systemd status systemd-networkd` should help)

Right. Elementary, like Ubuntu 18.04 upon which it's based, I believe, uses systemd-resolved + NetworkManager.

**Comment by cfergeau** [comment]
> I think the issue here is that it doesn't introspect on how the underlying infrastructure resolves DNS, to your next point:

Yes, this code is still evolving, and we are not guiding network configuration with feature checks, but just through some distro -> network configuration mapping. I'd still be curious to see the logs of `crc cleanup && crc setup --log-level debug` to understand what it's trying to do. And `/etc/os-release` would be useful to understand why it's not taking the correct ubuntu code path.

**Comment by paul-snively** [comment]
Right, sorry. I get:

```
psnively@oryx-pro:~/duck|⇒  crc setup --log-level debug
DEBU CodeReady Containers version: 1.21.0+68a4cdd7 
DEBU OpenShift version: 4.6.9 (embedded in executable) 
DEBU Running 'crc setup'                          
CodeReady Containers is constantly improving and we would like to know more about usage!
Would you like to contribute anonymous usage statistics (more details at https://developers.redhat.com/article/tool-data-collection)? [y/N]: 
No worry, you can still enable telemetry manually with the command 'crc config set consent-telemetry yes'.
INFO Checking if running as non-root              
INFO Checking if podman remote executable is cached 
DEBU Currently podman remote is not supported     
INFO Checking if admin-helper executable is cached 
DEBU admin-helper executable is not cached        
INFO Caching admin-helper executable              
DEBU Trying to extract admin-helper-linux from crc executable 
DEBU Extracting embedded 'admin-helper-linux' from /usr/local/bin/crc to /tmp/crc084220726/admin-helper-linux 
DEBU Copying '/tmp/crc084220726/admin-helper-linux' to '/home/psnively/.crc/bin/admin-helper-linux' 
DEBU admin-helper executable cached               
DEBU Making /home/psnively/.crc/bin/admin-helper-linux suid 
INFO Will use root access: change ownership of /home/psnively/.crc/bin/admin-helper-linux 
DEBU Running '/usr/bin/sudo chown root /home/psnively/.crc/bin/admin-helper-linux' 
INFO Will use root access: set suid for /home/psnively/.crc/bin/admin-helper-linux 
DEBU Running '/usr/bin/sudo chmod u+s,g+x /home/psnively/.crc/bin/admin-helper-linux' 
INFO Checking if CRC bundle is extracted in '$HOME/.crc' 
DEBU stat /home/psnively/.crc/cache/crc_libvirt_4.6.9.crcbundle: no such file or directory 
INFO Extracting bundle from the CRC executable    
DEBU Error changing /home/psnively/.crc/cache permissions to 0775 
DEBU Extracting embedded 'crc_libvirt_4.6.9.crcbundle' from /usr/local/bin/crc to /home/psnively/.crc/cache/crc_libvirt_4.6.9.crcbundle 
DEBU Uncompressing /home/psnively/.crc/cache/crc_libvirt_4.6.9.crcbundle to /home/psnively/.crc/cache 
crc.qcow2: 9.85 GiB / 9.85 GiB [-----------------------------------------------------------------------------------------------------------------------------------] 100.00%
INFO Checking minimum RAM requirements            
DEBU Total memory of system is 33523884032 bytes  
INFO Checking if Virtualization is enabled        
DEBU Checking if the vmx/svm flags are present in /proc/cpuinfo 
DEBU CPU virtualization flags are good            
INFO Checking if KVM is enabled                   
DEBU Checking if /dev/kvm exists                  
DEBU /dev/kvm was found                           
INFO Checking if libvirt is installed             
DEBU Checking if 'virsh' is available             
DEBU 'virsh' was found in /usr/bin/virsh          
DEBU Checking 'virsh capabilities' for libvirtd/qemu availability 
DEBU Running 'virsh capabilities'                 
DEBU Found x86_64 hypervisor with 'hvm' capabilities 
INFO Checking if user is part of libvirt group    
DEBU Checking if current user is part of the libvirt group 
DEBU Running '/usr/bin/groups psnively'           
DEBU Current user is already in the libvirt group 
INFO Checking if libvirt daemon is running        
DEBU Checking if libvirtd service is running      
DEBU Running 'systemctl status virtqemud.socket'  
DEBU Command failed: exit status 4                
DEBU stdout:                                      
DEBU stderr: Unit virtqemud.socket could not be found. 
DEBU virtqemud.socket is neither running nor listening 
DEBU Running 'systemctl status libvirtd.socket'   
DEBU Command failed: exit status 4                
DEBU stdout:                                      
DEBU stderr: Unit libvirtd.socket could not be found. 
DEBU libvirtd.socket is neither running nor listening 
DEBU Running 'systemctl status virtqemud.service' 
DEBU Command failed: exit status 4                
DEBU stdout:                                      
DEBU stderr: Unit virtqemud.service could not be found. 
DEBU virtqemud.service is neither running nor listening 
DEBU Running 'systemctl status libvirtd.service'  
DEBU libvirtd.service is running                  
INFO Checking if a supported libvirt version is installed 
DEBU Checking if libvirt version is >=3.4.0       
DEBU Running 'virsh -v'                           
INFO Checking if crc-driver-libvirt is installed  
DEBU Checking if crc-driver-libvirt is installed  
DEBU crc-driver-libvirt executable is not cached  
INFO Installing crc-driver-libvirt                
DEBU Installing crc-driver-libvirt                
DEBU Trying to extract crc-driver-libvirt from crc executable 
DEBU Extracting embedded 'crc-driver-libvirt' from /usr/local/bin/crc to /tmp/crc159341853/crc-driver-libvirt 
DEBU Copying '/tmp/crc159341853/crc-driver-libvirt' to '/home/psnively/.crc/bin/crc-driver-libvirt' 
DEBU crc-driver-libvirt is installed in /home/psnively/.crc/bin 
INFO Checking if AppArmor is configured           
DEBU AppArmor profile not configured              
INFO Updating AppArmor configuration              
INFO Will use root access: updating AppArmor configuration 
INFO Will use root access: Changing permission for /etc/apparmor.d/libvirt/TEMPLATE.qemu to 644  
DEBU Running '/usr/bin/sudo chmod 644 /etc/apparmor.d/libvirt/TEMPLATE.qemu' 
INFO Checking if systemd-networkd is running      
DEBU Checking if systemd-networkd.service is running 
DEBU Running 'systemctl status systemd-networkd.service' 
DEBU Command failed: exit status 3                
DEBU stdout: * systemd-networkd.service - Network Service
   Loaded: loaded (/lib/systemd/system/systemd-networkd.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:systemd-networkd.service(8) 
DEBU stderr:                                      
DEBU systemd-networkd.service is not running      
INFO Checking if NetworkManager is installed      
DEBU Checking if 'nmcli' is available             
DEBU 'nmcli' was found in /usr/bin/nmcli          
INFO Checking if NetworkManager service is running 
DEBU Checking if NetworkManager.service is running 
DEBU Running 'systemctl status NetworkManager.service' 
DEBU NetworkManager.service is already running    
INFO Checking if dnsmasq configurations file exist for NetworkManager 
INFO Checking if the systemd-resolved service is running 
DEBU Checking if systemd-resolved.service is running 
DEBU Running 'systemctl status systemd-resolved.service' 
DEBU systemd-resolved.service is already running  
INFO Checking if /etc/NetworkManager/dispatcher.d/99-crc.sh exists 
DEBU Checking NetworkManager dispatcher file for crc network 
DEBU File not found: /etc/NetworkManager/dispatcher.d/99-crc.sh: stat /etc/NetworkManager/dispatcher.d/99-crc.sh: no such file or directory 
INFO Writing NetworkManager dispatcher file for crc 
DEBU Fixing NetworkManager dispatcher configuration 
DEBU Checking if 'nmcli' is available             
DEBU 'nmcli' was found in /usr/bin/nmcli          
INFO Will use root access: write NetworkManager configuration to /etc/NetworkManager/dispatcher.d/99-crc.sh 
INFO Will use root access: Changing permission for /etc/NetworkManager/dispatcher.d/99-crc.sh to 755  
DEBU Running '/usr/bin/sudo chmod 755 /etc/NetworkManager/dispatcher.d/99-crc.sh' 
DEBU Reloading NetworkManager                     
INFO Will use root access: executing systemctl daemon-reload command 
DEBU Running '/usr/bin/sudo systemctl daemon-reload' 
INFO Will use root access: executing systemctl reload NetworkManager 
DEBU Running '/usr/bin/sudo systemctl reload NetworkManager' 
DEBU NetworkManager dispatcher configuration fixed 
INFO Checking if libvirt 'crc' network is available 
DEBU Checking if libvirt 'crc' network exists     
DEBU Running 'virsh --connect qemu:///system net-info crc' 
DEBU Command failed: exit status 1                
DEBU stdout:                                      
DEBU stderr: error: failed to get network 'crc'
error: Network not found: no network with matching name 'crc' 
DEBU Libvirt network crc not found                
INFO Setting up libvirt 'crc' network             
DEBU Creating libvirt 'crc' network               
DEBU Running 'virsh --connect qemu:///system net-destroy crc' 
DEBU Command failed: exit status 1                
DEBU stdout:                                      
DEBU stderr: error: failed to get network 'crc'
error: Network not found: no network with matching name 'crc' 
DEBU Running 'virsh --connect qemu:///system net-undefine crc' 
DEBU Command failed: exit status 1                
DEBU stdout:                                      
DEBU stderr: error: failed to get network 'crc'
error: Network not found: no network with matching name 'crc' 
DEBU libvirt 'crc' network created                
INFO Checking if libvirt 'crc' network is active  
DEBU Checking if libvirt 'crc' network is active  
DEBU Running 'virsh --connect qemu:///system net-info crc' 
DEBU Libvirt crc network is not active            
INFO Starting libvirt 'crc' network               
DEBU Starting libvirt 'crc' network               
DEBU Running 'virsh --connect qemu:///system net-start crc' 
DEBU Running 'virsh --connect qemu:///system net-autostart crc' 
DEBU libvirt 'crc' network started                
Setup is complete, you can now run 'crc start' to start the OpenShift cluster
```

and

```
psnively@oryx-pro:~/duck|⇒  cat /etc/os-release
NAME="elementary OS"
VERSION="5.1.7 Hera"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 5.1.7 Hera"
LOGO=distributor-logo
VERSION_ID="5.1.7"
HOME_URL="https://elementary.io/"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/os/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=hera
UBUNTU_CODENAME=bionic
```

You may not be looking at `ID_LIKE` and `UBUNTU_CODENAME` on derivatives like Elementary.

**Comment by cfergeau** [comment]
crc 1.21 takes into account `ID_LIKE=ubuntu`, and the preflight logs show that it's doing the expected configuration for systemd-resolved (dropping a file in `/etc/NetworkManager/dispatcher.d`). So it's something else which is not working as expected? One assumption crc is making is that `systemd-resolved` is listening on port 53 on localhost (127.0.0.53) which is not always true, maybe this is why your setup is different?

Can you check `resolvectl domain` and `resolvectl dns` after running `crc setup`?

**Comment by paul-snively** [comment]
Ubuntu Bionic, on which Elementary OS is based, doesn't have `resolvectl`; it has `systemd-resolve` instead. But I get:

`domain: resolve call failed: No appropriate name servers or networks for name found`

**Comment by cfergeau** [comment]
The binary used to interact with `systemd-resolved` is `/usr/bin/systemd-resolve` and not `/usr/bin/resolvectl`? On my fedora, `systemd-resolve` is a symlink to `resolvectl`.
What command do you type when you get this `resolve call failed` error?

**Comment by paul-snively** [comment]
> The binary used to interact with systemd-resolved is /usr/bin/systemd-resolve and not /usr/bin/resolvectl?

Correct.

> What command do you type when you get this resolve call failed error?

```
psnively@oryx-pro:~|⇒  systemd-resolve domain
domain: resolve call failed: No appropriate name servers or networks for name found
```

I presume `domain` is a subcommand of `resolvectl`, but not of `systemd-resolve`.

**Comment by cfergeau** [comment]
Really not clear why elementary does not install `resolvectl`, and I could not find the equivalent of https://packages.ubuntu.com/search?searchon=contents&keywords=resolvectl&mode=exactfilename&suite=groovy&arch=any for elementary to do a bit more digging.

**Comment by paul-snively** [comment]
FWIW, this changed in [Ubuntu Bionic](https://askubuntu.com/questions/1149364/why-is-resolvectl-no-longer-included-in-bionic-and-whats-the-alternative), which Elementary OS is based on.

I'll try a symlink. Thanks!

**Comment by paul-snively** [comment]
A symlink to `systemd-resolve` didn't work, because as described at the link above, `systemd-resolve` in 18.04 is too old.

Ultimately, the solution I chose was to follow [this gist](https://gist.github.com/Jiab77/7df6e80804567f6f599b227cf2fafd00) in order to upgrade `systemd` on 18.04. This gets me a recent-enough `resolvectl` for its use in the NetworkManager script to succeed. This resolves my issue, but it's hopefully clear that not having a proper solution for Ubuntu 18.04 LTS is really not adequate.

However, that's obviously not due to your not trying to find such a resolution for which I'm grateful. Thanks!

**Comment by cfergeau** [comment]
Oh,  until now I totally missed that the lack of `resolvectl` in older Ubuntu releases, I just assumed that anything using systemd-resolved would have `resolvectl`. I'm afraid solving this is going to be relatively low priority as 18.04 is relatively old (there is a 20.04 LTS release with `resolvectl`). crc should at least check for `resolvectl` availability and fail if it's not present.
