### ISSUE TITLE
Handle the errors effectively to prevent segfault/panic

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#159]
Looks like some of the errors are either we ignored or not handled correctly and that need to address properly.

- If a member is not part of `libvirt` group and user just use `crc start` before `crc setup` it will give panic.

- If user use `crc start` on already running instance that also give the panic.

**Comment by cfergeau** [comment]
I'd address the first issue with https://github.com/cfergeau/crc/commit/40d64394c7b6f18e1ccf2ebd5a9a134d0d136579 , even though we should make the generic code more robust as well.

**Comment by gbraad** [comment]
```diff
-	return false, err
+	return false, errors.New("current user is not in the libvirt group")
```

So the `err` here was created earlier, but not set with a value... as the actual issue came from another call, right? I think we need to be more cautious about the `err`-handling. We need to ad an abstraction to handle some of the simple `if err` handling and for our `result` return in `machine.go`.

**Comment by cfergeau** [comment]
> ```diff
> -	return false, err
> +	return false, errors.New("current user is not in the libvirt group")
> ```
> 
> So the `err` here was created earlier, but not set with a value... as the actual issue came from another call, right? I think we need to be more cautious about the `err`-handling. We need to ad an abstraction to handle some of the simple `if err` handling and for our `result` return in `machine.go`.

`err` was created earlier, but if it was non-null, we returned early, and then we never try to set it again, see https://github.com/cfergeau/crc/blob/40d64394c7b6f18e1ccf2ebd5a9a134d0d136579/pkg/crc/preflight/preflight_checks_linux.go#L154-L161 so the current code is effectively `return false, null`
