### ISSUE TITLE
Unable to find any community operators like Strimzi or Opendatahub operator after a fresh install. 

### ISSUE THREAD

**Issue by rhui** [code-ready/crc#1592]
### General information
  * OS: Linux / Fedora 32 
  * Hypervisor: KVM 
  * Did you run `crc setup` before starting it (Yes/No)? Yes 
  * Running CRC on: Laptop 

## CRC version
crc version
CodeReady Containers version: 1.17.0+99f5c87
OpenShift version: 4.5.14 (embedded in binary)
  
## CRC status
crc status --log-level debug 
DEBU CodeReady Containers version: 1.17.0+99f5c87 
DEBU OpenShift version: 4.5.14 (embedded in binary) 
DEBU About to run SSH command with hidden output  
DEBU SSH command succeeded                        
DEBU About to run SSH command:
df -B1 --output=size,used,target /sysroot | tail -1 
DEBU SSH command results: err: <nil>, output: 32720793600 14758567936 /sysroot 
CRC VM:          Running
OpenShift:       Running (v4.5.14)
Disk Usage:      14.76GB of 32.72GB (Inside the CRC VM)
Cache Usage:     25.68GB
Cache Directory: /home/rhui/.crc/cache
[rhui@MiWiFi-R1CM-srv Downloads]$ 

## CRC config
 crc config view
- memory                                : 15700
- pull-secret-file                      : ./pull-secret.txt
```

## Host Operating System
cat /etc/redhat-release 
Fedora release 32 (Thirty Two)

### Steps to reproduce

  1. Just a fresh install, and there are redhat operator in the operatorhub but none of community operators 
  2. See oc-command.txt and it seems that the catalog are fine. 
  3. See the screen shot on operator hub and there are others just not community. 


### Expected
   1. able to installed community operators like strimzi or opendatahub. 

### Actual

**Comment by rhui** [comment]
[oc-commands.txt](https://github.com/code-ready/crc/files/5370665/oc-commands.txt)
![Screenshot from 2020-10-13 18-15-58](https://user-images.githubusercontent.com/64659/95848654-eb531e00-0d80-11eb-93ca-fc8602ffdaaa.png)

**Comment by praveenkumar** [comment]
As per `oc-commands` I can see that the all the operator sources are succeed, sometime on the web console side it take some time to show it. Did you wait for around 2-3 mins and refresh the web console?

**Comment by rhui** [comment]
Hi Praveen, 
Yea, I have waited for more than that, and even using a different browser and clear cookies.. 

In my CRC -> OperatorHub -> Side bar I only see  
Provider Type
Certified(140)
Marketplace(81)

In another instance (quicklab) -> I see 
Provider Type
Red Hat(50)
Certified(140)
Community(130)
Marketplace(81)

I wonder if there are some authentication or flags that I need to enable.. 

Thanks, 
Roger

**Comment by rhui** [comment]
Hi Praveen, 

I figured it out.. 

oc logs pod/packageserver-7b8f7b49d4-hhr47 -n openshift-operator-lifecycle-manager|grep -i community

time="2020-10-13T10:04:19Z" level=warning msg="error getting stream" action="refresh cache" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 172.25.45.12:50051: connect: connection timed out\"" source="{community-operators openshift-marketplace}"

oc get pods -n openshift-marketplace
I saw the community-operators and redhat-operators pods unable to connect to quay and restart many times. 

I just delete the community-operators and redhat-operators pods and it pull the service, I now have all the operators in the operatorhub page.

**Comment by rhui** [comment]
I dig deeper to my own issue.. I find out that quay is slow and it takes longer to pull all the project down, the LivenessProbe and Readiness Probe is too short. Increasing that helps. 

deployment.apps/community-operators
