### ISSUE TITLE
[Epic] Native installers

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#16]
Installers for platforms to handle the setup and integration with the target platform.

- [x] Windows (https://github.com/code-ready/crc/issues/1516)
- [x] macOS (https://github.com/code-ready/crc/issues/1516)
- [ ] ~~Linux~~

**Comment by gbraad** [comment]
Needs to be reviewed ...

**Comment by gbraad** [comment]
As part of the Windows MSI we will deal with the signing of the binaries. Before this it will be of little value as the SmartScreen error ONYL shows when the executable is clicked on in the explorer; this is not the usage we normally see as `crc.exe` is a CLI-only tool

**Comment by guillaumerose** [comment]
Windows MSI will be ready in 1.29.0.
