### ISSUE TITLE
New or update user does not work until restart crc

### ISSUE THREAD

**Issue by mabayhan** [code-ready/crc#1615]
### General information

  * OS: Linux
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
CodeReady Containers version: 1.17.0+99f5c87
OpenShift version: 4.5.14 (embedded in binary)
```
  
## CRC status
```bash
CRC VM:          Running
OpenShift:       Running (v4.5.14)
Disk Usage:      21.24GB of 32.72GB (Inside the CRC VM)
Cache Usage:     13.04GB
Cache Directory: /home/mali/.crc/cache
```

## CRC config
```bash
- cpus                                  : 5
- memory                                : 16384
```

## Host Operating System
```bash
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
```

### Steps to reproduce

  1. Export Users 
```bash
oc get secret htpass-secret -ojsonpath={.data.htpasswd} -n openshift-config | base64 -d > users.htpasswd
````
  2. Add new user
```bash
htpasswd -bB users.htpasswd user_name p@ssw0rd
````
  3. Replace
```bash
oc create secret generic htpass-secret --from-file=htpasswd=users.htpasswd --dry-run -o yaml -n openshift-config | oc replace -f -
```
  4. Test Login

### Expected

Login to Web UI

### Actual

Username/password error,
Need to ```crc stop``` and ```crc start``` to be able to login with new username and password

### Logs

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by gbraad** [comment]
> Username/password error,
> Need to crc stop and crc start to be able to login with new username and password

My understanding is that this is not related to CRC, but how OpenShift deals with these credentials. You would likely need to restart the pod of the authentication provider. However, does this work as expected on another deployed cluster?

**Comment by gbraad** [comment]
@praveenkumar notes about this do not mention a needed reboot or restart of the cluster

**Comment by cfergeau** [comment]
If you try with `oc login -u user_name`, does it succeed? or same issues as with the web console?

**Comment by mabayhan** [comment]
Actually @cfergeau after doing that, I was able to login using web console. I assume, after adding user, I need to login using cli first.
