### ISSUE TITLE
[BUG] Cannot login as developer user / no provider selection at console

### ISSUE THREAD

**Issue by eburgueno** [code-ready/crc#1617]
### General information

  * OS: Linux
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop

## CRC version
```bash
CodeReady Containers version: 1.16.0+004e857
OpenShift version: 4.5.0-0.okd-2020-10-15-235428 (embedded in binary)
```
  
## CRC status
```bash
DEBU CodeReady Containers version: 1.16.0+004e857 
DEBU OpenShift version: 4.5.0-0.okd-2020-10-15-235428 (embedded in binary) 
DEBU About to run SSH command with hidden output  
DEBU SSH command succeeded                        
DEBU openshift-samples operator is degraded, Reason: FailedImageImports 
DEBU openshift-samples operator is still progressing, Reason:  
DEBU About to run SSH command:
df -B1 --output=size,used,target /sysroot | tail -1 
DEBU SSH command results: err: <nil>, output: 32737570816 14978863104 /sysroot 
CRC VM:          Running
OpenShift:       Running (v4.5.0-0.okd-2020-10-15-235428)
Disk Usage:      14.98GB of 32.74GB (Inside the CRC VM)
Cache Usage:     12.47GB
Cache Directory: /home/nevermind/.crc/cache
```

## CRC config
```bash
<no output>
```

## Host Operating System
```bash
NAME=Fedora
VERSION="32 (Workstation Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

### Steps to reproduce

  1. wget https://dl.fedoraproject.org/pub/alt/okd-crc/linux-amd64/crc; chmod +x crc
  2. ./crc setup
  3. ./crc start
  4. ./crc console
  5. eval $(./crc oc-env)
  6. oc login -u developer -p developer https://api.crc.testing:6443

### Expected
* `Login successful.` for the `oc` command
* A provider selection list on my browser

### Actual
```bash
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

Login failed (401 Unauthorized)
Verify you have provided correct credentials.
```
* No provider selection on my browser, just the login page (developer doesn't work there either).

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```
Tried these but the issue persists. I don't see anything relevant in the debug logs and I'm a bit reluctant of posting them in full.

```bash
Started the OpenShift cluster

To access the cluster, first set up your environment by following 'crc oc-env' instructions.
Then you can access it by running 'oc login -u developer -p developer https://api.crc.testing:6443'.
To login as an admin, run 'oc login -u kubeadmin -p <redacted> https://api.crc.testing:6443'.
To access the cluster, first set up your environment by following 'crc oc-env' instructions.

You can now run 'crc console' and use these credentials to access the OpenShift web console.

$ oc login -u developer -p developer https://api.crc.testing:6443
Login failed (401 Unauthorized)
Verify you have provided correct credentials.

$ oc login -u kubeadmin -p <redacted> https://api.crc.testing:6443
Login successful.

You have access to 57 projects, the list has been suppressed. You can list all projects with 'oc projects'

Using project "default".
```

**Comment by cgruver** [comment]
This looks like a potential issue with the OKD build.

As a work around, you can use the kubeadmin account to create your own htpasswd provider.  This might even be something that we should implement in crc and remove the kubeadmin account altogether.

```bash
mkdir -p okd-creds
htpasswd -B -c -b ./okd-creds/htpasswd admin admin
htpasswd -b ./okd-creds/htpasswd developer developer
oc create -n openshift-config secret generic htpasswd-secret --from-file=htpasswd=./okd-creds/htpasswd

cat << EOF > ./okd-creds/htpasswd-cr.yaml
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: okd4_htpasswd_idp
    mappingMethod: claim 
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpasswd-secret
EOF

oc create -f  ./okd-creds/htpasswd-cr.yaml
oc adm policy add-cluster-role-to-user cluster-admin admin
```

If you want to remove the temporary kubeadmin account:

```bash
oc delete secrets kubeadmin -n kube-system
```

That will delete the temporary account and just leave the htpasswd provider.

**Comment by cgruver** [comment]
htpasswd was missing from the build server.  I will push a new crc for OKD build to resolve.

**Comment by cgruver** [comment]
This should be resolved with the latest crc upload.  Please try again.

**Comment by eburgueno** [comment]
@cgruver thanks. I just downloaded the latest release and will try again.

By the way, not sure if this should be reported here, but the [OKD site](https://www.okd.io/crc.html) is pointing to a different download location than [the one mentioned in the docs](https://cloud.redhat.com/openshift/install/crc/installer-provisioned). When I download the one in the OKD site I get the same (older) version as originally reported:

```
$ wget https://dl.fedoraproject.org/pub/alt/okd-crc/linux-amd64/crc
$ chmod +x crc 
$ ./crc version
CodeReady Containers version: 1.16.0+004e857
OpenShift version: 4.5.0-0.okd-2020-10-15-235428 (embedded in binary)
```
vs
```
$ wget 'https://mirror.openshift.com/pub/openshift-v4/clients/crc/latest/crc-linux-amd64.tar.xz?extIdCarryOver=true&sc_cid=701f2000001Css5AAC'
$ ./crc version
CodeReady Containers version: 1.17.0+99f5c87
OpenShift version: 4.5.14 (embedded in binary)

```

**Comment by eburgueno** [comment]
I can confirm that the latest release `1.17.0+99f5c87` works as documented. Thank you!

**Comment by cgruver** [comment]
@eburgueno The OKD CRC version is reflective of the OKD build, not the CRC build.  That's why the version did not change.  It is a new binary, however.  Not ideal, but that's how it labels the version...

The OKD build of CRC is hosted by our friends at Fedora.  They were kind enough to lend us some space.

Apologies for the issue with the OKD version.  There was a problem, now resolved, with the build server.

**Comment by eburgueno** [comment]
Understood. No need to apologise, glad it was (seemingly) easy to fix! Happy to close this one.
