### ISSUE TITLE
[macOS] Possibility to configure the CIDR of the hyperkit bridge

### ISSUE THREAD

**Issue by devops-42** [code-ready/crc#1618]
### General information

  * OS: macOS
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it: Yes

## CRC version
```bash
CodeReady Containers version: 1.17.0+99f5c87
OpenShift version: 4.5.14 (embedded in binary)
```
  
This issue is more like a feature request.

When starting CRC on macOS the hyperkit builds a bridge network with the host network. This bridge network has a static configured CIDR. This may cause routing clashes in various network environments where this CIDR is already defined.

Is it possible by configuration to change the CIDR to a custom one?

Thanks for an answer in advance!

Cheers

**Comment by devops-42** [comment]
Found a manual workaround. It seems that hyperkit takes usage of the file `/Library/Preferences/SystemConfiguration/preferences.plist`. This file includes a section for the hostbridge `bridge100`, where the subnet range can be changed. Additionally, the files `/etc/resolver/testing` and `/etc/hosts` have to be amended to use the new network range.
Maybe this helps for implementing a flag with `crc setup`.

**Comment by guillaumerose** [comment]
With the new userland network stack, this should not be a problem anymore. 

The only remaining conflict that can happen is when a pod within the VM wants to connect to a service on the local network which IP is in the subnet 192.168.127.0/24. See https://github.com/code-ready/crc/issues/2151.
