### ISSUE TITLE
Installing CRC on high-security-envs - if needed, then even manually

### ISSUE THREAD

**Issue by dictyo** [code-ready/crc#1627]
* OS: Win10, Built 1709xxx
* Hypervisor: Hyper-V
* CodeReady Containers version: 1.17.0+99f5c87
OpenShift version: 4.5.14 (embedded in binary)

Hi everybody, 
since all my questions are about installing CRC on high-security-envs I combine them all three here: 

* There are numerous Symantec Endpoint Protection issues, all leading to the same prob at https://github.com/code-ready/crc/blob/71a12decdeb34de228a83bedb91481d4b3fd9e4d/vendor/github.com/code-ready/machine/libmachine/drivers/plugin/localbinary/plugin.go#L244
Can you think of a way to **install CRC without changing / disabling Symantec**?

* Is there some **instruction for (even better: partially) manual installation**? I realise that even if `crc setup/start` fails, it's possible to get everything done doing Hyper-V-initialization and all the config manually. But it is cumbersome to reconstruct installation by following the debug-log of an install in non-secure env and/or crc-sources on github.

* And a final hint/question: to find **goodhost.exe** during a scan on a harddrive is reason enough for some high security envs to shutdown and reset the PC without asking questions. How might the use of goodhosts.exe be avoided for future versions?

Some more info about me and my context:
I'm working for a government agency and since our cloud is based on Openshift4 we want to get CRC up and running on our local Win10-machines. Unfortunately security is quite high and direct communication with Security-department (or to achieve - even temporary - changes) is really hard to get so that our possibilities to get around Symantec Endpoint Protection are nearlly hopeless.  But we still would really like to migrate from Minikube/VirtualBox to CRC/Hyper-V.

Thanks a lot for your thoughts,
Ingo

**Comment by gbraad** [comment]
A soon to release new version of CRC will use a different way of handling the interaction with the Hyper-V driver.

**Comment by gbraad** [comment]
https://github.com/code-ready/machine/pull/47

**Comment by cfergeau** [comment]
>  to find goodhost.exe during a scan on a harddrive is reason enough for some high security envs to shutdown and reset the PC without asking questions. How might the use of goodhosts.exe be avoided for future versions?

Do you know the reason for blacklisting it? Changes to `/etc/hosts` are deemed unsecure/too dangerous?

**Comment by gbraad** [comment]
> Changes to /etc/hosts are deemed unsecure/too dangerous?

they allow to 'redirect' traffic (as in the form of DNS poisoning).

**Comment by dictyo** [comment]
Hi there, I checked the new build. SUCCESSSSSS! Tnx a lot for your changes!
Now the only little thing is to skip goodhost.exe for Win10, to prevent that some poor dev's pc are reset due to a remaining goodhosts.exe in ~/.crc/bin
TNX AGAIN :)

**Comment by cfergeau** [comment]
Do you know what would be a good way of handling creation of new hostnames to access openshift applications on this setup?
When you say you checked the new build, was this the experimental 'vsock' support? Or just the regular networking?
