### ISSUE TITLE
[BUG] - Default Switch does not work

### ISSUE THREAD

**Issue by patrickmcdonogh** [code-ready/crc#1644]
### General information

  * OS: Windows
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Desktop

## CRC version
```bash
# Put `crc version` output here
CodeReady Containers version: 1.18.0+bb304aa
OpenShift version: 4.6.1 (embedded in binary)
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
PS C:\Users\mcdon> crc status --log-level debug
DEBU CodeReady Containers version: 1.18.0+bb304aa
DEBU OpenShift version: 4.6.1 (embedded in binary)
Checking file: C:\Users\mcdon\.crc\machines\crc\.crc-exist
DEBU About to run SSH command with hidden output
DEBU SSH command succeeded
DEBU authentication operator not available, Reason: OAuthRouteCheckEndpointAccessibleController_EndpointUnavailable
DEBU About to run SSH command:
df -B1 --output=size,used,target /sysroot | tail -1
DEBU SSH command results: err: <nil>, output: 32720793600 12286414848 /sysroot
CRC VM:          Running
OpenShift:       Stopped
Disk Usage:      12.29GB of 32.72GB (Inside the CRC VM)
Cache Usage:     33.26GB
Cache Directory: C:\Users\mcdon\.crc\cache

## CRC config
```bash
# Put `crc config view` output here
PS C:\Users\mcdon> crc config view
- memory                                : 14336

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```
PS C:\Users\mcdon> systeminfo

Host Name:                 DESKTOP-FOED9GF
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19042 N/A Build 19042
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          mcdonoghpatrick@gmail.com
Registered Organization:
Product ID:                00330-81494-04672-AA965
Original Install Date:     27/10/2020, 04:37:36
System Boot Time:          04/11/2020, 09:30:59
System Manufacturer:       Micro-Star International Co., Ltd.
System Model:              MS-7C90
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 23 Model 113 Stepping 0 AuthenticAMD ~2240 Mhz
BIOS Version:              American Megatrends Inc. 1.30, 01/09/2020
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-gb;English (United Kingdom)
Input Locale:              en-gb;English (United Kingdom)
Time Zone:                 (UTC+00:00) Dublin, Edinburgh, Lisbon, London
Total Physical Memory:     32,694 MB
Available Physical Memory: 11,799 MB
Virtual Memory: Max Size:  37,558 MB
Virtual Memory: Available: 11,351 MB
Virtual Memory: In Use:    26,207 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-FOED9GF
Hotfix(s):                 6 Hotfix(s) Installed.
                           [01]: KB4580419
                           [02]: KB4562830
                           [03]: KB4570334
                           [04]: KB4577266
                           [05]: KB4580325
                           [06]: KB4579311
Network Card(s):           4 NIC(s) Installed.
                           [01]: Realtek PCIe 2.5GbE Family Controller
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [02]: Intel(R) Wi-Fi 6 AX200 160MHz
                                 Connection Name: WiFi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.23
                                 [02]: fe80::e8ea:22f6:9016:6852
                                 [03]: fdaa:bbcc:ddee:0:6dfe:4b5c:4151:adcf
                                 [04]: fd9b:b517:6f48:1:6dfe:4b5c:4151:adcf
                                 [05]: fdaa:bbcc:ddee:0:e8ea:22f6:9016:6852
                                 [06]: fd9b:b517:6f48:1:e8ea:22f6:9016:6852
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [04]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (Default Switch)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 192.168.32.1
                                 [02]: fe80::8d1d:f8ce:832c:dcf
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

### Steps to reproduce

  1.  crc config set memory 14336
  2.  crc setup
  3.  crc start -p C:\Utilities\OpenShift\crc-windows-1.18.0-amd64\pull-secret -m 14336
  4. Try one of the samples like nginx or any other. The images always fail to get pulled and built.

### Expected
Expected the sample to work. I.e. images pulled and built.

### Actual
Images dont get pulled.

I am working on a machine with wifi access only.

I noticed that i can get this to work if i do the following:
1. Delete the cluster
2. Create an external virtual switch in hyper-v
![image](https://user-images.githubusercontent.com/26539941/98100096-4f509a00-1e88-11eb-878f-6fc4c3e27e61.png)
3. Run crc setup
4. Run crc start

What is the best way to get this to work? Would you expect that i need to create another switch so the default is not used?

**Comment by gbraad** [comment]
This might be related to the machine setup. The default switch should do NAT and forwarding, but has been observed to fail at times. This might be due to the use of Windows Containers (as in some rel;eases it modified the network stack), or there are other tools installed or just a fluke? Anyways, if an alternative switch works, perhaps this is the best way forward for your setup. This is also why we added the option with the crc-named override switch.

**Comment by patrickmcdonogh** [comment]
Thanks for the reply.

**Comment by patrickmcdonogh** [comment]
By the way I just noticed some images pull and others do not.

For instance i just tried the node.js sample.

![image](https://user-images.githubusercontent.com/26539941/98103340-cab44a80-1e8c-11eb-91f6-90abe2c21e23.png)

**Comment by gbraad** [comment]
It might be helpful to check the logs. It might be a time out for a specific registry or outdated info?

Which did you try and failed?

**Comment by patrickmcdonogh** [comment]
Hi.
I have found a strange issue now. When i run
crc stop
and shut down the VM my computer no longer connects to the internet
I have to start the VM using crc start to get the internet working again on my machine
Its like all traffic is divered through the crc VM. Is that correct?

**Comment by patrickmcdonogh** [comment]
Are there any logs or screen shots that would help you? If so just let me know where they are and i will send them.

**Comment by gbraad** [comment]
This is due to the DNS records we might set. This is recorded in the Known Issue and can be resolved by removing the entries from the Default Switch; set-DNSClientServerAddress. Likely there is an unexpected metric that causes this behaviour.

also, the crc cleanup command could help, but it removes maybe more than necessary

**Comment by gbraad** [comment]
https://github.com/code-ready/crc/issues/1352#issuecomment-652499670

**Comment by gbraad** [comment]
```
PS> Set-DNSClientServerAddress "vEthernet (Default Switch)" -ResetServerAddresses
```
