### ISSUE TITLE
[BUG] Could not open '/home/localadmin/.crc/cache/crc_libvirt_4.5.14/crc.qcow2': Permission denied

### ISSUE THREAD

**Issue by tpdanh** [code-ready/crc#1649]
### General information

  * OS: Linux  - Ubuntu 
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
  * Hypervisor: KVM 
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on:  VM

## CRC version
```bash
# Put `crc version` output here
```
CodeReady Containers version: 1.17.0+99f5c87
OpenShift version: 4.5.14 (embedded in binary)
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
```
DEBU CodeReady Containers version: 1.17.0+99f5c87 
DEBU OpenShift version: 4.5.14 (embedded in binary) 
CRC VM:          Stopped
OpenShift:       Stopped
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     13.04GB
Cache Directory: /home/localadmin/.crc/cache

## CRC config
```bash
# Put `crc config view` output here
```
No output

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```

### Steps to reproduce

  1. crc setup
  2. crc start -p ./pull-secret.txt --log-level debug
  3. 
  4. 

### Expected
crc start

### Actual
$ crc start -p ./pull-secret.txt --log-level debug
DEBU CodeReady Containers version: 1.17.0+99f5c87 
DEBU OpenShift version: 4.5.14 (embedded in binary) 
DEBU Total memory of system is 135194472448 bytes 
WARN A new version (1.18.0) has been published on https://cloud.redhat.com/openshift/install/crc/installer-provisioned 
INFO Checking if oc binary is cached              
DEBU Running '/home/localadmin/.crc/bin/oc/oc version --client' 
DEBU Found oc version 4.5.14                      
DEBU oc binary already cached                     
INFO Checking if podman remote binary is cached   
DEBU Currently podman remote is not supported     
INFO Checking if goodhosts binary is cached       
DEBU goodhost binary already cached               
INFO Checking minimum RAM requirements            
DEBU Total memory of system is 135194472448 bytes 
INFO Checking if running as non-root              
INFO Checking if Virtualization is enabled        
DEBU Checking if the vmx/svm flags are present in /proc/cpuinfo 
DEBU CPU virtualization flags are good            
INFO Checking if KVM is enabled                   
DEBU Checking if /dev/kvm exists                  
DEBU /dev/kvm was found                           
INFO Checking if libvirt is installed             
DEBU Checking if 'virsh' is available             
DEBU 'virsh' was found in /usr/bin/virsh          
INFO Checking if user is part of libvirt group    
DEBU Checking if current user is part of the libvirt group 
DEBU Running '/usr/bin/groups localadmin'         
DEBU Current user is already in the libvirt group 
INFO Checking if libvirt daemon is running        
DEBU Checking if libvirtd service is running      
DEBU Running 'systemctl status virtqemud.socket'  
DEBU Command failed: exit status 4                
DEBU stdout:                                      
DEBU stderr: Unit virtqemud.socket could not be found. 
DEBU virtqemud.socket is not running              
DEBU Running 'systemctl status libvirtd.socket'   
DEBU Command failed: exit status 4                
DEBU stdout:                                      
DEBU stderr: Unit libvirtd.socket could not be found. 
DEBU libvirtd.socket is not running               
DEBU Running 'systemctl status virtqemud.service' 
DEBU Command failed: exit status 4                
DEBU stdout:                                      
DEBU stderr: Unit virtqemud.service could not be found. 
DEBU virtqemud.service is not running             
DEBU Running 'systemctl status libvirtd.service'  
DEBU libvirtd.service is running                  
INFO Checking if a supported libvirt version is installed 
DEBU Checking if libvirt version is >=3.4.0       
DEBU Running 'virsh -v'                           
INFO Checking if crc-driver-libvirt is installed  
DEBU Checking if crc-driver-libvirt is installed  
DEBU Running '/home/localadmin/.crc/bin/crc-driver-libvirt version' 
DEBU Found crc-driver-libvirt version 0.12.10     
DEBU crc-driver-libvirt is already installed      
INFO Checking if libvirt 'crc' network is available 
DEBU Checking if libvirt 'crc' network exists     
DEBU Running 'virsh --connect qemu:///system net-info crc' 
DEBU Checking if libvirt 'crc' definition is up to date 
DEBU Running 'virsh --connect qemu:///system net-dumpxml --inactive crc' 
DEBU libvirt 'crc' network has the expected value 
INFO Checking if libvirt 'crc' network is active  
DEBU Checking if libvirt 'crc' network is active  
DEBU Running 'virsh --connect qemu:///system net-info crc' 
DEBU libvirt 'crc' network is already active      
INFO Checking if NetworkManager is installed      
DEBU Checking if 'nmcli' is available             
DEBU 'nmcli' was found in /usr/bin/nmcli          
INFO Checking if NetworkManager service is running 
DEBU Checking if NetworkManager.service is running 
DEBU Running 'systemctl status NetworkManager'    
DEBU NetworkManager.service is already running    
INFO Checking if /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf exists 
DEBU Checking NetworkManager configuration        
DEBU NetworkManager configuration is good         
INFO Checking if /etc/NetworkManager/dnsmasq.d/crc.conf exists 
DEBU Checking dnsmasq configuration               
DEBU dnsmasq configuration is good                
INFO Loading bundle: crc_libvirt_4.5.14.crcbundle ... 
INFO Checking size of the disk image /home/localadmin/.crc/cache/crc_libvirt_4.5.14/crc.qcow2 ... 
INFO Creating CodeReady Containers VM for OpenShift 4.5.14... 
ERRO Error creating machine: Error creating the VM: Error creating machine: Error in driver during machine creation: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2020-11-06T18:46:51.523213Z qemu-system-x86_64: -drive file=/home/localadmin/.crc/machines/crc/crc.qcow2,format=qcow2,if=none,id=drive-virtio-disk0,aio=threads: Could not open backing file: Could not open '/home/localadmin/.crc/cache/crc_libvirt_4.5.14/crc.qcow2': Permission denied') 
Error creating machine: Error creating the VM: Error creating machine: Error in driver during machine creation: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2020-11-06T18:46:51.523213Z qemu-system-x86_64: -drive file=/home/localadmin/.crc/machines/crc/crc.qcow2,format=qcow2,if=none,id=drive-virtio-disk0,aio=threads: Could not open backing file: Could not open '/home/localadmin/.crc/cache/crc_libvirt_4.5.14/crc.qcow2': Permission denied')

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.
Llink to the file here: https://gist.github.com/tpdanh/03345cc3bb6cbe4dc6a7f9feb3f38e5f

**Comment by timroster** [comment]
Also observing on latest: 1.18.0-4.6.1 with Ubuntu 18.04.5 LTS

**Comment by guillaumerose** [comment]
Yes it is known. Please take a look at https://github.com/code-ready/crc/issues/1578

A fix should land in the next release for this.
