### ISSUE TITLE
How can I set single hostname (it's mapping to IP address) in OpenShift?

### ISSUE THREAD

**Issue by JiriHusak-lab** [code-ready/crc#1654]
Current issue:  I've to deploy applications using oc new-app from private gitlab repo using gitlab IP address, I can't use hostname.
Using IP address oc new-app  (oc new-app git@X.X.X.X:user/reponame.git    ... ) works properly, application is built and deployed successfully. 

I've configured gitlab server into /etc/hosts on host RHEL server and in the CRC VM CoreOS /etc/hosts as well. I've stop and start CRC. 
Now, I can run oc new-app command with gitlab hostname to deploy from gitlab as RHEL server, where I run oc commands knows gitlab hostname (it is in /etc/hosts) but build itself ends with error "Could not resolve hostname "mygitlab" : Name or service not known". 
So my question is how can I configure single hostname for OpenShift.
I'm aware off DNS Operator but here as I understand  I configure DNS nameserver, right? Not translation of hostname to IP.

May I ask you for any hint, where I need to configure my private gitlab IP? It's not a big issue, I can deploy application using IP address but I'm really curious how to configure hostname in OpenShift. I've spent lot of time trying to google that.

**Comment by cfergeau** [comment]
To be sure I understand correctly, this private IP is not mapped to a hostname in the DNS server you are using? Which is why you need to add it to `/etc/hosts`? Not sure how you can add custom DNS or /etc/hosts entries to your cluster :-/

**Comment by JiriHusak-lab** [comment]
Ok, so it is not supported way to add individual entries for mapping hostname to IP to Openshift. Like /etc/hosts configuration. So only way is to have this entries in DNS server OpenSHift is connected to, right?
Thanks

**Comment by gbraad** [comment]
> DNS server OpenSHift is connected to

You are able to host your own nameserver, and use the `crc start -n [nameserver]` option to override. though this is not a usecase we test
