### ISSUE TITLE
Setting disk size with --disk-size not yet implemented on libvirt

### ISSUE THREAD

**Issue by hippyod** [code-ready/crc#1660]
TL;DR: CRC 1.18 `crc --disk-size <unit>` doesn't work.  Workaround:

```
crc start
crc stop
qemu-img resize ${HOME}/.crc/machines/crc/crc.qcow2 +100G
sed -i 's/"DiskCapacity": 33285996544,/"DiskCapacity": 140660178944,/' ${HOME}/.crc/machines/crc/config.json
crc start
```

Tested on Fedora 33, CRC version 1.18

I have been using the `qemu-img` start/stop/qemu-img/start/xfs_growfs hack to change the VM's disk size for months now.  You recently changed something internally in this version that added the fabulous `--disk-size` flag, but it doesn't work, and neither does setting the value using `crc config`.  As of CRC 1.18 the `qemu-img` hack is broken, too,  because resizing the disk now checks against expected size, which is what the `sed` command works around from above.

**Comment by gbraad** [comment]
Not sure when you experienced this,  but disk size does not work on initial start yet. This is being resolved.

Also, resizing the disk needs you to grow the internal partition, right?

**Comment by gbraad** [comment]
https://github.com/code-ready/machine-driver-libvirt/pull/73

**Comment by hippyod** [comment]
I was fighting with this yesterday when I ran into the problem.  I downloaded CRC from Red Hat last week (11/4), but didn't get to it and notice the issue until yesterday.

The small script I posted above is first startup of the VM.  Yes, obviously using `libvritd`.

Issue template?

One last thing: the only reason I am even troubling all you all about this issue is in earlier versions of CRC, even though enlarging the disk was not straightforward, it did follow basic VM image management.  In this version, you have to dig into and screw around with undocumented CRC configuration files and debug logging info to get it to work.

Anyways, thanks for the quick reply, and thanks for all you all do.  Love CRC.

**Comment by cfergeau** [comment]
Regarding the title, it's only on hyperkit that `--disk-size` is not yet implemented, it is implemented with libvirt.

There is one known issue with disk resize, which is that it's not resized on initial start (when the VM is created), but only on 2nd start and later. Maybe this is what you are seeing. This 'initial start' issue will be addressed for next release. If you want to keep using the hacks you used in the past, just pass a `--disk-size` parameter bigger than the size of your hacked image.

**Comment by cfergeau** [comment]
Initial issue should be fixed by https://github.com/code-ready/crc/commit/0a4646abf17823ef16126581ff25cf661cb3b9b3 I think. And manual resizing can still be done as long as an appropriate disk size is passed to `crc start`. So I think this can be closed?
