### ISSUE TITLE
Running crc daemon on macOS prompts `Do you want the application to accept incoming network connections?`

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#1667]
### General information

  * OS: macOS
  * Hypervisor: hyperkit
```bash
>= 1.19.0
```

### Behaviour

When running `crc daemon`, macOS will open a dialog window asking the user accept incoming network connections.

This also affects people running `crc setup --enable-experimental-features` because the vsock host side code is launched in the daemon.

This will be fixed when crc will be correctly signed.

**Comment by cfergeau** [comment]
Duplicate of https://github.com/code-ready/crc/issues/836 ?

**Comment by gbraad** [comment]
this is as expected, unless we probably use entitlements
