### ISSUE TITLE
[BUG] Console in webbrowser loading POD more then 1 minute, CLI works ok 

### ISSUE THREAD

**Issue by arturobrzut** [code-ready/crc#1673]
### General information

  * OS: Linux Red Hat Enterprise Linux 8.2 (Ootpa)
  * Hypervisor: KVM / Hyper-V / hyperkit
  * Did you run `crc setup` before starting it YES

## CRC version
```
 ./crc version
CodeReady Containers version: 1.18.0+bb304aa
OpenShift version: 4.6.1 (embedded in binary)
```
  
## CRC status
```
❯ crc status
CRC VM:          Running
OpenShift:       Running (v4.6.1)
Disk Usage:      13.49GB of 32.72GB (Inside the CRC VM)
Cache Usage:     36.07GB
Cache Directory: /home/aobrzut/.crc/cache
```

## CRC config
```bash
❯ crc config view
```

## Host Operating System
```bash
 cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.2"
```

### Steps to reproduce

  1. crc start
  2. crc console
  3. start console in chrome webbrowser
  4. and now wait for display pod in namespace where there is not any POD 

### Expected
POD should be display in e.g. 5s

### Actual
POD is display after 2-3minutes

### Logs
crc start with debug
https://gist.github.com/arturobrzut/e48c7ab56596e4047b9830f7daa7ea3b

I found that the longest get in webbrowser in such case is 
Request URL: https://console-openshift-console.apps-crc.testing/api/prometheus/api/v1/rules
Request Method: GET
Status Code: 502 Bad Gateway
30s Waiting TTFB

and 
Request URL: https://console-openshift-console.apps-crc.testing/api/alertmanager/api/v2/silences
Request Method: GET
Status Code: 502 Bad Gateway
30s Waiting TTFB

Rest of Requests are ok , and with good timing [in ms]

At Second refresh page
the same situation with Bad Gateway, but time is better
Request URL: https://console-openshift-console.apps-crc.testing/api/prometheus/api/v1/rules
Request Method: GET
Status Code: 502 Bad Gateway
1s Waiting TTFB

**Comment by arturobrzut** [comment]
I found also that e..g on page with machines
https://console-openshift-console.apps-crc.testing/k8s/all-namespaces/machine.openshift.io~v1beta1~Machine

I also long wait for display this page 
and the same thing happens
and also get version takes long 

Request URL: https://console-openshift-console.apps-crc.testing/api/kubernetes/apis/config.openshift.io/v1/clusterversions/version
Request Method: GET
Status Code: 200 OK
Remote Address: 192.168.130.11:443
Referrer Policy: strict-origin-when-cross-origin

Timming:
Stalled: 28s
Full Reuqest : 29s

**Comment by cfergeau** [comment]
Can you describe what you tried on the CLI? I only see the issue title saying "CLI works ok", but I can't find details abouto what you tried on the CLI in the issue

**Comment by cfergeau** [comment]
In case it matters for this issue, https://github.com/code-ready/crc/issues/1663#issuecomment-727201187 has some details about the DNS setup

**Comment by arturobrzut** [comment]
CLI works ok means that it works fast
e.g. display all pods takes 0.1s
oc get pods --all-namespaces  0.23s user 0.10s system 41% cpu 0.793 total

but sometimes, mostly after crc start to display all pods in UI (console ) takes more then 1minutes 
(The problem is not only with PODs , but also with other resource, but I put POD as an example)

Mostly because of some resource return 502 Bad Gateway (e.g. rules, silense)
and if I run at the same time CLI it returns e.g. pods less then 1s

**Comment by arturobrzut** [comment]
After a while, e.g. 5min, the data are displayed fast (without delay on rules)
rules and silense do not return 502 Bad Gateway

**Comment by arturobrzut** [comment]
log from Console - from machines URL 
https://gist.github.com/arturobrzut/2980ebaee6ea5ab91fe03ad2b66b517b

and har file
https://gist.github.com/arturobrzut/5747181cf01a370230330ecf0137bd91

**Comment by arturobrzut** [comment]
I can confirm that this problem is most probably because of disabling Prometheus
If I enabled it (on 4.5.X) UI works ok, (fast)
