### ISSUE TITLE
Add single node cluster profile annotation to all OpenShift manifests

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#1680]
CVO will then be able to only pick these manifests. 

It is expected to open ~40 PRs. Examples can be found in each openshift repo by looking at PR opened either by Cesar or @guillaumerose.

**Comment by cfergeau** [comment]
This one is almost done, only a few PRs are still pending, see https://bugzilla.redhat.com/show_bug.cgi?id=1915473
