### ISSUE TITLE
Create a CI job to run OpenShift conformance tests against crc

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#1683]
After discussing with OpenShift folks, we conclued that we can call anything OpenShift if conformance tests are passing.

CRC needs to pass all conformance tests. Cluster profile will help fixing failing tests.

**Comment by praveenkumar** [comment]
Closing this in favor of https://github.com/code-ready/crc/issues/2457 and CI job currently running k8s conformance tests.
