### ISSUE TITLE
DNS records and port forwarding are hardcoded for vsock network mode

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#1685]
Routes created by the user cannot be reached from the host. DNS records are missing. Ports may also be closed (if it is not one that we open by default).

Currently after `crc start`, crc adds default dns records in hosts file with goodhost. 

A demo of a route controller that keep hosts file up to date can be found here: https://github.com/code-ready/crc/pull/1537
The main issue of this PR is that kubeconfig doesn't always exist. The controller should only run when it is present. Port exposure is not solved in this PR.

**Comment by gbraad** [comment]
I see the observed, but not what is expected.

>  that keep hosts file up to date 

keep up to date with which expected records? You mean the routes to an application?

> Ports may also be closed

Which ports are you refering to?

**Comment by guillaumerose** [comment]
A route contains both a dns name and a port.

TODO:
* Create a hosts file entry for each OpenShift route
* Open the required port for each OpenShift route

**Comment by guillaumerose** [comment]
DNS records are now created automatically. 
Port forwarding is apparently not needed. 80 and 443 are enough. Maybe I am wrong here. Let see how it goes in the next release.
