### ISSUE TITLE
[BUG] crc start on macos loops, failing on ssh command

### ISSUE THREAD

**Issue by chris-giblin** [code-ready/crc#1688]
### General information

  * OS: macOS 
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop

## CRC version
```bash
$ crc version
CodeReady Containers version: 1.12.0+6710aff
OpenShift version: 4.4.8 (embedded in binary)
```
  
## CRC status
```bash
$ crc status
CRC VM:          Stopped
OpenShift:       Stopped
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     12.43GB
Cache Directory: /Users/cgi/.crc/cache
```

## CRC config
```bash
# Put `crc config view` output here
```

## Host Operating System
```bash
$ sw_vers
ProductName:	macOS
ProductVersion:	11.0.1
BuildVersion:	20B29
```

### Steps to reproduce

  1.  crc delete -f
  2.  crc cleanup
  3.  rm -fr ~/.crc
  4. crc setup 
  5. crc start -p pull-secret  --log-level=debug 

### Expected
Functioning crc

### Actual
Loops, unable to connect ssh

```
Machine is up and running!
Machine successfully created
Created /Users/cgi/.crc/machines/crc/.crc-exist
(crc) Calling .GetState
(crc) DBG | exe=/Users/cgi/.crc/bin/crc-driver-hyperkit uid=0
(crc) DBG | hyperkit pid from json: 27340
Found binary path at /Users/cgi/.crc/bin/crc-driver-hyperkit
Launching plugin server for driver hyperkit
Plugin server listening at address 127.0.0.1:51773

<snip>

Using SSH private key: /Users/cgi/.crc/cache/crc_hyperkit_4.4.8/id_rsa_crc (-r--------)
&{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null core@192.168.64.2 -o IdentitiesOnly=yes -i /Users/cgi/.crc/cache/crc_hyperkit_4.4.8/id_rsa_crc -p 22] /usr/bin/ssh <nil>}
DEBU About to run SSH command:
exit 0             
DEBU SSH command results: err: exit status 255, output:  
DEBU error: Temporary Error: ssh command error:
command : exit 0
err     : exit status 255
output  :  - sleeping 1s 
DEBU retry loop 1                                 
```

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```
I did all that

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

crc start stdout:
https://gist.github.com/chris-giblin/94a371de0055599dc81b29f12b286ca9

crc.log:
https://gist.github.com/chris-giblin/5d4463c7f85de821ec91de4b81a7e0f7

**Comment by praveenkumar** [comment]
@chris-giblin looks like you are using a very old version of CRC and there are lot of fixes went in for latest version. This issue looks similar to https://github.com/code-ready/crc/issues/1555 one but it was due to nested virt. Can you please upgrade to latest version of CRC and then try again?

**Comment by gbraad** [comment]
It might also help to explain more about the system this is setup on; additionnal tools installed, like VPN, Antivirus, network tools, etc.

**Comment by chris-giblin** [comment]
No VPN. I became very aware of the problems with VPNs from reading the related issues.

**Comment by chris-giblin** [comment]
@praveenkumar that is the version for MacOS which is available at:
https://cloud.redhat.com/openshift/install/crc/installer-provisioned 

I removed crc, re-downloaded, installed. The version is always the same. I also followed the upgrade steps at:
https://access.redhat.com/documentation/en-us/red_hat_codeready_containers/1.9/html/getting_started_guide/installation_gsg#upgrading-codeready-containers_gsg

No matter what I do, the version is always:
```
$ crc version
CodeReady Containers version: 1.12.0+6710aff
OpenShift version: 4.4.8 (embedded in binary)

```

**Comment by cfergeau** [comment]
> @praveenkumar that is the version for MacOS which is available at:
> https://cloud.redhat.com/openshift/install/crc/installer-provisioned

Following that link and downloading a macos crc version gives me 1.18.0, which has OpenShift 4.6.1. Beware that the filename is always the same regardless of the version (crc-macos-am64.tar.xz), so it's easy to make mistakes and not use the latest one.

**Comment by chris-giblin** [comment]
@praveenkumar thanks for the prompt responses btw!
Could it be  the site implements a version-sensitive download? I recently upgraded to MacOS Big Sur.

**Comment by chris-giblin** [comment]
@praveenkumar you were right - I had an old version hiding in /usr/local/bin.
I now get :
```
$ crc version
CodeReady Containers version: 1.18.0+bb304aa
OpenShift version: 4.6.1 (embedded in binary)

I am now getting a different error. Will work on that ...
Thanks so far!
```

**Comment by chris-giblin** [comment]
I have it up and running!
Thanks @praveenkumar  !
