### ISSUE TITLE
Integration: time does not sync after cert rotation feature

### ISSUE THREAD

**Issue by jsliacan** [code-ready/crc#1690]
### General information

  * OS: Linux
  * Hypervisor: KVM

### Steps to reproduce

  1. `sudo timedatectl set-ntp no`
  2. `sudo date -s '3 month'`
  3. `sudo timedatectl set-ntp yes`
  4. `timedatectl` now most likely still lists the time as 3 months ahead (not synced). Sometimes it takes 1s to sync, sometimes it takes too long and causes issues elsewhere. 

### Suggestion
Run `sudo timedatectl set-ntp yes` one more time after step 3. This forces the sync right away. WDYT? See what I mean: https://asciinema.org/a/2G5US7ADsbF7lqB5V4CqFtJhr

**Comment by cfergeau** [comment]
> Run sudo timedatectl set-ntp yes one more time after step 3. This forces the sync right away.

This does not seem to be documented though? `sudo date -s '-3 months'` may help as step 3.5? (no idea if the syntax is valid)

**Comment by jsliacan** [comment]
Agree, it's not documented - I was just trying things because I literally cannot run that feature on my machine as it is. Sync is supposed to happen after `sudo timedatectl set-ntp yes` according to the docs, but for some reason it sometimes takes hours (I never waited longer, just interfered afterwards). 

You think `-3 months` might work because it puts the clock back to within 1 day of true time and then sync might pick it up? Or?

**Comment by cfergeau** [comment]
Before the test, you moved the clock exactly 3 months ahead, while the test was running, the clock kept ticking, so if you move it 3 months back, it should end up very close too the current time?
If you are sure you are running on a platform which uses chrony, various other options could be viable: `chronyc makestep`, or `chronyd -q`

**Comment by jsliacan** [comment]
> it should end up very close too the current time

Yes, but not the "correct" time. Seems irresponsible to pretend to clean up but not do it well :). Worse than not clean up?

I am using chrony on my laptop, but apparently `timedatectl` outsources the job to either `ntp` (older and slower to sync) or `chrony` which is on my F32. So I suppose we should have a solution which works for anything under the hood of `timedatectl`. 

To be fair, I'm surprised this is not more straightforward... Can't find online discussions why `set-ntp yes` does not take effect right away... Seems like the delay is not a feature!

**Comment by cfergeau** [comment]
> > it should end up very close too the current time
> 
> Yes, but not the "correct" time. Seems irresponsible to pretend to clean up but not do it well :). Worse than not clean up?

Why not the 'correct' time? Apart from clock drift while ntp was off, and potentially some (microsecond?) delays between reading the date and setting it, I don't think the time would be that incorrect? My feeling is that we are talking about a few seconds at most, which will be easily fixed through ntp. 


> To be fair, I'm surprised this is not more straightforward... Can't find online discussions why `set-ntp yes` does not take effect right away... Seems like the delay is not a feature!

One of NTP's goal is to avoid sudden clock jumps, it speeds up/slow down the clock frequency to adjust the time (ie one second lasts a bit longer, or is a bit shorter). When there is a huge discrepancy between the actual time and the time which is set, some implementations give up. If they don't give up, it's not surprising it will take very long for the time to be done. This is where `ntpdate`, `makestep`, ... come into play if you are ok with a sudden jump in the system clock.

**Comment by jsliacan** [comment]
Hopefully resolved by #1702.
