### ISSUE TITLE
Add a clicumber test for `--disk-size` (new and previously created VM)

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#1696]
This is a major feature, requested by many users. We should test it on the 3 platforms.

**Comment by jsliacan** [comment]
There are Ginkgo tests coming up: 45c52a8462be44c8fc17214ef85c0344bc0c04e0. Should we also have this in Cucumber? It'll be a duplication of one of the cases in Ginkgo and testing this requires min 2x start/stop. WDYT?

**Comment by guillaumerose** [comment]
Yes Ginkgo is good also! Just pick one :)
