### ISSUE TITLE
Add reserved IP subnets in docs

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#1698]
The current setup has some limitations: some IP are reserved for CRC use. These subnets should not collide with the host network (or resources that the user wants to reach).

@adrianriobo hit this bug:
`network_controller.go:59] Error starting OpenShift Network Controller: service IP: 172.25.0.0/16 conflicts with host network: 172.25.160.0/20`

We should find all reserved subnets and add them in the doc.

**Comment by gbraad** [comment]
Right. The kubernetes cluster itself uses this rnage... and it seems the default switch can assign different ranges within 172. it is nnot clear which it might be, and if this is configurable. For nnow, a reboot might rotate this again

**Comment by adrianriobo** [comment]
Yes, this was on Windows machine. I will try with restart, as it was not happening before. I will check if ranges are configurable at all, and you can decide if we should inform about the reserved subnets (and configure them to avoid the collisions)

**Comment by guillaumerose** [comment]
As of today, the user cannot use this network subnets:
* 10.217.0.0/22
* 10.217.4.0/23
* 192.168.126.0/24
* 192.168.130.0/24  (linux only)
* for macOS and Windows, there is also an extra subnet generated automatically. 

See https://github.com/code-ready/crc/pull/1895

**Comment by robin-owen** [comment]
> for macOS and Windows, there is also an extra subnet generated automatically.

Can we document this in more detail? Is there a range that the subnet can potentially be in which we can refer to? Also, is this automatically generated subnet related to the static subnet on Linux (`192.168.130.0/24`)?

**Comment by guillaumerose** [comment]
For macOS: 192.168.64.0/24 (according to /Library/Preferences/SystemConfiguration/com.apple.vmnet.plist)
For Windows, apparently it's random. I need to double check https://docs.microsoft.com/en-us/answers/questions/48268/change-hyper-v-default-switch-ip-address-range.html

**Comment by robin-owen** [comment]
Fixed by #1698.
