### ISSUE TITLE
[BUG] No install file found under latest folder -- links from management platform return 404

### ISSUE THREAD

**Issue by monteledwards** [code-ready/crc#1706]
https://mirror.openshift.com/pub/openshift-v4/clients/crc/latest/crc-macos-amd64.tar.xz
Referenced on https://cloud.redhat.com/openshift/install/crc/installer-provisioned

also on the release page, link 
https://mirror.openshift.com/pub/openshift-v4/clients/crc/1.19.0 also 404

**Comment by praveenkumar** [comment]
@monteledwards I just checked the following url and it is accessible, can you try again?

**Comment by gbraad** [comment]
It is empty for me too and the download results in a 404

**Comment by gbraad** [comment]
![image](https://user-images.githubusercontent.com/1894/99762236-027cec80-2b33-11eb-8aa9-b9caa02f1a3c.png)
![image](https://user-images.githubusercontent.com/1894/99762332-38ba6c00-2b33-11eb-8f46-35bdcd452848.png)

**Comment by praveenkumar** [comment]
It is back again should be accessible now?

```
$ curl -Ik https://mirror.openshift.com/pub/openshift-v4/clients/crc/latest/crc-macos-amd64.tar.xz
HTTP/1.1 200 OK
Date: Fri, 20 Nov 2020 05:27:32 GMT
Server: Apache/2.2.15 (Red Hat)
Last-Modified: Tue, 17 Nov 2020 12:22:18 GMT
ETag: "514a2f1b-adf3b544-5b44c8bb59280"
Accept-Ranges: bytes
Content-Length: 2918430020
Strict-Transport-Security: max-age=15768000, includeSubDomains
Connection: close
Content-Type: application/x-xz
```

**Comment by gbraad** [comment]
@monteledwards can you retry this?

**Comment by gbraad** [comment]
![image](https://user-images.githubusercontent.com/1894/99763956-f6932980-2b36-11eb-9faf-fb5e8771a4a6.png)

**Comment by monteledwards** [comment]
Hi - sorry for no response. Yes, this is working again. Thank you!
