### ISSUE TITLE
Publish CRC on Download Manager

### ISSUE THREAD

**Issue by gorkem** [code-ready/crc#1709]
To be able to take advantage of the CDN and the reporting capabilities of the developer.redhat.com download manager. Publish CRC downloads also to the download manager. 

This means CRC artifacts will publish on both current and download manager for sometime while we work on replacing the references from websites and tools.

**Comment by deboer-tim** [comment]
A few comments from previous discussions:

- The pull secret can stay where it is. This change is for the binary/archive only (i.e. everything else).
- There was a concern about discoverability, i.e. I can currently go to a folder and see all the releases. As a user I wasn't even aware of this, I think we could replace with a webpage.
- It may be possible to setup download manager URLs now and point to the existing downloads. This would allow us to start getting metrics and update the website while the backend moves.

**Comment by guillaumerose** [comment]
Related to https://github.com/code-ready/crc/issues/1725#issuecomment-734837144

**Comment by gbraad** [comment]
@deboer-tim Which page is the start to download from?

> The pull secret can stay where it is. 

 Before using the Download manager there is no notion of a page that exists on dev.rh. This will stay this way? If not it means we need to link between both pages on cloud.redhat.com and developer.redhat.com.

**Comment by gbraad** [comment]
@guillaumerose the current download location uses sticky sessions that often causes more harm than needed as a simple restart of the download will not redirect to the other mirror location.

**Comment by gbraad** [comment]
Waiting on feedback from Bhama, hence not planned in a sprint

**Comment by gbraad** [comment]
Haven't received the expected confirmation from Bhama. That would happen this Friday?

**Comment by guillaumerose** [comment]
CRC bits are now on the CDN here: https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/crc/latest/

We now need to change links in https://cloud.redhat.com/openshift/create/local

**Comment by guillaumerose** [comment]
mirror.openshift.com will do a redirect to the CDN. We have nothing to do on our end for now.

**Comment by guillaumerose** [comment]
The link is now changed on the portal. mirror.openshift.com will be changed later.
