### ISSUE TITLE
[BUG] DNS issue with crc  1.19.0+94b0362 / Windows 10 - K8s API URL not resolveable

### ISSUE THREAD

**Issue by dzilbermanvmw** [code-ready/crc#1710]
### General information

  * OS: Linux / macOS / Windows
  Windows 10 ENT v.19041
  * Hypervisor: KVM / Hyper-V / hyperkit
 Hyper-V
  * Did you run `crc setup` before starting it (Yes/No)?
YES
  * Running CRC on: Laptop / Baremetal-Server / VM
Laptop

NOTE: had issue with "default" DNS server for Hyper-V default switch, started crc with command:
*crc start -n 8.8.8.8*

## CRC version
```bash
# Put `crc version` output here
```
CodeReady Containers version: 1.19.0+94b0362
OpenShift version: 4.6.3 (embedded in executable)
 
## CRC status
```bash
# Put `crc status --log-level debug` output here
```
DEBU CodeReady Containers version: 1.19.0+94b0362
DEBU OpenShift version: 4.6.3 (embedded in executable)
Checking file: C:\Users\Daniel\.crc\machines\crc\.crc-exist
DEBU Copying 'C:\Users\Daniel\.crc\cache\crc_hyperv_4.6.3\oc.exe' to 'C:\Users\Daniel\.crc\bin\oc\oc.exe'
DEBU About to run SSH command:
df -B1 --output=size,used,target /sysroot | tail -1
DEBU SSH command results: err: <nil>, output: 32720793600 12393676800 /sysroot
DEBU About to run SSH command with hidden output
DEBU SSH command failed
DEBU cannot get OpenShift status: ssh command error:
command : oc get co -ojson --context admin --cluster crc --kubeconfig /opt/kubeconfig
err     : Process exited with status 1
output  :
CRC VM:          Running
OpenShift:       Not Reachable (v4.6.3)
Disk Usage:      12.39GB of 32.72GB (Inside the CRC VM)
Cache Usage:     17.53GB
Cache Directory: C:\Users\Daniel\.crc\cache

## CRC config
```bash
# Put `crc config view` output here
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```
Host Name:                 DANIEL-NEW-PC
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19041 N/A Build 19041
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Daniel
Registered Organization:
Product ID:                00329-10280-00000-AA342
Original Install Date:     10/9/2020, 9:32:53 PM
System Boot Time:          11/19/2020, 9:43:22 PM
System Manufacturer:       LENOVO
System Model:              90BG004TUS
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 21 Model 56 Stepping 1 AuthenticAMD ~3600 Mhz
BIOS Version:              LENOVO IRKT58AUS, 5/13/2016
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-08:00) Pacific Time (US & Canada)
Total Physical Memory:     16,332 MB
Available Physical Memory: 2,942 MB
Virtual Memory: Max Size:  30,668 MB
Virtual Memory: Available: 12,637 MB
Virtual Memory: In Use:    18,031 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DANIEL-NEW-PC
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB4569745
                           [02]: KB4561600
                           [03]: KB4570334
                           [04]: KB4566782
Network Card(s):           8 NIC(s) Installed.
                           [01]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (Default Switch)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 172.31.176.1
                                 [02]: fe80::cd72:bd8:acac:a4f1
                           [02]: VirtualBox Host-Only Ethernet Adapter
                                 Connection Name: VirtualBox Host-Only Network
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 192.168.56.1
                                 [02]: fe80::6526:c20a:d84b:6e67
                           [03]: VirtualBox Host-Only Ethernet Adapter
                                 Connection Name: VirtualBox Host-Only Network #2
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 192.168.99.1
                                 [02]: fe80::f979:97ce:477d:258
                           [04]: Realtek 8821AE Wireless LAN 802.11ac PCI-E NIC
                                 Connection Name: Wi-Fi
                                 Status:          Media disconnected
                           [05]: Realtek PCIe GbE Family Controller
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.2
                                 [02]: fe80::b0ab:f03c:6e43:4ac4
                           [06]: Microsoft Network Adapter Multiplexor Driver
                                 Connection Name: Network Bridge
                                 Status:          Media disconnected
                           [07]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [08]: VirtualBox Host-Only Ethernet Adapter
                                 Connection Name: VirtualBox Host-Only Network #3
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 192.168.5.1
                                 [02]: fe80::741a:ff74:a5b9:e4be
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

### Steps to reproduce

  1. Configured crc by running 'crs setup', got confirmation 
  2. Attempted running 'crc start' - got error related to DNS server not available 
  3. ran 'crc start -n 8.8.8.8' for alternative DNS server - got confirmation message:
INFO Found Virtual Switch to use: Default Switch
INFO A CodeReady Containers VM for OpenShift 4.6.3 is already running
Started the OpenShift cluster

To access the cluster, first set up your environment by following 'crc oc-env' instructions.
Then you can access it by running 'oc login -u developer -p developer https://api.crc.testing:6443'.
To login as an admin, run 'oc login -u kubeadmin -p hxYtC-KLeQC-kfNkm-ppi8i https://api.crc.testing:6443'.
You can now run 'crc console' and use these credentials to access the OpenShift web console.

  4. Attempts to login as 'developer' or 'admin' users failed due to DNS error:
oc login -u developer -p developer https://api.crc.testing:6443

### Expected
user authenticated to crc K8s cluster context

### Actual
error: dial tcp: lookup api.crc.testing: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server. - 
![crc_hyper-v_default_switch](https://user-images.githubusercontent.com/42846514/99853718-5d651280-2b38-11eb-9a46-452c82381f8d.jpg)

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by dzilbermanvmw** [comment]
I have also tried dedicated vswitch on Hyper-V following the https://medium.com/@stefaan.degeyter/installing-codeready-containers-openshift4-on-hyper-v-win-10-9c8d8a510c01 *(see attached screenshot) and re-started 'crc' with debug mode hoping that it would pick up the new switch - it did, but failed to register DNS server:

DEBU About to run SSH command:
sudo podman run  --ip 10.88.0.8 --name dnsmasq -v /var/srv/dnsmasq.conf:/etc/dnsmasq.conf -p 53:53/udp --privileged -d quay.io/crcont/dnsmasq:latest
DEBU SSH command results: err: <nil>, output: b8f4abf5fa7b93b62c07c52f73407fa9904f39dfac9bd122628a817adb2c1457
INFO Will run as admin: add dns server address to interface vEthernet (crc)
Error running post start: Nameserver 172.31.186.106 not successfully set on interface vEthernet (crc)
[crc_start_debug_dedicated_crc_switch.txt](https://github.com/code-ready/crc/files/5576886/crc_start_debug_dedicated_crc_switch.txt)
![Uploading crc_vswitch_MSFT_loopback_adapter.jpg…]()

**Comment by guillaumerose** [comment]
Sorry for the delay.
This error is known on Windows. We are working on a new network stack that solve this issue. Can you give it a try ? https://github.com/code-ready/crc/wiki/VPN-support--with-an--userland-network-stack
Thanks.
