### ISSUE TITLE
Create a crc users group in Windows

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#1717]
Non-admin user support requires to push Hyper-V commands to the admin-helper and also remove the unix socket used by the daemon and use a named pipe. The named pipe will then allow the crc group to dial in and perform privileged commands.

Today, we just check if the current admin user is in Hyper-V group.

**Comment by guillaumerose** [comment]
Related to https://github.com/code-ready/crc/issues/1691

**Comment by guillaumerose** [comment]
The group would also help for this PR https://github.com/code-ready/crc/pull/1385 where we need to choose who can access the pipe.

**Comment by gbraad** [comment]
> Today, we just check if the current admin user is in Hyper-V group.

Note, the difference: Today we check if the user is part of the Hyper-V Admin group.
This is a static SID group to allow the user to peform Hyper-VV administrative tasks.

Non-admin users woould have to be mapped to a user with the Hyper-V admin privileges?

**Comment by guillaumerose** [comment]
Yes good point. Let's redefine this group as a secure way to communicate with named pipes for the admin-helper and crc daemon.

Forget about Hyper-V comments. Let's focus on hosts file.

Here is my plan:

Phase 1:
API: add, remove and clean hosts file

* Remove goodhosts and use the admin-helper CLI.
* Add clean command

Phase 2:
API: add, remove and clean hosts file both CLI and HTTP over named pipe.

* Add a daemon mode for the admin-helper that listens a named pipe for a particular group
* Run it as part of crc setup. Handle upgrade.
* Use it in crc start.

**Comment by anjannath** [comment]
>Non-admin user support requires to push Hyper-V commands to the admin-helper and also remove the unix socket used by >the daemon and use a named pipe. The named pipe will then allow the crc group to dial in and perform privileged commands.

>Today, we just check if the current admin user is in Hyper-V group.

A group would be really helpful for #1385 as well, if i understand it correctly, what it means is we'd still do the user is part of `hyperv` admins group check, but additionally once the group is created, also check if the user is part of this newly created group, so that we can nicely in a secure way allow some users to connect to the named pipe that the admin helper and crc daemon would create.

**Comment by cfergeau** [comment]
Fixed in 1.28.0 I think?

**Comment by guillaumerose** [comment]
Yes! thx
