### ISSUE TITLE
[BUG] crc start fails to run VM commands in Windows (permissions issue?)

### ISSUE THREAD

**Issue by Spirit328** [code-ready/crc#1720]
### General information

  * OS: Windows
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it: Yes, rebooted several times
  * Running CRC on: Baremetal-Server

## CRC version
```bash
# Put `crc version` output here
```
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
```

## CRC config
```bash
# Put `crc config view` output here
crc version
CodeReady Containers version: 1.19.0+94b0362
OpenShift version: 4.6.3 (embedded in executable)
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```
Please find the output of systeminfo here: 
https://gist.github.com/Spirit328/eeda06d8898ef2edab1f47225546ffc2

### Steps to reproduce

  1.  Download latest CRC Version for Windows
  2.  Unzip
  3.  PS: $env:Path += ";C:\Users\tmichels\Downloads\crc-windows-amd64\crc-windows-1.19.0-amd64"
  4. crc setup --log-level debug

### Expected
Installed CRC, ready to use.

### Actual
Setup fails with error message:
[...]
DEBU Virtual Switch not found
Unable to perform Hyper-V administrative commands. Please reboot your system and run 'crc setup' to complete the setup process

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```
It already fails with "crc delete -f":
Machine 'crc' does not exist. Use 'crc start' to create it.

... and this is exactly the issue :-)

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.
https://gist.github.com/Spirit328/8a61f3f39f2ab146b98fd46cd19f63f9

**Comment by gbraad** [comment]
Can you run get-vm from powershell and share the output?

Note: installs alongside virtualbox aren't supported

**Comment by Spirit328** [comment]
I ran the command: "get-vm" in a regular PS.

PS: get-vm {ENTER}
get-vm : Fehler beim Zugreifen auf ein Objekt auf dem Computer "THOR", da das Objekt nicht gefunden wurde.
Möglicherweise wurde es gelöscht. Vergewissern Sie sich, dass auf dem Computer der Verwaltungsdienst für virtuelle
Computer ausgeführt wird.
In Zeile:1 Zeichen:1
+ get-vm
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.GetVM

Error during access to an object on this computer "THOR", because the object was not found.
Possibly it got deleted. Make sure the administration service for virtual computers will be executed.

In line: 1 Character: 1
+ get-vm
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.GetVM

I uninstalled Virtualbox, rebooted the computer, but nothing changed. :-(

**Comment by gbraad** [comment]
Try creating a VM using the Hyper-V Management tool. This looks more like a setup issue than CRC. If this fails, try removing the Hyper-V feature and re-add.

**Comment by cameronkerrnz** [comment]
I found that removing the Hyper-V feature, rebooting, then allowing crc setup to fix up my version of this issue. I think I had done something earlier with the default switch in some earlier struggles gettiing a VM working in Hyper-V. Some more debug messaging as to what commands its using (like what 'crc start --log-level debug') would surely be appreciated.
