### ISSUE TITLE
Issues witth resolving the crc.testing addresses on macOS: server on port 53 misbehaving

### ISSUE THREAD

**Issue by ckvtvm-arch** [code-ready/crc#1723]
### General information

  * OS: macOS  
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it - yes
  * Running CRC on: Laptop  

## CRC version

CodeReady Containers version: 1.18.0+bb304aa
OpenShift version: 4.6.1 (embedded in binary)

## CRC Setup

af71194@LC02CHB58MD6R ~ % crc setup
INFO Checking if oc binary is cached              
INFO Checking if podman remote binary is cached   
INFO Checking if goodhosts binary is cached       
INFO Checking if CRC bundle is cached in '$HOME/.crc' 
INFO Checking minimum RAM requirements            
INFO Checking if running as non-root              
INFO Checking if HyperKit is installed            
INFO Checking if crc-driver-hyperkit is installed 
INFO Checking file permissions for /etc/hosts     
INFO Checking file permissions for /etc/resolver/testing 
Setup is complete, you can now run 'crc start' to start the OpenShift cluster

## CRC status

af71194@LC02CHB58MD6R ~ % crc status --log-level debug
DEBU CodeReady Containers version: 1.18.0+bb304aa 
DEBU OpenShift version: 4.6.1 (embedded in binary) 
Checking file: /Users/af71194/.crc/machines/crc/.crc-exist
DEBU About to run SSH command with hidden output  
DEBU SSH command succeeded                        
DEBU authentication operator is still progressing, Reason: OAuthVersionRoute_WaitingForRoute 
DEBU authentication operator not available, Reason: OAuthRouteCheckEndpointAccessibleController_EndpointUnavailable::OAuthVersionRoute_RequestFailed 
DEBU operator-lifecycle-manager-packageserver operator not available, Reason:  
DEBU operator-lifecycle-manager-packageserver operator is still progressing, Reason:  
DEBU About to run SSH command:
df -B1 --output=size,used,target /sysroot | tail -1 
DEBU SSH command results: err: <nil>, output: 32720793600 12335108096 /sysroot 
CRC VM:          Running
OpenShift:       Starting
Disk Usage:      12.34GB of 32.72GB (Inside the CRC VM)
Cache Usage:     39.26GB
Cache Directory: /Users/af71194/.crc/cache

## CRC config

af71194@LC02CHB58MD6R ~ % crc config view
- nameserver                            : 8.8.8.8
- no-proxy                              : https://console-openshift-console.apps-crc.testing/
- pull-secret-file                      : /usr/local/bin/pull-secret.txt

## Host Operating System
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H15
 

### Steps to reproduce

  1. ssh -i ~/.crc/machines/crc/id_rsa core@$(crc ip) 

      Failed Units: 1

  2. status systemd-modules-load

     ● systemd-modules-load.service - Load Kernel Modules
   Loaded: loaded (/usr/lib/systemd/system/systemd-modules-load.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2020-11-25 23:15:08 UTC; 20min ago
     Docs: man:systemd-modules-load.service(8)
           man:modules-load.d(5)
 Main PID: 866 (code=exited, status=1/FAILURE)
      CPU: 12ms

  3. journalctl_pid=866
-- Logs begin at Tue 2020-10-27 01:51:02 UTC, end at Wed 2020-11-25 23:37:28 UTC. --
Nov 25 23:15:08 crc-h66l2-master-0 systemd-modules-load[866]: **Failed to insert 'hv_sock': No such device**

  4. crc console
     login to console 
     deploy image from dockerhub

### Expected

Successful deploy

### Actual

Internal error occurred: docker.io/jboss/keycloak:latest: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 172.25.0.10:53: server misbehaving

### Logs
 

https://gist.github.com/ckvtvm-arch/f43c135833ec81cbe6fabc04ce9b436c

**Comment by ckvtvm-arch** [comment]
I have spend 2 weeks trying to resolve this looking at DNS, Firewall, Previous versions of CRC, hyperkit etc.  NO LUCK . please help

**Comment by guillaumerose** [comment]
@ckvtvm-arch can you try this new feature ? https://github.com/code-ready/crc/wiki/VPN-support--with-an--userland-network-stack it should help for your case. Thanks.

**Comment by gbraad** [comment]
the title and journalctl error: `Failed to insert 'hv_sock': No such device` is not the issue you are experiencing. However, you are seeing DNS resolve issues. Changing the title accordingly

**Comment by cfergeau** [comment]
Let's keep tracking this in https://github.com/code-ready/crc/issues/1675
