### ISSUE TITLE
Is it possible to use CRC in CircleCI builds ?

### ISSUE THREAD

**Issue by gsaslis** [code-ready/crc#1735]
Hi folks, 

### General information

We are looking for a way to spin up a circleci VM in which to start CRC - so that we can run some tests against a short-lived openshift cluster. We previously used to do this with `oc cluster up` in ocp 3.11 but not sure what is the best way to do that with CRC, given nested virtualization problems. 

Since the CRC project itself is using CircleCI, I was wondering if perhaps there is some example somewhere of spinning up CRC inside circleci?

**Comment by anjannath** [comment]
> We previously used to do this with oc cluster up in ocp 3.11 but not sure what is the best way to do that with CRC, given nested virtualization problems.

in ocp 3.11 oc cluster up was using docker to deploy the ocp components as containers, for CRC we need a VM, as circleci doesn't have nested virtualization, you won't be able to launch CRC there.

> Since the CRC project itself is using CircleCI, I was wondering if perhaps there is some example somewhere of spinning up CRC inside circleci?

We only run go unit tests there, our e2e integration tests runs on centos ci and the openshift ci which uses GCP.

**Comment by gbraad** [comment]
the other restriction would be resource usage. most public CI services would not provide 12G of memory.

best wwould be to use your own CI environment or base one of GitLab runners

**Comment by gsaslis** [comment]
@anjannath ok, thanks for confirming, yes, this is what we were afraid of  : /

@gbraad circleci (at least) does currently provide executors that go up to 16G: https://circleci.com/docs/2.0/configuration-reference/#machine-executor-linux

**Comment by gbraad** [comment]
In that case, nested virtualization is the only thing holding this back.
