### ISSUE TITLE
Update README.md now that alpha releases are available

### ISSUE THREAD

**Issue by robin-owen** [code-ready/crc#174]

**Comment by gbraad** [comment]
for the public this is still 'coming soon'

**Comment by robin-owen** [comment]
Noted.

In that case, we can still use this issue to update the README to contain information about first-time setup and installation of CodeReady Containers for those who have the required bundle (without explicitly mentioning where to get it).

**Comment by finp** [comment]
I'm confused, comment on #173  says "releases aren't actually at the moment done from GitHub.", but I see 2 releases at https://github.com/code-ready/crc/releases 
The public will see these if they click Releases, so what's the point? Do you want some help for 'Getting Started' docs?

**Comment by gbraad** [comment]
CRC needs to be released as both a binary and an image bundle, based on the
result of code-ready/snc. The first is available, but not usable without
the bundle. This is what I was referring to.
