### ISSUE TITLE
Error creating machine: Error in driver during machine creation: host is not running: getting ip during machine start

### ISSUE THREAD

**Issue by linuxqiao** [code-ready/crc#1742]
### General information

  * OS: Linux
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it? (Yes)

## CRC version
```bash
$ ./crc version
CodeReady Containers version: 1.19.0+94b0362
OpenShift version: 4.6.3 (embedded in executable)
```
  
## CRC status
```bash
# Put the output of `crc status`
```

## CRC config
```bash
$ ./crc status
CRC VM:          Paused
OpenShift:       Stopped
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     15.32GB
Cache Directory: /home/test/.crc/cache
```

## Host Operating System
```bash
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.4 Beta (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.4:beta"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.4 Beta"
```

### Steps to reproduce

  1. ./crc setup
  2. ./crc start -p ../pull-secret.txt --log-level debug
  3. 
  4. 

### Actual
INFO Starting CodeReady Containers VM for OpenShift 4.6.3... 
DEBU Updating CRC VM configuration                
(crc) Calling .GetConfigRaw
(crc) Calling .Start
(crc) DBG | Starting VM crc
(crc) DBG | Validating network
(crc) DBG | Validating storage pool
(crc) DBG | GetIP called for crc
(crc) DBG | Getting current state...
(crc) DBG | Waiting for machine to come up 0/60
(crc) DBG | GetIP called for crc
(crc) DBG | Getting current state...
Making call to close driver server
(crc) Calling .Close
Successfully made call to close driver server
Making call to close connection to plugin binary
(crc) DBG | Closing plugin on server side
Error starting stopped VM: host is not running: getting ip during machine start

### Logs

Full log by: $ ./crc start -p ../pull-secret.txt --log-level debug
https://gist.github.com/linuxqiao/e125d55391857943ffc64c029e35a84d

**Comment by praveenkumar** [comment]
In your issue `crc status` is showing the VM in `paused` state no the `Stopped` state and might be reason it didn't retry before given up.

```
$ ./crc status
CRC VM:          Stopped
OpenShift:       Stopped
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     46.68GB
Cache Directory: /home/prkumar/.crc/cache

$ sudo virsh list --all
 Id   Name   State
-----------------------
 -    crc    shut off
```

**Comment by linuxqiao** [comment]
Tannks for your help.
I just start VM by 'crc start', and crc vm drop to this status.
I try to reboot/resume/start crc vm, but all failed.

$ sudo virsh reboot crc
Domain crc is being rebooted
$ sudo virsh list --all
 Id   Name   State
---------------------
 2    crc    paused

$ sudo virsh resume crc
error: Failed to resume domain crc
error: internal error: unable to execute QEMU command 'cont': Resetting the Virtual Machine is required

Any other suggestions?

**Comment by cfergeau** [comment]
Do you have enough disk space on the host? libvirt pauses virtual machines when they run out of disk space.

**Comment by linuxqiao** [comment]
Yes. disk space is enough.
Size  Used Avail Use% Mounted on
70G   14G   57G  20% /
483G   21G  463G   5% /home

**Comment by linuxqiao** [comment]
Still have this issue on 1.20.0
$ ./crc version
CodeReady Containers version: 1.20.0+ef3f80d
OpenShift version: 4.6.6 (embedded in executable)

$ ./crc start -p ../pull-secret.txt 
INFO Checking if podman remote executable is cached 
INFO Checking if goodhosts executable is cached   
INFO Checking minimum RAM requirements            
INFO Checking if running as non-root              
INFO Checking if Virtualization is enabled        
INFO Checking if KVM is enabled                   
INFO Checking if libvirt is installed             
INFO Checking if user is part of libvirt group    
INFO Checking if libvirt daemon is running        
INFO Checking if a supported libvirt version is installed 
INFO Checking if crc-driver-libvirt is installed  
INFO Checking if systemd-networkd is running      
INFO Checking if NetworkManager is installed      
INFO Checking if NetworkManager service is running 
INFO Checking if /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf exists 
INFO Checking if /etc/NetworkManager/dnsmasq.d/crc.conf exists 
INFO Checking if libvirt 'crc' network is available 
INFO Checking if libvirt 'crc' network is active  
INFO Loading bundle: crc_libvirt_4.6.6.crcbundle ... 
INFO Verifying bundle crc_libvirt_4.6.6.crcbundle ... 
INFO Creating CodeReady Containers VM for OpenShift 4.6.6... 
Error creating machine: Error creating the VM: Error creating machine: Error in driver during machine creation: host is not running: getting ip during machine start

$ ./crc status
CRC VM:          Paused
OpenShift:       Stopped
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     29.01GB
Cache Directory: /home/test/.crc/cache

Then, check the VM status, and can't start/resume crc VM.
$ sudo virsh list --all
 Id   Name   State
---------------------
 1    crc    paused

Anyone have ideas for this problem?

**Comment by cfergeau** [comment]
Can you take a look at the end of /var/log/libvirt/qemu/crc.log and see if there's any hint why the VM was paused ?

**Comment by linuxqiao** [comment]
All logs like this:
2020-12-09 03:14:59.744+0000: starting up libvirt version: 6.0.0, package: 30.module+el8.4.0+8705+34397d87 (Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla>, 2020-11-09-14:40:02, ), qemu 
version: 4.2.0qemu-kvm-4.2.0-37.module+el8.4.0+8837+c89bcfe6, kernel: 4.18.0-257.el8.x86_64, hostname: nec-ex5800-01.rhts.eng.pek2.redhat.com
LC_ALL=C \
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin \
HOME=/var/lib/libvirt/qemu/domain-1-crc \
XDG_DATA_HOME=/var/lib/libvirt/qemu/domain-1-crc/.local/share \
XDG_CACHE_HOME=/var/lib/libvirt/qemu/domain-1-crc/.cache \
XDG_CONFIG_HOME=/var/lib/libvirt/qemu/domain-1-crc/.config \
QEMU_AUDIO_DRV=none \
/usr/libexec/qemu-kvm \
-name guest=crc,debug-threads=on \
-S \
-object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-1-crc/master-key.aes \
-machine pc-q35-rhel8.2.0,accel=kvm,usb=off,dump-guest-core=off \
-cpu host,rdrand=off \
-m 8790 \
-overcommit mem-lock=off \
-smp 4,sockets=4,cores=1,threads=1 \
-uuid ec6dac51-ffe2-403b-bd91-d645f49e729c \
-no-user-config \
-nodefaults \
-chardev socket,id=charmonitor,fd=37,server,nowait \
-mon chardev=charmonitor,id=monitor,mode=control \
-rtc base=utc \
-no-shutdown \
-boot menu=off,strict=on \
-device pcie-root-port,port=0x10,chassis=1,id=pci.1,bus=pcie.0,multifunction=on,addr=0x2 \
-device pcie-root-port,port=0x11,chassis=2,id=pci.2,bus=pcie.0,addr=0x2.0x1 \
-device pcie-root-port,port=0x12,chassis=3,id=pci.3,bus=pcie.0,addr=0x2.0x2 \
-device pcie-root-port,port=0x13,chassis=4,id=pci.4,bus=pcie.0,addr=0x2.0x3 \
-device pcie-root-port,port=0x14,chassis=5,id=pci.5,bus=pcie.0,addr=0x2.0x4 \
-device qemu-xhci,id=usb,bus=pci.2,addr=0x0 \
-blockdev '{"driver":"file","filename":"/home/test/.crc/cache/crc_libvirt_4.6.6/crc.qcow2","aio":"threads","node-name":"libvirt-2-storage","auto-read-only":true,"discard":"unmap"}' \
-blockdev '{"node-name":"libvirt-2-format","read-only":true,"driver":"qcow2","file":"libvirt-2-storage","backing":null}' \
-blockdev '{"driver":"file","filename":"/home/test/.crc/machines/crc/crc.qcow2","aio":"threads","node-name":"libvirt-1-storage","auto-read-only":true,"discard":"unmap"}' \
-blockdev '{"node-name":"libvirt-1-format","read-only":false,"driver":"qcow2","file":"libvirt-1-storage","backing":"libvirt-2-format"}' \
-device virtio-blk-pci,scsi=off,bus=pci.3,addr=0x0,drive=libvirt-1-format,id=virtio-disk0,bootindex=1 \
-netdev tap,fd=39,id=hostnet0,vhost=on,vhostfd=40 \
-device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:fd:fc:07:21:82,bus=pci.1,addr=0x0 \
-chardev pty,id=charserial0 \
-device isa-serial,chardev=charserial0,id=serial0 \
-vnc 127.0.0.1:0 \
-device cirrus-vga,id=video0,bus=pcie.0,addr=0x1 \
-object rng-random,id=objrng0,filename=/dev/urandom \
-device virtio-rng-pci,rng=objrng0,id=rng0,bus=pci.4,addr=0x0 \
-sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny \
-msg timestamp=on
2020-12-09 03:14:59.745+0000: Domain id=1 is tainted: host-cpu
char device redirected to /dev/pts/1 (label charserial0)
2020-12-09T03:14:59.852006Z qemu-kvm: -device cirrus-vga,id=video0,bus=pcie.0,addr=0x1: warning: 'cirrus-vga' is deprecated, please use a different VGA card instead
error: kvm run failed No such file or directory
RAX=00000000000fffff RBX=0000000000000c90 RCX=0000000000000c90 RDX=0000000000000000
RSI=00000000000fffff RDI=0000000000000c90 RBP=ffffffffbbb89c3f RSP=ffffb4ef4189fde0
R8 =ffff991d5c3d2ce0 R9 =0000000000000000 R10=ffffb4ef4189fdf8 R11=0000000000000000
R12=ffffffffbbd7d718 R13=ffffffffbbb787ce R14=0000000000000000 R15=0000000000000000
RIP=ffffffffba261d38 RFL=00000282 [--S----] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0000 0000000000000000 ffffffff 00c00000
CS =0010 0000000000000000 ffffffff 00a09b00 DPL=0 CS64 [-RA]
SS =0018 0000000000000000 ffffffff 00c09300 DPL=0 DS   [-WA]
DS =0000 0000000000000000 ffffffff 00c00000
FS =0000 0000000000000000 ffffffff 00c00000
GS =0000 ffff991d5c700000 ffffffff 00c00000
LDT=0000 0000000000000000 ffffffff 00c00000
TR =0040 fffffe0000059000 0000206f 00008b00 DPL=0 TSS64-busy
GDT=     fffffe0000057000 0000007f
IDT=     fffffe0000000000 00000fff
CR0=80050033 CR2=00007f8ea5106000 CR3=000000024600a004 CR4=00160ee0
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000 
DR6=00000000ffff0ff0 DR7=0000000000000400
EFER=0000000000000d01
Code=40 00 66 2e 0f 1f 84 00 00 00 00 00 48 83 ec 08 89 f0 89 f9 <0f> 30 31 c0 0f 1f 44 00 00 48 83 c4 08 c3 48 c1 e2 20 89 f6 89 44 24 04 48 09 d6 89 c2 e8

The main failure:
2020-12-09T03:14:59.852006Z qemu-kvm: -device cirrus-vga,id=video0,bus=pcie.0,addr=0x1: warning: 'cirrus-vga' is deprecated, please use a different VGA card instead
error: kvm run failed No such file or directory
^^^^^^^^^^^^^^^ 
I run all of them by default configuration, how to use other VGA crad or ignore this?
Thanks.

**Comment by cfergeau** [comment]
`qemu-kvm-4.2.0-37.module+el8.4.0+8837+c89bcfe6` and `kernel: 4.18.0-257.el8.x86_64` are development RHEL packages, they are newer than what is in latest RHEL (8.3). Since the kvm error you get + trace make it look like a qemu/kernel bug, do you have a rhel 8.3 or older system available where you could check whether this happens?

**Comment by linuxqiao** [comment]
Yeap! Thank you! It works on RHEL-8.3.

**Comment by praveenkumar** [comment]
closing this since the used packages were from the devel not the stable one.
