### ISSUE TITLE
Space issue - how to clean VM folder  /sysroot/ostree/deploy/rhcos/var/lib/containers/storage/overlay

### ISSUE THREAD

**Issue by JiriHusak-lab** [code-ready/crc#1746]
Hi,

I've realized that my CRC space issue is caused by the fact that Container data are not purged after Container is deleted.

This is VM folder, where container folder are created:
 /sysroot/ostree/deploy/rhcos/var/lib/containers/storage/overlay

Each started container creates new folder here with Container content and when terminated - folder remains here.
One folder Example:
 /sysroot/ostree/deploy/rhcos/var/lib/containers/storage/overlay/1d14f839a486d2ad3a4f3f959e87e704f8096d73ea1f2b730fb73ad167fe0f13

I tried (using some logic based on folder content) to delete folders created by my Pods but I've created too many so my CRC can't start and I've to delete and create cluster again. Ok, I can improve my process but it is danger and difficult.

So question - how to purge mentioned folder or how to set CRC to delete container folder on Container termination?
What  I need to setup in CRC?

Now, each container restart add new folder, previous remain. So VM size is growing and growing.

Thanks a lot,
Jiri

**Comment by cfergeau** [comment]
Do these images show up in `sudo podman images`? If yes, I'd try `sudo podman image prune` and see if it helps.

**Comment by cfergeau** [comment]
Is this a duplicate of https://github.com/code-ready/crc/issues/1711 ?

**Comment by JiriHusak-lab** [comment]
Yes, after your reply I see it is the same. 
And thanks a lot, seem it is working.
sudo podman image prune did not clean, it tried just dangling images but
this works properly: sudo podman image prune -a -f

So thanks again, This issue and https://github.com/code-ready/crc/issues/1711 can be closed now.
