### ISSUE TITLE
Error cleaning up hyperkit on macos

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/crc#1749]
### General information

  * OS: macOS 14/15
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
CodeReady Containers version: Pre-release (1.20)
OpenShift version: 4.6.6 (not embedded in executable)
```
  
## CRC status
```bash
Machine 'crc' does not exist. Use 'crc start' to create it
```

## CRC config
```bash
```

## Host Operating System
```bash
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G1012
```

### Steps to reproduce

  1. crc setup
  2. crc start
  3. check hyperkit process exists
  4. crc delete -f
  5. check hyperkit process, now the process does not exists
  6. crc cleanup --log-level debug

### Expected

 crc cleanup finish properly and cleanup the machine

### Actual

crc cleanup end on fail (trying to kill hyperkit)

### Logs

```bash
macmini-crcqe-1:bundle_baremetal_macos14-brno crcqe$ crc cleanup --log-level debug
DEBU CodeReady Containers version: 1.19.0+d4ad56f 
DEBU OpenShift version: 4.6.6 (not embedded in executable) 
INFO Unload CodeReady Containers tray             
INFO Unload CodeReady Containers daemon           
INFO Removing launchd configuration for tray      
INFO Removing launchd configuration for daemon    
INFO Removing /etc/resolver/testing file          
DEBU Removing /etc/resolver/testing file          
INFO Will use root access: Remove file /etc/resolver/testing 
DEBU Running '/usr/bin/sudo rm -f /etc/resolver/testing' 
INFO Stopping CRC Hyperkit process                
DEBU Running '/usr/bin/pkill -f /Users/crcqe/.crc/bin/hyperkit' 
DEBU Command failed: exit status 1                
DEBU stdout:                                      
DEBU stderr:                                      
DEBU Failed to kill 'hyperkit' process. exit status 1 
DEBU Failed to kill 'hyperkit' process. exit status 1 
INFO Removing CRC Machine Instance directory      
DEBU Deleting machines directory                  
Failed to kill 'hyperkit' process. exit status 1

```

**Comment by cfergeau** [comment]
Do you have a hyperkit process running which it is failing to kill? or is this failing because there are no hyperkit processes running?

**Comment by adrianriobo** [comment]
You can see the log for the full flow described at Steps to reproduce [here](https://gist.github.com/adrianriobo/fbdf97f7fa408ea96398d703b8155029)

Also as first point to check it seems pkill even with -f parameter is returning exit 1
https://github.com/code-ready/crc/pull/1658/files#diff-d20508c28dcc59acc45e4e2d770cfcf4e4e9eff7b757671d3099182bcbcb19a4R195

**Comment by adrianriobo** [comment]
It is failing because there is no hyperkit process, so even with -f it seems some kind of check will be requierd

**Comment by cfergeau** [comment]
failures in cleanup functions are not fatal, the following cleanup methods will be run even if there was a failure, so it is not too bad. It would be nicer not to report expected failures at the end of `crc cleanup` though :)

**Comment by jsliacan** [comment]
> It would be nicer not to report expected failures at the end of crc cleanup though :)

Yeah, especially since `cleanup` is probably understood to "make sure no hyperkit process remains running" instead of "kill a hyperkit process" (the user doesn't mind if a process was killed or not, as long as it isn't running at the end).
