### ISSUE TITLE
Integration tests fail with non-default "Downloads" directory

### ISSUE THREAD

**Issue by robin-owen** [code-ready/crc#175]
I currently have my "Downloads" directory set to `~/dls` in `~/.config/user-dirs.dirs`.

Trying to run the integration tests through `make integration`, I encounter errors related to the bundle not being available in `~/Downloads`, which is a non-existent directory on my system.

Note: From the terminal, we can get the XDG "downloads" directory as follows:

```
$ xdg-user-dir DOWNLOAD
```

**Comment by praveenkumar** [comment]
Right I asked same on @jsliacan PR to make it more generic in terms of where to download the files for start.

- https://github.com/code-ready/crc/pull/121

**Comment by jsliacan** [comment]
Yes, I pushed the changes to #121 that include bundle download as part of the test (the bundle will be placed in the current test dir -- I think `test-run` inside `test/integration/out`). However, the changes I made don't build for reasons that are not present on my laptop. I need a bit of time to figure it out.

**Comment by cfergeau** [comment]
I believe this is fixed now, `make integration BUNDLE_LOCATION=xxxx` must be used to indicate the bundle location.
