### ISSUE TITLE
[BUG] inconsistency between memory specified on start and defined to VM (unit mismatch)

### ISSUE THREAD

**Issue by vashirov** [code-ready/crc#1763]
### General information

  * OS: Linux
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop

## CRC version
```bash
$ crc version                                                                                                                                                                
CodeReady Containers version: 1.20.0+ef3f80d                                                                                                                                 
OpenShift version: 4.6.6 (embedded in executable)
```

### Steps to reproduce

  1. crc start --memory 16384
  2. sudo virsh dumpxml crc | grep memory

### Expected

```xml
<memory unit='KiB'>16777216</memory>
```

### Actual
```xml
<memory unit='KiB'>16000000</memory>
```

@praveenkumar pointed to https://github.com/code-ready/machine-driver-libvirt/blob/master/pkg/libvirt/libvirt.go#L119-L121

**Comment by gbraad** [comment]
Perhaps avoid the whole unitless specification of memory?

**Comment by praveenkumar** [comment]
There is already PR https://github.com/code-ready/crc/pull/1740 but we are thinking to change it on machine driver side since other hypervisor using it as MiB instead MB.
