### ISSUE TITLE
Improve startup messages to be more informative

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#1765]
During start we need to inform the user of the settings that will be applied:

  * Show progress, maybe #994? or stages
  * Environment settings
    * proxy to be applied (only report this will be activated) 
  * Summarize VM settings
    * disk size
    * memory size (especially as unitless parameters can lead to confusion)
    * CPU
    * on restart; disk usage
  * Cluster settings
    * summarize details for login #1764

**Comment by guillaumerose** [comment]
Proxy settings are almost irrelevant on the host side now. The only http connection we performed is to get https://mirror.openshift.com/pub/openshift-v4/clients/crc/latest/release-info.json.
