### ISSUE TITLE
Build crc in a container

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#1766]
In order to use OpenShift CI for crc basic checks (lint, test and compilation), we need to create a Dockerfile for crc.

It will help us to move out of Travis.

**Comment by cfergeau** [comment]
A basic one is
```
$ cat Containerfile 
FROM registry.redhat.io/ubi8/ubi AS build
WORKDIR /go/src/app
RUN yum -y install diffutils git-core golang make
COPY . .
RUN make check

FROM registry.redhat.io/ubi8/ubi
COPY --from=build /go/src/app/out/linux-amd64/crc .
ENTRYPOINT ["/crc"]
```
But if it's aimed at being used by OpenShift CI, they may have more requirements regarding the base image, labelling, ...

**Comment by gbraad** [comment]
Moving the excutable into a container does not make a lot of sense, or would this be an alternative distribution method? THe idea is to have a consistent build environment for the native and cross compilation.

the result would have to be copied out using `[docker|podman] cp` to be useful.

This would allow easily cross compilation on a platform like Windows using Docker for Windows or Docker/Podman on WSL2.
