### ISSUE TITLE
Odo/Nodeshift deployment times out

### ISSUE THREAD

**Issue by mhdawson** [code-ready/crc#1768]
### General information

  * OS:  Windows
  * Hypervisor: Hyper-V 
  * Did you run `crc setup` before starting it (Yes)?

## CRC version
```bash
CodeReady Containers version: 1.19.0+94b0362
OpenShift version: 4.6.3 (embedded in executable)
```
  
## CRC status
```bash
CRC VM:          Running
OpenShift:       Degraded (v4.6.3)
Disk Usage:      16.01GB of 32.72GB (Inside the CRC VM)
Cache Usage:     17.53GB
Cache Directory: C:\Users\midawson\.crc\cache
```

## CRC config
```bash
nothing
```

## Host Operating System
```bash
Host Name:                 PF1MYAZ6-W10E
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.18363 N/A Build 18363
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Windows User
Registered Organization:   Red Hat
Product ID:                00329-00000-00003-AA625
Original Install Date:     11/18/2020, 7:21:09 PM
System Boot Time:          12/7/2020, 4:08:11 PM
System Manufacturer:       LENOVO
System Model:              20MAS1720T
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 10 GenuineIntel ~2592 Mhz
BIOS Version:              LENOVO N2CET50W (1.33 ), 1/15/2020
Windows Directory:         C:\windows
System Directory:          C:\windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-08:00) Pacific Time (US & Canada)
Total Physical Memory:     32,476 MB
Available Physical Memory: 6,755 MB
Virtual Memory: Max Size:  37,340 MB
Virtual Memory: Available: 8,632 MB
Virtual Memory: In Use:    28,708 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    win.redhat.com
Logon Server:              \\RDU2-DC02
Hotfix(s):                 8 Hotfix(s) Installed.
                           [01]: KB4580980
                           [02]: KB4513661
                           [03]: KB4516115
                           [04]: KB4517245
                           [05]: KB4521863
                           [06]: KB4580325
                           [07]: KB4586863
                           [08]: KB4586786
Network Card(s):           6 NIC(s) Installed.
                           [01]: Intel(R) Ethernet Connection (7) I219-LM
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     10.1.1.221
                                 IP address(es)
                                 [01]: 10.1.1.79
                                 [02]: fe80::7139:d752:9e7d:a31e
                           [02]: Intel(R) Wireless-AC 9560 160MHz
                                 Connection Name: Wi-Fi
                                 Status:          Media disconnected
                           [03]: Viscosity Virtual Adapter V9.1
                                 Connection Name: Raleigh (RDU2)
                                 Status:          Hardware not present
                           [04]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [05]: Viscosity Virtual Adapter V9.1
                                 Connection Name: Raleigh (RDU2)1
                                 Status:          Hardware not present
                           [06]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (Default Switch)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 192.168.170.225
                                 [02]: fe80::8d3b:42a8:b5fc:3ab4
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```

### Steps to reproduce

  1. Install CRC on Windows
  2. Log using oc command provided through console
  3. Follow instructions in this section 3.4. `Deploying a sample application with odo` in https://access.redhat.com/documentation/en-us/red_hat_codeready_containers/1.20/html-single/getting_started_guide/index#deploying-sample-application-with-odo_gsg
  4. run `odo push`

### Expected
Application deploys successfully

### Actual

push times out: 

odo push
Validation
 V  Checking component [28ms]

Configuration changes
 V  Retrieving component data [76ms]
 V  Triggering build from git [43ms]
h X  Waiting for build to finish [5m]
 X  Failed To Update Config To Component Deployed.
Error: unable to build the component: nodejs-thjj: unable to build nodejs-thjj-app-2, error: : timeout waiting for build nodejs-thjj-app-2 to start

I also tried a similar flow with nodeshift and it times out as well.  
I followed the same flow with a non CRC cluster and everything ran as expected...

### Logs
.

**Comment by cfergeau** [comment]
Did you include the `--s2i` flag when creating the nodejs component? Have you tried giving more memory to your instance?

**Comment by mhdawson** [comment]
@cfergeau I added 10G to the memory so I think it should have enough.  I think I also followed the exact same instructions between the run that worked on a different cluster versus what I ran on the CRC cluster.

**Comment by mhdawson** [comment]
This is the command from the instructions and it does include the `--s2i` flag: 

```shell
 odo create nodejs --s2i --git https://github.com/openshift/nodejs-ex
```

**Comment by gbraad** [comment]
Can you get the build log?
If it times out, it might be a network issue perhaps, like an image or dependency not being able to be pulled.

**Comment by mhdawson** [comment]
@gbraad thanks for your help on this.

Sorry but I'm a bit new to OpenShift and I can't seem to find a log for the build. I can find a BuildDetails which looks matched to my request but nothing on that seems to be a link to a log file. Can you point me to where to look for that?

I do see it is using

```shell
image-registry.openshift-image-registry.svc:5000/openshift/nodejs@sha256:4c2a9a7cb573190fcf8772b054f090daabc8b957cad0ba2373899ed6a70c25dd
```
which if i try to ping `image-registry.openshift-image-registry.svc` resolves an address but times out on a ping. 
```
Pinging image-registry.openshift-image-registry.svc [172.25.95.7] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 172.25.95.7:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
```

If I do an `ipcofing \all` I don't see any interface with an IP like that but maybe it's inside the CRC virtual machine? I don't know enough to know if that is expected or not.

**Comment by mhdawson** [comment]
Switched to the Admin view and found the Logs tab.

I waited quite a while on "Loading log..." but still 0 lines.

I tried to download the log and it ended up saying: log?container= coundn't be downloaded

**Comment by gbraad** [comment]
Are you connected to the VPN when you tried this?

**Comment by mhdawson** [comment]
@gbraad not connect to VPN

**Comment by mhdawson** [comment]
I think I figure out the issue.  It took a number of attempts, work arounds etc. to get CRC to install ok.  I think that messed up the default swtich such that the crc vm could not do dns lookups externally.  This seems to have fixed it:

crc config set nameserver 8.8.8.8

**Comment by gbraad** [comment]
So it was a network issue.

The default switch is known to cause issues with some stops to perform
lookups. Will go ahead with the auto forward of the host's dns.

**Comment by praveenkumar** [comment]
Closing this since it was a network issue and fixed by applying the nameserver.
