### ISSUE TITLE
Internet access fail after crc start command

### ISSUE THREAD

**Issue by Dingoldine** [code-ready/crc#1771]
Installing CRC and starting a local cluster on RHEL 8 following the docs disconnects me from the Internet. It seems to be a DNS issue, Internet access is only restored when removing the crc-nm-dnsmasq.conf and crc.conf files in the NetworkManager folder. How do I resolve this issue?

**Comment by guillaumerose** [comment]
Hello @Dingoldine,

We are working on a new network stack to avoid this kind of issue. It's still in beta but you can give it a try.
Please see https://github.com/code-ready/crc/wiki/VPN-support--with-an--userland-network-stack

Thanks!

**Comment by gbraad** [comment]
Too little information to provide help.
Let's see if this works, else add requested info from the template
