### ISSUE TITLE
Dns resolution fails on NetworkManager configured with dns = none

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/crc#1778]
CRC setup override the /etc/resolv.conf on the OS. To use its internal DNS mechanism. 

When finish with CRC and cleanup is executed it is expected that Network Manager re generate the /etc/resolv.conf file to its original state. 

In case Network Manager is configured with option:

```bash
[Main]
dns = none
```

The /etc/resolv.conf is not re generated, so values from crc setup stays on the resolv.conf file and name resolution fails:

```bash
Name or service not known
```

Maybe this configuration should be checked and handled according to it. Or if this is an edge case, maybe some extra information can be added to the documentation to require Network Manager with option dns = default

**Comment by gbraad** [comment]
What was the content of the config before CRC was run? As we should restore the config as it was

**Comment by adrianriobo** [comment]
No config, this was tested on a fresh new installation. Just download crc and setup without any specific config.

**Comment by cfergeau** [comment]
This should not be an issue with usermade networking, which hopefully can become the default relatively soon. Keeping this closed
