### ISSUE TITLE
[BUG] Error running post start: Nameserver not successfully set on interface vEthernet (Default Switch)

### ISSUE THREAD

**Issue by senthilrch** [code-ready/crc#1782]
### General information

  * OS: Windows
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop

## CRC version
```bash
CodeReady Containers version: 1.20.0+ef3f80d
OpenShift version: 4.6.6 (embedded in executable)
```
  
## CRC status
```bash
$ crc status --log-level debug
level=debug msg="CodeReady Containers version: 1.20.0+ef3f80d\n"
level=debug msg="OpenShift version: 4.6.6 (embedded in executable)\n"
Checking file: C:\Users\EECHENS\.crc\machines\crc\.crc-exist
level=debug msg="Copying 'C:\\Users\\EECHENS\\.crc\\cache\\crc_hyperv_4.6.6\\oc.exe' to 'C:\\Users\\EECHENS\\.crc\\bin\\oc\\oc.exe'"
Error getting ip: IP not found
```

## CRC config
```bash
eechens@IN-00240448 MINGW64 ~
$ crc config view

eechens@IN-00240448 MINGW64 ~
```

## Host Operating System
```bash
$ systeminfo

Host Name:                 IN-00240448
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          #####
Registered Organization:   #####
Product ID:                00330-80000-00000-AA584
Original Install Date:     5/6/2020, 10:14:11 AM
System Boot Time:          12/16/2020, 10:56:10 AM
System Manufacturer:       HP
System Model:              HP EliteBook 840 G5
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 142 Stepping 10 GenuineIntel ~1696 Mhz
BIOS Version:              HP Q78 Ver. 01.11.01, 4/27/2020
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi
Total Physical Memory:     16,227 MB
Available Physical Memory: 938 MB
Virtual Memory: Max Size:  18,659 MB
Virtual Memory: Available: 2,816 MB
Virtual Memory: In Use:    15,843 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    #####
Logon Server:              #####
Hotfix(s):                 8 Hotfix(s) Installed.
                           [01]: KB4569776
                           [02]: KB4521862
                           [03]: KB4549947
                           [04]: KB4558997
                           [05]: KB4561600
                           [06]: KB4562562
                           [07]: KB4566424
                           [08]: KB4558998
Network Card(s):           5 NIC(s) Installed.
                           [01]: Intel(R) Ethernet Connection (4) I219-LM
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [02]: Intel(R) Dual Band Wireless-AC 8265
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.43.1
                                 IP address(es)
                                 [01]: 192.168.43.52
                                 [02]: fe80::dcab:cf76:3fed:44a2
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [04]: PANGP Virtual Ethernet Adapter
                                 Connection Name: Ethernet 2
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 100.121.143.205
                           [05]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (Default Switch)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 192.168.41.209
                                 [02]: fe80::60dd:18da:1419:3642
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

```

### Steps to reproduce

  1.  crc setup (successful)
  2.  crc start (error)

### Expected
crc start should complete successfully

### Actual
crc start throws following error:-
Error running post start: Nameserver fe80::215:5dff:fea4:a902 not successfully set on interface vEthernet (Default Switch)

### Logs
[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM crc ).networkadapters[0]).ipaddresses[0]
[stdout =====>] : fe80::215:5dff:fea4:a902

[stderr =====>] :
level=debug msg="Waiting until ssh is available"
level=debug msg="retry loop: attempt 0"
level=debug msg="About to run SSH command:\nexit 0"
level=debug msg="SSH command results: err: dial tcp [fe80::215:5dff:fea4:a902]:22: connectex: No connection could be made because the target machine actively refused it., output: "
level=debug msg="error: Temporary error: ssh command error:\ncommand : exit 0\nerr     : dial tcp [fe80::215:5dff:fea4:a902]:22: connectex: No connection could be made because the target machine actively refused it.\noutput  :  - sleeping 1s"
level=debug msg="retry loop: attempt 1"
level=debug msg="About to run SSH command:\nexit 0"
level=debug msg="SSH command results: err: dial tcp [fe80::215:5dff:fea4:a902]:22: connectex: No connection could be made because the target machine actively refused it., output: "
level=debug msg="error: Temporary error: ssh command error:\ncommand : exit 0\nerr     : dial tcp [fe80::215:5dff:fea4:a902]:22: connectex: No connection could be made because the target machine actively refused it.\noutput  :  - sleeping 1s"
level=debug msg="retry loop: attempt 2"
level=debug msg="About to run SSH command:\nexit 0"
level=debug msg="SSH command results: err: dial tcp [fe80::215:5dff:fea4:a902]:22: connectex: No connection could be made because the target machine actively refused it., output: "
level=debug msg="error: Temporary error: ssh command error:\ncommand : exit 0\nerr     : dial tcp [fe80::215:5dff:fea4:a902]:22: connectex: No connection could be made because the target machine actively refused it.\noutput  :  - sleeping 1s"
level=debug msg="retry loop: attempt 3"
level=debug msg="About to run SSH command:\nexit 0"
level=debug msg="SSH command results: err: dial tcp [fe80::215:5dff:fea4:a902]:22: connectex: No connection could be made because the target machine actively refused it., output: "
level=debug msg="error: Temporary error: ssh command error:\ncommand : exit 0\nerr     : dial tcp [fe80::215:5dff:fea4:a902]:22: connectex: No connection could be made because the target machine actively refused it.\noutput  :  - sleeping 1s"
level=debug msg="retry loop: attempt 4"
level=debug msg="About to run SSH command:\nexit 0"
level=debug msg="SSH command results: err: dial tcp [fe80::215:5dff:fea4:a902]:22: connectex: No connection could be made because the target machine actively refused it., output: "
level=debug msg="error: Temporary error: ssh command error:\ncommand : exit 0\nerr     : dial tcp [fe80::215:5dff:fea4:a902]:22: connectex: No connection could be made because the target machine actively refused it.\noutput  :  - sleeping 1s"
level=debug msg="retry loop: attempt 5"
level=debug msg="About to run SSH command:\nexit 0"
level=debug msg="SSH command results: err: dial tcp [fe80::215:5dff:fea4:a902]:22: connectex: No connection could be made because the target machine actively refused it., output: "
level=debug msg="error: Temporary error: ssh command error:\ncommand : exit 0\nerr     : dial tcp [fe80::215:5dff:fea4:a902]:22: connectex: No connection could be made because the target machine actively refused it.\noutput  :  - sleeping 1s"
level=debug msg="retry loop: attempt 6"
level=debug msg="About to run SSH command:\nexit 0"
level=debug msg="SSH command results: err: dial tcp [fe80::215:5dff:fea4:a902]:22: connectex: No connection could be made because the target machine actively refused it., output: "
level=debug msg="error: Temporary error: ssh command error:\ncommand : exit 0\nerr     : dial tcp [fe80::215:5dff:fea4:a902]:22: connectex: No connection could be made because the target machine actively refused it.\noutput  :  - sleeping 1s"
level=debug msg="retry loop: attempt 7"
level=debug msg="About to run SSH command:\nexit 0"
level=debug msg="SSH command results: err: dial tcp [fe80::215:5dff:fea4:a902]:22: connectex: No connection could be made because the target machine actively refused it., output: "
level=debug msg="error: Temporary error: ssh command error:\ncommand : exit 0\nerr     : dial tcp [fe80::215:5dff:fea4:a902]:22: connectex: No connection could be made because the target machine actively refused it.\noutput  :  - sleeping 1s"
level=debug msg="retry loop: attempt 8"
level=debug msg="About to run SSH command:\nexit 0"
level=debug msg="SSH command results: err: dial tcp [fe80::215:5dff:fea4:a902]:22: connectex: No connection could be made because the target machine actively refused it., output: "
level=debug msg="error: Temporary error: ssh command error:\ncommand : exit 0\nerr     : dial tcp [fe80::215:5dff:fea4:a902]:22: connectex: No connection could be made because the target machine actively refused it.\noutput  :  - sleeping 1s"
level=debug msg="retry loop: attempt 9"
level=debug msg="About to run SSH command:\nexit 0"
level=debug msg="SSH command results: err: dial tcp [fe80::215:5dff:fea4:a902]:22: connectex: No connection could be made because the target machine actively refused it., output: "
level=debug msg="error: Temporary error: ssh command error:\ncommand : exit 0\nerr     : dial tcp [fe80::215:5dff:fea4:a902]:22: connectex: No connection could be made because the target machine actively refused it.\noutput  :  - sleeping 1s"
level=debug msg="retry loop: attempt 10"
level=debug msg="About to run SSH command:\nexit 0"
level=debug msg="SSH command results: err: dial tcp [fe80::215:5dff:fea4:a902]:22: connectex: No connection could be made because the target machine actively refused it., output: "
level=debug msg="error: Temporary error: ssh command error:\ncommand : exit 0\nerr     : dial tcp [fe80::215:5dff:fea4:a902]:22: connectex: No connection could be made because the target machine actively refused it.\noutput  :  - sleeping 1s"
level=debug msg="retry loop: attempt 11"
level=debug msg="About to run SSH command:\nexit 0"
level=debug msg="SSH command results: err: dial tcp [fe80::215:5dff:fea4:a902]:22: connectex: No connection could be made because the target machine actively refused it., output: "
level=debug msg="error: Temporary error: ssh command error:\ncommand : exit 0\nerr     : dial tcp [fe80::215:5dff:fea4:a902]:22: connectex: No connection could be made because the target machine actively refused it.\noutput  :  - sleeping 1s"
level=debug msg="retry loop: attempt 12"
level=debug msg="About to run SSH command:\nexit 0"
level=debug msg="SSH command results: err: dial tcp [fe80::215:5dff:fea4:a902]:22: connectex: No connection could be made because the target machine actively refused it., output: "
level=debug msg="error: Temporary error: ssh command error:\ncommand : exit 0\nerr     : dial tcp [fe80::215:5dff:fea4:a902]:22: connectex: No connection could be made because the target machine actively refused it.\noutput  :  - sleeping 1s"
level=debug msg="retry loop: attempt 13"
level=debug msg="About to run SSH command:\nexit 0"
level=debug msg="SSH command results: err: <nil>, output: "
level=info msg="CodeReady Containers VM is running"
level=debug msg="About to run SSH command:\ncat /home/core/.ssh/authorized_keys"
level=debug msg="SSH command results: err: <nil>, output: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDhRxUeUvpJJkk340Cakz/tAWLyQHe3wdc90ehJ1ly0ZrL0WHgaFi2qAxvyll0EPBkv6dSxFdy1qYTIghErJQCkVa0diE2lGx/7ox+O9rDV8l8V4Q4Qt/9vC1Y2JzRLJFVdj7a/eU6ldDrrxsNBIvpP5MVVVlLYYJ7em4IFYJHQcVSA3G6gQmddxHwynsMkMBJF6EjynC7gVxbsYjkWWcyV6E3WNJuEZU8it3e2vJFG1MQUIoJESSOTs7PQbj++vXSEbl3a7iu+QJ8fmg2vHMRw5bOE5c3j0A582n1hDCsZN5xvwqS19MqDx/bowTknHp4ZD6El7N5XTr7AXkIidhyT\n\n"
level=debug msg="About to run SSH command:\nsudo xfs_growfs / >/dev/null"
level=debug msg="SSH command results: err: <nil>, output: "
level=info msg="Starting network time synchronization in CodeReady Containers VM"
level=debug msg="About to run SSH command:\nsudo timedatectl set-ntp on"
level=debug msg="SSH command results: err: <nil>, output: "
level=debug msg="Creating /var/srv/dnsmasq.conf with permissions 0644 in the CRC VM"
level=debug msg="About to run SSH command with hidden output"
level=debug msg="SSH command succeeded"
level=debug msg="About to run SSH command:\nsudo podman rm -f dnsmasq"
level=debug msg="SSH command results: err: <nil>, output: 38ba28a1a0ffa281808c41b4b5f8d3dc3b6dcab7047ccee403414ad78ca0da70\n"
level=debug msg="About to run SSH command:\nsudo rm -f /var/lib/cni/networks/podman/10.88.0.8"
level=debug msg="SSH command results: err: <nil>, output: "
level=debug msg="About to run SSH command:\nsudo podman run  --ip 10.88.0.8 --name dnsmasq -v /var/srv/dnsmasq.conf:/etc/dnsmasq.conf -p 53:53/udp --privileged -d quay.io/crcont/dnsmasq:latest"
level=debug msg="SSH command results: err: <nil>, output: 0e91062d592c28f0943217fe32547d9d87b423d5458b52d617d35e1f96993bd5\n"
level=info msg="Will run as admin: add dns server address to interface vEthernet (Default Switch)"
Error running post start: Nameserver fe80::215:5dff:fea4:a902 not successfully set on interface vEthernet (Default Switch)

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by adrianriobo** [comment]
The problem is related with the  Ipv6 for the VM:

```bash
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM crc ).networkadapters[0]).ipaddresses[0]
[stdout =====>] : fe80::215:5dff:fea4:a902
```

It is not a bug on CRC, but rather the behaviour of a library we use. You can get more information and possible workarounds on this [related issue](https://github.com/code-ready/crc/issues/784#issuecomment-555423879)

**Comment by gbraad** [comment]
we will look into this at some point, but it mght help to disable IPv6 for now.
if not, you can create an override `crc` network (but the requirements are steeper due to relyng on external DHCP).

You could try: https://github.com/code-ready/crc/wiki/VPN-support--with-an--userland-network-stack, experimental but VERY appreciated as it might resolve this without disabling IPv4 or using an overide switch.

**Comment by cameronkerrnz** [comment]
I suspect that this issue is caused by trying to ssh to a link-local address without using an IPv6 scope identifier (without it, the OS has no idea which interface to send the message out of, as the address could be valid on any interface.

```
time="2021-04-01T22:01:29+13:00" level=debug msg="[executing ==>] : C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -NoProfile -NonInteractive (( Hyper-V\\Get-VM crc ).networkadapters[0]).ipaddresses[0]"
time="2021-04-01T22:01:31+13:00" level=debug msg="[stdout =====>] : fe80::2936:1b72:5489:f365\r"
...
time="2021-04-01T22:01:41+13:00" level=debug msg="SSH command results: err: dial tcp [fe80::2936:1b72:5489:f365]:22: i/o timeout, output: "
time="2021-04-01T22:01:41+13:00" level=debug msg="error: Temporary error: ssh command error:\ncommand : exit 0\nerr     : dial tcp [fe80::2936:1b72:5489:f365]:22: i/o timeout\\n - sleeping 1s"
```

From my ipconfig /all

```
Ethernet adapter vEthernet (Default Switch):

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter
   Physical Address. . . . . . . . . : 00-15-5D-AD-35-B2
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::95ff:b655:3f8d:1d04%32(Preferred)
   IPv4 Address. . . . . . . . . . . : 192.168.144.1(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :
   DHCPv6 IAID . . . . . . . . . . . : 536876381
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-27-9B-DC-A6-74-78-27-3B-19-72
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Enabled
```

The scope ID on this interface is 32, as can more easily be seen from get-netadapter (the ifIndex column)

```
PS C:\WINDOWS\system32> Get-NetAdapter

Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
Ethernet 4                Cisco AnyConnect Secure Mobility Cli...      55 Disabled     00-05-9A-3C-7A-00        10 Mbps
Bluetooth Network Conn... Bluetooth Device (Personal Area Netw...      22 Disconnected 68-3E-26-08-A4-AC         3 Mbps
vEthernet (WSL)           Hyper-V Virtual Ethernet Adapter #2          54 Up           00-15-5D-11-E8-30        10 Gbps
vEthernet (Default Swi... Hyper-V Virtual Ethernet Adapter             32 Up           00-15-5D-AD-35-B2        10 Gbps
Wi-Fi                     Intel(R) Wi-Fi 6 AX201 160MHz                14 Up           68-3E-26-08-A4-A8       780 Mbps
Ethernet                  Intel(R) Ethernet Connection (11) I2...      11 Disconnected 74-78-27-3B-19-72          0 bps
```

So that SSH connection attempt should look like the following:

dial tcp [fe80::2936:1b72:5489:f365%32]:22

In Linux, we would see the interface name after the %, but in Windows its the interface index.
