### ISSUE TITLE
[Integration Test] Invalid syntax on story health for windows

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/crc#1785]
There is syntax issue on windows for Scenario: Create and test app. In this scenario a rollout status is execute with:

```bash
oc rollout status dc/httpd-example || oc rollout status deployment httpd-example
```

This conditional composition of commands with || is valid syntax for bash based shells but not for powershell (5.1):

```
The token '||' is not a valid statement separator in this version
```

In these commands deploymentconfig and deployment rollouts are checked. But checking the httpd-example [template](https://github.com/sclorg/httpd-ex/blob/master/openshift/templates/httpd.json) 
only deploymentconfig is created

Before this [commit](https://github.com/code-ready/crc/commit/16d015a9e978c4a2b63b1b22b8e8677298afe52a) only deploymentconfig was checked. Then it was changed to deployment as from commits comments: newer oc versions change deploymentconfig into deployment when mapping from github. 

Then this [commit](https://github.com/code-ready/crc/commit/928a8a092e0ce2d02d5e9fa48e32ade62fb320b5) 
include both (with the current or syntax), as it seems oc creates deploymentconfig as expected. Only noticeable thing is, first commit seems based on a nightly build and all newer stable oc versions tested only creates deploymentconfig.

To solve this problem:

1. Just remove deployment rollout status part (as it should not exist any deployment). If that is the case is oc working properly?, as deployment is preferred instead of dc but their behaviour is distinct, so if the user expects a dc, does it make sense to have a deployment instead?. (Proposed solution)

2. Create an specific scenario for Windows with bot commands executed separately.

**Comment by adrianriobo** [comment]
As @praveenkumar suggested other option, even better, is to move away from deploy a new app based on an external sample and deploy our own resources.

**Comment by jsliacan** [comment]
That might have the downside of not being a likely user story (since the user won't deploy exactly the same thing as we would)?

**Comment by adrianriobo** [comment]
Define a set of resources to deploy an app on ocp is a user story, no matter if the manifests are made by you or picked from the sample template, actually this could be as simple as grab the current template and add it as a test resource. This way we ensure the exact elements which will be created in the cluster ... in this case only the deploymentconfig
