### ISSUE TITLE
crc start command hangs when crc is restarted a second time 

### ISSUE THREAD

**Issue by jtarte** [code-ready/crc#1790]
### General information

  * OS:  macOS 11.1 (BigSur)
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop 

## CRC version
```
CodeReady Containers version: 1.20.0+ef3f80d
OpenShift version: 4.6.6 (embedded in executable)
```
  
## CRC status
```
DEBU CodeReady Containers version: 1.20.0+ef3f80d 
DEBU OpenShift version: 4.6.6 (embedded in executable) 
Checking file: /Users/jtarte/.crc/machines/crc/.crc-exist
DEBU About to run SSH command:
df -B1 --output=size,used,target /sysroot | tail -1 
DEBU SSH command results: err: <nil>, output: 32720793600 11562704896 /sysroot 
DEBU About to run SSH command with hidden output  
DEBU SSH command failed                           
DEBU cannot get OpenShift status: ssh command error:
command : oc get co -ojson --context admin --cluster crc --kubeconfig /opt/kubeconfig
err     : Process exited with status 1
output  :  
CRC VM:          Running
OpenShift:       Not Reachable (v4.6.6)
Disk Usage:      11.56GB of 32.72GB (Inside the CRC VM)
Cache Usage:     13.87GB
Cache Directory: /Users/jtarte/.crc/cache
```

## CRC config
```
- cpus                                  : 6
- memory                                : 16384
- nameserver                            : 8.8.8.8
- pull-secret-file                      : /Users/jtarte/case_lab/crc/crc42-pull-secret.txt
```

## Host Operating System
```
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69
```

### Steps to reproduce

  1. crc setup
  2. crc start -log-level debug
  wait the env is running and OCP accepts connection
  3. crc stop
  4. crc start -log-level debug

### Expected
having a env up and running

### Actual
The environ is blocked
console output shows:
```
DEBU CodeReady Containers version: 1.20.0+ef3f80d 
DEBU OpenShift version: 4.6.6 (embedded in executable) 
DEBU Total memory of system is 34359738368 bytes  
DEBU No new version available. The latest version is 1.20.0 
INFO Checking if podman remote executable is cached 
DEBU Currently podman remote is not supported     
INFO Checking if goodhosts executable is cached   
DEBU goodhost executable already cached           
INFO Checking minimum RAM requirements            
DEBU Total memory of system is 34359738368 bytes  
INFO Checking if running as non-root              
INFO Checking if HyperKit is installed            
DEBU Running '/Users/jtarte/.crc/bin/hyperkit -v' 
DEBU Found hyperkit version v0.20200224-44-gb54460 
INFO Checking if crc-driver-hyperkit is installed 
DEBU Checking if crc-driver-hyperkit is installed 
DEBU Running '/Users/jtarte/.crc/bin/crc-driver-hyperkit version' 
DEBU Found crc-driver-hyperkit version 0.12.10    
INFO Checking file permissions for /etc/hosts     
DEBU Checking if /etc/hosts ownership/permissions need to be adjusted after crc upgrade 
INFO Checking file permissions for /etc/resolver/testing 
Checking file: /Users/jtarte/.crc/machines/crc/.crc-exist
Found binary path at /Users/jtarte/.crc/bin/crc-driver-hyperkit
Launching plugin server for driver hyperkit
Plugin server listening at address 127.0.0.1:63244
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(crc) Calling .GetBundleName
(crc) Calling .GetState
(crc) DBG | exe=/Users/jtarte/.crc/bin/crc-driver-hyperkit uid=0
(crc) DBG | hyperkit pid from json: 35616
(crc) DBG | hyperkit pid 35616 missing from process table
INFO Starting CodeReady Containers VM for OpenShift 4.6.6... 
DEBU Updating CRC VM configuration                
(crc) Calling .GetConfigRaw
(crc) Calling .Start
(crc) DBG | exe=/Users/jtarte/.crc/bin/crc-driver-hyperkit uid=0
(crc) DBG | clean start, hyperkit pid file doesn't exist: /Users/jtarte/.crc/machines/crc/hyperkit.pid
(crc) DBG | Using hyperkit binary from /Users/jtarte/.crc/bin/hyperkit
(crc) DBG | Using UUID c3d68012-0208-11ea-9fd7-f2189899ab08
(crc) DBG | Generated MAC e:f0:e3:c7:4f:be
(crc) DBG | Starting with cmdline: BOOT_IMAGE=(hd0,gpt1)/ostree/rhcos-8788e016f1c002b53aed3f47bbfc2f191e6706085f0aa825fd533ff28a7f14b7/vmlinuz-4.18.0-193.29.1.el8_2.x86_64 rhcos.root=crypt_rootfs random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu rd.luks.options=discard ostree=/ostree/boot.1/rhcos/8788e016f1c002b53aed3f47bbfc2f191e6706085f0aa825fd533ff28a7f14b7/0
(crc) DBG | Trying to execute /Users/jtarte/.crc/bin/hyperkit -A -u -F /Users/jtarte/.crc/machines/crc/hyperkit.pid -c 6 -m 16384M -s 0:0,hostbridge -s 31,lpc -s 1:0,virtio-net -U c3d68012-0208-11ea-9fd7-f2189899ab08 -s 2:0,virtio-blk,file:///Users/jtarte/.crc/machines/crc/crc.qcow2,format=qcow -s 3,virtio-sock,guest_cid=3,path=/Users/jtarte/.crc/machines/crc -s 4,virtio-rnd -l com1,autopty=/Users/jtarte/.crc/machines/crc/tty,log=/Users/jtarte/.crc/machines/crc/console-ring -f kexec,/Users/jtarte/.crc/cache/crc_hyperkit_4.6.6/vmlinuz-4.18.0-193.29.1.el8_2.x86_64,/Users/jtarte/.crc/cache/crc_hyperkit_4.6.6/initramfs-4.18.0-193.29.1.el8_2.x86_64.img,earlyprintk=serial BOOT_IMAGE=(hd0,gpt1)/ostree/rhcos-8788e016f1c002b53aed3f47bbfc2f191e6706085f0aa825fd533ff28a7f14b7/vmlinuz-4.18.0-193.29.1.el8_2.x86_64 rhcos.root=crypt_rootfs random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu rd.luks.options=discard ostree=/ostree/boot.1/rhcos/8788e016f1c002b53aed3f47bbfc2f191e6706085f0aa825fd533ff28a7f14b7/0
(crc) DBG | exe=/Users/jtarte/.crc/bin/crc-driver-hyperkit uid=0
(crc) DBG | hyperkit pid from json: 35953
(crc) DBG | Searching for e:f0:e3:c7:4f:be in /var/db/dhcpd_leases ...
(crc) DBG | Found 1 entries in /var/db/dhcpd_leases!
(crc) DBG | dhcp entry: {Name:crc-fdm75-master-0 IPAddress:192.168.64.2 HWAddress:e:f0:e3:c7:4f:be ID:1,e:f0:e3:c7:4f:be Lease:0x5fde336a}
(crc) DBG | Found match: e:f0:e3:c7:4f:be
(crc) DBG | IP: 192.168.64.2
(crc) Calling .GetState
(crc) DBG | exe=/Users/jtarte/.crc/bin/crc-driver-hyperkit uid=0
(crc) DBG | hyperkit pid from json: 35953
(crc) Calling .GetIP
DEBU Waiting until ssh is available               
DEBU retry loop: attempt 0                        
DEBU About to run SSH command:
exit 0             
DEBU SSH command results: err: <nil>, output:     
INFO CodeReady Containers VM is running           
DEBU About to run SSH command:
cat /home/core/.ssh/authorized_keys 
DEBU SSH command results: err: <nil>, output: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIMV5MoyWwa0ccSJGs3+rgAkstpHAkBoLinSTFcq0phLVuL3EjmE0U7OX28CPtqGDZ26lf86ElgJs7Jj61dG3gLcbm1/RYy3q+nAjQyt8REuKaczPOqGaBKyxhF+DR5qZufzSkYLjH9QE8sAxNhqmfLe2R33NWqstIx9ZuWrzvNsCA/4t4Wjv4u+EErg2VqH4IRo8tkiD4Krx9skHkwrSrApwwFiKiDnlWHIyDfzB/MMELwhZ99/YuBUlsWPSLHSErv2k4WNxnsOe2jB7ZKDNtFQ4psB5CH10PY9Qh/Wdaz69pryNppBcMYuLrqa5WpFgiXcwIN0c1uVK1wjtsFk7v
 
DEBU About to run SSH command:
sudo xfs_growfs / >/dev/null 
DEBU SSH command results: err: <nil>, output:     
INFO Starting network time synchronization in CodeReady Containers VM 
DEBU About to run SSH command:
sudo timedatectl set-ntp on 
DEBU SSH command results: err: <nil>, output:     
DEBU About to run SSH command:
cat /etc/resolv.conf 
DEBU SSH command results: err: <nil>, output: # Generated by NetworkManager
nameserver 192.168.64.1 
INFO Adding 8.8.8.8 as nameserver to the instance ... 
DEBU About to run SSH command:
NS=8.8.8.8; cat /etc/resolv.conf |grep -i "^nameserver $NS" || echo "nameserver $NS" | sudo tee -a /etc/resolv.conf 
DEBU SSH command results: err: <nil>, output: nameserver 8.8.8.8 
DEBU Creating /var/srv/dnsmasq.conf with permissions 0644 in the CRC VM 
DEBU About to run SSH command with hidden output  
DEBU SSH command succeeded                        
DEBU About to run SSH command:
sudo podman rm -f dnsmasq 
DEBU SSH command results: err: <nil>, output: bfde0a89bc7cdaf31bd5034fc6025614d167fffebd14b1b700747c62a97ff9ff 
DEBU About to run SSH command:
sudo rm -f /var/lib/cni/networks/podman/10.88.0.8 
DEBU SSH command results: err: <nil>, output:     
DEBU About to run SSH command:
sudo podman run  --ip 10.88.0.8 --name dnsmasq -v /var/srv/dnsmasq.conf:/etc/dnsmasq.conf -p 53:53/udp --privileged -d quay.io/crcont/dnsmasq:latest 
DEBU SSH command results: err: <nil>, output: 83b0477daec6de7f6dc2e7222a88ace4fceaf91d064792d1e874b9ea2dc3a9f8 
DEBU Running '/Users/jtarte/.crc/bin/goodhosts rm api.crc.testing oauth-openshift.apps-crc.testing console-openshift-console.apps-crc.testing default-route-openshift-image-registry.apps-crc.testing' 
DEBU Running '/Users/jtarte/.crc/bin/goodhosts add 192.168.64.2 api.crc.testing oauth-openshift.apps-crc.testing console-openshift-console.apps-crc.testing default-route-openshift-image-registry.apps-crc.testing' 
INFO Network restart not needed                   
DEBU About to run SSH command:
cat /etc/resolv.conf 
DEBU SSH command results: err: <nil>, output: # Generated by NetworkManager
nameserver 192.168.64.1
nameserver 8.8.8.8 
DEBU Creating /etc/resolv.conf with permissions 0644 in the CRC VM 
DEBU About to run SSH command with hidden output  
DEBU SSH command succeeded                        
DEBU retry loop: attempt 0                        
DEBU About to run SSH command:
host -R 3 foo.apps-crc.testing 
```

crc.logs shows
```
time="2020-12-18T18:21:53+01:00" level=debug msg="About to run SSH command with hidden output"
time="2020-12-18T18:21:53+01:00" level=debug msg="SSH command succeeded"
time="2020-12-18T18:21:53+01:00" level=debug msg="retry loop: attempt 0"
time="2020-12-18T18:21:53+01:00" level=debug msg="About to run SSH command:\nhost -R 3 foo.apps-crc.testing"
```

### Logs
[crc.log](https://github.com/code-ready/crc/files/5717122/crc.log)

**Comment by gbraad** [comment]
SSH to the VM seems to fail. perhaps not picking up the pivoted key?

**Comment by anjannath** [comment]
The logs seems to be incomplete, the second `crc start` stops abruptly according to the logs.. 

```
time="2020-12-18T18:21:53+01:00" level=debug msg="SSH command results: err: <nil>, output: # Generated by NetworkManager\nnameserver 192.168.64.1\nnameserver 8.8.8.8"
time="2020-12-18T18:21:53+01:00" level=debug msg="Creating /etc/resolv.conf with permissions 0644 in the CRC VM"
time="2020-12-18T18:21:53+01:00" level=debug msg="About to run SSH command with hidden output"
time="2020-12-18T18:21:53+01:00" level=debug msg="SSH command succeeded"
time="2020-12-18T18:21:53+01:00" level=debug msg="retry loop: attempt 0"
time="2020-12-18T18:21:53+01:00" level=debug msg="About to run SSH command:\nhost -R 3 foo.apps-crc.testing"
```

**Comment by jtarte** [comment]
Hi, I reproduced the incident in order to capture better logs

starting point : clean environment, no machine defined.

1) crc setup
2) crc start --log-level debug
The console output is captured in this file:
[crc_start_console_output_run1.log](https://github.com/code-ready/crc/files/5724304/crc_start_console_output_run1.log)

3) login into the cluster.

4) crc stop
5) crc status (the VM is stopped)

6) 2) crc start --log-level debug
[crc_start_console_output_run2.log](https://github.com/code-ready/crc/files/5724310/crc_start_console_output_run2.log)

The second start freezes.

Here is the crc.log file from .crc directory
[crc.log](https://github.com/code-ready/crc/files/5724314/crc.log)

**Comment by gbraad** [comment]
in the second run it started the VM, and then performs the network checks for resolving:

```
DEBU SSH command results: err: <nil>, output: # Generated by NetworkManager
nameserver 192.168.64.1
nameserver 8.8.8.8
DEBU Creating /etc/resolv.conf with permissions 0644 in the CRC VM
DEBU About to run SSH command with hidden output
DEBU SSH command succeeded
DEBU retry loop: attempt 0
DEBU About to run SSH command:
host -R 3 foo.apps-crc.testing 
```

and then nothing happens... like, it just hangs? How long have you waited?

**Comment by gbraad** [comment]
What is the result of

```
$ host -R 3 foo.apps-crc.testing
```

on the host?

**Comment by jtarte** [comment]
Today, I waited more than 10 min. During this time period, nothing happened.

Regarding the command result:
```
jtarte@Jeromes-MacBook-Pro-2 .crc % host -R 3 foo.apps-crc.testing
Host foo.apps-crc.testing not found: 3(NXDOMAIN)
jtarte@Jeromes-MacBook-Pro-2 .crc % 
```

**Comment by gbraad** [comment]
what about:

```
$ dig foo.apps-crc.testing @`crc ip`
```

**Comment by jtarte** [comment]
```
jtarte@Jeromes-MacBook-Pro-2 .crc % dig foo.apps-crc.testing @`crc ip`

; <<>> DiG 9.10.6 <<>> foo.apps-crc.testing @192.168.64.2
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 749
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;foo.apps-crc.testing.		IN	A

;; ANSWER SECTION:
foo.apps-crc.testing.	0	IN	A	192.168.64.2

;; Query time: 39 msec
;; SERVER: 192.168.64.2#53(192.168.64.2)
;; WHEN: Mon Dec 21 14:11:56 CET 2020
;; MSG SIZE  rcvd: 54

jtarte@Jeromes-MacBook-Pro-2 .crc %
```

**Comment by gbraad** [comment]
```
$ ssh -i ~/.crc/machines/crc/crc_id_rsa core@192.168.64.2
$ host -R 3 foo.apps-crc.testing
```

Note: I am not sure about the key name `crc_id_rsa`, but this is what I recall now. let me know the results

**Comment by jtarte** [comment]
I'm not able to ssh the vm 
```
jtarte@Jeromes-MacBook-Pro-2 .crc % ssh -i ~/.crc/machines/crc/crc_id_rsa core@192.168.64.2
Warning: Identity file /Users/jtarte/.crc/machines/crc/crc_id_rsa not accessible: No such file or directory.
The authenticity of host '192.168.64.2 (192.168.64.2)' can't be established.
ECDSA key fingerprint is SHA256:6PwPkP84274nGcSSGdUlSdJgXLGSj+/tnApqr3V2xdU.
Are you sure you want to continue connecting (yes/no/[fingerprint])? y
Please type 'yes', 'no' or the fingerprint: yes
Warning: Permanently added '192.168.64.2' (ECDSA) to the list of known hosts.
core@192.168.64.2: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
jtarte@Jeromes-MacBook-Pro-2 .crc % 
```

**Comment by gbraad** [comment]
```
Warning: Identity file /Users/jtarte/.crc/machines/crc/crc_id_rsa not accessible: No such file or directory.
```

```
$ ls /Users/jtarte/.crc/machines/crc/
```

Check for the name of the file... might wrote it wrong. not behind a keyboard now

**Comment by jtarte** [comment]
```
jtarte@Jeromes-MacBook-Pro-2 ~ % ls -al /Users/jtarte/.crc/machines/crc/
total 26817128
drwx------  13 jtarte  staff          416 Dec 21 13:59 .
drwx------   3 jtarte  staff           96 Dec 21 13:20 ..
-rw-r--r--   1 jtarte  staff            0 Dec 21 13:20 .crc-exist
-rw-------   1 jtarte  staff         2277 Dec 21 13:59 config.json
srwxr-xr-x   1 root    staff            0 Dec 21 13:59 connect
-rw-r--r--   1 root    staff        65536 Dec 21 13:59 console-ring
-rw-r--r--   1 root    staff  13754368000 Dec 21 14:24 crc.qcow2
-rw-r--r--   1 root    staff         2751 Dec 21 13:59 hyperkit.json
-rw-r--r--   1 root    staff            5 Dec 21 13:59 hyperkit.pid
-rw-------   1 jtarte  staff         1679 Dec 21 13:21 id_rsa
-rw-------   1 jtarte  staff          381 Dec 21 13:21 id_rsa.pub
-rw-r--r--   1 jtarte  staff        15215 Dec 21 13:21 kubeconfig
-rw-r--r--   1 root    staff           12 Dec 21 13:59 tty
jtarte@Jeromes-MacBook-Pro-2 ~ %
```

**Comment by gbraad** [comment]
```
$ ssh -i ~/.crc/machines/crc/id_rsa core@192.168.64.2
$ host -R 3 foo.apps-crc.testing     # in the VM
```

**Comment by jtarte** [comment]
```
jtarte@Jeromes-MacBook-Pro-2 ~ % ssh -i ~/.crc/machines/crc/id_rsa core@192.168.64.2 
Red Hat Enterprise Linux CoreOS 46.82.202011210620-0
  Part of OpenShift 4.6, RHCOS is a Kubernetes native operating system
  managed by the Machine Config Operator (`clusteroperator/machine-config`).

WARNING: Direct SSH access to machines is not recommended; instead,
make configuration changes via `machineconfig` objects:
  https://docs.openshift.com/container-platform/4.6/architecture/architecture-rhcos.html

---
[core@crc-fdm75-master-0 ~]$ host -R 3 foo.apps-crc.testing
foo.apps-crc.testing has address 192.168.64.2
[core@crc-fdm75-master-0 ~]$
```

**Comment by gbraad** [comment]
So the actual check and DNS is responsive
```
[core@crc-fdm75-master-0 ~]$ host -R 3 foo.apps-crc.testing
foo.apps-crc.testing has address 192.168.64.2
[core@crc-fdm75-master-0 ~]$
```
so not sure what makes it hang

**Comment by jtarte** [comment]
<img width="588" alt="Screenshot 2020-12-21 at 14 33 00" src="https://user-images.githubusercontent.com/14808115/102782355-82e47680-4399-11eb-8471-07d43bdb51a4.png">

**Comment by gbraad** [comment]
what shell are you using... ?
something seems off...

and this does not happen for a `crc start; crc delete; crc start` ?

**Comment by jtarte** [comment]
shell is `zsh`(default)

**Comment by jtarte** [comment]
No, with the sequence `crc start`; `crc delete`; `crc start`, I have the same behaviour.

To be able to have a working environment I have to do a `crc cleanup` and `crc setup` after the `crc delete` and before the `crc start`

**Comment by gbraad** [comment]
> `crc cleanup`

this sounds interesting. so this could very well be related to the config files. they have been modified between the sessions.

can you try just running `crc setup --log-level debug` and try to start afterwards

**Comment by praveenkumar** [comment]
I am also using Big Sur and tried the steps which you listed in the issue, didn't able to reproduce the issue :(

```
$ sw_vers 
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69
```

I am using bash but don't think that shell is the issue here.

**Comment by gbraad** [comment]
> I am using bash but don't think that shell is the issue here.

I thought it might he interaction between the `ssh` implementation... but we do not rely on the external client. so this is also a dead-end.

**Comment by jtarte** [comment]
I do the following : 

start with a clean environment

1) crc setup --log-level debug
[crc_setup.log](https://github.com/code-ready/crc/files/5725132/crc_setup.log)

2) crc start --log-level debug 
[crc_start1.log](https://github.com/code-ready/crc/files/5725133/crc_start1.log)

3) login into the cluster : OK

4) crc stop

5)crc setup --log-level debug
[crc_setup2.log](https://github.com/code-ready/crc/files/5725138/crc_setup2.log)

6) crc start --log-level debug 
[crc_start2.log](https://github.com/code-ready/crc/files/5725143/crc_start2.log)

same behaviour. The startup process hangs at the same step.

**Comment by gbraad** [comment]
unable to repro. more information is needed about the setup. especially around networking

**Comment by praveenkumar** [comment]
@jtarte in `crc_start2.log` https://github.com/code-ready/crc/issues/1790#issuecomment-749038608 message I don't see any error message like you described in the issue, here looks like it pass the ssh connection check also.

**Comment by gbraad** [comment]
> I don't see any error message like you described in the issue

Well, @praveenkumar ... that is because there is no error happening ...

> Today, I waited more than 10 min. During this time period, nothing happened.

https://github.com/code-ready/crc/issues/1790#issuecomment-748965417

It is summarized below. for the `host` query:

---

1st time:
```
DEBU SSH command results: err: <nil>, output: foo.apps-crc.testing has address 192.168.64.22nd time:
```

2nd time

    nothing returned ?

---

In other words, it is not clearly observable what causes this, though very likely something network related?

**Comment by jtarte** [comment]
> unable to repro. more information is needed about the setup. especially around networking

@gbraad 
What kind of information are you looking for ?
Say me what you need, I will provide it.

**Comment by gbraad** [comment]
https://github.com/code-ready/crc/issues/1790#issuecomment-749934155 more info around the network setup... like tools installed, VPN, wireless/wired at the same time, etc

also, why is `-n 8.8.8.8` needed? can it run without?

**Comment by jtarte** [comment]
I work at home. The network is my home network. I'm using wireless connection to a WIFI router (Netgear) that is wired to my internet box. I have a fiber internet connection. 

When I work with CRC, no vpn is activated. I saw in the past that when a VPN is up I have trouble with CRC.
On my laptop, I have two VPN, one to my enterprise intranet is Cisco AnyConnect, the second is tunnelblick to access a lab of my team.  But they are not activated when I work with CRC.

I put 8.8.8.8 dns  in my config as in the past I had trouble with CRC instance. I was not able to get the Operator marketplace for example. Since I put 8.8.8.8 in my config it fixed the problem and I am able to get the Operator marketplace. 

In the past, on the same laptop, with earlier version of CRC (1.18 and previous) and Mac OS Catalina, it worked fine, no issues.

The problem occurs since I moved to Mac OS Big Sur and CRC 1.20.

**Comment by guillaumerose** [comment]
@jtarte we worked on a new network stack that might be more robust (not only for VPN support). Can you give it a try: https://github.com/code-ready/crc/wiki/VPN-support--with-an--userland-network-stack ?

**Comment by jtarte** [comment]
@guillaumerose, good catch. I tried the new network stack, it seems to solve my issues. I'm able to stop / restart my instance without problems. I have to do additional tests but it seems working on my environment.

Now, the use of this new network stack generates additional questions:
* as far I understand, this feature is still experimental (alpha). So what is the associated roadmap ?
* Is it possible to run the `crc daemon` process in background rather to have a dedicated window for it ?
* The daemon windows shows a trace with a lot of errors (network errors) but it seems to have no impacts on the behaviour of crc instance
<img width="567" alt="Screenshot 2020-12-29 at 11 12 17" src="https://user-images.githubusercontent.com/14808115/103276420-c016bd00-49c6-11eb-89c6-76f74e27dbde.png">
Do I need to take attention to these errors messages ? or is it regular behaviour that could happen during the startup of the crc instance ?

**Comment by gbraad** [comment]
Note that someone else reported a similar problem with the host check? https://github.com/code-ready/crc/issues/1805#issuecomment-753251617

**Comment by guillaumerose** [comment]
@jtarte thanks for your feedback. 

> as far I understand, this feature is still experimental (alpha). So what is the associated roadmap ?

We released the minimum possible for this network stack to run in order to collect feedback. So far so good, no issues!
Now, we are missing a critical feature: user-created routes are not automatically added in the hosts file. A PR is in progress, it should land in few weeks.
After that, we can advertise this feature a bit more.

Epic: https://github.com/code-ready/crc/issues/1087

> Is it possible to run the crc daemon process in background rather to have a dedicated window for it ?

On Windows/macOS, crc setup with experimental features does that for you automatically. This work is linked to the system tray. It still something in progress. 
For Linux, we have no plan. 

> The daemon windows shows a trace with a lot of errors (network errors) but it seems to have no impacts on the behaviour of crc instance

Yes, this is expected, logs need to be improved. 

First errors are due to crc CLI that tries to connect to the VM (but the VM isn't started yet).
After that, errors are triggered by the embedded gateway. services/pods want to connect to unknown IPs.

**Comment by jtarte** [comment]
I did test with the latest crc release 1.21.
The problem seems to be  removed. 
I was able to start, stop, start , stop, start crc instances without problem. And I could do it without using the daemon. Network mode is the default (not entry in crc.json to put tov sock)

**Comment by cfergeau** [comment]
Closing as per last comment saying 1.21 is working.
