### ISSUE TITLE
Remove embedded bundle status from version

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#1824]
This is the follow up issue for https://github.com/code-ready/crc/pull/1806

We changed the way embedded works and excluded the bundle from the binary.

- It means now shipped tarball consist `crc` binary and the bundle file separately.
- Setup command now don't able to extract the bundle from the binary

With current workflow user (like dev) can use `-b` option and provide the bundle location with crc and it works but this will change the normal crc user habit to just use single binary (embedded everything) and not worry about bundle location.

To overcome this user workflow we can do following and then ask user to use `-b` option.
- If bundle and crc binary is in same directory then use bundle from this directory.
- If user moved the binary but bundle is still in current USER directories we can do a find and try to get the bundle path and use it.

If both doesn't work we prompt user to use the `-b` option.

**Comment by cfergeau** [comment]
> If user moved the binary but bundle is still in current USER directories we can do a find and try to get the bundle path and use it.

I'd prefer not to do this, as this is going to be slow in some cases, and can lead to unexpected results. It's also quite unusual for apps to do this.

**Comment by guillaumerose** [comment]
We should display where the default bundle will be loaded. With the msi and the pkg, it is not obvious.
