### ISSUE TITLE
Error While running " crc start" 

### ISSUE THREAD

**Issue by hebbar25** [code-ready/crc#1828]
Hello Team,

Below is the issue i am facing when i hit "crc start" command. 

I am not sure what exactly causing the issue , your help in this much appriciated

PS C:\Users\hebbar> crc setup
INFO Checking if podman remote executable is cached
INFO Checking if goodhosts executable is cached
INFO Checking if CRC bundle is extracted in '$HOME/.crc'
INFO Checking minimum RAM requirements
INFO Checking if running as normal user
INFO Checking Windows 10 release
INFO Checking Windows edition
INFO Checking if Hyper-V is installed and operational
INFO Checking if user is a member of the Hyper-V Administrators group
INFO Checking if Hyper-V service is enabled
INFO Checking if the Hyper-V virtual switch exist
INFO Found Virtual Switch to use: crc
Setup is complete, you can now run 'crc start' to start the OpenShift cluster
PS C:\Users\hebbar> crc start --log-level debug
DEBU CodeReady Containers version: 1.20.0+ef3f80d
DEBU OpenShift version: 4.6.6 (embedded in executable)
DEBU Total memory of system is 16982306816 bytes
DEBU No new version available. The latest version is 1.20.0
INFO Checking if podman remote executable is cached
DEBU Currently podman remote is not supported
INFO Checking if goodhosts executable is cached
DEBU goodhost executable already cached
INFO Checking minimum RAM requirements
DEBU Total memory of system is 16982306816 bytes
INFO Checking if running as normal user
INFO Checking Windows 10 release
INFO Checking Windows edition
DEBU Running on Windows ServerDatacenter edition
INFO Checking if Hyper-V is installed and operational
INFO Checking if user is a member of the Hyper-V Administrators group
INFO Checking if Hyper-V service is enabled
INFO Checking if the Hyper-V virtual switch exist
INFO Found Virtual Switch to use: crc
Checking file: C:\Users\hebbar\.crc\machines\crc\.crc-exist
? Image pull secret [? for help] ******************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************

DEBU Copying 'C:\Users\hebbar\.crc\cache\crc_hyperv_4.6.6\oc.exe' to 'C:\Users\hebbar\.crc\bin\oc\oc.exe'
INFO Loading bundle: crc_hyperv_4.6.6.crcbundle ...
INFO Verifying bundle crc_hyperv_4.6.6.crcbundle ...
INFO Creating CodeReady Containers VM for OpenShift 4.6.6...
Running pre-create checks...
[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @(Get-Module -ListAvailable hyper-v).Name | Get-Unique
[stdout =====>] : Hyper-V

[stderr =====>] :
[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(([System.Security.Principal.SecurityIdentifier]::new("S-1-5-32-578")))
[stdout =====>] : True

[stderr =====>] :
[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive [Console]::OutputEncoding = [Text.Encoding]::UTF8; (Hyper-V\Get-VMSwitch).Name
[stdout =====>] : crc

[stderr =====>] :
Creating machine...
[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive [Console]::OutputEncoding = [Text.Encoding]::UTF8; (Hyper-V\Get-VMSwitch).Name
[stdout =====>] : crc

[stderr =====>] :
Using switch "crc"
Creating VM...
[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Hyper-V\New-VM crc -Path 'C:\Users\hebbar\.crc\machines\crc' -MemoryStartupBytes 9216MB -SwitchName 'crc'
[stdout =====>] :
Name State CPUUsage(%) MemoryAssigned(M) Uptime   Status             Version
---- ----- ----------- ----------------- ------   ------             -------
crc  Off   0           0                 00:00:00 Operating normally 9.0

[stderr =====>] :
[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Hyper-V\Set-VMMemory -VMName crc -DynamicMemoryEnabled $false
[stdout =====>] :
[stderr =====>] :
[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Hyper-V\Set-VMProcessor crc -Count 4
[stdout =====>] :
[stderr =====>] :
[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Hyper-V\Add-VMHardDiskDrive -VMName crc -Path 'C:\Users\hebbar\.crc\machines\crc\crc.vhdx'
[stdout =====>] :
[stderr =====>] :
Starting VM...
[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Hyper-V\Start-VM crc
[stdout =====>] :
[stderr =====>] : Hyper-V\Start-VM : 'crc' failed to start.
Failed to start the virtual machine 'crc' because one of the Hyper-V components is not running.
'crc' failed to start. (Virtual machine ID 47C1EA83-1393-4D30-88EB-393C57A10038)
The Virtual Machine Management Service failed to start the virtual machine 'crc' because one of the Hyper-V components
is not running (Virtual machine ID 47C1EA83-1393-4D30-88EB-393C57A10038).
At line:1 char:1
+ Hyper-V\Start-VM crc
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OperationFailed,Microsoft.HyperV.PowerShell.Commands.StartVM

Error creating machine: Error creating the VM: Error creating machine: Error in driver during machine creation: exit status 1

**Comment by praveenkumar** [comment]
@hebbar25 Please use provided template to creating a bug report.

**Comment by hebbar25** [comment]
> report

crc start --log-level debug

**Comment by hebbar25** [comment]
@praveenkumar  which template?

**Comment by praveenkumar** [comment]
@hebbar25 when you create a bug report it have predefined template which provide us some more info https://github.com/code-ready/crc/issues/new?assignees=&labels=kind%2Fbug&template=bug_report.md&title=%5BBUG%5D

**Comment by gbraad** [comment]
https://github.com/code-ready/crc/issues/new/choose

**Comment by gbraad** [comment]
though from the error I can see:

```
The Virtual Machine Management Service failed to start the virtual machine 'crc' because one of the Hyper-V components
is not running (Virtual machine ID 47C1EA83-1393-4D30-88EB-393C57A10038).
```

Make sure ALL Hyper-V services are running and available. This does not sound like an issue with CRC, but rather setup or missing services. If you are unsure, remove the Hyper-V support from the "Add or remove optional features" and reinstall. Closing this issue for now, unless more info is added according to the template.
