### ISSUE TITLE
Post-Flight checks before kubelet start

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#184]
As part of the VM bringup, we need to make sure the environment is able to run the OpenShift cluster. However, AFTER the VM bringup, we could still experience issues that are related to other resources, like network connectitivity, disk space, etc. These results can indicate and therefore stop the start of kubelet.

For the current timeframe we need to consider two tests; DNS connectivity:

  * is `crc.testing` and `apps-crc.testing` returning the expected result? If not, this is an `ERROR` and prevents further execution
  * is an external resource, like `...` available? If not, a `WARN` should be given but the kubelet could get started.

If `WARN` we will start the `kubelet` service. Any startup issues have to be caught in that case with a possible status check, like #68. This is not going to be solved in this issue.

**Comment by praveenkumar** [comment]
Done and merged #187
