### ISSUE TITLE
Installation instructions for Linux platforms other than RHEL/Fedora

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#185]
However, ideally to be fixed as part of pre-flight checks, #97, we ,ight have to document in short what steps are needed to make this work on eg. Ubuntu

**Comment by anjannath** [comment]
Should we document this or enhance `crc setup` to handle other distros, for starters..

[ ] Ubuntu
[ ] Arch Linux
[ ] Debian

**Comment by gbraad** [comment]
At the moment we will focus on Ubuntu. We might also need code changes to
deal with skipping these specific distro checks when another distro is used.

I will review this and come up with a possible solution

**Comment by robin-owen** [comment]
Instructions for Ubuntu and Debian should be the same, shouldn't they? Should we instead focus on, for example, Ubuntu and SUSE (widely-used distros with very different package management)?

If we can make the information as generic as reasonably possible, we should be able to cover the most common uses with relatively minimal documentation.

**Comment by gbraad** [comment]
I am considering to use lsb_release to determine the distro used. But yes,
I consider

Ubuntu and SUSE first. Debian and Arch users mostly can handle the use
cases themselves. In code we need to determine the exception and skip these
tests with a INFO or WARN message

**Comment by gbraad** [comment]
Curently we check for `virsh` to be available on path: https://github.com/code-ready/crc/blob/f70e40f45ff6a0e023d7f14add3536712def2768/pkg/crc/preflight/preflight_checks_linux.go#L99 however, the fix https://github.com/code-ready/crc/blob/f70e40f45ff6a0e023d7f14add3536712def2768/pkg/crc/preflight/preflight_checks_linux.go#L116 is not correct as a different set of packages needs to be installed: https://github.com/minishift/minishift/blob/master/docs/source/getting-started/setting-up-virtualization-environment.adoc#on-ubuntu

Ubuntu also uses Systemd, so the check https://github.com/code-ready/crc/blob/f70e40f45ff6a0e023d7f14add3536712def2768/pkg/crc/preflight/preflight_checks_linux.go#L144 applies. Very likely, the check https://github.com/code-ready/crc/blob/f70e40f45ff6a0e023d7f14add3536712def2768/pkg/crc/preflight/preflight_checks_linux.go#L196 is also correct.

However, the group name is `libvirtd` instead of `libvirt`: https://github.com/code-ready/crc/blob/f70e40f45ff6a0e023d7f14add3536712def2768/pkg/crc/preflight/preflight_checks_linux.go#L159

The remaing checks: https://github.com/code-ready/crc/blob/f70e40f45ff6a0e023d7f14add3536712def2768/pkg/crc/preflight/preflight_checks_linux.go#L255, https://github.com/code-ready/crc/blob/f70e40f45ff6a0e023d7f14add3536712def2768/pkg/crc/preflight/preflight_checks_linux.go#L293, https://github.com/code-ready/crc/blob/f70e40f45ff6a0e023d7f14add3536712def2768/pkg/crc/preflight/preflight_checks_linux.go#L361 are also OK.

We need to confirm if https://github.com/code-ready/crc/blob/f70e40f45ff6a0e023d7f14add3536712def2768/pkg/crc/preflight/preflight_checks_linux.go#L438 the DNS overlay gets created using NetworkManager. I would expect this to be different.

**Comment by robin-owen** [comment]
Fixed by #277.
