### ISSUE TITLE
Investigate making use of the new macos Virtualization framework instead of hyperkit

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#1850]
See https://developer.apple.com/documentation/virtualization which provides a native virtualization layer in recent macos version (Big Sur and newer).

Miscellaneous projects making use of it:
 * https://github.com/evansm7/vftool
 * https://github.com/brucehoult/SimpleVM
 * https://github.com/Code-Hex/vz
 * https://github.com/gyf304/vmcli

This will need to be built on a native macOS machine (not different from the current hyperkit machine driver), but hopefully it would be possible to get rid of the out-of-process hyperkit driver, and have something more similar to the hyperv driver.

**Comment by cfergeau** [comment]
Current status: https://github.com/cfergeau/crc/tree/macos-vf can run a podman/openshift VM with user or system networking using virtualization framework. The hyperkit code is removed from this branch.

There is no longer an external machine driver, it's been merged in crc (similar to the hyperv machine driver). This however depends on https://github.com/cfergeau/vfkit which is a very small command line wrapper on top of https://github.com/Code-Hex/vz which are go bindings for the virtualization framework.
vfkit+vz is less than 1000 lines of code but which must still be built on a macOS machine. I don't expect this code to change very often though. crc with the vfkit machine driver code can be cross-built.

This currently depends on qemu-img to be able to reuse the hyperkit bundles. Virtualization framework only supports raw images, so we need to convert the qcow2 in the bundle to a raw image file. Praveen pointed out that `qcow-tool decode` might be usable for this. We already ship `qcow-tool` with hyperkit, so this would be a better alternative.

Using Apple's virtualization framework means that macOS 11 or newer is required.

Next steps for that code in no particular order:
- test/fix on m1 machines
- remove the qemu-img/qcow-tool dependency. This means putting a raw disk image in our bundle, and making sure compression/decompression, file copies, ... all handle sparse files correctly as we don't want to allocate the full 31GB on disk when the space is not used. Disk resizing will need to be reimplemented on top of this
- some more refinement can be done in vfkit (some VM startup errors may not be caught, it should catch signals and then call into virtualization.framework to stop the VM, we can even imagine using a  management socket rather than relying on pid matching and signals, ...)

**Comment by gbraad** [comment]
![image](https://user-images.githubusercontent.com/1894/151661415-6a579be6-5991-47a7-b716-08723ffe2fe5.png)

**Comment by cfergeau** [comment]
> remove the qemu-img/qcow-tool dependency. This means putting a raw disk image in our bundle, and making sure compression/decompression, file copies, ... all handle sparse files correctly as we don't want to allocate the full 31GB on disk when the space is not used. Disk resizing will need to be reimplemented on top of this

The qemu-img/qcow-tool dependency is gone, some  code changes were needed to make sure we generate sparse files when uncompressing the bundle, and the file copy code can be replaced by `unix.CloneFile` to take advantage of copy on write.
Disk resizing is done with `os.Truncate`
