### ISSUE TITLE
Insufficient wait when restarting network on the host

### ISSUE THREAD

**Issue by jsliacan** [code-ready/crc#1854]
### General information

  * OS: macOS
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
CodeReady Containers version: 1.21.0+68a4cdd7
OpenShift version: 4.6.9 (not embedded in executable)
```

## Host Operating System
```bash
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69
```

### Steps to reproduce

  1. `crc setup`
  2. `crc start`

### Expected
No errors.

### Actual
```bash
ERRO Host is not connected to internet
```

### Logs

https://gist.github.com/jsliacan/41d1ae5c1de40de2460d3e72a65dc797

**Comment by jmg421** [comment]
I believe I'm encountering the same issue.

**Comment by guillaumerose** [comment]
Might be fixed by https://github.com/code-ready/crc/pull/2207

**Comment by guillaumerose** [comment]
This is now affecting the legacy network mode. @cfergeau reworked also this part. 
Let's reopen if it happens again.
