### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rkratky** [code-ready/crc#1859]
### General information

Download of the CRC archive takes *very* long. The download speed is limited to about 1 MB/s (my connection averages 30 MB/s elsewhere).

### Steps to reproduce

  1. Start download from https://cloud.redhat.com/openshift/install/crc/installer-provisioned

### Expected

Speedy download.

### Actual

Several hours worth of waiting.

**Comment by cfergeau** [comment]
Clicking on the download link on cloud.redhat.com almost maxes out my 100Mbps connection (getting 11MBps), so this looks like an issue somewhere between cloud.redhat.com and your home.

**Comment by gbraad** [comment]
We are not in control of the CDN; at the mment this is only offered from a single zone.
At the moment they are in the process of allocating an alternative for; odo, crc, and openshift.
Unfortunately not clear when this will be available. Closing this issue as there is not much we can do: "the connection is as fast as the slowest link"

**Comment by guillaumerose** [comment]
Thanks for the report.
This will be fixed with https://github.com/code-ready/crc/issues/1709.
