### ISSUE TITLE
Simplify upgrade flow

### ISSUE THREAD

**Issue by deboer-tim** [code-ready/crc#1860]
### General information

  * OS: macOS
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop

## CRC version
```bash
CodeReady Containers version: 1.21.0+68a4cdd7
OpenShift version: 4.6.9 (not embedded in executable)
```

## Host Operating System
```bash
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69
```

### Steps to reproduce
  1. Install, start, and stop a previous version of crc.
  2. Download, setup, and try to start a new version.

### Expected
After I download and setup a new version of CRC I expect I can start it immediately, and without specifying the pull-secret again.

### Actual
Here's the rough path I've been taking the last couple times I upgraded, with some commentary thrown in:
```bash
deboer$ crc setup
...
Setup is complete, you can now run 'crc start -b $bundlename' to start the OpenShift cluster
deboer$ crc start
...
Bundle 'crc_hyperkit_4.6.9.crcbundle' was requested, but the existing VM is using 'crc_hyperkit_4.6.6.crcbundle'
- Ok, I forgot to clean up the last install! It doesn't tell me how to fix this, so maybe I was supposed to literally copy and paste the command above?
deboer$ crc start -b $bundle-name
flag needs an argument: 'b' in -b
- Well, that clearly didn't work. Ok, so let's try deleting the old version
deboer$ crc delete
Do you want to delete the OpenShift cluster? [y/N]: y
Deleted the OpenShift cluster
- And try start again
deboer$ crc start
 - Prompts for pull secret, so I Ctrl-C to go see where it is. Ok, one more time...
deboer$ crc start -p /Users/deboer/Downloads/pull-secret
```

Clearly I keep forgetting about the previous install and am a novice at CRC, so maybe there's a better way to do this. However, I feel like this is what other new users would try as well, and several commands/complexity more than it should be. It would be nice if 'cleanup' of any past installs was automatically done during setup, and ideally the pull secret wouldn't need to be specified each time.

**Comment by gbraad** [comment]
Running `crc setup` was only intended to be used once (ever)... setting up the environment to use CRC. after this only `crc start` would be needed.

... but the complexity due to the embedding of the bundle caused this to be a two-stage scenario of extracting the bundle in setup... and unpacking in the the start step. This was NEVER supposed to work this way.

When using native installers the bundle will not be embedded anymore for at least Windows and macOS.... but what about Linux?

**Comment by cfergeau** [comment]
> ... but the complexity due to the embedding of the bundle caused this to be a two-stage scenario of extracting the bundle in setup... and unpacking in the the start step. This was NEVER supposed to work this way. The single binary provided an ease of distribution, but not the ease of use we were after

This is also needed when new features require new configuration (vsock is one such thing). So it's much safer to run `crc setup` once for each new crc version. I'm never going to promise that `crc-1.20 setup` will setup a machine in such a way that `crc-1.47 start` will be happy with it

**Comment by cfergeau** [comment]
> Bundle 'crc_hyperkit_4.6.9.crcbundle' was requested, but the existing VM is using 'crc_hyperkit_4.6.6.crcbundle'
> - Ok, I forgot to clean up the last install! It doesn't tell me how to fix this, so maybe I was supposed to literally copy and paste the command above?

This is the part that would be nice to automate, with an additional "Do you want to delete your older instance, losing all its data, and create a new cluster using the newer OpenShift version? [y/N]"? A way of remembering the pull secret during this upgrade is still missing though :)

**Comment by cfergeau** [comment]
Somehow related to https://github.com/code-ready/crc/issues/2662 which is also about upgrade issues.

**Comment by gbraad** [comment]
Let's review actions and update the epic.
