### ISSUE TITLE
[BUG]: Fresh cluster CRC does not allow connection to console or API (even after restart)

### ISSUE THREAD

**Issue by yohanswanepoel** [code-ready/crc#1862]
### General information

  * OS: Linux (Fedora 33)
  * Hypervisor: KVM 
  * Did you run `crc setup` Yes
  * Running CRC on: Laptop 

## CRC version
```bash
# Put `crc version` output here
```
CodeReady Containers version: 1.21.0+68a4cdd7
OpenShift version: 4.6.9 (embedded in executable)

  
## CRC status
```bash
# Put `crc status --log-level debug` output here
```

## CRC config
```bash
# Put `crc config view` output here
```
- consent-telemetry                     : yes
- disk-size                             : 65
- memory                                : 18432

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```
VERSION="33 (Workstation Edition)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f33/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation

### Steps to reproduce

  1. crc start
  2. crc console
  3. (also tried) oc login -u developer -p developer https://api.crc.testing:6443
  4. 

### Expected
crc start should enable me to connect to OpenShift either via console or through API. This is a fresh install. GIST file with Debug attached

### Actual
This does not happen. Connection refused

oc login -u developer -p developer https://api.crc.testing:6443
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

The connection to the server oauth-openshift.apps-crc.testing was refused - did you specify the right host or port?

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.
https://gist.github.com/yohanswanepoel/33b7c78f9e0973d64d7733d62bbd7b60

**Comment by praveenkumar** [comment]
@yohanswanepoel Can you put output of `crc status --log-level debug` one? Looks like auth operator taking bit more time then usual in your case.

**Comment by yohanswanepoel** [comment]
Sure

[johan@localhost bin]$ crc status --log-level debug one
DEBU CodeReady Containers version: 1.21.0+68a4cdd7 
DEBU OpenShift version: 4.6.9 (embedded in executable) 
DEBU Running 'crc status'                         
Checking file: /home/johan/.crc/machines/crc/.crc-exist
DEBU About to run SSH command:
df -B1 --output=size,used,target /sysroot | tail -1 
DEBU SSH command results: err: <nil>, output: 69228015616 11004919808 /sysroot 
DEBU About to run SSH command with hidden output  
DEBU SSH command succeeded                        
DEBU authentication operator is degraded, Reason: APIServerDeployment_UnavailablePod::IngressStateEndpoints_NonReadyEndpoints::OAuthRouteCheckEndpointAccessibleController_SyncError::OAuthServerDeployment_GetFailed::OAuthServiceCheckEndpointAccessibleController_SyncError::OAuthServiceEndpointsCheckEndpointAccessibleController_SyncError 
DEBU authentication operator is still progressing, Reason: OAuthVersionDeployment_ReplicasNotAvailable::OAuthVersionRoute_WaitingForRoute 
DEBU authentication operator not available, Reason: APIServerDeployment_NoPod::APIServices_PreconditionNotReady::OAuthRouteCheckEndpointAccessibleController_EndpointUnavailable::OAuthServerDeployment_NoReplicas::OAuthServiceCheckEndpointAccessibleController_EndpointUnavailable::OAuthVersionRoute_RequestFailed 
DEBU dns operator not available, Reason: DNSUnavailable 
DEBU dns operator is still progressing, Reason: Reconciling 
DEBU dns operator is degraded, Reason: DNSDegraded 
DEBU image-registry operator is still progressing, Reason: DeploymentNotCompleted 
DEBU kube-scheduler operator is degraded, Reason: NodeInstaller_InstallerPodFailed 
DEBU kube-scheduler operator is still progressing, Reason: NodeInstaller 
DEBU network operator is still progressing, Reason: Deploying 
DEBU openshift-apiserver operator not available, Reason: APIServerDeployment_NoPod::APIServices_PreconditionNotReady 
DEBU operator-lifecycle-manager-packageserver operator not available, Reason:  
DEBU operator-lifecycle-manager-packageserver operator is still progressing, Reason:  
CRC VM:          Running
OpenShift:       Starting (v4.6.9)
Disk Usage:      11GB of 69.23GB (Inside the CRC VM)
Cache Usage:     13.35GB
Cache Directory: /home/johan/.crc/cache
Failed to write to log, write /home/johan/.crc/crc.log: file already closed
Failed to write to log, write /home/johan/.crc/crc.log: file already closed
[johan@localhost bin]$

**Comment by guillaumerose** [comment]
If you wait a bit, the cluster is still working ?

**Comment by yohanswanepoel** [comment]
I will try again - but after 10-15 minutes not working.

**Comment by yohanswanepoel** [comment]
It is a 4 core - hyperthreaded i5 not sure if that means it does not have
enough processing power?

**Comment by yohanswanepoel** [comment]
A machine reboot fixed it somehow. Happy to close it - Did I miss that in the instructions?

**Comment by cfergeau** [comment]
Logout/login is needed in some very specific cases, but if needed it and forgot, `crc start` would not go as far (it would fail to create the VM, or to connect to it).

**Comment by yohanswanepoel** [comment]
Interesting, crc start did not enforce/ask for a restart. It was a fresh Fedora install - I will see if I can repeat the issue.
