### ISSUE TITLE
Prevent Defender SmartScreen popup by signing binary for Windows

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#1864]
![image](https://user-images.githubusercontent.com/1894/105319961-96028600-5b93-11eb-82b6-6b400c05f2a0.png)

**Comment by gbraad** [comment]
This happens when someone tries to start the executable by double clicking. This is the wrong way, but the failure of this will only show AFTER this popup is handled. When run from the command line, this does not happen.

**Comment by gbraad** [comment]
Signing will only be done AFTER we have a Native installer #16 like a MSI for Windows #1516 .

**Comment by cfergeau** [comment]
This is being worked on now that we added a MSI installer.

**Comment by anjannath** [comment]
The msi is signed and there is no popup shown if crc is installed using the msi
