### ISSUE TITLE
Deny crc start if crc setup has not run

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#1872]
`crc start` often fails because the user didn't run `crc setup`. We should at least remind the user for that.

**Comment by praveenkumar** [comment]
@guillaumerose doesn't current behavior which make sure to let user know to run the `crc setup` if any preflight fails, solve this?

**Comment by guillaumerose** [comment]
We have this in current master. The bundle is extracted last in crc setup and the bundle presence is checked first by crc start.
