### ISSUE TITLE
Vsock network mode shows no progress when used

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#1878]
The user might get suspicious when using vsock when seeing:
```
INFO Waiting for machine to be running, this may take a few minutes...
INFO Machine is up and running!
```

and has to wait for about 2 minutes...

until finally more gets added:

```
INFO CodeReady Containers VM is running
INFO Generating new SSH Key pair ...
INFO Updating authorized keys ...
INFO Copying kubeconfig file to instance dir ...
INFO Starting network time synchronization in CodeReady Containers VM
```

The text: `INFO Machine is up and running!` is too suggestive as "It was successful, right?"

**Comment by cfergeau** [comment]
*grin* no debug logs to get a better idea what it's been doing during these 2 minutes? I'd expect waiting for SSH?

**Comment by guillaumerose** [comment]
We could redirect redirect/show VM console logs to entertain the user while it starts.

**Comment by gbraad** [comment]
Yep, waiting for SSH. So in this case showing another 'suggestive message', like "Waiting for SSH to provision the machine" or simialr would at least temper the enthusiasm to break out earlier.

**Comment by gbraad** [comment]
> We could redirect redirect/show VM console logs to entertain the user while it starts.

This might cause an information overload and likely the eclipse console wouldn't appreciate this either.

**Comment by cfergeau** [comment]
> Yep, waiting for SSH. So in this case showing another 'suggestive message', like "Waiting for SSH to provision the machine" or simialr would at least temper the enthusiasm to break out earlier.

There's a `logging.Debug("Waiting until ssh is available")` before the `Wait for SSH` call, the message could be reworded and promoted to `Info`. I wonder what the VM is doing during these 2 minutes though, should not take that long to start, get an IP and start sshd.
