### ISSUE TITLE
[BUG] improve handling or verification of the pull-secret before pushing to the VM

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#1892]
Verify the validity of the JSON before we pass it to the VM.
Any kind of validition is better than nothing.

**Comment by praveenkumar** [comment]
@gbraad we are already validating it as part of `-p` option or even when user do config set, why do you think we need another validation when until there is possibility that our earlier validation is not the correct one?

**Comment by gbraad** [comment]
but also for copy-paste

**Comment by gbraad** [comment]
as per @guillaumerose's PR: 

----

Couple of UX changes:

   * crc start now keep asking for the pull secret until a valid one is passed.
   * directly print how to get the pull secret before asking for it. No more indirection with [? for help].
   * if the pull secret is given by copy/paste, store it in the keyring.
   * ask only once the pull secret as it is stored in the keyring for most users now (unless pull-secret-file property is set)
   * make the daemon and the cli call almost the same code for the pull secret

**Comment by guillaumerose** [comment]
The pull secret is already validated quite heavily:

```
func ImagePullSecret(secret string) error {
	var s imagePullSecret
	err := json.Unmarshal([]byte(secret), &s)
	if err != nil {
		return fmt.Errorf("invalid pull secret: %v", err)
	}
	if len(s.Auths) == 0 {
		return fmt.Errorf("invalid pull secret: missing 'auths' JSON-object field")
	}

	for d, a := range s.Auths {
		_, authPresent := a["auth"]
		_, credsStorePresent := a["credsStore"]
		if !authPresent && !credsStorePresent {
			return fmt.Errorf("invalid pull secret, '%q' JSON-object requires either 'auth' or 'credsStore' field", d)
		}
	}
	return nil
}
```

**Comment by praveenkumar** [comment]
UX changes for this is already taken care by #1889
