### ISSUE TITLE
[BUG] Bundle extraction is somewhat slow

### ISSUE THREAD

**Issue by mykaul** [code-ready/crc#1893]
### General information

  * OS: Linux
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes, this is crc setup.
  * Running CRC on: Laptop (but with NVMe disk)

## CRC version
```bash
[ykaul@ykaul crc-linux-1.21.0-amd64]$ ./crc version
CodeReady Containers version: 1.21.0+68a4cdd7
OpenShift version: 4.6.9 (embedded in executable)

```
  
## Host Operating System
Latest Fedora 33
### Steps to reproduce

  1. Run crc setup. It takes a lot of time (much longer than in the past?) to extract.
  2. 
  3. 
  4. 

### Expected
Faster extraction

### Actual

I was surprised to see how long it takes to extract the bundle.
A simple strace shows inefficiency in reads and writes - 4 8K reads with 1 32K writes can't be very fast:
```
read(8, "\225\310S;M\360\24\337i}\177_*\240\372?\357\37\244\227W\346\325X\233\372\317\261]\242\344\324"..., 8192) = 8192
read(8, "}\221#\260\334=\1\354n\354\375\373\200\31\362\177\316\302\266\25-3R\212\272\373\350^B}Pj"..., 8192) = 8192
read(8, "1\204\374\247\234\317\300C\325\330\207\371\300\fHbs\3163e\234E)\320\257\31\250\364\214\0217\323"..., 8192) = 8192
read(8, "\227\261\207q\20\364\343\216\27\327[-\306\203\363\201\213F}u\306\305\251\210\36z\tQ\270)=\313"..., 8192) = 8192
write(9, "M\21\250\200 \274\334\202\340O\335\321\361a\314\177\2601_tU\33\276\302\217\273y\34\247C<\252"..., 32768) = 32768
read(8, "\31\276\32W6f\320LX\200\261\311\372\376\346`\337\5\332{\312\303\327\237?\36\260\7\224q\260]"..., 8192) = 8192
read(8, "S\370W\326\322\"\300\f\266oe\24\363'\301\327j^\234\360\265\226\344\">\313\224=\2324\220\330"..., 8192) = 8192
read(8, "\377\314F\1]\227o\354ED\252\254\177\301O\356'\254\246\357\201k\247WW\254\273\"9\333R\212"..., 8192) = 8192
read(8, "\203\31\217\\v\334\304\303\335\35\307\225\4+D\275\227\360\22686\325\224\357U\200\207\25\235\241\355v"..., 8192) = 8192
write(9, "\352d!\207M^/\234\233\36q\313c\27B\274=cz\24\4h\263*\20\325\21\0G\371zJ"..., 32768) = 32768
```

### Logs
```
time="2021-01-27T10:09:03+02:00" level=debug msg="Extracting embedded 'crc_libvirt_4.6.9.crcbundle' from /home/tlv/ykaul/Downloads/crc-linux-1.21.0-amd64/crc 
to /home/tlv/ykaul/.crc/cache/crc_libvirt_4.6.9.crcbundle"
time="2021-01-27T10:09:05+02:00" level=debug msg="Uncompressing /home/tlv/ykaul/.crc/cache/crc_libvirt_4.6.9.crcbundle to /home/tlv/ykaul/.crc/cache"
time="2021-01-27T10:13:52+02:00" level=info msg="Checking minimum RAM requirements"
```

In addition, it's unclear to me if the qcow2 is zlib compressed or not. I happen to run a different test unrelated to CRC and just used the image - snappy compressed it by 50%:
```
[ykaul@ykaul snzip]$ du -ch ~/.crc/cache/crc_libvirt_4.6.9/crc.qcow2 
9.9G	/home/tlv/ykaul/.crc/cache/crc_libvirt_4.6.9/crc.qcow2
9.9G	total
[ykaul@ykaul snzip]$ im ~/.crc/cache/crc_libvirt_4.6.9/crc.qcow2 
img2simg  import    
[ykaul@ykaul snzip]$ qemu-img info  ~/.crc/cache/crc_libvirt_4.6.9/crc.qcow2 
image: /home/tlv/ykaul/.crc/cache/crc_libvirt_4.6.9/crc.qcow2
file format: qcow2
virtual size: 31 GiB (33285996544 bytes)
disk size: 9.85 GiB
cluster_size: 65536
Format specific information:
    compat: 1.1
    compression type: zlib
    lazy refcounts: true
    refcount bits: 16
    corrupt: false
[ykaul@ykaul snzip]$ ./snzip ~/.crc/cache/crc_libvirt_4.6.9/crc.qcow2
[ykaul@ykaul snzip]$ du -ch ~/.crc/cache/crc_libvirt_4.6.9/crc.qcow2.sz 
4.8G	/home/tlv/ykaul/.crc/cache/crc_libvirt_4.6.9/crc.qcow2.sz
4.8G	total
```

**Comment by mykaul** [comment]
I don't remember it being so slow in the past.

**Comment by gbraad** [comment]
For quite a while we use `xz`

https://github.com/code-ready/snc/blob/251d56da66b8d31b7baa6df6b04d813a4a8b14f0/createdisk.sh#L191

I have always experienced this as slow on Windows, but not Linux. Perhaps lz4 is better?

However the perception of this being slower is due to the size perhaps. Newer bundles of increased in size 'dramatically' (by a few hundred megabytes).

Perhaps @cfergeau can help as he did the initial investigation and compression choice.

**Comment by mykaul** [comment]
One potentially related issue - do we encrypt any partition? That could explain some of this, and we probably want to re-think this for performance reasons:
```
[ykaul@ykaul glusterfs]$ virt-sparsify --inplace ~/.crc/machines/crc/crc.qcow2 
 100% ⟦▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒⟧ --:--
Enter key or passphrase ("/dev/sda4"): 
[  10.9] Trimming /dev/sda1
[  11.4] Trimming /dev/sda2
[  11.8] Sparsify in-place operation completed with no errors

```

**Comment by cfergeau** [comment]
I'll look more closely at the initial report later, but regarding encryption, no there is no encryption on the image we use. The image is 'encryption ready', which means it has a luks header and asks for an (empty) passphrase, but it uses a 'null' cipher, so the data is unencrypted. If it was encrypted, it would be hard to compress.
This luks header is gone in 4.7 and not used in OKD.

**Comment by cfergeau** [comment]
> I was surprised to see how long it takes to extract the bundle.

Can you quantify "long"? On my linux/macos test machines it takes a few minutes (3min30 for a `crc setup` run), which is at the same time not great, but not awful either.

> A simple strace shows inefficiency in reads and writes - 4 8K reads with 1 32K writes can't be very fast:

We use https://golang.org/pkg/io/#Copy which defaults to using a 32kB buffer. It must be the tar or xz code which split the 32kB read into 4 smaller reads.
I tried providing a 16MB buffer and using https://golang.org/pkg/io/#CopyBuffer this did not make a difference with decompression time (strace shows 8kB reads and 16MB writes). I'd expect the kernel to do read ahead/write caching for us, and hide most of the impact of these IOs.

> Perhaps @cfergeau can help as he did the initial investigation and compression choice. Perhaps lz4 is better? Any change would also mean having to add detection for the compression used and add the new implementation (and still allow fallback).

xz compression is very slow, but when I tested, uncompression was not a lot slower than other alternatives. However, I did not take into account that I was testing on an ideal setup (idle machine with enough RAM, linux system, native xz implementation). There are some situations where xz is slower than we'd like, though since it's a 'one time per release' thing, this does not come up so often. When I checked, lz4 added several hundred megabytes to our archive size, which was not a tradeoff we wanted to make at that time.

> In addition, it's unclear to me if the qcow2 is zlib compressed or not. I happen to run a different test unrelated to CRC and just used the image - snappy compressed it by 50%:

The qcow2 image itself is not compressed since we ship it in a compressed archive. I'm not familiar at all with compressed qcow2 files, and it never occurred to me to try that ;) This is again a tradeoff to make, more io latency for smaller disk footprint.

**Comment by mykaul** [comment]
This is how long it took:
```
time="2021-01-27T10:09:05+02:00" level=debug msg="Uncompressing /home/tlv/ykaul/.crc/cache/crc_libvirt_4.6.9.crcbundle to /home/tlv/ykaul/.crc/cache"
time="2021-01-27T10:13:52+02:00" level=info msg="Checking minimum RAM requirements"
```

I try out almost every release of CRC and honestly do not remember it taking that long - but this is subjective really.

As for alternative compression, what  do you think about lz4hc? From https://github.com/inikep/lzbench it seems not too bad.
XZ:
```

Compressor name | Compress. | Decompress. | Compr. size | Ratio
-- | -- | -- | -- | --



xz 5.2.4 -0 | 24 MB/s | 70 MB/s | 62579435 | 29.53
-- | -- | -- | -- | --
xz 5.2.4 -3 | 6.76 MB/s | 84 MB/s | 55745125 | 26.30
xz 5.2.4 -6 | 2.95 MB/s | 89 MB/s | 49195929 | 23.21
xz 5.2.4 -9 | 2.62 MB/s | 88 MB/s | 48745306 | 23.00


```

lz4hc:
```

Compressor name | Compress. | Decompress. | Compr. size | Ratio
-- | -- | -- | -- | --



lz4hc 1.9.2 -1 | 131 MB/s | 4071 MB/s | 83803769 | 39.54
-- | -- | -- | -- | --
lz4hc 1.9.2 -4 | 81 MB/s | 4210 MB/s | 79807909 | 37.65
lz4hc 1.9.2 -9 | 33 MB/s | 4378 MB/s | 77884448 | 36.75
lz4hc 1.9.2 -12 | 11 MB/s | 4427 MB/s | 77262620 | 36.45


```

**Comment by guillaumerose** [comment]
Also some numbers: https://github.com/code-ready/crc/issues/1340

Also, the xz implementation we use is far from ideal (it is not maintained at all).

**Comment by cfergeau** [comment]
I tried lz4 compression with `lz4 -9`, I don't know if it's the same as lzhc. This gives me a 3.9G tarball, while the xz-compressed bundle is 2.6G (in other words lz4 is 50% bigger than xz)

**Comment by cfergeau** [comment]
Interesting, with `zstd --ultra -22 -T0`, I get a 2.2G tarball, smaller than the xz one.

**Comment by cfergeau** [comment]
And this zstd tarball gets decompressed in 10 seconds, VS 2 minutes for the xz one. Need to double check these results as I've been doing these experiments while attending a totally different meeting :)

**Comment by gbraad** [comment]
@guillaumerose @cfergeau is uncimpression and bundle handling time part of telemetry?

**Comment by cfergeau** [comment]
It will indirectly be part of telemetry through "time `crc setup` took to complete". I don't think we have a specific "bundle handling time" measurement.

**Comment by guillaumerose** [comment]
Since zstd, it's really better. Closing this issue.
