### ISSUE TITLE
Ask the pull secret at `crc setup` step

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#1899]
The pull secret can be seen as a part of the setup. The VM won't start without it.
We could ask for it at setup time.

Major problems with this: the pull secret needs to be stored and the user, particularly on Linux, doesn't necessarily have a keyring.

The good point of this change is that once setup is ok, start is non-blocking. Currently we see some `crc start` last more than 1h in telemetry.

**Comment by gbraad** [comment]
I would rather see this being part of the installer or systray first start, Installer would seem more likely, though is not a solution available on all targets (Linux has no native installer).

**Comment by guillaumerose** [comment]
This has been changed for macOS and Windows trays.
The pull secret is now asked and stored before the first start. CLI didnt changed.

**Comment by cfergeau** [comment]
I'll close this, this is only an issue on linux machines without a keyring nowadays. Feel free to reopen if you think we should keep tracking this.
