### ISSUE TITLE
Use the telemetry ID as the cluster ID

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#1901]
Now that crc includes segment, it would be great to be able to link odo, vscode, etc usage with crc. 

Tools can report the cluster ID of the cluster they used. CRC can directly use a segment ID equal to its cluster ID.

**Comment by cfergeau** [comment]
My worry here is that it might make it easier to inadvertantly break the 'pseudonymous' nature of the segment ID? Some tools could collect cluster IDs together with other personal data, which would mean there would now be a 'real identity' <-> 'segment ID' mapping?

**Comment by praveenkumar** [comment]
If we add the cluster ID with segment one and then user start monitoring that means now we are capturing all the data using that ID so I would like it to be different as it is right now.
