### ISSUE TITLE
Telemetry: guess the country by looking at the system locale

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#1902]
CRC doesn't collect IP but it would be nice to now a little bit more about the location of our user.
For that, we could use the system locale and guess the country.

This is what others Red Hat developer projects are doing.

**Comment by cfergeau** [comment]
On the other hand, we should avoid collecting too much information which could uniquely identify the anonymous reports when put together.

**Comment by jsliacan** [comment]
@cfergeau we could pollute the data with some noisy random entries that we'd generate. Number of them would be proportional to the volume of the info we're getting from the real users. E.g. throw in a bunch of locations at random with some random usage patterns. If it's not too many, it doesn't matter statistically for our purposes, but it anonymizes the users. Then you can collect whatever you want (almost :) ).

**Comment by gbraad** [comment]
any kind of data is open to interpretation; this is the process to make it into information. and there will always be mistakes in such approaches. this can be compared anyway with download stats.

for example; I use the US locale, the Dutch Regional Settings, but located in Asia. This guesstimation would surely be off... as even from the VPN I am identified as either from Japan, Hong Kong, Raleigh or Amsterdam.

**Comment by deboer-tim** [comment]
I agree we need to be careful about what we collect and whether it ever becomes possible to uniquely identify someone, but gbraad is right that what we're talking about here is still both imprecise and has a potentially high failure rate.

We're just looking for a crude way to start telling where CRC users are in the world, without relying on any external service (e.g. one that would convert IP to country) or sending in any PII like IP. There are several cases where it'll be wrong (and personally I'd like to find some way of reducing this) but at least it will start to give us some idea.

**Comment by cfergeau** [comment]
> I agree we need to be careful about what we collect and whether it ever becomes possible to uniquely identify someone, but gbraad is right that what we're talking about here is still both imprecise and has a potentially high failure rate.

Even if this piece of information is imprecise, gathering multiple imprecise things about the same individual may ultimately uniquely identify this person, similar to https://pixelprivacy.com/resources/browser-fingerprinting/
Granted, we already have the anonymous ID to uniquely identify people, but I think what I'm worried about is of us gathering too much unique information, and that, knowing X is a crc user + a few generic facts about X, we'd be able to find their anonymous ID.

**Comment by jsliacan** [comment]
> what I'm worried about is of us gathering too much unique information, and that, knowing X is a crc user + a few generic facts about X, we'd be able to find their anonymous ID

I think that concern gets out of hand very quickly :) I don't know about many ways to measure anonymity, except for concepts like e.g. k-anonymity. But even if we wanted to make sure that every entry is identical to ~k other entries in an arbitrarily sub-optimal way, it'd be a considerable effort. Forget about making sure that we didn't ruin our data too much (that it stops being useful)... And I wouldn't be surprised if optimal case was NP-hard. 

What we could do is "expire" data: e.g. only keep averages for entries older than some past date. So we'd have entries for the past month, and then only keep aggregated data: n_1 people did this, n_2 people did that, etc. No idea if it makes sense in our context though. Or if we were really nice to our users, we could delete old data altogether :). As crazy as that sounds, it might not even be bad for us -- what users did with v1 of CRC is irrelevant to us when v21 is out. In a way...

**Comment by deboer-tim** [comment]
FYI, CRC is already collecting version info since it allows us to see adoption rate, confirm that a fix worked, etc.

We're also already sending the timezone, which we'd use here to guess the country - so we're not even talking about sending any new data. We could already guess it on the server-side, our telemetry engine just works much easier if we do it this way.

The intention across all tools is to not collect any PII, nor enough cumulative information to uniquely identify a person. As long as we continue to do that, we don't need to have any requirements on retention policy.

**Comment by cfergeau** [comment]
> We're also already sending the timezone, which we'd use here to guess the country - so we're not even talking about sending any new data. We could already guess it on the server-side, our telemetry engine just works much easier if we do it this way.

Then the question should become "should we be stripping out timezone info?". If we consider this makes user identification too easy, "it's already there" should not prevent us from stopping to send it. I'm not necessarily questioning the sending of this particular piece of information, but the trend I'm seeing is that "oh, let's add A, B, C, ..., X, Y, Z to telemetry to have a better idea of who are our users" without much thought given to "are we gathering too much cumulative information?" or some weighting of what we'd like VS user privacy.
At the moment our data set size is hundreds or a few thousands of users, so it does not much to have enough unique information to identify them, especially if you cross segment data with issues reported in github.

**Comment by gbraad** [comment]
In short, this optimization seems unnecessary as it can be done at a later stage.
I'd rather pre-process/massage the data as little as possible, except for sanitizing or stripping.

**Comment by deboer-tim** [comment]
> I'm not necessarily questioning the sending of this particular piece of information, but the trend I'm seeing is that "oh, let's add A, B, C, ..., X, Y, Z to telemetry to have a better idea of who are our users" without much thought given to "are we gathering too much cumulative information?" or some weighting of what we'd like VS user privacy.

Let me try to be clear then: we trying to be extremely careful about not collecting PII, and we also do not want to collect enough to be able to fingerprint. I agree it's valid to question whether any new request for data is useful or breaks either of these things.

> At the moment our data set size is hundreds or a few thousands of users, so it does not much to have enough unique information to identify them, especially if you cross segment data with issues reported in github.

With the limited volume today you could guess which user is me based on my timezone, OS, CRC version and time in my last bug, etc - but you still don't know for sure because you don't know if I turned on telemetry and there are at least two other people you know who would have the same fingerprint. I think we both agree that we need to keep that bit of unknown and we should never try to match up external data in an attempt to do this.

I've updated the internal telemetry guidance to try to be explicit about both of these points.

> In short, this optimization seems unnecessary as it can be done at a later stage.

The reason this was requested client-side is that it's simple and straight-forward, hence far less resource to do it. It's not clear to me whether you're suggesting deferring this or investigating the server-side equivalent?

**Comment by gbraad** [comment]
Personally I see no practical use from the guessed country. It would not provide conclusive feedback to improving CRC besides being a statistic of use. It would be far more pracrical to collect a locale setting as this can lead to deciding if a localzation effort is in place. The country statistic is somethings that can also be collected from the download manager? And yes, the effort to do this in CRC sounds like a duplication of multiple effort in JavaScript, Golang, etc while this is likely something a conversion step for the datasource could do.
