### ISSUE TITLE
Hyper-V driver should return more details when failing

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#1904]
When the user hits an error because of Hyper-V, he only sees this message:

```
Error creating machine: Error creating the VM: Error creating machine: Error in driver during machine creation: exit status 1
```

He can't do much with this information. All details are hidden in crc.log. 

code: https://github.com/code-ready/crc/blob/master/pkg/drivers/hyperv/powershell.go#L27

**Comment by gbraad** [comment]
https://github.com/code-ready/crc/blob/162e13a7e5e3b5f966874fe2dbd75f12b68cbbb9/pkg/libmachine/libmachine.go#L116

**Comment by gbraad** [comment]
all powershell commands are wrapped with `cmd` that calls `cmdout` and should return an error.
Something during the Create phase returned just `exit status 1`

**Comment by gbraad** [comment]
did the VM get created? as, visible from the manager?
as in the end of the Create method, it will call Start
