### ISSUE TITLE
[Epic] When a user uses the CLI, the action should reflect correctly in the daemon (and vice versa)

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#1915]
EDIT 21/06/2021:

Currently, if I use the tray to start the application, if I type `crc status`, it won't display in most case `Starting`.

The CLI and the daemon are currently separated. They share the same state (files in ~/.crc and the hypervisor API) and most of the time they are in sync, but not always. 
The goal is for the CLI to use the API when the daemon is started. 

---

When the daemon is launched, crc CLI should use it instead of performing the action itself. 
For instance, on macOS, the daemon will be (soon) always up. We could force all actions to be made by the daemon. 

It requires to create a Golang client for the daemon API. HTTP will help a lot: https://github.com/code-ready/crc/issues/1914.

The main benefit would be to deny/order concurrent/antagonist actions and have a single source of truth for crc status and the tray.

**Comment by cfergeau** [comment]
> For instance, on macOS, the daemon will be (soon) always up

Does this mean we want to force the tray to always be running on macos, or to always start the daemon, even if the tray is not started?

**Comment by gbraad** [comment]
>     The main benefit would be to deny/order concurrent/antagonist actions and have a single source of truth for crc status and the tray.

part of this discussion was on the config store/processes discussion.  When an action happens when alreafy runing, it is denied... unless a stop is given for example (but a -f would be needed to confirm the stop). This would prevent the whole Ctrl+C issue

however, this would introduce the need to 'stream' the output... or force to tail an output file that is given from the daemon

**Comment by gbraad** [comment]
> > When the daemon is launched, crc CLI should use it instead of performing the action itself.

> Does this mean we want to force the tray to always be running on macos, or to always start the daemon,

the daemon can be started from the command. it is essential for the dunctionality of vsock.
ideally it will always be there. when the tray is enabled/started (default soon) this is a given... but you could still turn this off, but the daemon will always have to start as part of the process.

**Comment by cfergeau** [comment]
>  The goal is for the CLI to use the API when the daemon is started.

I did some experiments around this in https://github.com/cfergeau/crc/commits/remote
This runs status through the daemon, and can also do this through a ssh tunnel if the daemon is running on a remote host.
This code needs to be cleaned up though, and this needs to be implemented for all commands (the branch has a TODO)
