### ISSUE TITLE
[Epic] daemon GA

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#1917]
What is needed to make the daemon GA:

- [ ] remove it from experimental-features
- [x] https://github.com/code-ready/crc/issues/1916 crc daemon should not bind ports if not running in vsock mode
- [ ] ?

**Comment by cameronkerrnz** [comment]
I would suggest that it needs to at least be able to expose the registry (so I can push an image to from within Docker etc.)

Should also be reasonable to have it listen on any NodePort.

Similarly, it would be great if it could expose Routes / Ingress; but its probably more useful to have it exposing NodePorts.

On Windows 10 Enterprise, I noticed that the modifications to the hosts file easily gets too long which causes resolution failures. I split mine out, and its much more reliable:

```
PS C:\WINDOWS\system32> Get-Content c:\windows\system32\drivers\etc\hosts
...
# localhost name resolution is handled within DNS itself.
# (at least until you put an entry in here for 127.0.0.1)
127.0.0.1 localhost
...
# Added by Docker Desktop
192.168.1.236 host.docker.internal
192.168.1.236 gateway.docker.internal
127.0.0.1 kubernetes.docker.internal
# To allow the same kube context to work on the host and the container:
127.0.0.1 api.crc.testing
127.0.0.1 console-openshift-console.apps-crc.testing
127.0.0.1 default-route-openshift-image-registry.apps-crc.testing
127.0.0.1 oauth-openshift.apps-crc.testing
127.0.0.1 downloads-openshift-console.apps-crc.testing
# End of section
```

(if you put all the 127.0.0.1 entries on one line then the ones on the end don't work)

**Comment by cfergeau** [comment]
Regarding your hosts file comment, did the line get too long when crc generated it? https://github.com/goodhosts/hostsfile/blob/2c912e71a4f3ca1a563437658c81fd433ebaadca/hosts.go#L263-L286 splits each line to have at most 8 entries, `default-route-openshift-image-registry.apps-crc.testing` is 56 bytes long, and is the longest entry, 8 such entries would give a line under 512 bytes, hopefully this is not too long for the Windows resolver ?

**Comment by cameronkerrnz** [comment]
It would have had less than 8 entries, but about that many. It was still one line at the time. I imagine there may well be different components (and different edge-cases) that could consume this file.

**Comment by cameronkerrnz** [comment]
It would be good to put a workaround in the Known Issues so users can access the internal registry (and other services) and be able to push images from Docker Desktop

(Possibly this comment would be better placed in the Wiki article on the vsock mode)

In the case of Docker Desktop (even when running in WSL mode), the docker daemon can't connect to 127.0.0.1:5000 ("connection refused"), so you need the daemon to be connecting to host.docker.internal:5000. This will raise a firewall issue with Windows Firewall. The DNS name host.docker.internal is one of the interfaces on your regular interfaces (eg. your wireless adaptor if that is what you use to connect your host to the network), so beware of this changing.

```
PS> oc -n openshift-image-registry port-forward service/image-registry 5000:5000 --address 0.0.0.0
```

You need to adjust the Docker Daemon's insecure registries to add host.docker.internal:

```json
{
  "registry-mirrors": [],
  "insecure-registries": [
    "host.docker.internal:5000"
  ],
  "debug": false,
  "experimental": false,
  "features": {
    "buildkit": true
  }
}
```

Test a docker login (you get the same error if being prompted for password.

```
PS> docker login -u developer -p $(oc whoami -t) host.docker.internal:5000
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
```

Granted, the name 'host.docker.internal' is misleading as to this being the OpenShift internal registry.

Let's tag and push an image into OpenShift

```
PS> docker tag openshift-r-shiny:latest host.docker.internal:5000/cameron-rshiny/openshift-r-shiny:latest

PS> docker push host.docker.internal:5000/cameron-rshiny/openshift-r-shiny:latest
The push refers to repository [host.docker.internal:5000/cameron-rshiny/openshift-r-shiny]
...
e1c75a5e0bfa: Pushed
latest: digest: sha256:adb80b7f0530b0acf1f62c97187b47b2c8685310b2c86b0aac1f452259a9ebad size: 4078
```

Verify:

```
PS> oc -n cameron-rshiny get is
NAME                IMAGE REPOSITORY                                                                           TAGS     UPDATED
openshift-r-shiny   default-route-openshift-image-registry.apps-crc.testing/cameron-rshiny/openshift-r-shiny   latest   About a minute ago
```
