### ISSUE TITLE
[Feature] Check if crc daemon process is reachable in case the network mode set as vsock

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#1923]
On all the platforms we need `crc daemon` to be running to work with vsock, It would be great if we can detect it as part preflight if the network mode is `vsock` ?

**Comment by gbraad** [comment]
s/running/reachable...

**Comment by gbraad** [comment]
The reason for reachable is a possible cause of it not running; at the moment we do not perform any checks if we can bind to these ports. They might be in use by something else. So we need to check if the port is reachable (and followed by a process or API check). If no expected response, we might have to start the daemon... but if this fails, we need to act on the error. The problem might be that these ports are already in use and need to be suffixed or offset for the new process.
