### ISSUE TITLE
[BUG] Images served from internal registry are not used by containers when overwritten

### ISSUE THREAD

**Issue by bentito** [code-ready/crc#1928]
### General information

  * OS: MacOS
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop

## CRC version
```bash
CodeReady Containers version: 1.21.0+68a4cdd7
OpenShift version: 4.6.9 (embedded in executable)
```
  
## CRC status
```bash
DEBU CodeReady Containers version: 1.21.0+68a4cdd7
DEBU OpenShift version: 4.6.9 (embedded in executable)
DEBU Running 'crc status'
Checking file: /Users/btofel/.crc/machines/crc/.crc-exist
DEBU About to run SSH command:
df -B1 --output=size,used,target /sysroot | tail -1
DEBU SSH command results: err: <nil>, output: 32720793600 15640846336 /sysroot
DEBU About to run SSH command with hidden output
DEBU SSH command succeeded
CRC VM:          Running
OpenShift:       Running (v4.6.9)
Disk Usage:      15.64GB of 32.72GB (Inside the CRC VM)
Cache Usage:     27.4GB
Cache Directory: /Users/btofel/.crc/cache
```

## CRC config
```bash
- consent-telemetry                     : no
```

## Host Operating System
```bash
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69
```

### Steps to reproduce

  1. Push an image to the internal registry using the externally accessible URL, for instance:
```bash
tekton-scorecard-image java_additions $ docker push default-route-openshift-image-registry.apps-crc.testing/default/tekton-scorecard-image:dev
The push refers to repository [default-route-openshift-image-registry.apps-crc.testing/default/tekton-scorecard-image]
491ebcd73f51: Pushed
e2f1c0959239: Pushed
24b29b06239f: Pushed
00af10937683: Pushed
3aa55ff7bca1: Pushed
dev: digest: sha256:40a7637f2d835f6522f1ed4ff51499698a71ddc1105094ccad10a11764933fc3 size: 1363
```
  2. Cause a pod to be created with a container based on that image, for instance (the following is config for operator-sdk's scorecard command, doesn't really matter, the important thing is the reference to the internal registry served image):
```yaml
kind: Configuration
apiversion: scorecard.operatorframework.io/v1alpha3
metadata:
  name: config
stages:
- tests:
  - image: image-registry.openshift-image-registry.svc:5000/default/tekton-scorecard-image:dev
    entrypoint:
    - tekton-scorecard-tests
    - customtest1
    labels:
      suite: tekton
      test: customtest1
<snip>
```
  3. Do some development, make some code changes, build a new image and push, like so:
```bash
tekton-scorecard-image java_additions $ docker push default-route-openshift-image-registry.apps-crc.testing/default/tekton-scorecard-image:dev
The push refers to repository [default-route-openshift-image-registry.apps-crc.testing/default/tekton-scorecard-image]
1323ee0c0c55: Pushed
30309fa628b9: Pushed
6402a00d9280: Pushed
00af10937683: Layer already exists
3aa55ff7bca1: Layer already exists
dev: digest: sha256:6fa11c4427b8686b19896b5ec9b351c84ebdc3a1f5f7c258aad7e47f0a4c6aad size: 1363
```
Note: The image layers have changed due to the code changes and they've been successfully pushed, and should be overwriting the `dev` tag image.
  4. Cause your pod to re-instantiate. Note that it does not use the new version of the image.

### Expected
When an image is overwritten in the CRC internal registry, the new version should be used for container creation.

### Actual
When an image is overwritten in the CRC internal registry, the new version is not used for container creation.

### Logs
I'm happy to add gist with debug level logs, just @ me in a response and request. I am hoping this problem should be re-creatable as described above though.

**Comment by bentito** [comment]
So, this is a workaround, and maybe the behavior I am reporting is simply normal Docker functionality !? If I do the following:
```bash
docker rmi default-route-openshift-image-registry.apps-crc.testing/default/tekton-scorecard-image:dev
```
Deleting the image from my local docker instance. Then build and the push the same image:tag to the CRC registry. Then the container uses my changed image.

**Comment by praveenkumar** [comment]
@bentito I tried something following after reading bit around deployments, build triggers and deployment config. Following is what works for me in the sense my pod automatic get updated as soon as I update the image to imagestream.

```
$ cat entry.sh 
#!/bin/sh

while true
do
   echo "Hello from version-1"
done

$ cat Dockerfile 
FROM busybox:latest

COPY entry.sh /bin/entry.sh

USER 1000:1000

ENV PATH /bin

ENTRYPOINT ["entry.sh"]

$ podman build -t test:dev -f Dockerfile

$ oc login -u developer -p developer

$ podman login -u developer -p $(oc whoami -t) default-route-openshift-image-registry.apps-crc.testing --tls-verify=false
login succeed

$ podman images
REPOSITORY                                                                  TAG     IMAGE ID      CREATED         SIZE
localhost/test                                                              dev     d07d9960ff66  6 minutes ago   1.45 MB

$ podman push d07d9960ff66 default-route-openshift-image-registry.apps-crc.testing/demo/test:dev --tls-verify=false

$ oc get is
NAME   IMAGE REPOSITORY                                                    TAGS   UPDATED
test   default-route-openshift-image-registry.apps-crc.testing/demo/test   dev    6 minutes ago

$ oc create deploymentconfig demo --image=image-registry.openshift-image-registry.svc:5000/demo/test:dev

$ oc set triggers dc/demo --from-image=demo/test:dev -c default-container

```

**Comment by bentito** [comment]
Okay I verified that there is no difference if I do the deployment the way I did it above but substitute quay as the image registry and an OCP 4.6 cluster for CRC internal registry and CRC. 

I do not have full control over the deployment details as that's done by `operator-sdk scorecard`, but maybe by trying to understand what you did with imagestreams and triggers I can understand how to alleviate the problem. 

Thanks @praveenkumar, I think it's safe to close this as a CRC issue.

**Comment by bentito** [comment]
Quick follow-up: This comes down to `operator-sdk scorecard` using `IfPresent` instead `AlwaysPullImage` for the `ImagePullPolicy`. There is an issue created on operator-sdk and the workaround for me was to add a script updating the tag to a new tag name each push.
