### ISSUE TITLE
[Segment] Capture crc run on tty/non-tty environment

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#1934]
We already have checks around interactive and terminal execution which help user to run the crc on a CI environment if needed. We should capture that data as part of telemeter to identify how many users are using CRC for non-tty case (mostly be the CI).

**Comment by gbraad** [comment]
this might even need additional checks on Windows, as there is a diference between Powershell from conhost or the new Windows Terminal... or even the use of mintty. :-/

**Comment by guillaumerose** [comment]
At least Linux/macOS is done with https://github.com/code-ready/crc/pull/1936

**Comment by guillaumerose** [comment]
On macOS/Linux, this doesn't bring much at the end. I don't think it worth looking at it for Windows.

**Comment by guillaumerose** [comment]
Let's close this for now. If we have something cool to say based on this parameter with macOS and Linux, we can reopen and do it for Windows.
