### ISSUE TITLE
make macOS tray enabled by default on setup

### ISSUE THREAD

**Issue by anjannath** [code-ready/crc#1937]
we have the basic functionality for the tray on macOS, so we can have it enabled by default on setup, user can always exit it from the tray menu.

To uninstall user needs to run `crc cleanup`
Maybe also a config option to skip the installation of the tray during `crc setup` like `crc setup install-tray false` ?

**Comment by cfergeau** [comment]
> user can always exit it from the tray menu.

But it will be restarted automatically with next reboot. I'm not clear on what the exact workflows would be, especially to reenable the tray, but in my opinion it should be possible to permanently disable the tray (with a click or so, not through several `crc` commands).

**Comment by anjannath** [comment]
> but in my opinion we need a way to permanently disable the tray (with a click or so, not through several crc commands).

+1,  i was thinking of adding a button for only removing the tray related files in the `Advanced` tab of preferences window

**Comment by gbraad** [comment]
it should not only be from the tray...

the action would be to allow a toggle to `start-tray` which will default to true, but will be allowed to modify.
the startup of the tray can check this and exit if the files AREN'T removed. but the cleanup could in that case also handle the removal. best to decide the flow before working on it.

**Comment by anjannath** [comment]
1. User runs `crc setup` and has the tray installed, To uninstall -
- He can run `crc cleanup` but this'll also remove the crc instance.
- He can close the try from its menu, but it'll show up on next reboot.

We already have the uninstall feature in the `crc cleanup` command, what we want to control is the auto-start behaviour, for that we can introduce a new config option in crc called `auto-start-tray` (_Launch tray at login_ on the tray UI) and this would control the auto-start behavior of the trays, this is for enabling/disabling only the trays and not control the daemon.

**Comment by cfergeau** [comment]
> For re-enabling the tray the user can either use the cli to do config set auto-start-tray true

followed by `crc setup` I assume? The rest of your proposal sounds good to me, and simple enough on the crc side!

**Comment by anjannath** [comment]
> followed by crc setup I assume?

I was thinking to run a callback on `config set/unset` for this, It'll just be creation/removal of a  file in `~/Library/LaunchDaemons`

**Comment by guillaumerose** [comment]
Do we have approval of @sspeiche for that ? 
I still can find lot of tiny bugs when I try the tray.

**Comment by sspeiche** [comment]
> Do we have approval of @sspeiche for that ?
> I still can find lot of tiny bugs when I try the tray.

Makes senses to me, especially since we may have installer ways in the future to uncheck a box and there is a way to clean it up. 

Another option, maybe a smaller step, is to just dump the command after `crc setup` or other command about how to enable system tray
