### ISSUE TITLE
Connection Issues to the crc VM on MacOS

### ISSUE THREAD

**Issue by sroe007** [code-ready/crc#1940]
### General information

  * OS: macOS 
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it? Yes

## CRC version
```bash
# Put the output of `crc version`

`CodeReady Containers version: 1.21.0+68a4cdd7
OpenShift version: 4.6.9 (embedded in executable)`
  
## CRC status
`crc status
CRC VM:          Running
OpenShift:       Not Reachable (v4.6.9)
Disk Usage:      22.49GB of 32.72GB (Inside the CRC VM)
Cache Usage:     13.53GB
Cache Directory: /Users/sean/.crc/cache`

## CRC config
# Put the output of `crc config view`

`crc config view
- consent-telemetry                     : no`


## Host Operating System
`sw_vers
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69
`

### Steps to reproduce

  1. `crc start --memory 16384 --log-level debug`
  2. `crc oc-env` and
  3. `export PATH="/Users/sean/.crc/bin/oc:$PATH"`
  4. `crc console --credentials` # only applies upon start failure - see notes below
  5. `ssh -i ~/.crc/machines/crc/id_ecdsa core@"$(crc ip)"` # log into the VM see Logs below
  6. `crc console` fails with "You are offline"
  7. `oc login -u developer -p developer https://api.crc.testing:6443` also fails with 
  8. `error: dial tcp 192.168.64.2:6443: connect: connection refused - verify you have provided the correct host and port and that the server is currently running.`
  9. I have checked the creation of the DNS entries in /etc/hosts and /etc/resolver/testing - all are as they should be and as documented. 
  10. I have examined extending the timeout values for the ssh client - the logs indicate a "temporary" ssh error which made me think that the cluster is taking too long (a lot of pods - see below) to come up but the CrashLoopBackOff on the k8s side indicate that something is broken on the apiserver


### Expected

Upon installation the environment worked for a period of approximately 48 hours. In one of the initial starts the certificate renewal could be observed. I did a crc stop since I don't need this environment running all the time. I have installed some additional products in the environment - including Istio 1.8 and Anypoint Service Mesh and CodeReady Workspaces (this environment is for a team enablement session). All of these installations worked fine. 

Is it possible to reconfigure the cluster without doing a delete - setting up the environment was quite a lot of work and without understanding what actually happened and how it could be avoided I would not want to repeat.


### Actual

After the next restart the VM comes up - see status above but OpenShift is not accessible. The logs - see the attached file
[crc_debug.pdf](https://github.com/code-ready/crc/files/5917297/crc_debug.pdf) -. shows the ssh connection on the `oc get nodes --context admin --cluster crc --kubeconfig /opt/kubeconfig` call failing after repeated attempts. 
 
The kubelet service show among other things a CrashLoopBackOff.


### Logs
 
See [crc_debug.pdf](https://github.com/code-ready/crc/files/5917297/crc_debug.pdf) and
[crc-kubelet-service.txt](https://github.com/code-ready/crc/files/5917466/crc-kubelet-service.txt)

**Comment by praveenkumar** [comment]
@sroe007 Are you facing this issue when doing start => stop => start scenario?

**Comment by sroe007** [comment]
@praveenkumar Hi...yes....as stated the environment worked fine for about 2 days - I stopped it with `crc stop` and the problem arose on restart without me having made any changes.....I checked by running `crc setup` again (checking file permissions)..

**Comment by praveenkumar** [comment]
As per the logs which you shared looks like apiserver is not even able to run after start. Can you ssh to the VM and try to check why it is the issue with apiserver? Hope you are not hit by https://github.com/code-ready/crc/issues/1888 one.
```
oc get nodes --context admin --cluster crc --kubeconfig /opt/kubeconfig
DEBU SSH command results: err: Process exited with status 1, output:
DEBU The connection to the server api.crc.testing:6443 was refused - did
you specify the right host or port?
```

**Comment by sroe007** [comment]
@praveenkumar ...something is definitely amiss in the apiserver - you can clearly see the CrashLoopBackOff in the attached kubelet.service log. I will take a look at the manifest for the etcd.yaml re #1888 and update

**Comment by sroe007** [comment]
@praveenkumar ...so checked the yaml of etcd and apiserver - both seem good - specifically the #1888 issue is not apparent - the ip of the etcd pod is as expected 192.168.64.2
[etcd.pdf](https://github.com/code-ready/crc/files/5919099/etcd.pdf)

**Comment by sroe007** [comment]
@praveenkumar I can now see some discrepancies which look similar to part of the description in #1888 - I am attaching some screenshots - as you can see from pod2, pod3 and pod4 the etcd Endpoints vary - with 192.168.126.11, 192.168.126.10 and the cluster address 192.168.64.2 whereby pod4 would appear to be the main pod. I also attach the output of crictl ps -a which shows no etcd pod at all running and the apiserver pod failing continuously. One question is how to do a systemctl restart as user core since i cannot sudo and this user has a client cert rather than password? I would like to try to reconfigure the pods if possible and restart the kubelet service - and secondly which of the pod yamls is correct in your view?
<img width="1086" alt="pod3" src="https://user-images.githubusercontent.com/57169144/106778731-921c3c80-6646-11eb-8fcf-d4acfce9076e.png">
<img width="1261" alt="pod4" src="https://user-images.githubusercontent.com/57169144/106778734-92b4d300-6646-11eb-8938-a01ce198cc47.png">

let service as described in #1888 
<img width="1697" alt="docker" src="https://user-images.githubusercontent.com/57169144/106778705-8a5c9800-6646-11eb-95d4-49f4f3b5364f.png">
<img width="1235" alt="pod2" src="https://user-images.githubusercontent.com/57169144/106778726-90eb0f80-6646-11eb-8339-36b991f9833d.png">

**Comment by sroe007** [comment]
@praveenkumar A further update....a significant number of resources in the above were not being generated - the problem being the .ssh handshake at the start so somehow the authorized key was broken or incorrect - leading to a handshake problem after `cat /home/core/.ssh/authorized_keys `- and as a result the following podman call, registry access etc...was correct. `sudo podman run  --ip 10.88.0.8 --name dnsmasq -v /var/srv/dnsmasq.conf:/etc/dnsmasq.conf -p 53:53/udp --privileged -d quay.io/crcont/dnsmasq:latest `  Thanks for your support

**Comment by praveenkumar** [comment]
> @praveenkumar A further update....a significant number of resources in the above were not being generated - the problem being the .ssh handshake at the start so somehow the authorized key was broken or incorrect - leading to a handshake problem after `cat /home/core/.ssh/authorized_keys `- and as a result the following podman call, registry access etc...was correct. `sudo podman run --ip 10.88.0.8 --name dnsmasq -v /var/srv/dnsmasq.conf:/etc/dnsmasq.conf -p 53:53/udp --privileged -d quay.io/crcont/dnsmasq:latest ` Thanks for your support

@sroe007 Sorry I still didn't get what was the issue :( do you mean the auth key was broken and this lead to podman command not able to run? We just want to make sure if we can fix it as part of CRC then we should do it.

**Comment by sroe007** [comment]
@praveenkumar - I am not completely sure what happened in the end. What it looks like is that somehow my ssh key got trashed - what I see in the broken environment is the following: 
`"2021-01-30T15:26:10+01:00" level=debug msg="About to run SSH command:\ncat /home/core/.ssh/authorized_keys"
time="2021-01-30T15:26:10+01:00" level=debug msg="SSH command results: err: <nil>, output: ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAAQYsUYKZBiRA5MSFA+ReXRFeMOrZO6h611Aj29jEOpodz4RAI74KS+gJHqfAYCuaXMp/uTW9GFVrY+Iva1eyRMEACJIxmdZQFHvZQs9pCuXKpG2l6Ua+G3yFwbZxrSvQscY6lhLkQrSAUASDEEzZtfGAFMDlR57rcO4eNx92Ga4e6ltw==\n\n
`
This looks like the key has a linebreak or something else at the end....

The result is that the handshake fails and the connection to the repository fails. The log shows

`time="2021-01-30T15:26:25+01:00" level=debug msg="About to run SSH command:\noc get nodes --context admin --cluster crc --kubeconfig /opt/kubeconfig"
time="2021-01-30T15:26:25+01:00" level=debug msg="SSH command results: err: Process exited with status 1, output: "
time="2021-01-30T15:26:25+01:00" level=debug msg="The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port?\n"
time="2021-01-30T15:26:25+01:00" level=debug msg="error: Temporary error: ssh command error:\ncommand : oc get nodes --context admin --cluster crc --kubeconfig /opt/kubeconfig\nerr     : Process exited with status 1\\n - sleeping 1s"
time="2021-01-30T15:26:26+01:00" level=debug msg="retry loop: attempt 1"
time="2021-01-30T15:26:26+01:00" level=debug msg="About to run SSH command:\noc get nodes --context admin --cluster crc --kubeconfig /opt/kubeconfig"
time="2021-01-30T15:26:27+01:00" level=debug msg="SSH command results: err: Process exited with status 1, output: "
time="2021-01-30T15:26:27+01:00" level=debug msg="The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port?\n"
time="2021-01-30T15:26:27+01:00" level=debug msg="error: Temporary error: ssh command error:\ncommand : oc get nodes --context admin --cluster crc --kubeconfig /opt/kubeconfig\nerr     : Process exited with status 1\\n - sleeping 1s"
time="2021-01-30T15:26:28+01:00" level=debug msg="retry loop: attempt 2"
time="2021-01-30T15:26:28+01:00" level=debug msg="About to run SSH command:\noc get nodes --context admin --cluster crc --kubeconfig /opt/kubeconfig"
time="2021-01-30T15:26:28+01:00" level=debug msg="SSH command results: err: Process exited with status 1, output: "
time="2021-01-30T15:26:28+01:00" level=debug msg="The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port?\n"
time="2021-01-30T15:26:28+01:00" level=debug msg="error: Temporary error: ssh command error:\ncommand : oc get nodes --context admin --cluster crc --kubeconfig /opt/kubeconfig\nerr     : Process exited with status 1\\n - sleeping 1s"
time="2021-01-30T15:26:29+01:00" level=debug msg="retry loop: attempt 3"
time="2021-01-30T15:26:29+01:00" level=debug msg="About to run SSH command:\noc get nodes --context admin --cluster crc --kubeconfig /opt/kubeconfig"
time="2021-01-30T15:26:51+01:00" level=debug msg="SSH command results: err: Process exited with status 1, output: "
time="2021-01-30T15:26:51+01:00" level=debug msg="The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port?\n"
time="2021-01-30T15:26:51+01:00" level=debug msg="error: Temporary error: ssh command error:\ncommand : oc get nodes --context admin --cluster crc --kubeconfig /opt/kubeconfig\nerr     : Process exited with status 1\\n - sleeping 1s"
time="2021-01-30T15:26:52+01:00" level=debug msg="retry loop: attempt 4"
`
The result is that sooner or later the number of retries of oc get nodes is exhausted. I could still ssh into the VM but as you can see from the screenshot of the crictl above half or more of the pods are missing. The etcd pod yamls as described in #1888 are ok though I am not clear why there is an etcd-pod-4 in the broken environment, the new environment (see below) has only etdc-pod-2 and etcd-pod-3. 

I ran out of time (as stated I need the env for a demo) and decided re-installing was quicker. 

In the newly installed environment you can see the key is correctly copied and the etcd and apiserver start correctly. `"About to run SSH command:\ncat /home/core/.ssh/authorized_keys"
time="2021-02-05T12:26:48+01:00" level=debug msg="SSH command results: err: <nil>, output: ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAH66aUP4A3g3scw89p5YITSyDnCQRRFRW57AsIreEqfjorVkU0j+ZDF5t8OsRGO+oEnVVm4QoJyJ/IiKEacyKA3TgAJPkpaccHMO9pDt6AyAdMf4euCU0WxQsKoT7ZDt3ZjOb6oAbZDF+jMj1oDmWtVMONOV31Nvd2/60sdSXt2KvHRdQ== core\n"
time="2021-02-05T12:26:48+01:00" level=info msg="Updating authorized keys ..."
time="2021-02-05T12:26:48+01:00" level=debug msg="About to run SSH command:\necho 'ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBABIPq9UVMaQNO4WtZZ0QK1yM9fMndpyAADV+sEWO1LNo720VpLHWYZlpXfN3TJsWFBJwe+1lgD/OMtgdbze8/MmywETsxu5Y03FbMsIv6ludwFCPgXQeBvSU1wZ9wxlbRPycuJPBAhEjWAQzAayXqFldEBJqr9gnJciIGHbvjBaEVCUhA==\n' > /home/core/.ssh/authorized_keys; chmod 644 /home/core/.ssh/authorized_keys"
time="2021-02-05T12:26:48+01:00" level=debug msg="SSH command results: err: <nil>, output: "
time="2021-02-05T12:26:48+01:00" level=info msg="Copying kubeconfig file to instance dir ..."
time="2021-02-05T12:26:48+01:00" level=debug msg="Copying '/Users/sean/.crc/cache/crc_hyperkit_4.6.9/kubeconfig' to '/Users/sean/.crc/machines/crc/kubeconfig'"
time="2021-02-05T12:26:48+01:00" level=debug msg="About to run SSH command:\nsudo xfs_growfs / >/dev/null"
`
Hope this helps. If you need the full logs let me know.
