### ISSUE TITLE
Add more values for `network-mode` config key

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#1945]
`network-mode` valid values are `default` or `vsock`. We need another name for the `default` mode as the current plan is that `vsock` becomes the default in the future.

**Comment by gbraad** [comment]
All I could think of was `legacy` or perhaps more informative `bridged` or `switched`, but this kinda based on the hypervisor... and `native` is also not the right name.

**Comment by cfergeau** [comment]
`bridged` sounds good to me, but not sure how good this name is on Windows?

**Comment by gbraad** [comment]
Workable...

**Comment by cfergeau** [comment]
Another possibility for the naming could be `network-mode`: `user` (=`vsock`) and `system`/`kernel` (=`default`).
