### ISSUE TITLE
CRC --Sporadically stops in nested virtualization environment (CRC on VMWare Workstation Pro running Centos8 on Windows Enterprise)

### ISSUE THREAD

**Issue by pthopa** [code-ready/crc#1965]
### General information

  * OS: Linux
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  NOTE: crc is running inside a VMWare Workstation Pro VM running guest os of centos8. The host os is Windows Enterprise.

## CRC version
```bash
# Put the output of `crc version`
CodeReady Containers version: 1.21.0+68a4cdd7
OpenShift version: 4.6.9 (embedded in executable)
  
## CRC status
```bash
# Put the output of `crc status`
CRC VM:          Running
OpenShift:       Starting (v4.6.9)
Disk Usage:      17.15GB of 32.72GB (Inside the CRC VM)
Cache Usage:     13.35GB
Cache Directory: /home/pthopa/.crc/cache
```

## CRC config
```bash
# Put the output of `crc config view`
```
- consent-telemetry                     : no
- 
## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"

### Steps to reproduce

  1. crc start  --> crc starts fine.. and i am able to bring up the cluster and deploy pods
  2. but after a few minutes, the crc stops and i not be able to connect to the cluster
  3. i cannot access the webconsole for openshift..  WhenI try running, "oc get po" from the command line (which just a min ago worked) now does not and I get the following error message
 **error: You must be logged in to the server (Unauthorized)**
 4. I I retry in a few mins, it works again briefly.

### Expected
crc should work continuously

### Actual
frequently crc seems to crash/stop running

### Logs

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

https://gist.github.com/pthopa/7a21d0b4892d78810b4a6d4f729a40a7

**Comment by gbraad** [comment]
Nested setups aren't supported as they introduce uncertainties when different hypervisors are used.
