### ISSUE TITLE
Use `crc-developer` or `crc-admin` context for some of e2e tests

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#1966]
In our e2e tests we are not testing the oc context switch and it should be tested to make sure the feature is working as expected.

**Comment by cfergeau** [comment]
Seems to be causing CI failures in #1980?

**Comment by guillaumerose** [comment]
Should we ensure authentication is working before the end of crc start ? Right now, when crc start ends, the cluster is maybe 50% of the time for me not working (console and auth).

**Comment by guillaumerose** [comment]
I added 5min timeout to try and it said ok all operators up. Just the time to type a new command, 3-4 operators were restarting..
