### ISSUE TITLE
Remove bundle option in the config file, keep it only for crc start command

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#1970]
The bundle option is meant for development only. We should hide it (or remove it) as much as we can. 

It is useful only in `crc start` command. We can remove it from other locations esp. the config file.

**Comment by praveenkumar** [comment]
I think if we have option on start then it is better to have as part of config also because bundle generation user can use generated bundle also with released crc binary?

**Comment by guillaumerose** [comment]
Yes you're right. At the end, this can be the "selected bundle" or "default bundle to use" when we will have multiples.
