### ISSUE TITLE
[BUG] Error starting crc using the pkg distributable

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/crc#1976]
### General information

  * OS: macOS
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it Yes
  * Running CRC on: Baremetal-Server

## CRC version
```bash
CodeReady Containers version: 1.22.0+f51e589a
OpenShift version: 4.6.15 (not embedded in executable)
```

## Host Operating System
```bash
ProductName:	Mac OS X
ProductVersion:	10.15.1
BuildVersion:	19B88
```
### SIP information
```bash
System Integrity Protection status: enabled.
```

### Steps to reproduce from cmd

  1. Install crc from pkg with cmd: sudo installer -pkg 1.22.0-crc-installer-macos-1.22.0-amd64.pkg -target /
  or
      Install crc from pkg with gui (double click on the pkg icon)
  2. crc setup
  3. crc config set pull-secret-file ~/pull-secret
  4. crc start --log-level debug

### Expected

Cluster will start properly

### Actual

crc start exit with error

### Logs

[Error log](https://gist.github.com/adrianriobo/6f6a3856935ae42856966273cade7118#file-bug-error-starting-crc-using-the-pkg-distributable)

Also from dmesg:

```bash
CODE SIGNING: 37330[hyperkit] vm_map_protect can't have both write and exec at the same time
```

### Extra info

As commented with @praveenkumar may relevant to this: https://developer.apple.com/forums/thread/129025

**Comment by guillaumerose** [comment]
An entitlement was missing. It will be easier to ship the same hyperkit as Docker Desktop.
We are already using the one built by their CI. It's better to trust their supply chain until we build it.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.application-identifier</key>
    <string>9BNSXJN65R.com.docker.docker</string>
    <key>com.apple.security.app-sandbox</key>
    <false/>
    <key>com.apple.security.application-groups</key>
    <array>
        <string>group.com.docker</string>
    </array>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    <key>com.apple.security.hypervisor</key>
    <true/>
</dict>
</plist>
```

**Comment by guillaumerose** [comment]
Fixed with the correct entitlements
