### ISSUE TITLE
crc start fails with:  Failed to run 'virsh capabilities': exit status 1

### ISSUE THREAD

**Issue by f087704** [code-ready/crc#1994]
hello, trying to setup CodeReady on my laptop Thinkpad T460:
Red Hat Enterprise Linux Workstation release 7.9 (Maipo)
crc version
CodeReady Containers version: 1.22.0+6faff76f
OpenShift version: 4.6.15 (embedded in executable)

crc setup completes fine

crc start fails with error:
crc start
INFO Checking if running as non-root              
INFO Checking if podman remote executable is cached 
INFO Checking if admin-helper executable is cached 
INFO Checking minimum RAM requirements            
INFO Checking if Virtualization is enabled        
INFO Checking if KVM is enabled                   
INFO Checking if libvirt is installed             
WARN Preflight checks failed during `crc start`, please try to run `crc setup` first in case you haven't done so yet 
Failed to run 'virsh capabilities': exit status 1

When I try to run the command from my user :+1
virsh capabilities
error: failed to connect to the hypervisor
error: Cannot recv data: Connection reset by peer

Works fine with SUDO, so must be an authorization problem :+1: 
sudo virsh capabilities
<capabilities>

  <host>
    <uuid>fe466fcc-2f8c-11b2-a85c-aeb0364c4ff7</uuid>
    <cpu>
      <arch>x86_64</arch>
      <model>Skylake-Client-IBRS</model>

I already checked the following are in /etc/libvirt/libvirtd.conf
#unix_sock_group = "libvirt"
#unix_sock_ro_perms = "0777"
#unix_sock_rw_perms = "0770"

Any help appreciated

**Comment by praveenkumar** [comment]
@f087704 Please use issue template to create the issue, it provide us more info to debug the issue https://github.com/code-ready/crc/issues/new?assignees=&labels=kind%2Fbug&template=bug_report.md&title=%5BBUG%5D

**Comment by cfergeau** [comment]
It's unexpected that `virsh capabilities` fails with permissions issues. Could you try `virsh uri` or `virsh list --all` to see if you get the same permission issues?

**Comment by sonawane-shashikant** [comment]
I faced the same issue.
$ crc start
INFO Checking if running as non-root
INFO Checking if podman remote executable is cached
INFO Checking if admin-helper executable is cached
INFO Checking minimum RAM requirements
INFO Checking if Virtualization is enabled
INFO Checking if KVM is enabled
INFO Checking if libvirt is installed
WARN Preflight checks failed during `crc start`, please try to run `crc setup` first in case you haven't done so yet
Failed to run 'virsh capabilities': exit status 1

$ virsh uri
error: failed to connect to the hypervisor
error: Failed to connect socket to '/run/user/1001/libvirt/libvirt-sock': No such file or directory

$ sudo virsh uri
qemu:///system

**Comment by cfergeau** [comment]
What OS/distribution are you running?

**Comment by f087704** [comment]
Hello I fixed my issue (on RHEL 7.9) with the following export before start :
export LIBVIRT_DEFAULT_URI=qemu:///system
as documented in https://serverfault.com/questions/1000937/virsh-failed-to-connect-to-hypervisor-as-user

**Comment by f087704** [comment]
Thanks for the support. Will close

**Comment by cfergeau** [comment]
`virsh -c qemu:///session capabilities` is very unexpected, so I'd like to understand better what's going on. This command is supposed to automatically start a  `libvirtd` daemon if needed.

**Comment by f087704** [comment]
sure. here you go 

rpm -qa libvirt*                                                                                                                              
libvirt-daemon-driver-storage-rbd-4.5.0-36.el7_9.3.x86_64                                                                                                           
libvirt-daemon-driver-network-4.5.0-36.el7_9.3.x86_64                                                                                                               
libvirt-daemon-driver-storage-disk-4.5.0-36.el7_9.3.x86_64                                                                                                          
libvirt-bash-completion-4.5.0-36.el7_9.3.x86_64                                                                                                                     
libvirt-daemon-driver-nodedev-4.5.0-36.el7_9.3.x86_64                                                                                                               
libvirt-glib-1.0.0-1.el7.x86_64
libvirt-daemon-driver-storage-mpath-4.5.0-36.el7_9.3.x86_64
libvirt-daemon-config-network-4.5.0-36.el7_9.3.x86_64
libvirt-daemon-driver-storage-4.5.0-36.el7_9.3.x86_64
libvirt-daemon-driver-interface-4.5.0-36.el7_9.3.x86_64
libvirt-python-4.5.0-1.el7.x86_64
libvirt-daemon-driver-storage-iscsi-4.5.0-36.el7_9.3.x86_64
libvirt-libs-4.5.0-36.el7_9.3.x86_64
libvirt-daemon-driver-storage-core-4.5.0-36.el7_9.3.x86_64
libvirt-daemon-config-nwfilter-4.5.0-36.el7_9.3.x86_64
libvirt-daemon-driver-storage-scsi-4.5.0-36.el7_9.3.x86_64
libvirt-daemon-driver-qemu-4.5.0-36.el7_9.3.x86_64
libvirt-daemon-driver-storage-gluster-4.5.0-36.el7_9.3.x86_64
libvirt-daemon-kvm-4.5.0-36.el7_9.3.x86_64
libvirt-daemon-driver-secret-4.5.0-36.el7_9.3.x86_64
libvirt-daemon-driver-storage-logical-4.5.0-36.el7_9.3.x86_64
libvirt-client-4.5.0-36.el7_9.3.x86_64
libvirt-daemon-4.5.0-36.el7_9.3.x86_64
libvirt-daemon-driver-lxc-4.5.0-36.el7_9.3.x86_64
libvirt-4.5.0-36.el7_9.3.x86_64
libvirt-daemon-driver-nwfilter-4.5.0-36.el7_9.3.x86_64

laptop Thinkpad T460

cat /etc/redhat-release 
Red Hat Enterprise Linux Workstation release 7.9 (Maipo)

uname -a
Linux xxxxxxxx 3.10.0-1160.11.1.el7.x86_64 #1 SMP Mon Nov 30 13:05:31 EST 2020 x86_64 x86_64 x86_64 GNU/Linux


crc version
CodeReady Containers version: 1.22.0+6faff76f
OpenShift version: 4.6.15 (embedded in executable)

**Comment by cfergeau** [comment]
Do you know if there's any changes made to your system which could prevent your user to start the libvirt daemon? After running `virsh -c qemu:///session uri`, there should be a `libvirtd` process running as your user, I think the automatic start of this daemon is what is not working as expected. If you run it manually, is this working better?
```
$ /usr/sbin/libvirtd -d
$ virsh -c qemu:///session uri
```

**Comment by f087704** [comment]
Hello, yes it's a company laptop, preset to run some windows KVM guests, so I guess there are a bunch of security rules enforced on top of defaults

**Comment by cfergeau** [comment]
Ok, thanks for the followup, we'll have to figure out a way to handle this better. I'm reopening the issue so that we remember to fix this for good, it should work without manually setting `LIBVIRT_DEFAULT_URI`

**Comment by cfergeau** [comment]
Summary of the issue, `virsh capabilities` does not work on some hardened corporate laptops, I suspect because regular users can't start `libvirtd` or something like this. This breaks `qemu:///session`, which is what `virsh capabilities` will be talking to by default.
We should use `virsh -c qemu:///system capabilities` instead, but there is a chicken and egg problem as we need libvirt to be installed before adding the user to the libvirt group for `qemu:///system` access, but we use `virsh capabilities` to determine whether we need to install libvirt.

**Comment by cfergeau** [comment]
Hopefully `virsh --readonly  -c qemu:///system capabilities` will be an option which won't require the user to be part of the libvirt group to be usable.

**Comment by TomRoss** [comment]
I have the same problem on Fedora 34 with CRC 4.8.4.

**Comment by cfergeau** [comment]
Please open a new issue and provide the information the issue template asks for, as this specific issue should be fixed, so this could be something new that you are seeing.
