### ISSUE TITLE
[BUG] (Windows) Access is denied on bundle extraction during setup; rename from tmp to final location

### ISSUE THREAD

**Issue by ssaranathan** [code-ready/crc#2004]
### General information

  * OS: Windows
  * Hypervisor: Hyper-V 
  * Did you run `crc setup` before starting it : Yes
  * Running CRC on: Laptop

## CRC version
```bash
# Put `crc version` output here
CodeReady Containers version: 1.22.0+6faff76f
OpenShift version: 4.6.15 (embedded in executable)
```
  
## CRC status
```bash
# Put `crc status --log-level debug` output here

DEBU CodeReady Containers version: 1.22.0+6faff76f
DEBU OpenShift version: 4.6.15 (embedded in executable)
DEBU Running 'crc status'
DEBU Checking file: C:\Users\xxx\.crc\machines\crc\.crc-exist
Machine does not exist. Use 'crc start' to create it
```

## CRC config
```bash
# Put `crc config view` output here 
consent-telemetry                     : yes
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows

Host Name:                 LAPTOP-P3IVLEKN
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19041 N/A Build 19041
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Windows User
Registered Organization:
Product ID:                00330-80000-00000-AA885
Original Install Date:     9/30/2020, 10:03:41 AM
System Boot Time:          2/13/2021, 7:05:04 PM
System Manufacturer:       LENOVO
System Model:              20EQS3B400
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 94 Stepping 3 GenuineIntel ~2712 Mhz
BIOS Version:              LENOVO N1EET62W (1.35 ), 11/10/2016
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     32,602 MB
Available Physical Memory: 18,472 MB
Virtual Memory: Max Size:  37,466 MB
Virtual Memory: Available: 20,946 MB
Virtual Memory: In Use:    16,520 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\LAPTOP-P3IVLEKN
Hotfix(s):                 9 Hotfix(s) Installed.
                           [01]: KB4578968
                           [02]: KB4601050
                           [03]: KB4561600
                           [04]: KB4577266
                           [05]: KB4580325
                           [06]: KB4586864
                           [07]: KB4593175
                           [08]: KB4598481
                           [09]: KB4601319
Network Card(s):           6 NIC(s) Installed.
                           [01]: Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows x64
                                 Connection Name: Ethernet 2
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 9.160.35.244
                                 [02]: fe80::742c:3013:b419:85a7
                           [02]: Intel(R) Ethernet Connection (2) I219-LM
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [03]: Intel(R) Dual Band Wireless-AC 8260
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.181
                                 [02]: fe80::4df:b592:2c12:dd4a
                           [04]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (Default Switch) 2
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 172.23.128.1
                                 [02]: fe80::31bf:a33f:8820:233e
                           [05]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [06]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (WSL)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 172.28.176.1
                                 [02]: fe80::1cf8:a3fb:8c8b:d0d5
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```

### Steps to reproduce

  1. crc setup
  2. 
  3. 
  4. 

### Expected
crc setup should have worked fine

### Actual
(base) PS C:\WINDOWS\system32> crc setup
INFO Checking if podman remote executable is cached
INFO Checking if admin-helper executable is cached
INFO Checking if CRC bundle is extracted in '$HOME/.crc'
INFO Checking if C:\Users\xxx\.crc\cache\crc_hyperv_4.6.15.crcbundle exists
INFO Extracting bundle from the CRC executable
INFO Ensuring directory C:\Users\xxx\.crc\cache exists
INFO Uncompressing crc_hyperv_4.6.15.crcbundle
crc.vhdx: 12.52 GiB / 12.52 GiB [-----------------------------------------------------------------------------] 100.00%
rename C:\Users\xxx\.crc\cache\tmp-extract\crc_hyperv_4.6.15 C:\Users\xxxx\.crc\cache\crc_hyperv_4.6.15: Access is denied.

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by gbraad** [comment]
> C:\Users\xxxx.crc\cache\crc_hyperv_4.6.15: Access is denied.

please check if you have permission to write or read from the here?
we have not seen this error before.

At least Enterprise has bene tested to work

**Comment by ssaranathan** [comment]
Hi @gbraad , Yes, this folder is automatically created during the extraction process when I run crc setup

Extracting embedded bundle crc_hyperv_4.6.15.crcbundle to C:\Users\xxx\.crc\cache

**Comment by gbraad** [comment]
Can you rename it by hand?
And run setup again after this to confirm

**Comment by ssaranathan** [comment]
Hi @gbraad , I tried that.. but during the extraction process the folder is locked (tmp-extract) and right after that it shows the message and the folder (tmp-extract) is deleted by the setup process.  It happens so quickly that I am unable to do that.

**Comment by gbraad** [comment]
Perhaps something else interferes, like a virus scanner?
I believe the is access denied due to the folder being locked by another process

**Comment by ssaranathan** [comment]
I am not very sure.. No other process is accessing that folder.  Also, the virus protection is managed by our corporate team and we cannot turn it off ..

**Comment by gbraad** [comment]
What might happen here is that the folder gets accessed to inspect the file operations and integrity of the file (by the antivirus) and when we do the rename it gets denied as the file is accessed. You could try to copy the file over from another machine or extract this manually; the `.crcbundle` is essentially an archive,

**Comment by ssaranathan** [comment]
Thanks @gbraad.  How do I extract the .crcbundle manually ?

**Comment by gbraad** [comment]
The `crcbundle` is a zstd compressed tarball; a tool like https://github.com/mcmilk/7-Zip-zstd can be decompressed.

**Comment by wwwild** [comment]
I experienced a similar error and had to combine the 7zip codec steps with cygwin's `zstd` command:

From the `.crc\cache` folder:
```
zstd --decompress crc_hyperv_4.6.15.crcbundle -o crc_hyperv_4.6.15.zst
7z x crc_hyperv_4.6.15.zst 
...

**Comment by gbraad** [comment]
@wwwild can you describe more about your environment?

**Comment by gbraad** [comment]
I guess it goes wrong here: https://github.com/code-ready/crc/blob/f148ddc8687689a97c9b7e6baac4697c17b3547b/pkg/crc/machine/bundle/repository.go#L110

**Comment by wwwild** [comment]
I experienced a similar error and had to combine the 7zip codec steps with cygwin's `zstd` command:

From the `.crc\cache` folder:
```
zstd --decompress crc_hyperv_4.6.15.crcbundle -o crc_hyperv_4.6.15.zst
7z x crc_hyperv_4.6.15.zst 
...

**Comment by juhanevalainen** [comment]
Thanks, that helped.  To clarify, is this rename effectively the last step in this 'crc setup' execution then?   Just wondering if the suggested manual extraction is all that is needed to overcome this current access issue now.

**Comment by cfergeau** [comment]
> Hi @gbraad , Yes, this folder is automatically created during the extraction process when I run crc setup
> 
> Extracting embedded bundle crc_hyperv_4.6.15.crcbundle to C:\Users\xxx.crc\cache
> 
> Error happens when it tries to rename:
> 
> rename C:\Users\xxx.crc\cache\tmp-extract\crc_hyperv_4.6.15 C:\Users\xxx.crc\cache\crc_hyperv_4.6.15: Access is denied.

Just to be sure since this was edited. Are the paths in the error message starting with `C:\Users\xxx.crc\cache` or are they `C:\Users\xxx\.crc\cache` (with a `\` between `xxx` and `.crc`)? I noticed the same pattern in #2087.

**Comment by gbraad** [comment]
Perhaps an error with the environment variables

**Comment by ClaudioRetico** [comment]
Same problem.

**Comment by guillaumerose** [comment]
Are you using an antivirus? If yes, what is the name of the antivirus?

**Comment by ClaudioRetico** [comment]
I use windows security (company policy) 
![image](https://user-images.githubusercontent.com/28264701/111158990-e47f4000-8598-11eb-823f-4647c0021211.png)

**Comment by juhanevalainen** [comment]
I had the same error too, on my corporate windows10 system. I ended up unzipping with the tools mentioned here and that worked fine.

**Comment by ClaudioRetico** [comment]
SOLVED: you need to exclude the C:\Users\xxx\.crc directory from antivirus (i.e. in Windows Security).

**Comment by guillaumerose** [comment]
This code changed recently. Previously, if the user hits ctrl+c during bundle extraction, the bundle directory could be corrupted. Now we unpack to a temporary directory and then rename. 

It seems that we are unpacking and renaming the content of the bundle too fast for the antivirus.

A quick fix on crc side is maybe to add a retry loop. Long term, we should unpack at the right location.

**Comment by guillaumerose** [comment]
I made a PR with a workaround. Can you give it a try? http://artifacts.ci.centos.org/minishift/crc/pr/2102/windows-amd64/

How to test:
* Delete the bundle **directory** in ~/.crc/cache
* Run `crc start -b <path to the .crcbundle file - it should be in ~/.crc/cache>`

**Comment by praveenkumar** [comment]
@serenamarie125 @juhanevalainen @ClaudioRetico Can you folks try https://github.com/code-ready/crc/issues/2004#issuecomment-800034547 and let us know if that solve issue for you without any other workaround?

**Comment by juhanevalainen** [comment]
Yes sure, this is what happens..., do I need to grab a new copy of that bundle first right?

**D:\openshift\crc>crc start -b c:\Users\JuhaNevalainen\.crc\cache --log-level debug
DEBU CodeReady Containers version: 1.23.1+4d63a261
DEBU OpenShift version: 4.7.1 (not embedded in executable)
DEBU Running 'crc start'
DEBU Total memory of system is 34213019648 bytes
WARN Using unsupported bundle cache
DEBU No new version available. The latest version is 1.23.1
DEBU [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM crc ).state
                   ] : Running
DEBU [stderr =====>] :
DEBU Checking file: C:\Users\JuhaNevalainen\.crc\machines\crc\.crc-exist
Error loading bundle metadata: could not find cached bundle info in C:\Users\JuhaNevalainen\.crc\cache\crc_hyperv_4.6.15: CreateFile C:\Users\JuhaNevalainen\.crc\cache\crc_hyperv_4.6.15: The system cannot find the file specified.

D:\openshift\crc>dir c:\users\JuhaNevalainen\.crc\cache
 Volume in drive C is Windows
 Volume Serial Number is D019-D1C8**

 Directory of c:\users\JuhaNevalainen\.crc\cache

17/03/2021  15.10    <DIR>          .
17/03/2021  15.10    <DIR>          ..
03/03/2021  13.09     2 596 738 289 crc_hyperv_4.6.15.crcbundle
               1 File(s)  2 596 738 289 bytes
               2 Dir(s)  92 692 717 568 bytes free

D:\openshift\crc>

**Comment by juhanevalainen** [comment]
Still the same result:
```
D:\openshift\crc>crc start -b c:\Users\JuhaNevalainen\.crc\cache\crc_hyperv_4.6.15.crcbundle --log-level debug
DEBU CodeReady Containers version: 1.23.1+4d63a261
DEBU OpenShift version: 4.7.1 (not embedded in executable)
DEBU Running 'crc start'
DEBU Total memory of system is 34213019648 bytes
WARN Using unsupported bundle crc_hyperv_4.6.15.crcbundle
DEBU No new version available. The latest version is 1.23.1
DEBU [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM crc ).state
                   ] : Running
DEBU [stderr =====>] :
DEBU Checking file: C:\Users\JuhaNevalainen\.crc\machines\crc\.crc-exist
Error loading bundle metadata: could not find cached bundle info in C:\Users\JuhaNevalainen\.crc\cache\crc_hyperv_4.6.15: CreateFile C:\Users\JuhaNevalainen\.crc\cache\crc_hyperv_4.6.15: The system cannot find the file specified.
```

**Comment by guillaumerose** [comment]
You need to delete the running VM. Do `crc delete -f` before.

**Comment by praveenkumar** [comment]
> Error loading bundle metadata: could not find cached bundle info in C:\Users\JuhaNevalainen\.crc\cache\crc_hyperv_4.6.15: CreateFile C:\Users\JuhaNevalainen\.crc\cache\crc_hyperv_4.6.15: The system cannot find the file specified.

@juhanevalainen can you check what bundle is present in your `C:\Users\JuhaNevalainen\.crc\cache\`  and use that with `-b` option after deleting existing VM.

**Comment by juhanevalainen** [comment]
@guillaumerose many thanks, that helped.  Its going well beyond those errors now...we will know soon.

**Comment by guillaumerose** [comment]
Was the bundle extracted correctly during the `crc start` ? I guess yes. 
If you can confirm that, I merge the quick fix for the next release.

**Comment by juhanevalainen** [comment]
Yes that cache subfolder now exists there and it seemed all fine in the debugger output too.

**Comment by EgorSemenov** [comment]
> I had the same error too, on my corporate windows10 system. I ended up unzipping with the tools mentioned here and that worked fine.

Could you post please, which tools and commands did u use?

**Comment by 3nigm4** [comment]
> > I had the same error too, on my corporate windows10 system. I ended up unzipping with the tools mentioned here and that worked fine.
> 
> @juhanevalainen
> Could you post please, which tools and commands did u use?

I recommend to use the WSL and the codecs for 7z to solve the problem

In your wsl linux shell:
`sudo apt install zstd`
`cd | wslpath "$(wslvar USERPROFILE)/.crc/cache"`
`zstd --decompress crc_hyperv_4.7.2.crcbundle -o crc_hyperv_4.7.2.zst` or whatever the version will be, when you do this

Now in windows create the folder `Codecs` in your 7-zip install directory like so:
`C:\Program Files\7-Zip\Codecs`

Grab this archive or newer: https://github.com/mcmilk/7-Zip-zstd/releases/download/19.00-v1.4.9-R2/Codecs-x64.7z

When you extract it you'll also find a `Codecs` folder. Copy paste only the dlls into the folder you created before.
In a new cmd/powershell window:
`cd C:\Users\$env:UserName\.crc\cache\`
`7z x .\crc_hyperv_4.7.2.zst`

After that you should be able to:

`crc setup`
`crc start`

**Comment by juhanevalainen** [comment]
@3nigm4 yes sure so I used this zstd that I got form links above and then ran 7z afterwards.

However note that with the new bundle fix now released none of that should be needed anymore.  

[zstd.zip](https://github.com/code-ready/crc/files/6318895/zstd.zip)

**Comment by cfergeau** [comment]
The code talked about in this commit has been merged in https://github.com/code-ready/crc/commit/2e89ea8f3903bee58187e35600516331447ac854 and this hasn't been reported recently, closing this.
