### ISSUE TITLE
[Segment] Mask  PII data before sending to segment

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#2006]
We are getting username as part of the error when it contains the path, better to mask it.

```
Error starting stopped VM: virError(Code=38, Domain=18, Message='Cannot access storage file '/home/<username>/.crc/machines/crc/crc.qcow2' (as uid:64055, gid:129): Permission denied')
```

**Comment by jsliacan** [comment]
Same for errors of this form:
```bash
<username> not part of libvirtd group
```

**Comment by cfergeau** [comment]
Suggestion from some internal discussion:
> we probably can add `telemetry.SetError()`, and in that helper, do `s/os.GetHome()/$HOME` `s/os.GetUserName()/$USER`

**Comment by cfergeau** [comment]
Username and homedir are now being hidden, let's close this and open more specific issues if we need to hide more.
