### ISSUE TITLE
crc1.22 OpenShift cluster running, but 'crc status' always reports "Starting"

### ISSUE THREAD

**Issue by rscher** [code-ready/crc#2013]
### General information

  * OS: Linux
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
# Put the output of `crc version`

$ crc version
CodeReady Containers version: 1.22.0+6faff76f
OpenShift version: 4.6.15 (embedded in executable)

  
## CRC status
```bash
# Put the output of `crc status`
$ crc status
CRC VM:          Running
OpenShift:       Starting (v4.6.15)
Disk Usage:      21.12GB of 32.72GB (Inside the CRC VM)
Cache Usage:     14.31GB
Cache Directory: /home/crcuser/.crc/cache

## CRC config
```bash
# Put the output of `crc config view`
$ crc config view
- consent-telemetry                 : no
- cpus                                        : 32
- memory                                : 32000
- pull-secret-file                      : /home/crcuser/pull-secret.txt


## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"


### Steps to reproduce

  1. crc setup;crc start --log-level debug
  2. crc status: OpenShift:   Starting (v4.6.15)
  3. able to use cluster, but incorrect crc status 
  4. $  $(echo  "oc login https://api.crc.testing:6443 -u kubeadmin -p"   $(crc console --credentials | grep 'kubeadmin' | gawk  '{ print $12 }') )
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

Login successful.

You have access to 59 projects, the list has been suppressed. You can list all projects with ' projects'

Using project "odm8105".



### Expected
$ crc status
CRC VM:          Running
OpenShift:       Running (v4.6.15)
Disk Usage:      20.97GB of 32.72GB (Inside the CRC VM)
Cache Usage:     14.31GB
Cache Directory: /home/crcuser/.crc/cache

### Actual
$ crc status
CRC VM:          Running
OpenShift:       Starting (v4.6.15)
Disk Usage:      20.97GB of 32.72GB (Inside the CRC VM)
Cache Usage:     14.31GB
Cache Directory: /home/crcuser/.crc/cache

### Logs

https://gist.githubusercontent.com/rscher/3152cf5d534af0b53ce11d22626dcc8d/raw/3caeb86ca1e7ffa78226b28b3afea2c73e017f7c/crc.log

**Comment by cfergeau** [comment]
After logging in as `kubeadmin`  with `oc`, can you paste the output of `oc get co` from a running cluster showing `Starting` instead of `Running`?

**Comment by rscher** [comment]
[crcuser@crc2 ~]$ oc get co
NAME                                       VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE
authentication                             4.6.15    True        False         False      39h
cloud-credential                           4.6.15    True        False         False      17d
cluster-autoscaler                         4.6.15    True        False         False      17d
config-operator                            4.6.15    True        False         False      17d
console                                    4.6.15    True        False         False      2d5h
csi-snapshot-controller                    4.6.15    True        False         False      17d
dns                                        4.6.15    True        False         False      2d5h
etcd                                       4.6.15    True        False         False      17d
image-registry                             4.6.15    True        False         False      2d5h
ingress                                    4.6.15    True        False         False      16d
insights                                   4.6.15    True        False         False      17d
kube-apiserver                             4.6.15    True        False         False      17d
kube-controller-manager                    4.6.15    True        False         False      17d
kube-scheduler                             4.6.15    True        True          True       17d
kube-storage-version-migrator              4.6.15    True        False         False      17d
machine-api                                4.6.15    True        False         False      17d
machine-approver                           4.6.15    True        False         False      17d
machine-config                             4.6.15    True        False         False      17d
marketplace                                4.6.15    True        False         False      2d5h
monitoring                                 4.6.15    False       True          True       16d
network                                    4.6.15    True        False         False      17d
node-tuning                                4.6.15    True        False         False      2d5h
openshift-apiserver                        4.6.15    True        False         False      2d5h
openshift-controller-manager               4.6.15    False       True          False      35h
openshift-samples                          4.6.15    True        False         False      17d
operator-lifecycle-manager                 4.6.15    True        False         False      17d
operator-lifecycle-manager-catalog         4.6.15    True        False         False      17d
operator-lifecycle-manager-packageserver   4.6.15    True        False         False      34h
service-ca                                 4.6.15    True        False         False      17d
storage                                    4.6.15    True        False         False      17d
[crcuser@crc2 ~]$ crc status
CRC VM:          Running
OpenShift:       Starting (v4.6.15)
Disk Usage:      20.21GB of 32.72GB (Inside the CRC VM)
Cache Usage:     14.31GB
Cache Directory: /home/crcuser/.crc/cache

**Comment by praveenkumar** [comment]
@rscher Have you enable the monitoring on this cluster and also can you describe the controller pod which provide us bit an idea why it is in pending state.

**Comment by rscher** [comment]
hello @praveenkumar ,
No I have not, Im using crc 'out of the box', just reporting what I am seeing when using v1.22 in a server-like environment for on-prem testing. Can you advise how to move forward please, as this is becoming a blocking issue for our IBM Cloud Pak testing on OpenShift 4.6 for on-prem envs.
thanks !

**Comment by praveenkumar** [comment]
@rscher Can you also share the pod description and logs which is in the pending state, we will try to see what's causing it?

**Comment by gbraad** [comment]
@rscher A while back I have sent you an email about this. This is related to how the environment is created
This is likely the same setup as mentioned here: https://github.com/code-ready/crc/issues/1830 ?

**Comment by rscher** [comment]
@gbraad @praveenkumar @timroster
Hey guys, this is this same environment as #1830, but that issue was reported on crc v.1.20.
It seems crc v1.22 has some improvements and was able to get it work 1 time- crc status reported "running" ,
and I deployed a hefty Cloud Pak application (5 pods) which stayed up and running for 8 days. 
Others also have reported some success whether  within a "nested" virtual config such as fyre/fyre-protected in IBM or directly onto bare-metal servers.
The support statement that Red Hat gave awhile back that using crc's embedded VM (qemu)  within a VM is not supported 
may have applied to earlier versions, but it certainly is not the case now.

It is running and quite stable in another virtual env for 8 months now (VMware RHEL VM's on Xeon-based processors).
The issue we are experiencing now on v1.22 in the fyre VPC env is that of instability. It appears to run successfully at times and for certain configurations ( MTBF with a heavy K8S/DB2-based application  running was as high as 8 days). 
For some reason, I am seeing this condition (different than #1830) where CRC status is stuck in a pending state and reports  OpenShift: Starting (v4.6.15), but I am able to login and perform tasks.
the debug log shows  this ...
```
time="2021-02-19T10:08:34-08:00" level=debug msg="kube-scheduler operator is degraded, Reason: NodeInstaller_InstallerPodFailed"
time="2021-02-19T10:08:34-08:00" level=debug msg="kube-scheduler operator is still progressing, Reason: NodeInstaller"
time="2021-02-19T10:08:34-08:00" level=debug msg="openshift-controller-manager operator is still progressing, Reason: _DesiredStateNotYetAchieved"
time="2021-02-19T10:08:34-08:00" level=debug msg="openshift-controller-manager operator not available, Reason: _NoPodsAvailable"
```
It seems like it's performance-related,  possibly due to greater workloads running in 1.22 than previous versions ? and in this case on less powerful AMD EPYC cpu;s. System Monitor shows on average CPU utilization around 90% with 16 AMD CPU's.
That would also explain why we don't see the same issue with v1.22 in the other  VPC-based env, on  RHEL VM's on Xeon  CPUs. System monitor shows on anywhere from 35-50% CPU utilization with the same workload running on crc 1.22 with 16 Xeon CPUs.

One way this could be tested and possibly proved, is to be able to control which operators and workloads are scheduled to run when crc starts. 

I see no reason to have to run the operators/pods for these namespaces:
marketplace                                
monitoring                                 
openshift-samples                          
operator-lifecycle-manager                 
operator-lifecycle-manager-catalog         
operator-lifecycle-manager-packageserver 

We can enable OLM selectively when there is a need, but I'd like to test out starting crc without the workloads from the 6 namespaces above. 
 How can that be configured ? 

-Russ

**Comment by gbraad** [comment]
> The support statement that Red Hat gave awhile back that using crc's embedded VM (qemu) within a VM is not supported
may have applied to earlier versions, but it certainly is not the case now.

This has not changed. Nested virtualization on a host that is not RHEL (or Fedora) is hard for us to 'support'. Developer tools is provided with community support.

> hefty Cloud Pak application 

Can you please explain what you are trying to achieve here? CRC should not be considered as a replacement for the OpenShift installer. It is only used to provide a developer setup.

> It is running and quite stable in another virtual env for 8 months now (VMware RHEL VM's on Xeon-based processors).

And we have identified this before. This is still in line with the assessment we made about a year ago and last January about the Castle and Fyre environments. The machines that are based on AMD's EPYC had issues running or even starting the CRC vm.


> Others also have reported some success whether within a "nested" virtual config such as fyre/fyre-protected in IBM or directly onto bare-metal servers.

Can you describe the difference in this statement as I am confused to interpret this as : 'some success ... onto bare-metal servers' ?

**Comment by gbraad** [comment]
> I see no reason to have to run the operators/pods for these namespaces:

These are provided as this is all part of the regular payload of OpenShift.

> `marketplace`

non-essential, does not impact performance.

> `monitoring`

Is disabled for CRC, unless this has been re-enabled. This is the only operator we 'scale down;. It is considered essential, but consumes a lot of resources that otherwise will affect use when considering a developers' environment on a notebook. 'disabling' this does not negatively affect the stability of the cluster, but does have side-effects of not registering in the cluster manager.


> `openshift-samples`

non-essential, does not impact performance.

> `operator-lifecycle-manager`
> `operator-lifecycle-manager-catalog`
> `operator-lifecycle-manager-packageserver`

essential for the cluster


> We can enable OLM selectively when there is a need, but I'd like to test out starting crc without the workloads from the 6 namespaces above.
> How can that be configured ?

For this you woiuld have to generate a new bundle using code-ready/snc or restart the same bundle after you scaled these down.

**Comment by gbraad** [comment]
> should not be considered as a replacement for the OpenShift installer.

With this we also mean, do you see the same issues when running this on a cluster that is setup with the openshift-installer ?

> Baremetal

This slightly added confusion to the assessment. Do you see issues on a baremetal server that is setup with RHEL as the host, running CRC? And are these machines Xeon or EPYC based?
