### ISSUE TITLE
Simplify crc status: no virtual machine is equivalent to virtual machine stopped

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#2023]
(opening a discussion)

After a fresh install, `crc status` fails with the error "Machine does not exist. Use 'crc start' to create it".
More annoying: the tray is showing Unknown status.

I have the feeling we could say that the VM is stopped. This is not fundamentally false after all.

```
$ crc status
CRC VM:          Stopped
OpenShift:       Stopped
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     39.55GB
Cache Directory: /home/guillaumerose/.crc/cache
```

Perhaps we could introduce a new state ? Like Inexistent, PendingCreation. 
What should the API answer ?

**Comment by gbraad** [comment]
Currently the daemon throws 500 errors in the case of no VM. I believe this is wrong, as the daemon is able to process the request, just the success should either be false, with an error message, or success, with a clear state of NoVM or Stopped.

**Comment by guillaumerose** [comment]
We did that but only for the API. 
The CLI now the difference between Stopped and no VM.
