### ISSUE TITLE
Running crc setup causes PC to lose internet connection

### ISSUE THREAD

**Issue by noahzheutlin** [code-ready/crc#2024]
Deleting the crc-nm-dnsmasq.conf file in etc/NetworkManager/conf.d and then running systemctl restart NetworkManager fixes the internet connection, but causes other issues within crc.

OS is RHEL 8

**Comment by rohanarora** [comment]
Please consider taking a look at https://github.com/code-ready/crc/issues/1663

**Comment by cfergeau** [comment]
@noahzheutlin Is this still happening? Could you provide more details about the actual breakage you are seeing? I assume DNS resolution issues?
