### ISSUE TITLE
Ellipsis consistency: choose between `word...` or `word ...`

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#2039]
### Steps to reproduce

  1. crc setup
  2. crc start

### Expected

```
INFO Adding user's pull secret to instance disk... 
INFO Verifying validity of the kubelet certificates... 
```

### Actual

```
INFO Adding user's pull secret to instance disk... 
INFO Verifying validity of the kubelet certificates ... 
```

### Description

Three dots are often used in crc: sometimes with a space before, sometimes directly next to the word. We should make a choice! :)

ping @robin-owen

**Comment by robin-owen** [comment]
From a "grammatically correct" standpoint, we should not have a space before the ellipses.

**Comment by cfergeau** [comment]
> From a "grammatically correct" standpoint, we should not have a space before the ellipses.

wikipedia lists various point of views on this https://en.wikipedia.org/wiki/Ellipsis#In_English :) But no spaces look nicer to me!
