### ISSUE TITLE
[BUG] Setup doesn't extract bundle in latest crc 1.23.1

### ISSUE THREAD

**Issue by faysou** [code-ready/crc#2075]
### General information

  * OS: Windows
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop 

## CRC version
```bash
# Put `crc version` output here
```
CodeReady Containers version: 1.23.1+be17b141
OpenShift version: 4.7.0 (not embedded in executable)
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
```
DEBU CodeReady Containers version: 1.23.1+be17b141
DEBU OpenShift version: 4.7.0 (not embedded in executable)
DEBU Running 'crc status'
DEBU Checking file: C:\Users\faysou\.crc\machines\crc\.crc-exist
Machine does not exist. Use 'crc start' to create it

## CRC config
```bash
# Put `crc config view` output here
```
- consent-telemetry                     : yes
- nameserver                            : 8.8.8.8
- pull-secret-file                      : ps
- 
## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```
Host Name:                 DESKTOP-8D64617
OS Name:                   Microsoft Windows 10 Pro Insider Preview
OS Version:                10.0.21327 N/A Build 21327
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          faysou
Registered Organization:
Product ID:                00331-10000-00001-AA745
Original Install Date:     05/03/2021, 18:07:00
System Boot Time:          08/03/2021, 09:35:21
System Manufacturer:       Dell Inc.
System Model:              XPS 13 7390 2-in-1
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 126 Stepping 5 GenuineIntel ~1298 Mhz
BIOS Version:              Dell Inc. 1.7.1, 28/12/2020
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-gb;English (United Kingdom)
Input Locale:              en-gb;English (United Kingdom)
Time Zone:                 (UTC+00:00) Dublin, Edinburgh, Lisbon, London
Total Physical Memory:     32,538 MB
Available Physical Memory: 18,148 MB
Virtual Memory: Max Size:  65,306 MB
Virtual Memory: Available: 45,440 MB
Virtual Memory: In Use:    19,866 MB
Page File Location(s):     E:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-8D64617
Hotfix(s):                 2 Hotfix(s) Installed.
                           [01]: KB5001029
                           [02]: KB5001030
Network Card(s):           6 NIC(s) Installed.
                           [01]: TAP-NordVPN Windows Adapter V9
                                 Connection Name: Ethernet 2
                                 Status:          Media disconnected
                           [02]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (Internal Ethernet Port Windows Phone Emulator Internal Switch)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 169.254.80.80
                                 [02]: fe80::5024:6162:a5f0:422f
                           [03]: Killer(R) Wi-Fi 6 AX1650s 160MHz Wireless Network Adapter (201D2W)
                                 Connection Name: WiFi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.100
                                 [02]: fe80::e9bb:a0b2:9830:5920
                                 [03]: fd00::3c30:6fc:9599:984b
                                 [04]: 2a01:4b00:8492:5100:3c30:6fc:9599:984b
                                 [05]: fd00::e9bb:a0b2:9830:5920
                                 [06]: 2a01:4b00:8492:5100:e9bb:a0b2:9830:5920
                           [04]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [05]: ASIX AX88179 USB 3.0 to Gigabit Ethernet Adapter
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [06]: Nlwt Tun
                                 Connection Name: NordLynx
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

### Steps to reproduce

  1.  crc setup
  2.  crc start
  3. 
  4. 

### Expected
The installation continues.

### Actual
C:\Users\faysou\.crc\cache\crc_hyperv_4.7.0.crcbundle not found, please provide the path to a valid bundle using the -b option
No extraction happens during the setup step. I remember it did in past versions.
The .crc folder has few files after setup, which I don't think is normal.

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by anjannath** [comment]
@faysou The windows binary got changed during the signing process and setup was unable to extract the embedded bundle, (we are trying to release signed binaries also for windows).

we have since fixed the issue and new builds have been uploaded to https://mirror.openshift.com/pub/openshift-v4/clients/crc/latest/

**Comment by faysou** [comment]
Thank you, it works now.
