### ISSUE TITLE
UX change: always have a VM ready to start

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#2085]
crc is a clone a docker-machine. crc has exactly the same UX: start/stop/delete. There is a simplification we miss: machine is made to run multiples VMs, crc is not.

The major issue with the current behaviour, is the weird status before the first start of the VM. Currently `crc status` and all other commands are returning an error, asking the user to finish the work.

I guess for the user it is easy to understand start/stop the cluster. But what about delete? I can't see a `crc create` action. 
In the tray, there is no help message for delete command. It's not obvious of what it does. 

The proposal here is to always have a VM ready to start. At the end of `crc setup`, we perform everything needed to just have to (literally) start the VM in `crc start`. 

Also, `crc delete` should be removed and replaced by a command like `crc reset` which delete and recreate a fresh VM.

WDYT?

**Comment by cfergeau** [comment]
There seems to be 2 discussions at once:
1. « The major issue with the current behaviour, is the weird status before the first start of the VM.  »
2. « I guess for the user it is easy to understand start/stop the cluster. But what about delete? I can't see a crc create action. »

For 2., it might be too late for UI changes, but no strong opinion on it. But I think your main issue at the moment is 1., which might be fixable without doing 2.? Ideally, commands would give the same output after `crc delete` and after `crc stop`, ie no difference between "VM  does not exist" and "VM is stopped".

**Comment by guillaumerose** [comment]
> no difference between "VM does not exist" and "VM is stopped".

This is what I thought but:
* if the VM is stopped, you can start it without asking for the pull secret. This is what the tray thinks and then, it never asks for the pull secret
* if I delete a VM that doesn't exist with the tray, it prompts an error because it doesn't exist, etc.

Lot of small things, it's not immediate. 

I can hack a bit for the tray but consistency with CLI is I think necessary. What should crc status return? 
Introduce new statuses? Not so easy. 

Other example: https://github.com/code-ready/crc/blob/master/pkg/libmachine/libmachine.go#L107 here we say a machine exists only if start succeed. It can take 2-3minutes (because we are waiting for the VM to start).

(sorry.. this reply looks like a braindump of all my issues)

**Comment by gbraad** [comment]
funny that this one comes up again. When this was proposed a year ago this was deemed as "wasting resources". but when configurable and even fully pre-heated can help people in a CI setup.

**Comment by cfergeau** [comment]
> if the VM is stopped, you can start it without asking for the pull secret. This is what the tray thinks and then, it never asks for the pull secret

This is a bug in the tray, as if you interrupt start before the pull secret is copied to the VM, then it will ask again for the pull secret. This is not something which is really supported at the moment, but might become more important with your work to allow to interrupt crc start early.

> if I delete a VM that doesn't exist with the tray, it prompts an error because it doesn't exist, etc.

This can be seen as the same issue as before, we could move towards a model where there is no difference (or as little as possible) between "VM does not exist" and "VM is stopped".

**Comment by guillaumerose** [comment]
The code to enable pre-heated/always-ready-to-start VM is small. I tried it and the feeling is pretty good on Linux (create is really fast since it doesn't copy the disk image from the cache to the VM directory). `crc status` reports `Stopped`, no more errors `VM doesnt exist`, etc.

The only issue I have is with the pull secret: Currently, we ask it at creation time and directly save it in the running VM. I can't do that anymore. `crc start` doesn't know anymore if the VM already run once before or not.

I can still ask for the pull secret during `crc start` when the file is not present on the disk. It would imply that the VM needs to be running before knowing wether or not the pull secret is needed.
I can ask it at crc setup time and save it once for all somewhere.
