### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by harish-shenoy** [code-ready/crc#2087]
### General information

  * OS:  Windows
  * Hypervisor:  Hyper-V 
  * Did you run `crc setup` before starting it Yes?
  * Running CRC on: Laptop 
  * 
## CRC version
```bash
# Put `crc version` output here
CodeReady Containers version: 1.23.1+be17b141
OpenShift version: 4.7.0 (embedded in executable)
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
DEBU CodeReady Containers version: 1.23.1+be17b141
DEBU OpenShift version: 4.7.0 (embedded in executable)
DEBU Running 'crc status'
DEBU Checking file: C:\Users\HARISHSHENOY\.crc\machines\crc\.crc-exist
Machine does not exist. Use 'crc start' to create it

## CRC config
```bash
# Put `crc config view` output here
- consent-telemetry                     : no

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```
Host Name:                 DESKTOP-IKONK4S
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19042 N/A Build 19042
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          IBMUSER
Registered Organization:   IBM
Product ID:                00330-80000-00000-AA687
Original Install Date:     01-09-2020, 11:20:46
System Boot Time:          11-03-2021, 12:39:09
System Manufacturer:       LENOVO
System Model:              20L6S29D1V
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 142 Stepping 10 GenuineIntel ~1910 Mhz
BIOS Version:              LENOVO N24ET56W (1.31 ), 19-02-2020
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              00004009
Time Zone:                 (UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi
Total Physical Memory:     32,607 MB
Available Physical Memory: 24,272 MB
Virtual Memory: Max Size:  37,471 MB
Virtual Memory: Available: 28,100 MB
Virtual Memory: In Use:    9,371 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-IKONK4S
Hotfix(s):                 11 Hotfix(s) Installed.
                           [01]: KB4601050
                           [02]: KB4561600
                           [03]: KB4562830
                           [04]: KB4570334
                           [05]: KB4577266
                           [06]: KB4577586
                           [07]: KB4580325
                           [08]: KB4586864
                           [09]: KB4593175
                           [10]: KB4598481
                           [11]: KB4601319
Network Card(s):           4 NIC(s) Installed.
                           [01]: Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows x64
                                 Connection Name: Ethernet 2
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 9.85.83.54
                                 [02]: fe80::9c3c:dbfb:c905:3627
                           [02]: Intel(R) Dual Band Wireless-AC 8265
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.102
                                 [02]: fe80::2ce0:62a0:10aa:4e7e
                                 [03]: 2409:4071:2197:18da:c81b:9576:783d:8211
                                 [04]: 2409:4071:2197:18da:2ce0:62a0:10aa:4e7e
                           [03]: Intel(R) Ethernet Connection (4) I219-LM
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [04]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (Default Switch)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 172.23.48.1
                                 [02]: fe80::3c1b:2f12:5352:24af
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
### Steps to reproduce

  1.  crc delete -f
  2.  crc cleanup
  3.  crc setup
  4. crc start

### Actual
Error

### Logs

Before gather the logs try following if that
[crc.log](https://github.com/code-ready/crc/files/6122287/crc.log)
 fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by harish-shenoy** [comment]
CRC setup error 
INFO Checking if C:\Users\HARISHSHENOY\.crc\cache\crc_hyperv_4.7.0.crcbundle exists
INFO Extracting bundle from the CRC executable
INFO Ensuring directory C:\Users\HARISHSHENOY\.crc\cache exists
INFO Uncompressing crc_hyperv_4.7.0.crcbundle
crc.vhdx: 11.41 GiB / 11.41 GiB [-----------------------------------------------------------------------------] 100.00%
rename C:\Users\HARISHSHENOY\.crc\cache\tmp-extract\crc_hyperv_4.7.0 C:\Users\HARISHSHENOY\.crc\cache\crc_hyperv_4.7.0: Access is denied.

CRC start error
DEBU Failed to load bundle crc_hyperv_4.7.0.crcbundle: could not find cached bundle info in C:\Users\HARISHSHENOY\.crc\cache\crc_hyperv_4.7.0: CreateFile C:\Users\HARISHSHENOY\.crc\cache\crc_hyperv_4.7.0: The system cannot find the file specified.
INFO Extracting bundle: crc_hyperv_4.7.0.crcbundle ...
DEBU Uncompressing C:\Users\HARISHSHENOY\.crc\cache\crc_hyperv_4.7.0.crcbundle to C:\Users\HARISHSHENOY\.crc\cache\tmp-extract
crc.vhdx: 11.41 GiB / 11.41 GiB [-----------------------------------------------------------------------------] 100.00%
Error getting bundle metadata: rename C:\Users\HARISHSHENOY\.crc\cache\tmp-extract\crc_hyperv_4.7.0 C:\Users\HARISHSHENOY\.crc\cache\crc_hyperv_4.7.0: Access is denied.
[Uploading crc.log…]()

**Comment by gbraad** [comment]
@guillaumerose Second time I see this: `rename C:\Users\HARISHSHENOY.crc\cache\tmp-extract\crc_hyperv_4.7.0 C:\Users\HARISHSHENOY.crc\cache\crc_hyperv_4.7.0: Access is denied` on Windows being reported.

**Comment by mircomarahrens** [comment]
Can confirm. I managed to manually unpack the bundle following [Issue 2004](https://github.com/code-ready/crc/issues/2004).

**Comment by harish-shenoy** [comment]
@mircomarahrens Thanks.. extracted using zstd and it works now

**Comment by guillaumerose** [comment]
What's the name of your antivirus?
