### ISSUE TITLE
Watchdog for crc daemon

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#2108]
### General information

  * OS: macOS

### Description

If we want to run the daemon as a child of the daemon, we need a way to ensure the daemon die when the tray is closed.
A good solution is to watch stdin in the daemon and if it is closed, terminate the process.

Related to https://github.com/code-ready/tray-macos/issues/89

**Comment by cfergeau** [comment]
The daemon could also automatically shutdown after 1 minute without receiving any requests

**Comment by anjannath** [comment]
>If we want to run the daemon as a child of the daemon, we need a way to ensure the daemon die when the tray is closed.
A good solution is to watch stdin in the daemon and if it is closed, terminate the process.

Is this a typo? did you mean `run the daemon as a child of the _tray_`, or you mean to separate the daemon serving the API from the daemon that manages the vsock? As now if the tray is closed and we kill the daemon and if vsock was in use we'll stop the user from able to use crc.

**Comment by guillaumerose** [comment]
Implemented in https://github.com/code-ready/crc/commit/a7a1fa1cce4706d8141de3e22327ccfb1fa1f641#diff-6a402f241a359c13dc3183a088f87a7f0a331df8350209c3d674f40f7119cef1

**Comment by gbraad** [comment]
> The daemon could also automatically shutdown after 1 minute without receiving any requests

@cfergeau This sounds like an optimization that can be added as a feature. Please file it as such, as 1m sounds an arbitrary time, but some kind of 'timeout' / stopping the daemon might be helpful, but who checks this and who starts this again? Especially when the CLI would start using the daemon on Windows and macOS, what decides to start it and is the start penalty justified?
