### ISSUE TITLE
Setup disconnected cluster using CRC

### ISSUE THREAD

**Issue by amitkrout** [code-ready/crc#2113]
As a use I want to spin up a airgapped/disconnect cluster on my laptop. AFAIK most of the QE/developer under devtools rely on ```flexy``` job to spin airgapped cluster.  Sometime we face resource quota issue in flexy to get a disconnected cluster and during product release time getting a flexy resource is a hard challenge. 

NOTE : OpenSHift QE uses fexy job to spinup cluster of various types, for example spinning up regular and disconnected cluster on AWS, PSI, GCP etc.

It would be great if you looking the possibility of spinning up a disconnected cluster using CRC

**Comment by gbraad** [comment]
This has been on our long-list and has been requested before. the documentation specifies that this is currently not possible. some images for the S2I or operators will need to be pulled... there is also no ETA.

What could be possible is that you prepare an cluster and share that image or use this as the bundle image instead.

**Comment by praveenkumar** [comment]
My understanding is airgapped/disconnected environment is using a mirror registry and we put steps https://github.com/code-ready/crc/wiki/Add-mirror-registry here how to do that for crc, Have you folks tried it and it is not working?

**Comment by praveenkumar** [comment]
I spend more time today to have an CRC environment same what QE get from internal flexy job but there is some limitation.
- Mirror should have content for same release version which CRC have. (A manual step which user need to do)
     - https://docs.openshift.com/container-platform/latest/openshift_images/samples-operator-alt-registry.html#installation-creating-mirror-registry_samples-operator-alt-registry
- Mirror also have all the sample operator content
- Mirror also have required images for testing in proper namespace.

```
$ cat <<EOF | oc apply -f -
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: image-policy-aosqe
spec:
  repositoryDigestMirrors:
  - mirrors:
    - <mirror-registry>:port/openshifttest
    source: quay.io/openshifttest
  - mirrors:
    -  <mirror-registry>:port
    source: registry.redhat.io
  - mirrors:
    -  <mirror-registry>:port
    source: registry.stage.redhat.io
  - mirrors:
    - <mirror-registry>:port/openshift-qe-optional-operators
    source: quay.io/openshift-qe-optional-operators
EOF


$ cat <<EOF | oc apply -f -
apiVersion: v1
data:
  upshift.mirror-registry.qe.devcluster.openshift.com..5001: |
    -----BEGIN CERTIFICATE-----
   <CERT>
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
   <CERT>
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: registry-config
  namespace: openshift-config
EOF
  
$ oc get image.config.openshift.io/cluster -oyaml 
spec:
  additionalTrustedCA:
    name: registry-config


# cat /etc/containers/registries.conf 

[[registry]]
  prefix = ""
  location = "quay.io/openshift-qe-optional-operators"
  mirror-by-digest-only = true

  [[registry.mirror]]
    location = " <mirror-registry>:port/openshift-qe-optional-operators"

[[registry]]
  prefix = ""
  location = "quay.io/openshifttest"
  mirror-by-digest-only = true

  [[registry.mirror]]
    location = " <mirror-registry>:port/openshifttest"

[[registry]]
  prefix = ""
  location = "registry.redhat.io"
  mirror-by-digest-only = true

  [[registry.mirror]]
    location = " <mirror-registry>:port"

[[registry]]
  prefix = ""
  location = "registry.stage.redhat.io"
  mirror-by-digest-only = true

  [[registry.mirror]]
    location = "<mirror-registry>:port"
```
