### ISSUE TITLE
[ISSUE] Error waiting for apiserver: Temporary error: ssh command error

### ISSUE THREAD

**Issue by mircomarahrens** [code-ready/crc#2125]
### General information

  * OS: Windows
  * Hypervisor Host: Hyper-V
  * Hypervisor Guest: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
CodeReady Containers version: 1.23.1+be17b141
OpenShift version: 4.7.0 (embedded in executable)
```
  
## CRC status
```bash
CRC VM:          Running
OpenShift:       Unreachable (v4.7.0)
Disk Usage:      8.981GB of 32.74GB (Inside the CRC VM)
Cache Usage:     13.01GB
Cache Directory: /home/devad/.crc/cache
```

## CRC config
```bash
- consent-telemetry                     : no
- pull-secret-file                      : /home/devad/crc/pull-secret.txt
```

## Host Operating System
```bash
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19042 N/A Build 19042
```

## Guest Operating System
```bash
Red Hat Enterprise Linux Server release 7.7 (Maipo)
```

### Steps to reproduce

  1. Setup VM with RHEL 7.7 with Virtualization Tools
  2. Enable nested virtualization from Windows host for VM with
  ```bash
  Set-VMProcessor -VMName <VMName> -ExposeVirtualizationExtensions $true
  ```
  3. Activate nested virtualization within VM; output after activation:
  ```bash
  > cat /sys/module/kvm_intel/parameters/nested
  Y
  ```
  4. `crc setup`, `crc start`

### Expected
CRC is running, VM is accessible

### Actual
```bash
[...]
DEBU error: Temporary error: ssh command error:
command : timeout 5s oc get nodes --context admin --cluster crc --kubeconfig /opt/kubeconfig
err     : Process exited with status 124\n - sleeping 1s
DEBU retry loop: attempt 117
DEBU Running SSH command: timeout 5s oc get nodes --context admin --cluster crc --kubeconfig /opt/kubeconfig
DEBU SSH command results: err: Process exited with status 124, output:
DEBU
DEBU error: Temporary error: ssh command error:
command : timeout 5s oc get nodes --context admin --cluster crc --kubeconfig /opt/kubeconfig
err     : Process exited with status 124\n - sleeping 1s
DEBU RetryAfter timeout after 118 tries
DEBU Making call to close driver server
DEBU (crc) Calling .Close
DEBU (crc) DBG | time="2021-03-18T22:10:07+01:00" level=debug msg="Closing plugin on server side"
DEBU Successfully made call to close driver server
DEBU Making call to close connection to plugin binary
Error waiting for apiserver: Temporary error: ssh command error:
command : timeout 5s oc get nodes --context admin --cluster crc --kubeconfig /opt/kubeconfig
err     : Process exited with status 1\n (x75)
Temporary error: ssh command error:
command : timeout 5s oc get nodes --context admin --cluster crc --kubeconfig /opt/kubeconfig
err     : Process exited with status 124\n (x3)
Temporary error: ssh command error:
command : timeout 5s oc get nodes --context admin --cluster crc --kubeconfig /opt/kubeconfig
err     : Process exited with status 1\n (x25)
Temporary error: ssh command error:
command : timeout 5s oc get nodes --context admin --cluster crc --kubeconfig /opt/kubeconfig
err     : Process exited with status 124\n (x15)
```

### Logs

https://gist.github.com/mircomarahrens/38a60989b8c9b698dc36f4af8a1d0a26

**Comment by gbraad** [comment]
Nested virtualization setups aren't supported by us.

**Comment by gbraad** [comment]
I have tested this setup with Fedora33/CentOS8 using KVM/Intel, and Windows 10. It should work, but many things can influence the performance so this is mostly a YMMV ("Your mileage may vary").

**Comment by gbraad** [comment]
So this is running Hyper-V with a RHEL VM and that VM runs CRC? This is possible, but quite slow from experience.
I strongly suggest you to run CRC directly on the host with Hyper-V as the hypervisor.

If the issue in that case still persists re-open this one.

**Comment by mircomarahrens** [comment]
> So this is running Hyper-V with a RHEL VM and that VM runs CRC? This is possible, but quite slow from experience.
> I strongly suggest you to run CRC directly on the host with Hyper-V as the hypervisor.
> 
> If the issue in that case still persists re-open this one.

I successfully run CRC on the Windows Host, but I was not able to connect to a proxy from WSL2, as commented [here](https://github.com/code-ready/crc/issues/374#issuecomment-800077305). I would like to have an local test environment to run Ansible Playbooks for the configuration of an OpenShift cluster. Is this possible with Windows?

**Comment by gbraad** [comment]
WSL2 and CM communcation is an issue related to how Microoft configures their network:
Run the following commands in PowerShell to enable this https://github.com/gbraad/windows-dotfiles/blob/main/setup-wsl.ps1

```powershell
# Allow traffic from Hyper-V VMs to WSL and vice versa
PS > Set-NetIPInterface -ifAlias "vEthernet (WSL)" -Forwarding Enabled
PS> Set-NetIPInterface -ifAlias "vEthernet (Default Switch)" -Forwarding Enabled
```

Note that this need to be run after each reboot

**Comment by mircomarahrens** [comment]
Unfortunately none of the proposed solutions worked. I tried
1. Enable port forwarding via
```bash
# Allow traffic from Hyper-V VMs to WSL and vice versa
PS> Set-NetIPInterface -ifAlias "vEthernet (WSL)" -Forwarding Enabled
PS> Set-NetIPInterface -ifAlias "vEthernet (Default Switch)" -Forwarding Enabled
```
2. Setup VM with Default Switch as virtual switch and try to connect to a running proxy on the Windows machine:
On Windows:
```bash
> oc login -u kubeadmin -p <token> https://api.crc.testing:6443
> oc proxy --port=8001 --api-prefix='/' --address=$IP_SWITCH --accept-hosts=".*"
Starting to serve on 172.23.144.1:8001
```
Where `$IP_SWITCH` is either the ip of the WSL switch or the Default Switch.
On VM or WSL:
```bash
> BRIDGE_IP=$(grep nameserver /etc/resolv.conf | sed 's/nameserver //')
> oc config set clusters.crc.server $BRIDGE_IP:8001
Property "clusters.crc.server" set.
> oc config set contexts.crc.cluster crc
Property "contexts.crc.cluster" set.
> oc config use-context crc
Switched to context "crc".
```
On WSL:
```bash
> oc login -u kubeadmin -p <token> https://api.crc.testing:6443
error: dial tcp 127.0.0.1:6443: connect: connection refused - verify you have provided the correct host and port and that the server is currently running.
> oc version
Client Version: 4.6.4
The connection to the server 127.0.0.1:8001 was refused - did you specify the right host or port?
```

On VM:
```bash
> oc login -u kubeadmin -p <token> https://api.crc.testing:6443
error: dial tcp 192.168.130.11:6443: connect: no route to host - verify you have provided the correct host and port and that the server is currently running.
> oc version
Client Version: 4.6.4
The connection to the server 127.0.0.1:8001 was refused - did you specify the right host or port?
```

**Comment by gbraad** [comment]
> api.crc.testing

Seems to resolve to 127.0.0.1 on WSL. It does not automatically enable the DNS on the WSL environment. Please make sure it resolves to the correct IP by overriding the DNS or set a fixed address in hosts. Also, it feels like a large part of the description is missing.

However in short, the CRC VM starts and is operational? Can you access it from the Windows host directly?

**Comment by tommiyau** [comment]
I used VMWare workstation and CRC as a install on a RHEL8 guest is simply non-functional. You can watch the coreos VM start and it will hang and have other various issues and occassionally boot correctly. When that happens everything runs fine. Simply swapping back to a RHEL7 guest machine fixes all my issues with running crc in a VM. RHEL7 does not exhibit any of the issues that RHEL8 exhibits with running the CRC VM. Its stable compared to RHEL8 as a guest. Pretty sad but thats the work around that I have.
