### ISSUE TITLE
[Feature] add support for podman drivers

### ISSUE THREAD

**Issue by thotz** [code-ready/crc#2126]
### General information
Minikube support different drivers options such docker and podman in which k8s can be created inside a VM. Requesting similar feature for CRC

**Comment by guillaumerose** [comment]
Yes it would be awesome to have this.
Sadly, there is no way to run OpenShift in a container right now. We are experimenting around that but it will take a long time before it gets accepted.

**Comment by gbraad** [comment]
Closing for now as this is not possible. OpenShift 4.x is 'bound' to RHCOS and Cri-o as the container runtime.
