### ISSUE TITLE
Error when starting CRC on older mac

### ISSUE THREAD

**Issue by jsliacan** [code-ready/crc#214]
On a Mac OSX 10.11.6, the following error comes up during start.

```
$ crc setup
crc - Local OpenShift 4.x cluster
INFO Caching oc binary                            
INFO Setting up virtualization                    
INFO Setting file permissions for resolver        
$ crc start -b ~/Downloads/crc_vbox_4.1.0.tar.xz -d virtualbox
crc - Local OpenShift 4.x cluster
INFO Checking if oc binary is cached              
INFO Checking if VirtualBox is Installed          
INFO Checking file permissions for resolver       
INFO Extracting the Bundle tarball ...            
INFO Creating VM ...                              
INFO Bridge IP on the host: 192.168.130.1         
INFO Restarting the network                       
ERRO Error running post start: : exit status 7    
INFO Running                                      
[: exit status 7]
```

**Comment by gbraad** [comment]
we might need to have a macOS version check, just like we do with Windows 10 version (+update).
This looks like an issue with restarting the network.

**Comment by praveenkumar** [comment]
@gbraad I think we should have it part of document that older version of mac is not yet supported.

**Comment by gbraad** [comment]
Minimum being 10.12 ?

**Comment by cfergeau** [comment]
Apple seems to be issuing [security updates](https://support.apple.com/en-us/HT201222) for macos 10.12 or newer, so 10.12 sounds like a good target. I'm not sure we have an easy way to test it though.

**Comment by ffirg** [comment]
I have a similar issue on MacOS 10.14.6 (Mojave)
Errors on host network restart.

Debug output suggest it's picking up my VPN config as a net device and trying to do something with that. Shutting down the background VPN process (Viscosity) doesn't work (same error).

$ crc start --log-level debug
DEBU No new version available, latest version at mirror is 1.0.0-rc.0
INFO Checking if running as non-root
INFO Checking if oc binary is cached
DEBU oc binary already cached
INFO Checking if HyperKit is installed
DEBU Checking if hyperkit is installed
INFO Checking if crc-driver-hyperkit is installed
DEBU Checking if crc-driver-hyperkit is installed
DEBU crc-driver-hyperkit is already installed in /Users/pgriffit/.crc/bin/crc-driver-hyperkit
INFO Checking file permissions for /etc/resolver/testing
INFO Checking file permissions for /etc/hosts
Checking file: /Users/pgriffit/.crc/machines/crc/.crc-exist
? Image pull secret [? for help] *********************************************************************************************************************************************************************************************************************************************************************************INFO Loading bundle: crc_hyperkit_4.2.0-0.nightly-2019-09-26-192831.crcbundle ... ********************INFO Creating CodeReady Containers VM for OpenShift 4.2.0-0.nightly-2019-09-26-192831... *************Found binary path at /Users/pgriffit/.crc/bin/crc-driver-hyperkit*************************************Launching plugin server for driver hyperkit***********************************************************Plugin server listening at address 127.0.0.1:63620****************************************************() Calling .GetVersion********************************************************************************Using API Version  1**********************************************************************************() Calling .SetConfigRaw******************************************************************************() Calling .GetMachineName****************************************************************************(crc) Calling .GetMachineName*************************************************************************(crc) Calling .DriverName*****************************************************************************Running pre-create checks...**************************************************************************(crc) Calling .PreCreateCheck*************************************************************************(crc) DBG | exe=/Users/pgriffit/.crc/bin/crc-driver-hyperkit uid=0************************************(crc) Calling .GetConfigRaw***************************************************************************Creating machine...***********************************************************************************(crc) Calling .Create*********************************************************************************(crc) DBG | exe=/Users/pgriffit/.crc/bin/crc-driver-hyperkit uid=0************************************(crc) Downloading /Users/pgriffit/.crc/cache/crc.disk from file:///Users/pgriffit/.crc/cache/crc_hyperkit_4.2.0-0.nightly-2019-09-26-192831/crc.qcow2...****************************************************(crc) DBG | exe=/Users/pgriffit/.crc/bin/crc-driver-hyperkit uid=0************************************(crc) DBG | clean start, hyperkit pid file doesn't exist: /Users/pgriffit/.crc/machines/crc/hyperkit.pid****************************************************************************************************(crc) DBG | Using hyperkit binary from /Users/pgriffit/.crc/bin/hyperkit******************************(crc) DBG | Using UUID 9d31a044-f0f2-11e9-a65c-24a074f106f8
(crc) DBG | Generated MAC 7e:f0:4a:9f:bf:a2
(crc) DBG | Starting with cmdline: BOOT_IMAGE=/ostree/rhcos-684c0aec21d7e368327d272805db52e349427abc89e9561cdeaa01ca36d4ddda/vmlinuz-4.18.0-80.11.2.el8_0.x86_64 console=tty0 console=ttyS0,115200n8 rootflags=defaults,prjquota rw root=UUID=fd0a4584-ed9b-4ecc-b8c1-6bac17322edc ostree=/ostree/boot.0/rhcos/684c0aec21d7e368327d272805db52e349427abc89e9561cdeaa01ca36d4ddda/0 coreos.oem.id=qemu ignition.platform.id=qemu
(crc) DBG | Trying to execute /Users/pgriffit/.crc/bin/hyperkit -A -u -F /Users/pgriffit/.crc/machines/crc/hyperkit.pid -c 4 -m 8192M -s 0:0,hostbridge -s 31,lpc -s 1:0,virtio-net -U 9d31a044-f0f2-11e9-a65c-24a074f106f8 -s 2:0,virtio-blk,file:///Users/pgriffit/.crc/machines/crc/crc.disk,format=qcow -s 3,virtio-rnd -l com1,autopty=/Users/pgriffit/.crc/machines/crc/tty,log=/Users/pgriffit/.crc/machines/crc/console-ring -f kexec,/Users/pgriffit/.crc/cache/crc_hyperkit_4.2.0-0.nightly-2019-09-26-192831/vmlinuz-4.18.0-80.11.2.el8_0.x86_64,/Users/pgriffit/.crc/cache/crc_hyperkit_4.2.0-0.nightly-2019-09-26-192831/initramfs-4.18.0-80.11.2.el8_0.x86_64.img,earlyprintk=serial BOOT_IMAGE=/ostree/rhcos-684c0aec21d7e368327d272805db52e349427abc89e9561cdeaa01ca36d4ddda/vmlinuz-4.18.0-80.11.2.el8_0.x86_64 console=tty0 console=ttyS0,115200n8 rootflags=defaults,prjquota rw root=UUID=fd0a4584-ed9b-4ecc-b8c1-6bac17322edc ostree=/ostree/boot.0/rhcos/684c0aec21d7e368327d272805db52e349427abc89e9561cdeaa01ca36d4ddda/0 coreos.oem.id=qemu ignition.platform.id=qemu
(crc) DBG | exe=/Users/pgriffit/.crc/bin/crc-driver-hyperkit uid=0
(crc) DBG | hyperkit pid from json: 15086
(crc) DBG | Searching for 7e:f0:4a:9f:bf:a2 in /var/db/dhcpd_leases ...
(crc) DBG | Found 9 entries in /var/db/dhcpd_leases!
(crc) DBG | dhcp entry: {Name:crc-chc9n-master-0 IPAddress:192.168.64.10 HWAddress:9a:ec:e3:92:8c:5c ID:1,9a:ec:e3:92:8c:5c Lease:0x5da9d781}
(crc) DBG | dhcp entry: {Name:crc-chc9n-master-0 IPAddress:192.168.64.9 HWAddress:d2:d4:7c:66:61:94 ID:1,d2:d4:7c:66:61:94 Lease:0x5da9d5d1}
(crc) DBG | dhcp entry: {Name:crc-chc9n-master-0 IPAddress:192.168.64.8 HWAddress:9a:4d:fa:55:f3:7b ID:1,9a:4d:fa:55:f3:7b Lease:0x5da9d083}
(crc) DBG | dhcp entry: {Name: IPAddress:192.168.64.7 HWAddress:56:9c:4b:3c:69:4b ID:1,56:9c:4b:3c:69:4b Lease:0x5b7f1afa}
(crc) DBG | dhcp entry: {Name: IPAddress:192.168.64.6 HWAddress:d2:dc:17:9:93:88 ID:1,d2:dc:17:9:93:88 Lease:0x5b6c2df2}
(crc) DBG | dhcp entry: {Name: IPAddress:192.168.64.5 HWAddress:2:37:3a:ba:8a:4 ID:1,2:37:3a:ba:8a:4 Lease:0x5b6c2b02}
(crc) DBG | dhcp entry: {Name:faas-tutorial IPAddress:192.168.64.4 HWAddress:4a:fd:df:ac:ef:dc ID:1,4a:fd:df:ac:ef:dc Lease:0x5b117b8c}
(crc) DBG | dhcp entry: {Name:boot2docker IPAddress:192.168.64.3 HWAddress:5e:34:ef:6c:4b:a2 ID:1,5e:34:ef:6c:4b:a2 Lease:0x5aaad96e}
(crc) DBG | dhcp entry: {Name:minishift IPAddress:192.168.64.2 HWAddress:2:51:8:22:87:a6 ID:1,2:51:8:22:87:a6 Lease:0x5982f40b}
(crc) DBG | error: Temporary Error: could not find an IP address for 7e:f0:4a:9f:bf:a2 - sleeping 2s
(crc) DBG | retry loop 1
(crc) DBG | exe=/Users/pgriffit/.crc/bin/crc-driver-hyperkit uid=0
(crc) DBG | hyperkit pid from json: 15086
(crc) DBG | Searching for 7e:f0:4a:9f:bf:a2 in /var/db/dhcpd_leases ...
(crc) DBG | Found 9 entries in /var/db/dhcpd_leases!
(crc) DBG | dhcp entry: {Name:crc-chc9n-master-0 IPAddress:192.168.64.10 HWAddress:9a:ec:e3:92:8c:5c ID:1,9a:ec:e3:92:8c:5c Lease:0x5da9d781}
(crc) DBG | dhcp entry: {Name:crc-chc9n-master-0 IPAddress:192.168.64.9 HWAddress:d2:d4:7c:66:61:94 ID:1,d2:d4:7c:66:61:94 Lease:0x5da9d5d1}
(crc) DBG | dhcp entry: {Name:crc-chc9n-master-0 IPAddress:192.168.64.8 HWAddress:9a:4d:fa:55:f3:7b ID:1,9a:4d:fa:55:f3:7b Lease:0x5da9d083}
(crc) DBG | dhcp entry: {Name: IPAddress:192.168.64.7 HWAddress:56:9c:4b:3c:69:4b ID:1,56:9c:4b:3c:69:4b Lease:0x5b7f1afa}
(crc) DBG | dhcp entry: {Name: IPAddress:192.168.64.6 HWAddress:d2:dc:17:9:93:88 ID:1,d2:dc:17:9:93:88 Lease:0x5b6c2df2}
(crc) DBG | dhcp entry: {Name: IPAddress:192.168.64.5 HWAddress:2:37:3a:ba:8a:4 ID:1,2:37:3a:ba:8a:4 Lease:0x5b6c2b02}
(crc) DBG | dhcp entry: {Name:faas-tutorial IPAddress:192.168.64.4 HWAddress:4a:fd:df:ac:ef:dc ID:1,4a:fd:df:ac:ef:dc Lease:0x5b117b8c}
(crc) DBG | dhcp entry: {Name:boot2docker IPAddress:192.168.64.3 HWAddress:5e:34:ef:6c:4b:a2 ID:1,5e:34:ef:6c:4b:a2 Lease:0x5aaad96e}
(crc) DBG | dhcp entry: {Name:minishift IPAddress:192.168.64.2 HWAddress:2:51:8:22:87:a6 ID:1,2:51:8:22:87:a6 Lease:0x5982f40b}
(crc) DBG | error: Temporary Error: could not find an IP address for 7e:f0:4a:9f:bf:a2 - sleeping 2s
(crc) DBG | retry loop 2
(crc) DBG | exe=/Users/pgriffit/.crc/bin/crc-driver-hyperkit uid=0
(crc) DBG | hyperkit pid from json: 15086
(crc) DBG | Searching for 7e:f0:4a:9f:bf:a2 in /var/db/dhcpd_leases ...
(crc) DBG | Found 9 entries in /var/db/dhcpd_leases!
(crc) DBG | dhcp entry: {Name:crc-chc9n-master-0 IPAddress:192.168.64.10 HWAddress:9a:ec:e3:92:8c:5c ID:1,9a:ec:e3:92:8c:5c Lease:0x5da9d781}
(crc) DBG | dhcp entry: {Name:crc-chc9n-master-0 IPAddress:192.168.64.9 HWAddress:d2:d4:7c:66:61:94 ID:1,d2:d4:7c:66:61:94 Lease:0x5da9d5d1}
(crc) DBG | dhcp entry: {Name:crc-chc9n-master-0 IPAddress:192.168.64.8 HWAddress:9a:4d:fa:55:f3:7b ID:1,9a:4d:fa:55:f3:7b Lease:0x5da9d083}
(crc) DBG | dhcp entry: {Name: IPAddress:192.168.64.7 HWAddress:56:9c:4b:3c:69:4b ID:1,56:9c:4b:3c:69:4b Lease:0x5b7f1afa}
(crc) DBG | dhcp entry: {Name: IPAddress:192.168.64.6 HWAddress:d2:dc:17:9:93:88 ID:1,d2:dc:17:9:93:88 Lease:0x5b6c2df2}
(crc) DBG | dhcp entry: {Name: IPAddress:192.168.64.5 HWAddress:2:37:3a:ba:8a:4 ID:1,2:37:3a:ba:8a:4 Lease:0x5b6c2b02}
(crc) DBG | dhcp entry: {Name:faas-tutorial IPAddress:192.168.64.4 HWAddress:4a:fd:df:ac:ef:dc ID:1,4a:fd:df:ac:ef:dc Lease:0x5b117b8c}
(crc) DBG | dhcp entry: {Name:boot2docker IPAddress:192.168.64.3 HWAddress:5e:34:ef:6c:4b:a2 ID:1,5e:34:ef:6c:4b:a2 Lease:0x5aaad96e}
(crc) DBG | dhcp entry: {Name:minishift IPAddress:192.168.64.2 HWAddress:2:51:8:22:87:a6 ID:1,2:51:8:22:87:a6 Lease:0x5982f40b}
(crc) DBG | error: Temporary Error: could not find an IP address for 7e:f0:4a:9f:bf:a2 - sleeping 2s
(crc) DBG | retry loop 3
(crc) DBG | exe=/Users/pgriffit/.crc/bin/crc-driver-hyperkit uid=0
(crc) DBG | hyperkit pid from json: 15086
(crc) DBG | Searching for 7e:f0:4a:9f:bf:a2 in /var/db/dhcpd_leases ...
(crc) DBG | Found 9 entries in /var/db/dhcpd_leases!
(crc) DBG | dhcp entry: {Name:crc-chc9n-master-0 IPAddress:192.168.64.10 HWAddress:9a:ec:e3:92:8c:5c ID:1,9a:ec:e3:92:8c:5c Lease:0x5da9d781}
(crc) DBG | dhcp entry: {Name:crc-chc9n-master-0 IPAddress:192.168.64.9 HWAddress:d2:d4:7c:66:61:94 ID:1,d2:d4:7c:66:61:94 Lease:0x5da9d5d1}
(crc) DBG | dhcp entry: {Name:crc-chc9n-master-0 IPAddress:192.168.64.8 HWAddress:9a:4d:fa:55:f3:7b ID:1,9a:4d:fa:55:f3:7b Lease:0x5da9d083}
(crc) DBG | dhcp entry: {Name: IPAddress:192.168.64.7 HWAddress:56:9c:4b:3c:69:4b ID:1,56:9c:4b:3c:69:4b Lease:0x5b7f1afa}
(crc) DBG | dhcp entry: {Name: IPAddress:192.168.64.6 HWAddress:d2:dc:17:9:93:88 ID:1,d2:dc:17:9:93:88 Lease:0x5b6c2df2}
(crc) DBG | dhcp entry: {Name: IPAddress:192.168.64.5 HWAddress:2:37:3a:ba:8a:4 ID:1,2:37:3a:ba:8a:4 Lease:0x5b6c2b02}
(crc) DBG | dhcp entry: {Name:faas-tutorial IPAddress:192.168.64.4 HWAddress:4a:fd:df:ac:ef:dc ID:1,4a:fd:df:ac:ef:dc Lease:0x5b117b8c}
(crc) DBG | dhcp entry: {Name:boot2docker IPAddress:192.168.64.3 HWAddress:5e:34:ef:6c:4b:a2 ID:1,5e:34:ef:6c:4b:a2 Lease:0x5aaad96e}
(crc) DBG | dhcp entry: {Name:minishift IPAddress:192.168.64.2 HWAddress:2:51:8:22:87:a6 ID:1,2:51:8:22:87:a6 Lease:0x5982f40b}
(crc) DBG | error: Temporary Error: could not find an IP address for 7e:f0:4a:9f:bf:a2 - sleeping 2s
(crc) DBG | retry loop 4
(crc) DBG | exe=/Users/pgriffit/.crc/bin/crc-driver-hyperkit uid=0
(crc) DBG | hyperkit pid from json: 15086
(crc) DBG | Searching for 7e:f0:4a:9f:bf:a2 in /var/db/dhcpd_leases ...
(crc) DBG | Found 9 entries in /var/db/dhcpd_leases!
(crc) DBG | dhcp entry: {Name:crc-chc9n-master-0 IPAddress:192.168.64.10 HWAddress:9a:ec:e3:92:8c:5c ID:1,9a:ec:e3:92:8c:5c Lease:0x5da9d781}
(crc) DBG | dhcp entry: {Name:crc-chc9n-master-0 IPAddress:192.168.64.9 HWAddress:d2:d4:7c:66:61:94 ID:1,d2:d4:7c:66:61:94 Lease:0x5da9d5d1}
(crc) DBG | dhcp entry: {Name:crc-chc9n-master-0 IPAddress:192.168.64.8 HWAddress:9a:4d:fa:55:f3:7b ID:1,9a:4d:fa:55:f3:7b Lease:0x5da9d083}
(crc) DBG | dhcp entry: {Name: IPAddress:192.168.64.7 HWAddress:56:9c:4b:3c:69:4b ID:1,56:9c:4b:3c:69:4b Lease:0x5b7f1afa}
(crc) DBG | dhcp entry: {Name: IPAddress:192.168.64.6 HWAddress:d2:dc:17:9:93:88 ID:1,d2:dc:17:9:93:88 Lease:0x5b6c2df2}
(crc) DBG | dhcp entry: {Name: IPAddress:192.168.64.5 HWAddress:2:37:3a:ba:8a:4 ID:1,2:37:3a:ba:8a:4 Lease:0x5b6c2b02}
(crc) DBG | dhcp entry: {Name:faas-tutorial IPAddress:192.168.64.4 HWAddress:4a:fd:df:ac:ef:dc ID:1,4a:fd:df:ac:ef:dc Lease:0x5b117b8c}
(crc) DBG | dhcp entry: {Name:boot2docker IPAddress:192.168.64.3 HWAddress:5e:34:ef:6c:4b:a2 ID:1,5e:34:ef:6c:4b:a2 Lease:0x5aaad96e}
(crc) DBG | dhcp entry: {Name:minishift IPAddress:192.168.64.2 HWAddress:2:51:8:22:87:a6 ID:1,2:51:8:22:87:a6 Lease:0x5982f40b}
(crc) DBG | error: Temporary Error: could not find an IP address for 7e:f0:4a:9f:bf:a2 - sleeping 2s
(crc) DBG | retry loop 5
(crc) DBG | exe=/Users/pgriffit/.crc/bin/crc-driver-hyperkit uid=0
(crc) DBG | hyperkit pid from json: 15086
(crc) DBG | Searching for 7e:f0:4a:9f:bf:a2 in /var/db/dhcpd_leases ...
(crc) DBG | Found 10 entries in /var/db/dhcpd_leases!
(crc) DBG | dhcp entry: {Name:crc-chc9n-master-0 IPAddress:192.168.64.11 HWAddress:7e:f0:4a:9f:bf:a2 ID:1,7e:f0:4a:9f:bf:a2 Lease:0x5da9da09}
(crc) DBG | Found match: 7e:f0:4a:9f:bf:a2
(crc) DBG | IP: 192.168.64.11
(crc) Calling .GetConfigRaw
(crc) Calling .DriverName
(crc) Calling .DriverName
Waiting for machine to be running, this may take a few minutes...
(crc) Calling .GetState
(crc) DBG | exe=/Users/pgriffit/.crc/bin/crc-driver-hyperkit uid=0
(crc) DBG | hyperkit pid from json: 15086
Machine is up and running!
Machine successfully created
Created /Users/pgriffit/.crc/machines/crc/.crc-exist
(crc) Calling .GetState
(crc) DBG | exe=/Users/pgriffit/.crc/bin/crc-driver-hyperkit uid=0
(crc) DBG | hyperkit pid from json: 15086
Found binary path at /Users/pgriffit/.crc/bin/crc-driver-hyperkit
Launching plugin server for driver hyperkit
Plugin server listening at address 127.0.0.1:63673
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
DEBU Waiting until ssh is available
(crc) Calling .GetSSHHostname
(crc) Calling .GetSSHPort
(crc) Calling .GetSSHKeyPath
(crc) Calling .GetSSHKeyPath
(crc) Calling .GetSSHUsername
Using SSH client type: native
&{{{<nil> 0 [] [] []} core [0x1354350] 0x1354320 <nil>  [] 0s} 192.168.64.11 22 <nil> <nil>}
About to run SSH command:
exit 0
SSH cmd err, output: <nil>:
INFO Verifying validity of the cluster certificates ...
(crc) Calling .GetSSHHostname
(crc) Calling .GetSSHPort
(crc) Calling .GetSSHKeyPath
(crc) Calling .GetSSHKeyPath
(crc) Calling .GetSSHUsername
Using SSH client type: native
&{{{<nil> 0 [] [] []} core [0x1354350] 0x1354320 <nil>  [] 0s} 192.168.64.11 22 <nil> <nil>}
About to run SSH command:
date --date="$(sudo openssl x509 -in /var/lib/kubelet/pki/kubelet-client-current.pem -noout -enddate | cut -d= -f 2)" --iso-8601=seconds
SSH cmd err, output: <nil>: 2019-10-28T10:58:42+00:00

(crc) Calling .GetIP
(crc) Calling .DriverName
(crc) Calling .GetSSHHostname
(crc) Calling .GetSSHPort
(crc) Calling .GetSSHKeyPath
(crc) Calling .GetSSHKeyPath
(crc) Calling .GetSSHUsername
Using SSH client type: native
&{{{<nil> 0 [] [] []} core [0x1354350] 0x1354320 <nil>  [] 0s} 192.168.64.11 22 <nil> <nil>}
About to run SSH command:
echo 'dXNlcj1yb290CnBvcnQ9IDUzCmJpbmQtaW50ZXJmYWNlcwpleHBhbmQtaG9zdHMKbG9nLXF1ZXJpZXMKc3J2LWhvc3Q9X2V0Y2Qtc2VydmVyLXNzbC5fdGNwLmNyYy50ZXN0aW5nLGV0Y2QtMC5jcmMudGVzdGluZywyMzgwLDEwCmxvY2FsPS9jcmMudGVzdGluZy8KZG9tYWluPWNyYy50ZXN0aW5nCmFkZHJlc3M9L2FwcHMtY3JjLnRlc3RpbmcvMTkyLjE2OC42NC4xMQphZGRyZXNzPS9ldGNkLTAuY3JjLnRlc3RpbmcvMTkyLjE2OC42NC4xMQphZGRyZXNzPS9hcGkuY3JjLnRlc3RpbmcvMTkyLjE2OC42NC4xMQphZGRyZXNzPS9hcGktaW50LmNyYy50ZXN0aW5nLzE5Mi4xNjguNjQuMTEKYWRkcmVzcz0vY3JjLWNoYzluLW1hc3Rlci0wLmNyYy50ZXN0aW5nLzE5Mi4xNjguNjQuMTEK' | openssl enc -base64 -d | sudo tee /var/srv/dnsmasq.conf > /dev/null
SSH cmd err, output: <nil>:
(crc) Calling .GetSSHHostname
(crc) Calling .GetSSHPort
(crc) Calling .GetSSHKeyPath
(crc) Calling .GetSSHKeyPath
(crc) Calling .GetSSHUsername
Using SSH client type: native
&{{{<nil> 0 [] [] []} core [0x1354350] 0x1354320 <nil>  [] 0s} 192.168.64.11 22 <nil> <nil>}
About to run SSH command:
sudo podman rm -f dnsmasq
SSH cmd err, output: Process exited with status 1: Error: no container with name or ID dnsmasq found: no such container

(crc) Calling .GetSSHHostname
(crc) Calling .GetSSHPort
(crc) Calling .GetSSHKeyPath
(crc) Calling .GetSSHKeyPath
(crc) Calling .GetSSHUsername
Using SSH client type: native
&{{{<nil> 0 [] [] []} core [0x1354350] 0x1354320 <nil>  [] 0s} 192.168.64.11 22 <nil> <nil>}
About to run SSH command:
sudo rm -f /var/lib/cni/networks/podman/10.88.0.8
SSH cmd err, output: <nil>:
(crc) Calling .GetSSHHostname
(crc) Calling .GetSSHPort
(crc) Calling .GetSSHKeyPath
(crc) Calling .GetSSHKeyPath
(crc) Calling .GetSSHUsername
Using SSH client type: native
&{{{<nil> 0 [] [] []} core [0x1354350] 0x1354320 <nil>  [] 0s} 192.168.64.11 22 <nil> <nil>}
About to run SSH command:
sudo podman run  --ip 10.88.0.8 --name dnsmasq -v /var/srv/dnsmasq.conf:/etc/dnsmasq.conf -p 53:53/udp --privileged -d quay.io/crcont/dnsmasq:latest
SSH cmd err, output: <nil>: 27ebd2ddab7a822728c303c5f93717cf5804d6de991c431b229e121e92f82150

DEBU Updating api.crc.testing to 192.168.64.11 in /etc/hosts file
DEBU Updating oauth-openshift.apps-crc.testing to 192.168.64.11 in /etc/hosts file
INFO Restarting the host network
DEBU Disabling the Thunderbolt Ethernet Device (stdout: ), (stderr: )
DEBU Enabling the Thunderbolt Ethernet Device (stdout: ), (stderr: )
DEBU Disabling the Wi-Fi Device (stdout: ), (stderr: )
DEBU Enabling the Wi-Fi Device (stdout: ), (stderr: )
DEBU Disabling the iPhone USB Device (stdout: ), (stderr: )
DEBU Enabling the iPhone USB Device (stdout: ), (stderr: )
DEBU Disabling the Bluetooth PAN Device (stdout: ), (stderr: )
DEBU Enabling the Bluetooth PAN Device (stdout: ), (stderr: )
DEBU Disabling the Thunderbolt Bridge Device (stdout: ), (stderr: )
DEBU Enabling the Thunderbolt Bridge Device (stdout: ), (stderr: )
DEBU Disabling the *VPN - Raleigh Device (stdout: *VPN - Raleigh is not a recognized network service.
** Error: The parameters were not valid.
), (stderr: )
DEBU Enabling the *VPN - Raleigh Device (stdout: *VPN - Raleigh is not a recognized network service.
** Error: The parameters were not valid.
), (stderr: )
ERRO Error occurred: Error running post start: Restarting the host network failed: : exit status 4
Making call to close driver server
(crc) Calling .Close
(crc) DBG | Closing plugin on server side
Successfully made call to close driver server
Making call to close connection to plugin binary
Making call to close driver server
(crc) Calling .Close
Successfully made call to close driver server
Making call to close connection to plugin binary

**Comment by ffirg** [comment]
I'd say this is a bug as well, as crc is picking up networkservices which are disabled:
$ networksetup -listallnetworkservices
An asterisk (*) denotes that a network service is disabled.
Thunderbolt Ethernet
Wi-Fi
iPhone USB
Bluetooth PAN
Thunderbolt Bridge
*VPN - Raleigh
*VPN - Amsterdam
*VPN - Phoenix

**Comment by ffirg** [comment]
Enabling the disabled networkservices with this:
networksetup -setnetworkserviceenabled 'VPN - Raleigh' on
is a workaround.
