### ISSUE TITLE
[BUG] Cannot recover from "Error loading bundle metadata: oc not found in bundle"

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#2145]
In telemetry, there are lot of people encountering this error. They cannot fix it easily and most of the time, they give up.

**Investigation**

People 1 on Linux:

crc setup -> ok (first time it appears in telemetry)
crc start -> Error loading bundle metadata: oc not found in bundle
crc delete -> Driver cannot remove machine: Failed to fetch machine 'crc'
crc status -> Cannot get machine state: Failed to fetch machine 'crc'
crc setup -> ok
crc start -> Error loading bundle metadata: oc not found in bundle
give up

People 2 on macOS:

crc setup -> ok (first time it appears in telemetry)
crc start -> Error loading bundle metadata: oc not found in bundle (couple of times)
...
crc delete -> ok
crc setup -> ok
crc start -> ok
recovered

People 3 on Linux:
crc setup -> ok (first time it appears in telemetry)
crc start -> Error loading bundle metadata: oc not found in bundle
crc cleanup -> ok
crc setup -> ok
crc start -> ok
recovered

It seems that they all have an old crc machine configured: ~/.crc/machines/crc/config.json is present and probably an old bundle or missing bundle.
For the first example, the VM is not configured anymore in libvirt.

**Comment by cfergeau** [comment]
Yup, might be a side-effect of https://github.com/code-ready/crc/commit/ed243aafde0b532b0a on upgrades, when the initial state is a version where `oc` was not present in the bundle.

**Comment by praveenkumar** [comment]
I think `crc cleanup => crc setup => crc start` should be part of if any error message happen before we start the VM for `start` and for `crc cleanup => crc setup` for setup command failure.

**Comment by cfergeau** [comment]
A reproducer is:
```
eproducer:
```
$ crc-linux-1.17.0-amd64/crc setup
$ crc-linux-1.17.0-amd64/crc start
[...]
$ crc-linux-1.24.0-amd64/crc start
Error loading bundle metadata: oc not found in bundle
```
Does not happen with 1.19.0 instead of 1.17.0 which is consistent with when `oc` was added to the bundle ( [`1.19.0~21`](https://github.com/code-ready/crc/commit/2feb01f3910e9ec791460f7548c134ed43190fdf) )

**Comment by cfergeau** [comment]
This can be artificially reproduced by removing the `oc` binary from a bundle and trying to start crc.
This is a side-effect of [this commit](https://github.com/code-ready/crc/commit/d8c8b8d5b7eda770a28ce66275d6e886b1b26550). Before it, the preflight would most often fail after an upgrade. Without it, this triggers other codepaths which expect `oc` to be in the bundle (which is an also a bug). This explains why this only started to happen recently.

**Comment by cfergeau** [comment]
The root cause is https://github.com/code-ready/crc/commit/ed243aafde0b532b0a as suspected earlier.

**Comment by cfergeau** [comment]
The expected error message is `Bundle 'crc_libvirt_4.7.2.crcbundle' was requested, but the existing VM is using 'crc_libvirt_4.6.3.crcbundle'`

**Comment by cfergeau** [comment]
Problematic code is https://github.com/code-ready/crc/blob/c9657918dcee998fb1f132a1d32b3ba86344b54d/pkg/crc/machine/bundle/metadata.go#L142-L167
oc being embedded could have been indicated in the bundle info somehow.
