### ISSUE TITLE
Add API endpoint /api/logs for getting logs

### ISSUE THREAD

**Issue by anjannath** [code-ready/crc#2152]
Commit 3d5300ca4fd3da3c9044e5c7769b53d5024035c9 added functionality to get logs using the daemon api, this can be used from the binary protocol as 
`echo '{"command":"logs"}' | nc -U ~/.crc/crcd.sock` we should expose this from the HTTP api as well

**Comment by guillaumerose** [comment]
Fixed by https://github.com/code-ready/crc/commit/a6a4c7af02c040fe106c075cc436a64401d4d065
