### ISSUE TITLE
Don't write default config in `~/.crc/crc.json` when using `crc config set`

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#216]
When `~/.crc/crc.json` is missing, crc will create an empty file `{}` when needed. However, when `crc config set` is used, all config parameters are written to `~/.crc/crc.json` even if they have their default value:
```
$ ~/go/bin/crc config set warn-check-virtualbox-installed false
$ cat ~/.crc/crc.json 
{
  "bundle": "crc_vbox_4.1.0.tar.xz",
  "cpus": 4,
  "memory": 8192,
  "vm-driver": "hyperkit",
  "warn-check-virtualbox-installed": "false"
}
```
This is going to be a noticeable issue as we don't want the `bundle` name to stick on `crc` version upgrades if the user did not explicitly configure it. This would cause some confusion.

**Comment by anjannath** [comment]
The default values are loaded into [viper](https://github.com/spf13/viper) in `root.go` and when we write the config upon running `crc config set` those get written to the file as well.
https://github.com/code-ready/crc/blob/29eef0237ce8b6ee29e97ce7893f1e036b6b17fb/cmd/crc/cmd/root.go#L37-L40

The default values are loaded in the begining in root.go to make sure that when we use `config.Get()` later in the code we consider the defaults as well..
https://github.com/code-ready/crc/blob/29eef0237ce8b6ee29e97ce7893f1e036b6b17fb/cmd/crc/cmd/root.go#L68-L72

If we remove this, then we have to make sure that we get them from `cmd/config` pkg to get the defaults and not `config.Get()`.

**Comment by cfergeau** [comment]
I looked at viper, and it does not seem to be able to differentiate between default values and values we set ourselves :( 
One thing that we could probably do to workaround this is to keep a map of the config entries with a non-default value in `pkg/crc/config/viper_config.go` and only save these

**Comment by anjannath** [comment]
I took a look at it again yesterday, and found out that the default values are coming from the flags that we bind to the particular config properties.. 

https://github.com/code-ready/crc/blob/21c495d836a1f2218e3f21ec11bf6b3664ef7f0f/cmd/crc/cmd/start.go#L63-L71

The default values are coming from the constants package, and in case of the bundle, `constants.DefaultBundle` will be bumped, when the bundle is updated.

We should not have a problem when we update the bundle as flag values take precedence over the configured values, but we do have an issue with the config file.
