### ISSUE TITLE
podman binary name

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#2171]
The inclusion of the `podman` client is very inconsistent; as for Linux this can be the full implementation, while on macOS/Windows this is `podman-remote`.

When considering convenience and consistent use we want to settle on a single command; `podman`. This has been brought up before.

https://github.com/code-ready/snc/pull/378

**Comment by gbraad** [comment]
We will use `podman-remote`

**Comment by cfergeau** [comment]
Is there an upstream issue regarding the inconsistent naming?

**Comment by gbraad** [comment]
@cfergeau this is what I could find https://github.com/containers/podman/issues/5477#issuecomment-598996914 and there has been an email conversation around this.

**Comment by gbraad** [comment]
The interesting reply is: https://github.com/containers/podman/issues/5477#issuecomment-600052213

----
@rhatdan wrote:
Yes I agree, the executable should be podman.exe not podman-remote-windows.exe

----

The V2.2.1 releases are:

* podman-remote-release-darwin.zip
  * podman
* podman-remote-release-windows.zip
  * podman.exe
* podman-remote-static.tar.gz
  * podman-remote-static

So there is still an inconsistency between what the platforms provide as binary/command for inclusion.

**Comment by guillaumerose** [comment]
https://github.com/containers/podman/pull/9918 confirms what I have in https://github.com/code-ready/snc/pull/378

Linux: podman-remote
macOS: podman
Windows: podman.exe

**Comment by gbraad** [comment]
While great what @vrothberg concludes, this would lead to an inconsistency for use on #Linux if we expose this as a command.

`podman-env` would add to path, and would have to instruct the user based on the OS to either use `podman` or `podman-remote`, and this also needs to be documented accordingly. To me this feels like a bad UX.

**Comment by gbraad** [comment]
https://github.com/containers/podman/pull/9381

**Comment by guillaumerose** [comment]
In 1.26.0:
Linux: podman-remote
macOS: podman
Windows: podman.exe
