### ISSUE TITLE
Determining actions around sunsetting the single binary archive (macOS)

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#2181]
Since we now have an installer for macOS we need to determine how and when to take actions when it comes to sunsetting the single binary archive. For instance:

  * [x] how to handle the 'setup' (in relation to `crc setup`
  * [x] how to deal with providing the pull-secret 
  * [x] the integration with consumers, eg adapters (informing about timeline, so they can schedule around this)
     * [x] vscode
     * [x] eclipse
  * [ ] ...

**Comment by cfergeau** [comment]
We could stop shipping crc-macos-amd64.tar.xz now, and tell our consumers that they need to adjust how they install crc, and that they can find the crc executable in /usr/local/bin.

The first 2 items seem like additional integration work which is made possible by the use of an installer, but the single binary archive could be removed before or after they are done, this seems relatively independent.

**Comment by gbraad** [comment]
> We could stop shipping crc-macos-amd64.tar.xz now

I do not think this is the right approach as both the vscode adapters and the eclipse plugin use these files (download) to setup a local cluster environment.

@denisgolovin, @jeffmaury and @robstryker can likely tell you more about this.

**Comment by jeffmaury** [comment]
> 
> 
> > We could stop shipping crc-macos-amd64.tar.xz now
> 
> I do not think this is the right approach as both the vscode adapters and the eclipse plugin use these files (download) to setup a local cluster environment.
> 
> @dgolovin, @jeffmaury and @robstryker can likely tell you more about this.

Yes removing the tar.xz packaging for MacOS will break the CRC integration in JBoss Tools as we provide bootstrap experience. We are evaluating integrating .pkg into the next release of JBoss Tools / CodeReady Studio scheduled early July

**Comment by dgolovin** [comment]
Not breaking VSCode OpenShift Extension, bc installing the binaries is still user responsibility.
Is installer available only for macOS?

**Comment by dgolovin** [comment]
NM. I see it is only 'crc-macos-amd64.pkg', which would require to run packager on macOS to install. It is still archive for everything else.

**Comment by cfergeau** [comment]
> I do not think this is the right approach as both the vscode adapters and the eclipse plugin use these files (download) to setup a local cluster environment.

I was not suggesting to do it right away, I was using  'could' to express something purely hypothetical/rethoritical. All the steps that you list in this issue are not required before we can stop shipping the crc archive.

**Comment by gbraad** [comment]
Windows msi is currently being tested, but awaiting the signing to move forward.

**Comment by gbraad** [comment]
This sprint we will still carry the portable binary, but likely in sprint 201 we will drop this.

**Comment by gbraad** [comment]
Note: I believe there is another risk; an older release of the jboss tools, calling to install a newer version of CRC (after the release of CRS) could not handle specific pre-conditions.

**Comment by jeffmaury** [comment]
Here is an updated status on the JBoss Tools/Codeready Studio side:
- there is no way for us to not break existing installations as they share a common registry file where the CRC versions are listed and  older version will consider .pkg files as zip and will fail. Given the amount of users on MacOs, I think we can live with that as the workaround would be to use an older version of CRC or install CRC from outside JBT/CRS
- plan is to add support for .pkg and .msi files but the question is: does the current workflow still apply. So the current workflow is the following: user chooses a CRC version from the list, specifies an installation folder, CRC file is downloaded then expanded to that folder. In case of .pkg or .msi would it be possible to run the installer so that it installs on this folder ? Is there a way to pass that information when launching the installer ? Are there some other parameters that needs to be specified during installation ?

**Comment by cfergeau** [comment]
With the .pkg, and probably same with the msi, crc gets installed system-wide, and I'm not sure you can change the destination installation directory. I don't think you can specify any parameters at installation time. Would it be a blocker for you if it gets installed in a system location?

**Comment by jeffmaury** [comment]
At least it requires us to change the workflow as current workflow is requesting user to specify the installation folder and we'll need to find a way to get the folder where it has been installed. Is there a way to get 2 different installations of CRC with this new workflow ?

**Comment by robstryker** [comment]
I think enforcing a single system-wide version is a big mistake. Developers might need to test stuff between differing versions, say when upgrading a deployment to use the newer. They might need to test or debug the deployment on multiple versions to ensure it still runs correctly, or to help debug an issue on a newer version that wasn't replicatable on the old. 

There are other problems with a single system-wide installation. The entire webtools framework kinda assumes that each runtime has an installation folder that is relatively unchanging once installed. For example, if a user creates a "CRC 1.21" server adapter, he really shouldn't have any fear that the installation folder suddenly has its contents replaced with a CRC 1.22 installation. A single system-wide installation makes this an issue that will likely trip up a number of our processes. We will end up with stale "CRC 1.21" server adapters that actually run CRC 1.22 (bc it was upgraded behind the scenes) but possibly using 1.21 flags (as an example). We've had problems like this for other server adapters in the past. 

It seems unnecessary to me, and a net loss of control for the user, to be honest.

**Comment by gbraad** [comment]
> developers might need to test stuff between differing versions, say when upgrading a deployment to use the newer. 

We only 'support' the latest version, but we are also aware of the need to use older versions. However, this means this additional tests to ensure this works might have to be on your team?

**Comment by gbraad** [comment]
> I think enforcing a single system-wide version is a big mistake. 

You can have multiple bundles extracted as part of the user's `~/.crc/cache` folder. System-wide would only refer here to the binary.

**Comment by cfergeau** [comment]
> > I think enforcing a single system-wide version is a big mistake.
> 
> You can have multiple bundles extracted as part of the user's `~/.crc/cache` folder. System-wide would only refer here to the binary.

But a given crc release will only run one version of OpenShift, it's not possible to make it use another bundle you have in ~/.crc/cache.

**Comment by gbraad** [comment]
>  it's not possible to make it use another bundle you have in ~/.crc/cache.

... unless you specify `-b`, like the generated bundle. It is not an impossibility, but rather would like to understand more around this. @robstryker @jeffmaury any possibility of a meeting soon?

**Comment by gbraad** [comment]
>  I don't think you can specify any parameters at installation time. 

Possible for a Windows-based .msi install, but we have avoided this, as when people install in the user folder, which could be on a location other than the windrive, or a network share, this will fail startup. This is a known issue with the drivers/virtualization stack. When we use the system-wide installation of the `crc.exe` binary, we avoid this issue.

This might be possible for .pkg install, but this is untested.

**Comment by cfergeau** [comment]
> ... unless you specify -b, like the generated bundle

`-b` with release binaries only accepts a bundle with exactly the same name as the embedded one. This is being relaxed  with custom bundle generation, but only slightly, the bundle passed to `-b` will have to start with `crc_libvirt_4.7.5` if the release uses `crc_libvirt_4.7.5.crcbundle`

**Comment by jeffmaury** [comment]
> 
> 
> > it's not possible to make it use another bundle you have in ~/.crc/cache.
> 
> ... unless you specify `-b`, like the generated bundle. It is not an impossibility, but rather would like to understand more around this. @robstryker @jeffmaury any possibility of a meeting soon?

Feel free to schedule one

**Comment by guillaumerose** [comment]
Is the meeting scheduled ?

**Comment by jeffmaury** [comment]
No

**Comment by gbraad** [comment]
We have spoken briefly last week and decided to drop the phat-binary for macOS. The current release will not include this file anymore. However, Windows and Linux will be delivered as-is.
