### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by matgeb83** [code-ready/crc#2185]
### General information

  * OS: Linux RHEL 8.3
  * Hypervisor: KVM 
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop / Baremetal-Server / VM - on Vsphere? how can you run it on Baremetal? not the issue though just curios 

## CRC status

crc status
CRC VM:          Running
OpenShift:       Unreachable (v4.7.2)
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     13.17GB
Cache Directory: /home/mccadmin/.crc/cache

### CRC config  
```json
{
  "consent-telemetry": "yes",
  "cpus": 6,
  "disable-update-check": true,
  "disk-size": 40,
  "enable-cluster-monitoring": true,
  "enable-experimental-features": true,
  "host-network-access": true,
  "memory": 47000,
  "network-mode": "vsock",
  "pull-secret-file": /.mysecrets/ocp/pull-secret.json"
}
```

-  i needed to enable Host Network Access  and vsock .. and crc machine  was able to start successfully but ssh handshake failed after several attempt  as shown on the debug log below.   i also dont see the crc network - 192.168.130.1 when i enable vsock 

```
EBU RetryAfter timeout after 28 tries            
DEBU Making call to close driver server           
DEBU (crc) Calling .Close                         
DEBU Successfully made call to close driver server 
DEBU Making call to close connection to plugin binary 
DEBU (crc) DBG | time="2021-04-05T20:37:03-07:00" level=debug msg="Closing plugin on server side" 
Failed to connect to the CRC VM with SSH -- host might be unreachable: Temporary error: ssh command error:
command : exit 0
err     : ssh: handshake failed: read tcp 127.0.0.1:37520->127.0.0.1:2222: read: connection reset by peer\n
Temporary error: ssh command error:
command : exit 0
err     : ssh: handshake failed: read tcp 127.0.0.1:37522->127.0.0.1:2222: read: connection reset by peer\n
Temporary error: ssh command error:
command : exit 0
err     : ssh: handshake failed: read tcp 127.0.0.1:37524->127.0.0.1:2222: read: connection reset by peer\n
Temporary error: ssh command error:
command : exit 0
err     : ssh: handshake failed: read tcp 127.0.0.1:37526->127.0.0.1:2222: read: connection reset by peer\n
Temporary error: ssh command error:
command : exit 0
err     : ssh: handshake failed: read tcp 127.0.0.1:37528->127.0.0.1:2222: read: connection reset by peer\n
Temporary error: ssh command error:
command : exit 0
err     : ssh: handshake failed: read tcp 127.0.0.1:37530->127.0.0.1:2222: read: connection reset by peer\n
Temporary error: ssh command error:
command : exit 0
err     : ssh: handshake failed: read tcp 127.0.0.1:37532->127.0.0.1:2222: read: connection reset by peer\n
```

**Comment by gbraad** [comment]
> i also dont see the crc network - 192.168.130.1 when i enable vsock

vsock does NOT use the CRC network.
after the setup, did you make to use `crc delete; crc setup; crc start` to make sure the VM does not have an assigned network interface, as vsock will take care of this.

**Comment by praveenkumar** [comment]
> I needed to enable Host Network Access and vsock .. and crc machine was able to start successfully but ssh handshake failed after several attempt as shown on the debug log below. i also dont see the crc network - 192.168.130.1 when i enable vsock

@matgeb83 with `vsock` mode you shouldn't see `192.168.130.1` and that is expected.  Can you try following and provide the logs in a gist?

```
$ crc delete
$ crc cleanup
$ crc setup
$ crc start --log-level deug
```

**Comment by matgeb83** [comment]
@praveenkumar   per your request, below is the link for debug logs.  Thank you in advance for looking at this.  

https://gist.github.com/matgeb83/7bd8b293791a3706a0878dd4d7abed61

**Comment by gbraad** [comment]
@matgeb83 so did you delete the VM before getting the log?

```
err     : ssh: handshake failed: read tcp 127.0.0.1:37770->127.0.0.1:2222:
```

which suggest no connection can be made. This would suggest either the VM can not be assigned an IP as the interface we use for vsock is not made (which can only happen when the VM is not connected to the crc network), or that the daemon does not start,.

Can you open the Virtual Machine Manager and check the console of the VM to se what it says?

**Comment by matgeb83** [comment]
crc is powered on @gbraad.  and i did delete /.crc directory completely and did the setup and start. 
![ksnip_20210406-101504](https://user-images.githubusercontent.com/78124117/113734564-0dd74b80-96c1-11eb-8ebd-d3aa1ee8eb4d.png)

**Comment by cfergeau** [comment]
You need to start `crc daemon` in another terminal before `crc start` if you want networking to work, after reading this issue, it's not clear if this is being done or not.

**Comment by matgeb83** [comment]
daemon has been running 

 ps aux |grep crc
mccadmin    9270  0.0  0.0 2010556 41264 ?       Sl   Apr05   0:03 ./crc daemon

**Comment by matgeb83** [comment]
I was running daemon in the background and did not notice the following connection errors.  

evel=info msg="listening /home/mccadmin/.crc/crc-http.sock"
level=info msg="listening vsock://:1024"
level=info msg="listening /home/mccadmin/.crc/crc-http.sock"
level=error msg="Error reading from socket"
level=error msg="Error reading from socket"
2021/04/05 22:34:53 tcpproxy: for incoming conn 127.0.0.1:37762, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:35:04 tcpproxy: for incoming conn 127.0.0.1:37764, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:35:15 tcpproxy: for incoming conn 127.0.0.1:37766, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:35:26 tcpproxy: for incoming conn 127.0.0.1:37768, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:35:37 tcpproxy: for incoming conn 127.0.0.1:37770, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:35:48 tcpproxy: for incoming conn 127.0.0.1:37772, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:35:59 tcpproxy: for incoming conn 127.0.0.1:37774, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:36:10 tcpproxy: for incoming conn 127.0.0.1:37776, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:36:21 tcpproxy: for incoming conn 127.0.0.1:37778, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:36:32 tcpproxy: for incoming conn 127.0.0.1:37780, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:36:43 tcpproxy: for incoming conn 127.0.0.1:37782, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:36:54 tcpproxy: for incoming conn 127.0.0.1:37784, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:37:05 tcpproxy: for incoming conn 127.0.0.1:37786, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:37:16 tcpproxy: for incoming conn 127.0.0.1:37788, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:37:27 tcpproxy: for incoming conn 127.0.0.1:37790, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:37:38 tcpproxy: for incoming conn 127.0.0.1:37792, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:37:49 tcpproxy: for incoming conn 127.0.0.1:37794, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:38:00 tcpproxy: for incoming conn 127.0.0.1:37796, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:38:11 tcpproxy: for incoming conn 127.0.0.1:37798, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:38:22 tcpproxy: for incoming conn 127.0.0.1:37800, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:38:33 tcpproxy: for incoming conn 127.0.0.1:37802, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:38:44 tcpproxy: for incoming conn 127.0.0.1:37804, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:38:55 tcpproxy: for incoming conn 127.0.0.1:37806, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:39:06 tcpproxy: for incoming conn 127.0.0.1:37808, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:39:17 tcpproxy: for incoming conn 127.0.0.1:37810, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:39:28 tcpproxy: for incoming conn 127.0.0.1:37812, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:39:39 tcpproxy: for incoming conn 127.0.0.1:37814, error dialing "192.168.127.2:22": context deadline exceeded
2021/04/05 22:39:50 tcpproxy: for incoming conn 127.0.0.1:37816, error dialing "192.168.127.2:22": context deadline exceeded

**Comment by gbraad** [comment]
> error dialing "192.168.127.2:22": context deadline exceeded

this would suggest the VM got an address, but I do not see the assignment.

Are you perhaps on a VPN or sharing the same IP address range 192.168.127.0/24?

**Comment by matgeb83** [comment]
discovered that vsock does not work as expected on a nested virtualization environment.  tested vsock on a KVM installed on baremetal and it is correctly working.  

closing this bug ...

**Comment by gbraad** [comment]
> on Vsphere? 

Nested virtualization is not supported. Totally missed this.

> how can you run it on Baremetal? not the issue though just

No baremetal install available and also not scheduled. It might be a better idea to use the OpenShift installer for this.

**Comment by gbraad** [comment]
> discovered that vsock does not work as expected on a nested virtualization environment.

This is likely not caused by vsock, but rather the nested setup. We have only tested this on KVM nested or Hyper-V nested; so likely a regular switched setup would work... or not.

**Comment by matgeb83** [comment]
> 
> Note: running a 'baremetal'-option inside a VM would still not qualify as that would be unsupported/untested too... YMMV. #2080 #2125 #1031 #2082 are just a few of unexplained behaviour.

Just to be clear,   Baremetal +  RHEL virtualization install + CRC is supported right?  im talking about rather than installing RHEL 8 on baremetal and  CRC on top of it.  we can do RHEL 8 Virtualization (i.e. RHEL server UI install with virtual capabilities) on baremetal and CRC on top.

**Comment by cfergeau** [comment]
I don't understand the difference between rhel8 on baremetal, and  rhel server ui install with virtual capabilities on baremetal. rhel8 host with crc running there is fine. rhel8 host + rhel8 VM with crc running nested is at best supported on intel CPUs, and maybe some older AMD server CPUs.
