### ISSUE TITLE
[BUG] MacOS pkg installer skip step destination select

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/crc#2190]
### General information

 Tested on MacOS 10.14, with self built pkg installer:

```bash
make NO_CODESIGN=1 BUNDLE_DIR=~/jenkins/bundles out/macos-amd64/crc-macos-amd64.pkg
```

## CRC version

Pre release 1.25.0

### Steps to reproduce

  1.  Double click on pkg 
  2.  Installer start 
  3.  Tab Introduction. Click Continue
  3.  Tab License. Click Continue
  4.  Pop up on License Agreement. Click Agree
  5.  Installer jumps to Tab Installation Type, skipping Destination Select tab. Click Go Back
  6.  Go back to Tab License. Click Continue
  7.  Here goes to step 5..so destination can not be selected

### Expected

Select destination folder for installation

### Actual

Occasionally the full flow is honored and the destination folder can be selected... but most of the times ends up on a wrong flow.

**Comment by cfergeau** [comment]
Isn't the macOS install path hardcoded in the `crc` binary anyway?

**Comment by adrianriobo** [comment]
I mean I can install it, it uses the default path, but the problem is the flow with the installer is not consistent on every run

**Comment by cfergeau** [comment]
Yeah, Guillaume mentioned this inconsistency in the past, he was not sure why this is happening.

**Comment by guillaumerose** [comment]
Thanks for this! 
We should disable it at least for now. The path `/Applications/CodeReady Containers.app` is set in stone in `crc` binary. Moving the app would certainly break `crc`.
