### ISSUE TITLE
Is it possible to improve the start-up time of the new CRC instance?

### ISSUE THREAD

**Issue by rludva** [code-ready/crc#2191]
I am not sure if it is possible to improve the start-up time during which the CRC instance is starting.

Right now in a scenario where the CRC cluster is created for testing applications after each pull request, it is taking about 25 minutes before the OCP is ready for operation.

Is it possible to improve the start-up time in future releases?

**Comment by praveenkumar** [comment]
>  it is taking about 25 minutes before the OCP is ready for operation.

@rludva This should not be the case, can you provide bit more details why it is taking 25 mins, from fresh install it shouldn't take more than 10mins. Is this for an older release of crc or newer one?

**Comment by rludva** [comment]
It is for a new release but starting on OpenStack in a virtual machine. Probably more resource is important for the machine, like CPU/memory or there is some kind of network issue that slows down. We have to investigate more then.

**Comment by rludva** [comment]
_The additional start-up time was probably caused by adding an insecure registry which takes around 10 minutes to reconcile everything._ This script adds the stuff after crc start.
