### ISSUE TITLE
Add Gherkin tests for testing CLI functionality

### ISSUE THREAD

**Issue by agajdosi** [code-ready/crc#22]
I have done quick spike last week whether it would be possible to port parts of Minishift integration tests into CRC and it went successfully. For that purpose I have used the shell runner which was part of Minishift tests, which opens shell instance and runs all test commands in that instance.

It needs some polishing and few additions like - how to secure that CRC binary will be first on the path, but overall it should not take much time and is nearly ready. WDYT @LalatenduMohanty, @gbraad ?

**Comment by tsedmik** [comment]
+1

**Comment by gbraad** [comment]
sounds good.

Should this be part of the general repo? or shall we go ahead and for now create a separate repo and see if we can pull it in later. It seems like it can run standalone... right?

**Comment by agajdosi** [comment]
@gbraad Sure, we can create a separate repository for it. Theoretically it might be even useful for other folks, so we might keep it as package and then import it + implement `crc` specific steps in `crc` repository.

**Comment by gbraad** [comment]
@agajdosi and might help to test crc also with other tools, like odo... or even only odo if they prefer so. ;-)

**Comment by agajdosi** [comment]
Hi @LalatenduMohanty, based on the conversation above, would it be possible to create a repository for integration tests inside `code-ready` organization? As the code might be useful for others, maybe naming could be `clicumber`?

Until then I am working on it here: https://github.com/agajdosi/clicumber.

**Comment by agajdosi** [comment]
@gbraad @LalatenduMohanty @tsedmik @jsliacan Would be nice to have the resolution on whether to add the tests in here or whether to keep the tests separated in specific repo (in that case we need to come up with the name for the repo and create the repository in the code-ready namespace). Can we agree on having the resolution on tomorrow morning?

**Comment by tsedmik** [comment]
I opt for having it as a separate project. It can be used by others - who want to create tests based on CLI with Cucumber support.

And I also like the name `clicumber` :+1:

**Comment by gbraad** [comment]
Fixed by 35702327bc95514657d8198d34523f92e4fb2794
