### ISSUE TITLE
respect `XDG Base Directory Specification` on Linux and document handling on Windows/OSX

### ISSUE THREAD

**Issue by goern** [code-ready/crc#220]
The 'XDG Base Directory Specification' should be respected on GNU/Linux systems, as `crc` should not assume that it is ok to use `$HOME/.crc`

Handling of XDG ENV vars on other operating systems should be documented. At least most of the ENV should be respected on OSX.

**Comment by praveenkumar** [comment]
@goern we did think of it and since minishift/minikube also use `$HOME/.<project>` we went through this route instead of `XDG Base Directory Specification` so a user coming from these project should know where to look for files, in future, we should consider this.

**Comment by cfergeau** [comment]
In my opinion, once we have our initial releases, this will be much harder to change, so this really should be done early.

**Comment by Maurycy-Krzeminski** [comment]
Is there consideration to use XDG base directory, or maybe using some other named env variable that would allow to set where .crc folder should be?
