### ISSUE TITLE
Unable to access CRC Cluster post new user addition

### ISSUE THREAD

**Issue by krish-sriram** [code-ready/crc#2203]
I am running CRC-Windows-1.24.0  on Windows 10.
CodeReady Containers version: 1.24.0+5f06e84b
OpenShift version: 4.7.2 (embedded in executable)

I tried adding new user via the OC command line using the following link.

https://github.com/code-ready/crc/wiki/Add-another-user-to-cluster

Post the execution of this command , I am unable to login either using developer or kubeadmin on the browser.

**Comment by praveenkumar** [comment]
@krish-sriram In the wiki it is mentioned that it replace existing secret when using `oc replace -f` so you can now only login with your added user not the existing `kubeadmin` and `developer` one. Will try to update it to have some kind of append functionality so existing user always present.

**Comment by krish-sriram** [comment]
I am unable to access via new user as well.

**Comment by praveenkumar** [comment]
@krish-sriram We will try those steps again ourself and get back to you.

**Comment by krish-sriram** [comment]
@praveenkumar  I got logged out of cluster,  I will have to delete and recreate the cluster to try this out. I will try post the result here.

**Comment by praveenkumar** [comment]
> @praveenkumar I got logged out of cluster, I will have to delete and recreate the cluster to try this out. I will try post the result here.

@krish-sriram Sure, and please close this issue it that worked for you.

**Comment by praveenkumar** [comment]
Closing this since there is no response from reporter now.
