### ISSUE TITLE
Can't access crc from crc start on Fedora 33 - err: ssh: handshake failed

### ISSUE THREAD

**Issue by aireilly** [code-ready/crc#2214]
I can't get access to the crc VM on `crc start`.

```
time="2021-04-12T17:21:04+01:00" level=debug msg="error: Temporary error: ssh command error:\ncommand : exit 0\nerr     : ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain\\n - sleeping 1s"
time="2021-04-12T17:21:05+01:00" level=debug msg="retry loop: attempt 139"
time="2021-04-12T17:21:05+01:00" level=debug msg="Running SSH command: exit 0"
time="2021-04-12T17:21:05+01:00" level=debug msg="Using ssh private keys: [/home/aireilly/.crc/cache/crc_libvirt_4.7.2/id_ecdsa_crc]"
time="2021-04-12T17:21:05+01:00" level=debug msg="SSH command results: err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain, output: "
``` 
I've tried: 

```
$ crc stop -f
$ crc delete -f
$ crc cleanup
$ sudo rm -rf ~/.crc
< REBOOT >
$ crc setup
$ crc start --log-level debug
```
Software version: 
CodeReady Containers version: 1.24.0+5f06e84b
OpenShift version: 4.7.2 (embedded in executable
Fedora 33 (Workstation Edition)
[crc.log](https://github.com/code-ready/crc/files/6298297/crc.log)

I'm not on VPN, and running crc on a Lenovo thinkpad t590.

What can I try?

**Comment by cfergeau** [comment]
The VM has apparently failed to start, not sure why.
Can you check `virsh -c qemu:///system list` after `crc start` failed? And also look in `journalctl -u libvirtd`, and in `/var/lib/libvirt/qemu/crc.log`

**Comment by aireilly** [comment]
Thanks for quick response!

```aireilly@aireilly-t590: ~ $ virsh -c qemu:///system list
 Id   Name   State
----------------------
 1    crc    running```

journalctl -u libvirtd

```
-- Reboot --
Jan 31 10:24:16 VFIEVOX3.Router systemd[1]: Starting Virtualization daemon...
Jan 31 10:24:16 VFIEVOX3.Router systemd[1]: Started Virtualization daemon.
Jan 31 10:24:17 VFIEVOX3.Router dnsmasq[2139]: started, version 2.83 cachesize 150
Jan 31 10:24:17 VFIEVOX3.Router dnsmasq[2139]: compile time options: IPv6 GNU-getopt DBus no-UBus no-i18n IDN2 DHCP DHC>
Jan 31 10:24:17 VFIEVOX3.Router dnsmasq-dhcp[2139]: DHCP, IP range 192.168.122.2 -- 192.168.122.254, lease time 1h
Jan 31 10:24:17 VFIEVOX3.Router dnsmasq-dhcp[2139]: DHCP, sockets bound exclusively to interface virbr0
Jan 31 10:24:17 VFIEVOX3.Router dnsmasq[2139]: reading /etc/resolv.conf
Jan 31 10:24:17 VFIEVOX3.Router dnsmasq[2139]: using nameserver 127.0.0.53#53
Jan 31 10:24:17 VFIEVOX3.Router dnsmasq[2139]: read /etc/hosts - 2 addresses
Jan 31 10:24:17 VFIEVOX3.Router dnsmasq[2139]: read /var/lib/libvirt/dnsmasq/default.addnhosts - 0 addresses
Jan 31 10:24:17 VFIEVOX3.Router dnsmasq-dhcp[2139]: read /var/lib/libvirt/dnsmasq/default.hostsfile
Jan 31 10:25:39 VFIEVOX3.Router dnsmasq[2139]: reading /etc/resolv.conf
Jan 31 10:25:39 VFIEVOX3.Router dnsmasq[2139]: using nameserver 127.0.0.53#53
Jan 31 10:25:39 VFIEVOX3.Router dnsmasq[2139]: reading /etc/resolv.conf
Jan 31 10:25:39 VFIEVOX3.Router dnsmasq[2139]: using nameserver 127.0.0.53#53
Jan 31 10:25:39 VFIEVOX3.Router dnsmasq[2139]: reading /etc/resolv.conf
Jan 31 10:25:39 VFIEVOX3.Router dnsmasq[2139]: using nameserver 127.0.0.53#53
Jan 31 10:25:39 VFIEVOX3.Router dnsmasq[2139]: reading /etc/resolv.conf
Jan 31 10:25:39 VFIEVOX3.Router dnsmasq[2139]: using nameserver 127.0.0.53#53
Jan 31 10:25:39 VFIEVOX3.Router dnsmasq[2139]: reading /etc/resolv.conf
Jan 31 10:25:39 VFIEVOX3.Router dnsmasq[2139]: using nameserver 127.0.0.53#53
Jan 31 11:01:30 fedora dnsmasq[2139]: reading /etc/resolv.conf
Jan 31 11:01:30 VFIEVOX3.Router dnsmasq[2139]: using nameserver 127.0.0.53#53
Jan 31 11:01:30 VFIEVOX3.Router dnsmasq[2139]: reading /etc/resolv.conf

```
qemu/crc.log doesn't exist?
```
cat: /var/lib/libvirt/qemu/crc.log: No such file or directory
```

**Comment by aireilly** [comment]
Some more detail:

```
aireilly@aireilly-t590: ~ $ crc status
CRC VM:          Running
OpenShift:       Unreachable (v4.7.2)
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     13.17GB
Cache Directory: /home/aireilly/.crc/cache
aireilly@aireilly-t590: ~ $ crc config view
- consent-telemetry                     : yes
aireilly@aireilly-t590: ~ $ crc config view
- consent-telemetry                     : yes
aireilly@aireilly-t590: ~ $ crc ip
```

**Comment by aireilly** [comment]
```
aireilly@aireilly-t590: ~ $ free
              total        used        free      shared  buff/cache   available
Mem:       32620212     4680744     6564908      917296    21374560    26549456
Swap:       4194300           0     4194300

```

**Comment by praveenkumar** [comment]
@aireilly following is what concerning in your case, even VM is running
```
time="2021-04-12T17:21:05+01:00" level=debug msg="Using ssh private keys: [/home/aireilly/.crc/cache/crc_libvirt_4.7.2/id_ecdsa_crc]"
time="2021-04-12T17:21:05+01:00" level=debug msg="SSH command results: err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain, output: "
```

Which should be something like.
```
DEBU Using ssh private keys: [/home/prkumar/.crc/cache/crc_libvirt_4.7.5/id_ecdsa_crc] 
DEBU SSH command results: err: dial tcp 192.168.130.11:22: connect: no route to host, output:  
DEBU error: Temporary error: ssh command error:
command : exit 0
err     : dial tcp 192.168.130.11:22: connect: no route to host\n - sleeping 1s 
DEBU retry loop: attempt 1                        
DEBU Running SSH command: exit 0                  
```

Can you manually able to ssh to that running machine using `ssh -i /home/aireilly/.crc/cache/crc_libvirt_4.7.2/id_ecdsa_crc core@192.168.130.11` ? Also check from virt-manager if some issue with VM.

**Comment by gbraad** [comment]
When looking at:

```
Apr 12 17:22:30 aireilly-t590 dnsmasq-dhcp[5010]: DHCPACK(crc) 192.168.130.11 52:fd:fc:07:21:82 crc-rsppg-master-0
Apr 12 17:32:20 aireilly-t590 libvirtd[5152]: End of file while reading data: Input/output error
```

you see the VM DOES a DHCP request, gets an offer and acks this... but is followed by a failure. Likely it is not possible to persist the DHCP lease ? 

```
$ cat /var/lib/libvirt/dnsmasq/default.leases
```

Perhaps the following can show more about the network state
```
$ domifaddr crc
$ net-dhcp-leases crc
```

**Comment by aireilly** [comment]
I can ssh with `ssh -i /home/aireilly/.crc/cache/crc_libvirt_4.7.2/id_ecdsa_crc core@192.168.130.11`

but default.leases doesn't exist.

```
aireilly@aireilly-t590: ~ $ cat /var/lib/libvirt/dnsmasq/default.leases
cat: /var/lib/libvirt/dnsmasq/default.leases: No such file or directory
```
and 

````
virsh # net-dhcp-leases crc
error: failed to get network 'crc'
error: Network not found: no network with matching name 'crc'

virsh # domifaddr crc
error: failed to get domain 'crc'
```
`

**Comment by cfergeau** [comment]
The logs shows that `crc` failed to connect to the VM using something similar to `ssh -i /home/aireilly/.crc/cache/crc_libvirt_4.7.2/id_ecdsa_crc core@192.168.130.11`, but then the same command works. I'm wondering if it could be that the VM was very slow to start?

**Comment by aireilly** [comment]
Hi, so I updated my Fedora OS with some random system updates last night, and now my crc cluster comes up and I can interact with it completely normally. I wish there was more that I could say, is there anything else that I could provide now with running config that could help diagnose future issues like this?

**Comment by aireilly** [comment]
thanks for your help, I'll close this now.

**Comment by gbraad** [comment]
you could check `dnf history` and see what could have been the culprit before the update.

**Comment by aireilly** [comment]
`    94 | install docker --allowerasing                                                                 | 2021-04-13 13:12 | E, I           |    5 EE
    93 | remove docker docker-client docker-client-latest docker-common docker-latest docker-latest-lo | 2021-04-13 13:11 | Removed        |    5 EE
    92 | install docker-ce docker-ce-cli containerd.io                                                 | 2021-04-13 13:00 | Install        |    7 EE
    91 | remove docker docker-client docker-client-latest docker-common docker-latest docker-latest-lo | 2021-04-13 12:59 | Removed`

**Comment by gbraad** [comment]
Docker .... interesting. We had issues with this before, but these were around the DNS and resolving, but this mostly affected Docker instead of us.
