### ISSUE TITLE
crc OCP Unreachable after running several hours

### ISSUE THREAD

**Issue by matgeb83** [code-ready/crc#2222]
### General information

  * OS: Linux -RHEL 8 VM on Vsphere
  * Hypervisor: KVM 
  * Did you run `crc setup` before starting it (Yes/No)? yes
  * Running CRC on: Laptop / Baremetal-Server / VM  - Running it on VM Vsphere

## CRC version
1.24
  
## CRC status
DEBU CodeReady Containers version: 1.24.0+5f06e84b 
DEBU OpenShift version: 4.7.2 (embedded in executable) 
DEBU Running 'crc status'                         
DEBU Checking file: /home/mccadmin/.crc/machines/crc/.crc-exist 
DEBU Checking file: /home/mccadmin/.crc/machines/crc/.crc-exist 
DEBU Found binary path at /home/mccadmin/.crc/bin/crc-driver-libvirt 
DEBU Launching plugin server for driver libvirt   
DEBU Plugin server listening at address 127.0.0.1:41871 
DEBU () Calling .GetVersion                       
DEBU Using API Version 1                          
DEBU () Calling .SetConfigRaw                     
DEBU () Calling .GetMachineName                   
DEBU (crc) Calling .GetState                      
DEBU (crc) DBG | time="2021-04-13T15:06:55-07:00" level=debug msg="Getting current state..." 
DEBU (crc) DBG | time="2021-04-13T15:06:55-07:00" level=debug msg="Fetching VM..." 
DEBU (crc) Calling .GetBundleName                 
DEBU (crc) Calling .GetIP                         
DEBU (crc) DBG | time="2021-04-13T15:06:55-07:00" level=debug msg="GetIP called for crc" 
DEBU (crc) DBG | time="2021-04-13T15:06:55-07:00" level=debug msg="Getting current state..." 
DEBU (crc) DBG | time="2021-04-13T15:06:55-07:00" level=debug msg="IP address: 192.168.130.11" 
DEBU Running SSH command: df -B1 --output=size,used,target /sysroot | tail -1 
DEBU Using ssh private keys: [/home/mccadmin/.crc/machines/crc/id_ecdsa /home/mccadmin/.crc/cache/crc_libvirt_4.7.2/id_ecdsa_crc] 
DEBU SSH command results: err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain, output:  
DEBU Cannot get root partition usage: ssh command error:
command : df -B1 --output=size,used,target /sysroot | tail -1
err     : ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain\n 
DEBU Running SSH command: <hidden>                
DEBU Using ssh private keys: [/home/mccadmin/.crc/machines/crc/id_ecdsa /home/mccadmin/.crc/cache/crc_libvirt_4.7.2/id_ecdsa_crc] 
DEBU SSH command failed                           
DEBU cannot get OpenShift status: ssh command error:
command : timeout 5s oc get co -ojson --context admin --cluster crc --kubeconfig /opt/kubeconfig
err     : ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain\n 
DEBU Making call to close driver server           
DEBU (crc) Calling .Close                         
DEBU Successfully made call to close driver server 
DEBU Making call to close connection to plugin binary 
CRC VM:        DEBU (crc) DBG | time="2021-04-13T15:06:55-07:00" level=debug msg="Closing plugin on server side" 
  Running
OpenShift:       Unreachable (v4.7.2)
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     13.17GB
Cache Directory: /home/mccadmin/.crc/cache

## CRC config
- consent-telemetry                     : yes
- cpus                                  : 5
- disable-update-check                  : true
- disk-size                             : 40
- enable-cluster-monitoring             : true
- enable-experimental-features          : true
- memory                                : 18000
- pull-secret-file                      :/.mysecrets/ocp/pull-secret.json

## Host Operating System
Red Hat Enterprise Linux release 8.3 (Ootpa)

### Steps to reproduce

  1. crc start
  2. run containers for number of days 
  3. openshift status appear unreachable after sometime
  4. do crc stop and start. issue persist 

### Expected
To start successfully 

### Actual
openshift cluster unreachable.  

### Logs
https://gist.github.com/445fc84c2c5f3ffd2993675446d74771

i didnt attempt to do crc delete because i didnt want to recreate/deploy the containers that were running.  are there any known solutions for this issue or work arounds so i dont have to lose my containers?

**Comment by gbraad** [comment]
> Linux -RHEL 8 VM on Vsphere

We do not support nested virtualization as a setup. Please try this on a desktop and see if this is reproducible.
We had a similar report before, but this was also a nested-virt setup.

**Comment by gbraad** [comment]
```
DEBU Running SSH command: df -B1 --output=size,used,target /sysroot | tail -1 
DEBU Using ssh private keys: [/home/mccadmin/.crc/machines/crc/id_ecdsa /home/mccadmin/.crc/cache/crc_libvirt_4.7.2/id_ecdsa_crc] 
DEBU SSH command results: err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain, output:  
```

Can't get access with ssh, so check if the node is actually running. Might be under memory pressure or so as it can not authenticate.

**Comment by matgeb83** [comment]
okay i will  stop crc and increase the cpu/memory and  start it again and see if that resolves the issue.
