### ISSUE TITLE
[BUG] Spurious dialogs about not being able to delete cluster pop up under MacOS with crc 1.25 setup

### ISSUE THREAD

**Issue by bentito** [code-ready/crc#2226]
### General information

  * OS:  macOS
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it (Yes/No)? Errors were on running crc setup
  * Running CRC on: Laptop

## CRC version
```bash
# Put `crc version` output here
CodeReady Containers version: 1.25.0+0e5748c8
```
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
crc status --log-level debug
DEBU CodeReady Containers version: 1.25.0+0e5748c8
DEBU OpenShift version: 4.7.5 (embedded in executable)
DEBU Running 'crc status'
DEBU Checking file: /Users/btofel/.crc/machines/crc/.crc-exist
Machine does not exist. Use 'crc start' to create it
```

## CRC config
```bash
# Put `crc config view` output here
crc config view
- consent-telemetry                     : no
- cpus                                  : 12
- memory                                : 20480
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
sw_vers
ProductName:	macOS
ProductVersion:	11.2.3
BuildVersion:	20D91
```

### Steps to reproduce

  1. crc delete
  2. replace crc 1.24 binary with 1.25
  3. crc setup

### Expected
Run setup with no errors

### Actual
Setup seemed to run okay, but popped a sequence of UX dialogs saying it could not stop the OpenShift cluster and one other type (sorry I missed). Popped about 5-6 dialogs. I was able to dismiss all. 1.25 seems to be starting just fine.

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by anjannath** [comment]
@bentito Unfortunately can't reproduce this on my macOS (10.14.6), is this consistently reproducible for you? providing screenshots of the actual pop-ups would help us in debugging this.

**Comment by bentito** [comment]
No, sorry, can't reproduce anymore either.

**Comment by bentito** [comment]
No I can't reproduce any more either, probably safe to close.
