### ISSUE TITLE
Rework podman preflight checks/support

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#2227]
I noticed that the podman URL that crc uses is outdated (https://storage.googleapis.com/libpod-master-releases rather than https://github.com/containers/podman/releases/download/ ).
However, since podman will be shipped with the bundle, this URL should not be needed.
The podman preflight check is also disabled at the moment, but the podman binary from the bundle is currently not used.

**Comment by guillaumerose** [comment]
Done in 1.26.0
