### ISSUE TITLE
[BUG] Updating the pull-secret secret does not have any effect

### ISSUE THREAD

**Issue by jwendell** [code-ready/crc#2229]
### General information

  * OS: Linux
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it? Yes
  * Running CRC on: Laptop

## CRC version
```bash
CodeReady Containers version: 1.25.0+0e5748c8
OpenShift version: 4.7.5 (embedded in executable)
```
  
## CRC status
```bash
DEBU CodeReady Containers version: 1.25.0+0e5748c8 
DEBU OpenShift version: 4.7.5 (embedded in executable) 
DEBU Running 'crc status'                         
DEBU Checking file: /home/jwendell/.crc/machines/crc/.crc-exist 
DEBU Checking file: /home/jwendell/.crc/machines/crc/.crc-exist 
DEBU Found binary path at /home/jwendell/.crc/bin/crc-driver-libvirt 
DEBU Launching plugin server for driver libvirt   
DEBU Plugin server listening at address 127.0.0.1:35283 
DEBU () Calling .GetVersion                       
DEBU Using API Version 1                          
DEBU () Calling .SetConfigRaw                     
DEBU () Calling .GetMachineName                   
DEBU (crc) Calling .GetState                      
DEBU (crc) DBG | time="2021-04-15T12:34:44-04:00" level=debug msg="Getting current state..." 
DEBU (crc) DBG | time="2021-04-15T12:34:44-04:00" level=debug msg="Fetching VM..." 
DEBU (crc) Calling .GetBundleName                 
DEBU (crc) Calling .GetIP                         
DEBU (crc) DBG | time="2021-04-15T12:34:44-04:00" level=debug msg="GetIP called for crc" 
DEBU (crc) DBG | time="2021-04-15T12:34:44-04:00" level=debug msg="Getting current state..." 
DEBU (crc) DBG | time="2021-04-15T12:34:44-04:00" level=debug msg="IP address: 192.168.130.11" 
DEBU Running SSH command: df -B1 --output=size,used,target /sysroot | tail -1 
DEBU Using ssh private keys: [/home/jwendell/.crc/machines/crc/id_ecdsa /home/jwendell/.crc/cache/crc_libvirt_4.7.5/id_ecdsa_crc] 
DEBU SSH command results: err: <nil>, output: 32737570816 11999858688 /sysroot 
DEBU Running SSH command: <hidden>                
DEBU SSH command succeeded                        
DEBU Unexpected operator status for network: ManagementStateDegraded 
DEBU Making call to close driver server           
DEBU (crc) Calling .Close                         
DEBU Successfully made call to close driver server 
DEBU Making call to close connection to plugin binary 
DEBU (crc) DBG | time="2021-04-15T12:34:47-04:00" level=debug msg="Closing plugin on server side" 
CRC VM:          Running
OpenShift:       Running (v4.7.5)
Disk Usage:      12GB of 32.74GB (Inside the CRC VM)
Cache Usage:     13.4GB
Cache Directory: /home/jwendell/.crc/cache
```

## CRC config
```bash
- consent-telemetry                     : yes
- memory                                : 16384
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
NAME=Fedora
VERSION="33 (Workstation Edition)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f33/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

### Steps to reproduce

  1. After started, update the secret `pull-secret`, e.g., with a command like `oc set data secret/pull-secret -n openshift-config --from-file=.dockerconfigjson`
  2. Try to deploy a pod whose image points to a protected registry
  3. Pod does not start: `unauthorized: access to the requested resource is not authorized`

### Expected

Kubelet makes use of the updated credentials when pulling the image

### Actual

Kubelet does not notice the change of the secret and tries to pull the image using old/wrong credentials

### Workaround

  1. Delete the machine, and when starting it again, use `crc start --pull-secret-file=/path/to/file`.
  2. Kubelet pulls sucessfully the image using the correct credentials.

**Comment by praveenkumar** [comment]
@jwendell When you update the gobal pull secret (from `openshift-config` namespace), machine config operator take care of updating `/var/lib/kubelet/config.json` on the node, In crc case since it is single node and we disable the MCO so either you have to add your secret to the secret file before running crc (which you mentioned in workaround) and might be the best thing. Other thing you can do is ssh to the crc VM and manually update that `kubelet/config.json` file and restart the crio/kubelet. 

I don't think it is a bug but a limitation and might be we can mention it as part of document.

**Comment by gbraad** [comment]
This is a limitation as the controlled/coordinated reconciliation can not happen when there is no quorum. We might wanna add a statement to the documentation? Although, this is a 1% situation as the simplest way is to `crc delete` and `crc start` with the new pull-secret. CRC should be considered ephemeral

**Comment by guillaumerose** [comment]
I hope that with OpenShift 4.8 we can avoid removing the MCO. It may require to restart the node although.

**Comment by cfergeau** [comment]
Is this the only way of accessing a protected registry? Or can you specify a non-global pull secret to access it?
