### ISSUE TITLE
Better info message(s) after crc config set

### ISSUE THREAD

**Issue by navidshaikh** [code-ready/crc#224]
If we set the params via `config set`, the info message printed post operation could be improved

```
 # ./crc config set memory 20480
crc - Local OpenShift 4.x cluster

# ./crc config set cpus 4      
crc - Local OpenShift 4.x cluster
```

here `crc - Local OpenShift 4.x cluster` doesn't indicate anything, either remove it or may be something like `Successfully configured memory to X`.

**Comment by gbraad** [comment]
this command would not have effect on the current instance. it would only apply these settings to new instance.

feedback will be added.

**Comment by navidshaikh** [comment]
> it would only apply these settings to new instance.

You mean one needs to delete and re-create the instance if updated the resource allocation via config ?
IIUC, a reboot is needed.
