### ISSUE TITLE
Document the changes and use of vsock (macOS)

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#2256]
With the upcoming release of CRC, v1.26 we are changing the network mode that we use from the current hypervisor driver IP assignment to the vsock userspace network stack. This allows us to use a more fine-grained approach to network ports, routes, etc, but it also means the current method will become a 'legacy' option. While it should be transparent to the user, some changes will be made to how the DNS is configured, or for people to get access to the VM.

Note: the main reason we have this vsock option is because it allows people to use CRC while needing a VPN connectivity.

**Comment by gbraad** [comment]
@robin-owen @guillaumerose

**Comment by praveenkumar** [comment]
But we also need to document this option for the linux also in case user want to use `vsock` as with v1.26 it shouldn't be experimental feature right?

**Comment by gbraad** [comment]
At the moment this is also not the default on Windows. Perhaps we can stage this for Sprint 201; enable for Windows as default and for Linux as an option.

**Comment by cfergeau** [comment]
It's now the default on macOS and Windows (when the installer is used). The option will most likely be removed soon on both platforms (gone already with the macOS installer, and https://github.com/code-ready/crc/pull/2661 does the same change for the Windows installer).
