### ISSUE TITLE
Don't show warn message for wildcard dns resolution in case of vsock mode

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#2259]
In case of vsock mode we add the router controller which add the route entry to `/etc/hosts` as soon as there is any route created. As part of our default/legacy mode we have a check which verify if dns settings are as expected to resolve wildcard dns entry using `foo.apps-crc.testing` . Either we change it to something known like `canary-openshift-ingress-canary.apps-crc.testing` which we put in `/etc/hosts` before hand or just add another check which will make sure in case of vsock this is not executed.

**Comment by cfergeau** [comment]
The goal of the check is to make sure DNS resolution is set up as expected with default networking. I would just skip it when the routes controller is in use. If knowing if the routes controller is in use is not possible, then we can skip it when vsock is used.
