### ISSUE TITLE
Add preflight checking for M1 CPUs

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#2269]
https://github.com/code-ready/crc/issues/2047 is about a mysterious hyperkit startup failure.
Praveen pointed out this happens on a M1 machine. Since M1 is both untested and unsupported, we should add a preflight check detecting this.

**Comment by Dennis-kw-yiu** [comment]
hi @cfergeau will M1 will be supported in the future?

**Comment by Dennis-kw-yiu** [comment]
hi @cfergeau will M1 will be supported in the future?

**Comment by cfergeau** [comment]
This is not in our short term plans. If I'm not mistaken, the M1 is currently limited to 16GB of RAM, which is unfortunately a bit too small for crc, and there is no native ARM OpenShift version. Not clear how good/bad using x86 emulation in a VM would be, if at all possible.

**Comment by guillaumerose** [comment]
Code that might help to detect this: https://github.com/kubernetes/minikube/blob/241112f4ea1fab2cd91276dc76362b86e2941c65/pkg/minikube/detect/detect.go#L54

**Comment by gbraad** [comment]
> will M1 will be supported in the future?

We do not at the moment, but in future might. It does depend on access to these machines, amount of available memory or if possible the availability of an ARM release of OpenShift (avoiding the emulation).
