### ISSUE TITLE
Provide an easier way to authenticate

### ISSUE THREAD

**Issue by nicolaferraro** [code-ready/crc#227]
This is a feature request to improve user experience.

After starting a crc cluster, instructions on how to authenticate are not provided in the logs. User and password are provided, but not the exact API URL to authenticate against.

Password is complex to remember and if it happens that you play a bit in the console, you lose it and the only way to recover it is to stop and restart crc to have it printed again.

Auto-creation of users is disabled. It was nice if I could "oc login -u developer" without having to create the "developer" user in advance.

Ability to use any-password is also a nice feature that can be added, since it seems too complex to create a new user on crc.

**Comment by J0EG** [comment]
After creating a user vi htpasswd file and logging into the cli, is there anything that needs to be done to allow web console login for that user. I agree there should be a developer user for users to play with and get running right away.

**Comment by hupiper** [comment]
I was able to add a developer user by following the docs on configuring an htpasswd identity provider: https://docs.openshift.com/container-platform/4.1/authentication/identity_providers/configuring-htpasswd-identity-provider.html

**Comment by anjannath** [comment]
A `developer` user with password `developer` is now added, and available in the new release.
