### ISSUE TITLE
[BUG] Doc step not working on RHEL 7.9 workstation for setting up a CRC remote server

### ISSUE THREAD

**Issue by varshab1210** [code-ready/crc#2278]
### General information
  * OS: RHEL 7
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it - yes 
  * Running CRC on: Baremetal-Server
## CRC version
```bash
# Put `crc version` output here
```
$ ./crc version
CodeReady Containers version: 1.25.0+0e5748c8
OpenShift version: 4.7.5 (embedded in executable)
## CRC status
```bash
# Put `crc status --log-level debug` output here
```
Not required for the issue i am hitting, however here is the status
$ ./crc status
CRC VM:          Running
OpenShift:       Running (v4.7.5)
Disk Usage:      15.14GB of 32.74GB (Inside the CRC VM)
Cache Usage:     13.4GB
Cache Directory: /home/node4/.crc/cache
## CRC config
```bash
# Put `crc config view` output here
```
$ ./crc config view
- consent-telemetry                     : no
- memory                                : 92160
Not required for the issue i am hitting
## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```
[node4@tools-node4 ~]$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux Workstation"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Workstation"
VARIANT_ID="workstation"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux Workstation 7.9 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:workstation"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
[node4@tools-node4 ~]$
### Steps to reproduce
Following https://code-ready.github.io/crc/#setting-up-remote-server_gsg to setup the crc remote server.
  1. At step 2 of the doc 
  ```
$ dnf install haproxy policycoreutils-python-utils
Last metadata expiration check: 15:11:53 ago on Mon 26 Apr 2021 07:54:32 PM IST.
Package haproxy-1.5.18-9.el7.x86_64 is already installed.
No match for argument: policycoreutils-python-utils
Error: Unable to find a match: policycoreutils-python-utils
[data2@tools-data2 ~]
```
**NOTE:** I can find a thread of discussion regarding the issue i am hitting. As per the thread, one suggestion is migrating the os to rhel 8.2 and other less loud suggestion is use the RHEL 7.9. I tried the the steps given in https://code-ready.github.io/crc/#setting-up-remote-server_gsg on RHEL 7.9 but step 2 did not work 
### Expected
Step should work
### Actual
Given steps are not working 
### Logs
Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```
Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by gbraad** [comment]
> Error: Unable to find a match: policycoreutils-python-utils

While we suggest 7.5 or higher is supported, I am not sure if this process is regularly tested. We know it works on Fedora and RHEL 8.x for instance, but this package seems to be missing... but relevant?

Please continue installing `dnf install haproxy` and ignore the policycore package (or at least install `policycoreutils-python`).

Does that work?

**Comment by varshab1210** [comment]
Yes, ```policycoreutils-python``` worked. Thanks!

**Comment by gbraad** [comment]
@robin-owen @adrianriobo @jsliacan  is this up to date? Might have to retest this on RHEL 7.x ... and consider how to make sure this becomes a tested scenario; when in docs we need to 'support' it.

**Comment by adrianriobo** [comment]
> Not sure if this is actually is needed

It seems this is a dependency for `semanage` and the library name has change from RHEL 7.X (policycoreutils-python) to RHEL 8.X (policycoreutils-python-utils). So the question around the docs is if we want to cover every specific supported version?

On the other hand afaik there is no e2e test covering this. And probably it would be great to have that kind of test (setting remote access + setting client to access it, then operate the cluster from the client) As we already know this is a user story which clients are implementing

**Comment by cfergeau** [comment]
`yum install /usr/sbin/semanage` will work on both RHEL7 and RHEL8, we can switch to this rather than `policycoreutils-python`

**Comment by gbraad** [comment]
> On the other hand afaik there is no e2e test covering this. And probably it would be great to have that kind of test (setting remote access + setting client to access it, then operate the cluster from the client) As we already know this is a user story which clients are implementing

We need to consider what the priority of this is. At least it should be recorded.
