### ISSUE TITLE
bundle generation statement in release notes 1.26

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#2286]
For Linux we offer a new command that allows you to export the current cluster bundle for distribution within for instance a team or CI. This is currently in preview.

```
$ crc bundle
```

@praveenkumar any additional notes?

**Comment by cfergeau** [comment]
"This currently in preview, and the command, its parameters or its behaviour may be changed in incompatible ways in the future."? Or we don't need to be so verbose/careful?

**Comment by praveenkumar** [comment]
> "This currently in preview, and the command, its parameters or its behaviour may be changed in incompatible ways in the future."? Or we don't need to be so verbose/careful?

@cfergeau Yes that should be more explicit but during preview do we change the parameters? I think that we can only do for experimental commands?

**Comment by robin-owen** [comment]
There's no explicit need to state this with a technology preview. We include a generic statement regarding such.
