### ISSUE TITLE
Feature request: allow switching CNI to OVN-Kubernetes

### ISSUE THREAD

**Issue by jotak** [code-ready/crc#2294]
OpenShift can be used with OpenShiftSDN, which has been the default for a while, or OVN-Kubernetes. In future releases, the default plugin should change to OVN-Kubernetes.

While this is probably going to be transparent for most application developers who use CRC, it's still perhaps a good idea to allow switching from one to another in CRC.
Personally it would also help me to use some features that OVN-Kubernetes only provides.

Not sure what would be the best way to proceed, should it be a crc config or something else...
The OpenShift documentation mentions two ways to use OVN-Kubernetes, either [by editing manifests before cluster installation](https://docs.openshift.com/container-platform/4.7/networking/ovn_kubernetes_network_provider/configuring-hybrid-networking.html#configuring-hybrid-ovnkubernetes_configuring-hybrid-networking) or [by following this migration guide](https://docs.openshift.com/container-platform/4.7/networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.html) on an existing cluster.

For some reason I couldn't follow the migration guide, and I'm not sure if it's due to something special in CRC or something different. (I can file a different issue about that). But basically, when restarting the (unique) node, openshift never recovers and its status remains as "unreachable" forever.

**Comment by cfergeau** [comment]
> For some reason I couldn't follow the migration guide, and I'm not sure if it's due to something special in CRC or something different.

If these instructions rely on the MCO to be functional, then this could be the issue as CRC disables it.

**Comment by jotak** [comment]
I see, so the only remaining way would be to act before cluster installation (if I understand what you told me, it's more something with snc)

**Comment by praveenkumar** [comment]
> I see, so the only remaining way would be to act before cluster installation (if I understand what you told me, it's more something with snc)

@jotak Right, better to try with snc.

**Comment by jotak** [comment]
Would it mean to produce twice as many artifacts for download, one for openshift-sdn and another for ovn-k (x number of currently supported architectures) ?

**Comment by praveenkumar** [comment]
> Would it mean to produce twice as many artifacts for download, one for openshift-sdn and another for ovn-k (x number of currently supported architectures) ?

@jotak I am just saying for special use case, for CRC we are not changing the default but we are planning to have MCO running when we create bundle from 4.8 release (which support single node).

**Comment by gbraad** [comment]
CRC will only deliver images with the 'default' that the installer will offer.

**Comment by srampal** [comment]
I second this feature request. There are many differences between the default Openshift SDN based CNI and the OVN-Kubernetes based CNI option (and the forward direction for Openshift is to move to OVN-Kubernetes) .. the current CNI default is mainly for backwards compatibility. Hence it would be very useful for testing, development, demos etc if CRC could support both CNI options.

**Comment by cfergeau** [comment]
Our plan is still to enable the MCO for our 4.8-based releases. When this is released, it will be useful to check if the migration guide can now be successfully followed or not.

**Comment by cfergeau** [comment]
The last 2 crc releases have been 4.8  based with the MCO enabled, maybe switching to OVN-Kubernetes now works by following the steps in the OpenShift documentation?

**Comment by rhrazdil** [comment]
I'm failing to follow documenation for migration to OVN kubernetes.
After completing the migration, I always get to the following state:
```
oc get co
NAME                                       VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
authentication                             4.9.12    False       False         True       15m     OAuthServerRouteEndpointAccessibleControllerAvailable: Get "https://oauth-openshift.apps-crc.testing/healthz": dial tcp 192.168.130.11:443: connect: connection refused
config-operator                            4.9.12    True        False         False      7d3h    
console                                    4.9.12    False       True          False      14m     DeploymentAvailable: 0 replicas available for console deployment...
dns                                        4.9.12    True        False         False      7m4s    
etcd                                       4.9.12    True        False         False      7d3h    
image-registry                             4.9.12    True        False         False      26m     
ingress                                    4.9.12    True        False         True       7d3h    The "default" ingress controller reports Degraded=True: DegradedConditions: One or more other status conditions indicate a degraded state: CanaryChecksSucceeding=False (CanaryChecksRepetitiveFailures: Canary route checks for the default ingress controller are failing)
kube-apiserver                             4.9.12    True        False         False      7d3h    
kube-controller-manager                    4.9.12    True        False         False      7d3h    
kube-scheduler                             4.9.12    True        False         False      7d3h    
machine-api                                4.9.12    True        False         False      7d3h    
machine-approver                           4.9.12    True        False         False      7d3h    
machine-config                             4.9.12    True        False         False      7d3h    
marketplace                                4.9.12    True        False         False      7d3h    
network                                    4.9.12    True        False         False      7d3h    
node-tuning                                4.9.12    True        False         False      27m     
openshift-apiserver                        4.9.12    True        False         False      27m     
openshift-controller-manager               4.9.12    True        False         False      26m     
openshift-samples                          4.9.12    True        False         False      7d3h    
operator-lifecycle-manager                 4.9.12    True        False         False      7d3h    
operator-lifecycle-manager-catalog         4.9.12    True        False         False      7d3h    
operator-lifecycle-manager-packageserver   4.9.12    True        False         False      7m4s    
service-ca                                 4.9.12    True        False         False      7d3h 
```

where authentication,  console and ingress cluster operators are in error state.

**Comment by rhrazdil** [comment]
@cfergeau  maybe worth reopening this?

**Comment by gbraad** [comment]
> and the forward direction for Openshift is to move to OVN-Kubernetes

Unless this is the default for OpenShift this remains a non-standard approach. We are providing an environment for development purposes first. I do not see a motivation for us to investigate this. You are however more than welcome to look into this and update the instructions.

**Comment by gbraad** [comment]
Note that the docs state clearly:

-----


You must configure hybrid networking with OVN-Kubernetes during the installation of your cluster. You **cannot** switch to hybrid networking after the installation process.


-----

Therefore, this needs to be done by creating a custom bundle. Please look at snc.

**Comment by rhrazdil** [comment]
@gbraad Thanks for your reply!

> The migration might assume the control plane gets restarted in a coordinated way. This might not work for a single node.

Migration worked for me on a single node cluster running on bare metal, so that shouldn't be an issue.

> Note that the docs states:
> You must configure hybrid networking with OVN-Kubernetes during the installation of your cluster. You cannot switch to hybrid networking after the installation process.
> Therefore, consider creating a custom bundle to verify this.

Well, I'm not interested in hybrid networking, IIUC this shouldn't concern users who would only like to perform migration to OVN, as it's not a prerequisite for that, right?

> Last, our images are based on the libvirt provider and this is not a supported provider according to the migration guide.

Yeah.. I can't tell whether this causes the issue or not. I don't have capacity to dig deeper atm. I may get a chance to try this in the future though.

**Comment by gbraad** [comment]
We also wouldn't have the time. It is interesting to note this worked on baremetal single node.

It might be a combination with of the dummy interface and a non-supported provider

**Comment by gbraad** [comment]
> as it's not a prerequisite for that, right

Couldn't say. We are not the experts / implementors of OVN. Perhaps better to find those as they might understand better what is happening here.
