### ISSUE TITLE
[BUG] CRC daemon isn't stopped or disabled by `crc cleanup`

### ISSUE THREAD

**Issue by jsliacan** [code-ready/crc#2313]
This topic seems to include also e.g. #2305

### General information

  * OS: Linux
  * Hypervisor: KVM

## CRC version
```bash
CodeReady Containers version: 1.26.0+8f6f946f
OpenShift version: 4.7.7 (not embedded in executable)
```
### Steps to reproduce

  1. Run `crc daemon` and observe pid.
  2. Run `crc cleanup`.
  3. Check that the daemon process with the pid from step 1 is still running.

### Expected
Cleanup kills daemon process. 

### Actual

```
$ crc status
Machine does not exist. Use 'crc start' to create it
$ crc daemon
daemon is already running
$ top -b | grep crc
1446146 jsliacan  20   0 1950872  51212  20972 S   0.0   0.2   1:22.73 crc
$ crc cleanup
INFO Removing vsock configuration                 
INFO Removing 'crc' network from libvirt          
INFO Removing /etc/NetworkManager/dispatcher.d/99-crc.sh file 
INFO Removing the crc VM if exists                
INFO Removing pull secret from the keyring        
INFO Removing older logs                          
INFO Removing hosts file records added by CRC     
INFO Removing CRC Machine Instance directory      
Cleanup finished
$ top -b | grep crc
1446146 jsliacan  20   0 1950872  51212  20972 S   0.0   0.2   1:22.73 crc
```

**Comment by cfergeau** [comment]
I think this is still the case.

**Comment by praveenkumar** [comment]
I think on linux now it is handled by socket activation and for mac/windows tray suppose to do that. Should we also do that with `crc cleanup` ?

**Comment by anjannath** [comment]
> 
> 
> I think on linux now it is handled by socket activation and for mac/windows tray suppose to do that. Should we also do that with `crc cleanup` ?

On windows and macOS the daemon is started from tray, so as soon as tray is gone, the daemon process also dies. 

For linux i think we'll have to remove the systemd unit for the daemon?

**Comment by cfergeau** [comment]
For linux, `removeDaemonSystemdService` runs during `cleanup` and stops the daemon/remove its unit files, so this is done.
