### ISSUE TITLE
[BUG] Consistency of config file is not checked after every change

### ISSUE THREAD

**Issue by jsliacan** [code-ready/crc#2314]
### General information

  * OS: Linux
  * Hypervisor: KVM

## CRC version
```bash
CodeReady Containers version: 1.26.0+8f6f946f
OpenShift version: 4.7.7 (not embedded in executable)
```

## CRC config
```bash
- bundle                                : /home/jsliacan/Downloads/crc_libvirt_4.7.7.crcbundle
- consent-telemetry                     : no
- host-network-access                   : true
- memory                                : 10200
- pull-secret-file                      : /home/jsliacan/Downloads/crc-pull-secret
```

### Steps to reproduce

  1. `crc config set network-mode vsock`
  2. `crc config set host-network-access true`
  3. `crc config unset network-mode`
  4. Host network access isn't supported for non-vsock network mode(s), yet config file accepts that combination.

**Note**: The combination is not allowed if `network-mode` is unset and user tries to set `host-network-access` to `true`. However, user is allowed to unset `network-mode` away from `vsock` even without changing `host-network-access` to `false`. 

### Expected
Validity of config combinations is enforced consistently.

**Comment by gbraad** [comment]
the same is currently the case for nameserver: #1879. the setting is 'ignored', but the user is not informed about this.
