### ISSUE TITLE
[BUG] Default settings are not treated as config settings

### ISSUE THREAD

**Issue by jsliacan** [code-ready/crc#2315]
### General information

  * OS: Linux
  * Hypervisor: KVM

## CRC version
```bash
CodeReady Containers version: 1.26.0+8f6f946f
OpenShift version: 4.7.7 (not embedded in executable)
```

## CRC config
```bash

```

### Steps to reproduce

  1. `crc start --disk-size 40`
  2. `crc stop` && `crc config unset disk-size` (if it was set)
  3. `crc start` (should fall back on default 31G & complain that shrink not supported)

**Note**: if the default value of 31G is explicitly set in config, CRC complains at start as it should. Only implicit default results in the above.

### Expected
Specified disk size is less than current one, not allowed. (or something similar)

### Actual
Starts without warnings/info/error but ignores the default setting and keeps previous 40G.

**Comment by gbraad** [comment]
> `crc start --disk-size 40`
> `crc stop` && `crc config unset disk-size` (if it was set)
> `crc start` (should fall back on default 31G & complain that shrink not supported)

I believe the config option is only considered at the moment the VM is created; meaning, when not existing and started.
