### ISSUE TITLE
Password conflicts for kubeadmin in CRC 1.26.0 (OCP 4.7.8)

### ISSUE THREAD

**Issue by eschabell** [code-ready/crc#2325]
### General information

  * OS: macOS 
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it (Yes)?
  * Running CRC on: Laptop (16 GB RAM) and MacMini (64 GB RAM), below is output from laptop.

## CRC version
```bash
# Put `crc version` output here
CodeReady Containers version: 1.26.0+31f06c09
OpenShift version: 4.7.8 (embedded in executable)
```
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
$ crc status --log-level debug
DEBU CodeReady Containers version: 1.26.0+31f06c09 
DEBU OpenShift version: 4.7.8 (embedded in executable) 
DEBU Running 'crc status'                         
DEBU Checking file: /Users/erics/.crc/machines/crc/.crc-exist 
DEBU Checking file: /Users/erics/.crc/machines/crc/.crc-exist 
DEBU Found binary path at /Users/erics/.crc/bin/crc-driver-hyperkit 
DEBU Launching plugin server for driver hyperkit  
DEBU Plugin server listening at address 127.0.0.1:58078 
DEBU () Calling .GetVersion                       
DEBU Using API Version 1                          
DEBU () Calling .SetConfigRaw                     
DEBU () Calling .GetMachineName                   
DEBU (crc) Calling .GetState                      
DEBU (crc) DBG | time="2021-05-10T11:08:28+02:00" level=debug msg="exe=/Users/erics/.crc/bin/crc-driver-hyperkit uid=0" 
DEBU (crc) Calling .GetBundleName                 
DEBU (crc) Calling .GetIP                         
DEBU Running SSH command: df -B1 --output=size,used,target /sysroot | tail -1 
DEBU Using ssh private keys: [/Users/erics/.crc/machines/crc/id_ecdsa /Users/erics/.crc/cache/crc_hyperkit_4.7.8/id_ecdsa_crc] 
DEBU SSH command results: err: <nil>, output: 32737570816 12364316672 /sysroot 
DEBU Running SSH command: <hidden>                
DEBU SSH command succeeded                        
DEBU Unexpected operator status for network: ManagementStateDegraded 
DEBU Making call to close driver server           
DEBU (crc) Calling .Close                         
DEBU Successfully made call to close driver server 
DEBU Making call to close connection to plugin binary 
DEBU (crc) DBG | time="2021-05-10T11:08:29+02:00" level=debug msg="Closing plugin on server side" 
CRC VM:          Running
OpenShift:       Running (v4.7.8)
Disk Usage:      12.36GB of 32.74GB (Inside the CRC VM)
Cache Usage:     13.37GB
Cache Directory: /Users/erics/.crc/cache
```

## CRC config
```bash
# Put `crc config view` output here
$ crc config view
- consent-telemetry                     : no
- cpus                                  : 6
- memory                                : 10240
- pull-secret-file                      : /Users/erics/bin/pull-secret.txt
```

## Host Operating System
```bash
# put the output of `sw_vers` in case of Mac
ProductName:	macOS
ProductVersion:	11.2.3
BuildVersion:	20D91
```

### Steps to reproduce

  1.  run crc setup
  2.  note console output with a kubeadmin password listed (in my test case): WwA7M-7Vgnt-5DX73-HiWLN   (note this changes each new install) or run the command '$ crc console --credentials' for output showing "To login as an admin, run 'oc login -u kubeadmin -p WwA7M-7Vgnt-5DX73-HiWLN https://api.crc.testing:6443'". This is the password that works.
  3.  Now check the cached kubeadmin-password file 'cat HOME/.crc/cache/crc_hyperkit_4.7.8/kubeadmin-password' which is producing "9KH6e-eFDc9-z8JZu-yx8X4" for me, which does not work.
  4.  Why are there now two admin passwords being created?

### Expected
Up to this CRC version the kubeadmin-password file listed the correct password for logging into CRC as kubeadmin. 

### Actual
Two different kubeadmin passwords exist, confusing users.

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
@eschabell we don't want the user to use ` HOME/.crc/cache/crc_hyperkit_4.7.8/kubeadmin-password` one which is created during the first install of cluster and we changed it for every fresh start, moving forward we are going to remove this file completely because it is not make any sense and confuse user. If you are using crc in the script then better to use ` ./crc console --credentials -ojson | jq .clusterConfig.adminCredentials.password` which will provide you always correct info.

**Comment by eschabell** [comment]
Thanks @praveenkumar, figured something was tightening up for a reason, but your suggestion works just fine for me.

**Comment by praveenkumar** [comment]
Closing this issue since now `kubeadmin-password` file is not part of snc repo.
