### ISSUE TITLE
[Docs] Adding information around network mode

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#2336]
Recently a change was introduced to name the networking modes `user` and `system`. We might need to describe what this means.

**Comment by gbraad** [comment]
@code-ready/crc-team please add relevant information so @robin-owen could consider what to do with this.

**Comment by cfergeau** [comment]
All of https://code-ready.github.io/crc/#dns-configuration_gsg becomes obsolete with `user`/`vsock` mode. If we stick on only documenting the default networking mode, it's at the moment complicated as we are in the middle of a transition, and the default is not consistent yet (macos installer defaults to vsock, all other crc binaries/installers default to system).
