### ISSUE TITLE
[Feature] Allow config option to assign the kubeadmin/developer passwords on startup

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#2346]
Due to security concerns (see #1391) we had to implement the option to assign a random password, however this is not ideal when it comes to a mental model. While the `start` command now summarized the password(s) used (see #1240) it still be suggested to allow a configuration option to set a password the user 'knows'(wants).

**Comment by cfergeau** [comment]
Could kube contexts be a way of addressing this, at least for the 'cmdline automation' use case?

**Comment by praveenkumar** [comment]
> Could kube contexts be a way of addressing this, at least for the 'cmdline automation' use case?

@cfergeau kube contexts have token which expire in 24 hours, if that was not the case then it would be the best way to deal it.

**Comment by cfergeau** [comment]
> kube contexts have token which expire in 24 hours

I keep forgetting that :relaxed: , thanks for the reminder!
