### ISSUE TITLE
Update background color of the MSI installer images 

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#2368]
![](https://github.com/code-ready/crc/blob/3d6bc39dec495000c8acce5246ee4c48e34344a3/packaging/windows/Resources/background.png?raw=true)

![](https://github.com/code-ready/crc/blob/3d6bc39dec495000c8acce5246ee4c48e34344a3/packaging/windows/Resources/banner.png?raw=true)

**Comment by gbraad** [comment]
![background](https://user-images.githubusercontent.com/1894/119308493-b48ea000-bc9f-11eb-8635-523f4d7c73c8.png)
![banner](https://user-images.githubusercontent.com/1894/119308500-b6586380-bc9f-11eb-9363-f9d76adec327.png)

**Comment by gbraad** [comment]
the PR includes an `xcf` file with a layer to allow the logo to be moved and background to be changed if needed

**Comment by anjannath** [comment]
Fixed in #2369
