### ISSUE TITLE
[BUG] Error upgrading CRC with installer

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/crc#2370]
### General information

OS Windows

## CRC version
```bash
Pre release 1.27.0
```

### Steps to reproduce

  1.  Install CRC previous version from installer (Ex. `1.26.0`)
  2.  Remove previous binary manually (remove `C:\Program Files\CodeReady Containers`)
  3.  Install CRC 1.27.0 from installer

### Expected

Detected previous version due to registry record, delete record and resources if available.

### Actual

Detect previous version installed so only remove option offered... Then the remove ends up on an error and there is no possible workaround to pass this step. 

![1 27 0_installer_remove_option](https://user-images.githubusercontent.com/1957899/119314703-5351d700-bc75-11eb-8a13-5b839e27f2d8.png)

![1 27 0_remove_error](https://user-images.githubusercontent.com/1957899/119314716-577df480-bc75-11eb-8086-15ef0ee222a8.png)

**Comment by anjannath** [comment]
Reopening, more to be done for this issue

**Comment by anjannath** [comment]
tested with upgrading from 1.26.0 to 1.27.0 which handled properly, files are replaced without any user interaction, if the tray is running user is asked to stop the tray process and restart the installation
