### ISSUE TITLE
[BUG] Tray unhandle exception on long run

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/crc#2373]
### General information

OS Windows

## CRC version
```bash
CodeReady Containers version: 1.27.0+3d6bc39d
OpenShift version: 4.7.11 (not embedded in executable)
```

### Steps to reproduce

  1.  Install CRC from installer
  2.  Start the cluster from the tray
  3.  Delete the cluster from the tray
  4. Keep crc and tray installed without interactions for a long time

### Expected

Nothing to happen, CRC can be handle at any time from the tray.

### Actual

Lots of popus showing communication errors appear and tray application shows an error to  unhandle exception. The only option is `Quit` , otherwise connection popups keep appearing.

![1 27 0_win_long_run](https://user-images.githubusercontent.com/1957899/119485052-eb73bd00-bd56-11eb-858b-415437a5212b.png)

**Comment by gbraad** [comment]
This code will see changes when the HTTP support is added. Will certainly address this.
