### ISSUE TITLE
[E2E] Fix UX experience with MacOS tray

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/crc#2374]
On MacOS platform, with the new CRC version `1.27.0`. When starting the cluster from the tray without previous setting of the pull secret file, the tray is asking for the pull secret content instead of the pull secret file location (as it was on previous versions). 

This change breaks the previous UX experience, so this needs to be changed on the e2e UX Feature to accommodate the current UX flow.

**Comment by guillaumerose** [comment]
Sorry, I totally forgot this.. :(

**Comment by adrianriobo** [comment]
No problem fixed!
