### ISSUE TITLE
[BUG] Kubernetes context from previous installations

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/crc#2375]
### General information

Tested on MacOS, but affects all platforms. This is more obvious on MacOS as now the contexts are shown directly from the tray

## CRC version
```bash
CodeReady Containers version: 1.27.0+3d6bc39d
OpenShift version: 4.7.11 (not embedded in executable)
```

### Steps to reproduce

  1.  Install CRC from installer
  2.  `crc setup`
  3.  start CRC from tray
  4.  check Kubernetes Context list from tray
 or
  5. logging the cluster as kubeadmin
  6. get contexts: `oc config get-contexts`

### Expected

The list will show the current available contexts

### Actual

The list shows context from ~/.kube/config so it includes contexts from previous executions which are not available on fresh new CRC installations. 

![1 27 0_tray_macos_context](https://user-images.githubusercontent.com/1957899/119562114-44b70d00-bda6-11eb-9cec-77238b0a2595.png)

From here switch to this context and execute some commands:

```bash
oc project
error: you do not have rights to view project "testproj" specified in your config or the project doesn't exist
```

```bash
oc create deployment httpd-example --image=quay.io/bitnami/nginx --port=8080
error: failed to create deployment: namespaces "testproj" not found
```

**Comment by praveenkumar** [comment]
@adrianriobo This is not issue with context but more of a issue with openshift side where it create context for every project you create and make it as active one but when you delete the project it doesn't remove the context so that's why this error.

**Comment by adrianriobo** [comment]
Well, not sure if: 

`start  a CRC cluster` 
`create a project` 
`crc delete`
`crc cleanup`

...do I expected the contexts for that cluster remain?, the tray will show only contexts for CRC right? but should it be for the currernt CRC cluster?.

**Comment by guillaumerose** [comment]
`crc delete` could also cleanup Kubernetes context. That's a good idea I think.

**Comment by adrianriobo** [comment]
We claim is an "ephemeral" so it probably would make sense delete those remaining too.

**Comment by guillaumerose** [comment]
Contexts are now deleted after crc delete. Feel free to reopen if you have a new idea!
