### ISSUE TITLE
RHEL 8 install issue

### ISSUE THREAD

**Issue by cheers4asc** [code-ready/crc#238]
Trying this on RHEL 8 with the latest 0.87 release, getting stuck at the time of extraction. 
is this issue with the bundle or something is wrong with my setup . 
Debug level doesn't yield anything apart from the extraction issue. 
manually I can extract that bundle.

[ crc]# ./crc --log-level debug start -b ./crc-0.87.0-linux-amd64.tar.xz 
crc - Local OpenShift 4.x cluster
INFO Checking if oc binary is cached              
DEBU oc binary already cached                     
INFO Checking if Virtualization is enabled        
DEBU Checking if the vmx/svm flags are present in /proc/cpuinfo 
DEBU CPU virtualization flags are good            
INFO Checking if KVM is enabled                   
DEBU Checking if /dev/kvm exists                  
DEBU /dev/kvm was found                           
INFO Checking if Libvirt is installed             
DEBU Checking if 'virsh' is available             
DEBU 'virsh' was found in /usr/bin/virsh          
INFO Checking if user is part of libvirt group    
DEBU Checking if current user is part of the libvirt group 
DEBU Current user is already in the libvirt group 
INFO Checking if Libvirt is enabled               
DEBU Checking if libvirtd.service is enabled      
DEBU libvirtd.service is already enabled          
INFO Checking if Libvirt daemon is running        
DEBU Checking if libvirtd.service is running      
DEBU libvirtd.service is already running          
INFO Checking if crc-driver-libvirt is installed  
DEBU Checking if crc-driver-libvirt is installed  
DEBU crc-driver-libvirt is already installed in /usr/local/bin/crc-driver-libvirt 
INFO Checking if Libvirt crc network is available 
DEBU Checking if libvirt 'crc' network exists     
DEBU libvirt 'crc' network exists                 
DEBU Checking if libvirt 'crc' network definition contains crc-4gdnp-master-0 
DEBU libvirt 'crc' network definition contains crc-4gdnp-master-0 
INFO Checking if Libvirt crc network is active    
DEBU Checking if libvirt 'crc' network is active  
DEBU libvirt 'crc' network is already active      
INFO Checking if /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf exists 
DEBU Checking NetworkManager configuration        
DEBU NetworkManager configuration is good         
INFO Checking if /etc/NetworkManager/dnsmasq.d/crc.conf exists 
DEBU Checking dnsmasq configuration               
DEBU dnsmasq configuration is good                
INFO Extracting the Bundle tarball ...            
ERRO Error to get bundle Metadata Error during extraction : xz: file format not recognized 
INFO                                              
[Error during extraction : xz: file format not recognized]

**Comment by praveenkumar** [comment]
`crc-0.87.0-linux-amd64.tar.xz` this is wrong bundle, right now it is shared internally, we are trying to make it public.
