### ISSUE TITLE
[BUG] Error in driver during machine creation: unknown feature amd-sev-es

### ISSUE THREAD

**Issue by matsonkepson** [code-ready/crc#2385]
### General information

  * OS: Linux CentOS Stream release 8
  * Hypervisor: KVM / ovirt
  * Did you run `crc setup` before starting it (Yes/No)? yes
  * Running CRC on: VM

## CRC version
```bash
# Put `crc version` output here
[aes@ose4trial ~]$ crc version
CodeReady Containers version: 1.27.0+3d6bc39d
OpenShift version: 4.7.11 (embedded in executable)

```
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
[aes@ose4trial ~]$ crc status --log-level debug
DEBU CodeReady Containers version: 1.27.0+3d6bc39d 
DEBU OpenShift version: 4.7.11 (embedded in executable) 
DEBU Running 'crc status'                         
DEBU Checking file: /home/aes/.crc/machines/crc/.crc-exist 
Machine does not exist. Use 'crc start' to create it

```

## CRC config
```bash
# Put `crc config view` output here
[aes@ose4trial ~]$ crc config view
- consent-telemetry                     : yes
- pull-secret-file                      : /opt/pull-secret-redhat.io

```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
[aes@ose4trial ~]$ cat /etc/os-release
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

```

### Steps to reproduce

  1. plain system
  2. crc setup
  3. crc start
  4. 

### Expected
 running

### Actual
not running with error
```
Error creating machine: Error in driver during machine creation: virError(Code=1, Domain=10, Message='internal error: unknown feature amd-sev-es')
```
### Logs

Gist log with debug below

https://gist.github.com/matsonkepson/e00da7e1ad57724bf42575a3b6255a54

**Comment by wpernath** [comment]
This seems to be an qemu issue, which is described here: 
https://bugzilla.redhat.com/show_bug.cgi?id=1961562

The workaround of the Bugzilla has solved the startup issue of CRC for me on CentOS 8:

<bugzilla comment #16>
> Is there any known workaround? Right now this completely blocks our package
> updates in RHEL 8.5 and our CI. Thanks!

Yes, there is simple workaround:

  mkdir -p /etc/qemu/firmware
  touch /etc/qemu/firmware/50-edk2-ovmf-cc.json

This will create an empty file which can disable the new firmware, more details here [1], look for firmware description.

[1] <https://libvirt.org/formatdomain.html#operating-system-booting>

</bugzilla comment #16>

**Comment by matsonkepson** [comment]
thanks @wpernath for fast response.
This workaround works for me

**Comment by praveenkumar** [comment]
Since it is the bug from qemu side, closing it from CRC side.
