### ISSUE TITLE
Use something else than Make to build on Windows

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#2396]
Make is not really made to run on Windows. 
Many reasons:
* It is not clear where the developer should build: in WSL? Powershell? Cygwin?
* There are path errors
* Slash and backslash errors all the time
* Env. variables cannot be used before a command, etc.

I understand it is not easy to maintain 2 scripts but the current solution doesn't work well and is inefficient. 
I would prefer to run a single .ps1 script that does everything (install dependencies and build everything).

```
PS C:\Users\guillaume\gomod\crc> make
go install -ldflags="-X github.com/code-ready/crc/pkg/crc/version.crcVersion=1.27.0 -X github.com/code-ready/crc/pkg/crc/version.bundleVersion=4.7.11 -X github.com/code-ready/crc/pkg/crc/version.commitSha=ac609dfe -extldflags='-static' "  ./cmd/crc
PS C:\Users\guillaume\gomod\crc> make cross
GOARCH=amd64 GOOS=darwin go build -ldflags="-X github.com/code-ready/crc/pkg/crc/version.crcVersion=1.27.0 -X github.com/code-ready/crc/pkg/crc/version.bundleVersion=4.7.11 -X github.com/code-ready/crc/pkg/crc/version.commitSha=ac609dfe -extldflags='-static' " -o out/macos-amd64/crc  ./cmd/crc
'GOARCH' is not recognized as an internal or external command,
```

**Comment by gbraad** [comment]
We never supported building on Windows directly due to these issues with make, ssh inconsistencies etc. Recommended is to use WSL or Linux with `make cross`.

**Comment by guillaumerose** [comment]
For the MSI, we need to build on Windows so this needs to change.

**Comment by gbraad** [comment]
> For the MSI, we need to build on Windows so this needs to change.

As I understood it was investigated to use generally available tools to build the MSI.

https://github.com/code-ready/crc/wiki/Building-the-msi-package

This includes wix-toolset

**Comment by gbraad** [comment]
The content of the `make.ps1` would be:

https://github.com/code-ready/crc/blob/66e85bb1a1be7bfbbf4ef4ac46eee9eb5c0dd1a0/appveyor.yml#L7-L12

**Comment by anjannath** [comment]
`make cross` works fine in powershell here:

```posh
PS C:\Users\anath\redhat\crc> make cross
GOARCH=amd64 GOOS=darwin go build -ldflags="-X github.com/code-ready/crc/pkg/crc/version.crcVersion=1.27.0 -X github.com/code-ready/crc/pkg/crc/version.bundleVersion=4.7.11 -X github.com/code-ready/crc/pkg/crc/version.commitSha=40f235bb -extldflags='-static' " -o out/macos-amd64/crc  ./cmd/crc
GOOS=linux GOARCH=amd64 go build -ldflags="-X github.com/code-ready/crc/pkg/crc/version.crcVersion=1.27.0 -X github.com/code-ready/crc/pkg/crc/version.bundleVersion=4.7.11 -X github.com/code-ready/crc/pkg/crc/version.commitSha=40f235bb -extldflags='-static' " -o out/linux-amd64/crc  ./cmd/crc
GOARCH=amd64 GOOS=windows go build -ldflags="-X github.com/code-ready/crc/pkg/crc/version.crcVersion=1.27.0 -X github.com/code-ready/crc/pkg/crc/version.bundleVersion=4.7.11 -X github.com/code-ready/crc/pkg/crc/version.commitSha=40f235bb -extldflags='-static' " -o out/windows-amd64/crc.exe  ./cmd/crc
```

**Comment by gbraad** [comment]
same here, and also on AppVeyor, so this sounds like configuration issues.

**Comment by gbraad** [comment]
>  also there are issues with the backslashes like for `make clean`

Instead of changing the tool, these can be fixed. The additional overhead and maintenance that a new build script introduces does not sounds appealing.

**Comment by guillaumerose** [comment]
Let's close this for the moment. I found a way to get everything working. I would prefer to only use PowerShell and not have to mess with Cygwin, etc.

**Comment by ewheelerinc** [comment]
Maybe CMake is the way to go instead of Make. VS2019 has support for cmake according to this article, and it would facilitate building in Linux as well (https://github.com/wixtoolset/issues/issues/4381):

https://docs.microsoft.com/en-us/cpp/linux/create-a-new-linux-project?view=msvc-160
