### ISSUE TITLE
crc on windows 10 enterprise - failed to expose port

### ISSUE THREAD

**Issue by jh-acc** [code-ready/crc#2405]
As a workaround to crc switching off internet on windows 10 enterprise, I was advised to try the userland network 
stack setting.

https://github.com/code-ready/crc/wiki/VPN-support--with-an--userland-network-stack

I upgraded to crc  1.27 
Hyper-v and crc are enabled in the firewall
curl 127.0.0.1:80 shows nothing is running... 

The Hyperv vm, CPX-GMAAZQ82HAF is listening on port 80, 8000
```
C:\code-ready-containers\crc-windows-1.27.0-amd64>netstat -ao | find ":80"
  TCP    0.0.0.0:80             CPX-GMAAZQ82HAF:0      LISTENING       4
  TCP    0.0.0.0:8000           CPX-GMAAZQ82HAF:0      LISTENING       4
  TCP    [::]:80                CPX-GMAAZQ82HAF:0      LISTENING       4
  TCP    [::]:8000              CPX-GMAAZQ82HAF:0      LISTENING       4
```

When I use crc start, I get this error message at the end of the start:
```
INFO Checking if vsock is correctly configured
INFO Starting CodeReady Containers VM for OpenShift 4.7.11...
failed to expose port :80 -> 192.168.127.2:80: listen tcp :80: bind: An attempt was made to access a 
socket in a way forbidden by its access permissions.
```

Is there another setting which I need to change to get this running?

**Comment by guillaumerose** [comment]
The port 80 is not available on your computer, perhaps it is denied. Therefore, crc cannot start. 
Do you have a special setup? Something enforced by an administrator?

**Comment by macagr** [comment]
I have the same issue. I think this may be a configuration enforced by an administrator. At least, port 80 is part of the excluded port range (got it by running `netsh interface ipv4 show excludedportrange protoco=tcp`). So my question would be: is it possible to configure a port different than 80? if it's not I'll just try to solve it from the admin angle. Many thanks!

**Comment by jh-acc** [comment]
Thanks for the comments. This is a corporate laptop with restrictions. I checked with the command  'netsh interface ipv4 show excludedportrange protoco=tcp'.
