### ISSUE TITLE
oc login on Windows 10, loader.go:223,  Config not found

### ISSUE THREAD

**Issue by swjtustudent** [code-ready/crc#2410]
**General Information:**
OS: Windows 10 x86_64
Hyper-v: 10.0.19041.1
CodeReady Containers version: 1.24.0+5f06e84b
OpenShift version: 4.7.2 (embedded in executable)

**Step to Reproduce:**
1. crc setup
2. crc start -p .\pull-secret --log-level debug
3. oc login -u kubeadmin -p tBP79-Nt3f9-ocJzI-va8Bb https://api.crc.testing:6443

**Expected result**:
Logon success

**Actual result**:
W0609 10:50:10.676142   11868 loader.go:223] Config not found: C:\Users\lenovo\.crc\cache\crc_hyperv_4.7.8\kubeconfig
error: dial tcp: lookup api.crc.testing: no such host - verify you have provided the correct host and port and that the server is currently running.

current installed bundle is crc_hyperv_4.7.2, not crc_hyperv_4.7.8

$ crc status:
CRC VM:          Running
OpenShift:       Unreachable (v4.7.2)
Disk Usage:      11.24GB of 32.74GB (Inside the CRC VM)
Cache Usage:     14.62GB
Cache Directory: C:\Users\lenovo\.crc\cache

**start log**:
[crc_start.txt](https://github.com/code-ready/crc/files/6620857/crc_start.txt)

**crc.log**:
[crc.log](https://github.com/code-ready/crc/files/6620862/crc.log)

**Comment by swjtustudent** [comment]
This issue is because KUBECONFIG not set correctly. closed.

**Comment by gbraad** [comment]
Thanks for the quick feedback
