### ISSUE TITLE
Sunsetting phat-binary for Windows

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#2427]
In reference to #2181 we will do the same for Windows.

  * [x] Upgrade should be posible
  * [x] Tray install and autostart (the deamon process is started by the tray so we only need to setup the tray to autostart)
  * [ ] #2469
    * [x] Clearer message about running `crc setup` after the installation (https://github.com/code-ready/crc/issues/2429)
    * [ ] Show clear failed message when installation fails (https://github.com/code-ready/crc/issues/2421)

**Comment by gbraad** [comment]
* [ ] Upgrade should be posible
  * [ ] Daemon install and autotstart
  * [ ] ...

**Comment by cfergeau** [comment]
The MSI installer is now the default, we no longer ship publicly the binary, but some of the items listed in the initial comment are still being worked on.

**Comment by anjannath** [comment]
With the new electron tray, we'll launch the setup from the tray. The remaining items need to be implemented on the msi installer anymore
