### ISSUE TITLE
Confusing error message from the Windows tray

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#2428]
### General information

Tried nested Windows (up to date French business edition 21h1) on a RHEL8.4 host. Nested virt setup was only partial though, forgot to set `cpu=host-passthrough` in my libvirt config. Preflight checks did not detect the partial hyperv configuration, but `crc start` failed with:
```
DEBU stderr: Hyper-V\Start-VM : Échec du démarrage de 'crc'.
Impossible de démarrer l'ordinateur virtuel « crc », car l'un des composants Hyper-V n'est pas en cours d'exécution.
Échec du démarrage de « crc ». (ID d'ordinateur virtuel 4E62C6E3-5787-4DDF-AEF7-35C6300F8B1B)
Le service de gestion d'ordinateurs virtuels n'a pas pu démarrer l'ordinateur virtuel «crc», car l'un des composants
Hyper-V n'est pas en cours d'exécution (ID d'ordinateur virtuel 4E62C6E3-5787-4DDF-AEF7-35C6300F8B1B).
Au caractère Ligne:1 : 43
+ $ProgressPreference = 'SilentlyContinue'; Hyper-V\Start-VM crc
+                                           ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OperationFailed,Microsoft.HyperV.PowerShell.Commands.StartVM
Error starting machine: Error in driver during machine start: exit status 1
```

Which roughly says "One of hyper-v components is not running".

However, when trying to start crc from the tray, this error box kept popping up:
![error](https://user-images.githubusercontent.com/526310/121925379-24db8f00-cd3d-11eb-8ebb-bdd1c0e909d5.png)

(not 100% sure start is failing because of the same error in both cases, but that's likely).

This bug is about 2 things:
- the hyperv preflight which should be failing
- the tray which should report a better error

**Comment by guillaumerose** [comment]
Fix attempt in https://github.com/code-ready/tray-windows/pull/87/commits/d256c60ab986f7ad0da47373f767e1c7d0427930
