### ISSUE TITLE
[BUG] Multiple issues on long run on windows (installed from tray)

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/crc#2434]
### General information

On windows run crc for a long time, there are several communication issues, some of them end up requiring kill the tray.

## CRC version
```bash
CodeReady Containers version: 1.28.0+08de64bd
OpenShift version: 4.7.13 (not embedded in executable)
```
### Steps to reproduce

  1. Install crc from msi 
  2. start the cluster
  3. keep the cluster running for a long run

### Expected

Nothing to happen

### Actual

Multiple communication errors, some of  them require killing the tray

![1 28 0-windows-longrun-communication](https://user-images.githubusercontent.com/1957899/122011280-3748dd80-cdbc-11eb-89d9-9b968efbc860.png)

![1 28 0-windows-longrun](https://user-images.githubusercontent.com/1957899/122011313-3f088200-cdbc-11eb-94f4-577c3ed38ffa.png)

**Comment by cfergeau** [comment]
Useful information is most likely hidden under that "Details" button :) This could be similar to https://github.com/code-ready/tray-windows/issues/82

**Comment by guillaumerose** [comment]
The no connection pop up is fixed in https://github.com/code-ready/tray-windows/pull/86.
The null exception is fixed in https://github.com/code-ready/tray-windows/pull/87

**Comment by anjannath** [comment]
Running windows tray constantly for last few releases, haven't faced this issue anymore, keeping it closed.
