### ISSUE TITLE
[Epic] Utilize crc.dev for discoverability of the (older) releases

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#2438]
Make sure we link releases to developer.redhat.com so they can be tracked, as the CDN does not track direct links (needs to be 302).

**Comment by guillaumerose** [comment]
Right now, older releases can be discovered easily on Github releases page. https://github.com/code-ready/crc/releases

**Comment by gbraad** [comment]
> Right now, older releases can be discovered easily on Github releases page. https://github.com/code-ready/crc/releases

Unfortunately these releases aren't the same, as they do not include the needed OpenShift bundle.

**Comment by gbraad** [comment]
Not seeing this as an Epic, however we have 'finished' the use of https://crc.dev and need to follow-up with possible content.

**Comment by cfergeau** [comment]
regarding crc.dev, we now have
* [download.crc.dev] pointing to the downloads on developers.redhat.com
* docs.crc.dev pointing to crc's docs (code-ready.github.io/crc)
* crc.dev pointing to the landing page, but the content is in https://github.com/code-ready/code-ready.github.io/ so this can be easily changed

**Comment by cfergeau** [comment]
Is this so important now? It seems mirror.openshift.com has been migrated to new infra, so it might stay much longer than initially expected?
