### ISSUE TITLE
crc cleanup taking care of isolated daemon process

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/crc#2441]
### General information

 Tested on MacOS platforms. 

## CRC version
```bash
CodeReady Containers version: 1.28.0+08de64bd
OpenShift version: 4.7.13 (not embedded in executable)
```

### Steps to reproduce

  1.  Install CRC
  2.  `config set autostart-tray false`
  3.  start daemon as background process: `crc daemon &` 
  4.  `crc cleanup` 

### Observations

Step 3 background execution is not the cause, as foreground will act the same, but for the edge case background will give more chances user just forget about it.

Then after `crc cleanup` what are the expectations? No crc resouces left?. There is no way to accomplish this beyond checking for the process and force killing.

`crc stop` not possible as no machine was created
`crc cleanup` does not take care of the process

Linked to upgrade process, there is **no check for crc daemon process when upgrading**...this means if the daemon is dangling from previous version no warning and upgrade will be done fine. (When tray is running it complains about it). 

Then if you repeat the steps you will end up having a message saying daemon is already running (but from previous version)...and you may not aware of that...this could end up on unexpected behavior if proceed to `crc start`

**Comment by cfergeau** [comment]
Seems related to https://github.com/code-ready/crc/issues/2313 ?
