### ISSUE TITLE
[BUG] `crc start` exits with "Failed to update cluster ID"

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#2444]
### General information

  * OS: Linux
  * Hypervisor: KVM

## CRC version

master with a 4.7.11 bundle 

### Steps to reproduce

  1. `crc start -b ~/Downloads/crc_libvirt_4.7.11.crcbundle --log-level debug -p ~/pull-secret.txt`

It happened only once for me. 

### Expected

A Working cluster

### Actual

A half working cluster

### Logs

```
$ crc start -b ~/Downloads/crc_libvirt_4.7.11.crcbundle --log-level debug -p ~/pull-secret.txt
...
DEBU Running SSH command: <hidden>                
DEBU SSH command succeeded                        
DEBU Running SSH command: <hidden>                
DEBU SSH command succeeded                        
DEBU Waiting for availability of resource type 'clusterversion' 
DEBU retry loop: attempt 0                        
DEBU Running SSH command: timeout 5s oc get clusterversion --context admin --cluster crc --kubeconfig /opt/kubeconfig 
DEBU SSH command results: err: <nil>, output: NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.7.11    True        False         33d     Cluster version is 4.7.11 
DEBU NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.7.11    True        False         33d     Cluster version is 4.7.11 
DEBU Running SSH command: timeout 30s oc get clusterversion version -o jsonpath="{['spec']['clusterID']}" --context admin --cluster crc --kubeconfig /opt/kubeconfig 
DEBU SSH command results: err: Process exited with status 124, output:  
DEBU Making call to close driver server           
DEBU (crc) Calling .Close                         
DEBU Successfully made call to close driver server 
DEBU Making call to close connection to plugin binary 
DEBU (crc) DBG | time="2021-06-17T10:38:15+02:00" level=debug msg="Closing plugin on server side" 
Failed to update cluster ID: ssh command error:
command : timeout 30s oc get clusterversion version -o jsonpath="{['spec']['clusterID']}" --context admin --cluster crc --kubeconfig /opt/kubeconfig
err     : Process exited with status 124\n
``` 

I don't have a good idea to fix it. If someone has an idea!

**Comment by praveenkumar** [comment]
Just a guess since in the code we only do retry when getting the specific resource, in this case it is clusterversion and after that we just execute the command. It might be possible that during the resource list and actually updating the resource, reconcile happen and apiserver just disappear for time being. 

Also right now we are just returning the error but we should capture `stderr` and log it or make it part of error to make sure this is the case or something else happen. Will look more into it.

**Comment by guillaumerose** [comment]
Yes maybe we should do like snc and have a retry loop for everything.

**Comment by praveenkumar** [comment]
This is no longer reproducible and stderr is now part of error message.
