### ISSUE TITLE
[BUG] CRC page on developers.redhat.com is a mess

### ISSUE THREAD

**Issue by jeffmaury** [code-ready/crc#2450]
### General information

 if you go to the CRC page on developers.redhat.com, you will have:

- the Install OpenShift on your laptop button redirects to 404 
- the Release Notes, Installation and Troubleshooting links link to 1.19 documentation

**Comment by cfergeau** [comment]
https://developers.redhat.com/products/codeready-containers/overview

**Comment by anjannath** [comment]
When clicking on "Install OpenShift on you laptop"(https://developers.redhat.com/download-manager/link/3868678) i am getting correctly redirected to https://cloud.redhat.com/openshift/create/local

**Comment by gbraad** [comment]
> Install OpenShift on your laptop button redirects to 404

Which link do you see it goes to?

**Comment by jeffmaury** [comment]
Hard to tell as it seems to be random so can't reproduce

**Comment by jeffmaury** [comment]
![image](https://user-images.githubusercontent.com/695993/122572656-3b8c2980-d04e-11eb-8ad0-dcb611f18fcb.png)

**Comment by gbraad** [comment]
> Hard to tell as it seems to be random so can't reproduce

We'll have to look into this... but since you mention it is random/inconsistent it might very well be related to the new setup

**Comment by jeffmaury** [comment]
Seems to be caused my some weird cookie as it's working from a private window
