### ISSUE TITLE
[BUG] CRC DNS Localhost Conflicts

### ISSUE THREAD

**Issue by EHSchmitt4395** [code-ready/crc#2453]
### General information

  * OS: macOS Catalina 10.15
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it (Yes/No)?   Yes
  * Running CRC on: Laptop / Baremetal-Server / VM.    Laptop 

## CRC version
CodeReady Containers version: 1.24.0+5f06e84b
OpenShift version: 4.7.2 (embedded in executable)
  
## CRC status
DEBU CodeReady Containers version: 1.24.0+5f06e84b
DEBU OpenShift version: 4.7.2 (embedded in executable)
DEBU Running 'crc status'
DEBU Checking file: /var/root/.crc/machines/crc/.crc-exist
Machine does not exist. Use 'crc start' to create it
sh-3.2# exit
exit
es893323@C02FC223MD6T ~ % sh-3.2# crc status --log-level debug
DEBU CodeReady Containers version: 1.24.0+5f06e84b
DEBU OpenShift version: 4.7.2 (embedded in executable)
DEBU Running 'crc status'
DEBU Checking file: /var/root/.crc/machines/crc/.crc-exist
Machine does not exist. Use 'crc start' to create i
es893323@C02FC223MD6T ~ % crc status --log-level debug
DEBU CodeReady Containers version: 1.24.0+5f06e84b
DEBU OpenShift version: 4.7.2 (embedded in executable)
DEBU Running 'crc status'
DEBU Checking file: /Users/es893323/.crc/machines/crc/.crc-exist
DEBU Checking file: /Users/es893323/.crc/machines/crc/.crc-exist
DEBU Found binary path at /Users/es893323/.crc/bin/crc-driver-hyperkit
DEBU Launching plugin server for driver hyperkit
DEBU Plugin server listening at address 127.0.0.1:51365
DEBU () Calling .GetVersion
DEBU Using API Version 1
DEBU () Calling .SetConfigRaw
DEBU () Calling .GetMachineName
DEBU (crc) Calling .GetState
DEBU (crc) DBG | time="2021-06-18T15:27:08-07:00" level=debug msg="hyperkit pid from json: 1745"
DEBU (crc) Calling .GetBundleName
DEBU Running SSH command: df -B1 --output=size,used,target /sysroot | tail -1
DEBU Using ssh private keys: [/Users/es893323/.crc/machines/crc/id_ecdsa /Users/es893323/.crc/cache/crc_hyperkit_4.7.2/id_ecdsa_crc]
DEBU SSH command results: err: <nil>, output: 32737570816 12594257920 /sysroot
DEBU Running SSH command: <hidden>
DEBU SSH command succeeded
DEBU Unexpected operator status for network: ManagementStateDegraded
DEBU Making call to close driver server
DEBU (crc) Calling .Close
DEBU Successfully made call to close driver server
DEBU Making call to close connection to plugin binary
DEBU (crc) DBG | time="2021-06-18T15:27:08-07:00" level=debug msg="Closing plugin on server side"
CRC VM:          Running
OpenShift:       Running (v4.7.2)
Disk Usage:      12.59GB of 32.74GB (Inside the CRC VM)
Cache Usage:     13.36GB
Cache Directory: /Users/es893323/.crc/cache

## CRC config
- consent-telemetry                     : no
- cpus                                  : 12
- memory                                : 16384
- network-mode                          : vsock

## Host Operating System
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H1217

### Steps to reproduce

  1.  crc setup
  2.  crc start 
  3.  gcloud auth login

### Expected
Gcloud and local terminal should be able to authenticate with google api & cloud. 

### Actual
Gcloud auth is impossible because CRC shares and takes over Localhost. 
```
ERROR: There was a problem with web authentication. Try running again with --no-launch-browser.
ERROR: (gcloud.auth.login) Could not reach the login server. A potential cause of this could be because you are behind a proxy. Please set the environment variables HTTPS_PROXY and HTTP_PROXY to the address of the proxy in the format "protocol://address:port" (without quotes) and try again.
Example: HTTPS_PROXY=https://192.168.0.1:8080
```
Note this will fail with no launch browser because the issue persists with google reply to localhost 

After crc cleanup, auth works again.  I use gcloud in conjunction crc to test deployments that utilize GCP KMS encryptions.

### Logs

https://github.com/EHSchmitt4395/crclog/blob/main/log.yaml

**Comment by gbraad** [comment]
please update to a more recent version to confirm this with the current network stack.
using our user networking code we create a forward from localhost to the VM, and we do not remove those when the VM isn't running, but it is not that we 'claim' all of localhost, just the API port.

**Comment by guillaumerose** [comment]
When I use `gcloud auth login` on my macOS, it opens the port 8085. 
This port is not used by `crc`, so I guess you have an application already using it.

**Comment by EHSchmitt4395** [comment]
my apologies, latest version does seem to have a fixed network setup - cheers!

**Comment by cfergeau** [comment]
Thanks for the follow-up, closing this then.
