### ISSUE TITLE
[BUG] MacOS lack of system tray running shouldn't prevent CRC from running

### ISSUE THREAD

**Issue by sspeiche** [code-ready/crc#2454]
### General information

  * OS: macOS
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Bare metal Laptop! ;-)
 
## CRC version
```bash
CodeReady Containers version: 1.28.0+08de64bd
OpenShift version: 4.7.13 (not embedded in executable)
```

### Steps to reproduce

  1. Get everything going as usual
  2. Exit/quit the system tray
  3. Try to start

### Expected

I expected a number of things to happen:
1. CRC just worked, doesn't require me to use system tray
2. CRC prompts to start the tray for me
```bash
$crc start
CRC system tray is not running, start it now? (Yes)
```

### Actual

```bash
Is '/Applications/CodeReady Containers.app' running? Cannot reach daemon API: Get "http://unix/api/version": dial unix /Users/sspeiche/.crc/crc-http.sock: connect: connection refused
```

**Comment by gbraad** [comment]
We made the tray an essential part of the deployments on Windows and macOS, as they provide a better interaction on these platforms.

**Comment by gbraad** [comment]
Confrmed, the networking stack is controlled by the daemon and this is explicitly started by the tray; https://github.com/code-ready/tray-macos/blob/007e3c872462cc5dded60b638d2bef7a84b6704d/CodeReady%20Containers/AppDelegate.swift#L105-L130and therefore essential for the operation and interaction with the VM.

**Comment by anjannath** [comment]
This will be handled in https://github.com/code-ready/crc/issues/2557
