### ISSUE TITLE
Force shutdown VM during the bundle generation

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#2468]
Recently with 4.8 testing one of the blocking issue we found is vm taking longer time to shutdown gracefully (~7-8 mins) and a bug is filled against it https://bugzilla.redhat.com/show_bug.cgi?id=1965992. As part of bundle creation we first stop the cluster and that run `client.Stop` functionality which waits for 2 min before error out and currently if there is any error we just error out from the bundle generate command.  Should we prompt user for forcefully shutdown after 2min like we do for `crc stop` command or we just ourself perform the force shutdown? Also what if disk corruption happen due to forcefully shutdown of VM?

This is follow up issue of the comment https://github.com/code-ready/crc/pull/2324#discussion_r655196827

**Comment by cfergeau** [comment]
I would follow exactly the same behaviour as `stop`, including having a `-f` flag. Or are there important reasons forcing us to differ from `stop` behaviour in the case of bundle generation?

**Comment by praveenkumar** [comment]
> I would follow exactly the same behaviour as `stop`, including having a `-f` flag. Or are there important reasons forcing us to differ from `stop` behaviour in the case of bundle generation?

How about just having `-f` option and if user don't provide it then we error out for stop otherwise forcefully shutdown?

**Comment by cfergeau** [comment]
Could work... If stop is too slow, behaviour will not be great anyway, as `crc generate-bundle` will fail, but if make sure the VM is stopped, and re-run immediatly `crc generate-bundle`, the bundle generation will most likely also fail because the first steps require the VM to be up :(

**Comment by cfergeau** [comment]
A `--forceStop` option was added in 02a30bf8bbf239703d
