### ISSUE TITLE
Remove crc setup step when there is an installer

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#2469]
With 1.28.0, with the .pkg and the .msi, the user still need to run `crc setup`. 
We would like to remove this step and to have crc ready to start right after the installer exits.

For macOS, the only relevant steps remaining are the bundle extraction and installation of the tray application (setting it to auto start).

For Windows, setup still does:
  * install and configure Hyper-V,
  * install the admin-helper daemon,
  * extract the bundle.

Installers currently install for all users. Bundles should be shared by all users as they are static. 
Tracking issue: https://github.com/code-ready/crc/issues/2251

The remaining issue is, as usual, in Windows. 2 ways to explore:
  * [ ] Move most of the setup in the MSI

It would imply CustomAction in the MSI for enabling Hyper-V, etc. The error feedback is not easy to handle. It is apparently possible to compile Golang code as a DLL and run it as a library in the installer.

  * [ ] Assist the user by running the equivalent of crc setup in a tray welcome screen.

The tray would first run `crc setup --check-only` and in case of error, it would run `crc setup` with the correct messaging around.

**Comment by gbraad** [comment]
Related to #2427

**Comment by praveenkumar** [comment]
Have we experimented with adding `crc setup` as part of post script for MSI and PKG side? This will make sure the `crc setup` is run same way on the CLI and on the installer side. Since we are already getting request to use crc without tray so if we take different path on installer side and on cli side then it will increase our testing matrix.

**Comment by gbraad** [comment]
@praveenkumar there is however an issue with running these as post-install tasks in the MSI, such as proper error messaging when things fail; this is the issue with a custom-action. We want to prevent a lot of custom code at this stage that is specific (and perhaps in a different language) for just the installer.

**Comment by anjannath** [comment]
From the msi, only two things remain to not depend on `crc setup` command:
1. Creation of the registry key for gvisor-tap-vsock ()
2. The bundle extraction (This'll be handled in #2251)

**Comment by cfergeau** [comment]
Still some work to be done.
