### ISSUE TITLE
Upgrade go to 1.15

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#2473]
OpenShift is now using go1.15 everywhere. crc should also move to this version.

All repos needs to be changed:
- [x] crc
- [x] hyperkit driver
- [x] libvirt driver
- [ ] admin-helper
- [ ] routes-controller
- [ ] gvisor-tap-vsock

**Comment by praveenkumar** [comment]
Shouldn't we also include the `admin-helper` to the list even we create a container image out of it?

**Comment by praveenkumar** [comment]
@guillaumerose I think also `route-controller` should be part of this list and then we can use this issue as template in the future go upgrade.
