### ISSUE TITLE
Remove the system network mode on macOS

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#2475]
The system network mode is only useful for the fat binary.

When the system mode is removed we can:
* run hyperkit as normal user
* remove the driver binary and compile it directly in crc binary
* remove crc setup because nothing needs to be changed anymore (last thing was patch /etc/resolver but it is only for system network mode)

_Originally posted by @guillaumerose in https://github.com/code-ready/crc/issues/2399#issuecomment-856519443_

**Comment by gbraad** [comment]
This issue needs follow-ups to completely remove the functionality.

**Comment by praveenkumar** [comment]
Reopening this since it should track the follow up.

**Comment by gbraad** [comment]
@guillaumerose can you create a new issue for the follow-ups, and then close this?

**Comment by gokhansengun** [comment]
Removing system network mode limits crc's use case for me. 

In one of my use cases, I have a service inside the cluster that is both accessed from the cluster and the host, therefore the service exposed by a route. With user network mode, it is not possible to access the service inside the cluster as the route's fqdn needs to resolve to 127.0.0.1 (via nip.io), Accessing the service from the host works fine.

Could network mode be made optional like it was 1.28?

**Comment by gbraad** [comment]
Please create an issue to explain your needs
