### ISSUE TITLE
libvirt: Revise host dnsmasq configuration

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#248]
Now that we are running dnsmasq in the `crc` VM, we can have a simpler dnsmasq configuration on the host ( `server=/.testing/192.168.130.11` is probably enough), or we could directly add the dns server to `/etc/resolv.conf`

**Comment by gbraad** [comment]
@zeenix This is actually the issue we referenced. For this to work, we can first just use the DNSmasq server as running inside the VM. Instead of having to rely on NetworkManager to use a dnsmasq overlay, we can just use a simple entry to add the VM as a nameserver.

**Comment by gbraad** [comment]
I will create follow-up tasks for dealing with `systemd-resolv`, but we have also concluded that this is ONLY the default on headless setups; Ubuntu desktops should still use NetworkManager as the default.

**Comment by zeenix** [comment]
> I will create follow-up tasks for dealing with `systemd-resolv`, but we have also concluded that this is ONLY the default on headless setups; Ubuntu desktops should still use NetworkManager as the default.

Yeah, i don't think we need to even think about supporting Ubuntu server/headless right now so I'd suggest not creating a task for that one but up to you.
