### ISSUE TITLE
BUG : ERRO Cannot update kubeconfig: Head "https://oauth-openshift.apps-crc.testing": Service Unavailable

### ISSUE THREAD

**Issue by sivaraj-karuppusamy** [code-ready/crc#2486]
I am trying to setup a crc container on linux machine with OS RHEL 7.9.
VERSION="4.9.1"
COMPONENT="worker"
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
Red Hat Enterprise Linux Server release 7.9 (Maipo)
Red Hat Enterprise Linux Server release 7.9 (Maipo)

CRC status:-

CRC VM:          Running
OpenShift:       Running (v4.7.11)
Disk Usage:      15.41GB of 32.74GB (Inside the CRC VM)
Cache Usage:     13.32GB
Cache Directory: /home/X144282/.crc/cache

**Comment by praveenkumar** [comment]
@sivaraj-karuppusamy Can you please use the bug template to create an issue so that we get required info to debug/reproduce it? Also from status I can see `OpenShift: Running (v4.7.11)` so not sure what is the issue.

**Comment by sivaraj-karuppusamy** [comment]
Hi Praveen, Can you please provide more info on the bug template so i can create an issue .

**Comment by sivaraj-karuppusamy** [comment]
Any logs required from my end, kindly let me know.

**Comment by sivaraj-karuppusamy** [comment]
@praveenkumar : Can you provide the steps to raise a bug template

**Comment by sivaraj-karuppusamy** [comment]
@praveenkumar required info has been provided as per bug template . 2489

**Comment by praveenkumar** [comment]
closing in favor of #2489
