### ISSUE TITLE
[BUG] ERRO Cannot update kubeconfig: Head "https://oauth-openshift.apps-crc.testing": Service Unavailable

### ISSUE THREAD

**Issue by sivaraj-karuppusamy** [code-ready/crc#2489]
### General information

  * OS: Linux 
  * Hypervisor: vmware
  * Did you run `crc setup` before starting it (Yes/No)? - YES
  * Running CRC on: Laptop / Baremetal-Server / VM - VM

## CRC version

# crc version
WARN A new version (1.28.0) has been published on https://cloud.redhat.com/openshift/create/local
CodeReady Containers version: 1.27.0+3d6bc39d
OpenShift version: 4.7.11 (embedded in executable)

```
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
$ crc status --log-level debug
DEBU HTTP-PROXY: http://10.64.80.180:8080, HTTPS-PROXY: http://10.64.80.180:8080, NO-PROXY: 127.0.0.1,localhost,.r02.xlgs.local,10.229.49.121, proxyCAFile:
DEBU CodeReady Containers version: 1.27.0+3d6bc39d
DEBU OpenShift version: 4.7.11 (embedded in executable)
DEBU Running 'crc status'
DEBU Checking file: /home/X144282/.crc/machines/crc/.crc-exist
DEBU Checking file: /home/X144282/.crc/machines/crc/.crc-exist
DEBU Found binary path at /home/X144282/.crc/bin/crc-driver-libvirt
DEBU Launching plugin server for driver libvirt
DEBU Plugin server listening at address 127.0.0.1:46519
DEBU () Calling .GetVersion
DEBU Using API Version 1
DEBU () Calling .SetConfigRaw
DEBU () Calling .GetMachineName
DEBU (crc) Calling .GetState
DEBU (crc) DBG | time="2021-06-28T05:44:36-04:00" level=debug msg="Getting current state..."
DEBU (crc) DBG | time="2021-06-28T05:44:36-04:00" level=debug msg="Fetching VM..."
DEBU (crc) Calling .GetBundleName
DEBU (crc) Calling .GetIP
DEBU (crc) DBG | time="2021-06-28T05:44:36-04:00" level=debug msg="GetIP called for crc"
DEBU (crc) DBG | time="2021-06-28T05:44:36-04:00" level=debug msg="Getting current state..."
DEBU (crc) DBG | time="2021-06-28T05:44:36-04:00" level=debug msg="IP address: 192.168.130.11"
DEBU Running SSH command: df -B1 --output=size,used,target /sysroot | tail -1
DEBU Using ssh private keys: [/home/X144282/.crc/machines/crc/id_ecdsa /home/X144282/.crc/cache/crc_libvirt_4.7.11/id_ecdsa_crc]
DEBU SSH command results: err: <nil>, output: 32737570816 15537512448 /sysroot
DEBU Running SSH command: <hidden>
DEBU SSH command succeeded
DEBU Making call to close driver server
DEBU (crc) Calling .Close
DEBU Successfully made call to close driver server
DEBU Making call to close connection to plugin binary
DEBU (crc) DBG | time="2021-06-28T05:44:37-04:00" level=debug msg="Closing plugin on server side"
CRC VM:          Running
OpenShift:       Running (v4.7.11)
Disk Usage:      15.54GB of 32.74GB (Inside the CRC VM)
Cache Usage:     13.32GB
Cache Directory: /home/X144282/.crc/cache
```

## CRC config
```bash
# Put `crc config view` output here
[X144282@XLCAPP437426DV ~]$ crc config view
- consent-telemetry                     : no
- http-proxy                            : http://10.64.80.180:8080
- https-proxy                           : http://10.64.80.180:8080
- no-proxy                              : .r02.xlgs.local,10.229.49.121
[X144282@XLCAPP437426DV ~]$
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux

[X144282@XLCAPP437426DV ~]$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
[X144282@XLCAPP437426DV ~]$
```

### Steps to reproduce

  1. 
  2. 
  3. 
  4. 

### Expected:
Webconsole /oauth should be accessible. Crc is running but not accessible .

### Actual
oauth/webconsole Service is not accessible nor not reachable from the VM machine or remotely.

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
@sivaraj-karuppusamy This is a nested virtualization setup and we don't have any vmware specific hardware to test it :( , we did receive same kind of issues (around nested virtualization) in the past.

**Comment by sivaraj-karuppusamy** [comment]
@praveenkumar : FYi, the crc start log file.
<script src="https://gist.github.com/sivaraj-karuppusamy/48ce3675da2abe145aaa88a025deed8c.js"></script>

**Comment by sivaraj-karuppusamy** [comment]
@praveenkumar could please go through the log file which i shared in gist and provide an update. If anything need to be tested from my end.

**Comment by cfergeau** [comment]
It's a bit tricky to help you here, as there are multiple things which could go wrong:
- vmware nested virtualization
- rhel 7.9
- use of a slightly old crc version with expired certificates
- http proxy

While we try to support most of these, bugs may occur, especially when using all of these together. And as Praveen mentioned, there has been known issues in the past with vmware nested virtualization.
If possible, I'd recommend trying the latest crc release with http proxy on a bare metal rhel8 host. If we know if this works or not, this would remove some of the potentially problematic parts from the equation.

**Comment by danielmenezesbr** [comment]
@sivaraj-karuppusamy, I have a [similar problem](https://github.com/code-ready/crc/issues/2490).

In my use case currently, the workaround is to use the[ SNC](https://github.com/code-ready/snc/) instead of using the CRC. This workaround does not necessarily apply to you.

[In this repository](https://github.com/danielmenezesbr/crc-on-gcp-terraform) shows how to use SNC / CRC on GCP.

The previous repository configuration is applicable to OCP 4.6, but I think that with a few tweaks it is possible to work in OCP 4.7 as well.
