### ISSUE TITLE
[BUG] CRC user / system installation on Windows.

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/crc#2505]
Currently CRC is installed partially per user. 

When install CRC from msi, then you need to execute `crc setup` when finish a reboot is required. After reboot the machine if a different user is logged in it gets a notification message saying `crc setup is not completed and a new crc setup is required before run crc start`.

At that point the user logged in (different from the one who ran the installer) can not execute crc as it shows command not recognized (basically is not on its PATH env).

At this point the installation seems in the middle of a system wide installation.

**Comment by anjannath** [comment]
We can modify the system PATH environment variable, i think it makes sense now too since we add the start-menu entry and startup per machine.
