### ISSUE TITLE
OCP 4.8 readiness

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#2509]
* [x] BZ issue for authentication
       - since rc1, no workaround
       - https://bugzilla.redhat.com/show_bug.cgi?id=1978193
  * [x] BZ issue for MCO
       - has a possible workaround, requested backport
       - https://bugzilla.redhat.com/show_bug.cgi?id=1975078
  * [x] BZ issue for OLM
       - https://bugzilla.redhat.com/show_bug.cgi?id=1979550

Also to consider
  * [ ] https://github.com/code-ready/snc/issues/451 Increase bundle size when 4.8 is used

**Comment by gbraad** [comment]
Also to consider
  * [ ] https://github.com/code-ready/snc/issues/451 Increase bundle size when 4.8 is used

**Comment by cfergeau** [comment]
We also need to check if changes to the host OS done through the MCO work as expected on macOS. My understanding is that in some cases, MCO changes could require the use of a new ostree layer. This is done through changes to the kernel command line + a reboot. On macOS, the kernel command line is hardcoded in the bundle, it can't change dynamically, so if an ostree layer is needed, this won't be possible on macOS.
A possible solution to this is to switch to using UEFI boot with hyperkit, which is easy once you have a precompiled firmware (docker ships one).

**Comment by guillaumerose** [comment]
With @praveenkumar we tried on macOS. After a kubelet change, the MCO triggered a restart of the VM.
It actually stopped it. We had to run `crc start` again. After that, the configuration was in place and working as expected.

**Comment by cfergeau** [comment]
> we tried on macOS. After a kubelet change, the MCO triggered a restart of the VM. It actually stopped it. We had to run crc start again

hyperkit exit code should allow to differentiate between shutdown and reboot:
```
EXIT STATUS

The hyperkit process exits with one of the following values:
- 0: The guest either powered down or halted cleanly.
- 1: An error occurred.
- 2: The guest rebooted/reset. The caller is responsible for starting a new hyperkit process in this case.
```
