### ISSUE TITLE
crc fails starting when dnsmasq started outside from NetworkManager

### ISSUE THREAD

**Issue by akram** [code-ready/crc#251]
Hi all,

if dnsmasq is already started outside of NetworkManager, crc fails starting with the following error:

```
INFO Extracting the Bundle tarball ...
INFO Starting stopped VM ...
INFO Bridge IP on the host: 192.168.130.1
ERRO Failed internal dns query: ssh command error:
command : host -R 3 foo.apps-crc.testing
```

crc tells NetworkManager to start dnsmasq. But if a dnsmasq service is already started, NetworkManager is failing with the following message:
```
-- Logs begin at Thu 2019-06-06 03:29:01 EDT. --
Jun 19 07:15:05 mylaptop.mydom NetworkManager[16439]: <warn>  [1560942905.4391] dns-mgr: plugin dnsmasq child quit unexpectedly
Jun 19 07:15:05 mylaptop.mydom NetworkManager[16439]: <info>  [1560942905.4391] dns-plugin[0x56074776c830]: starting dnsmasq...
Jun 19 07:15:05 mylaptop.mydom NetworkManager[16439]: dnsmasq: failed to create listening socket for 127.0.0.1: Address already in use
Jun 19 07:15:05 mylaptop.mydom NetworkManager[16439]: <warn>  [1560942905.4433] dnsmasq[0x56074776c830]: dnsmasq exited with error: Network access problem (address in use, permissions) (2)
```

Leading to /etc/resolv.conf never getting correctly updated and remaining to something like:
```
# Generated by NetworkManager
search mydom
nameserver 192.168.x.y
```
 
instead of:
```
# Generated by NetworkManager
search mydom
nameserver 127.0.0.1
```

Thank you @praveenkumar for helping sorting out the whole issue 
cc @cfergeau

**Comment by akram** [comment]
resolution here is to stop and disable dnsmasq . Restarting NetworkManager and maybe rebooting your laptop may be required:

```
systemctl stop dnsmaq
systemctl disable dnsmasq
systemctl restart NetworkManager
```

**Comment by praveenkumar** [comment]
Once we have #248 in I hope then it should be more easy and we don't have to rely on host NetworkManager side.

**Comment by gbraad** [comment]
you mean you use `systemctl enable dnsmasq` ?

**Comment by akram** [comment]
> you mean you use `systemctl enable dnsmasq` ?

for some reason my dnsmasq unit was enabled and started.
Probably because I installed and configured openshift 4 for for libvirt. Or maybe, dnsmasq is enabled by default with REHL8.

the fix is to disable and stop dnsmasq standalone unit and let NetworkManager start its own dnsmasq process.

**Comment by gbraad** [comment]
I do not remember that OpenShift 4 describes to enable dnsmasq (we maintain this howto now), but we have to do some investigation for sure to why this was enabled.

Oftentimes people use this for caching reasons, and we should be able to work with this...

**Comment by cben** [comment]
I too had dnsmasq standalone unit enabled, probably as result of attempting to troubleshoot bad DNS in `oc cluster up` and reading https://stackoverflow.com/questions/48057668/pods-cant-resolve-dns-after-oc-cluster-up advice, but not understand that NetworkManager is running dnsmasq anyway (?)

- [x] https://docs.okd.io/3.11/install/prerequisites.html#prereq-dns does explain

Disabling the standalone unit wasn't enough to make crc work for me yet.  Nor oc cluster.  It now seems I have some wider DNS problem in all docker containers, outside openshift too...

**Comment by gbraad** [comment]
@cben in response to:

> Disabling the standalone unit wasn't enough to make crc work for me yet. Nor oc cluster. It now seems I have some wider DNS problem in all docker containers, outside openshift too...

Please file a new issue if you still have these issues. It seems you are using different things at the same time. Plus, be aware that docker has issues with some nameservers that refer to `localhost` as this gets replaced with `8.8.8.8`. This is a known issue for Docker that causes issues in a corporate environment.
