### ISSUE TITLE
[BUG] crc cleanup error 

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/crc#2521]
On windows after run `crc setup` if user just want to undo changes with `crc cleanup` without rebooting the machine the `crc cleanup` command ends up failing with:

```bash
Post "http://unix/clean": open \\.\pipe\crc-admin-helper: Access is denied.
``` 

Also the error seems bit random as subsequent execution of `crc cleanup` does not show any error 

## CRC version
```bash
CodeReady Containers version: 1.29.0+c289875e
OpenShift version: 4.7.18 (embedded in executable)
```
  
### Logs

```bash
PS C:\Users\crcqe> crc setup
INFO Checking if crc-admin-helper executable is cached
INFO Checking for obsolete admin-helper executable
INFO Checking if running on a supported CPU architecture
INFO Checking minimum RAM requirements
INFO Checking if running in a shell with administrator rights
INFO Checking Windows 10 release
INFO Checking Windows edition
INFO Checking if Hyper-V is installed and operational
INFO Checking if crc-users group exists
INFO Checking if current user is in Hyper-V group and crc-users group
INFO Checking if Hyper-V service is enabled
INFO Checking if the Hyper-V virtual switch exists
INFO Found Virtual Switch to use: Default Switch
INFO Checking if admin-helper daemon is installed
INFO Installing admin-helper daemon
INFO Will run as admin: install admin-helper daemon
INFO Checking if CRC bundle is extracted in '$HOME/.crc'
INFO Checking if C:\Users\crcqe\.crc\cache\crc_hyperv_4.7.18.crcbundle exists
Your system is correctly setup for using CodeReady Containers, you can now run 'crc start' to start the OpenShift cluster
PS C:\Users\crcqe> crc cleanup
INFO Removing hosts file records added by CRC
INFO Uninstalling admin-helper daemon
INFO Will run as admin: uninstall admin-helper daemon
INFO Removing the crc VM if exists
INFO Removing dns server from interface
INFO Will run as admin: Remove dns entry for default switch
INFO Removing 'crc-users' group
INFO Will run as admin: remove crc-users group
INFO Removing pull secret from the keyring
INFO Removing older logs
INFO Removing CRC Machine Instance directory
Post "http://unix/clean": open \\.\pipe\crc-admin-helper: Access is denied.
PS C:\Users\crcqe>
```

**Comment by gbraad** [comment]
this is due to the `crc-users` being removed. this means `admin-helper` or opening the port leads to a permission error.

**Comment by gbraad** [comment]
@anjannath @adrianriobo Since this is not resolved in the current release binaries, this needs to be recorded as a known issue, right?

Also, needs to be resolved in the next sprint.

**Comment by guillaumerose** [comment]
I don't really know how to fix this.
Cleanup is a best-effort function. This error didnt prevent the others cleanup functions to be performed. It is just that at the end, crc prints all errors.

Should the message be more explicit: `Cannot remove custom hosts file entries: Post "http://unix/clean": open \\.\pipe\crc-admin-helper: Access is denied.` ?

**Comment by anjannath** [comment]
> 
> 
> I don't really know how to fix this.
> Cleanup is a best-effort function. This error didnt prevent the others cleanup functions to be performed. It is just that at the end, crc prints all errors.
> 
> Should the message be more explicit: `Cannot remove custom hosts file entries: Post "http://unix/clean": open \\.\pipe\crc-admin-helper: Access is denied.` ?

one easy-fix i wanted to try was just return `nil` if the err was of type `PermissionError`, like we are doing for `ErrNotExists` it should get rid of this specific error showing up in the end of cleanup? but not seeing this error consistently.. :/ 

https://github.com/code-ready/crc/blob/c3360d0f6f46d02e9d32e074a033993232a587f3/pkg/crc/preflight/preflight_checks_common.go#L246-L252
