### ISSUE TITLE
[msi] Run `crc delete` from a custom action when upgrading using the msi

### ISSUE THREAD

**Issue by anjannath** [code-ready/crc#2537]
The recommended way to upgrade in the binary installation is to perform `crc delete`. [upgrading doc](https://crc.dev/crc/#upgrading-codeready-containers_gsg) the msi can perform this when it detects a upgrade scenario.

Note: macOS pkg should also do this if its not already added as the issue mentioned in https://github.com/code-ready/crc/issues/2534#issuecomment-874588286 might occur in there aswell

Related to: #2534

**Comment by cfergeau** [comment]
The installer needs to ask the user before doing this, with the "don't delete" button highlighted by default, as this is a data loss scenario.

**Comment by anjannath** [comment]
> 
> 
> The installer needs to ask the user before doing this, with the "don't delete" button highlighted by default, as this is a data loss scenario.I guess an alternative could be to stop the cluster/stop the tray/daemon and upgrade the binaries, and then when next starting up the cluster, tell the user they need to delete it before starting?

We currently are able to stop the tray and proceed with the installation, i think showing a message from the tray to delete the cluster if there's an existing one is a better way.
