### ISSUE TITLE
[e2e] Use redis instead of etcd operator as part of marketplace story

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#2542]
recently we observed #2538 one and looks like we are using an operator which is not actively maintained and developed as per https://github.com/coreos/etcd-operator page. Better to use something like redis for our marketplace story.

**Comment by adrianriobo** [comment]
Just after a quick view on some of the operators available (with clustering feature), I could not find any hosted on quay. So we have 2 possible approaches:

* Make use of operator with corporate registry like [akka](https://operatorhub.io/operator/akka-cluster-operator) or [postgres](https://operatorhub.io/operator/postgres-operator)
* Pick any other operator and push the images used to our quay organization

Make use of the specs as they are will create issues related to dockerhub limit rate
