### ISSUE TITLE
'You are logged in as a temporary administrative user.' banner is shown again

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#2547]
In 4.7, we changed what was needed to remove this banner. With 4.8, it is back again. 

![Screenshot from 2021-07-07 11-31-25](https://user-images.githubusercontent.com/172624/124788544-bc518d80-df49-11eb-9581-c45adc9d95ef.png)

It appears some code was specifically added in the console for this purpose. https://github.com/openshift/console/commit/fa1c708ab298c706378019e68660e990c6a39d34#diff-31d31bf56f5ae7e32c1b35bfc7fde9b464fdb5242882722686aeda0a74082752R47

**Comment by cfergeau** [comment]
This seems to have been fixed in 4.8.9 https://github.com/openshift/console/pull/9516
Keeping this open until we can confirm, latest crc release is based on 4.8.5

**Comment by anjannath** [comment]
In 4.8.5 we still have this banner
![image](https://user-images.githubusercontent.com/8885742/132470667-cb40ffc8-7de1-4f9d-ad61-52daffd8b9c4.png)

**Comment by cfergeau** [comment]
The banner is not present in 1.35.0, we can keep this one closed.
