### ISSUE TITLE
Error starting a stopped crc VM

### ISSUE THREAD

**Issue by dharmit** [code-ready/crc#255]
I managed to spin up a CRC VM with `./crc start -b /path/to/tar/ball`. Thanks for making it so simple to spin up a single node OpenShift 4.x VM.

Today I tried to start that VM but it fails with following error:
```bash
$ crc start -b ~/Downloads/crc_libvirt_4.1.0.tar.xz
crc - Local OpenShift 4.x cluster
INFO Checking if oc binary is cached              
INFO Checking if Virtualization is enabled        
INFO Checking if KVM is enabled                   
INFO Checking if Libvirt is installed             
INFO Checking if user is part of libvirt group    
INFO Checking if Libvirt is enabled               
INFO Checking if Libvirt daemon is running        
INFO Checking if crc-driver-libvirt is installed  
INFO Checking if Libvirt crc network is available 
INFO Checking if Libvirt crc network is active    
INFO Checking if /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf exists 
INFO Checking if /etc/NetworkManager/dnsmasq.d/crc.conf exists 
INFO Extracting the Bundle tarball ...            
INFO Starting stopped VM ...                      
ERRO Error occured: unknown error occurred        
ERRO Error determining host IP: unknown error occurred 
INFO Running                                      
[unknown error occurred]
```

I didn't do a `crc stop` explicitly. The VM turned off due to system shutdown.

```bash
$ crc version
crc - Local OpenShift 4.x cluster
version: 0.87.0-alpha-4.1.0+3a5033a
```

A few tangential questions:
- Is there a plan to add `crc status` and `crc resume` commands to check status and resume a stopped VM respectively?
- The tarball I have is RHEL based. Where do I find a Fedora or CentOS based tarball?
- Rather silly one: what next after managing to start VM with `crc start`? How do I login to that VM? How do I access the web console? I couldn't find this info in the docs.

**Comment by cfergeau** [comment]
Can you run with `--log-level debug`? Maybe this will give more information as to what's going wrong :)
The VM image is based on Red Hat CoreOS and will for the foreseeable future. But it should be possible to use it together with CRC on Fedora/CentOS/RHEL.
I think when `crc start` is successful, it prints information about how to use it. There is already a ticket for adding `crc status`.

**Comment by dharmit** [comment]
Oddly, running `crc start` right after failure leads to a successful start. But it fails on the first attempt. Logs were long so I created a gist. https://gist.github.com/dharmit/5d9f0030d9fb178a0c7a1e61297bec37

Thanks for answering those questions! :smile:

**Comment by dharmit** [comment]
To add to the above comment, even a fresh start fails on the first attempt. It worked fine yesterday, IIRC. Added a gist with debug logs: https://gist.github.com/dharmit/5d9f0030d9fb178a0c7a1e61297bec37#file-fresh-start-stdout-md.

There are two files in the gist. One containing logs from a fresh start and other containing logs from the failed attempt to resume an existing VM.

**Comment by cfergeau** [comment]
it looks as if the VM was never coming up when it fails.
You can use `sudo virsh -c qemu:///system list` to check when it's running, and if it's indeed not running, I'd try `sudo virsh -c qemu:///system console crc` a few times while `crc start` is running to try to get logs from the VM.

**Comment by praveenkumar** [comment]
@dharmit Are you using it in nested environment or directly on the host?

**Comment by dharmit** [comment]
@praveenkumar no this is not a nested environment. I'm trying on my laptop. But your question prompted me to check if virtualization is enabled in the BIOS because this is a new laptop. It is enabled in the BIOS so no issues on that front either.

**Comment by dharmit** [comment]
I noticed the my `/etc/resolv.conf` was using `127.0.0.1`. I'm not sure if it has anything to do with CRC. I changed it to `1.1.1.1` that I normally use.

I have uploaded the console logs. Error has changed a bit this time. https://gist.github.com/dharmit/5d9f0030d9fb178a0c7a1e61297bec37#file-console-log-md

**Comment by praveenkumar** [comment]
> I noticed the my /etc/resolv.conf was using 127.0.0.1. I'm not sure if it has anything to do with CRC. I changed it to 1.1.1.1 that I normally use.

yes it is do with CRC since this is the dnsmasq nameserver we use to query internal domain name, you shouldn't be changing this one.

**Comment by dharmit** [comment]
> yes it is do with CRC since this is the dnsmasq nameserver we use to query internal domain name, you shouldn't be changing this one.

But it breaks DNS resolution for various other websites on my laptop!

**Comment by praveenkumar** [comment]
@dharmit wait till we worked out on #248 so we will not depend on the host DNS side for internal communication for the VM.

**Comment by cfergeau** [comment]
@dharmit have you tested newer releases? Are you still experiencing this issue? I'll assume new releases are less problematic and I'll close this ticket, you can reopen it or file a new issue if this is still a problem.
