### ISSUE TITLE
[BUG] On MacOS when daemon running during `crc setup` popup shows daemon crash 

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/crc#2567]
### General information

  * OS: macOS
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it (Yes/No)? Y
  * Running CRC on: Laptop

## CRC version

1.29.1

### Steps to reproduce

  1. Install crc
  2. `crc daemon`
  3. `crc setup`

### Expected

No error

### Actual

Pop up showing daemon crash.

![1 29 1-daemon-run+daemon](https://user-images.githubusercontent.com/1957899/125284237-80d40c00-e319-11eb-9873-5f9c0b3ec7e6.png)

**Comment by adrianriobo** [comment]
The daemon process has no issue and after this I can run `crc start`. Also mention if I omit `crc setup`. The cluster also start without any issue. (So no need to run `crc setup` at all)

**Comment by guillaumerose** [comment]
on macOS, the daemon is not meant to be run by hand. Should we hide the subcommand ?

**Comment by adrianriobo** [comment]
Actually description is hidden, but to he fair if I am an old user and I am use to run it I will no check the help but try to run it directly... 
```
Available Commands:
  bundle      Manage CRC bundles
  cleanup     Undo config changes
  config      Modify crc configuration
  console     Open the OpenShift Web Console in the default browser
  delete      Delete the OpenShift cluster
  help        Help about any command
  ip          Get IP address of the running OpenShift cluster
  oc-env      Add the 'oc' executable to PATH
  podman-env  Setup podman environment
  setup       Set up prerequisites for the OpenShift cluster
  start       Start the OpenShift cluster
  status      Display status of the OpenShift cluster
  stop        Stop the OpenShift cluster
  version     Print version information
```

**Comment by gbraad** [comment]
The daemon commands should all be hidden.

**Comment by cfergeau** [comment]
I haven't been able to reproduce this with a recent version.
