### ISSUE TITLE
[API] Refactor the config to use HTTP verbs

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#2570]
Currently the config endpoint uses `config/get`, `config/set` and `config/unset` to expose the functionality to deal with configuration. However, this seems to be a direct copy of the binary protocol and does not follow HTTP verbs as expected

**Comment by cfergeau** [comment]
Follow-up discussion from https://github.com/code-ready/crc/pull/2629/commits/dff5828cedeab05a651d9f2e574cbee311acea1b

This requires quite extensive changes to the API, not just `POST /api/config/unset` -> `DELETE /api/config`, `POST /api/config/get` -> `GET /api/config`, ...

GET should not need any additional data in the request body as described in https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET , so `curl -X POST -d '{"properties":["cpus", "memory"]}' --unix-socket ~/.crc/crc-http.sock http:/c/api/config` would become `curl -X GET --unix-socket ~/.crc/crc-http.sock http:/c/api/config/cpus&memory`
