### ISSUE TITLE
Failed to add user to group. (-2147022676 <username> Hyper-V Administrators )

### ISSUE THREAD

**Issue by osya** [code-ready/crc#2581]
Trying to install `crc-windows-amd64.msi` version 1.29.1-4.7.18 on Windows 10 Pro. 

Error appears "Failed to add user to group. (-2147022676 <username> Hyper-V Administrators )"

Because in Computer Management | Local User and Group | Groups there is a group "Администраторы Hyper-V". But crc trying to use hardcoded group name "Hyper-V Administrators"

Workaround: create group "Hyper-V Administrators" then installation successful

**Comment by praveenkumar** [comment]
This looks like localization issue.

**Comment by osya** [comment]
> This looks like localization issue.

You are right! :)

**Comment by wakedeer** [comment]
same here! Is there a workaround?

**Comment by wakedeer** [comment]
@osya Thanks for the workaround!
`net localgroup "Hyper-V Administrators" /add` 
helped me
