### ISSUE TITLE
[integration] Revisit the crc stop test.

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#259]
This is a follow up issue for discussion happen https://github.com/code-ready/crc/pull/239#discussion_r296103639 here, we don't want to hold that PR any longer since other PR is depend on it.

**Comment by cfergeau** [comment]
The main concern is this:
> we are using crc stop -f and end message for this command can be CodeReady Containers instance forcibly stopped or CodeReady Containers instance stopped which will make this test always flaky if we compare with only one message.
