### ISSUE TITLE
crc setup does not work if Windows 10 uses ExecutionPolicy AllSigned

### ISSUE THREAD

**Issue by jochenr** [code-ready/crc#2596]
crc setup does not work in my environment (Windows 10 laptop), because the powershell ExecutionPolicy ist set to "AllSigned".

I get the error message (sorry i canot convince my systemto log it in English):
DEBU stderr: C:\Users\xxxx\AppData\Local\Temp\crcScripts557137339\runAsAdmin.ps1 : Die Datei
"C:\Users\xxxx\AppData\Local\Temp\crcScripts557137339\runAsAdmin.ps1" kann nicht geladen werden. Die Datei
"C:\Users\xxxx\AppData\Local\Temp\crcScripts557137339\runAsAdmin.ps1" ist nicht digital signiert. Sie k�nnen dieses
Skript im aktuellen System nicht ausf�hren. Weitere Informationen zum Ausf�hren von Skripts und Festlegen der
Ausf�hrungsrichtlinie erhalten Sie unter "about_Execution_Policies" (https:/go.microsoft.com/fwlink/?LinkID=135170)..
In Zeile:1 Zeichen:43

meaning that the script "...runAsAdmin.ps1" is not digitally signed

due to the company group policies this cannot be changed;-(

I have two suggestions
for
https://github.com/code-ready/crc/blob/19171e86f65accffe7478f58f96f1223fbca5d30/pkg/os/windows/powershell/powershell_windows.go#L78

1.) provide the temporary script with a signature that we can trust (our admins would add the cert....)

2.) start the command with "-executionpolicy bypass" option

**Comment by gbraad** [comment]
We can not sign on the fly (as this would need to share a cert that does not actually provide security). We are moving most of these (if not all) steps to a native installer (MSI).

**Comment by jochenr** [comment]
A MSI installer that does all the steps would be great. Do you already have a timeline/roadmap for that?

As a workaround it would be great, if we can pass arguments to "crc.exe" which will be "looped through" to the powershell call so that a user can decide weather he would pass the insecure (e.g. "-executionpolicy bypass") arguments himself.

**Comment by gbraad** [comment]
^^ We are already working on this and a preview is available; though setup steps around Hyper-V aren't done. it seems the standard MSI tasks can not handle SID for adding a user to a group, which therefore has to use a name; and this causes issues when these names are localized.

**Comment by jochenr** [comment]
thanks for the info.
I already did the Hyper-V virtual swich and the users-group manually, because I just wanted to simulate the setup routine by hand....
hopefully you find the solutions to create a very good MSI.
thank you very much for your efforts!

p.s.: is there a documentation how I can completely install it manually? reverse enineering from the code is hard;-)

**Comment by jochenr** [comment]
with the MSI installer in version 1.32.1 I was able to install:-)
thank you!

**Comment by gbraad** [comment]
thanks for the feedback. this confirms that the MSI might have been a good idea.
