### ISSUE TITLE
[BUG] upgrade unexpected behavior

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/crc#2598]
Testing pre release bits `1.30.0` on windows we got unexpected behavior:

1. Got version `1.29.1` installed with msi (install and restart the computer)

2. Try to upgrade to `1.30.0` with `1.29.1` running, we want to avoid restart the computer. As hyper-v and user and groups are already set up from previous installation the restart should not be necessary.

3. When `1.30,0` installation finishes it asks for reboot. Is this necessary?. We do not reboot.

4. Then `crc setup` finish successfully telling us we can start crc as usual. But tray is always reporting error and exiting. If we check the `crc setup --check-only` logs we can see:

```bash
INFO Checking if admin-helper daemon is installed
DEBU Get http://unix/version: open \\.\pipe\crc-admin-helper: Access is denied.
Get http://unix/version: open \\.\pipe\crc-admin-helper: Access is denied.
```

**Comment by adrianriobo** [comment]
From `crc setup`:

```powershell
PS C:\Users\crcqe> crc setup
INFO Checking if crc-admin-helper executable is cached
INFO Checking for obsolete admin-helper executable
INFO Checking if running on a supported CPU architecture
INFO Checking minimum RAM requirements
INFO Checking if running in a shell with administrator rights
INFO Checking Windows 10 release
INFO Checking Windows edition
INFO Checking if Hyper-V is installed and operational
INFO Checking if crc-users group exists
INFO Checking if current user is in Hyper-V group and crc-users group
INFO Checking if Hyper-V service is enabled
INFO Checking if the Hyper-V virtual switch exists
INFO Found Virtual Switch to use: Default Switch
INFO Checking if admin-helper daemon is installed
INFO Installing admin-helper daemon
INFO Will run as admin: install admin-helper daemon
INFO Checking if vsock is correctly configured
INFO Checking if CodeReady Containers daemon is installed
INFO Checking if tray executable is present
INFO Checking if tray is running
INFO Starting CodeReady Containers tray
INFO Checking if CRC bundle is extracted in '$HOME/.crc'
INFO Checking if C:\Program Files\CodeReady Containers\crc_hyperv_4.8.0.crcbundle exists
INFO Extracting bundle from the CRC executable
INFO Ensuring directory C:\Program Files\CodeReady Containers exists
INFO Uncompressing crc_hyperv_4.8.0.crcbundle
crc.vhdx: 13.62 GiB / 13.62 GiB [-----------------------------------------------------------------------------] 100.00%
oc.exe: 96.73 MiB / 96.73 MiB [-------------------------------------------------------------------------------] 100.00%
Your system is correctly setup for using CodeReady Containers, you can now run 'crc start' to start the OpenShift cluster
```

**Comment by anjannath** [comment]
a simple fix would be to skip the steps that need reboot such as -- adding user to hyper-v admin group and creating the crc-users group in case of an upgrade scenario

**Comment by anjannath** [comment]
To achieve no restart on upgrades, we have to roll out the changes to the msi in two releases. The reason for this is during an upgrade, the windows installer actually does a full uninstall of the previous version and then installs the new version, but the uninstall of the previous version is handled with the msi of the previous version itself, so changes we do to the msi for the current release will not be used for the uninstall phase during upgrade.

For a no-restart upgrade scenario, we need to skip the group changes, so first we do a release of the msi that doesn't delete the crc-users group and doesn't remove the current user from the this group if its an upgrade, then in the next release msi will not add the crc-users group and addition of current user to this group if its an upgrade.

By doing the above we'll not have to reboot if its an upgrade scenario.

Note: We have two group related tasks, but we atm do not remove the user from "Hyper-V Admins" on uninstall so we don't need to change that.
