### ISSUE TITLE
Implement the `crc IP` command.

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#260]
We need to implement `crc IP` command.

**Comment by cfergeau** [comment]
Why do we want such a command? In general, we don't want the user to directly access the VM, and if they want to do it, it should have DNS entries (api.crc.testing comes to mind). If needed, we can easily add other names.

**Comment by praveenkumar** [comment]
@cfergeau most of the time when user try to deploy an application and use `NodePort` service then they always require the node IP (in our case it's VM IP), I got few messages from user about it so thought of having it also part of crc. This is trivial command and if it provide some value to user then having it would be good.

- https://kubernetes.io/docs/concepts/services-networking/service/#nodeport

**Comment by praveenkumar** [comment]
This is fixed by #261
