### ISSUE TITLE
File versioning in the windows installer zip file?

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#2617]
For the 1.30.1 release, the Windows installer is released as `crc-windows-installer.zip`
This archive contains these files:
```
cab1.cab
cab2.cab
cab3.cab
crc-windows-amd64.msi
```

I think these files should be in their own directory (`crc-windows-1.30.1-amd64/`)? Maybe we could also version the msi name?

**Comment by cfergeau** [comment]
When we only ship the installer, the zip could be renamed to `crc-windows-amd64.zip` for consistency with the other platforms.

**Comment by gbraad** [comment]
is the naming of the file something we control ?

**Comment by cfergeau** [comment]
We control the name of the unsigned tarball, dunno how the signed tarball is generated. Might need sync with the team doing the signing.

**Comment by cfergeau** [comment]
Let's revisit this when we start shipping the electron installer.
