### ISSUE TITLE
[Spike] Decouple bundle and different binaries from crc released binary

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#2623]
Since we are looking into remote enablement for CRC where it is deployed on a remote linux machine and able to consume the `crc-http.sock`  it. From consumer machine it doesn't make sense to download complete fat binary if just need to communicating with the remote.  If we decouple the bundle and different binaries then we can have more control over what to download where.

This spike is for having a discussion with the team and try to break it small tasks and estimate time to have it in.

**Comment by cfergeau** [comment]
So we'd ship a small macOS .pkg, a small Windows .msi, and a small crc binary on linux, which would be the same as today, except the .crcbundle file would not be there? Then `crc setup/start/bundle download` would download the bundle if it's not cached?

Would we also provide a way to download both the binaries and the bundle at the same time? This would avoid having to wait for downloads twice, which is a change from what we are currently doing.

I assume we'd still only allow one very specific bundle version to work with a given crc release?

At the moment, on macOS and Windows, the bundle data is signed as part of the installer signature. We need to be careful and to keep some guarantee that the bundle we download is the intended one, and not just something which happens to seem to be at the right location.

**Comment by cfergeau** [comment]
> Since we are looking into remote enablement for CRC where it is deployed on a remote linux machine and able to consume the crc-http.sock it. From consumer machine it doesn't make sense to download complete fat binary if just need to communicating with the remote. If we decouple the bundle and different binaries then we can have more control over what to download where.

Just to have an example, user runs a macOS laptop, but wants to run crc on a remote server as their laptop is not powerful enough to run crc directly. Currently, they would have to download a multi-GB macOS binary for their laptop and a multi-GB linux binary for the server. The macOS download size is due to the bundle, which the user does not need since they will be running crc on the remote server. They only need the macOS binaries.
Problem we want to solve: How do we help the user only download what they need (macOS binaries and linux bundle) rather than  downloading GB of useless data?

**Comment by praveenkumar** [comment]
Mac
-----
Bundle
Hyperkit
Hyperkit driver => might be removed since we have now user mode networking
Qcow-tool
Admin-helper

Linux
-----
Bundle
Libvirt driver
Admin-helper

Windows
------
Bundle
Admin-helper

Cross-build
-------
CRC
Admin-helper

Issue we want to solve:
------
User is on macOS, and wants to run the tray on macOS, and crc on a remote linux box. We want to limit the size of the downloads (no download of 2 bundles)

Benefits
------
Have small crc binary in size
Able to build most of independent components on the brew including crc binary (with cross build)
In case of remote scenarios, users don’t need to download a multiGB file just to use it as a client.
Able to release other components (mac os specific with signing)  early on and can be consumed by crc binary.

How
----
We need to make a plan around how these files can be served (mostly from the CDN) and what would be our automatic upload there or we need to file the tickets like we do now.
Mechanism from CRC side to consume those, as of now except bundle all other binaries are downloaded should we make bundle download also part of the setup or something else.
We still have to follow our opinionated way to support a single bundle version with a specific release. (This is not something we plan for this split)
We must match sha for each downloaded artifact to make sure of the integrity.


Options about How to fetch the bundle (Context)
-----------------
Until now we were downloading binaries which have a bundle at once. We are planning a change where the binary and bundle could be downloaded separately.How important is it to keep a "all in one" download, or can we split and download the bundle 'on demand'? If on demand then which following option is the best one? 
- Download it as part of `crc setup` /  installation
- Download it along with thin binary (need to update the doc)
- Have 2 options on the cloud.redhat.com (thin and fat binary) (PM agrees to)



Persona
-----
- User Joe wants to use crc to have a cluster on his laptop/desktop locally, He doesn't have any issue to download everything at once and then carry on with his work. And this is what we are currently supporting.
- User Jack doesn’t have enough resources on his local laptop/desktop but wants to use crc on a Linux server where he has enough resources so he either directly downloads the Linux release on his Linux server or downloads it on his laptop and transfers it to their Linux server.  
- Futuristic user Jill who wants to access his remote crc instance using win/mac tray and doesn’t want to download 3.2GB data just to use the tray but he also wants to have oc/odo client or webconsole  to interact with openshift, podman-remote (if want to connect podman). What would be the best way to support this user.

**Comment by praveenkumar** [comment]
With recent team sync we are going to postpone this feature till we have better understanding around installer and tray application where we are putting effort to have those electron based.

**Comment by gbraad** [comment]
We are actively working on this to enable podman
