### ISSUE TITLE
[HELP needed] CRC console Monitoring error

### ISSUE THREAD

**Issue by xgxtbku** [code-ready/crc#2624]
### General information

  * OS: Linux
  * Did you run `crc setup` before starting it (Yes/No)? yes
  * Running CRC on: Baremetal-Server

## CRC version
```bash
1.29.1+bc5f4409
```
  
## CRC status
```bash
DEBU CodeReady Containers version: 1.29.1+bc5f4409
DEBU OpenShift version: 4.7.18 (embedded in executable)
DEBU Running 'crc status'
DEBU Checking file: /home/crcadmin/.crc/machines/crc/.crc-exist
DEBU Checking file: /home/crcadmin/.crc/machines/crc/.crc-exist
DEBU Found binary path at /home/crcadmin/.crc/bin/crc-driver-libvirt
DEBU Launching plugin server for driver libvirt
DEBU Plugin server listening at address 127.0.0.1:38163
DEBU () Calling .GetVersion
DEBU Using API Version 1
DEBU () Calling .SetConfigRaw
DEBU () Calling .GetMachineName
DEBU (crc) Calling .GetState
DEBU (crc) DBG | time="2021-08-03T16:38:13+02:00" level=debug msg="Getting current state..."
DEBU (crc) DBG | time="2021-08-03T16:38:13+02:00" level=debug msg="Fetching VM..."
DEBU (crc) Calling .GetBundleName
DEBU Running SSH command: df -B1 --output=size,used,target /sysroot | tail -1
DEBU Using ssh private keys: [/home/crcadmin/.crc/machines/crc/id_ecdsa /home/crcadmin/.crc/cache/crc_libvirt_4.7.18/id_ecdsa_crc]
DEBU SSH command results: err: <nil>, output: 32737570816 22060511232 /sysroot
DEBU Making call to close driver server
DEBU (crc) Calling .Close
DEBU Successfully made call to close driver server
DEBU Making call to close connection to plugin binary
DEBU (crc) DBG | time="2021-08-03T16:38:14+02:00" level=debug msg="Closing plugin on server side"
CRC VM:          Running
OpenShift:       Running (v4.7.18)
Disk Usage:      22.06GB of 32.74GB (Inside the CRC VM)
Cache Usage:     13.34GB
Cache Directory: /home/crcadmin/.crc/cache

```

## CRC config
```bash
- consent-telemetry                     : yes
- network-mode                          : user
- skip-check-network-manager-installed  : true
- skip-check-network-manager-running    : true
```

## Host Operating System
```bash
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### Steps to reproduce

  1. Opening: https://console-openshift-console.apps-crc.testing/
  2. Going to: Monitoring page
  3. Monitoring panels display: Danger alert:An error occurred Bad Gateway / Error loading values Bad Gateway
  4. Developer console info:
 
> Failed to load resource: the server responded with a status of 502 (Bad Gateway)/api/alertmanager/api/v2/silences:1
>  Failed to load resource: the server responded with a status of 502 (Bad Gateway) /api/prometheus/api/v1/rules:1

> GET https://console-openshift-console.apps-crc.testing/api/alertmanager/api/v2/silences net::ERR_ABORTED 502 (Bad Gateway)
> GET https://console-openshift-console.apps-crc.testing/api/prometheus/api/v1/rules net::ERR_ABORTED 502 (Bad Gateway)

### Expected
Monitoring to work.

### Actual
Monitoring fails with a Bad Gateway exception.

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by cfergeau** [comment]
Monitoring is disabled by default, and `crc config view` output indicates you haven't enabled it?
Have you followed the steps described at https://crc.dev/crc/#starting-monitoring-alerting-telemetry_gsg ?

**Comment by xgxtbku** [comment]
Hey.
No, but I've done it now and increased memory for the crc. Now the crc start constantly looping INFO Operator monitoring is degraded message.

**Comment by xgxtbku** [comment]
At: https://console-openshift-console.apps-crc.testing/settings/cluster/clusteroperators
Monitoring - Degraded - Failed to rollout the stack. Error: the Cluster Monitoring ConfigMap doesn't contain a 'config.yaml' key

**Comment by xgxtbku** [comment]
Also crc status now shows:
crc status
CRC VM:          Running
OpenShift:       Degraded (v4.7.18)
Disk Usage:      22.06GB of 32.74GB (Inside the CRC VM)
Cache Usage:     13.34GB
Cache Directory: /home/crcadmin/.crc/cache

**Comment by praveenkumar** [comment]
@xgxtbku did you stop and start the cluster after memory increased and enabling the monitoring or you did a clean start if not then please first try to do `crc delete` => `crc start`

**Comment by xgxtbku** [comment]
that will remove all my pods right?

**Comment by xgxtbku** [comment]
INFO Kubelet client certificate has expired, renewing it... [will take up to 8 minutes]
now this running for almost 30mins.

**Comment by xgxtbku** [comment]
now it finished the crc start
The last message was: 
DEBU monitoring operator is degraded, Reason: UpdatingTelemeterclientFailed
INFO Operator monitoring is degraded

**Comment by xgxtbku** [comment]
Started working.
The last issue I've found. I've tried to update the cluster from Administrator menu -> Administration -> Cluster Settings -> Upgrade.
Got this error:
Failing - True - 
UpgradePreconditionCheckFailedPrecondition "ClusterVersionUpgradeable" failed because of "ClusterVersionOverridesSet": Disabling ownership via cluster version overrides prevents upgrades. Please remove overrides before continuing.

How can I do this?

**Comment by praveenkumar** [comment]
@xgxtbku CRC doesn't support cluster update, we already mentioned in the documents https://crc.dev/crc/#differences-from-production-openshift-install_gsg

**Comment by praveenkumar** [comment]
Closing this issue since it is resolved.

**Comment by jhonDoe15** [comment]
facing the same issue reinstalling crc with the latest version:
```
>crc version
CodeReady Containers version: 1.35.0+751824a9
OpenShift version: 4.9.5
```

having the same monitoring bad gateway and unable to upgrade openshift version even though downloaded and installed the latest crc, trying to update from 4.9.5 to 4.9.7 assuming it would solve the monitoring bad gateway issue

**Comment by NL-TCH** [comment]
resolution: 
`crc stop` to stop the vm
`crc config set enable-cluster-monitoring true` to enable monitoring (this requires more RAM for the VM)
finally start the vm again `crc start`

verify with `crc config view`

this solved it for me
