### ISSUE TITLE
new-app from private git repo over ssh Host key verification failed.

### ISSUE THREAD

**Issue by lrhazi** [code-ready/crc#2630]
Sorry for the newbie question, but is there way to disable the host key verification?
```
PS C:\Users\lrhazi> oc new-app ssh://git@gitlab.cua.edu:2222/acct-mgmt/idp-server.git --source-secret=lrhazi-2020-key -v7
I0805 12:56:18.306832    9740 loader.go:372] Config loaded from file:  C:\Users\lrhazi\.kube\config
I0805 12:56:18.314834    9740 repository.go:450] Executing git ls-remote git@gitlab.cua.edu:2222/acct-mgmt/idp-server.git
I0805 12:56:20.066619    9740 repository.go:541] Error executing command: exit status 128
I0805 12:56:20.079906    9740 repository.go:450] Executing git ls-remote git@gitlab.cua.edu:2222/acct-mgmt/idp-server.git
I0805 12:56:20.261718    9740 repository.go:541] Error executing command: exit status 128
I0805 12:56:20.271666    9740 repository.go:450] Executing git ls-remote git@gitlab.cua.edu:2222/acct-mgmt/idp-server.git
I0805 12:56:20.449147    9740 repository.go:541] Error executing command: exit status 128
I0805 12:56:20.465226    9740 sourcelookup.go:89] could not list git remotes for ssh://git@gitlab.cua.edu:2222/acct-mgmt/idp-server.git: Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by cfergeau** [comment]
Did you try `--insecure-registry=true`?

**Comment by cfergeau** [comment]
https://docs.openshift.com/container-platform/4.8/cicd/builds/creating-build-inputs.html#builds-source-secret-ssh-key-auth_creating-build-inputs seems to have a note which might be related to this:
> Ensure that the known_hosts file includes an entry for the host of your source code.

Not sure which `known_hosts file this is about :-/

**Comment by lrhazi** [comment]
Thanks! That known_hosts reference sounded very close! but it does not seem to work. I made sure the knwon_hosts file does contain an entry for the git server.

```
PS C:\Temp> oc create secret generic lrhazi-2020-key3 --from-file=ssh-privatekey=lrhazi-Jan-2020.pem --from-file=known_hosts --type=kubernetes.io/ssh-auth
secret/lrhazi-2020-key3 created
```
```
PS C:\Temp> oc new-app ssh://git@gitlab.cua.edu:2222/acct-mgmt/idp-server.git --source-secret=lrhazi-2020-key3
error: unable to load template file "ssh://git@gitlab.cua.edu:2222/acct-mgmt/idp-server.git": the path "ssh://git@gitlab.cua.edu:2222/acct-mgmt/idp-server.git" cannot be accessed: CreateFile ssh://git@gitlab.cua.edu:2222/acct-mgmt/idp-server.git: The filename, directory name, or volume label syntax is incorrect.
error: git ls-remote failed with: Host key verification failed.
fatal: Could not read from remote repository.
```

**Comment by lrhazi** [comment]
I found out it's somehow lying to me :)
Running tcpdump on the git server I confirmed that there are no packets arriving on port 2222, while the new-app command is running!!!

**Comment by lrhazi** [comment]
Seems that even though my URL is: 
```ssh://git@gitlab.cua.edu:2222/acct-mgmt/idp-server.git```
It is trying to use port 22 instead!!!

**Comment by cfergeau** [comment]
I could not find any examples of using `new-app` with `ssh://`, maybe this is not supported? Only relatively recent documentation (ie openshift 4 based instead of openshift 3) I could find about private repos is https://www.datagenx.net/2021/01/building-openshift-app-from-private-git.html

**Comment by lrhazi** [comment]
This is what ended up working for me:
```
oc create secret generic mykey --from-file=ssh-privatekey=/home/my/.ssh/id_rsa --from-file=/home/my/.ssh/known_hosts --type=kubernetes.io/ssh-auth

oc new-app git@gitlab.cua.edu_2222:/acct-mgmt/idp-server.git --source-secret=mykey

oc edit buildconfig/idp-server

oc start-build buildconfig/idp-server
oc logs -f buildconfig/idp-server
```

But also had to make sure git/ssh will work using my key. so tweak ~/.ssh/config, accept host key...etc.

The key is realizing that "oc" calls my onw local git and ssh commands! Not openshift containers as I thought.
And the edit buildconfig was needed to set the url bask to "ssh://..."
