### ISSUE TITLE
Question around minimum requirements (macOS)

### ISSUE THREAD

**Issue by angusfz** [code-ready/crc#2635]
Try to install crc on MBP 2016 (I7, 16G ram) without success, but the same crc configuration can work properly on ec2 metal instance(c5n.mental, centos 7.9).

crc log
```
INFO 4 operators are progressing: authentication, image-registry, openshift-controller-manager, operator-lifecycle-manager-packageserver
ERRO Cluster is not ready: cluster operators are still not stable after 10m9.756444437s
INFO Waiting for the proxy configuration to be applied...
INFO Adding crc-admin and crc-developer contexts to kubeconfig...
ERRO Cannot update kubeconfig: Head "https://oauth-openshift.apps-crc.testing": Service Unavailable
```

crc status
```bash
$ crc status
CRC VM:          Running
OpenShift:       Unreachable (v4.8.2)
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     17.27GB
Cache Directory: /home/centos/.crc/cache
```

Maybe the issue is about hardware performance?
Any suggested CPU spec for running crc ?

**Comment by praveenkumar** [comment]
@angusfz what is the mac OS version on that system. Also it would be help for us if you file issue using the template for this MacOS problem you are facing.

**Comment by gbraad** [comment]
> 16G ram

This machine is what I used before to run CRC (as one of the developers), so this is certainly the specs that are possible. However, there might be other factors that can influence the performance. It would be appreciated if you can follow the issue template to gather all the needed info (hence the NEEDINFO label).

**Comment by angusfz** [comment]
Sure, will open new issue with issue template

**Comment by gbraad** [comment]
@angusfz after you have done so, please close this one
