### ISSUE TITLE
Access crc running on Win10 from WSL2

### ISSUE THREAD

**Issue by woiza** [code-ready/crc#2641]
I installed crc on Win 10 without issues and am able to access it with my browser and with PowerShell. I tried to access it using bash on my WSL2 Ubuntu VM:

```bash
~  oc login -u kubeadmin https://api.crc.testing:6443
                                                                                                                                          
error: dial tcp 127.0.0.1:6443: connect: connection refused - verify you have provided the correct host and port and that the server is currently running.
```

```PS
PS C:\codereadycontainers> crc version
CodeReady Containers version: 1.30.1+376cc3c1
OpenShift version: 4.8.2 (not embedded in executable)
````

How can I access a crc running on Win10 from Linux running in a WSL2 instance?

**Comment by gbraad** [comment]
This is a known issue with the network stack of WSL. They prevent access to services on the host or other VMs without you enabling this. https://github.com/code-ready/crc/issues/374#issuecomment-803580645

Closing as invalid as this is not a CRC issue
