### ISSUE TITLE
Have logic to dynamic create bundle split for windows msi

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#2645]
As of now we are using a kind of hard coded way to split the bundle files to accommodate it for windows msi but this is depend on bundle size so if bundle size reduced/increased then msi creation will fail. Since we don't have any CI in place to capture that on bundle bases, it is identified during the release and which make use to complete respin the release artifacts after adjusting the bundle split. It would be better if we can have a logic to dynamically handle it so we don't have to adjust it as per bundle size.

**Comment by cfergeau** [comment]
There has been some work in that area in https://github.com/anjannath/crc/commits/msi-template
