### ISSUE TITLE
[HELP Needed] The node was low on resource: ephemeral-storage.

### ISSUE THREAD

**Issue by xgxtbku** [code-ready/crc#2649]
### General information

  * OS: Linux 
  * Hypervisor:
  * Did you run `crc setup` before starting it Yes
  * Running CRC on: Baremetal-Server

## CRC version
```bash
CodeReady Containers version: 1.29.1+bc5f4409
OpenShift version: 4.7.18 (embedded in executable)
```
  
## CRC status
```bash
DEBU CodeReady Containers version: 1.29.1+bc5f4409
DEBU OpenShift version: 4.7.18 (embedded in executable)
DEBU Running 'crc status'
DEBU Checking file: /home/crcadmin/.crc/machines/crc/.crc-exist
DEBU Checking file: /home/crcadmin/.crc/machines/crc/.crc-exist
DEBU Found binary path at /home/crcadmin/.crc/bin/crc-driver-libvirt
DEBU Launching plugin server for driver libvirt
DEBU Plugin server listening at address 127.0.0.1:40319
DEBU () Calling .GetVersion
DEBU Using API Version 1
DEBU () Calling .SetConfigRaw
DEBU () Calling .GetMachineName
DEBU (crc) Calling .GetState
DEBU (crc) DBG | time="2021-08-16T12:31:00+02:00" level=debug msg="Getting current state..."
DEBU (crc) DBG | time="2021-08-16T12:31:00+02:00" level=debug msg="Fetching VM..."
DEBU (crc) Calling .GetBundleName
DEBU Running SSH command: df -B1 --output=size,used,target /sysroot | tail -1
DEBU Using ssh private keys: [/home/crcadmin/.crc/machines/crc/id_ecdsa /home/crcadmin/.crc/cache/crc_libvirt_4.7.18/id_ecdsa_crc]
DEBU SSH command results: err: <nil>, output: 32737570816 27358097408 /sysroot
DEBU network operator is degraded, Reason: RolloutHung
DEBU network operator is still progressing, Reason: Deploying
DEBU Making call to close driver server
DEBU (crc) Calling .Close
DEBU Successfully made call to close driver server
DEBU Making call to close connection to plugin binary
CRC VM:          Running
OpenShift:       Starting (v4.7.18)
Disk Usage:      27.36GB of 32.74GB (Inside the CRC VM)
Cache Usage:     13.34GB
Cache Directory: /home/crcadmin/.crc/cache
```

## CRC config
```bash
    - consent-telemetry                     : yes
    - enable-cluster-monitoring             : true
    - memory                                : 20480
    - network-mode                          : user
    - skip-check-network-manager-installed  : true
    - skip-check-network-manager-running    : true
```

## Host Operating System
```bash
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### Steps to reproduce

  1. Opening CRC console
  2. Go to Administrator menu -> Workloads -> Pods
  3. Most of my Pods got Evicted
  Some of the Events:
  - The node had condition: [DiskPressure].
  - The node was low on resource: ephemeral-storage. Container rabbitmq was using 56Ki, which exceeds its request of 0.
  - The node was low on resource: ephemeral-storage. Container download-server was using 823816Ki, which exceeds its request of 0.
  
 Most of the issues looks like this ephemeral-storage issue.

This seems to be an issue with the Disk usage. How can I fix it? (please help with a step by step guide)
Also is there a way to set an auto Disk freeup/cleanup to avoid this cases?

**Comment by praveenkumar** [comment]
@xgxtbku As per `crc status` looks like you have consumed most of disk space `Disk Usage:      27.36GB of 32.74GB (Inside the CRC VM)`. if you need to extend you disk for the VM then better to stop the cluster set the higher disk space using `crc config set disk-size 50` which will extend it to 50GB and then start the cluster again.

**Comment by xgxtbku** [comment]
@praveenkumar does it free the space up if its not needed? Or the 50GB will get filled up soon. I don't want to add any more pods/nodes to the setup.

**Comment by praveenkumar** [comment]
> does it free the space up if its not needed? Or the 50GB will get filled up soon. I don't want to add any more pods/nodes to the setup.

@xgxtbku It doesn't free up the space but add 20GB more so that cluster doesn't complain about disk pressure, if you are sure that you don't have any pod  then just use `35` instead `50`

**Comment by xgxtbku** [comment]
@praveenkumar thanks. :)
