### ISSUE TITLE
dial tcp: lookup api.crc.testing: no such host - verify you have provided the correct host and port and that the server is currently running.

### ISSUE THREAD

**Issue by PrathibaAB** [code-ready/crc#2654]
### General information

  * OS:  Windows
  * Hypervisor: Hyper-V 
  * Did you run `crc setup` before starting it (Yes)
  * Running CRC on: Laptop

## CRC version
CodeReady Containers version: 1.26.0+31f06c09
OpenShift version: 4.7.8 (embedded in executable)

  
## CRC status
<img width="796" alt="crc status --log-level debug" src="https://user-images.githubusercontent.com/61728676/129843693-2b971755-b0da-485f-85b4-fbea3d40dc8b.png">

## CRC config
![image](https://user-images.githubusercontent.com/61728676/129843818-748912c0-5245-43b0-a5eb-0b221885d3f5.png)

## Host Operating System
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19043 N/A Build 19043
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
System Manufacturer:       LENOVO
System Model:              20MVS16C05
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 23 Model 17 Stepping 0 AuthenticAMD ~2000 Mhz
BIOS Version:              LENOVO R0WET56W (1.24 ), 28-06-2019
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
Total Physical Memory:     31,620 MB
Available Physical Memory: 24,243 MB
Virtual Memory: Max Size:  36,228 MB
Virtual Memory: Available: 27,127 MB
Virtual Memory: In Use:    9,101 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-743302K
Hotfix(s):                 10 Hotfix(s) Installed.
                           [01]: KB4601050
                           [02]: KB4562830
                           [03]: KB4577586
                           [04]: KB4580325
                           [05]: KB4589212
                           [06]: KB4593175
                           [07]: KB4598481
                           [08]: KB5000736
                           [09]: KB5005033
                           [10]: KB5005260
Network Card(s):          
                           [05]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (Default Switch)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 172.26.32.1
                                 [02]: fe80::f5fe:e127:e5ff:6ee9
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

### Steps to reproduce

  1. crc setup
  2.  crc start -p pull-secret --nameserver 8.8.8.8
  3. oc login -u developer -p developer https://api.crc.testing:6443

### Expected
successfully login and display the Projects 

### Actual
![image](https://user-images.githubusercontent.com/61728676/129865582-69a403f5-5979-4fc9-a0ed-545c3bb5fbf1.png)

out of 10 , 8 attempts are failed .

### Logs
log file for crc start --log-level 
https://gist.github.com/PrathibaAB/6adedc1f82aafd397cf8280587662195

**Comment by praveenkumar** [comment]
@PrathibaAB Can you please use issue template and fill all the details when creating the issue with this info we are not able to debug the error.

**Comment by gbraad** [comment]
> withOUT this info we are not able to debug the error.

this means, please also include the detailed debug log output.

**Comment by PrathibaAB** [comment]
Please check i have added details about issue

**Comment by praveenkumar** [comment]
@PrathibaAB As per logs shared here https://gist.github.com/PrathibaAB/6adedc1f82aafd397cf8280587662195 looks like cluster started successfully. Can you put output of `crc status --log-level debug` after that, it might be server is reconciling?

**Comment by PrathibaAB** [comment]
C:\Users\PrathibaAB>oc login -u developer -p developer https://api.crc.testing:6443
Login successful.

Error from server (ServiceUnavailable): the server is currently unable to handle the request (get projects.project.openshift.io)

C:\Users\PrathibaAB>crc status --log-level debug
DEBU CodeReady Containers version: 1.26.0+31f06c09
DEBU OpenShift version: 4.7.8 (embedded in executable)
DEBU Running 'crc status'
DEBU Checking file: C:\Users\PrathibaAB\.crc\machines\crc\.crc-exist
DEBU Checking file: C:\Users\PrathibaAB\.crc\machines\crc\.crc-exist
DEBU [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM crc ).state
                   ] : Running
DEBU [stderr =====>] :
DEBU [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM crc ).state
                   ] : Running
DEBU [stderr =====>] :
DEBU [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM crc ).networkadapters[0]).ipaddresses[0]
             =====>] : 172.31.46.209
DEBU [stderr =====>] :
DEBU Running SSH command: df -B1 --output=size,used,target /sysroot | tail -1
DEBU Using ssh private keys: [C:\Users\PrathibaAB\.crc\machines\crc\id_ecdsa C:\Users\PrathibaAB\.crc\cache\crc_hyperv_4.7.8\id_ecdsa_crc]
DEBU SSH command results: err: <nil>, output: 32737570816 15112474624 /sysroot
DEBU Running SSH command: <hidden>
DEBU SSH command succeeded
DEBU Unexpected operator status for network: ManagementStateDegraded
DEBU openshift-apiserver operator not available, Reason: APIServices_Error
CRC VM:          Running
OpenShift:       Stopped (v4.7.8)
Disk Usage:      15.11GB of 32.74GB (Inside the CRC VM)
Cache Usage:     14.53GB
Cache Directory: C:\Users\PrathibaAB\.crc\cache

**Comment by praveenkumar** [comment]
@PrathibaAB This really like an issue with IO may be your host has old hardware or it is low on resources. We did see something like on nested virtualization setup.

**Comment by PrathibaAB** [comment]
how can i resolve  issue with IO may be your host has old hardware or it is low on resources ?
