### ISSUE TITLE
Review configs around version variables

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/crc#2656]
Currently this variable is used to set the default network mode on macos:

https://github.com/code-ready/crc/blob/e50d8813a5570eeb924742c4bd1ea472f09222a6/pkg/crc/config/settings.go#L124

In the past when two different distributables for macos with different defaults networking modes, that variable make sense, now there is only one default mode for networking on macos so probably this should not be dependent on this variable.

One of the issues with this variable appears on integration tests, which make use of machine Client class, so this means integration tests should be build with `macosInstallPath` set.

**Comment by adrianriobo** [comment]
Just find out same can be applied on `windows` to variable `msiBuild`

https://github.com/code-ready/crc/blob/e50d8813a5570eeb924742c4bd1ea472f09222a6/pkg/crc/version/version.go#L28

**Comment by cfergeau** [comment]
Couple of thoughts/questions on this:
- any reasons the integration test Makefile target does not set this variable? (not necessarily the best long term solution, but could help for now)
- I started https://github.com/cfergeau/crc/tree/deadcode to rework the code around `msiBuild`, `macosInstallPath`, ... I think it should not be too hard to replace `macosInstallPath` with just a boolean (the same as on Windows), and to default to this boolean being true, we'd require its value to be changed when building from source (just thinking out loud for now though :)
- at this point, I think we can bite the bullet and just change the default networking mode for all platforms, not have some installer/not installer special casing in `defaultNetworkMode`. Everything that we hand out to our customers should be able to deal with usermode networking now (macOS and Windows through their respective installers, linux through vsock socket activation of the daemon)

**Comment by adrianriobo** [comment]
> any reasons the integration test Makefile target does not set this variable? (not necessarily the best long term solution, but could help for now)

Well right now integration goal on Makefile only run tests and does not distinguish on platforms...I am working towards build the integration container which will hold the integration binary , at that point if still existing may make more sense to add those. Otherwise as you said is not a long term solution so I wouild prefer no add nothing about this right now. 
Instead I am doing that customization manually before running those tests, not best option but is short term solution.

> I started https://github.com/cfergeau/crc/tree/deadcode to rework the code around msiBuild, macosInstallPath, ... I think it should not be too hard to replace macosInstallPath with just a boolean (the same as on Windows), and to default to this boolean being true, we'd require its value to be changed when building from source (just thinking out loud for now though :)

At fisrst thought seems fine to me

> at this point, I think we can bite the bullet and just change the default networking mode for all platforms, not have some installer/not installer special casing in defaultNetworkMode. Everything that we hand out to our customers should be able to deal with usermode networking now (macOS and Windows through their respective installers, linux through vsock socket activation of the daemon)

Interesting I was not aware of the route to change the default network mode on Linux as well.. Does this have a expected plannification to take actions on it?
