### ISSUE TITLE
[BUG] Mac OS installer fails to provide runnable CRC

### ISSUE THREAD

**Issue by bentito** [code-ready/crc#2662]
### General information

  * OS: macOS
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it (Yes/No)? No
  * Running CRC on: Laptop

## CRC version
```bash
CodeReady Containers version: 1.31.2+19538dab
OpenShift version: 4.8.4 (not embedded in executable)
```
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
```

## CRC config
```bash
# Put `crc config view` output here
```

## Host Operating System
```bash
ProductName:	macOS
ProductVersion:	11.5.2
BuildVersion:	20G95
```

### Steps to reproduce

1. Stop CRC task bar item;
2. Run installer;
3. Start CRC task bar item;

### Expected

CRC will start.

### Actual

CRC fails to start with an error like:
<img width="315" alt="image" src="https://user-images.githubusercontent.com/4449199/130118345-d39b89ee-2ebb-447d-9ec9-7b0bd7b0c908.png">

The following steps are actually needed to start as expected:

• Stop CRC task bar item;
• Run installer;
• issue crc delete from CLI;
• Start CRC task bar item;
• Start CRC from task bar

**Comment by cfergeau** [comment]
>  • issue crc delete from CLI;

This should be doable from the task bar item? Or does it fail to start after upgrade?
This error message needs to be improved to be useful to the user, but what it's saying is that crc instances created with previous crc versions unfortunately cannot be used with newer crc versions. Since deleting a crc instance is a data loss operation, crc cannot do it automatically. But the tray could ask whether to do it, with an explanation. Or even better, the installer could check for this before doing the upgrade.

**Comment by bentito** [comment]
It’s kind of a chicken and egg scenario. The installer won’t run with the tray running. Quit tray. Run installer. Tray can’t start now due to error above. Must do delete via CLI. Perhaps the installer should just tell users to do this at the end of a successful install, for now.

**Comment by cfergeau** [comment]
If the tray fails to start, that's a bug. I'd expect the error to only be shown when clicking "Start" in the tray menu.

**Comment by bentito** [comment]
Okay bug then, I'll try to document on my next go-round with the installer. But the installer makes you quit the tray to run the installer. If it's supposed to start it for you, post-install, it's not, in my environment.

**Comment by bentito** [comment]
Here's some further documentation of the problem from the most recent 1.32.1 CRC release: 
If you are running the CRC already, the CRC installer commands you to quit it (and quits itself):
<img width="270" alt="image" src="https://user-images.githubusercontent.com/4449199/133473748-0d227b78-882b-4f91-8462-10f2e994fa16.png">
Then you go find the installer package wherever you downloaded it, run it again, and it installs without issue. At which point you try to start a cluster using the tray, and you get:
<img width="263" alt="image" src="https://user-images.githubusercontent.com/4449199/133473935-48172ff3-2140-4b23-bafc-5b21559db982.png">
By now you've learned from painful experience that the way around this is to head off to the CLI to issue: `crc delete`. At which point you can start a cluster from the tray without issue.

**Comment by gbraad** [comment]
it is not elegant, but the quickest fix we can do for now. this also affects CLI and Windows.
We will look into this
