### ISSUE TITLE
How can I delete operator images during development?

### ISSUE THREAD

**Issue by bobbygryzynger** [code-ready/crc#2670]
I'm developing an operator using `crc` and https://sdk.operatorframework.io. I am able to deploy the operator to the cluster and successfully test it. But, when I try to remove the operator and reinstall it, the operator image that gets pulled is always the one cached on the cluster. 

I am using `make deploy` (as described here: https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#2-run-as-a-deployment-inside-the-cluster) to deploy the image and I am following the advice listed here for removing the operator: https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#cleanup

The only workaround I've found is to tag a new image of the operator each time I need to test an update, but this ends up being cumbersome for development when what I would like to be able to do is use a `<registry>/<repo>:latest` tag during development and keep pushing updates to it. 

Is there any way to delete the locally stored operator image in order to force a fresh image pull? Or is there any other way of ensuring that I pull a new image from my registry when I make updates?

Thanks for the great tool and any advice you can provide.

**Comment by bobbygryzynger** [comment]
Thanks @anjannath I am in fact seeing that behavior. Nonetheless, is there any mechanism available for removing operator images in `crc` when not using a `:latest` tag

**Comment by praveenkumar** [comment]
@bobbygryzynger Can you change the deployment of that operator and set the container image policy to `Always` even it is not `latest` tagged?

**Comment by bobbygryzynger** [comment]
Thanks @praveenkumar, for my purposes, these two options work well enough. Either using a `latest` tag or changing the deployment's image pull policy to `Always` work to get me the latest version of my operator's image.
