### ISSUE TITLE
[Known Issue] kubeadmin/developer user login failed when cert is expired and rotated automatic

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#2671]
If a user using 1.30.1 release of crc then cert of the bundle already expired and recovery is working as expected but after the start process complete and user try to login to cluster, following error happen

```
$ oc login -u kubeadmin -p AEJ7z-trsoy-EqQZS-ArzvC https://api.crc.testing:6443
Login failed (401 Unauthorized)
```

This is happen because of https://bugzilla.redhat.com/show_bug.cgi?id=1978193 and patch merged for 4.9 side but not on 4.8 side so as a workaround after user have the cluster the first thing he/she need to do is delete the auth csr.

```
$ oc --kubeconfig=$HOME/.crc/machine/crc/kubeconfig delete csr system:openshift:openshift-authenticator
```

**Comment by rootmadhu** [comment]
Hi Praveen,

I am unable to delete the csr when the kubeadmin user stopped working. How to recover from this stage. Its the latest crc 4.9.10.
[crc@localhost ~]$ oc whoami
Error from server (Forbidden): users.user.openshift.io "~" is forbidden: User "system:anonymous" cannot get resource "users" in API group "user.openshift.io" at the cluster scope
[crc@localhost ~]$ oc delete secret -n openshift-oauth-apiserver openshift-authenticator-certs
Error from server (Forbidden): secrets "openshift-authenticator-certs" is forbidden: User "system:anonymous" cannot delete resource "secrets" in API group "" in the namespace "openshift-oauth-apiserver"
[crc@localhost ~]$ crc status
CRC VM:          Running
OpenShift:       Running (v4.9.10)
Disk Usage:      15.87GB of 32.74GB (Inside the CRC VM)
Cache Usage:     15.65GB
Cache Directory: /home/crc/.crc/cache

Regards
Madhu

**Comment by gbraad** [comment]
> kubeadmin user stopped working

This issue has been closed and is unrelated as this was a blocker issue for a release. Information is missing... Please file a new issue.
