### ISSUE TITLE
[BUG] `crc delete` warning

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#2676]
With crc 1.31.2, run `crc delete` after a successful `crc start`:
```
$ ./crc  delete
Do you want to delete the OpenShift cluster? [y/N]: y
WARN open /home/teuf/.crc/machines/crc/kubeconfig: no such file or directory 
Deleted the OpenShift cluster
```
The `kubeconfig` warning is unexpected, did not check where it's coming from.

**Comment by praveenkumar** [comment]
@cfergeau this should be coming when we are clearing the crc cluster entry of kubeconfig file and you might be getting it because you have `KUBECONFIG` variable set to `/home/teuf/.crc/machines/crc/kubeconfig` which is deleted as soon as delete hits.

**Comment by cfergeau** [comment]
Very good guess, this is indeed the issue :)
