### ISSUE TITLE
[win] Set VM start policy so that it's not automatically started after a host reboot

### ISSUE THREAD

**Issue by izderadicka** [code-ready/crc#2678]
### General information

  * OS:  Windows
  * Hypervisor: Hyper-V 
  * Did you run `crc setup` before starting it (Yes/No)? YES
  * Running CRC on: Laptop 

## CRC version
```bash
crc version
CodeReady Containers version: 1.31.2+19538dab
OpenShift version: 4.8.4 (not embedded in executable)
```
  
## CRC status
```bash
crc status --log-level debug
DEBU CodeReady Containers version: 1.31.2+19538dab
DEBU OpenShift version: 4.8.4 (not embedded in executable)
DEBU Running 'crc status'
DEBU Checking file: C:\Users\AAUser\.crc\machines\crc\.crc-exist
DEBU Checking file: C:\Users\AAUser\.crc\machines\crc\.crc-exist
DEBU Running '( Hyper-V\Get-VM crc ).state'
DEBU Running SSH command: df -B1 --output=size,used,target /sysroot | tail -1
DEBU Using ssh private keys: [C:\Users\AAUser\.crc\machines\crc\id_ecdsa C:\Users\AAUser\.crc\cache\crc_hyperv_4.8.4\id_ecdsa_crc]
DEBU SSH command results: err: ssh: handshake failed: read tcp 127.0.0.1:50482->127.0.0.1:2222: wsarecv: An existing connection was forcibly closed by the remote host., output:
DEBU Cannot get root partition usage: ssh command error:
command : df -B1 --output=size,used,target /sysroot | tail -1
err     : ssh: handshake failed: read tcp 127.0.0.1:50482->127.0.0.1:2222: wsarecv: An existing connection was forcibly closed by the remote host.\n
DEBU cannot get OpenShift status: Get "https://api.crc.testing:6443/apis/config.openshift.io/v1/clusteroperators": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
CRC VM:          Running
OpenShift:       Unreachable (v4.8.4)
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     14.38GB
Cache Directory: C:\Users\AAUser\.crc\cache
```

## CRC config
```bash
crc config view
- consent-telemetry                     : no
```

## Host Operating System
```bash
Host Name:                 DESKTOP-******
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19043 N/A Build 19043
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          ******
Registered Organization:   ******
Product ID:               ***********
Original Install Date:     02.08.2021, 19:23:46
System Boot Time:          28.08.2021, 9:03:40
System Manufacturer:       LENOVO
System Model:              20UES1351L
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 23 Model 96 Stepping 1 AuthenticAMD ~1700 Mhz
BIOS Version:              LENOVO R1BET36W(1.05 ), 11.06.2020
Windows Directory:         C:\windows
System Directory:          C:\windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague
Total Physical Memory:     31 976 MB
Available Physical Memory: 12 481 MB
Virtual Memory: Max Size:  36 584 MB
Virtual Memory: Available: 15 410 MB
Virtual Memory: In Use:    21 174 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-FU0TMB8
Hotfix(s):                 9 Hotfix(s) Installed.
                           [01]: KB4601050
                           [02]: KB4562830
                           [03]: KB4570334
                           [04]: KB4577266
                           [05]: KB4580325
                           [06]: KB4586864
                           [07]: KB5000736
                           [08]: KB5005033
                           [09]: KB5005260
Network Card(s):           8 NIC(s) Installed.
                           [01]: Realtek PCIe GbE Family Controller
                                 Connection Name: Ethernet 2
                                 Status:          Media disconnected
                           [02]: Intel(R) Wi-Fi 6 AX200 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.86
                                 [02]: fe80::8875:b2e0:e0bd:3a58
                           [03]: Realtek PCIe GbE Family Controller
                                 Connection Name: Ethernet 3
                                 Status:          Media disconnected
                           [04]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [05]: Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows x64
                                 Connection Name: Ethernet 4
                                 Status:          Hardware not present
                           [06]: Lenovo USB Ethernet
                                 Connection Name: Ethernet 5
                                 Status:          Media disconnected
                           [07]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (Default Switch)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 172.23.224.1
                                 [02]: fe80::5c08:e5ce:3060:e73
                           [08]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (WSL)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 172.28.240.1
                                 [02]: fe80::902a:a4d0:c921:cf0e
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```

### Steps to reproduce

  1.  Installed and setup and run CRC without problem for couple of days
  2. My PC rebooted to install some Win updates
  3. After reboot:
    - crc VM was running
    - but I cannot connect to web console and api console (connection reset)
  4. I shut down VM, and tried `crc start`  - it got stuck on `CodeReady Containers instance is running with IP 127.0.0.1` , in debug it can be seen that crc is trying to ssh to VM and connection was closed.
  5. I tried to reboot whole computer several times - same problem

### Expected
CRC to work after reboot

### Actual
Fails to start after reboot -   I think it has to do something with network configuration,
from crc start debug log I can see that it is using Default Hyper-V virtual switch.   What I saw in past that this switch does not have fixed IP range, but it changes after boot (I guess to avoid conflicts with local networks and VPNs, but I saw changes also when I reboot on same network).   
crc is using 127.0.0.1 to comunicate with VM (I guess there is some port forwading set up) -  and VM after restart migh have different IP - so it'll not work? Just guessing.

Here is debug log for `crc start`  : https://gist.github.com/izderadicka/233b1fce9385f223ff688bf16301e3e1

I do not want to delete now, as I have there some work I'd like to save -  is there any way how to fix the network setup only??

**Comment by guillaumerose** [comment]
Is the tray or crc daemon running? It must run to get functional networking.

**Comment by izderadicka** [comment]
@guillaumerose 

Yes tray is running - this is the log shown in tray app:
```
Checking if running in a shell with administrator rights
Checking Windows 10 release
Checking Windows edition
Checking if Hyper-V is installed and operational
Checking if crc-users group exists
Checking if current user is in Hyper-V Admins group
Checking if Hyper-V service is enabled
Checking if the Hyper-V virtual switch exists
Found Virtual Switch to use: Default Switch
Checking if vsock is correctly configured
listening vsock://00000400-FACB-11E6-BD58-64006A7986D3
listening \\.\pipe\crc-http
```

**Comment by gbraad** [comment]
> I do not want to delete now, as I have there some work I'd like to save

If you didn't perform a clean shutdown, it might be possible the virtual disk is corrupted.

> ssh: handshake failed: read tcp 127.0.0.1:50482->127.0.0.1:2222:

n recent releases of CRc we moved from the Virtual Switch setup to using a usermode network stack. This means you get some ports assigned on localhost that point to the VM. Hence you see 127.0.0.1 now and no 'Virtual Switch' reference.

Can you share a screenshot of the Hyper-V manager for the CRC machine? It might be able to show if the VM actually started or not.

**Comment by izderadicka** [comment]
@gbraad 

I actually went through delete, clean and setup steps -   the CRC was working then as expected. But I think I can easily simulate the problem if I just restart the PC without stopping CRC.   After reboot I'm basically in same situation, which is:
1) VM is running
![image](https://user-images.githubusercontent.com/2185733/131246432-47f1b385-396e-42c3-8600-a81eacde965d.png)

2) But I cannot connect to VM - neither web console, oc console, nor crc stop is working (as it first tries to ssh to machine to stop kubelet:
```
crc stop --log-level debug
DEBU CodeReady Containers version: 1.31.2+19538dab
DEBU OpenShift version: 4.8.4 (not embedded in executable)
DEBU Running 'crc stop'
DEBU Checking file: C:\Users\ZZ0734668\.crc\machines\crc\.crc-exist
INFO Stopping kubelet and all containers...
DEBU Using root access: Executing systemctl stop kubelet
DEBU Running SSH command: sudo systemctl stop kubelet
DEBU Using ssh private keys: [C:\Users\ZZ0734668\.crc\machines\crc\id_ecdsa]
DEBU SSH command results: err: dial tcp 127.0.0.1:2222: connectex: No connection could be made because the target machine actively refused it., output:
Executing systemctl action failed:  ssh command error:
command : sudo systemctl stop kubelet
err     : dial tcp 127.0.0.1:2222: connectex: No connection could be made because the target machine actively refused it.\n:
```
Thank to your notion about user mode  network, I got some clue.
Before reboot I noticed that ports 2222, 443, 6443, 80  are served by `crc.exe daemon -watchdog` process.   After reboot this process is running (together with other two processes):
```
Get-Process | Select-Object -Property ProcessName,Id, HasExited, Responding | select-string "crc"


@{ProcessName=crc; Id=7420; HasExited=False; Responding=True}
@{ProcessName=crc-admin-helper-windows; Id=5940; HasExited=; Responding=True}
@{ProcessName=crc-tray; Id=5844; HasExited=False; Responding=True}
```
However crc daemon is not listening on those ports (I checked with `Get-NetTCPConnection -State Listen | Select-Object -Property LocalAddress,LocalPort,@{'Name' = 'ProcessName';'Expression'={(Get-Process -Id $_.OwningProcess).Name}}` - these ports 2222, etc are not being listen on.

Just killing and restarting crc daemon did not help.  I needed to:
- stop manually  VM in Hyper-V console.
- run again `crc start` -  then VM is started and `crc daemon` starts to listen on ports 2222, 443 ....

My problem was that not every time `crc start` was successful after reboot (and manual stop of VM)-     I have tried couple of time and after some reboots it never started to communicate with VM (though VM was started) -  failed that it cannot run ssh on localhost:2222 (as can be seen - in previous logs).   I'm guessing that in that case crc daemon did not open tunnel for ssh on 2222? But do not know why.

Maybe problem was with state of VM machine?   It was true that for one of problematic reboots I have found in windows logs that  "kernel was rebooted without shutting down", which can lead to problems.  However other demonstration of the problem  (cannot start after reboot and manually stopping crc VM) was after normal reboot (with crc running).

**Comment by gbraad** [comment]
> But I think I can easily simulate the problem if I just restart the PC without stopping CRC.

With earlier versions of OCP it was not such a big problem, but we noticed in some tests with 4.8 that a forced stop could cause a corrupted fikesystem. Maybe we are hitting this?

**Comment by gbraad** [comment]
@praveenkumar did we record an issue for that behavior? We might need to add a known issue?

We will try to repro this.
For now, please stop cleanly... And prevent disk full, as someone else also reported this can cause a similar issue.

**Comment by praveenkumar** [comment]
> @praveenkumar did we record an issue for that behavior? We might need to add a known issue?

It was https://bugzilla.redhat.com/show_bug.cgi?id=1975078 on 4.8 side.

**Comment by gbraad** [comment]
Is this a scenario we can somehow try to repro ? /cc: @adrianriobo

**Comment by iampathat** [comment]
I also have the some issue and solved it like izderadicka. I have to take 'shut down' (take some time) in Hyper-V on the VM to get it working again if i am not doing a proper crc close. After doing the shut down on vm then 'crc start' works as expected again. And sure it's easy to repro, just close your computer without doing a crc stop.

**Comment by gbraad** [comment]
> repro

as in an automated test ;-). Reboots or shutdowns are tests that take more time to setup

**Comment by praveenkumar** [comment]
We also need to figure out if this is only 4.8 version which causing the issue or older `4.7` one also?

**Comment by adrianriobo** [comment]
> Is this a scenario we can somehow try to repro

This is possible, but it will require change a little bit the logic on testing, as then tests should run from outside of the target host to be able to control the reboot during the testing flow... I will add an issue to prioritize this

**Comment by gbraad** [comment]
Interesting to note:

![image](https://user-images.githubusercontent.com/1894/134322469-2e485a52-3fbf-4f6e-bf44-fe420545a95b.png)

... seems there is a stop action defined, and we might also wanna disable checkpoints.

**Comment by gbraad** [comment]
Maybe this is also what is behind the problem: https://github.com/code-ready/crc/issues/2791

We still need to fix the start policy for sure, as the unclean shutdown and restart on boot is not good.
