### ISSUE TITLE
Is CodeReady Containers tray application running? Cannot reach daemon API: Get "http://unix/api/version": open \\.\pipe\crc-http: The system cannot find the file specified.[BUG]

### ISSUE THREAD

**Issue by robin0141** [code-ready/crc#2679]
### General information

  * OS: Linux / macOS / Windows :Windows
  * Hypervisor: KVM / Hyper-V / hyperkit
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop / Baremetal-Server / VM :Laptop

## CRC version
```bash
# Put `crc version` output here
CodeReady Containers version: 1.31.2+19538dab
OpenShift version: 4.8.4 (not embedded in executable)
```
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
```
DEBU CodeReady Containers version: 1.31.2+19538dab
DEBU OpenShift version: 4.8.4 (not embedded in executable)
DEBU Running 'crc status'
DEBU Checking file: C:\Users\VersaFile\.crc\machines\crc\.crc-exist
DEBU Running '(Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion" -Name ReleaseId).ReleaseId'
DEBU Running '(Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion").EditionID'
Machine does not exist. Use 'crc start' to create it
## CRC config
```bash
# Put `crc config view` output here
```
PS C:\Users\Ve> crc config view
- consent-telemetry                     : yes

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```

Host Name:                 LAPTOP-V0
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.19042 N/A Build 19042
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          rob
Registered Organization:   N/A
Product ID:                00325-81747-49996-AAOEM
Original Install Date:     24/03/2021, 18:56:16
System Boot Time:          28/08/2021, 12:32:58
System Manufacturer:       LENOVO
System Model:              81Y6
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 165 Stepping 2 GenuineIntel ~2592 Mhz
BIOS Version:              LENOVO EFCN33WW, 29/05/2020
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     16,292 MB
Available Physical Memory: 11,308 MB
Virtual Memory: Max Size:  36,772 MB
Virtual Memory: Available: 29,774 MB
Virtual Memory: In Use:    6,998 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\LAPTOP-V0H
Hotfix(s):                 7 Hotfix(s) Installed.
                           [01]: KB5004331
                           [02]: KB4562830
                           [03]: KB4577586
                           [04]: KB4580325
                           [05]: KB4589212
                           [06]: KB5005033
                           [07]: KB5005260
Network Card(s):           7 NIC(s) Installed.
                           [01]: TAP-Windows Adapter V9
                                 Connection Name: Ethernet 2
                                 Status:          Media disconnected
                           [02]: Intel(R) Wi-Fi 6 AX201 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.0.1
                                 IP address(es)
                                 [01]: 192.168.0.56
                                 [02]: fe80::1156:cfde:8fa:6c61
                                 [03]: 2607:9880:1868:c9:9d82:c15a:dcd7:cffe
                                 [04]: 2607:9880:1868:c9:1156:cfde:8fa:6c61
                                 [05]: 2607:9880:1868:c9::d8c9
                           [03]: Realtek PCIe GbE Family Controller
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [04]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [05]: ExpressVPN Wintun Driver
                                 Connection Name: Local Area Connection
                                 Status:          Media disconnected
                           [06]: ExpressVPN TAP Adapter
                                 Connection Name: Ethernet 6
                                 Status:          Hardware not present
                           [07]: LogMeIn Hamachi Virtual Ethernet Adapter
                                 Connection Name: Hamachi
                                 Status:          Hardware not present
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

### Steps to reproduce

  1. Crc setup 
  2. crc start gives below error
  3. Is CodeReady Containers tray application running? Cannot reach daemon API: Get "http://unix/api/version": open \\.\pipe\crc-http: The system cannot find the file specified.
  4. 

### Actual
Is CodeReady Containers tray application running? Cannot reach daemon API: Get "http://unix/api/version": open \\.\pipe\crc-http: The system cannot find the file specified.

### Logs
PS C:\Users\Ve> crc start --log-level debug
DEBU CodeReady Containers version: 1.31.2+19538dab
DEBU OpenShift version: 4.8.4 (not embedded in executable)
DEBU Running 'crc start'
DEBU Total memory of system is 17083187200 bytes
DEBU No new version available. The latest version is 1.31.2
DEBU Running '(Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion" -Name ReleaseId).ReleaseId'
DEBU Running '(Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion").EditionID'
Is CodeReady Containers tray application running? Cannot reach daemon API: Get "http://unix/api/version": open \\.\pipe\crc-http: The system cannot find the file specified.

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by anjannath** [comment]
> Host Name: LAPTOP-V0
OS Name: Microsoft Windows 10 Home
OS Version: 10.0.19042 N/A Build 19042

@robin0141 crc cannot be run on window 10 Home edition since hyper-v is not present there. [doc](https://crc.dev/crc/#_microsoft_windows)

Similar to #2666

**Comment by gbraad** [comment]
Best to not allow the setup to run on Home
