### ISSUE TITLE
crcVersion: 1.29.1 : Getting issue Failed to renew TLS certificates

### ISSUE THREAD

**Issue by rupeshad81** [code-ready/crc#2683]
Hi,

While installing the crc version 1.29.1 , getting below issue:
```
[crc@eaas-crc ~]$ crc start --cpus 12 --memory 40000 --pull-secret-file /tmp/pullsecret.json
WARN A new version (1.31.2) has been published on https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/crc/1.31.2/crc-linux-amd64.tar.xz
INFO Checking if running as non-root
INFO Checking if running inside WSL2
INFO Checking if crc-admin-helper executable is cached
INFO Checking for obsolete admin-helper executable
INFO Checking if running on a supported CPU architecture
INFO Checking minimum RAM requirements
INFO Checking if Virtualization is enabled
INFO Checking if KVM is enabled
INFO Checking if libvirt is installed
INFO Checking if user is part of libvirt group
INFO Checking if active user/process is currently part of the libvirt group
INFO Checking if libvirt daemon is running
INFO Checking if a supported libvirt version is installed
INFO Checking if crc-driver-libvirt is installed
INFO Checking if systemd-networkd is running
INFO Checking if NetworkManager is installed
INFO Checking if NetworkManager service is running
INFO Checking if /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf exists
INFO Checking if /etc/NetworkManager/dnsmasq.d/crc.conf exists
INFO Checking if libvirt 'crc' network is available
INFO Checking if libvirt 'crc' network is active
INFO Loading bundle: crc_libvirt_4.7.18...
INFO Creating CodeReady Containers VM for OpenShift 4.7.18...
INFO Generating new SSH Key pair...
INFO Generating new password for the kubeadmin user
INFO Starting CodeReady Containers VM for OpenShift 4.7.18...
INFO CodeReady Containers instance is running with IP 192.168.130.11
INFO CodeReady Containers VM is running
INFO Updating authorized keys...
INFO Check internal and public DNS query...
INFO Check DNS query from host...
INFO Adding user's pull secret to instance disk...
INFO Adding proxy configuration to kubelet and crio service...
INFO Verifying validity of the kubelet certificates...
INFO Starting OpenShift kubelet service
INFO Kubelet client certificate has expired, renewing it... [will take up to 8 minutes]
INFO Kubelet serving certificate has expired, waiting for automatic renewal... [will take up to 8 minutes]
Failed to renew TLS certificates: please check if a newer CodeReady Containers release is available: Temporary error: certificate /var/lib/kubelet/pki/kubelet-server-current.pem still expired (x8)


[crc@eaas-crc ~]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.8 (Maipo)
[crc@eaas-crc ~]$ crc version
WARN A new version (1.31.2) has been published on https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/crc/1.31.2/crc-linux-amd64.tar.xz
CodeReady Containers version: 1.29.1+bc5f4409
OpenShift version: 4.7.18 (embedded in executable)
```

**Comment by gbraad** [comment]
Please use CRC 1.31.2 before filing an issue. Older versions of CRC aren't supported.

Note; bundles will have to renew certificates 30 after they have been released. This is a necessity and adds to the startup time. For some releases of the bundle this process can not be performed as this is not a scenario that is actually supported for a single node cluster setup.

**Comment by gbraad** [comment]
Note: If another issue is filed without, following the issue template it will be marked as invalid and immediately closed.

**Comment by rupeshad81** [comment]
Hi,

But CRC 1.31.2  is not stable for RHEL 7 or 8 , as per the Redhat.

So installing this version, Please provide the proper certificate.

Thanks

**Comment by gbraad** [comment]
> But CRC 1.31.2 is not stable for RHEL 7 or 8 , as per the Redhat.

Who says? This works on RHEL 7.9 and 8.4, as tested by us.

>  Please provide the proper certificate.

Certificates are generated INSIDE the VM upon start when needed. The image contains a CSR (signing request), so this is not something we 'provide'.

As per #2677, #2674 and #2628 we know this is based on a nested virtualization setup. Which we have indicated is not supported either. Unless you try this on a desktop/notebook computer or bare-metal, there is not much we can do. Though, my colleague has asked you questions related to the pull-secret, but this has been unanswered. Can you please answer the questions so we can try to resolve some of the problems?

**Comment by rupeshad81** [comment]
Hi,

As we cannot install on the laptop and we do not have any bare-metal.  Till now we had released the crc 4.7.11 which is stable on the OS version 7.6 .
So now we had OS version 7.8 , but then also crc get failed on the certificate, please provide the pull secret path to get download.

Thanks

**Comment by gbraad** [comment]
> please provide the pull secret path to get download

? I am not understanding what you are referring to. You are likely confusing issues I am touching on. Please answer here: https://github.com/code-ready/crc/issues/2677#issuecomment-908352249

> As we cannot install on the laptop and we do not have any bare-metal. 

It would have been possible to run 1.29.1 on a laptop, and recreate a bundle with `crc generate` for re-use on the other environment. But since this is not an option, there is not much we can do in this case.

**Comment by rupeshad81** [comment]
Hi,
I had replied.

Can you provide the latest path for pull secret , we will check once this option.

Thanks

**Comment by rupeshad81** [comment]
Hi,

Please can you update with pull secret path, to apply for latest crc version 4.7.x

Thanks

**Comment by cfergeau** [comment]
No 'pull secret update' is needed, the same pull secret should work for all versions of crc. For what it's worth, I just tried crc 1.29.1 on an up to date EL7 distro, and the certificate renewal was successful. What you are seeing is thus *not* an issue happening to everyone, but must be related to something specific to your setup. Which is why it is important to provide accurate and detailed debugging information, and not to try too many things at once so that it's possible to narrow down what is causing this issue.

But I'd recommend first using the latest crc release as *if* this is something we can fix in crc, we'll only be able to fix it on top of the latest release.

**Comment by rupeshad81** [comment]
Hi,

Thanks, you can close.
