### ISSUE TITLE
System services inactive when setting up crc fom multiple ssh sessions

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/crc#2690]
When setting up crc on a remote computer using ssh connections one possible use case would be split `setup` and `start` across two different ssh sessions:

```bash
ssh -i id_rsa user@host crc setup
# do whatever
ssh -i id_rsa user@host crc start ....
```

In this scenario the system services started during `crc setup` are shown as `inactive` so a `setup` within the same ssh session as `start`is required.

**Comment by cfergeau** [comment]
The systemd user session gets killed when the ssh session ends, and a new one is started with the next ssh session. This means the units which were started in the first session won't be started in the new one. This can be changed using `loginctl enable-linger`

**Comment by cfergeau** [comment]
Actually this will also happen in the 'remote crc' usecase:

    ssh into your remote machine, crc setup, do stuff with crc, log out when you are done
    next time you log into the machine, you'll need to rerun crc setup before being able to start your crc instance

Starting the .socket units automatically with the user session would do the trick (systemctl enable --user crc-http.socket, does this work with user sessions?)

**Comment by cfergeau** [comment]
The issue is even more problematic than that. When the daemon is started through socket activation, it will be stopped automatically when the last user session is closed. When using crc remotely with user mode networking, this means starting crc with ssh, and then logging out will break cluster networking :-/

**Comment by cfergeau** [comment]
The solution to this might be to unconditionally run `loginctl enable-linger $USER` so that there is always a user session running for the user.

**Comment by praveenkumar** [comment]
In case of unconditionally running `enable-linger` should we also let user know/warn that services started for this user? As per man page `This allows users who are not logged in to run  long-running services.` might not everyone wants?

**Comment by cfergeau** [comment]
A note in our  documentation could be useful, I'm not sure it's really important to add a `crc setup` warning about it.
Maybe there's an alternative to `enable-linger`, but haven't figured that out yet :)
