### ISSUE TITLE
[BUG] Too many aliases for a single line in hosts file (Windows)

### ISSUE THREAD

**Issue by skorhone** [code-ready/crc#2710]
### General information

  * OS: Windows
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop

## CRC version
```bash
CodeReady Containers version: 1.31.2+19538dab
OpenShift version: 4.8.4 (not embedded in executable)
```
  
## CRC status
```bash
DEBU CodeReady Containers version: 1.31.2+19538dab
DEBU OpenShift version: 4.8.4 (not embedded in executable)
DEBU Running 'crc status'
DEBU Checking file: C:\Users\user\.crc\machines\crc\.crc-exist
DEBU Checking file: C:\Users\user\.crc\machines\crc\.crc-exist
DEBU Running '( Hyper-V\Get-VM crc ).state'
DEBU Running SSH command: df -B1 --output=size,used,target /sysroot | tail -1
DEBU Using ssh private keys: [C:\Users\user\.crc\machines\crc\id_ecdsa C:\Users\user\.crc\cache\crc_hyperv_4.8.4\id_ecdsa_crc]
DEBU SSH command results: err: <nil>, output: 32737570816 14662197248 /sysroot
CRC VM:          Running
OpenShift:       Running (v4.8.4)
Disk Usage:      14.66GB of 32.74GB (Inside the CRC VM)
Cache Usage:     14.38GB
Cache Directory: C:\Users\user\.crc\cache
```

## CRC config
```bash
- consent-telemetry                     : no
- memory                                : 20480
```

## Host Operating System
```bash
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19042 N/A Build 19042
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
```

### Steps to reproduce

  1. crc start
  2. type c:\windows\system32\drivers\etc\hosts

### Expected
At most 9 aliases per ip per line. Preferably one line per alias

```
127.0.0.1 myhost
127.0.0.1 prometheus-istio-system.apps-crc.testing
127.0.0.1 istio-ingressgateway-istio-system.apps-crc.testing
127.0.0.1 grafana-istio-system.apps-crc.testing
127.0.0.1 jaeger-istio-system.apps-crc.testing
127.0.0.1 kiali-istio-system.apps-crc.testing
127.0.0.1 api.crc.testing canary-openshift-ingress-canary.apps-crc.testing
127.0.0.1 console-openshift-console.apps-crc.testing
127.0.0.1 default-route-openshift-image-registry.apps-crc.testing
127.0.0.1 downloads-openshift-console.apps-crc.testing
127.0.0.1 oauth-openshift.apps-crc.testing
```

I'm not sure if it's Windows or some 3rd party component (vpn, 3rd party firewall) that adds limit of 9 entries per line, but current single line approach isn't just working. Limit of 9 came from experimenting behavior (User has had similar experience here: https://superuser.com/questions/932112/is-there-a-maximum-number-of-hostname-aliases-per-line-in-a-windows-hosts-file )

### Actual
All aliases are on single line:

```
127.0.0.1 myhost prometheus-istio-system.apps-crc.testing istio-ingressgateway-istio-system.apps-crc.testing grafana-istio-system.apps-crc.testing jaeger-istio-system.apps-crc.testing kiali-istio-system.apps-crc.testing api.crc.testing canary-openshift-ingress-canary.apps-crc.testing console-openshift-console.apps-crc.testing default-route-openshift-image-registry.apps-crc.testing downloads-openshift-console.apps-crc.testing oauth-openshift.apps-crc.testing
```

### Logs
```
Cannot update kubeconfig: Head "https://oauth-openshift.apps-crc.testing": dial tcp: lookup oauth-openshift.apps-crc.testing: no such host
```

**Comment by cfergeau** [comment]
The `hostsfile` module we are using has code for this https://github.com/goodhosts/hostsfile/commit/57158c4acf4812de4e18728a918eac8fcfe6f628
crc's admin-helper seems to be using a recent enough version of this module, and crc seems to be using an up-to-date admin-helper release, so I'm not sure yet where the missing bit is.

**Comment by gbraad** [comment]
Windows has a maximum of 9 entries per line, and to add more a new line is required as alias.
I am not aware of the known limitation of having a maximum of 9 lines for the same host/alias.

Might have a try with this later, but I know there is a tool called "Host File Optimizer" that might help with this.

**Comment by gbraad** [comment]
```
# Test section
127.0.0.1 one two three four five six seven eight nine ten
127.0.0.1 eleven
127.0.0.1 tweleve
127.0.0.1 thirteen
127.0.0.1 fourteen
127.0.0.1 fifteen
127.0.0.1 sixteen
127.0.0.1 seventeen
127.0.0.1 eighteen
127.0.0.1 nineteen
127.0.0.1 twenty
# End of test section
```

```
C:\Users\gbraad>ping one

Pinging one [127.0.0.1] with 32 bytes of data:
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128

Ping statistics for 127.0.0.1:
    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
Control-C
^C
C:\Users\gbraad>ping nine

Pinging one [127.0.0.1] with 32 bytes of data:
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128

Ping statistics for 127.0.0.1:
    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
Control-C
^C
C:\Users\gbraad>ping ten

Pinging ten.gbraad.net [185.199.108.153] with 32 bytes of data:
Reply from 185.199.108.153: bytes=32 time=71ms TTL=51

Ping statistics for 185.199.108.153:
    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 71ms, Maximum = 71ms, Average = 71ms
Control-C
^C
C:\Users\gbraad>ping eleven

Pinging eleven [127.0.0.1] with 32 bytes of data:
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128

Ping statistics for 127.0.0.1:
    Packets: Sent = 3, Received = 3, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
Control-C
^C
C:\Users\gbraad>ping nineteen

Pinging nineteen [127.0.0.1] with 32 bytes of data:
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128

Ping statistics for 127.0.0.1:
    Packets: Sent = 2, Received = 2, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
Control-C
^C
C:\Users\gbraad>ping twenty

Pinging twenty [127.0.0.1] with 32 bytes of data:
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128

Ping statistics for 127.0.0.1:
    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
Control-C
^C
```

So it seems the limitation is only for the entries on a line, and not the amount of lines.
If this is failing on your end, it might be something else?

Have you installed a firewall or other endpoint protection?

**Comment by skorhone** [comment]
We do have Symantec Endpoint Protection and Cisco VPN installed. Like I mentioned the limit might be because of some 3rd party product. There's no way of telling which product is causing the problem - I do not have required access to isolate it. And even if I did, convincing Symantec or Cisco to fix their product... you all know how this discussion would end.

If I manually split the long entry from multiple lines, everything seems to work properly. This should be easy enough to change at crc side? I can't see any negative side effects in this change (unless some other 3rd party product mishandles having multiple lines :-))

**Comment by gbraad** [comment]
We might be able to propose a fix for the library we use, but might go with an intermediate postprocess to put them on individual lines.

Will see if this can be fixed soonish

**Comment by gbraad** [comment]
https://github.com/goodhosts/hostsfile/issues/18

**Comment by praveenkumar** [comment]
> The `hostsfile` module we are using has code for this [goodhosts/hostsfile@57158c4](https://github.com/goodhosts/hostsfile/commit/57158c4acf4812de4e18728a918eac8fcfe6f628)
> crc's admin-helper seems to be using a recent enough version of this module, and crc seems to be using an up-to-date admin-helper release, so I'm not sure yet where the missing bit is.

I think this code is for cleaning/removing side not taking account to add an host entry.
```
$ cat /etc/hosts
127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4
::1 localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.122.1 libvirt.default
192.168.130.11 api.crc.testing canary-openshift-ingress-canary.apps-crc.testing console-openshift-console.apps-crc.testing default-route-openshift-image-registry.apps-crc.testing downloads-openshift-console.apps-crc.testing oauth-openshift.apps-crc.testing
192.168.130.11 oauth-openshift.apps-crc.testing
192.168.130.11 downloads-openshift-console.apps-crc.testing oauth-openshift.apps-crc.testing

$ ~/.crc/bin/crc-admin-helper-linux remove oauth-openshift.apps-crc.testing

$ cat /etc/hosts
127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4
::1 localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.122.1 libvirt.default
192.168.130.11 api.crc.testing canary-openshift-ingress-canary.apps-crc.testing console-openshift-console.apps-crc.testing default-route-openshift-image-registry.apps-crc.testing downloads-openshift-console.apps-crc.testing
192.168.130.11 downloads-openshift-console.apps-crc.testing
```

**Comment by guillaumerose** [comment]
Maybe we should drop this hostsfile library and do our own text processing. We could also add delimiters around the entries we added.

**Comment by gbraad** [comment]
Does a later version of this library work? The author claims this exists?
But yeah, delimiting is also not existing now

**Comment by cfergeau** [comment]
> I think this code is for cleaning/removing side not taking account to add an host entry.

ah looks like it. This seems like something which was missed when they added the line splitting.

**Comment by skorhone** [comment]
Just to say, I really dislike the fact that library rewrites whole hosts file. If you've added custom comments (documentation), it all gets removed.

And now that I tested following:
- added a new entry with completely different host (127.0.0.2 foo) with a comment while crc was running
- stopped crc
- started crc

I observed that entry and comment got removed. 

```
127.0.0.1 prometheus-istio-system.apps-crc.testing
127.0.0.1 istio-ingressgateway-istio-system.apps-crc.testing
127.0.0.1 grafana-istio-system.apps-crc.testing
127.0.0.1 jaeger-istio-system.apps-crc.testing
127.0.0.1 kiali-istio-system.apps-crc.testing
127.0.0.1 api.crc.testing canary-openshift-ingress-canary.apps-crc.testing
127.0.0.1 console-openshift-console.apps-crc.testing
127.0.0.1 default-route-openshift-image-registry.apps-crc.testing
127.0.0.1 downloads-openshift-console.apps-crc.testing
127.0.0.1 oauth-openshift.apps-crc.testing
127.0.0.1 bookinfo-bookinfo-gateway-525eca1d5089dbdc-istio-system.apps-crc.testing
# another thing
127.0.0.2 another
```

Got translated to:

```
127.0.0.1 prometheus-istio-system.apps-crc.testing istio-ingressgateway-istio-system.apps-crc.testing grafana-istio-system.apps-crc.testing jaeger-istio-system.apps-crc.testing kiali-istio-system.apps-crc.testing bookinfo-bookinfo-gateway-525eca1d5089dbdc-istio-system.apps-crc.testing api.crc.testing canary-openshift-ingress-canary.apps-crc.testing console-openshift-console.apps-crc.testing default-route-openshift-image-registry.apps-crc.testing downloads-openshift-console.apps-crc.testing oauth-openshift.apps-crc.testing
```

This will cause major issues for everyone that uses hosts file for anything other than crc discovery.

I'd personally just read the whole file in memory, do a simple regex for removing specific content (block, or lines) and then append new content to end of file. Structure of hosts file is so simple that you really don't need fancy wrapper library for editing it.

**Comment by praveenkumar** [comment]
if https://github.com/goodhosts/hostsfile/pull/20 is merged upstream then we can try to update our admin-helper to use this functionality to make sure each line doesn't have multiple host.

**Comment by praveenkumar** [comment]
https://github.com/code-ready/admin-helper/pull/23 should fix it, tried it on windows.

**Comment by praveenkumar** [comment]
This is fixed and available on latest version of crc.

**Comment by z11k** [comment]
> 

exactly, well said. it's really bad idea and very intrusive default behavior. **is there some change regarding that?** i have pretty long and not interested in mods. provide settings what is needed and let change on user will be far user user friendly way...thx
