### ISSUE TITLE
`.exe` file is missing from the versions after `v1.31.2`

### ISSUE THREAD

**Issue by divyansh42** [code-ready/crc#2717]
In the [OpenShift tools Installer](https://github.com/redhat-actions/openshift-tools-installer) action we support the installation of CRC on the Windows platform.
For Windows OS this works using `.exe` file but it seems after version `1.31.2` `.exe` is replaced with MSI files.
To be able to support installation in Windows we definitely need `exe` files as we need to run this action without admin permissions and the MSI file needs admin permissions. 
By any chance, can we get `exe` file back?

Ref: https://github.com/redhat-actions/openshift-tools-installer/issues/50

cc \@jduimovich @tetchel

**Comment by praveenkumar** [comment]
@divyansh42 How did you perform  the `crc setup` then before running `crc  start` for those action because even in case of `exe` file we do need to run the `setup` for administrator privilege to perform like enabling hyperV or usermode networking side.

**Comment by gbraad** [comment]
Unfortunately we will not be offering phat-binaries anymore. The install process as mentioned before `crc setup` was too involved and made the binary bloated. While it allows to easily move files around, it leaves a multitude of large files on the disk (eg. 2+ GB binary, 2+ GB bundle, 3+ GB disk image, etc).

The MSI is a single time affair. Or use the msi from the command line with `msiexec` ?

**Comment by cfergeau** [comment]
Did you manage to integrate the new installation process in your tools? Or do you need more help from our side for this?
@divyansh42 @tetchel @jduimovich ?

**Comment by divyansh42** [comment]
Due to some other priorities, we were not able to devote much time to this.
I'll update this issue in case some help is needed from your side.
Thanks!
