### ISSUE TITLE
[BUG]The web console is blank.

### ISSUE THREAD

**Issue by freedom01020** [code-ready/crc#2718]
### General information

  * OS: Linux (RHEL8.1)
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it ? Yes

## CRC version
```bash
CodeReady Containers version: 1.31.2+19538dab
OpenShift version: 4.8.4 (embedded in executable)
```

  
## CRC status
```bash
DEBU CodeReady Containers version: 1.31.2+19538dab
DEBU OpenShift version: 4.8.4 (embedded in executable)
DEBU Running 'crc status'
DEBU Checking file: /home/casa/.crc/machines/crc/.crc-exist
DEBU Checking file: /home/casa/.crc/machines/crc/.crc-exist
DEBU Found binary path at /home/casa/.crc/bin/crc-driver-libvirt
DEBU Launching plugin server for driver libvirt
DEBU Plugin server listening at address 127.0.0.1:38095
DEBU () Calling .GetVersion
DEBU Using API Version 1
DEBU () Calling .SetConfigRaw
DEBU () Calling .GetMachineName
DEBU (crc) Calling .GetState
DEBU (crc) DBG | time="2021-09-12T23:36:12-04:00" level=debug msg="Getting current state..."
DEBU (crc) DBG | time="2021-09-12T23:36:12-04:00" level=debug msg="Fetching VM..."
DEBU (crc) Calling .GetBundleName
DEBU (crc) Calling .GetIP
DEBU (crc) DBG | time="2021-09-12T23:36:12-04:00" level=debug msg="GetIP called for crc"
DEBU (crc) DBG | time="2021-09-12T23:36:12-04:00" level=debug msg="Getting current state..."
DEBU (crc) DBG | time="2021-09-12T23:36:12-04:00" level=debug msg="IP address: 192.168.130.11"
DEBU Running SSH command: df -B1 --output=size,used,target /sysroot | tail -1
DEBU Using ssh private keys: [/home/casa/.crc/machines/crc/id_ecdsa /home/casa/.crc/cache/crc_libvirt_4.8.4/id_ecdsa_crc]
DEBU SSH command results: err: <nil>, output: 106825756672 18006347776 /sysroot
DEBU Making call to close driver server
DEBU (crc) Calling .Close
DEBU Successfully made call to close driver server
DEBU Making call to close connection to plugin binary
CRC VM:          Running
OpenShift:       Running (v4.8.4)
Disk Usage:      18.01GB of 106.8GB (Inside the CRC VM)
Cache Usage:     33.42GB
Cache Directory: /home/casa/.crc/cache
```

## CRC config
```bash
- consent-telemetry                     : no
- cpus                                  : 32
- disk-size                             : 100
- memory                                : 61440
```

## Host Operating System
```bash
NAME="Red Hat Enterprise Linux"
VERSION="8.1 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.1"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.1 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.1:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.1
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.1"
```

### Steps to reproduce

  1. crc login -u kubeadmin
  2. crc console

### Expected
Open the web console normally

### Actual
Login from the console, this step is normal. However, after login, the interface is blank.
![555](https://user-images.githubusercontent.com/48399321/133021061-69869854-52b1-42cd-89b3-d938a1ea2eca.png)
![666](https://user-images.githubusercontent.com/48399321/133021190-07e7755f-67d0-49b7-aa59-f545628c94b1.png)

**Comment by praveenkumar** [comment]
@freedom01020 it is sometime because of cache can you try that console url `https://console-openshift-console.apps-crc.testing` in incognito mode or in a different browser?

**Comment by gbraad** [comment]
You could check the browser console for more info about this, but most likely a cache issue as mentioned before.
Force a hard-refresh or use private mode

**Comment by freedom01020** [comment]
> @freedom01020 it is sometime because of cache can you try that console url `https://console-openshift-console.apps-crc.testing` in incognito mode or in a different browser?

Thanks, after I change the browser with chrome, it works!

**Comment by freedom01020** [comment]
> You could check the browser console for more info about this, but most likely a cache issue as mentioned before.
> Force a hard-refresh or use private mode

Thanks!
Althought I try that console url https://console-openshift-console.apps-crc.testing in incognito mode or in a different browser but still failed.
Fortunately, after I change the browser with chrome, it works!
