### ISSUE TITLE
docs: Document that `no_proxy` needs to be set for `.testing` not just for `oc` use

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#2726]
After configuring my cluster with an external proxy, I wanted to run `curl -k -I api.crc.testing`, but this failed as I had forgotten to add `crc.testing` to `no_proxy` first.

Our documentation only says:
> To use an existing oc executable on your host machine, export the .testing domain as part of the no_proxy environment variable.

It is not needed only for `oc`, but for any cluster interaction.

**Comment by jhcook** [comment]
It would be great if this were updated as it’s caught me out, and I’ll never get that time back. 👍

**Comment by cfergeau** [comment]
I attempted to improve this in https://github.com/cfergeau/crc/commit/9695d882bee14200042f09af26182051daf8c4aa but I am having trouble wording it in a way I like:
>  If you are not using [command]`crc oc-env`, when interacting with the cluster, export the `.testing` domain as part of the `no_proxy` environment variable.
