### ISSUE TITLE
[BUG] You must be logged in to the server (the server has asked for the client to provide credentials ( pods/log xxxx-1-build))

### ISSUE THREAD

**Issue by JiriHusak-lab** [code-ready/crc#2728]
### General information

  * OS: Linux 
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes)?
  * Running CRC on:  Baremetal-Server
  * 
## CRC version
```bash
# Put `crc version` output here
CodeReady Containers version: 1.17.0+99f5c87
OpenShift version: 4.5.14 (embedded in binary)
```
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
DEBU CodeReady Containers version: 1.17.0+99f5c87
DEBU OpenShift version: 4.5.14 (embedded in binary)
DEBU About to run SSH command with hidden output
DEBU SSH command succeeded
DEBU About to run SSH command:
df -B1 --output=size,used,target /sysroot | tail -1
DEBU SSH command results: err: <nil>, output: 268943994880 30602780672 /sysroot
CRC VM:          Running
OpenShift:       Running (v4.5.14)
Disk Usage:      30.6GB of 268.9GB (Inside the CRC VM)
Cache Usage:     13.04GB

```

## CRC config
```bash
# Put `crc config view` output here
- cpus                                  : 24
- memory                                : 54576
- pull-secret-file                      : pull-secret
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.2"

```

### Steps to reproduce

  1. oc logs -f xxxx-1-build
   returns: 
  **error: You must be logged in to the server (the server has asked for the client to provide credentials ( pods/log xxxx-1-build))**

 I'm logged of course, I can perform other oc commands.
 I have run crc stop and crc start,
 crc start shows (among others):
	INFO Verifying validity of the cluster certificates …
	INFO Starting OpenShift kubelet service
 with no errors

Application is running, only issue I can see when trying to display logs. Other funstionality seems working.
My deployed demo app is working.

I've googled many advices but none of them is relevant.

Deleting cluster and building it again (crc stop, crc delete; crc cleanup; crc setup; crc start) I did 19 days ago and it solved this issue. But now issue is back in 19 days. I do not want to recreate cluster again and again.

  2. 
  3. 
  4. 

### Expected
to display log content

### Actual
**error: You must be logged in to the server (the server has asked for the client to provide credentials ( pods/log xxxx-1-build))**

### Logs
no logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
@JiriHusak-lab This is because of cert, if your crc cluster always up it means it also update the certs on periodic bases so you might be hitting it after 19 days because during this time may be cert rotation in progress. Does it not auto resolved after 10-15 mins? when you hit this issue again try to capture following.
```
$ oc get node
$ oc get co
```

**Comment by gbraad** [comment]
> DEBU CodeReady Containers version: 1.17.0+99f5c87

You are running a very old version and therefore certificate rotation is expected (these happen for sure 30 days after the release of the CRC binary+bundle). Your release is https://github.com/code-ready/crc/releases/tag/1.17.0 which is from Oct 2020. We do not support this anymore (current release N-1).

Please update the cluster/CRC
