### ISSUE TITLE
Failed to update kubeadmin user password: Temporary error

### ISSUE THREAD

**Issue by tomasz-sulek** [code-ready/crc#2729]
Hello, 
On the fresh installation of CRC v4.8.5 on the freshly installed RHEL8.4 i have an error:

```
INFO Waiting for user's pull secret part of instance disk... 
Failed to update kubeadmin user password: Temporary error: ssh command error:
command : timeout 5s oc get secret --context admin --cluster crc --kubeconfig /opt/kubeconfig
err     : Process exited with status 124\n (x13)
```

When i try to start CRC with options:

`crc start -m 12288 -p pull-secret`

**Comment by gbraad** [comment]
> CRC v4.8.5

??? you likely mean CRC with OCP 4.8.5. But can you please follow the issue template?

**Comment by tomasz-sulek** [comment]
I am sorry
Openshift 4.8.5
CRC 1:32:1

Where I can find issue template ?

**Comment by praveenkumar** [comment]
> Where I can find issue template ?

@tomasz-sulek https://github.com/code-ready/crc/issues/new/choose (use bug report) and you will get the issue template

**Comment by praveenkumar** [comment]
@laynecook It would be better if you file an new issue using issue template and also use the latest release.
