### ISSUE TITLE
CRC : Not able to oc login : The connection to the server oauth-openshift.apps-crc.testing was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by rupeshad81** [code-ready/crc#2746]
Hi,

Please can you suggest , what we need to do for fixing the below issue:

[crc@eaas-crc ~]$ crc version
CodeReady Containers version: 1.32.1+4d40571f
OpenShift version: 4.8.5 (embedded in executable)
[crc@eaas-crc ~]$
[crc@eaas-crc ~]$
[crc@eaas-crc ~]$ crc status
CRC VM:          Running
OpenShift:       Running (v4.8.5)
Disk Usage:      6.16GB of 32.74GB (Inside the CRC VM)
Cache Usage:     15.96GB
Cache Directory: /home/crc/.crc/cache
[crc@eaas-crc ~]$
[crc@eaas-crc ~]$
[crc@eaas-crc ~]$ crc config view
- consent-telemetry                     : yes
- http-proxy                            : http://10.232.233.70:8080
- https-proxy                           : http://10.232.233.70:8080
- no-proxy                              : 127.0.0.1,localhost,.corp.amdocs.com,.apps-crc.testing,.crc.testing
- skip-check-daemon-systemd-sockets     : true
- skip-check-daemon-systemd-unit        : true
[crc@eaas-crc ~]$
[crc@eaas-crc ~]$
[crc@eaas-crc ~]$ crc console --credentials
To login as a regular user, run 'oc login -u developer -p developer https://api.crc.testing:6443'.
To login as an admin, run 'oc login -u kubeadmin -p 7F5Et-xUjvV-NCyhN-vrEKw https://api.crc.testing:6443'
[crc@eaas-crc ~]$ oc login -u kubeadmin -p 7F5Et-xUjvV-NCyhN-vrEKw https://api.crc.testing:6443
The connection to the server oauth-openshift.apps-crc.testing was refused - did you specify the right host or port?

**Comment by praveenkumar** [comment]
Closing this issue since it is not filled using the issue template

/close
