### ISSUE TITLE
Daemon not properly initialized after crc setup[BUG]

### ISSUE THREAD

**Issue by ananth5** [code-ready/crc#2758]
Unable to run crc start after running setup

![image](https://user-images.githubusercontent.com/18162536/134764005-3478573c-67c2-49ab-a3a2-18420a1c1dce.png)

Attempt #1
I tried setting up the username in env and rerunning the crc setup but that did not help
![image](https://user-images.githubusercontent.com/18162536/134764027-8db73410-8259-4e34-bb87-26a42b029f7d.png)

Attempt #2
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
The above commands also did not work.

crc status output
 
![image](https://user-images.githubusercontent.com/18162536/134764063-edabd3d2-77ac-478d-b083-f374456b02bb.png)

Full log below
![image](https://user-images.githubusercontent.com/18162536/134764085-896efb47-e00c-41f3-bbf8-36bc78c5a101.png)

Running systeminfo command below gave the following output

PS C:\Users\ananth.shanmugam\OneDrive - cgcmb\Desktop> systeminfo

Host Name:                 CGCNBPOC-ASUS
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19043 N/A Build 19043
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          cgc
Registered Organization:
Product ID:                00330-80000-00000-AA110
Original Install Date:     14/9/2021, 1:18:50 PM
System Boot Time:          25/9/2021, 1:55:21 PM
System Manufacturer:       ASUSTeK COMPUTER INC.
System Model:              ASUS EXPERTBOOK B1400CEPE_B1400CEPE
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 140 Stepping 1 GenuineIntel ~2803 Mhz
BIOS Version:              ASUSTeK COMPUTER INC. B1400CEPE.301, 15/4/2021
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+08:00) Kuala Lumpur, Singapore
Total Physical Memory:     16,061 MB
Available Physical Memory: 8,972 MB
Virtual Memory: Max Size:  18,493 MB
Virtual Memory: Available: 9,661 MB
Virtual Memory: In Use:    8,832 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    cgc.gov.my
Logon Server:              \\CGC-DC01
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB5004331
                           [02]: KB5000736
                           [03]: KB5005565
                           [04]: KB5005699
Network Card(s):           5 NIC(s) Installed.
                           [01]: Intel(R) Wi-Fi 6 AX201 160MHz
                                 Connection Name: Wi-Fi
                                 Status:          Media disconnected
                           [02]: Intel(R) Ethernet Connection (13) I219-V
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [04]: Remote NDIS based Internet Sharing Device
                                 Connection Name: Ethernet 2
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.42.129
                                 IP address(es)
                                 [01]: 192.168.42.124
                           [05]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (Default Switch)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 172.17.112.1
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
PS C:\Users\ananth.shanmugam\OneDrive - cgcmb\Desktop>

### General information

  * OS:  Windows   
  * Hypervisor: Hyper-V
  *   * Did you run `crc setup` before starting it (Yes/No)?  Yes
  * Running CRC on: Laptop / Baremetal-Server / VM   Laptop

## CRC version
```bash
# Put `crc version` output here
```
CodeReady Containers version: 1.32.1+4d40571f
OpenShift version: 4.8.5 (bundle installed at C:\Program Files\CodeReady Containers\crc_hyperv_4.8.5.crcbundle)  
## CRC status
PS C:\Users\ananth.shanmugam\OneDrive - cgcmb\desktop> crc status
Machine does not exist. Use 'crc start' to create it

```bash
# Put `crc status --log-level debug` output here
```
![image](https://user-images.githubusercontent.com/18162536/134764232-f313110f-abe8-4282-8df7-b90e728acefd.png)

## CRC config
```bash
# Put `crc config view` output here
```
![image](https://user-images.githubusercontent.com/18162536/134764212-d81d5adf-6d5c-44eb-9f36-4200f5dfaec8.png)

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```
![image](https://user-images.githubusercontent.com/18162536/134764265-da90ac6d-1c78-4ce1-a29e-fcfb6a97df7e.png)
![image](https://user-images.githubusercontent.com/18162536/134764283-3cf4ef93-71fd-437a-bb70-24f14ce19ee2.png)

### Steps to reproduce

  1. crc delete -f
  2. crc cleanup
  3. crc setup
  4. crc start --log-level debug

### Logs

Before gather the logs try following if that fix your issue
```bash


Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by adrianriobo** [comment]
Did you restart the computer after install crc? It seems like the system tray is not running, which should be auto started after restart the computer

**Comment by ananth5** [comment]
hi adrianriobo, 
i have tried restarting my laptop several times. It did not fix the issue. My firewall is already disabled

**Comment by ananth5** [comment]
No, it disappears once i launch it. Once it stayed for a 2 -3 seconds, then it disappears. The issue is I am not sure why is it disappearing from the tray.

**Comment by adrianriobo** [comment]
Can you check windows security, there is a reported known bug where crc-tray.exe is detected as false positive and gets blocked #2665

**Comment by ananth5** [comment]
> Can you check windows security, there is a reported known bug where `crc-tray.exe` is detected as false positive and gets blocked #2665

I have already turned off everything in windows 10 including firewall and enable app via firewall
![image](https://user-images.githubusercontent.com/18162536/135077106-20cad267-b016-4cf2-972c-9cbfc97ec61e.png)
![image](https://user-images.githubusercontent.com/18162536/135077159-9d809b5f-6f1e-4453-b658-bf83e1c3fae2.png)
![image](https://user-images.githubusercontent.com/18162536/135077319-372e449c-ab86-4eb5-84d2-794acb0fb4c1.png)

**Comment by cfergeau** [comment]
I don't know if you are still seeing this issue, but maybe you need to run `crc delete; crc cleanup`, then uninstall the crc application, and reinstall a newer version, to see if this helps. The daemon not starting is a big problem.
I noticed ` Hyper-V Requirements: A hypervisor has been detected. Features required for Hyper-V will not be displayed.` in your logs, just to be sure, your Windows is not running inside a VM?

**Comment by ananth5** [comment]
Hi All,
Apologies for the late reply. Thank you very much for your supportThe issue was with the laptop security application. Making sure to install CRC first, then the security applications solved the issue. Thank you.
RegardsAnanth Shanmugam 
    On Monday, December 6, 2021, 09:46:05 PM GMT+8, Christophe Fergeau ***@***.***> wrote:  
 
 


I don't know if you are still seeing this issue, but maybe you need to run crc delete; crc cleanup, then uninstall the crc application, and reinstall a newer version, to see if this helps. The daemon not starting is a big problem.
I noticed  Hyper-V Requirements: A hypervisor has been detected. Features required for Hyper-V will not be displayed. in your logs, just to be sure, your Windows is not running inside a VM?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cfergeau** [comment]
Thanks for the follow-up, I'll close this issue then!
