### ISSUE TITLE
[BUG] 1.33.1 crc-windows-installer.zip is empty  

### ISSUE THREAD

**Issue by pjos** [code-ready/crc#2777]
### General information

  * OS: Windows
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it (Yes/No)? Not applicable, installation package empty
  * Running CRC on: Laptop 

1.33.1 CRC package for windows `crc-windows-installer.zip` is empty, 199 bytes in size.
https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/crc/1.33.1

**Comment by praveenkumar** [comment]
@pjos Thanks for letting us know, we will try to upload it again.

**Comment by praveenkumar** [comment]
@pjos Hi we fixed the windows package issue, can you try now and let us know if that works for you?

**Comment by pjos** [comment]
The whole OCP world has been waiting for a new CRC and is now downloading, ETA for my download i 6 days :-o.  Anyway, the package is bigger and I've seen already 1.33.1 windows issues reported so this issue can be closed. Thanks for fast response on this one.

**Comment by praveenkumar** [comment]
@pjos We host the releases on the CDN so if someone from your region download it then it should be way faster. 

/close
