### ISSUE TITLE
crc setup error: Unit virtqemud.socket could not be found

### ISSUE THREAD

**Issue by JiriHusak-lab** [code-ready/crc#2782]
On RHEL , crc setup is raising errors related to virtualization.
NetworkManager is installed. See versions and errors below.

crc version: 1.33.1 
Red Hat Enterprise Linux release 8.2 (Ootpa)
Package NetworkManager-1:1.22.8-4.el8.x86_64 is already installed.

systemctl is-enabled libvirtd
_enabled_

systemctl is-enabled virtqemud
_Failed to get unit file state for virtqemud.service: No such file or directory_

systemctl status libvirtd.socket
_Unit libvirtd.socket could not be found._

systemctl status virtqemud.socket
_Unit virtqemud.socket could not be found._

crc setup
.... 
DEBU Checking if current user is part of the libvirt group 
DEBU Current user is already in the libvirt group 
INFO Checking if active user/process is currently part of the libvirt group 
INFO Checking if libvirt daemon is running 
DEBU Checking if libvirtd service is running 
**DEBU Running 'systemctl status virtqemud.socket' 
DEBU Command failed: exit status 4 
DEBU stdout: 
DEBU stderr: Unit virtqemud.socket could not be found. 
DEBU virtqemud.socket is neither running nor listening 
DEBU Running 'systemctl status libvirtd.socket' 
DEBU Command failed: exit status 4 
DEBU stdout: 
DEBU stderr: Unit libvirtd.socket could not be found. 
DEBU libvirtd.socket is neither running nor listening** 

Is NetworkManager version too old or is specific configuration needed for crc?
Thanks a lot for any hint.

Thanks and Regards,
Jirka

**Comment by praveenkumar** [comment]
@JiriHusak-lab Does it error out eventually, can you put complete log of `crc setup --log-level debug` command?

**Comment by JiriHusak-lab** [comment]
Every run of crc setup ends with error.


[crc@rhel821 ~]$ crc setup --log-level debug
DEBU CodeReady Containers version: 1.32.1+4d40571f
DEBU OpenShift version: 4.8.5 (embedded in executable)
DEBU Running 'crc setup'
DEBU Checking if systemd-resolved.service is running
DEBU Running 'systemctl status systemd-resolved.service'
DEBU systemd-resolved.service is already running
INFO Checking if running as non-root
INFO Checking if running inside WSL2
INFO Checking if crc-admin-helper executable is cached
DEBU Running '/var/crc/.crc/bin/crc-admin-helper-linux --version'
DEBU Found crc-admin-helper-linux version 0.0.6
DEBU crc-admin-helper executable already cached
INFO Checking for obsolete admin-helper executable
DEBU Checking if an older admin-helper executable is installed
DEBU No older admin-helper executable found
INFO Checking if running on a supported CPU architecture
INFO Checking minimum RAM requirements
DEBU Total memory of system is 67276972032 bytes
INFO Checking if crc executable symlink exists
INFO Checking if Virtualization is enabled
DEBU Checking if the vmx/svm flags are present in /proc/cpuinfo
DEBU CPU virtualization flags are good
INFO Checking if KVM is enabled
DEBU Checking if /dev/kvm exists
DEBU /dev/kvm was found
INFO Checking if libvirt is installed
DEBU Checking if 'virsh' is available
DEBU 'virsh' was found in /usr/bin/virsh
DEBU Checking 'virsh capabilities' for libvirtd/qemu availability
DEBU Running 'virsh --readonly --connect qemu:///system capabilities'
DEBU Found x86_64 hypervisor with 'hvm' capabilities
INFO Checking if user is part of libvirt group
DEBU Checking if current user is part of the libvirt group
DEBU Current user is already in the libvirt group
INFO Checking if active user/process is currently part of the libvirt group
INFO Checking if libvirt daemon is running
DEBU Checking if libvirtd service is running
DEBU Running 'systemctl status virtqemud.socket'
DEBU Command failed: exit status 4
DEBU stdout:
DEBU stderr: Unit virtqemud.socket could not be found.
DEBU virtqemud.socket is neither running nor listening
DEBU Running 'systemctl status libvirtd.socket'
DEBU Command failed: exit status 4
DEBU stdout:
DEBU stderr: Unit libvirtd.socket could not be found.
DEBU libvirtd.socket is neither running nor listening
DEBU Running 'systemctl status virtqemud.service'
DEBU Command failed: exit status 4
DEBU stdout:
DEBU stderr: Unit virtqemud.service could not be found.
DEBU virtqemud.service is neither running nor listening
DEBU Running 'systemctl status libvirtd.service'
DEBU libvirtd.service is running
INFO Checking if a supported libvirt version is installed
DEBU Checking if libvirt version is >=3.4.0
DEBU Running 'virsh -v'
INFO Checking if crc-driver-libvirt is installed
DEBU Checking if crc-driver-libvirt is installed
DEBU Running '/var/crc/.crc/bin/crc-driver-libvirt version'
DEBU Found crc-driver-libvirt version 0.13.1
DEBU crc-driver-libvirt is already installed
INFO Checking crc daemon systemd service
DEBU Checking crc daemon systemd service
DEBU Checking if crc-daemon.service is running
DEBU Running 'systemctl --user status crc-daemon.service'
DEBU Command failed: exit status 1
DEBU stdout:
DEBU stderr: Failed to connect to bus: No such file or directory
DEBU Could not get crc-daemon.service  status: Executing systemctl action failed:  exit status 1: Failed to connect to bus: No such file or directory
DEBU Checking if crc-daemon.service has the expected content
INFO Checking crc daemon systemd socket units
DEBU Checking crc daemon systemd socket units
DEBU Checking if crc-http.socket is running
DEBU Running 'systemctl --user status crc-http.socket'
DEBU Command failed: exit status 1
DEBU stdout:
DEBU stderr: Failed to connect to bus: No such file or directory
DEBU Could not get crc-http.socket  status: Executing systemctl action failed:  exit status 1: Failed to connect to bus: No such file or directory
DEBU crc-http.socket is not running
INFO Setting up crc daemon systemd socket units
DEBU Setting up crc daemon systemd socket units
DEBU Setting up crc-http.socket
DEBU Running 'systemctl --user status crc-http.socket'
DEBU Command failed: exit status 1
DEBU stdout:
DEBU stderr: Failed to connect to bus: No such file or directory
DEBU Could not get crc-http.socket  status: Executing systemctl action failed:  exit status 1: Failed to connect to bus: No such file or directory
DEBU Starting crc-http.socket
DEBU Running 'systemctl --user daemon-reload'
DEBU Command failed: exit status 1
DEBU stdout:
DEBU stderr: Failed to connect to bus: No such file or directory
DEBU Running 'systemctl --user start crc-http.socket'
DEBU Command failed: exit status 1
DEBU stdout:
DEBU stderr: Failed to connect to bus: No such file or directory
Executing systemctl action failed:  exit status 1: Failed to connect to bus: No such file or directory

**Comment by cfergeau** [comment]
```
DEBU stderr: Unit virtqemud.service could not be found.
DEBU virtqemud.service is neither running nor listening
DEBU Running 'systemctl status libvirtd.service'
DEBU libvirtd.service is running
```
This means this test is fine.

```
INFO Checking crc daemon systemd socket units
[...]
DEBU stderr: Failed to connect to bus: No such file or directory
```
This is the problematic part. You can avoid this using `crc config set skip-check-daemon-systemd-unit true` and `crc config set skip-check-daemon-systemd-sockets true`.

Are you running `crc` through ssh, or are you changing user with `su`/... before running it, ...? Trying to understand if this failure is due to RHEL8.2, or to something specific you are doing.

**Comment by JiriHusak-lab** [comment]
Hi Christophe,
thanks o lot. Your comment gave me a hint. Yes, I was logging as crc using sudo su - crc.
When loging directly as crc, error disapeared and crc setup runs successfully. So hint with crc config set ... commands were not needed.
Thanks a lot!
Now crc start is raising another error, I will opend another issue and now I'm closing this one as resolved.
Thanks again.
Jirka

**Comment by JiriHusak-lab** [comment]
Hint to login directly as crc and not using sudo su - crc helped.
