### ISSUE TITLE
[BUG]crc cleanup does not remove crc libvirt storage pool

### ISSUE THREAD

**Issue by JiriHusak-lab** [code-ready/crc#2785]
### General information

  * OS: Linux  
  * Hypervisor: KVM 
  * Did you run `crc setup` before starting it (Yes]
  * Running CRC on:  VM

## CRC version
```bash
1.33.1
```
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
crc status --log-level debug
DEBU CodeReady Containers version: 1.32.1+4d40571f
DEBU OpenShift version: 4.8.5 (embedded in executable)
DEBU Running 'crc status'
DEBU Checking file: /var/crc/.crc/machines/crc/.crc-exist
Machine does not exist. Use 'crc start' to create it

```

## CRC config
```bash
# Put `crc config view` output here
```

## Host Operating System
```bash
Red Hat Enterprise Linux release 8.2 (Ootpa)
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```

### Steps to reproduce

  1.  crc setup run as userx
       userx run crc cleanup and removed .crc directory in userx $HOME

  2. correct user crc run crc cleanup, crc setup - successfully.
crc $HOME is/var/crc and I'm running installation from /var/crc. 
/var/crc/.crc/machines/crc  directory is created

      Then "crc start" ends with error:
```
...
DEBU Using API Version 1
DEBU () Calling .SetConfigRaw
DEBU () Calling .GetMachineName
DEBU (crc) Calling .GetMachineName
DEBU (crc) Calling .DriverName
DEBU Running pre-create checks...
DEBU (crc) Calling .PreCreateCheck
DEBU (crc) DBG | time="2021-10-04T13:52:09+02:00" level=debug msg="About to check libvirt version"
DEBU (crc) DBG | time="2021-10-04T13:52:09+02:00" level=debug msg="Validating network"
DEBU (crc) DBG | time="2021-10-04T13:52:09+02:00" level=debug msg="Validating storage pool"
DEBU (crc) DBG | time="2021-10-04T13:52:09+02:00" level=debug msg="Activating pool 'crc'"
DEBU (crc) DBG | time="2021-10-04T13:52:09+02:00" level=warning msg="Failed to start storage pool: virError(Code=38, Domain=0, Message='cannot open directory '/home/**userx**/.crc/machines/crc': No such file or directory')"
```

I do not know where '/home/**userx**/.crc/machines/crc value is stored and why "crc start" wants to use this value for userx.
I run all cleaning
```
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```
I've deleted .crc as well.

userx did all cleaning as well.

I tried set | grep userx - no result.
I can't find where crc takes this value (/home/**userx**/.crc/machines/crc)  for storage pool. How I can force crc to user CRC $HOME path I mean /var/crc/.crc/machines/crc ?
 

  3. 
  4. 

### Expected
"crc stat" uses value /var/crc/.crc/machines/crc for storage pool. And not value for userx who runs crc installation previously and has clean it up already.

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
@JiriHusak-lab What is the output of `whoami` command?

**Comment by JiriHusak-lab** [comment]
$ whoami
crc
[crc@rhel821 crc]$

**Comment by JiriHusak-lab** [comment]
plus:
[crc@rhel821 ~]$ pwd
/var/crc
[crc@rhel821 ~]$ ls -ld .crc/machines/crc
drwxr-xr-x 2 crc crc 4096 Oct  4 13:52 .crc/machines/crc

**Comment by JiriHusak-lab** [comment]
I have found something.
File /etc/libvirt/storage/crc.xml
There is value '/home/userx/.crc/machines/crc' 

Full content of /etc/libvirt/storage/crc.xml:


<pool type='dir'>
  <name>crc</name>
  <uuid>9e270d9f-35d6-40a2-9759-654d174df006</uuid>
  <capacity unit='bytes'>0</capacity>
  <allocation unit='bytes'>0</allocation>
  <available unit='bytes'>0</available>
  <source>
  </source>
  <target>
    <path>/home/jkulich/.crc/machines/crc</path>
  </target>
</pool>

When I run crc setup and crc start, this file /etc/libvirt/storage/crc.xml is not updated with crc user.

**Comment by cfergeau** [comment]
(was typing this before your last comment)

Can you check `virsh -c qemu:///system pool-list -all`, and `virsh -c qemu:///system pool-dumpxml crc` if the first command shows a `crc` pool? I'm not sure we remove this pool with `crc cleanup`

Apart from this, the path to the VM files is relative to https://pkg.go.dev/os#UserHomeDir , which should do the right thing even in your setup.

**Comment by cfergeau** [comment]
You can remove this with `virsh -c qemu:///system pool-destroy crc;  virsh -c qemu:///system pool-undefine crc`, then everything should go back in order.

**Comment by praveenkumar** [comment]
@JiriHusak-lab Also don't close the issue if that https://github.com/code-ready/crc/issues/2785#issuecomment-933448067 solve your issue, looks like  we need to update our cleanup steps for libvirt.

**Comment by JiriHusak-lab** [comment]
BINGO. Thanks a lot. Christopher's advice moved me over this issue. Thanks.
I have some warnings from crc start I'd like to ask but they are not related to this issue so I will open another one to not mix up issues.
