### ISSUE TITLE
CRC Failed to update kubeconfig file

### ISSUE THREAD

**Issue by vimalk78** [code-ready/crc#2789]
Note: This appears to be an issue in my environment, rather than a bug in CRC

I have been using CRC for a long time, every now and then i update to a newer version of CRC. 
Using CRC version `CodeReady Containers version: 1.33.1+3cfaa10f`
I do `crc setup` and then `crc start -m 16384 -p ~/crc/pull-secret --log-level debug`
and i end up in this error

```
INFO Changing the password for the kubeadmin user 
DEBU Running SSH command: <hidden>                
DEBU SSH command succeeded                        
DEBU Waiting for availability of resource type 'clusterversion' 
DEBU retry loop: attempt 0                        
DEBU Running SSH command: timeout 5s oc get clusterversion --context admin --cluster crc --kubeconfig /opt/kubeconfig 
DEBU SSH command results: err: <nil>, output: NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.8.12    True        False         11d     Cluster version is 4.8.12 
DEBU NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.8.12    True        False         11d     Cluster version is 4.8.12 
DEBU Running SSH command: timeout 30s oc get clusterversion version -o jsonpath="{['spec']['clusterID']}" --context admin --cluster crc --kubeconfig /opt/kubeconfig 
DEBU SSH command results: err: <nil>, output:     
INFO Updating cluster ID...                       
DEBU Running SSH command: timeout 30s oc patch clusterversion version -p '{"spec":{"clusterID":"2554eb05-fe1b-4ba5-a5ff-542a4588f04d"}}' --type merge --context admin --cluster crc --kubeconfig /opt/kubeconfig 
DEBU SSH command results: err: <nil>, output: clusterversion.config.openshift.io/version patched 
DEBU Making call to close driver server           
DEBU (crc) Calling .Close                         
DEBU Successfully made call to close driver server 
DEBU Making call to close connection to plugin binary 
DEBU Making call to close driver server           
DEBU (crc) Calling .Close                         
DEBU Successfully made call to close driver server 
DEBU Making call to close connection to plugin binary 
DEBU (crc) DBG | time="2021-10-05T11:25:45+05:30" level=debug msg="Closing plugin on server side" 
Failed to update kubeconfig file: Failed to copy kubeconfig file: /home/vimalkum/.crc/machines/crc/kubeconfig: unable to find admin user in /home/vimalkum/.crc/cache/crc_libvirt_4.8.12/kubeconfig
```

later switching back to crc 1.32 and repeating the same steps i get same error

**Comment by vimalk78** [comment]
Adding crc.log
[crc.log](https://github.com/code-ready/crc/files/7283291/crc.log)

**Comment by vimalk78** [comment]
few days ago i was doing some multi arch rust development, and i had installed s390x and ppc64le specific tools/targets in cargo.

Is it possible that this has affected crc?

**Comment by cfergeau** [comment]
Could you check `oc --kubeconfig /home/vimalkum/.crc/cache/crc_libvirt_4.8.12/kubeconfig config get-users` and `oc --kubeconfig /home/vimalkum/.crc/cache/crc_libvirt_4.8.12/kubeconfig config get-contexts`? You could also try to remove `/home/vimalkum/.crc/cache/crc_libvirt_4.8.12/` and rerun `crc setup`

**Comment by vimalk78** [comment]
these commands do not work as the content of kubeconfig is
```
$ cat /home/vimalkum/.crc/cache/crc_libvirt_4.8.12/kubeconfig
apiVersion: v1
clusters: null
contexts: null
current-context: ""
kind: Config
preferences: {}
users: null
```

**Comment by cfergeau** [comment]
"something" must have corrupted it then, this is not the content it's supposed to have. In general, I would not recommend setting `KUBECONFIG` to `~/.crc/cache` as these files are private to crc and should never be modified.

**Comment by cfergeau** [comment]
We should probably make everything in `~/.crc/cache` read-only to see if it avoids this kind of unwanted changes.

**Comment by vimalk78** [comment]
the kubeconf in `~/.crc/cache` is not edited by me, it was generated like this

**Comment by cfergeau** [comment]
`~/.crc/cache/crc_libvirt_4.8.12/kubeconfig` is a pre-generated file shipped through `crc_libvirt_4.8.12.crcbundle`, and I just checked it's not empty.
If you keep `KUBECONFIG=~/.crc/cache/crc_libvirt_4.8.12/kubeconfig` set in your environment, some tool may have changed it.

**Comment by vimalk78** [comment]
i will unset this env variable and try again

**Comment by vimalk78** [comment]
i unset the `KUBECONFIG` environment variable , and tried to recreate crc with `crc start -m 16384 -p ~/crc/pull-secret --log-level debug`
but end up with same error

**Comment by vimalk78** [comment]
i am on Fedora 31. does this make a difference ?
```
$ cat /etc/system-release
Fedora release 31 (Thirty One)
```

**Comment by cfergeau** [comment]
> i unset the `KUBECONFIG` environment variable , and tried to recreate crc with `crc start -m 16384 -p ~/crc/pull-secret --log-level debug` but end up with same error

You'll need to start with `rm -rf ~/.crc/cache/crc_libvirt_4.8.12; crc setup`

**Comment by cfergeau** [comment]
> i am on Fedora 31. does this make a difference ?

In this case, probably not, but fedora 31 and fedora 32 are out of support (and fedora 33 only has a few months left).

**Comment by vimalk78** [comment]
after deleting the folder ``, and running `crc setup` and `crc start -m 16384 -p ~/crc/pull-secret --log-level debug`, the crc has started successfully. 
Perhaps the previous downloads were corrupted somehow? not sure.  

Thanks for all your help.
