### ISSUE TITLE
[BUG] crc version on windows prints incorrect URL for getting latest version 

### ISSUE THREAD

**Issue by jduimovich** [code-ready/crc#2812]
### General information

  *  Windows
  * Hypervisor: Hyper-V 
  * Did you run `crc setup` before starting it Yes ?
  * Running CRC on: Laptop 

## CRC version
```bash
# Put `crc version` output here
g:\bin>crc version
WARN A new version (1.34.0) has been published on  https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/crc/1.34.0/crc-windows-amd64.zip
CodeReady Containers version: 1.33.1+3cfaa10f
OpenShift version: 4.8.12 (bundle installed at C:\Program Files\CodeReady Containers\crc_hyperv_4.8.12.crcbundle)
```
  
The URL for the download seems to be invalid `https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/crc/1.34.0/crc-windows-amd64.zip `

**Comment by praveenkumar** [comment]
@jduimovich Thanks for creating the bug, we have to update the msi download link :(

**Comment by gbraad** [comment]
this is rather a known issue for now
