### ISSUE TITLE
[BUG]FAILED DNS query from the cluster.  

### ISSUE THREAD

**Issue by mikei121092** [code-ready/crc#2844]
### General information

Issue: 

I try to utilize crc start to utilize the crc service.  It was working yesterday.  However, I am now getting this issue:  

<img width="419" alt="CRC_issue" src="https://user-images.githubusercontent.com/62250291/142734571-460fcca6-b119-45ab-a319-2b7f438221e1.png">

A curl result of quay.io 

<img width="227" alt="crc2" src="https://user-images.githubusercontent.com/62250291/142734636-1f741861-40dd-4a3f-bf21-098d383b1a2f.png">

As a result of this issue I cannot access the OS image regestries and cannot utilize crc.  Please Help!  Thank you. 

  OS: Linux 
  Hypervisor: KVM
  Did you run `crc setup` before starting it (Yes/No)? YES
  Running CRC on: VM

## CRC version
CodeReady Containers version: 1.35.0+751824a9
OpenShift version: 4.9.5 (embedded in executable)
```

## CRC status
CRC VM:          Running
OpenShift:       Running (v4.9.5)
Disk Usage:      13.12GB of 32.74GB (Inside the CRC VM)
Cache Usage:     32.32GB

## CRC config
- consent-telemetry                     : no

## Host Operating System

RHEL 8.3

### Steps to reproduce

  1.  oc setup
  2.  oc start
  3. 
  4. 

### Expected
I expect it to start normally with the working DNS so I can utilize image repositories and what not and create apps in OS. 

### Actual
I receive an internal DNS issue.  As a result I cannot access any OS image repositories.  



I have tried to set the DNS config with crc as 1.1.1.1.  The issue persists.  I have deleted and reinstalled CRC and the issue persists.  

Please help me!  Thank you so much!!!  It is appreciated!

**Comment by mikei121092** [comment]
So I waited a day.  Woke up.  Fired up CRC and now it works.  Maybe an issue on the quay.io side for future reference?  Not sure but crc is fine.  

Advice:  if its related to DNS it seems to be saying it cant translate that domain.  And if you curl that domain and have issues, give it a day and try again.

**Comment by praveenkumar** [comment]
> So I waited a day. Woke up. Fired up CRC and now it works. Maybe an issue on the quay.io side for future reference? Not sure but crc is fine.
> 
> Advice: if its related to DNS it seems to be saying it cant translate that domain. And if you curl that domain and have issues, give it a day and try again.

This does seem to issue with dns, in future you might to try with `--nameserver` option.

**Comment by cfergeau** [comment]
Just a note, `HTTP/1.1 301 Moved Permanently` when using `curl quay.io` is expected. `curl -L` will follow redirections.
