### ISSUE TITLE
[BUG] CRC Setup Fails for OpenRC Init System

### ISSUE THREAD

**Issue by lannuttia** [code-ready/crc#2853]
### General information

  * OS: Linux
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop

## CRC version
```bash
CodeReady Containers version: 1.35.0+751824a9
OpenShift version: 4.9.5 (embedded in executable)
```
  
## CRC status
```bash
DEBU CodeReady Containers version: 1.35.0+751824a9 
DEBU OpenShift version: 4.9.5 (embedded in executable) 
DEBU Running 'crc status'                         
DEBU Checking file: /home/anthony/.crc/machines/crc/.crc-exist 
Machine does not exist. Use 'crc start' to create it
```

## CRC config
```bash
- consent-telemetry                     : yes
```

## Host Operating System
```bash
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
```

### Steps to reproduce

  1. Run `crc setup`

### Expected
`crc setup` works out of the box, provides an option to manually specify the init system to run setup for, or at least provides an option that allows you to bypass all the automatic systemd specific init system configuration logic.

### Actual
`crc setup` fails because there isn't a libvirtd systemd unit file. This is because my system doesn't use systemd as an init system.

### Logs

Before gather the logs try following if that fix your issue
```bash
INFO Checking if running as non-root              
INFO Checking if running inside WSL2              
INFO Checking if crc-admin-helper executable is cached 
INFO Checking for obsolete admin-helper executable 
INFO Checking if running on a supported CPU architecture 
INFO Checking minimum RAM requirements            
INFO Checking if crc executable symlink exists    
INFO Checking if Virtualization is enabled        
INFO Checking if KVM is enabled                   
INFO Checking if libvirt is installed             
INFO Checking if user is part of libvirt group    
INFO Checking if active user/process is currently part of the libvirt group 
INFO Checking if libvirt daemon is running        
WARN No active (running) libvirtd systemd unit could be found - make sure one of libvirt systemd units is enabled so that it's autostarted at boot time. 
INFO Starting libvirt service                     
INFO Using root access: Executing systemctl daemon-reload command 
Password: 
INFO Using root access: Executing systemctl start libvirtd 
Failed to start libvirt service
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by gbraad** [comment]
As per documentation we only support/know thisto work on Fedora, RHEL, CentOS and Ubuntu as distributions. Systemd is a requirement.

Are you on Gentoo?

You might be able to run some of the processes manually and skip the preflights that check for this.

**Comment by cfergeau** [comment]
> or at least provides an option that allows you to bypass all the automatic systemd specific init system configuration logic.

See `crc config` which will give a list of `skip-xxxx` options. You can then set the ones for the tests you don't need.
```
$ crc config set skip-xxxx true
```

**Comment by lannuttia** [comment]
> > or at least provides an option that allows you to bypass all the automatic systemd specific init system configuration logic.
> 
> See `crc config` which will give a list of `skip-xxxx` options. You can then set the ones for the tests you don't need.
> 
> ```
> $ crc config set skip-xxxx true
> ```

After following cfergeau's advice, I appear to have everything up and running. At the end of the day my config looks like this.

```
- consent-telemetry                     : yes
- skip-check-crc-dnsmasq-file           : true
- skip-check-daemon-systemd-sockets     : true
- skip-check-daemon-systemd-unit        : true
- skip-check-libvirt-installed          : true
- skip-check-libvirt-running            : true
- skip-check-network-manager-installed  : true
- skip-check-network-manager-running    : true
- skip-check-systemd-networkd-running   : true
```
The only thing that I think I wouldn't have been able to outright disable without at least attempting to run it first would be skip-check-crc-dnsmasq-file because I'm pretty sure that alters some NetworkManager configuration and tries to restart.

For anyone reading this in the future, the pertinent aspects of my setup is I am running Gentoo with OpenRC as the init system. I had KVM/QEMU, libvirt, and NetworkManager already working and configured before I tried to use `crc setup`. As far as I know, the only thing that fundamentally differentiated my system from the standard system that `crc` expects was the difference in init system.

At this point, the only thing that I need to do any additional research into to verify that everything actually works is the implications of skip-check-crc-dnsmasq-file and systemd-networkd not existing on my system. Worst case scenario, I might investigate migrating from OpenRC to systemd but I'm hoping it doesn't come to that.
