### ISSUE TITLE
Misleading message after changing preset

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#2859]
It currently says:
```
$ crc config set preset podman
"Changes to configuration property 'preset' are only applied when the CRC instance is created."
"If you already have a running CRC instance, then for this configuration change to take effect, delete the CRC instance with 'crc delete' and start it with 'crc start'."
```

but if the podman bundle is not available yet, `crc setup` will be needed.

**Comment by gbraad** [comment]
> but if the podman bundle is not available yet, crc setup will be needed.

Interesting to know how this is going to be messaged to the user. The tray/app needs to do the right thing too.
