### ISSUE TITLE
Improvements to bundle downloading

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#2860]
Miscellaneous things I wrote down when initially testing this:
- it's hard to recover from ctrl+c during initial bundle download, might be better to first download to a temp file, and then move it in place
- sha256sum is not checked if the file is already present
- when failing to unpack the bundle, we should fallback to trying to download it
- the bundle URL version and the version expected by crc are disconnected at the moment, would be nice to ensure they are consistent somehow

**Comment by cfergeau** [comment]
steps to reproduce the first item:
```
$ rm -rf ~/.crc/cache
$ crc setup
...
INFO Downloading crc_podman_libvirt_3.4.2.crcbundle 
...
<press ctrl+C during the download>

$ crc setup
...
INFO Extracting bundle: crc_podman_libvirt_3.4.2... 
crc-podman.qcow2: 34.00 MiB / 1.62 GiB Error getting bundle metadata: unexpected EOF
```
One need to manually remove the partially downloaded file to fix this.

**Comment by gbraad** [comment]
this has always been an issue. when the tray app is closed, this also results in partial files. no resume
