### ISSUE TITLE
disk resizing gets unexpectedly triggered when podman is used

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#2862]
With the podman preset:
```
$ crc delete && crc start
[...]
INFO Resizing /dev/vda4 filesystem                
```

This happens because the podman disk image is around 10GB, but crc resizes it to the default disk size for the OpenShift bundle, which is 31GiB.

**Comment by cfergeau** [comment]
https://github.com/cfergeau/crc/commit/d77f791fb15f7df326ffd54f4fb52daa81914e54 fixes it, but I wanted to explore something different before filing a PR for it.

**Comment by praveenkumar** [comment]
This is fixed on the snc side so closing this.
