### ISSUE TITLE
[Hold] Support podman preset with an OpenShift bundle?

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#2867]
At the moment this is forbidden, see 789fa3393ea7055da9355099bfea591a69dfcf80
and the conversation at https://github.com/code-ready/crc/pull/2824#discussion_r749472218

**Comment by gbraad** [comment]
For now we keep this choice tied to an image.

**Comment by cfergeau** [comment]
I know, but this issue can be used to list what is missing before we decide to support this.

**Comment by praveenkumar** [comment]
With openshift bundle which we ship is still have older version of podman and doesn't have all functionality (like podman-machine cni which allow networking) for those.
