### ISSUE TITLE
[Task] Returns a config option that is not possible to set on the platform

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#2868]
### General information

  * OS: Linux

## CRC version
Current dev and master branch
  
## CRC config
```bash
<none>
```

### Steps to reproduce

  1. `GET /api/config`

### Issue
The current API will return all settings that possible, which on Linux includes `autostart-tray`

Settings the value will however return:

```
Value 'true' for configuration property 'autostart-tray' is invalid, reason: Tray autostart is only supported on macOS and windows
```

It would be better to only return settings that are possible for the current (hosting) platform

**Comment by cfergeau** [comment]
Imo this is not an http API-level issue, but an option we should not expose at all on linux. The following should come up empty:
```
$ out/linux-amd64/crc config  |grep tray
* autostart-tray                             Automatically start the tray (true/false, default: true)
```

**Comment by gbraad** [comment]
> >  It would be better to only return settings that are possible for the current (hosting) platform

> Imo this is not an http API-level issue, but an option we should not expose at all on linux. 

confirms what I said. settings/config options not relevant for the platform should never be shown  or even errored on as:

```
Tray autostart is only supported on macOS and windows
```

It should respond as:

```
Configuration property 'autostart-tray' does not exist
```

**Comment by cfergeau** [comment]
This will be solved by https://github.com/code-ready/crc/pull/3009

**Comment by anjannath** [comment]
resolved for the `autostart-tray` config option via #3009
