### ISSUE TITLE
[Task] Add a way to distinguish if a value is default or what the default value is

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#2869]
### General information

  * OS: Linux

## CRC version
Current dev and master branch
  
## CRC config
```bash
<none>
```

### Steps to reproduce

  1. `GET /api/config`

### Issue
The current API will return all settings that possible, but does not indicate if the config is a default or not. 

` { autostart-tray: true, bundle: '/home/gbraad/.crc/cache/crc_libvirt_4.9.0.crcbundle', ... , nameserver: "", `

This means empty options are given or bundle, which is not explicitly set. It would be better to return settings that also includes what the default is or even if the default is used.

```json
   { nameserver: "",
       default: "" }, ...
```

```json
    { bundle: '/home/gbraad/.crc/cache/crc_libvirt_4.9.0.crcbundle', isDefault: true }, ...
```

This way we can also print this as a description or information in the React components for Electron and Cockpit module.

**Comment by gbraad** [comment]
Currently these have been defined in the Configuration component

**Comment by anjannath** [comment]
this is what the api returns with the changes in https://github.com/anjannath/crc/tree/config-defaults but not very clean
```json
{
  "Configs": {
    "bundle": {
      "value": "/Users/anjan/.crc/cache/crc_podman_hyperkit_3.4.4_amd64.crcbundle",
      "IsDefault": true,
      "defaultValue": "/Users/anjan/.crc/cache/crc_podman_hyperkit_3.4.4_amd64.crcbundle"
    },
    "consent-telemetry": {
      "value": "no",
      "IsDefault": false,
      "defaultValue": ""
    },
    "cpus": {
      "value": 2,
      "IsDefault": true,
      "defaultValue": 2
    },
    [...]
}
```

might be better to extend the `SettingValue` struct to also include a `DefaultValue` field, although the difference between `Setting` and `SettingValue` becomes a bit distorted after this:

https://github.com/code-ready/crc/blob/88a0aeeb5d89af1f37b4f8000a67b5c517a1a404/pkg/crc/config/types.go#L16-L29

**Comment by cfergeau** [comment]
> might be better to extend the SettingValue struct to also include a DefaultValue field, although the difference between Setting and SettingValue becomes a bit distorted after this:

I'd prefer not to go this way, `SettingValue` describes the current state of the key, while `Setting` describes its 'format'. The former can be changed at runtime, the latter cannot.
