### ISSUE TITLE
*.sha256 files published along with binaries are not properly formatted

### ISSUE THREAD

**Issue by dgolovin** [code-ready/crc#2871]
*.sha256 files published to https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/crc/ are not properly formatted. 

```shell
~/bin$ sha256sum -c *.sha256
sha256sum: crc-linux-amd64.tar.xz.sha256: no properly formatted SHA256 checksum lines found
```

Correct format includes sha256sum and filename 

```shell
~/bin$ sha256sum crc-linux-amd64.tar.xz
a4e4b011d7cfa08f47408554ee2e4f55254dcc3419380d843beb1c22977b1d9e  crc-linux-amd64.tar.xz
```

so output when running sha256sum to check file would be 

```shell
~/bin$ sha256sum -c crc-linux-amd64.tar.xz.sha256 
crc-linux-amd64.tar.xz: OK
```

**Comment by praveenkumar** [comment]
https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/crc/1.36.0/sha256sum.txt is correctly formatted, individual shasum files are just have sha256sum but not the file name which it should have. We will ask the RCM team to update it but meanwhile you can use this one.

**Comment by cfergeau** [comment]
I brought that up a few months ago with the team managing https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/crc/ (these files are automatically generated at upload time), and apparently some parts of our infrastructure rely on these files being in the current format. Not sure there is much we can do about this :-/

**Comment by dgolovin** [comment]
@praveenkumar @cfergeau thank you for explanation. I am just going to use sha256sum.txt. Closing.
