### ISSUE TITLE
[Tasks] Lists of task to do a dev branch alpha relase

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#2877]
This is initial tasks list which we have to do/perform to have an alpha release from dev branch.

- [ ] Bundle location (Right now on GCP)
- [ ] Installer for Mac/Windows ( As of now even in dev branch, installer contain the bundles and if we create installer without bundle then we need to change the bundle cache path from installed directory to default one so we can avoid permission error.
- [ ] No tray integration initially (we can hook it in later release mostly in beta)
- [ ] Try to do initial release for Linux/Mac.
- [ ] Document steps on wiki about how to use this dev release to try it out.
- [ ] Enable the telemetry by default for tech preview.

Update the process as we go on..

**Comment by cfergeau** [comment]
> As of now even in dev branch, installer contain the bundles and if we create installer without bundle then we need to change the bundle cache path from installed directory to default one so we can avoid permission error.

Do we change it completely? Or do we keep the option of shipping single installer for bundle + crc, but while having the possibility of downloading to ~/.crc/cache if bundle is missing?

**Comment by cfergeau** [comment]
- [ ] Add 'Known Issues' document to the wiki
- [ ] Add a big 'This is an experimental releases for testing purposes, please report any issues you find to  ....` banner every time(?) the binary is used

**Comment by praveenkumar** [comment]
> Do we change it completely? Or do we keep the option of shipping single installer for bundle + crc, but while having the possibility of downloading to ~/.crc/cache if bundle is missing?

We do need to change it completely because it doesn't make sense to add both bundle (podman + openshift) + crc as part of installer or even with default installer (where we only ship the opnshift bundle) and the user require the podman one.

**Comment by cfergeau** [comment]
I agree podman + openshift + crc do not make sense.
I can see a use case for shipping openshift + crc, but downloading the podman bundle if the user eventually decides to use podman. We'd also be shipping either crc standalone, or crc+podman for people who know from the start they only want podman.
