### ISSUE TITLE
[BUG-HELP needed] URLs not working after a reinstall of crc

### ISSUE THREAD

**Issue by xgxtbku** [code-ready/crc#2883]
### General information

  * OS: Linux 
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it: Yes
  * Running CRC on: Baremetal-Server

## CRC version
```bash
# 
CodeReady Containers version: 1.29.1+bc5f4409
OpenShift version: 4.7.18 (embedded in executable)
```
  
## CRC status
```bash
CRC VM:          Running
OpenShift:       Running (v4.7.18)
Disk Usage:      29.3GB of 106.8GB (Inside the CRC VM)
Cache Usage:     13.34GB
Cache Directory: /home/crcadmin/.crc/cache
```

## CRC config
```bash
# Put `crc config view` output here
```

## Host Operating System
```bash
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-polcy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### Steps to reproduce & Problem

Hello!
My openshift installation crashed and was not able to reach the webconsole after dozens of restarts. So I tried to fix it
1. crc delete
2. crc setup
3. crc start
4. The machine started the console is available. I am happy.
5. Started to add applications.
6. Added a java backend, postgres and it seems working but when I added a React application I realised none of my pods are reachable with the route what the webconsole generated for me.
7. If I try to open the https://currenciesfrontend-concurencies.apps-crc.testing/ it displays this:
![image](https://user-images.githubusercontent.com/78586452/146158118-9373ca21-63e8-4f79-b130-031390850d0a.png)
So i added the url to the local host file on the server and also on my local pc with the server ip to resolve the url. It worked before but now it dont.
I tried to ping the pods ip in the server pc it also responds with 100% lost packet.

### Expected
To be able to open applications with routes, urls.

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
@xgxtbku you are using a very old version of crc `CodeReady Containers version: 1.29.1+bc5f4409
OpenShift version: 4.7.18 (embedded in executable)`  can you try with latest one and also as per screenshot looks like the pod is not serving to this route so better to check that application pod logs.

**Comment by xgxtbku** [comment]
@praveenkumar i got this error when i downloaded and deleted the pods and started to cleanup:
INFO Removing CRC Machine Instance directory      
unexpected AppArmor template file /etc/apparmor.d/libvirt/TEMPLATE.qemu, cannot configure it automatically

**Comment by xgxtbku** [comment]
@praveenkumar upgraded to the latest version still having the url issue.

**Comment by praveenkumar** [comment]
@xgxtbku I still think this is not the  crc specific issue but the application which you are using. CRC job is to provide you the cluster locally and that is working, now if your app is not coming up that means you need to check the application logs what causing the issue.

**Comment by xgxtbku** [comment]
> @xgxtbku I still think this is not the crc specific issue but the application which you are using. CRC job is to provide you the cluster locally and that is working, now if your app is not coming up that means you need to check the application logs what causing the issue.

But I am not able to ping the app's ip what the OS created from the same server.

**Comment by praveenkumar** [comment]
> But I am not able to ping the app's pod ip what the OS created from the same server.

As I said if you need to debug the app, check if pod is running, if it running check if that is serving and all the stuff. We (as crc team) can't do much what's going on the app side.

**Comment by xgxtbku** [comment]
> > But I am not able to ping the app's pod ip what the OS created from the same server.
> 
> As I said if you need to debug the app, check if pod is running, if it running check if that is serving and all the stuff. We (as crc team) can't do much what's going on the app side.

Solved it somehow. It needed time to be able to recognise the 3000->8080 port forward. 
Please close this. Thanks for the help!
