### ISSUE TITLE
[Task] Add hostname entry for the podman VM to the hosts table

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#2896]
We add records to the hosts table to allow the lookup of the VM by the hostname.
We do not add records for the Podman preset. This makes the console commands dependent of the `crc ip` command or #2895.

**Comment by gbraad** [comment]
https://github.com/code-ready/tray-electron/blob/668ddc234cd9963177350e00676bd5acbb816a2c/main.js#L486

```
const podmanHost = "podman.crc.testing";
```

**Comment by gbraad** [comment]
Something similar to this is needed for podman https://github.com/code-ready/crc/blob/acbaf2bf1b412d640d354db0f084930196d16255/pkg/crc/services/dns/dns.go#L136

**Comment by praveenkumar** [comment]
Part of https://github.com/code-ready/crc/pull/2899 one
