### ISSUE TITLE
template-service-broker does not work

### ISSUE THREAD

**Issue by rbaumgar** [code-ready/crc#291]
CRC 0.88
tried to install Template Service Broker to get all templates in the Developer Catalog
create namespace openshift-template-service-broker
Go to OperatorHUB: select OpenShift Template Service Broker Operator, install
create Template Service Broker
when the pod(apiserver-1-xj6ln) is running
message: >- Failed to find exact match for servicecatalog.k8s.io/v1beta1.ClusterServiceBroker by [kind, name, singularName, shortNames]
And no templates are shown in the Developer Catalog

**Comment by praveenkumar** [comment]
@rbaumgar does that work on a `4.1.3` cluster which is deployed over AWS side?

**Comment by rbaumgar** [comment]
my cluster is running libvirt. But I had a cluster running on AWS with a running and working template service broker...

**Comment by praveenkumar** [comment]
@rbaumgar We are not able to test out each an every scenario at this moment on CRC side but expectionation should be if you have enough resource on the host and provided to CRC also and your application doesn't have hard requirement on multi node it should be supported. Please put down (or link to a doc) how you are trying to install it, we will also try to reproduce it and figure out what actually failing.

**Comment by kdubois** [comment]
@rbaumgar This is working fine for me.  Did you install the service catalog first?
https://docs.openshift.com/container-platform/4.1/applications/service_brokers/installing-service-catalog.html

**Comment by praveenkumar** [comment]
@kdubois thanks for confirming, I am closing this issue now, @rbaumgar let us know if there is still something breaking for you and we reopen it.

**Comment by rbaumgar** [comment]
@kdubois @praveenkumar you are right. When service catalog is installed template service broker works fine.
