### ISSUE TITLE
error: dial tcp: lookup api.crc.testing on 192.168.86.1:53: no such host

### ISSUE THREAD

**Issue by shuawest** [code-ready/crc#292]
I'm getting the startup error [1] on OSX and I'm unable to login to the cluster using oc. After previous troubleshooting, I did disable my wired ethernet port [2], and it cleared up crc setup errors I was having before. 

I am able to log into the web portal (https://console-openshift-console.apps-crc.testing) after startup. However I cannot log in using the oc command to the target address "https://api.crc.testing:6443" as shown the output below. 

Environment:
crc: 0.88.0 for mac
image: crc_vbox_4.1.3.tar.xz
virt:  virtualbox
os:  macOS Majoave 10.14.5
vbox version: 6.0.8 r130520 (Qt5.6.3) 

[1] 
Joshs-MacBook-Pro:crc jowest$ crc setup
INFO Caching oc binary
INFO Setting up virtualization
INFO Setting file permissions for /etc/resolver/testing
INFO Setting file permissions for /etc/resolv.conf
Password:
Joshs-MacBook-Pro:crc jowest$ crc start -d virtualbox -b crc_vbox_4.1.3.tar.xz
INFO Checking if oc binary is cached
INFO Checking if VirtualBox is Installed
INFO Checking file permissions for /etc/resolver/testing
INFO Checking file permissions for /etc/resolv.conf
INFO Extracting the crc_vbox_4.1.3.tar.xz Bundle tarball ...
INFO Creating VM ...
INFO Restarting the host network
WARN Host is not connected to internet.
INFO Check internal and public dns query ...
INFO Copying kubeconfig file to instance dir ...
INFO Starting OpenShift cluster ... [waiting 3m]
INFO To access the cluster using 'oc', run 'oc login -u kubeadmin -p ehbg7-zu5i6-JKt7V-PvJsm https://api.crc.testing:6443'
INFO Access the OpenShift web-console here: https://console-openshift-console.apps-crc.testing
INFO Login to the console with user: kubeadmin, password: ehbg7-zu5i6-JKt7V-PvJsm
ERRO Error approving the node csr Not able to get csr names (exit status 1 : Unable to connect to the server: dial tcp: lookup api.crc.testing on 192.168.86.1:53: no such host
)
Joshs-MacBook-Pro:crc jowest$ oc login -u kubeadmin -p ehbg7-zu5i6-JKt7V-PvJsm https://api.crc.testing:6443
error: dial tcp: lookup api.crc.testing on 192.168.86.1:53: no such host - verify you have provided the correct host and port and that the server is currently running.

[2] 
CRC 4.1.0 not able to start on OSX with enabled WIFI and wired network
https://github.com/code-ready/crc/issues/225
#225 opened 21 days ago by skabashnyuk • updated yesterday

**Comment by shuawest** [comment]
Also once I log into the web console is it clearl not started properly, as the webpage is in constant reload post login, and the page states: "Oh no! Something went wrong.
There was an error logging you in. Please log out and try again."

**Comment by praveenkumar** [comment]
@shuawest what is the OSx version and does your `/etc/resolv.conf` contains the VM IP which should be also present `/etc/resolver/testing` file?

**Comment by wrichter** [comment]
See also #293 I found that /etc/resolv.conf gets overwritten with the default values during VM start

**Comment by cfergeau** [comment]
yes, it's the same as #293
