### ISSUE TITLE
Getting error while start the crc on macOS

### ISSUE THREAD

**Issue by sudhirverma** [code-ready/crc#293]
macOS version: 10.14.5

steps: 
1. ./crc setup
2. ./crc start -d virtualbox -b crc_vbox_4.1.3.tar.xz

Error:
**While connecting on VPN**
``` 
ERRO Error approving the node csr Not able to get csr names (exit status 1 : Unable to connect to the server: dial tcp: lookup api.crc.testing on 10.68.5.26:53: no such host
) 
```

**While not connected on VPN**
```
$ cat /etc/resolver/testing
port 53
nameserver 192.168.130.100

$ ls -l /etc/resolv.conf
lrwxr-xr-x  1 root  wheel  22 Sep 21  2018 /etc/resolv.conf -> ../var/run/resolv.conf


$ ./crc start -d virtualbox -b crc_vbox_4.1.3.tar.xz

WARN Unable to read host resolv file (cat: /etc/resolv.conf: No such file or directory
 : exit status 1) 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13cafd1]

goroutine 1 [running]:
github.com/code-ready/crc/pkg/crc/services/dns.waitForNetwork()
    /home/prkumar/work/github/crc/pkg/crc/services/dns/dns_darwin.go:109 +0x61
github.com/code-ready/crc/pkg/crc/services/dns.restartNetwork(0x161277f, 0x1b, 0x0)
    /home/prkumar/work/github/crc/pkg/crc/services/dns/dns_darwin.go:96 +0x556
github.com/code-ready/crc/pkg/crc/services/dns.runPostStartForOS(0x1602b36, 0x3, 0x16b01a0, 0xc000aeb820, 0xc0001521f8, 0x3, 0xc0001521fb, 0x3, 0xc00015e280, 0x19, ...)
    /home/prkumar/work/github/crc/pkg/crc/services/dns/dns_darwin.go:46 +0x1c9
github.com/code-ready/crc/pkg/crc/services/dns.RunPostStart(0x1602b36, 0x3, 0x16b01a0, 0xc000aeb820, 0xc0001521f8, 0x3, 0xc0001521fb, 0x3, 0xc00015e280, 0x19, ...)
    /home/prkumar/work/github/crc/pkg/crc/services/dns/dns.go:60 +0x307
github.com/code-ready/crc/pkg/crc/machine.Start(0x1602b36, 0x3, 0x7ffeefbffbe5, 0x15, 0x7ffeefbffbd7, 0xa, 0x2000, 0x4, 0x0, 0x0, ...)
    /home/prkumar/work/github/crc/pkg/crc/machine/machine.go:177 +0x21bf
github.com/code-ready/crc/cmd/crc/cmd.runStart(0xc00013aac0, 0x0, 0x4)
    /home/prkumar/work/github/crc/cmd/crc/cmd/start.go:56 +0x24a
github.com/code-ready/crc/cmd/crc/cmd.glob..func9(0x1a79260, 0xc00013aac0, 0x0, 0x4)
    /home/prkumar/work/github/crc/cmd/crc/cmd/start.go:32 +0x3f
github.com/spf13/cobra.(*Command).execute(0x1a79260, 0xc00013aa40, 0x4, 0x4, 0x1a79260, 0xc00013aa40)
    /home/prkumar/work/github/practice/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0x1a7a0a0, 0x14, 0x0, 0x0)
    /home/prkumar/work/github/practice/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x1a7a0a0, 0xc00019df68, 0x14df682)
    /home/prkumar/work/github/practice/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x2b
github.com/code-ready/crc/cmd/crc/cmd.Execute()
    /home/prkumar/work/github/crc/cmd/crc/cmd/root.go:65 +0x2d
main.main()
    /home/prkumar/work/github/crc/cmd/crc/main.go:10 +0x25
```

**Comment by gbraad** [comment]
Networking related: openvpn is used on macOS. When the user connects, the content of `/etc/resolv.conf` is overwritten by the VPN configuration. It fails when disconnected as the file is missing

**Comment by jsliacan** [comment]
When starting CRC on RHEL 8, this error shows up. Seems related but not the same. I thought it might be useful to record it here.

```
05:00:06.090420  stdout: level=error msg="Error approving the node csr Not able to get csr names (exit status 1 : Unable to connect to the server: net/http: TLS handshake timeout\n)"
```

**Comment by praveenkumar** [comment]
As a workaround till we are putting a fix around it, try to follow below steps.

```
$ crc delete
$ cat /etc/resolv.conf
<-- Copy the content -->
$ sudo rm /etc/resolv.conf
$ sudo vi /etc/resolv.conf => put the content back
$ crc setup
$ crc start -b <bundle_location> -d virtualbox
```

**Comment by wrichter** [comment]
I find that the crc start / "restart host network" step seems to overwrite resolv.conf, taking out the name server. I had to add the name server as first entry to my IP configuration via OSX System Preferences -> Network -> <My wired network connection> -> Advanced -> DNS

**Comment by cfergeau** [comment]
> I find that the crc start / "restart host network" step seems to overwrite resolv.conf, taking out the name server. I had to add the name server as first entry to my IP configuration via OSX System Preferences -> Network -> -> Advanced -> DNS

On which network interface did you do it? This can easily be done from the command line, so this could be an option for us (`networksetup -setdnsservers networkservice dns1 [dns2] [...]`).
See also https://github.com/openshift/origin/issues/23266 for a way to fix this on the `oc` side.

**Comment by wrichter** [comment]
> On which network interface did you do it? This can easily be done from the command line, so this could be an option for us (`networksetup -setdnsservers networkservice dns1 [dns2] [...]`).
> See also [openshift/origin#23266](https://github.com/openshift/origin/issues/23266) for a way to fix this on the `oc` side.

I used a wired ethernet connection (dev name is en5) provided by the monitor via USB-C/Thunderbolt

**Comment by cfergeau** [comment]
Quick summary, as there are 3 different issue here:
- on Sudhir system, /etc/resolv.conf can't be read causing `WARN Unable to read host resolv file (cat: /etc/resolv.conf: No such file or directory: exit status 1)`. I don't know why this happens
- in such situations, crc's error handling is lacking and causes a crash, this is addressed by PR #300 
- when /etc/resolv.conf exists and is successfully modified, the file gets overwritten during the network restart crc triggers, which then causes the `Error approving the node csr` message. One potential fix is to build oc with native macos resolver support (in other word, build it with CGO_ENABLED=1)

**Comment by wrichter** [comment]
This problem no longer occurs on 0.89.0-alpha-4.1.6+8e9c40e OSX/hyperkit.

**Comment by praveenkumar** [comment]
This is already fixed so I am closing it.
