### ISSUE TITLE
CI:  Add step to enable proxy port from firewall

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#2934]
For some environment when firewalld service is enable then proxy scenario is failing because  port `3128` is not part of libvirt firewall rules and proxy server is not accessible by instance. We should add it as part of step just to avoid this failure.

**Comment by cfergeau** [comment]
Fwiw, a more detailed description of the issue/failing setup will be needed, on my test machine:
```
$ sudo firewall-cmd  --info-zone=libvirt
libvirt (active)
  target: ACCEPT
  icmp-block-inversion: no
  interfaces: crc virbr0
  sources: 
  services: dhcp dhcpv6 dns ssh tftp
  ports: 
  protocols: icmp ipv6-icmp
  forward: no
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	rule priority="32767" reject
```
but I can connect nonetheless from the VM to port 3128 of another physical machine in the same local network as the host.

**Comment by adrianriobo** [comment]
On the qe environment where we saw a `fail` related to the proxy, the firewalld setup is exactly the same:

```bash
sudo firewall-cmd  --info-zone=libvirt
libvirt (active)
  target: ACCEPT
  icmp-block-inversion: no
  interfaces: crc virbr0 virbr1
  sources: 
  services: dhcp dhcpv6 dns ssh tftp
  ports: 
  protocols: icmp ipv6-icmp
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	rule priority="32767" reject
```

**Comment by cfergeau** [comment]
where is the proxy running?

**Comment by adrianriobo** [comment]
The proxy is running as a container on the same host  where crc is running

**Comment by cfergeau** [comment]
I ran additional tests, starting `nc --listen` in a container running on the host, then I can reach it from the VM by using either the external IP address of my host, or 192.168.130.1, and both were fine.
So either my setup is more permissive than a default install, and but I don't remember making changes, or the problem which is being seen is not related to firewall rules.

**Comment by adrianriobo** [comment]
>So either my setup is more permissive than a default install  

It is not, according to the setup on the machine showing the issue: https://github.com/code-ready/crc/issues/2934#issuecomment-1009850565 during testing
