### ISSUE TITLE
Spike streaming JSON for `crc setup`.

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#2935]
When running `crc setup` information is streamed using `stdout` and only the end result is shown. This currently causes confusion, as messages like https://github.com/code-ready/crc/issues/2969 are shown; `you can now run 'crc start' to start`. This would direct a UI user to issue an unnecessary command from a command line.

It would be best to return the preflight and fixes from `crc setup` as a stream of JSON fragments, that can be interpreted by the tray/app and display instead of the command output. This is needed for code-ready/tray-electron#114

**Comment by gbraad** [comment]
Moved to next sprint.

**Comment by gbraad** [comment]
This is needed for https://github.com/code-ready/tray-electron/issues/114

**Comment by gbraad** [comment]
Ideally this needs the step streamed BEFORE the result is known, and followed by the actual state is finished (passed/failed)

**Comment by cfergeau** [comment]
Maybe the progress can only be shown for very long operations (download and uncompress), and all other operations don't need a progress bar because they are very fast?
