### ISSUE TITLE
[BUG] Cannot access service exposed as a NodePort

### ISSUE THREAD

**Issue by arapulido** [code-ready/crc#2938]
### General information

  * OS: macOS
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: VM (hyperkit)

## CRC version
```bash
CodeReady Containers version: 1.37.0+3876d27d
OpenShift version: 4.9.10 (bundle installed at /Applications/CodeReady Containers.app/Contents/Resources/crc_hyperkit_4.9.10.crcbundle)
```
  
## CRC status
```bash
DEBU CodeReady Containers version: 1.37.0+3876d27d
DEBU OpenShift version: 4.9.10 (bundle installed at /Applications/CodeReady Containers.app/Contents/Resources/crc_hyperkit_4.9.10.crcbundle)
DEBU Running 'crc status'
DEBU Checking file: /Users/ara.pulido/.crc/machines/crc/.crc-exist
DEBU Checking file: /Users/ara.pulido/.crc/machines/crc/.crc-exist
DEBU Found binary path at /Applications/CodeReady Containers.app/Contents/Resources/crc-driver-hyperkit
DEBU Launching plugin server for driver hyperkit
DEBU Plugin server listening at address 127.0.0.1:59583
DEBU () Calling .GetVersion
DEBU Using API Version 1
DEBU () Calling .SetConfigRaw
DEBU () Calling .GetMachineName
DEBU (crc) Calling .GetState
DEBU (crc) Calling .GetBundleName
DEBU Running SSH command: df -B1 --output=size,used,target /sysroot | tail -1
DEBU Using ssh private keys: [/Users/ara.pulido/.crc/machines/crc/id_ecdsa /Users/ara.pulido/.crc/cache/crc_hyperkit_4.9.10/id_ecdsa_crc]
DEBU SSH command results: err: <nil>, output: 32737570816 19453972480 /sysroot
DEBU Unexpected operator status for etcd: RecentBackup
DEBU Making call to close driver server
DEBU (crc) Calling .Close
DEBU Successfully made call to close driver server
DEBU Making call to close connection to plugin binary
CRC VM:          Running
OpenShift:       Running (v4.9.10)
Disk Usage:      19.45GB of 32.74GB (Inside the CRC VM)
Cache Usage:     25.68GB
Cache Directory: /Users/ara.pulido/.crc/cache
```

## CRC config
```bash
- consent-telemetry                     : no
```

## Host Operating System
```bash
ProductName:	macOS
ProductVersion:	11.6.1
BuildVersion:	20G224
```

### Steps to reproduce

  1. Create a service with a NodePort exposed
  2. Try to access the service from the laptop at localhost:NodePort

### Expected

The service is accessible

### Actual

I cannot access the service in the NodePort directly.

If I ssh into the VM, the service can be accessed at localhost:NodePort successfully.

How can I do the same from outside the VM?

**Comment by cfergeau** [comment]
This is a limitation of the usermode networking used by crc. The port can probably be opened manually with
(did not test this, so probably only approximate) `curl -X POST -d '{"local": "127.0.0.1:6443", "remote": "192.168.127.2:6443"}'  --unix-socket ~/.crc/crc-http.sock http:/unix/network/services/forwarder/expose` with `6443` replaced by the port you are trying to open.

**Comment by I-nebukad-I** [comment]
I have the same problem under Windows. Would the proposed solution work there too?

Is there a way to open the ports permanently?

As I understand port 80 and port 2222 are exposed on the host machine. Would the same method not work for NodePorts?

**Comment by cfergeau** [comment]
>  Would the proposed solution work there too?

Yes something similar should work on Windows.

> As I understand port 80 and port 2222 are exposed on the host machine. Would the same method not work for NodePorts?

Port 80 and port 2222 are exposed on the host machine because the equivalent of this `curl` command is hardcoded in `crc` source code when the daemon starts up
https://github.com/code-ready/crc/blob/master/pkg/crc/machine/vsock.go

> Is there a way to open the ports permanently?

At the moment, this is not possible.

**Comment by cfergeau** [comment]
Maybe `oc port-forward` could also help to work around this.
