### ISSUE TITLE
Create .crc-exists in generic code

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#294]
Currently, hyperkit will always recreate the disk image from the cache because libmachine does not detect the machine has already been created. The detection is done by checking for ~/.crc/machines/crc/.crc-exists existence, which machine-driver-hyperkit is not creating. However since this file is needed by all machine drivers, we can create it in the generic libmachine code.

**Comment by praveenkumar** [comment]
This is machine and driver specific changes, I would prefer that to part of the driver instead putting it in the crc side.

- https://github.com/code-ready/machine-driver-libvirt/blob/master/libvirt.go#L300-L301
- https://github.com/code-ready/machine/blob/master/drivers/virtualbox/virtualbox.go#L281-L282

**Comment by cfergeau** [comment]
I can move it to machine/libmachine, closer to the existence check in `machine/libmachine/persist/filestore.go`
Since it's generic code which is using the file existence to decide whether to recreate the VM or not, I think it's better to have the file creation in generic code too rather than having to duplicate it in each machine driver.

**Comment by cfergeau** [comment]
I've moved the creation of the file to `machine/libmachine/persist/filestore.go` in Store.Save() (so this issue would fit better there). One potential issue with that is that Store.Save() is called quite early in the VM creation process, so the `.crc-exist` file will be created earlier than before.

**Comment by praveenkumar** [comment]
@cfergeau can we close this issue from this repo then?
