### ISSUE TITLE
`crc cleanup` command does not remove the tray/app on macOS

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/crc#2947]
Testing the dev tech preview version checking the `crc cleanup` command it was observed that it is not removing the tray on macos anymore. Previous versions for crc remove it so this feature should be paired or re defined.

**Comment by anjannath** [comment]
at the moment `crc cleanup` doesn't handle the closing/killing of the tray app, it is the users responsibility to close the tray before running `crc cleanup`
