### ISSUE TITLE
Unexpected behavior for upgrading on mac

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/crc#2948]
Unexpected behavior for upgrading on mac. After installer finishes old CodeReady Containers app (old tray) still accessible on /Applications (new react on /Applications/crc-tray)

**Comment by praveenkumar** [comment]
As part of mac package looks like it have different localization files and during the installation of pkg it doesn't replace the existing installed `/Applications/CodeReady Containers.app` but create `/Applications/CodeReady Containers.localized` .

**Comment by adrianriobo** [comment]
Also, trying to re-install it, it seems it does not override the folder `/Applications/CodeReady Containers.localized` , as trying a second installation I end up with: `/Applications/CodeReady Containers.localized` and `CodeReady Containers-1.localized`

**Comment by gbraad** [comment]
This might be related to a missing 'clean' ?

**Comment by praveenkumar** [comment]
https://matthew-brett.github.io/docosx/flat_packages.html have details about how we are creating the package file on mac and we did try to add preinstall script but that still not working.

**Comment by anjannath** [comment]
I suspect this is because we change the `CFBundleIdentifier` for the tray in the next release, to correctly identify versions of the same application it uses that key.

I tested by creating two versions (bumping tray version no.) by keeping the same `CFBundleIdentifier` and its correctly replacing the previous version inside `/Applications`

**Comment by praveenkumar** [comment]
@anjannath you mean we used to have `com.redhat.codeready.containers` and then we changed it to `com.electron.crc-tray` which caused this issue?

**Comment by gbraad** [comment]
@anjannath You confirmed that this is resolved with https://github.com/code-ready/tray-electron/pull/161 ?

**Comment by anjannath** [comment]
@gbraad Yes, this is resolved, closing
