### ISSUE TITLE
[Bug] pullsecret defined API call should be preset aware

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#2950]
The current API call to determine if the pull-secret is given, is based on the openshift preset.
When we would use this in the tray, the API could possibly prevent the podman preset to start when the pull-secret is not defined.

This API call introduced to prevent the slow startup, as the pull-secret preflight check follows quite late. It would be quicker to check if the puyll-secret is there or not, provide a popup and continue.

The suggestion would be to make this API call aware of the preset and check if pull-secret is needed, based on this, and if defined when necessary. This way the tray does not need to check the configuration and preset value to determine this. It should not have to be aware of this logic.

This is needed for: https://github.com/gbraad/crc-tray-electron/commit/2b5e773d36dd6499fb2fd6efd5f30db312143707#r64088220 which solves: https://github.com/code-ready/tray-electron/issues/61

**Comment by praveenkumar** [comment]
@gbraad the `/pull-secret` api is preset aware, I tested with curl and getting correct response.

```
✗ ./crc config view
- consent-telemetry                     : no
- network-mode                          : user
- preset                                : podman

✗ curl -IXGET --unix-socket ~/.crc/crc-http.sock http:/c/api/pull-secret  
HTTP/1.1 200 OK
Date: Tue, 18 Jan 2022 14:09:18 GMT
Content-Length: 0

✗ ./crc config unset preset
Successfully unset configuration property 'preset'
✗ ./crc config view        
- consent-telemetry                     : no
- network-mode                          : user
✗ curl -IXGET --unix-socket ~/.crc/crc-http.sock http:/c/api/pull-secret  
HTTP/1.1 404 Not Found
Date: Tue, 18 Jan 2022 14:13:27 GMT
Content-Length: 61
Content-Type: text/plain; charset=utf-8
```

**Comment by gbraad** [comment]
The API call is correctly aware of the preset. I believe the issues, around not starting, are caused by #2949 Segment related timeouts.

**Comment by gbraad** [comment]
It seems this does not always returned the expected value. I've seen two reports about this sometimes sending a 'not defined' (or perhaps an error?) and a reported case #3003

**Comment by gbraad** [comment]
@anjannath can you add your findings here?

**Comment by cfergeau** [comment]
Unclear if this is still an issue or not?
