### ISSUE TITLE
[BUG] Error running post start: Post "http://unix/remove": open \\.\pipe\crc-admin-helper: The system cannot find the file specified.

### ISSUE THREAD

**Issue by rludva** [code-ready/crc#2957]
### General information

  * OS: Windows
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it? Yes
  * Running CRC on: Laptop

## CRC version
```bash
D:\ocpcrc138>crc version
CodeReady Containers version: 1.38.0+659b2cbd
OpenShift version: 4.9.12 (bundle installed at D:\ocpcrc138\crc_hyperv_4.9.12.crcbundle)
```
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
// waiting for this output
```

## CRC config
```bash
# Put `crc config view` output here
// not any custom crc config
```

## Host Operating System
```bash
# Put the output of `systeminfo` in case of Windows
https://gist.github.com/rludva/af85ca0647df24bff996d3c898ff85e6
```

### Expected
CRC will start without any issue.

### Actual
There is an error during crc start:
```bash
INFO Updating authorized keys...
Error running post start: Post "http://unix/remove": open \\.\pipe\crc-admin-helper: The system cannot find the file specified.
```

### crc setup/start logs 
https://gist.github.com/rludva/978abd207e5bb29b4379e2a3ce463d05

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by cfergeau** [comment]
How was crc installed? admin-helper is supposed to be installed by the msi installer. It can be seen in the list of processes or services once it is installed.
The `crc start` logs are not really useful, better to run `crc stop` or `crc delete` and re-running `crc start --log-level debug`
