### ISSUE TITLE
crc should remove the ip it added to /etc/hosts when the VM is not running

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#296]
Currently when starting a VM, we add VM IP to /etc/resolv.conf so that it can use the DNS server running in our instance. However, when the VM is stopped/destroyed, we never remove the entry, even if the DNS server is no longer reachable.

**Comment by praveenkumar** [comment]
@cfergeau we are now not using `/etc/resolv.conf` can we just close this issue ?

**Comment by cfergeau** [comment]
We are still using it on macos, aren't we?

**Comment by cfergeau** [comment]
> We are still using it on macos, aren't we?

We are now using /etc/hosts, which should be similarly cleaned up.

**Comment by gbraad** [comment]
Stop and (re)start cleanup should still be considered.
