### ISSUE TITLE
[BUG] Root path propagation set to PRIVATE

### ISSUE THREAD

**Issue by bcaton85** [code-ready/crc#2968]
### General information

  * OS: macOS
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it (Yes)
  * Running CRC on: Laptop

## CRC version
```bash
CodeReady Containers version: 1.37.0+3876d27d
OpenShift version: 4.9.10 (bundle installed at /Applications/CodeReady Containers.app/Contents/Resources/crc_hyperkit_4.9.10.crcbundl
```
  
## CRC status
```bash
DEBU CodeReady Containers version: 1.37.0+3876d27d 
DEBU OpenShift version: 4.9.10 (bundle installed at /Applications/CodeReady Containers.app/Contents/Resources/crc_hyperkit_4.9.10.crcbundle) 
DEBU Running 'crc status'                         
DEBU Checking file: /Users/bcaton/.crc/machines/crc/.crc-exist 
DEBU Checking file: /Users/bcaton/.crc/machines/crc/.crc-exist 
DEBU Found binary path at /Applications/CodeReady Containers.app/Contents/Resources/crc-driver-hyperkit 
DEBU Launching plugin server for driver hyperkit  
DEBU Plugin server listening at address 127.0.0.1:50171 
DEBU () Calling .GetVersion                       
DEBU Using API Version 1                          
DEBU () Calling .SetConfigRaw                     
DEBU () Calling .GetMachineName                   
DEBU (crc) Calling .GetState                      
DEBU (crc) DBG | time="2022-01-25T09:05:23-05:00" level=debug msg="hyperkit pid 2490 missing from process table" 
DEBU (crc) Calling .GetBundleName                 
DEBU Making call to close driver server           
DEBU (crc) Calling .Close                         
DEBU Successfully made call to close driver server 
DEBU Making call to close connection to plugin binary 
DEBU (crc) DBG | time="2022-01-25T09:05:23-05:00" level=debug msg="Closing plugin on server side" 
CRC VM:          Stopped
OpenShift:       Stopped (v4.9.10)
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     12.64GB
Cache Directory: /Users/bcaton/.crc/cache

```

## CRC config
```bash
- consent-telemetry                     : no
```

## Host Operating System
```bash
ProductName:	macOS
ProductVersion:	11.6.1
BuildVersion:	20G224
```

### Steps to reproduce

  1. Have CRC running: `crc start`
  2. In the console go to nodes -> select the only node -> terminal
  3. In the terminal run the chroot /host command 
  4. Run `findmnt -o PROPAGATION /` and find the propagation set to private:
  ```
PROPAGATION
private
  ```

### Expected
Output should be 
  ```
PROPAGATION
shared
  ```

### Actual
  ```
PROPAGATION
private
  ```

This relates to running rootless podman in CRC, which throws warnings because the root path is not set to shared propagation. [Here is the original issue raised with buildah.](https://github.com/containers/buildah/issues/3726)

**Comment by gbraad** [comment]
You are referring to a setting for the OpenShift image that is not correctly set. This image wasn't intended to be used for podman use. This is the reason why we pulled the support of this for now. The dev-preview uses FCOS instead. Can you have a look at this?

https://github.com/code-ready/crc/releases/tag/dev-1.99.1

**Comment by bcaton85** [comment]
Okay makes sense. The use case was to test unprivileged and rootless podman builds running in a pod in Openshift. This works but gives the warnings seen in the buildah issue. It seems that it's something that will be resolved in a future release.

**Comment by benyaminl** [comment]
Jump wanna bump, this also raised on WSL Linux (any distro), but only once when the WSL boot up. Never seen this on old podman.

**Comment by benyaminl** [comment]
@gbraad @bcaton85 so this is the end?
