### ISSUE TITLE
[Task] Confusing message from `crc setup` shown in the output of the onboarding

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#2969]
The following message confuses people who run the dev preview.

`Your system is correctly setup for using CodeReady Containers, you can now run 'crc start' to start the OpenShift cluster`

This is shown as part of the `Running setup` screen in the new tray/desktop application:

![image](https://user-images.githubusercontent.com/1894/151106607-2db09e5d-8254-4617-84b3-488d26adb79b.png)

Since we aren't suppressing this output yet, until resolved in https://github.com/code-ready/tray-electron/issues/114 we need to either change the message or prevent this from being shown.

**Comment by cfergeau** [comment]
The last message is confusing, but all the logs before it are imo also not great ;) A spinner with just "Preparing your system for crc use (this might take a few minutes)" , and a way to see the logs in case of failure might be better. Then we can add a proper "downloading bundle" + progress bar when we get a clearer idea how to achieve this.

**Comment by gbraad** [comment]
@cfergeau I agree...

A spinner with "Reticulating splines" conveys more meaning ;-)

**Comment by gbraad** [comment]
Currently only a spinner is shown
