### ISSUE TITLE
Onboarding process start again after exit tray on macos

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/crc#2972]
### Steps:
1. install
2. onboarding
3. start instance from tray
4. exit tray
5. click Codeready Containers icon 

### Expected
Tray should be accessible again

### Actual
Onboaring process start again

**Comment by anjannath** [comment]
This is also fixed in https://github.com/code-ready/crc/pull/2971

the on-boarding process was starting again since `crc setup --check-only` was failing :
> In mac crc setup --check-only is always going to fail when you exit from the tray because this check do something launchctl list | grep crc.tray | awk '{print $1}'
