### ISSUE TITLE
[BUG]  remote registry lookup failed

### ISSUE THREAD

**Issue by Leo-need** [code-ready/crc#2975]
### General information

  * OS: macOS 
  * Hypervisor:  hyperkit
  * Did you run `crc setup` before starting it (Yes/No)?  YES
  * Running CRC on: Laptop 

## CRC version
```bash
CodeReady Containers version: 1.38.0+659b2cbd
OpenShift version: 4.9.12 (bundle installed at /Applications/CodeReady Containers.app/Contents/Resources/crc_hyperkit_4.9.12.crcbundle)
```
  
## CRC status
```bash
DEBU CodeReady Containers version: 1.38.0+659b2cbd 
DEBU OpenShift version: 4.9.12 (bundle installed at /Applications/CodeReady Containers.app/Contents/Resources/crc_hyperkit_4.9.12.crcbundle) 
DEBU Running 'crc status'                         
DEBU Checking file: /Users/myname.crc/machines/crc/.crc-exist 
DEBU Checking file: /Users/myname/.crc/machines/crc/.crc-exist 
DEBU Found binary path at /Applications/CodeReady Containers.app/Contents/Resources/crc-driver-hyperkit 
DEBU Launching plugin server for driver hyperkit  
DEBU Plugin server listening at address 127.0.0.1:59411 
DEBU () Calling .GetVersion                       
DEBU Using API Version 1                          
DEBU () Calling .SetConfigRaw                     
DEBU () Calling .GetMachineName                   
DEBU (crc) Calling .GetState                      
DEBU (crc) Calling .GetBundleName                 
DEBU Running SSH command: df -B1 --output=size,used,target /sysroot | tail -1 
DEBU Using ssh private keys: [/Users/myname/.crc/machines/crc/id_ecdsa /Users/myname/.crc/cache/crc_hyperkit_4.9.12/id_ecdsa_crc] 
DEBU SSH command results: err: <nil>, output: 32737570816 14371184640 /sysroot 
DEBU Unexpected operator status for etcd: RecentBackup 
DEBU Making call to close driver server           
DEBU (crc) Calling .Close                         
DEBU Successfully made call to close driver server 
DEBU Making call to close connection to plugin binary 
CRC VM:          Running
OpenShift:       Running (v4.9.12)
Disk Usage:      14.37GB of 32.74GB (Inside the CRC VM)
Cache Usage:     12.78GB
Cache Directory: /Users/myname/.crc/cache
DEBU Running 'sw_vers -productVersion'            
```

## CRC config
```bash
- consent-telemetry                     : yes
- host-network-access                   : true
- nameserver                            : 8.8.8.8
- pull-secret-file                      : /Users/myname/Downloads/pull-secret.txt

```

## Host Operating System
```bash
ProductName:	macOS
ProductVersion:	11.6.1
BuildVersion:	20G224
```

### Steps to reproduce

  1.  fresh installation of crc from the scratch
  2.  oc new-app  --image registry.access.redhat.com/rhscl/mysql-57-rhel7 --name mysql

### Expected

Image dowloaded, app running

### Actual

container image remote registry lookup failed: registry.access.redhat.com/rhscl/mysql-57-rhel7:latest: Get "https://registry.access.redhat.com/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
error: unable to locate any local docker images with name "registry.access.redhat.com/rhscl/mysql-57-rhel7"

First 20 min everything run as expected, but then I get error above
I've tried to:

crc stop
crc delete
crc cleanup
rm -rf .crc
crc config set nameserver 8.8.8.8
crc config set host-network-access true
crc start -n 8.8.8.8 

but get same results

start log https://gist.github.com/Leo-need/d1814da47d1b11d25d4bb9846519112d

Please help to debug this

**Comment by praveenkumar** [comment]
@Leo-need as per start logs all looks as expected. Is this machine behind vpn or any specific organization firewall which blocking  registry.access.redhat.com request. Can you try to access this on the host and also in the VM using https://github.com/code-ready/crc/wiki/Debugging-guide one.

**Comment by Leo-need** [comment]
@praveenkumar thank you for answer
There is no any proxy, vpn or firewall
I can access registry.access.redhat.com from host, I can ping it and get answer with curl
From the VM I can ping registry.access.redhat.com and thats all, curl doesn't answer and podman pull answer is 
`error pinging docker registry registry.access.redhat.com: Get "https://registry.access.redhat.com/v2/": dial tcp 184.51.88.187:443: i/o timeout`
I've tried to turnoff firewall on my laptop, but get same result. 
Any idea how else I can debug this?
Also I saw in the Debugging guide, that crc run this VM with vsock network mode but I didn't find how to change that mode to something else, does it specific for macos and hyperkit?

**Comment by praveenkumar** [comment]
> Also I saw in the Debugging guide, that crc run this VM with vsock network mode but I didn't find how to change that mode to something else, does it specific for macos and hyperkit?

@Leo-need yes it is run with vsock network mode and we are putting effort on this mode because it allow users to run the crc behind vpn/firewall also. I tried to run a sample pod which use registry.access.redhat.com and it works as expected also testing team doesn't find any issue. Since you are getting this every single time is it because of some other changes you did you your host or if you can check some of your colleague if they face same issue. 

```
<crc_vm> podman pull registry.access.redhat.com/ubi8/go-toolset:1.16.12
Trying to pull registry.access.redhat.com/ubi8/go-toolset:1.16.12...
Getting image source signatures
Checking if image destination supports signatures
Copying blob sha256:87b5ac18d5e002d3cacb7d4b49196a3abb5e0b3422ed222a509d3169d9759c31
Copying blob sha256:8671113e1c57d3106acaef2383f9bbfe1c45a26eacb03ec82786a494e15956c3
Copying blob sha256:aad543859364662ddb264ad5752fd9449d47410b9efa0278463c0a9c578b79c6
Copying blob sha256:79a56ba04a301eb949644bca29f18b1879b6f305091ef1eb8068a0f5828db863
Copying blob sha256:5dcbdc60ea6b60326f98e2b49d6ebcb7771df4b70c6297ddf2d7dede6692df6e
Copying blob sha256:87b5ac18d5e002d3cacb7d4b49196a3abb5e0b3422ed222a509d3169d9759c31
Copying blob sha256:8671113e1c57d3106acaef2383f9bbfe1c45a26eacb03ec82786a494e15956c3
Copying blob sha256:aad543859364662ddb264ad5752fd9449d47410b9efa0278463c0a9c578b79c6
Copying blob sha256:79a56ba04a301eb949644bca29f18b1879b6f305091ef1eb8068a0f5828db863
Copying blob sha256:5dcbdc60ea6b60326f98e2b49d6ebcb7771df4b70c6297ddf2d7dede6692df6e
Copying config sha256:1188301ca1d447dda58fab71d784bf35bcd7c490daa697e9c8d3c61398eabf12
Writing manifest to image destination
Storing signatures
```

**Comment by Leo-need** [comment]
@praveenkumar thank you for answers
Unfortunately I don't have any colleagues here. Could you please help me to debug this a little bit. May be some of your colleagues have same setup as I do:
macbook pro 2019 bigsur 11.6.1
I found out that it works after I rebooted laptop, but only for one iteration like curl request on image pull, after that  get same result, ICMP works, but nothing else. It seems like something with my laptop
I don’t  have any specific settings or software on my laptop, only virtual box and this installation of crc. I turned off firewall and tried different internet providers.
Can you please tell me from which network interface VM should communicate with internet for my laptop, I've tried to tcpdump traffic from localhost, but didn’t see anything except ssh session logs. How I can check that VM sends requests to the internet?

**Comment by cfergeau** [comment]
The virtual machines communicate with the crc daemon running on the host over the vsock socket (it's a unix socket in `~/.crc/machines/crc`). Then the crc daemon does the network communication (through gvisor/gvisor-tap-vsock). If you kill the running crc daemon process and run it from a terminal (just `crc daemon` or `crc daemon --log-level debug`), it should show some info about network traffic.

**Comment by Leo-need** [comment]
@cfergeau thank you for advice
it doesn’t help, I only can see messages like this:

`2.612MB sent to the VM, 1.899MB received from the VM
2.613MB sent to the VM, 1.9MB received from the VM
2.615MB sent to the VM, 1.903MB received from the VM`

**Comment by Leo-need** [comment]
hi guys, any update here?

**Comment by praveenkumar** [comment]
@Leo-need if you want to debug it with wireshark/tcpdump then try to do following to capture network packets.

- Exit from the tray, make sure there is no crc/crc daemon instance is running.
```
<--- from one terminal tab ---->
$ touch /tmp/crc_pcap.pcap
$ export CRC_DAEMON_PCAP_FILE=/tmp/crc_pcap.pcap
$ crc daemon

<---- On second terminal tab ----->
$ crc start  
```

You can use this `crc_pcap.pcap` with wireshark or tcpdump to understand where is the issue.
