### ISSUE TITLE
[BUG] Releases notes link is a dud 

### ISSUE THREAD

**Issue by gorkem** [code-ready/crc#2977]
The link to the release notes from the About dialog on Tray opens a 404 page. 
The link opened is `https://access.redhat.com/documentation/en-us/red_hat_codeready_containers/1.38.0/html-single/release_notes_and_known_issues/index`.  I think the version number `1.38.0` on the URL is causing the issue since the documentation site has it as `1.38` only.

### General information

  * OS: macOS

## CRC version
```bash
CodeReady Containers version: 1.38.0+659b2cbd
OpenShift version: 4.9.12 (bundle installed at /Applications/CodeReady Containers.app/Contents/Resources/crc_hyperkit_4.9.12.crcbundle)
```

**Comment by gbraad** [comment]
This is a known issue and was resolved at some point. But this is an issue with the documentation site not being able to offer point release. It was fixed at some point, and then Robert got upset ... it was discussed, but it was never relayed they removed this.

We are not not going to fix this as the macOS client has stopped development for over 2 months now and is deprecated in the next release.
