### ISSUE TITLE
4.1.3/OSX/Vbox: marketplace operator pods are CrashLooping

### ISSUE THREAD

**Issue by wrichter** [code-ready/crc#298]
This is the log output for the certified-operators: 

time="2019-07-05T09:33:03Z" level=info msg="Using in-cluster kube client config" port=50051 type=appregistry time="2019-07-05T09:33:03Z" level=info msg="operator source(s) specified are - [https://quay.io/cnr|certified-operators]" port=50051 type=appregistry time="2019-07-05T09:33:03Z" level=info msg="package(s) specified are - nuodb-ce-certified,crunchy-postgres-operator,robin-operator,tidb-operator-certified,percona-xtradb-cluster-operator-certified,mariadb,memql-certified,storageos,oneagent-certified,appdynamics-operator,orca,insightedge-operator,federatorai-certified,kong,mongodb-enterprise,couchbase-enterprise-certified,sysdig-certified,openunison-ocp-certified,portworx-certified,planetscale-certified,hazelcast-enterprise-certified,synopsys-certified,twistlock-certified,newrelic-infrastructure,instana-agent,aqua-certified,anchore-engine,percona-server-mongodb-operator-certified,sematext" port=50051 type=appregistry time="2019-07-05T09:33:03Z" level=info msg="input has been sanitized" port=50051 type=appregistry time="2019-07-05T09:33:03Z" level=info msg="sources: [https://quay.io/cnr/certified-operators]" port=50051 type=appregistry time="2019-07-05T09:33:03Z" level=info msg="packages: [nuodb-ce-certified crunchy-postgres-operator robin-operator tidb-operator-certified percona-xtradb-cluster-operator-certified mariadb memql-certified storageos oneagent-certified appdynamics-operator orca insightedge-operator federatorai-certified kong mongodb-enterprise couchbase-enterprise-certified sysdig-certified openunison-ocp-certified portworx-certified planetscale-certified hazelcast-enterprise-certified synopsys-certified twistlock-certified newrelic-infrastructure instana-agent aqua-certified anchore-engine percona-server-mongodb-operator-certified sematext]" port=50051 type=appregistry time="2019-07-05T09:33:23Z" level=info msg="skipping operator source due to error: https://quay.io/cnr/certified-operators" port=50051 type=appregistry time="2019-07-05T09:33:23Z" level=info msg="the following packages could not be resolved: map[tidb-operator-certified:false mongodb-enterprise:false couchbase-enterprise-certified:false openunison-ocp-certified:false hazelcast-enterprise-certified:false robin-operator:false orca:false twistlock-certified:false mariadb:false kong:false sysdig-certified:false aqua-certified:false percona-server-mongodb-operator-certified:false memql-certified:false sematext:false nuodb-ce-certified:false storageos:false insightedge-operator:false synopsys-certified:false newrelic-infrastructure:false federatorai-certified:false planetscale-certified:false instana-agent:false crunchy-postgres-operator:false oneagent-certified:false percona-xtradb-cluster-operator-certified:false appdynamics-operator:false portworx-certified:false anchore-engine:false]" port=50051 type=appregistry time="2019-07-05T09:33:23Z" level=info msg="download list is empty, bailing out: [nuodb-ce-certified crunchy-postgres-operator robin-operator tidb-operator-certified percona-xtradb-cluster-operator-certified mariadb memql-certified storageos oneagent-certified appdynamics-operator orca insightedge-operator federatorai-certified kong mongodb-enterprise couchbase-enterprise-certified sysdig-certified openunison-ocp-certified portworx-certified planetscale-certified hazelcast-enterprise-certified synopsys-certified twistlock-certified newrelic-infrastructure instana-agent aqua-certified anchore-engine percona-server-mongodb-operator-certified sematext]" port=50051 type=appregistry time="2019-07-05T09:33:23Z" level=info msg="No package manifest downloaded" port=50051 type=appregistry time="2019-07-05T09:33:23Z" level=error msg="the following error(s) occurred while preparing the download list: Get https://quay.io/cnr/api/v1/packages?namespace=certified-operators: dial tcp: lookup quay.io on 172.30.0.10:53: read udp 10.128.1.41:49618->172.30.0.10:53: i/o timeout" port=50051 type=appregistry time="2019-07-05T09:33:23Z" level=error msg="The following error occurred while downloading - Get https://quay.io/cnr/api/v1/packages?namespace=certified-operators: dial tcp: lookup quay.io on 172.30.0.10:53: read udp 10.128.1.41:49618->172.30.0.10:53: i/o timeout" port=50051 type=appregistry time="2019-07-05T09:33:23Z" level=fatal msg="error loading manifest from remote registry - Get https://quay.io/cnr/api/v1/packages?namespace=certified-operators: dial tcp: lookup quay.io on 172.30.0.10:53: read udp 10.128.1.41:49618->172.30.0.10:53: i/o timeout" port=50051 type=appregistry

**Comment by praveenkumar** [comment]
As per logs `tcp: lookup quay.io on 172.30.0.10:53: read udp 10.128.1.41:49618->172.30.0.10:53: i/o timeout" port=50051 type=appregistry time="2019-07-05T09:33:23Z" level=fatal msg="error loading manifest from remote registry - Get https://quay.io/cnr/api/v1/packages?namespace=certified-operators: dial tcp: lookup quay.io on 172.30.0.10:53: read udp 10.128.1.41:49618->172.30.0.10:53: i/o timeout" port=50051 type=appregistry` this looks like the crc VM doesn't have internet connectivity.

**Comment by wrichter** [comment]
How can I log into the node? From the host computer, I can ping quay.io fine.

**Comment by skabashnyuk** [comment]
Have the same issue.


This is CRC 4.3.1 on OSX virtualbox.
After I try https://github.com/code-ready/crc/issues/293#issuecomment-508535142
My operators pods are not starting
```
[10:36:01]skabashn:Downloads#: oc get pods
NAME                                    READY   STATUS             RESTARTS   AGE
certified-operators-7ddb99ffd5-2q4jx    0/1     CrashLoopBackOff   6          16d
community-operators-8df446fd8-g5zrx     0/1     CrashLoopBackOff   6          16d
marketplace-operator-69dcb77c86-4724g   1/1     Running            1          16d
redhat-operators-7c96466564-bzj57       0/1     CrashLoopBackOff   6          9m9s
redhat-operators-bd686ccb-hmqbm         0/1     CrashLoopBackOff   6          12m
```

```
[10:38:22]skabashn:Downloads#: oc logs community-operators-8df446fd8-g5zrx
time="2019-07-15T08:36:38Z" level=info msg="Using in-cluster kube client config" port=50051 type=appregistry
time="2019-07-15T08:36:38Z" level=info msg="operator source(s) specified are - [https://quay.io/cnr|community-operators]" port=50051 type=appregistry
time="2019-07-15T08:36:38Z" level=info msg="package(s) specified are - node-network-operator,twistlock,cert-utils-operator,knative-camel-operator,aqua,knative-serving-operator,apicurito,strimzi-kafka-operator,spark-gcp,spinnaker-operator,knative-eventing-operator,syndesis,descheduler,hazelcast-enterprise,opsmx-spinnaker-operator,eclipse-che,atlasmap-operator,knative-kafka-operator,etcd,camel-k,federation,cockroachdb,triggermesh,jaeger,planetscale,postgresql,microcks,federatorai,infinispan,prometheus,myvirtualdirectory,namespace-configuration-operator,metering,node-problem-detector,openshift-pipelines-operator,opendatahub-operator,microsegmentation-operator" port=50051 type=appregistry
time="2019-07-15T08:36:38Z" level=info msg="input has been sanitized" port=50051 type=appregistry
time="2019-07-15T08:36:38Z" level=info msg="sources: [https://quay.io/cnr/community-operators]" port=50051 type=appregistry
time="2019-07-15T08:36:38Z" level=info msg="packages: [node-network-operator twistlock cert-utils-operator knative-camel-operator aqua knative-serving-operator apicurito strimzi-kafka-operator spark-gcp spinnaker-operator knative-eventing-operator syndesis descheduler hazelcast-enterprise opsmx-spinnaker-operator eclipse-che atlasmap-operator knative-kafka-operator etcd camel-k federation cockroachdb triggermesh jaeger planetscale postgresql microcks federatorai infinispan prometheus myvirtualdirectory namespace-configuration-operator metering node-problem-detector openshift-pipelines-operator opendatahub-operator microsegmentation-operator]" port=50051 type=appregistry
time="2019-07-15T08:36:53Z" level=info msg="skipping operator source due to error: https://quay.io/cnr/community-operators" port=50051 type=appregistry
time="2019-07-15T08:36:53Z" level=info msg="the following packages could not be resolved: map[knative-kafka-operator:false camel-k:false jaeger:false prometheus:false myvirtualdirectory:false node-problem-detector:false twistlock:false cert-utils-operator:false federation:false cockroachdb:false postgresql:false aqua:false hazelcast-enterprise:false syndesis:false planetscale:false microsegmentation-operator:false strimzi-kafka-operator:false knative-eventing-operator:false opendatahub-operator:false descheduler:false atlasmap-operator:false etcd:false triggermesh:false namespace-configuration-operator:false openshift-pipelines-operator:false apicurito:false spinnaker-operator:false knative-camel-operator:false metering:false infinispan:false node-network-operator:false spark-gcp:false eclipse-che:false microcks:false federatorai:false knative-serving-operator:false opsmx-spinnaker-operator:false]" port=50051 type=appregistry
time="2019-07-15T08:36:53Z" level=info msg="download list is empty, bailing out: [node-network-operator twistlock cert-utils-operator knative-camel-operator aqua knative-serving-operator apicurito strimzi-kafka-operator spark-gcp spinnaker-operator knative-eventing-operator syndesis descheduler hazelcast-enterprise opsmx-spinnaker-operator eclipse-che atlasmap-operator knative-kafka-operator etcd camel-k federation cockroachdb triggermesh jaeger planetscale postgresql microcks federatorai infinispan prometheus myvirtualdirectory namespace-configuration-operator metering node-problem-detector openshift-pipelines-operator opendatahub-operator microsegmentation-operator]" port=50051 type=appregistry
time="2019-07-15T08:36:53Z" level=info msg="No package manifest downloaded" port=50051 type=appregistry
time="2019-07-15T08:36:53Z" level=error msg="the following error(s) occurred while preparing the download list: Get https://quay.io/cnr/api/v1/packages?namespace=community-operators: dial tcp: lookup quay.io on 172.30.0.10:53: read udp 10.128.0.135:33952->172.30.0.10:53: i/o timeout" port=50051 type=appregistry
time="2019-07-15T08:36:53Z" level=error msg="The following error occurred while downloading - Get https://quay.io/cnr/api/v1/packages?namespace=community-operators: dial tcp: lookup quay.io on 172.30.0.10:53: read udp 10.128.0.135:33952->172.30.0.10:53: i/o timeout" port=50051 type=appregistry
time="2019-07-15T08:36:53Z" level=fatal msg="error loading manifest from remote registry - Get https://quay.io/cnr/api/v1/packages?namespace=community-operators: dial tcp: lookup quay.io on 172.30.0.10:53: read udp 10.128.0.135:33952->172.30.0.10:53: i/o timeout" port=50051 type=appregistry
[10:38:24]skabashn:Downloads#:
```
 https://quay.io/cnr/api/v1/packages?namespace=community-operators is reachable from the host but not from crc VM

```
core@crc-cvgnz-master-0 ~]$ curl -v  https://quay.io/cnr/api/v1/packages?namespace=community-operators
* Could not resolve host: quay.io
* Closing connection 0
curl: (6) Could not resolve host: quay.io
[core@crc-cvgnz-master-0 ~]$ ^C
[core@crc-cvgnz-master-0 ~]$ ^C
[core@crc-cvgnz-master-0 ~]$ exit
вихід
Connection to 192.168.130.103 closed.
[10:41:58]skabashn:Downloads#: curl -v  https://quay.io/cnr/api/v1/packages?namespace=community-operators
*   Trying 50.17.181.26...
* TCP_NODELAY set
* Connected to quay.io (50.17.181.26) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: OU=Domain Control Validated; OU=EssentialSSL Wildcard; CN=*.quay.io
*  start date: Aug 30 00:00:00 2018 GMT
*  expire date: Aug 29 23:59:59 2020 GMT
*  subjectAltName: host "quay.io" matched cert's "quay.io"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fe1ec000000)
> GET /cnr/api/v1/packages?namespace=community-operators HTTP/2
> Host: quay.io
> User-Agent: curl/7.54.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200
< server: nginx/1.16.0
< date: Mon, 15 Jul 2019 08:42:04 GMT
< content-type: application/json
< content-length: 11899
```

**Comment by skabashnyuk** [comment]
@praveenkumar is this issue already a known bug and it's going to be solved with some pr in next release. Is there something that what I can do to help to diagnose this bug?

**Comment by praveenkumar** [comment]
@skabashnyuk can you try to build `crc` binary with latest master and see if that works #314 is already resolved and merged in master.

**Comment by praveenkumar** [comment]
@wrichter @skabashnyuk can you folks check if the latest version of crc `0.89.0` the issue still exist?

**Comment by wrichter** [comment]
I could not reproduce it in 0.89.0/OSX/hyperkit

**Comment by praveenkumar** [comment]
Thanks for confirmation, closing this now.
