### ISSUE TITLE
make `version` preset aware

### ISSUE THREAD

**Issue by anjannath** [code-ready/crc#2990]
output of both `crc version` and GET request to `/api/version` always gives back the openshift version even if the preset is set to podman

```
PS > crc version
CodeReady Containers version: 1.99.1+4f3a33ae
OpenShift version: 4.9.12 (not embedded in executable)
PS > crc config view
- consent-telemetry                     : no
- network-mode                          : user
- preset                                : podman
```

### o/p from `/api/version`
```json
{
  "CrcVersion": "2.99.0",
  "CommitSha": "da986df5",
  "OpenshiftVersion": "4.9.12"
}
```

**Comment by anjannath** [comment]
i'd suggest the api to return something like following:
```json
{
  "CrcVersion": "2.99.0",
  "CommitSha": "da986df5",
  "Components": {
    "openshift": "4.9.12",
    "podman": "3.4.4"
   }
}
```

**Comment by praveenkumar** [comment]
Should this just tell user what this specific version of crc contain?
```json
{
  "CrcVersion": "2.99.0",
  "CommitSha": "da986df5",
  "openshift": "4.9.12",
  "podman": "3.4.4"
}
```

**Comment by gbraad** [comment]
Version should return which versions are supported by the crc binary. 

You could imagine the tray has no idea aboutthr possible options available, like now no M1 9n Arm, so this should be requested from the backend. Status instead is preset aware, as it related to the current running version.

**Comment by gbraad** [comment]
> i'd suggest the api to return something like following:
> 
> ```json
> {
>   "CrcVersion": "2.99.0",
>   "CommitSha": "da986df5",
>   "Components": {
>     "openshift": "4.9.12",
>     "podman": "3.4.4"
>    }
> }
> ```

Not components, but bundle based presets
