### ISSUE TITLE
[RFE] Automatically start the GUI after installation finished on macOS

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#2993]
Related to the discussion: https://github.com/code-ready/crc/discussions/2988#discussioncomment-2127300

The user had to 'search' and discover CodeReady Containers as the application does not start automatically after the installation finished.

**Comment by praveenkumar** [comment]
As of now once user install the package , he/she needs to locate the CodeReady Containers from Application or from the finder. Some user might even think they have to run crc setup => crc start from the command line.

Need to check if this is possible with post install script.
