### ISSUE TITLE
[BUG] When installing CRC: CodeReady Containers is running. Please stop the application before updating

### ISSUE THREAD

**Issue by milles9393** [code-ready/crc#3034]
Hi, I am trying to download CRC for my MacOS. I've been running CRC successfully a couple of months before. 

The problem I am facing right now is that the crc-amd64.pkg is saying "CodeReady Containers is running. Please stop the application before updating." 

### General information

  * OS:  macOS 
  * Running CRC on: Laptop 

### Steps to reproduce

  1. I've deleted CRC and removed all files associated to it (AFAIK). This includes ` /.crc `, ` crc cli` etc. 
  2. Download latest CRC version for MacOS 

### Expected
Download to happen so that I can get the crc CLI and be able to run `crc setup` etc. 

### Actual
CodeReady Containers is running. Please stop the application before updating.

**Comment by praveenkumar** [comment]
@milles9393 Can you try to do `ps aux | grep crc` and see if there is some process which is actually using it?

**Comment by gbraad** [comment]
Did you check with `ps` if any process matches the name `crc*` ?

**Comment by milles9393** [comment]
Aah, of course..thanks for the help. I killed the process and it works now. 

Thanks a lot. @praveenkumar @gbraad
