### ISSUE TITLE
[RFE] Use `crc setup` to start the daemon if not running

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#3036]
Since our future plan to decouple tray and installer from the crc and tray should only talk to `crc daemon` as it currently doing but right now it also starts it. In the future if a developer doesn't need to use tray or in a CI use case where CI is a mac/windows host then `crc setup` and `crc start` should provide user expected environment.

This will also kind of align with some developer mind share where they really don't want to have any tray app but consume application as it is.

I will create an issue on tray side which should first check if daemon is running and if it is then don't start and consume the existing daemon.

**Comment by cfergeau** [comment]
This is related to https://github.com/code-ready/crc/issues/2557 and https://github.com/code-ready/crc/issues/2459

**Comment by gbraad** [comment]
Yep

**Comment by cfergeau** [comment]
Closing this as this should be mostly solved in git.
