### ISSUE TITLE
CRC on Windows 10 Pro unable to utilize network address other than loopback

### ISSUE THREAD

**Issue by jdennis** [code-ready/crc#3038]
CRC version 1.39 uses the local loopback address however some users want to use a network address, the issue is described in one of the comments in this article: https://developers.redhat.com/blog/2020/09/09/how-to-run-red-hat-codeready-containers-on-windows-10-enterprise

Using an existing crc vm which had been created to use the loopback I then tried to modify it to utilize a Hyper-V network adapter, these are the steps I performed:

1. crc stop
2. use hyper-v manager to add network adapter to crc vm and attach to default switch
3. crc start
4. lookup network address assigned by Hyper-V
5. edit the local hosts file changing the 127.0.01 assigned to the crc network names to the new network address
6. restart crc

I then tried to connect to the dashboard using the network address with the https port 443. The browser responded with a refuse to connect error. I verified the network address was in fact reaching the crc vm using windows tracert and could successfully ping as well.

Interestingly crc start continued to report crc was running with the 127.0.0.1 IP address.

After a while I started to get these errors in the shell window from where I started crc:

Temporary error: ssh command error:
command : exit 0
err     : ssh: handshake failed: read tcp 127.0.0.1:52166->127.0.0.1:2222: wsarecv: An existing connection was forcibly closed by the remote host.

So it seems one cannot just add a network adaptor and address to the crc vm and just have it work. Something still thinks things are still on the loopback.

**Comment by gbraad** [comment]
Sorry for not responding to this issue earlier. I saw this was related to the conversation on the blog post.

The address

> https://127.0.0.1

does not work, but

> https://console-openshift-console.apps-crc.testing

will and that is expected. This is how SNI works. The address 127.0.0.1 is disallowed to resolve to the endpoint of the webpage/console application.
You can login to the VM using: `ssh core@127.0.0.1 -p 2222` for example.

But perhaps it is better to understand what you actually want to to do. Why is access to the VM's IP address necessary?

**Comment by PhillipDowney** [comment]
I have similar issue, I would prefer to be using CRC over Minikube, but I connect from a second computer using a Mac to my windows machine with hyper-v using a switch. With this latest version of CRC how do you connect to it from a remote PC  if it is running on Hyper-v on another machine ?
