### ISSUE TITLE
Update OpenShift CI configurations to run jobs for the `main` branch

### ISSUE THREAD

**Issue by anjannath** [code-ready/crc#3041]
We were running the jobs for `dev` and `master` branches, since we renamed the `dev`-> `main` configs needs to be updated to reflect that

**Comment by praveenkumar** [comment]
https://github.com/openshift/release/pull/26640 here to update it on CI side.

**Comment by anjannath** [comment]
Fixed via https://github.com/openshift/release/pull/26640
