### ISSUE TITLE
CRC doesn't work on RHEL 7.6

### ISSUE THREAD

**Issue by tsedmik** [code-ready/crc#305]
*Environment*:
RHEL 7.6
CRC built from master branch

If I try CRC _alpha-3 (0.88.0)_, `crc setup` works properly. When I try `crc setup` with CRC built from master branch, the following error appears.

```
[cloud-user@tsedmik-rhel76 ~]$ ./crc setup
./crc: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```

I found no way how to get/install the required library.

**Comment by jmazzitelli** [comment]
FWIW: I'm using this on RHEL 7.6 successfully:

```
$ crc version
version: 0.88.0-alpha-4.1.3+783056a
```

**Comment by praveenkumar** [comment]
@tsedmik check if you have `openssl-devel` package on this system which provides `libcrypto.so` this should be part of standard installation.

**Comment by cfergeau** [comment]
openssl changed its ABI and thus its soname between RHEL7 and RHEL8/fedora (openssl 1.0.x VS opensll 1.1.x). RHEL7.6 has libcrypto.so.10 while the binary was built against  libcrypto.so.1.1
I don't know if installing compat-openssl10-devel instead of openssl-devel on the machine building the binary would avoid this issue or not.

**Comment by gbraad** [comment]
would a simple symlink work?

**Comment by cfergeau** [comment]
@gbraad, this would not work, the file was renamed because the old and new version are not compatible. If they were ABI (runtime) compatible, then the .so file would have kept the same name.

**Comment by tsedmik** [comment]
@praveenkumar I have `openssl-devel` package installed on the system. The problem is somewhere else. The CRC is built on RHEL 8 machine and this binary doesn't work on RHEL 7 :-(. When I build the CRC on RHEL 7, I'm able to run it.

**Comment by tsedmik** [comment]
@cfergeau I'll try to install `compat-openssl10-devel` instead of `openssl-devel` on the machine building the binary to avoid this issue.

**Comment by cfergeau** [comment]
Is this still an issue with the latest builds?

**Comment by tsedmik** [comment]
I tested this issue - _RHEL 7.6_, _CRC 1.0.0.beta3_ - and it works as expected --> closing this issue
