### ISSUE TITLE
[How-to]  Is it possible to connect to a remote instance of crc from a Windows client ?

### ISSUE THREAD

**Issue by rscher** [code-ready/crc#3054]
Hey Guys,

Russ here from IBM ... Question on connecting to a  remote instance of crc, running the latest crc 1.40.0 on RHEL 8.5:
Hate to ask, but is there any way to connect to a crc remote instance from a Windows-based  client machine running oc  ?

Docs state the following-
[Connecting to a remote CodeReady Containers instance](https://crc.dev/crc/#connecting-to-remote-instance_gsg)
Use dnsmasq to connect a client machine to a remote server running a CodeReady Containers OpenShift cluster.
**This procedure assumes the use of a Red Hat Enterprise Linux, Fedora, or CentOS client.** 

You may have remembered the previous crc issues I raised when running crc within our Castle and Fyre VPC environments 
here at IBM.  These issues were reported for earlier crc releases which did not behave well in these VPCs due to unsupported "nested virtualization" topology on machines based on AMD's EPYC CPU running qemu pc-i440fx-bionic.

The good news is, crc has improved considerably and the latest versions that bundle  OCP 4.9.15 and 4.9.18 under RHEL 8.4/8.5
have none of the earlier issues, cluster status correctly reports "Running" and the performance is drastically better.
This is despite the recent issue of 'wildcard dns resolution for apps-crc.testing not working', which is easily worked around by 
appending  $CRC_IP   '<new app URL>'  to /etc/hosts.

Now that the platform is somewhat stable, ideally would like to run crc on a remote server and connect to it from
a client machine with oc client installed. The limitation within fyre/castle is that all VDI's are Windows-based VM's, 
hence my question if there is any way to accomplish this.

As always, appreciate all your guidance and help

-Russ Scher
IBM Cloud

**Comment by praveenkumar** [comment]
@rscher What we need is just the resolver on client side so something https://superuser.com/questions/1148514/using-specific-dns-server-for-specific-domains might work on windows-10 client.
```
> Add-DnsClientNrptRule -Namespace ".api.crc.testing" -NameServers "<Remove-IP>"
> Add-DnsClientNrptRule -Namespace ".apps-crc.testing" -NameServers "<Remove-IP>"
```

**Comment by gbraad** [comment]
Alternatively, you can use the `ssh -D` trick to create a SOCKS5 proxy to connect directly to the remote host. In that case you can use the browser configured with the proxy and/or the command line tools. This is a little bit out of our scope. Might be able to look into this later if the previous option didn't work. Note: Nrpt rules have been suggested before in our issue tracker and worked for people

**Comment by rscher** [comment]
@gbraad @praveenkumar 
Thanks for those suggestions, will try both out, Nrpt seems promising.
I'm wondering if the 'wildcard dns resolution not working'  issue in the latest crc builds
would affect this ? was easy enough to workaround within the RHEL host by adding 
app routes to the CRC_IP line in /etc/hosts:
  192.168.130.11  api.crc.testing   **my_app_route.apps-crc.testing**   **my_app_route2.apps-crc.testing** 
So from windows, I'm looking to use those same app routes/URLs (including the openshift console URL) 
from a browser in Windows VDI.

-Russ

**Comment by gbraad** [comment]
You can add addresses to `c:\windows\system32\drivers\etc\hosts`and they should work, but as long as the console and API got exposed.

**Comment by rscher** [comment]
thanks guys, that was super helpful. 
-Russ

**Comment by Maltawdy** [comment]
> thanks guys, that was super helpful. -Russ

had you figure out how to do that ? are you able to use oc command from "outside server" to the "CRC on windows machine"? if yes can you share how? thanks

**Comment by shawgrey** [comment]
I have configured haproxy. How can I access the web console from browser in windows?
By adding URLs to windows host file or is there anything else?

**Comment by cfergeau** [comment]
Yes adding entries into windows hosts file should do the trick.
