### ISSUE TITLE
[BUG] CodeReady Web Console Is Not Accessible

### ISSUE THREAD

**Issue by markdevopstraining** [code-ready/crc#3071]
I’m encountering some issues after starting codeready – I can’t access the console. Can you help on this one please? Thank you.

Here’s some relevant logs and screenshots.
```
Checking if running in a shell with administrator rights
Checking Windows 10 release
Checking Windows edition
Checking if Hyper-V is installed and operational
Checking if crc-users group exists
Checking if current user is in Hyper-V Admins group
Checking if Hyper-V service is enabled
Checking if the Hyper-V virtual switch exists
Found Virtual Switch to use: Default Switch
Checking if vsock is correctly configured
listening vsock://00000400-FACB-11E6-BD58-64006A7986D3
listening [\\.\pipe\crc-http](file://./pipe/crc-http)
new connection from bb5024c0-0000-0000-0000-000081e1ffff:78f2fe85-facb-11e6-bd58-64006a7986d3 to 00000000-0000-0000-0000-000000000000:00000400-facb-11e6-bd58-64006a7986d3
Checking if running in a shell with administrator rights
Checking Windows 10 release
Checking Windows edition
Checking if Hyper-V is installed and operational
Checking if crc-users group exists
Checking if current user is in Hyper-V Admins group
Checking if Hyper-V service is enabled
Checking if the Hyper-V virtual switch exists
Found Virtual Switch to use: Default Switch
Checking if vsock is correctly configured
A CodeReady Containers VM for OpenShift 4.9.18 is already running
```

![image](https://user-images.githubusercontent.com/69137583/158600331-3fbd85dc-46d5-4230-ba43-3ae0376854cd.png)

![image](https://user-images.githubusercontent.com/69137583/158600353-a61afe73-afeb-4197-bde4-725ca14baa7b.png)

**Comment by cfergeau** [comment]
> `A CodeReady Containers VM for OpenShift 4.9.18 is already running`

It's probably best to first delete this already running VM (`crc delete`, or through the equivalent in the system tray UI), and then try to start again. Or have you already tried this multiple times?

**Comment by markdevopstraining** [comment]
Hi Christophe,

Will try your recommendation. Just wondering if the issue was due to the fact that I'm not an administrator in my local machine? I had to ask for our admins first so I can start CodeReady successfully, because otherwise, it would prompt an error (Access Denied). After it had been started, I was trying to access the console as a normal user, and the issue occurs. Thank you.

Regards,

MARK CHRISTIAN A. REYES
Programmer/Analyst
Solutions Delivery - Application Management
Information Technology Group

***@***.***<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.securitybank.com%2Fnews%2Fsecurity-bank-wins-its-4th-bank-of-the-year-award%2F&data=04%7C01%7Cmcreyes%40securitybank.com.ph%7Cebf2c21693b045f51b1108da0008c323%7Ceb18a3418b3942f4a368bcb385e9422f%7C0%7C0%7C637822334893862928%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BaZxZsd5hX%2BfWoByc%2BuiN6%2BuFCtt8fLes6ZjjhcF%2FaY%3D&reserved=0>

**Comment by cfergeau** [comment]
> Just wondering if the issue was due to the fact that I'm not an administrator in my local machine?

You need to be able to get admin rights when running `crc setup`. After this is done, `crc start` and other commands should be usable as a non-admin user.

**Comment by markdevopstraining** [comment]
Hi Christophe,

Here's the error I'm getting when running crc start using a normal user. Reason why I had to ask for our admins to run the command prompt as Administrator before I run crc start. Can you help me on this one? Thank you.
***@***.***

Regards,

MARK CHRISTIAN A. REYES
Programmer/Analyst
Solutions Delivery - Application Management
Information Technology Group

***@***.***<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.securitybank.com%2Fnews%2Fsecurity-bank-wins-its-4th-bank-of-the-year-award%2F&data=04%7C01%7Cmcreyes%40securitybank.com.ph%7Cebf2c21693b045f51b1108da0008c323%7Ceb18a3418b3942f4a368bcb385e9422f%7C0%7C0%7C637822334893862928%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BaZxZsd5hX%2BfWoByc%2BuiN6%2BuFCtt8fLes6ZjjhcF%2FaY%3D&reserved=0>

**Comment by cfergeau** [comment]
> Here's the error I'm getting when running crc start using a normal user. Reason why I had to ask for our admins to run the command prompt as Administrator before I run crc start. Can you help me on this one? Thank you.

I'm afraid I don't see an error message in your latest comment https://github.com/code-ready/crc/issues/3071#issuecomment-1073384628

**Comment by markdevopstraining** [comment]
Hi Christophe,

Do you mean the "Access Denied" on my screenshot is not an error message? Thank you.

***@***.***

Regards,

MARK CHRISTIAN A. REYES
Programmer/Analyst
Solutions Delivery - Application Management
Information Technology Group

***@***.***<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.securitybank.com%2Fnews%2Fsecurity-bank-wins-its-4th-bank-of-the-year-award%2F&data=04%7C01%7Cmcreyes%40securitybank.com.ph%7Cebf2c21693b045f51b1108da0008c323%7Ceb18a3418b3942f4a368bcb385e9422f%7C0%7C0%7C637822334893862928%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BaZxZsd5hX%2BfWoByc%2BuiN6%2BuFCtt8fLes6ZjjhcF%2FaY%3D&reserved=0>

**Comment by cfergeau** [comment]
> Do you mean the "Access Denied" on my screenshot is not an error message? Thank you.

Ah no, I mean I don't see any screenshots nor any logs in your comments on github, see this link for example:
https://github.com/code-ready/crc/issues/3071#issuecomment-1073384628

**Comment by markdevopstraining** [comment]
Apparently the screenshot I’m sending via email can’t be viewed in GitHub. Can you see it now?

![image](https://user-images.githubusercontent.com/69137583/159245982-da392bb3-e85a-42a2-a348-dab507c32961.png)

**Comment by cfergeau** [comment]
Yes, this works much better, thanks! :)

**Comment by markdevopstraining** [comment]
Okay. Please let me know what could be the issue if Admin account is not needed to run crc start. Thank you.

**Comment by gbraad** [comment]
Hi Mark, can you provide information if the admin-helper is actually running? This is responsible for modifying the dns records in the hosts file. access denied looks like the process is not running or not allowed to be accessed.

**Comment by gbraad** [comment]
It might also help to provide more information; as the issue template was not followed it is hard to understand what your setup looks like.

**Comment by gbraad** [comment]
> Admin account

Administrator account is NOT needed. We install a service (admin-helper) to allow the regular user to start CRC. Any task that needs raised privileges, are performed by requesting the admin helper for this. This is only updating hosts records. This is why the VM is running, but perhaps openshift unreachable, as we do not get the needed response from the domain name we connect to.

 * Check  the admin-helper (services.msc)
 * See what is recorded in `C:\windows\system32\drivers\etc\hosts`

**Comment by markdevopstraining** [comment]
I just used the installation Wizard, with the help of our admins (since installation required Admin access). Afterwards, we rebooted my laptop and ran "crc setup".

**Comment by gbraad** [comment]
> with the help of our admins (since installation required Admin access).

Most likely something didn't not get installed as expected, as the `admin-helper` is essential for an e2e experience.
There is a new version, so please update and make sure the admin helper is up and running on restarts.

**Comment by markdevopstraining** [comment]
Okay. will try to reinstall it
