### ISSUE TITLE
[BUG] Wildcard DNS resolution for `apps-crc.testing` does not appear to be working

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#3078]
Running `crc start` on linux/windows when usermode networking is being used prints `Wildcard DNS resolution for apps-crc.testing does not appear to be working`. This is actually expected with usermode networking as we don't attempt to configure name resolution for `*.apps-crc.testing`, we only create entries in /etc/hosts corresponding to existing openshift routes.
This message should be removed/omitted when usermode is being used as it's very misleading.

**Comment by ringerc** [comment]
See also https://github.com/crc-org/crc/issues/2593
