### ISSUE TITLE
Add functionality to get the cluster operator status, programatically.

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#308]
Right now we don't have any way to get the cluster operator status programmatically, we should have it so command like `status` can consume it.

**Comment by gbraad** [comment]
you mean, the status of a single operator?

**Comment by praveenkumar** [comment]
@gbraad nope, I meant all the required operators.

**Comment by gbraad** [comment]
check... as selective checking would sound 'wasteful' to me.

**Comment by anjannath** [comment]
Fixed in #309
