### ISSUE TITLE
[BUG] Latest crc client v 2.0.1 requires network connection, no longer able to run 'crc setup' within restricted network env

### ISSUE THREAD

**Issue by rscher** [code-ready/crc#3082]
### General information

  * OS:  RHEL 8.5 / RHEL 7.9 
  * Hypervisor: KVM / Hyper-V / hyperkit: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on:  VM

## CRC version
```bash
# Put `crc version` output here
$ crc version
CodeReady Containers version: 2.0.1+bf3b1a6
OpenShift version: 4.10.3
Podman version: 3.4.4
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
$ crc status --log-level debug
DEBU CodeReady Containers version: 2.0.1+bf3b1a6
DEBU OpenShift version: 4.10.3
DEBU Podman version: 3.4.4
DEBU Running 'crc status'
DEBU Checking file: /home/crcuser/.crc/machines/crc/.crc-exist
Machine does not exist. Use 'crc start' to create it


## CRC config
```bash
# Put `crc config view` output here

$ crc config view
- consent-telemetry                     : no
- cpus                                           : 16
- disable-update-check                  : true
- kubeadmin-password                  : ******
- memory                                     : 25564
- pull-secret-file                      : /home/crcuser/pull-secret.txt


## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.9 (Maipo)"

also tried on RHEL 8.5 , same result

### Steps to reproduce

  1. $ crc setup --log-level debug
  2. 
  3. 
  4. 

### Expected

Seems latest crc v2.0.1, given the small size of tar.xz file = 23.9 M no longer contains the bundle
 and requires network connection to download it, unlike previous versions. See below
This prevents using crc as before, v1.40.0  within a restricted network env (no internet access).

v2.0.1     crc-linux-amd64.tar.xz   23.9M  Tue Mar 15 14:19:48 2022   <--- no embedded bundle , no longer works without network
v1.40.0   crc-linux-amd64.tar.xz   3.1G     Mon Feb 28 14:41:06 2022 <--- contains bundle, works fine without network

**What are my options here ?**

thanks,
-Russ

### Logs
$ crc setup --log-level debug
 
See gists ..

RHEL 7.9   https://gist.github.com/rscher/df6427003e7e871a6e25730514afbd1c
RHEL 8.5  https://gist.github.com/rscher/aedbce6e1dbbbc418e0a48e1fd9f5a40

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

**Comment by praveenkumar** [comment]
The best you can do is download the `crc` binary and `bundle` ( https://mirror.openshift.com/pub/openshift-v4/clients/crc/bundles/openshift/4.10.3/ ) both manually from a device which is connected to external internet and transfer/scp to the machine which is in restricted network, then do something following.

```
$ crc setup -b <bundle_path_on_the_machine>
$ crc start
```

**Comment by rscher** [comment]
> 

thanks @praveenkumar,  [crc_libvirt_4.10.3_amd64.crcbundle](https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/crc/bundles/openshift/4.10.3/crc_libvirt_4.10.3_amd64.crcbundle) was the missing link, didn't notice you publish the 3 GB bundle separately from the crc binary. Looks like I have a path forward.
thanks,
-Russ

**Comment by praveenkumar** [comment]
@rscher Please close the issue once it works for you.

**Comment by praveenkumar** [comment]
@gbraad @robin-owen Do we need to put a documents in case of disconnected env?

**Comment by gbraad** [comment]
File as a Known issue, add to current requirements. And file an issue for implementing and documenting how to use a downloaded bundle.

**Comment by rscher** [comment]
@praveenkumar @gbraad ,

All looks good using downloaded bundle

$ crc setup -b  /home/crcuser/binaries/crc/latest/crc_libvirt_4.10.3_amd64.crcbundle   --log-level debug
see https://gist.github.com/rscher/d8f9f7ae784fba0414d87c1b80e0f2ab

one very minor point, fails check for public DNS query. (no internet connection)

INFO Check internal and public DNS query...
WARN Failed public DNS query from the cluster: ssh command error:
command : curl --head quay.io
err     : Process exited with status 7
 
-if  no Skip config param or disable a preflight check for public DNS query exists, that should probably be a new RFE.
-looks like  Wildcard DNS resolution #3078](https://github.com/code-ready/crc/issues/3078)
  is fixed in this version ,  correct ?

-Russ

**Comment by rscher** [comment]
> @rscher Please close the issue once it works for you.

thanks guys , closing issue.

**Comment by cfergeau** [comment]
@rscher I see you reopened this issue, did you have more problems using crc in a disconnected environment?

**Comment by rscher** [comment]
Hi @praveenkumar @gbraad ,

Regarding downloading bundle, I updated my script to download bundle along with latest crc,
can you also post to a latest URL  ?
  https://mirror.openshift.com/pub/openshift-v4/clients/crc/bundles/openshift/latest 
to correspond with  the crc client/latest ?
https://mirror.openshift.com/pub/openshift-v4/clients/crc/latest
My script just downloads whatever crc client version is in /latest

can we do also do that for the corresponding bundle ? 
instead  of the explicit version URL  https://mirror.openshift.com/pub/openshift-v4/clients/crc/bundles/openshift/4.10.3 ?
that @praveenkumar  provided ?

thanks !
-Russ

**Comment by gbraad** [comment]
Latest of the bundle depends on the CRC version. So we might have published a nu dle that is only used for development purpose or test cases. So unfortunately that can't work.

**Comment by rscher** [comment]
hmm  .. seems like it would correspond to whatever is published in CRC version  /latest
https://mirror.openshift.com/pub/openshift-v4/clients/crc/latest

so scripts can just to a wget on the ../latest
without knowing the exact version# , am I missing something ?

thanks !
-Russ

**Comment by rscher** [comment]
> @rscher What you should do if you want script way to get the bundle url for a specific release.
> 
> ```
> $ openshiftVersion=$(curl -sL https://mirror.openshift.com/pub/openshift-v4/clients/crc/latest/release-info.json | jq -r .version.openshiftVersion)
> $ curl -L -O https://mirror.openshift.com/pub/openshift-v4/clients/crc/bundles/openshift/"${openshiftVersion}"/crc_libvirt_"${openshiftVersion}"_amd64.crcbundle
> ```

@praveenkumar ah nice, that will work. 
thanks again !
-Russ
