### ISSUE TITLE
[BUG] `crc start` fails as dependent service not started -- Daemon not available 

### ISSUE THREAD

**Issue by krishna16101991** [code-ready/crc#3083]
Is CodeReady Containers tray application running? Cannot reach daemon API: Get "http://unix/api/version": open \\.\pipe\crc-http: The system cannot find the file specified.

getting this error, tried manually also to start container but after putting secret also nothing happening
[crc.log](https://github.com/code-ready/crc/files/8350801/crc.log)

Issue is on Windows 10

**Comment by praveenkumar** [comment]
@krishna16101991 Please use the issue template https://github.com/code-ready/crc/issues/new?assignees=&labels=kind%2Fbug%2C+status%2Fneed+triage&template=bug_report.md&title=%5BBUG%5D use this and if you installed the crc from the installer then make sure you start it from `Start => Code Ready Container` which will open the guided workflow and start the tray.

**Comment by gbraad** [comment]
This would sound like an issue with the start of the daemon,

**Comment by gbraad** [comment]
Let me guess, you start `crc start` directly from the command line,. without using the tray?

```
c:\Program Files\CodeReady Containers>crc start
WARN A new version (2.0.1) has been published on https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/crc/2.0.1/crc-windows-installer.zip
Is 'crc daemon' running? Cannot reach daemon API: Get "http://unix/api/version": open \\.\pipe\crc-http: The system cannot find the file specified.
```

If so, we unfortunately forgot to auto start the daemon. Cab you run another command prompt with `crc daemon` and leave this running in the background, In another command prompt you should now be able to start `crc start` successfully.

**Comment by gbraad** [comment]
Related to #3086

**Comment by gbraad** [comment]
https://github.com/code-ready/crc/pull/3088

**Comment by miltonabatista** [comment]
> Let me guess, you start `crc start` directly from the command line,. without using the tray?
> 
> ```
> c:\Program Files\CodeReady Containers>crc start
> WARN A new version (2.0.1) has been published on https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/crc/2.0.1/crc-windows-installer.zip
> Is 'crc daemon' running? Cannot reach daemon API: Get "http://unix/api/version": open \\.\pipe\crc-http: The system cannot find the file specified.
> ```
> 
> If so, we unfortunately forgot to auto start the daemon. Cab you run another command prompt with `crc daemon` and leave this running in the background, In another command prompt you should now be able to start `crc start` successfully.




##

@praveenkumar 
Thank for that.

So, When I  run crc daemon  --log-level debug I could see my problem.
When crc daemon run  "@(Get-Wmiobject Win32_ComputerSystem).HypervisorPresent" ever returned False.
## Problem
My windows was set "bcdedit /set hypervisorlaunchtype off"

## Fix
I fixed It:  run  "bcdedit /set {current} hypervisorlaunchtype auto"
Now crc works fine.

**Comment by krishna16101991** [comment]
@gbraad @miltonabatista - yes I am doing crc start directly from the command line,. without using the tray. tried running crc daemon in another cmd, below is the outcome:

crc daemon --log-level debug
DEBU CodeReady Containers version: 2.0.1+f0fcd50e
DEBU OpenShift version: 4.10.3
DEBU Podman version: 3.4.4
DEBU Running 'crc daemon'
INFO Checking if running in a shell with administrator rights
DEBU Running '$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent());$currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)'
INFO Checking Windows 10 release
DEBU Running '(Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion" -Name ReleaseId).ReleaseId'
INFO Checking Windows edition
DEBU Running '(Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion").EditionID'
DEBU Running on Windows ServerDatacenter edition
INFO Checking if Hyper-V is installed and operational
DEBU Running '@(Get-Wmiobject Win32_ComputerSystem).HypervisorPresent'
DEBU Running '@(Get-Service vmms).Status'
DEBU Hyper-V management service not available
DEBU Running '(Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion" -Name ReleaseId).ReleaseId'
DEBU Running '(Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion").EditionID'
Hyper-V management service not available

crc start --log-level debug
DEBU CodeReady Containers version: 2.0.1+f0fcd50e
DEBU OpenShift version: 4.10.3
DEBU Podman version: 3.4.4
DEBU Running 'crc start'
DEBU Total memory of system is 17179459584 bytes
DEBU No new version available. The latest version is 2.0.1
DEBU Checking file: C:\Users\krisingh\.crc\machines\crc\.crc-exist
DEBU Running '(Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion" -Name ReleaseId).ReleaseId'
DEBU Running '(Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion").EditionID'
Is CodeReady Containers tray application running? Cannot reach daemon API: Get "http://unix/api/version": open \\.\pipe\crc-http: The system cannot find the file specified.

**Comment by gbraad** [comment]
> Hyper-V management service not available

Something is nt right with your system.
It seems setup has not installed the needed requirements?

**Comment by krishna16101991** [comment]
@gbraad - Yes, I was trying on AWS MS 2019 machine and enabling Hyper-V is disable for this. Further I tried same on Windows 10 Enterprise and ran crc daemon in separate cmd and I am able to successfully running crc start in another cmd, also openshift cluster platform is accessible.  But now problem is I have enabled AAP operator in operators hub and out of 5 Pods 1 pod is not starting due to insufficient resources , due to this unable to see AAP interface . My system is with 16 GB RAM

**Comment by gbraad** [comment]
> Hyper-V management service not available

> AWS

 Nested virtualization is not supported as a setup.

**Comment by gbraad** [comment]
Not related to CRC

**Comment by weironz** [comment]
Nested virtualization 
```
[rocky@node71 ~]$ crc config set skip-check-daemon-systemd-unit true
crc config set skip-check-daemon-systemd-sockets true
Successfully configured skip-check-daemon-systemd-unit to true

Successfully configured skip-check-daemon-systemd-sockets to true
[rocky@node71 ~]$ 
```
then
```
crc setup
crc start
```
```
[rocky@node71 ~]$ crc version
CRC version: 2.41.0+e6495f
OpenShift version: 4.16.7
MicroShift version: 4.16.7
```

```
[rocky@node71 root]$ crc console --credentials
Get "http://unix/api/webconsoleurl": read unix @->/home/rocky/.crc/crc-http.sock: read: connection reset by peer
```
must run `crc daemon `
