### ISSUE TITLE
crc start ( Get "http://unix/api/version": open \\.\pipe\crc-http: The system cannot find the file specified)

### ISSUE THREAD

**Issue by miltonabatista** [code-ready/crc#3085]
General information
OS: Windows 11 Pro
Hypervisor: Hyper-V
Did you run crc setup before starting it (Yes/No)? Yes
Running CRC on: Desktop pc

CRC version
CodeReady Containers version: 2.0.1+f0fcd50e
OpenShift version: 4.10.3
Podman version: 3.4.4

## Error
crc start
Is CodeReady Containers tray application running? Cannot reach daemon API: Get "http://unix/api/version": open \\.\pipe\crc-http: The system cannot find the file specified.

**Comment by praveenkumar** [comment]
check https://github.com/code-ready/crc/issues/3083 and make sure you use the issue template.

**Comment by praveenkumar** [comment]
close #3086
