### ISSUE TITLE
Remove preflight checks as part of crc daemon

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#3093]
Why do we have preflight checks for `crc daemon` this is always block in case `crc daemon` is started as standalone process after #3088 and #3072. Also crc daemon doesn't need to have any checks before it can run.

After following PR merge if dev member try to do following then it will fail to debug the daemon api.
```
> .\crc.exe daemon
INFO Checking if running in a shell with administrator rights
INFO Checking Windows 10 release
INFO Checking Windows edition
INFO Checking if Hyper-V is installed and operational
INFO Checking if crc-users group exists
INFO Checking if current user is in Hyper-V Admins group
INFO Checking if Hyper-V service is enabled
INFO Checking if the Hyper-V virtual switch exists
INFO Found Virtual Switch to use: Default Switch
INFO Checking if vsock is correctly configured
INFO Checking if daemon task is installed
exit status 1
```

**Comment by gbraad** [comment]
the daemon starts slowly due to these checks; the tray has a delay of 4 to 6 seconds for this. after the removal of these preflights for the daemon we can check if the tray can start quicker,

**Comment by cfergeau** [comment]
> crc daemon doesn't need to have any checks before it can run.

Why? When is the daemon going to validate the OS is setup properly for crc use?

**Comment by praveenkumar** [comment]
> > crc daemon doesn't need to have any checks before it can run.
> 
> Why? When is the daemon going to validate the OS is setup properly for crc use?

@cfergeau do we really need that? Daemon is separate process and doesn't need any setup to run. It is not depend on preflight to run correctly right? `crc setup` and `crc start` require preflight check because these command depend on it not the `setup` like  other subcommand `version`, `oc-env` ..etc?

**Comment by gbraad** [comment]
the daemon can run independent of a `crc setup`. the actual check happens when you perform a `crc start`.

**Comment by cfergeau** [comment]
Yes, this is the background info that was missing, that the needed checks will be ran as part of `crc start` anyway.

**Comment by cfergeau** [comment]
> After following PR merge if dev member try to do following then it will fail to debug the daemon api.

Fwiw, the right `skip` option can be set for this. This is not a very compelling reason for removing the checks ;)

**Comment by praveenkumar** [comment]
It is removed with https://github.com/code-ready/crc/pull/3088/commits/458237512bd1d22a2fce3e44f5c24ff279d9a475
