### ISSUE TITLE
Disk, memory, cpu settings for VM should be variables we can set during install

### ISSUE THREAD

**Issue by hupiper** [code-ready/crc#311]
It would be nice to be able set the crc VM with increased values for things like disk and memory if we want to turn features on in crc like monitoring, or for adding maistro to the cluster. I can do it after the VM is created by shutting it down and increasing the values. I would like to set the initial config with different values if needed.

**Comment by praveenkumar** [comment]
@hupiper For memory and cpu we already have option which you can use before starting it. You can also use `crc config set memory/cpu` to set it as part of config.

```
$ ./crc start -h
Start cluster
[..]
  -c, --cpus int           Number of CPU cores to allocate to the CRC VM (default 4)
  -m, --memory int         MiB of Memory to allocate to the CRC VM (default 8192)
```

Increase the disk size is not an option right now but we will work towards it.

**Comment by gbraad** [comment]
Closing, as these functions already exist. Maybe some automation might be added, but these are optimizations for later. Disk size is a different ptroblem as this not the virtual machine profile, but has been investigated: see #127
