### ISSUE TITLE
[BUG] Error deleting CRC cluster on Windows

### ISSUE THREAD

**Issue by jsliacan** [code-ready/crc#3123]
### General information

  * OS: Windows
  * Hypervisor: Hyper-V

## CRC version
```bash
PS C:\Users\crcqe> crc version
CodeReady Containers version: 2.1.0+81a5f334
OpenShift version: 4.10.6
Podman version: 3.4.4
```

## CRC config
```bash
PS C:\Users\crcqe> crc config view
- consent-telemetry                     : no
```

### Steps to reproduce

  1. Start CRC from powershell
  2. Issue `crc delete -f` or `crc delete` on a running cluster.

### Expected

Cluster deleted without any errors being reported.

### Actual
```
PS C:\Users\crcqe> crc delete
Do you want to delete the instance? [y/N]: y
failed to remove podman system connection exit status 1: time="2022-04-21T11:42:34+02:00" level=error msg="The handle is invalid."
```

**Comment by gbraad** [comment]
can you put your `crc config view1 here too?
preset looks to be `podman` ?

**Comment by jsliacan** [comment]
@gbraad preset was `openshift`. Will log into the machine & get the config now.
