### ISSUE TITLE
[BUG] Unable to start crc from tray due to failing preflight check

### ISSUE THREAD

**Issue by anjannath** [code-ready/crc#3149]
### General information

  * OS: macOS

### Steps to reproduce

  1. install crc by using the pkg installer 
  2. complete the steps of the on-boarding wizard
  3. the tray icon appears, now click on start
  
Nothing will happen, as in the status on the tray doesn't change to `Starting`, if you check the `About` page or the `Configurations` page, it all works as expected and communicates with the daemon properly

Upon checking the logs in `~/.crc/crcd.log` and following the lines after the `start` request was sent to daemon, you can see the following failing preflight check, which prevents the start (tray doesn't show an error about this)

```bash
ime="2022-04-26T11:32:20+02:00" level=debug msg="Running 'bash -c launchctl list | grep com.redhat.crc.daemon | awk '{print $1}''"
time="2022-04-26T11:32:20+02:00" level=debug msg="launchd agent 'com.redhat.crc.daemon' is not running"
```

**Comment by cfergeau** [comment]
Any idea why the launchd agent is eventually not running? Is this some kind of race condition between the tray starting the daemon itself, and crc setup configuring the launchd agent?

**Comment by anjannath** [comment]
> Any idea why the launchd agent is eventually not running? Is this some kind of race condition between the tray starting the daemon itself, and crc setup configuring the launchd agent?

yes, when the tray starts during the on-boarding phase itself the daemon is started.

this prevents the `crc setup` running in the background to start the daemon with `luanchd`.

**Comment by cfergeau** [comment]
Ah, and https://github.com/code-ready/crc/commit/4de2dce2b2276af8707aa502085da49dcdafa91b does not trigger because the version is correct :-/
Hopefully we can remove the daemon startup from the tray in the next release?
