### ISSUE TITLE
vfkit follow-ups

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#3157]
Before doing the first crc release using vfkit, some updates to our jenkins release jobs, and to the signing process will be needed.

**Comment by anjannath** [comment]
- For signing the macOS pkg we need to again apply the entitlements at https://raw.githubusercontent.com/code-ready/vfkit/main/vf.entitlements to the download `vfkit` binary

**Comment by cfergeau** [comment]
Why? Is it macos automatically dropping the entitlement at download time?

**Comment by cfergeau** [comment]
A bit more details in https://github.com/code-ready/crc/pull/3160 , but it's related to https://github.com/code-ready/crc/blob/main/packaging/package.sh which always resign vfkit/crc-admin-helper, and the `codesign` invocation also needs to apply the correct entitlements.
Ideally we would only be signing vfkit/admin-helper releases once, and not resign them for each crc release.

**Comment by anjannath** [comment]
> A bit more details in #3160 , but it's related to https://github.com/code-ready/crc/blob/main/packaging/package.sh which always resign vfkit/crc-admin-helper, and the `codesign` invocation also needs to apply the correct entitlements.
> Ideally we would only be signing vfkit/admin-helper releases once, and not resign them for each crc release.

Since all the dependent binaries also needs to contain a valid signature, and we don't sign them with an Apple known key during their release, its done in `package.sh` together with the finale crc release.

If we can get the release binaries of `vfkit` and `admin-helper` signed by RCM alread, we can skip the resigning again during crc release.

**Comment by cfergeau** [comment]
We've done a few crc releases with vfkit by now, let's close this.
