### ISSUE TITLE
CRC does not work on ppc64le

### ISSUE THREAD

**Issue by manojnkumar** [code-ready/crc#316]
Trying to build the docs on linux-ppc64le, hit this error:

```
[root@rhel-7 crc]# make build_docs
podman run -v /root/apps/crc/docs:/docs:Z --rm registry.gitlab.com/gbraad/asciidoctor-centos:latest -b html5 -D /docs/build /docs/source/getting-started/master.adoc
standard_init_linux.go:203: exec user process caused "exec format error"
```

The Makefile also needs a section like this to build for ppc64le?
```
$(BUILD_DIR)/linux-ppc64le/crc:  $(BUILD_DIR)/$(GOOS)-$(GOARCH)
        GOOS=linux GOARCH=ppc64le go build -ldflags="$(LDFLAGS)" -o $(BUILD_DIR)/linux-ppc64le/crc ./cmd/crc
```

**Comment by praveenkumar** [comment]
@manojnkumar we never targeted crc on power pc.  We want our support matrix to same as minishift or minikube mostly `x86_64` arch.

**Comment by manojnkumar** [comment]
@praveenkumar: Do you foresee any issues if we go down this path of making it build for ppc64le?

**Comment by praveenkumar** [comment]
@manojnkumar I don't see any issue but it all depend on the time we have in hand and also testing cycle if we add another arch. (As of now we don't even have any ppc hardware to do build or test).

**Comment by gbraad** [comment]
Closing as this is NOT a viable target from the perspective to run a `x86_64` based image. Also, at the moment there is no support to run OpenShift 4.x on PowerPC AFAIK.

**Comment by gbraad** [comment]
Note: this can be reconsidered when this is on the roadmap of OpenShift 4.x
