### ISSUE TITLE
[Windows] crc setup fails in case 2 user from same system try to use crc

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#3162]
Note: This is not the blocker issue but someone might experience it ( so putting it for record).

There are many reason why crc setup can fails and preflight check can detect and let user know what can be done to resolve it. Recently we added the task scheduler logic to start the daemon process as task and found out following scenario which is kind of hard for preflight check to understand what causing the issue.

Assume there are 2 different user (foo and bar) on this windows system
- User logged in with foo and run `crc setup`
- `crc setup` succeed and user start using crc instance
- User logout from `foo` without `crc cleanup` and logged in with `bar`
- Again try to do `crc setup` but noticed it is failing 
```
> .\crc.exe setup
[...]
INFO Checking if daemon task is installed
INFO Installing the daemon task
failed to register crcDaemon task, exit status 1: Register-ScheduledTask : Cannot create a file when that file already exists.
At line:1 char:43
+ ... yContinue'; Register-ScheduledTask -Xml '<?xml version="1.0" encoding ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (PS_ScheduledTask:Root/Microsoft/...S_ScheduledTask) [Register-ScheduledTask], CimException
    + FullyQualifiedErrorId : HRESULT 0x800700b7,Register-ScheduledTask
```
- Thought `crc cleanup` would fix it but it doesn't because user `bar` doesn't able to read the tasks which started/running by `foo` user
```
> .\crc.exe cleanup --log-level debug
[...]
DEBU Running 'Get-ScheduledTask -TaskName crcDaemon'
DEBU Command failed: exit status 1
DEBU stdout:
DEBU stderr: Get-ScheduledTask : No MSFT_ScheduledTask objects found with property 'TaskName' equal to 'crcDaemon'.  Verify the value of the property and reAt line:1 char:43
+ ... reference = 'SilentlyContinue'; Get-ScheduledTask -TaskName crcDaemon
+                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (crcDaemon:String) [Get-ScheduledTask], CimJobException
    + FullyQualifiedErrorId : CmdletizationQuery_NotFound_TaskName,Get-ScheduledTask
```
- If user try to open the task schedular then he can see from UI `crcDeamon` is running.

How to solve
------
- User logout from `bar` and log back in to `foo` and then use `crc cleanup` 

Or

- User open the task schedular UI from the administrator and delete the task manually
- Also user have to open task manager UI from the adminstrator and kill the daemon process.

**Comment by cfergeau** [comment]
Or maybe we should stop the scheduled task when the user logs out?

**Comment by praveenkumar** [comment]
> Or maybe we should stop the scheduled task when the user logs out?

@cfergeau not only stop the schedule task but need to remove it because `Register-ScheduledTask` will always fail until task is deleted from that user.

**Comment by zsery** [comment]
Hi, 
there is my result :
- crc cleanup, crc delete ... - does not help/work.
- User open the task schedular UI from the administrator and delete the task manually - does not help/work.
- Also user have to open task manager UI from the adminstrator and kill the daemon process - - does not help/work.
On the Windows [Version 10.0.22000.613].

**Comment by praveenkumar** [comment]
@zsery Can you put the steps you used to install the crc and also what you want to do? Does `crc setup` not working for you, what error are you getting?

**Comment by zsery** [comment]
@praveenkumar My installation steps:
1, run crc-windows-amd64.msi
2, under admin rights run crc setup

There is Debug log:
DEBU CRC version: 2.2.2+be1af25f
DEBU OpenShift version: 4.10.9
DEBU Podman version: 3.4.4
DEBU Running 'crc setup'
CRC is constantly improving and we would like to know more about usage (more details at https://developers.redhat.com/article/tool-data-collection)
Your preference can be changed manually if desired using 'crc config set consent-telemetry <yes/no>'
Would you like to contribute anonymous usage statistics? [y/N]: n
No worry, you can still enable telemetry manually with the command 'crc config set consent-telemetry yes'.
INFO Using bundle path C:\Users\zdenek.sery\.crc\cache\crc_hyperv_4.10.9_amd64.crcbundle
INFO Checking if current user is in Hyper-V Admins group
DEBU Running '$sid = New-Object System.Security.Principal.SecurityIdentifier("S-1-5-32-578")
        @([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole($sid)'
INFO Checking if CRC bundle is extracted in '$HOME/.crc'
INFO Checking if C:\Users\zdenek.sery\.crc\cache\crc_hyperv_4.10.9_amd64.crcbundle exists
DEBU error getting bundle info for crc_hyperv_4.10.9_amd64.crcbundle: could not find cached bundle info in C:\Users\zdenek.sery\.crc\cache\crc_hyperv_4.10.9_amd64: CreateFile C:\Users\zdenek.sery\.crc\cache\crc_hyperv_4.10.9_amd64: The system cannot find the file specified.
DEBU could not find cached bundle info in C:\Users\zdenek.sery\.crc\cache\crc_hyperv_4.10.9_amd64: CreateFile C:\Users\zdenek.sery\.crc\cache\crc_hyperv_4.10.9_amd64: The system cannot find the file specified.

INFO Getting bundle for the CRC executable
DEBU Ensuring directory C:\Users\zdenek.sery\.crc\cache exists
INFO Downloading crc_hyperv_4.10.9_amd64.crcbundle
DEBU Downloading https://mirror.openshift.com/pub/openshift-v4/clients/crc/bundles/openshift/4.10.9/crc_hyperv_4.10.9_amd64.crcbundle to C:\Users\zdenek.sery\.crc\cache\crc_hyperv_4.10.9_amd64.crcbundle
3.16 GiB / 3.16 GiB [--------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 26.50 MiB p/s
DEBU Download saved to C:\Users\zdenek.sery\.crc\cache\crc_hyperv_4.10.9_amd64.crcbundle
INFO Uncompressing C:\Users\zdenek.sery\.crc\cache\crc_hyperv_4.10.9_amd64.crcbundle
DEBU Uncompressing C:\Users\zdenek.sery\.crc\cache\crc_hyperv_4.10.9_amd64.crcbundle to C:\Users\zdenek.sery\.crc\cache\tmp-extract
crc.vhdx: 14.05 GiB / 14.05 GiB [----------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00%
oc.exe: 96.65 MiB / 96.65 MiB [------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00%
DEBU retry loop: attempt 0
INFO Checking if daemon task is installed
DEBU Running 'Get-ScheduledTask -TaskName crcDaemon'
DEBU Command failed: exit status 1
DEBU stdout:
DEBU stderr: Get-ScheduledTask : �loha XML obsahuje hodnotu, kter� nen� spr�vn� naform�tovan� nebo je mimo rozsah.
At line:1 char:43
+ ... reference = 'SilentlyContinue'; Get-ScheduledTask -TaskName crcDaemon
+                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_ScheduledTask:Root/Microsoft/...T_ScheduledTask) [Get-ScheduledTask], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041318,Get-ScheduledTask

DEBU crcDaemon task is not installed: exit status 1 : Get-ScheduledTask : �loha XML obsahuje hodnotu, kter� nen� spr�vn� naform�tovan� nebo je mimo rozsah.
At line:1 char:43
+ ... reference = 'SilentlyContinue'; Get-ScheduledTask -TaskName crcDaemon
+                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_ScheduledTask:Root/Microsoft/...T_ScheduledTask) [Get-ScheduledTask], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041318,Get-ScheduledTask

DEBU exit status 1
INFO Installing the daemon task
DEBU Running 'Get-ScheduledTask -TaskName crcDaemon'
DEBU Command failed: exit status 1
DEBU stdout:
DEBU stderr: Get-ScheduledTask : �loha XML obsahuje hodnotu, kter� nen� spr�vn� naform�tovan� nebo je mimo rozsah.
At line:1 char:43
+ ... reference = 'SilentlyContinue'; Get-ScheduledTask -TaskName crcDaemon
+                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_ScheduledTask:Root/Microsoft/...T_ScheduledTask) [Get-ScheduledTask], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041318,Get-ScheduledTask

DEBU crcDaemon task is not installed: exit status 1 : Get-ScheduledTask : �loha XML obsahuje hodnotu, kter� nen� spr�vn� naform�tovan� nebo je mimo rozsah.
At line:1 char:43
+ ... reference = 'SilentlyContinue'; Get-ScheduledTask -TaskName crcDaemon
+                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_ScheduledTask:Root/Microsoft/...T_ScheduledTask) [Get-ScheduledTask], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041318,Get-ScheduledTask

DEBU Running 'Register-ScheduledTask -Xml '<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.3" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>Run crc daemon as a task</Description>
    <Version>2.2.2</Version>
  </RegistrationInfo>
  <Settings>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <Hidden>true</Hidden>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <IdleSettings>
      <Duration>PT10M</Duration>
      <WaitTimeout>PT1H</WaitTimeout>
      <StopOnIdleEnd>true</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>
  </Settings>
  <Triggers />
  <Actions Context="Author">
    <Exec>
      <Command>powershell.exe</Command>
      <Arguments>-WindowStyle Hidden -Command &amp; &#39;C:\Program Files\Red Hat OpenShift Local\crc.exe&#39; daemon</Arguments>
    </Exec>
  </Actions>
</Task>
' -TaskName crcDaemon'
INFO Checking if daemon task is running
DEBU Running '(Get-ScheduledTask -TaskName "crcDaemon").State'
DEBU expected crcDaemon task to be in 'Running' but got ''
INFO Running the daemon task
DEBU Running 'Start-ScheduledTask -TaskName crcDaemon'
INFO Checking admin helper service is running
DEBU Running '(Get-Service crcAdminHelper).Status'
Your system is correctly setup for using CRC. Use 'crc start' to start the instance

**Comment by praveenkumar** [comment]
@zsery I will try those steps and get back to. Meanwhile why you are running the `crc setup` under admin right? you just open powershell (without run as administrator) and run it and it should pop as UAC prompt if some command executed as admin.

**Comment by zsery** [comment]
@praveenkumar  I can try it without administrator rights. I'm an admin and I assumed it was necessary. The settings I understood as not a user process, but the system process :-)

**Comment by zsery** [comment]
@praveenkumar There are crc_start (user rights) and crc_start files in the debug level logging.
[crc_start.txt](https://github.com/code-ready/crc/files/8681553/crc_start.txt)
[crc_setup.txt](https://github.com/code-ready/crc/files/8681554/crc_setup.txt)

**Comment by praveenkumar** [comment]
> @praveenkumar There are crc_start (user rights) and crc_start files in the debug level logging.

@zsery Going through the setup and start logs doesn't look like this issue should justify it. As per logs `setup` works and even `start` able to start the VM but it is failed to update the pull secret, because of slow IO? For this better to create a new issue with issue template.

**Comment by praveenkumar** [comment]
I also tested following scenario and that doesn't have any issue.
- Created a user which also have admin privilleges
- Run the powershell.exe as administrator and executed `crc setup`
- Run the powershell.exe without administrator and executed `crc start` 
Above steps works as expected so I think @zsery your issue doesn't related to this one, this only happen as I described in the issue.
