### ISSUE TITLE
[BUG] Cannot set up crc 2.2.2 on Corporate laptop build of Win10 Enteprise with Hyper-V enabled - error messages not useful

### ISSUE THREAD

**Issue by gkuzmanov** [code-ready/crc#3163]
### General information

  * OS: Windows
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it (Yes/No)?
  * Running CRC on: Laptop / Baremetal-Server / VM

## CRC version
CRC version: 2.2.2+be1af25f
OpenShift version: 4.10.9
Podman version: 3.4.4
  
## CRC status
DEBU CRC version: 2.2.2+be1af25f
DEBU OpenShift version: 4.10.9
DEBU Podman version: 3.4.4
DEBU Running 'crc status'
DEBU Checking file: C:\Users\A415415\.crc\machines\crc\.crc-exist
Machine does not exist. Use 'crc start' to create it

## Host Operating System
Host Name:                 DESKTOP-65NCJRA
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19043 N/A Build 19043
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Windows User
Registered Organization:
Product ID:                00330-80000-00000-AA716
Original Install Date:     05/02/2021, 15:59:26
System Boot Time:          30/04/2022, 01:32:47
System Manufacturer:       LENOVO
System Model:              20F2S10805
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 78 Stepping 3 GenuineIntel ~2501 Mhz
BIOS Version:              LENOVO N1HET94W (1.58 ), 09/12/2021
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-gb;English (United Kingdom)
Time Zone:                 (UTC+00:00) Dublin, Edinburgh, Lisbon, London
Total Physical Memory:     16,158 MB
Available Physical Memory: 3,268 MB
Virtual Memory: Max Size:  29,419 MB
Virtual Memory: Available: 8,046 MB
Virtual Memory: In Use:    21,373 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    AtosC2-DWP
Logon Server:              \\DESKTOP-65NCJRA
Hotfix(s):                 13 Hotfix(s) Installed.
                           [01]: KB5012117
                           [02]: KB4562830
                           [03]: KB4577586
                           [04]: KB4580325
                           [05]: KB4589212
                           [06]: KB4598481
                           [07]: KB5000736
                           [08]: KB5012599
                           [09]: KB5006753
                           [10]: KB5007273
                           [11]: KB5011352
                           [12]: KB5011651
                           [13]: KB5005699
Network Card(s):           9 NIC(s) Installed.
                           [01]: Zscaler Network Adapter 1.0.2.0
                                 Connection Name: Ethernet 2
                                 Status:          Media disconnected
                           [02]: Juniper Networks Virtual Adapter
                                 Connection Name: Ethernet 4
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 157.203.66.120
                                 [02]: fe80::348d:ddde:d4ba:bb76
                           [03]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (Default Switch)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 172.29.224.1
                                 [02]: fe80::dce:3818:f740:e12f
                           [04]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (vWiFi)
                                 Status:          Media disconnected
                           [05]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (vBackplane)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 192.168.234.1
                                 [02]: fe80::e900:e976:141a:b52e
                           [06]: Intel(R) Ethernet Connection I219-LM
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [07]: Intel(R) Dual Band Wireless-AC 8260
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.10.1
                                 IP address(es)
                                 [01]: 192.168.10.153
                           [08]: DisplayLink Network Adapter NCM
                                 Connection Name: Ethernet 3
                                 Status:          Media disconnected
                           [09]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (WSL)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 172.25.48.1
                                 [02]: fe80::d811:fc2a:1d49:2054
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

### Steps to reproduce

  1. Install OpenShift Local 2.2.2 on Windows 10 Enterprise edition
  2. Reboot
  3. Try to set up:
crc delete -f
crc cleanup
crc setup
crc start --log-level debug
crc-tray.exe

### Logs
C:\Program Files\Red Hat OpenShift Local>crc delete -f
Machine does not exist. Use 'crc start' to create it

C:\Program Files\Red Hat OpenShift Local>crc cleanup
INFO Removing daemon task
INFO Removing hosts file records added by CRC
INFO Removing pull secret from the keyring
INFO Removing older logs
INFO Removing CRC Machine Instance directory
INFO Removing crc's virtual machine
Cleanup finished

C:\Program Files\Red Hat OpenShift Local>crc setup
INFO Using bundle path C:\Users\A415415\.crc\cache\crc_hyperv_4.10.9_amd64.crcbundle
INFO Checking if current user is in Hyper-V Admins group
INFO Checking if CRC bundle is extracted in '$HOME/.crc'
INFO Checking if C:\Users\A415415\.crc\cache\crc_hyperv_4.10.9_amd64.crcbundle exists
INFO Checking if daemon task is installed
INFO Installing the daemon task
INFO Checking if daemon task is running
INFO Running the daemon task
INFO Checking admin helper service is running
Your system is correctly setup for using CRC. Use 'crc start' to start the instance

C:\Users\A415415\AppData\Roaming>crc start --log-level debug
DEBU CRC version: 2.2.2+be1af25f
DEBU OpenShift version: 4.10.9
DEBU Podman version: 3.4.4
DEBU Running 'crc start'
DEBU Total memory of system is 16943312896 bytes
DEBU No new version available. The latest version is 2.2.2
DEBU Checking file: C:\Users\A415415\.crc\machines\crc\.crc-exist
Is 'crc daemon' running? Cannot reach daemon API: Get "http://unix/api/version": open \\.\pipe\crc-http: The system cannot find the file specified.

C:\Users\A415415\AppData\Roaming>crc-tray
level=info msg="Using bundle path C:\\Users\\A415415\\.crc\\cache\\crc_hyperv_4.10.9_amd64.crcbundle"
level=info msg="Checking if current user is in Hyper-V Admins group"
level=info msg="Checking if CRC bundle is extracted in '$HOME/.crc'"
level=info msg="Checking if C:\\Users\\A415415\\.crc\\cache\\crc_hyperv_4.10.9_amd64.crcbundle exists"
level=info msg="Checking if daemon task is installed"
level=info msg="Checking if daemon task is running"
level=info msg="Checking admin helper service is running"
Status tick: HTTPError: Response code 500 (Internal Server Error)
Status tick: HTTPError: Response code 500 (Internal Server Error)
Status tick: HTTPError: Response code 500 (Internal Server Error)
Status tick: HTTPError: Response code 500 (Internal Server Error)
Status tick: HTTPError: Response code 500 (Internal Server Error)
Status tick: HTTPError: Response code 500 (Internal Server Error)
Status tick: HTTPError: Response code 500 (Internal Server Error)
Status tick: HTTPError: Response code 500 (Internal Server Error)

**Comment by praveenkumar** [comment]
> Is 'crc daemon' running? Cannot reach daemon API: Get "http://unix/api/version": open \.\pipe\crc-http: The system cannot find the file specified.

@gkuzmanov looks like the `crc daemon` process is not running can you check from task manager if there is any `crc` process which is running? Does the tray application is running which is named as `Red Hat OpenShift local` from the start menu?

**Comment by gkuzmanov** [comment]
There certainly was no crc daemon process running - is that a msi installer failure?  Is the msi installer meant to set the crc daemon up as a service on the target Windows 10 platform?

There is however a crc-admin-helper-windows.exe running with a "daemon" arg1:

"C:\Program Files\Red Hat OpenShift Local\crc-admin-helper-windows.exe" daemon

and the service wrapper around it:

C:\>sc query crcAdminHelper

SERVICE_NAME: crcAdminHelper
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

If that is the daemon why is "crc start" unable to contact it?

**Comment by gkuzmanov** [comment]
> > Is 'crc daemon' running? Cannot reach daemon API: Get "http://unix/api/version": open .\pipe\crc-http: The system cannot find the file specified.
> 
> @gkuzmanov looks like the `crc daemon` process is not running can you check from task manager if there is any `crc` process which is running? Does the tray application is running which is named as `Red Hat OpenShift local` from the start menu?

@praveenkumar There certainly was no crc.exe daemon process running - is that a msi installer failure?  Is the msi installer meant to set the crc daemon up as a service on the target Windows 10 platform?

There is however a crc-admin-helper-windows.exe running with a "daemon" arg1:

"C:\Program Files\Red Hat OpenShift Local\crc-admin-helper-windows.exe" daemon

and the service wrapper around it:

C:\>sc query crcAdminHelper

SERVICE_NAME: crcAdminHelper
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

If that is the daemon why is "crc start" unable to contact it?  Where does this daemon log when it is running in the background?

**Comment by praveenkumar** [comment]
> If that is the daemon why is "crc start" unable to contact it? Where does this daemon log when it is running in the background? System (event viewer) logs or text log files somewhere?

@gkuzmanov This daemon is started by system tray which you need to start from Start menu and `Red Hat OpenShift local`  once you have tray you can then use `crc start` from cli or from the tray itself.

**Comment by gkuzmanov** [comment]
> > If that is the daemon why is "crc start" unable to contact it? Where does this daemon log when it is running in the background? System (event viewer) logs or text log files somewhere?
> 
> @gkuzmanov This daemon is started by system tray which you need to start from Start menu and `Red Hat OpenShift local` once you have tray you can then use `crc start` from cli or from the tray itself.

@praveenkumar there is nothing in the system tray - though this does not explain where the daemon is meant to be started from.  Background and hidden/minimized applications sometimes display an icon in the systray area but it is not the systray that starts them.

Also, this does not explain what:

"C:\Program Files\Red Hat OpenShift Local\crc-admin-helper-windows.exe" daemon

is doing and why it does not display an icon in the systray.

**Comment by praveenkumar** [comment]
@gkuzmanov In windows we have 2 different daemon which need to be running before start the crc

- `crc-admin-helper-windows.exe daemon` => This is required to map openshift route to the host and it is running as part of service which you noticed and also running.

- `crc daemon` => This start the virtual network which responsible for VM - host communication and this should start as part of tray.

**Comment by gkuzmanov** [comment]
@praveenkumar I found at least one of the problems.

The work Windows laptop in question is forced by policy to run zScaler proxy.  It is a (corporately controlled) local proxy process listening locally on 127.0.0.1:9000 and also serving a proxy autoconf (pac) file for the benefit of local browsers.  The local zScaler proxy then connects over a split-tunnel exception bypassing the corporate VPN directly to a nearby zScaler proxy farm (dynamically determined, never twice the same IP address).

To accommodate another app which needed access to a Proxy Autoconfig file but needed to pick up the info via the HTTPS_PROXY env variable I used the following (slightly unusual) syntax:

HTTPS_PROXY=pac+http://127.0.0.1:9000/localproxy-1651836637.pac

where the "pac+" prefix indicates what follows in the value is actually the URL of a proxy autoconfig file to download instead of the fixed host:port of a proxy.

It seems the crc utilities do not understand that syntax but instead of issuing an error to that effect seem to twist themselves into knots.

Now that I removed the "pac+" prefix from the value of the HTTPS_PROXY environment variable the crc-tray app does run and does display in the systray.  What config files contain the settings exposed through the "Red Hat OpenShift Local" config dialogue?

![2022-05-11-crc-proxy-config](https://user-images.githubusercontent.com/34477082/167871017-17654807-8510-4332-911c-a17d5b1303d2.png)
![2022-05-11-crc-sizing-config](https://user-images.githubusercontent.com/34477082/167871048-09029493-5330-44c4-87a3-13cce528ed78.png)

Also, now that the crc tray is working, I get problems further down the line.

First, both daemons are running (the crc daemon and the crc-admin-helper-windows daemon).  But now even when I am not running the crc VM the Powershell one-liner polling the state of the crc Hyper-V VM is taking up 22-48% of my CPU!

![2022-05-11-vm-status-powershell-wreaking-havoc](https://user-images.githubusercontent.com/34477082/167871796-cc426598-6446-408f-a99d-3e25f49f6223.png)

Also, I seem to be getting spurious DNS errors from curl in the crc setup process, as well as ssh command errors from some of the admin context "oc get nodes" ssh commands:

![2022-05-11-dns-and-ssh-errors](https://user-images.githubusercontent.com/34477082/167872715-091975c5-eb7e-46ee-a0db-60626f744e21.png)

Running the same PowerShell command interactively returns immediately and takes almost no resources:

![2022-05-11-hyper-v-vm-state](https://user-images.githubusercontent.com/34477082/167874166-3da85e5a-63e1-4e90-8ef8-40c97498ce9d.png)

Also, running the curl command inside a WSL prompt does not produce any DNS errors:

![2022-05-11-curl-inside-wsl-no-dns-errors](https://user-images.githubusercontent.com/34477082/167874588-825a271f-24a4-4a6d-b1ab-67891ec27e85.png)

**Comment by praveenkumar** [comment]
@gkuzmanov About proxy we didn't test the Zscalar but when you specify it with `127.0.0.1:9000` to the VM then it is going to fail because this is something running on your host and VM doesn't have any info around it. Can you try following and see if that resolve your issue.

```
> crc.exe delete
> crc.exe config set host-network-access true
> crc.exe config set http-proxy http://host.crc.testing:9000
<--- if this also require https or need proxy certs then use following setting also ---->
> crc.exe config set https-proxy  <https_proxy_url>
> crc.exe config set proxy-ca-file <ca-file-path>
```

About CPU spike I checked on my windows system but didn't able to reproduce it. Will check with our QE team if they able to reproduce that CPU spike.
![Screenshot (8)](https://user-images.githubusercontent.com/410007/168226798-64f2599e-b5f0-41b5-9af4-7753d4f49039.png)

**Comment by gbraad** [comment]
> Powershell one-liner polling the state of the crc Hyper-V VM is taking up 22-48% of my CPU!

the crc-tray is hecking the status of the VM, and perhaps this might be the case that the application is reporting an issue here. Is the VM 'stopped' or 'deleted' ?

**Comment by gbraad** [comment]
> pac+http://127.0.0.1:9000/localproxy-1651836637.pac

The pac is an autoconfig file. It would contain a set of rules to follow (based on a javascript state machine). Most of the tools, such as the OpenShift cluster or podman would not know how to handle this anyway.

It might be better to load the file and observe the rules and use the one that is appropriate for the use of the proxy/outside path.

eg. `DIRECT` would mean it would not use the proxy, while `PROXY ...` would sent the data to a specified proxy. Since you mention it is a split tunnel, I think it is most likely they catch local endpoints and one or two remote endpoints over the VPN.
