### ISSUE TITLE
.xz is actually uncompressed tar

### ISSUE THREAD

**Issue by srl295** [code-ready/crc#324]
```
$ curl -L https://github.com/code-ready/crc/releases/download/0.88.0/crc-0.88.0-linux-amd64.tar.xz | file -
/dev/stdin: POSIX tar archive (GNU)
```

it's not xz compressed. (unless curl is uncompressing?)

**Comment by srl295** [comment]
either the file should be compressed, or rename it to just `crc-0.88.0-linux-amd64.tar`

**Comment by praveenkumar** [comment]
@srl295 yes, you are right, looks like last release we didn't use the proper options to create and `xz` compression files. We will try to have it as part of Makefile to make our life easy in that regards.

**Comment by praveenkumar** [comment]
This is now fixed and we have it part of our Makefile now.
