### ISSUE TITLE
[BUG]  crc  2.5.1 setup/start fails on new host:  DEBU stderr: Failed to connect to bus: No such file or directory  DEBU Could not get crc-daemon.service  status: Executing systemctl action failed: ..  Failed to connect to bus: No such file or directory 

### ISSUE THREAD

**Issue by rscher** [code-ready/crc#3248]
### General information

  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / Hyper-V / hyperkit / vfkit
  * Did you run `crc setup` before starting it (Yes/No)?
  * Running CRC on: Laptop / Baremetal-Server / VM

Linux/KVM/VM

## CRC version
```bash
# Put `crc version` output here

[crcuser@rh85 ~]$ crc version
CRC version: 2.5.1+3d569b8
OpenShift version: 4.10.18
Podman version: 4.1.0
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
```

## CRC config
```bash
# Put `crc config view` output here
```
[crcuser@rh85 ~]$ crc config view
- consent-telemetry              : no
- cpus                                  : 16
- disk-size                             : 64
- enable-cluster-monitoring      : true
- kubeadmin-password                    : ********
- memory                                : 49152
- pull-secret-file                      : /home/crcuser/pull-secret.txt

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```
[crcuser@rh85 ~]$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.6 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"

### Steps to reproduce

run script:
$ cat temp_bootstrap_crc.sh 
#!/bin/bash
 logLevel=debug 
 crc config set consent-telemetry no
 crc config set cpus 16
 crc config set memory  49152 
 crc config set pull-secret-file ~/pull-secret.txt
 crc config set kubeadmin-password *****
 crc config set disk-size  64
 crc config set enable-cluster-monitoring true
 crc setup --log-level $logLevel
 crc start --log-level $logLevel

### Expected
setup: crc and bundle to be downloaded
start:  create crc VM and OpenShift cluster starts like in  all other  RHEL hosts  .
not sure how to fix this 

### Actual
 crc  2.5.1 setup/start fails setting up on new host: 
**DEBU stderr: Failed to connect to bus: No such file or directory  DEBU Could not get crc-daemon.service  status: Executing systemctl action failed: ..  Failed to connect to bus: No such file or directory** 

### Logs

[crcuser@rh85 ~]$ ./temp_bootstrap_crc.sh 
Successfully configured consent-telemetry to no
Changes to configuration property 'cpus' are only applied when the CRC instance is started.
If you already have a running CRC instance, then for this configuration change to take effect, stop the CRC instance with 'crc stop' and restart it with 'crc start'.
Changes to configuration property 'memory' are only applied when the CRC instance is started.
If you already have a running CRC instance, then for this configuration change to take effect, stop the CRC instance with 'crc stop' and restart it with 'crc start'.
Successfully configured pull-secret-file to /home/crcuser/pull-secret.txt
Successfully configured kubeadmin-password to ****
Changes to configuration property 'disk-size' are only applied when the CRC instance is started.
If you already have a running CRC instance, then for this configuration change to take effect, stop the CRC instance with 'crc stop' and restart it with 'crc start'.
Successfully configured enable-cluster-monitoring to true
DEBU CRC version: 2.5.1+3d569b8                   
DEBU OpenShift version: 4.10.18                   
DEBU Podman version: 4.1.0                        
DEBU Running 'crc setup'                          
INFO Using bundle path /home/crcuser/.crc/cache/crc_libvirt_4.10.18_amd64.crcbundle 
DEBU Checking if systemd-resolved.service is running 
DEBU Running 'systemctl status systemd-resolved.service' 
DEBU systemd-resolved.service is already running  
INFO Checking if running as non-root              
INFO Checking if running inside WSL2              
INFO Checking if crc-admin-helper executable is cached 
DEBU Running '/home/crcuser/.crc/bin/crc-admin-helper-linux --version' 
DEBU Found crc-admin-helper-linux version 0.0.11  
DEBU crc-admin-helper executable already cached   
INFO Checking for obsolete admin-helper executable 
DEBU Checking if an older admin-helper executable is installed 
DEBU No older admin-helper executable found       
INFO Checking if running on a supported CPU architecture 
DEBU GOARCH is amd64 GOOS is linux                
INFO Checking minimum RAM requirements            
DEBU Total memory of system is 65747271680 bytes  
INFO Checking if crc executable symlink exists    
INFO Checking if Virtualization is enabled        
DEBU Checking if the vmx/svm flags are present in /proc/cpuinfo 
DEBU CPU virtualization flags are good            
INFO Checking if KVM is enabled                   
DEBU Checking if /dev/kvm exists                  
DEBU /dev/kvm was found                           
INFO Checking if libvirt is installed             
DEBU Checking if 'virsh' is available             
DEBU 'virsh' was found in /usr/bin/virsh          
DEBU Checking 'virsh capabilities' for libvirtd/qemu availability 
DEBU Running 'virsh --readonly --connect qemu:///system capabilities' 
DEBU Found x86_64 hypervisor with 'hvm' capabilities 
INFO Checking if user is part of libvirt group    
DEBU Checking if current user is part of the libvirt group 
DEBU Current user is already in the libvirt group 
INFO Checking if active user/process is currently part of the libvirt group 
INFO Checking if libvirt daemon is running        
DEBU Checking if libvirtd service is running      
DEBU Running 'systemctl status virtqemud.socket'  
DEBU virtqemud.socket is running                  
INFO Checking if a supported libvirt version is installed 
DEBU Checking if libvirt version is >=3.4.0       
DEBU Running 'virsh -v'                           
INFO Checking if crc-driver-libvirt is installed  
DEBU Checking if crc-driver-libvirt is installed  
DEBU Running '/home/crcuser/.crc/bin/crc-driver-libvirt version' 
DEBU Found crc-driver-libvirt version 0.13.2      
DEBU crc-driver-libvirt is already installed      
INFO Checking crc daemon systemd service          
DEBU Checking crc daemon systemd service          
DEBU Checking if crc-daemon.service is running    
DEBU Running 'systemctl --user status crc-daemon.service' 
DEBU Command failed: exit status 1                
DEBU stdout:                                      
DEBU stderr: Failed to connect to bus: No such file or directory 
DEBU Could not get crc-daemon.service  status: Executing systemctl action failed:  exit status 1: Failed to connect to bus: No such file or directory 
DEBU Checking if crc-daemon.service has the expected content 
INFO Checking crc daemon systemd socket units     
DEBU Checking crc daemon systemd socket units     
DEBU Checking if crc-http.socket is running       
DEBU Running 'systemctl --user status crc-http.socket' 
DEBU Command failed: exit status 1                
DEBU stdout:                                      
DEBU stderr: Failed to connect to bus: No such file or directory 
DEBU Could not get crc-http.socket  status: Executing systemctl action failed:  exit status 1: Failed to connect to bus: No such file or directory 
DEBU crc-http.socket is not running               
INFO Setting up crc daemon systemd socket units   
DEBU Setting up crc daemon systemd socket units   
DEBU Setting up crc-http.socket                   
**DEBU Running 'systemctl --user status crc-http.socket' 
DEBU Command failed: exit status 1                
DEBU stdout:                                      
DEBU stderr: Failed to connect to bus: No such file or directory 
DEBU Could not get crc-http.socket  status: Executing systemctl action failed:  exit status 1: Failed to connect to bus: No such file or directory 
DEBU Starting crc-http.socket                     
DEBU Running 'systemctl --user enable crc-http.socket' 
DEBU Command failed: exit status 1                
DEBU stdout:                                      
DEBU stderr: Failed to connect to bus: No such file or directory 
Executing systemctl action failed:  exit status 1: Failed to connect to bus: No such file or directory**
DEBU CRC version: 2.5.1+3d569b8                   
DEBU OpenShift version: 4.10.18                   
DEBU Podman version: 4.1.0                        
DEBU Running 'crc start'                          
DEBU Total memory of system is 65747271680 bytes  
file '/home/crcuser/.crc/cache/crc_libvirt_4.10.18_amd64.crcbundle' does not exist

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```
Yes tried the following to clean out any references ..
crc  delete -f
crc cleanup
virsh -c qemu:///system destroy crc
virsh -c qemu:///system undefine crc
rm -rf ~/.crc

--
still fails  with

 Running 'systemctl --user status crc-http.socket' 
DEBU Command failed: exit status 1                
DEBU stdout:                                      
DEBU stderr: Failed to connect to bus: No such file or directory 
DEBU Could not get crc-http.socket  status: Executing systemctl action failed:  exit status 1: Failed to connect to bus: No such file or directory 

[crcuser@rh85 ~]$ **sudo systemctl status   virtlockd.socket ; sudo systemctl status  libvirtd ;  sudo systemctl status virtlockd.socket ; sudo  systemctl status virtqemud.socket** 
● virtlockd.socket - Virtual machine lock manager socket
   Loaded: loaded (/usr/lib/systemd/system/virtlockd.socket; enabled; vendor preset: disabled)
   Active: active (listening) since Tue 2022-07-05 18:48:25 EDT; 1h 6min ago
   Listen: /run/libvirt/virtlockd-sock (Stream)
    Tasks: 0 (limit: 401008)
   Memory: 0B
   CGroup: /system.slice/virtlockd.socket

Jul 05 18:48:25 rh85 systemd[1]: Stopping Virtual machine lock manager socket.
Jul 05 18:48:25 rh85 systemd[1]: Listening on Virtual machine lock manager socket.
● libvirtd.service - Virtualization daemon
   Loaded: loaded (/usr/lib/systemd/system/libvirtd.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2022-07-05 19:54:22 EDT; 3s ago
     Docs: man:libvirtd(8)
           https://libvirt.org
 Main PID: 229213 (libvirtd)
    Tasks: 21 (limit: 32768)
   Memory: 73.5M
   CGroup: /system.slice/libvirtd.service
           ├─  1912 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
           ├─  1913 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
           └─229213 /usr/sbin/libvirtd --timeout 120

Jul 05 19:54:22 rh85 systemd[1]: Starting Virtualization daemon...
Jul 05 19:54:22 rh85 systemd[1]: Started Virtualization daemon.
Jul 05 19:54:22 rh85 dnsmasq[1912]: read /etc/hosts - 4 addresses
Jul 05 19:54:22 rh85 dnsmasq[1912]: read /var/lib/libvirt/dnsmasq/default.addnhosts - 0 addresses
Jul 05 19:54:22 rh85 dnsmasq-dhcp[1912]: read /var/lib/libvirt/dnsmasq/default.hostsfile
● virtlockd.socket - Virtual machine lock manager socket
   Loaded: loaded (/usr/lib/systemd/system/virtlockd.socket; enabled; vendor preset: disabled)
   Active: active (listening) since Tue 2022-07-05 18:48:25 EDT; 1h 6min ago
   Listen: /run/libvirt/virtlockd-sock (Stream)
    Tasks: 0 (limit: 401008)
   Memory: 0B
   CGroup: /system.slice/virtlockd.socket

Jul 05 18:48:25 rh85 systemd[1]: Stopping Virtual machine lock manager socket.
Jul 05 18:48:25 rh85 systemd[1]: Listening on Virtual machine lock manager socket.
● virtqemud.socket - Libvirt qemu local socket
   Loaded: loaded (/usr/lib/systemd/system/virtqemud.socket; enabled; vendor preset: disabled)
   Active: active (listening) since Tue 2022-07-05 18:50:11 EDT; 1h 4min ago
   Listen: /run/libvirt/virtqemud-sock (Stream)
    Tasks: 0 (limit: 401008)
   Memory: 0B
   CGroup: /system.slice/virtqemud.socket

Jul 05 18:50:11 rh85 systemd[1]: Listening on Libvirt qemu local socket.

apprec any guidance !

-Russ
IBM Cloud

**Comment by praveenkumar** [comment]
@rscher looks like https://github.com/code-ready/crc/issues/2815#issuecomment-948355390 can you try and let us know if that works?

**Comment by rscher** [comment]
> @rscher looks like [#2815 (comment)](https://github.com/code-ready/crc/issues/2815#issuecomment-948355390) can you try and let us know if that works?
 @praveenkumar  that  didnt work alone, but ran cmds from here:  https://github.com/code-ready/crc/issues/2839
and crc setup worked after that.
thanks again for your help !
-Russ

[crcuser@rh85 ~]$ cat ./fix.sh
 crc cleanup
 sudo systemctl stop libvirtd.service
 sudo systemctl stop libvirtd{,-ro,-admin,-tcp,-tls}.socket
 sudo systemctl disable libvirtd.service
 sudo systemctl disable libvirtd{,-ro,-admin,-tcp,-tls}.socket
 for drv in qemu interface network nodedev nwfilter secret storage
  do
    sudo systemctl unmask virt${drv}d.service
    sudo systemctl unmask virt${drv}d{,-ro,-admin}.socket
    sudo systemctl enable virt${drv}d.service
    sudo systemctl enable virt${drv}d{,-ro,-admin}.socket
  done
   for drv in qemu network nodedev nwfilter secret storage
  do
    sudo systemctl start virt${drv}d{,-ro,-admin}.socket
  done
 sudo  systemctl is-active virtnetworkd.socket
 sudo systemctl is-active virtnetworkd.service
--

[crcuser@rh85 ~]$ ./fix.sh 
INFO Removing vsock configuration                 
INFO Removing 'crc' network from libvirt          
INFO Removing /etc/NetworkManager/dispatcher.d/99-crc.sh file 
INFO Using root access: Removing NetworkManager configuration file in /etc/NetworkManager/dispatcher.d/99-crc.sh 
INFO Using root access: Executing systemctl daemon-reload command 
INFO Using root access: Executing systemctl reload NetworkManager 
INFO Removing crc daemon systemd socket units     
INFO Removing crc daemon systemd service          
INFO Removing crc's virtual machine               
INFO Removing crc libvirt storage pool            
INFO Removing hosts file records added by CRC     
INFO Removing pull secret from the keyring        
INFO Removing older logs                          
INFO Removing CRC Machine Instance directory      
INFO Removing crc executable symlink              
Cleanup finished
Created symlink /etc/systemd/system/multi-user.target.wants/virtqemud.service → /usr/lib/systemd/system/virtqemud.service.
Created symlink /etc/systemd/system/sockets.target.wants/virtlogd.socket → /usr/lib/systemd/system/virtlogd.socket.
Created symlink /etc/systemd/system/sockets.target.wants/virtlockd.socket → /usr/lib/systemd/system/virtlockd.socket.
Created symlink /etc/systemd/system/multi-user.target.wants/virtinterfaced.service → /usr/lib/systemd/system/virtinterfaced.service.
Created symlink /etc/systemd/system/multi-user.target.wants/virtnetworkd.service → /usr/lib/systemd/system/virtnetworkd.service.
Created symlink /etc/systemd/system/multi-user.target.wants/virtnodedevd.service → /usr/lib/systemd/system/virtnodedevd.service.
Created symlink /etc/systemd/system/multi-user.target.wants/virtnwfilterd.service → /usr/lib/systemd/system/virtnwfilterd.service.
Created symlink /etc/systemd/system/multi-user.target.wants/virtsecretd.service → /usr/lib/systemd/system/virtsecretd.service.
Created symlink /etc/systemd/system/sockets.target.wants/virtsecretd.socket → /usr/lib/systemd/system/virtsecretd.socket.
Created symlink /etc/systemd/system/sockets.target.wants/virtsecretd-ro.socket → /usr/lib/systemd/system/virtsecretd-ro.socket.
Created symlink /etc/systemd/system/sockets.target.wants/virtsecretd-admin.socket → /usr/lib/systemd/system/virtsecretd-admin.socket.
Created symlink /etc/systemd/system/multi-user.target.wants/virtstoraged.service → /usr/lib/systemd/system/virtstoraged.service.
Created symlink /etc/systemd/system/sockets.target.wants/virtstoraged.socket → /usr/lib/systemd/system/virtstoraged.socket.
Created symlink /etc/systemd/system/sockets.target.wants/virtstoraged-ro.socket → /usr/lib/systemd/system/virtstoraged-ro.socket.
Created symlink /etc/systemd/system/sockets.target.wants/virtstoraged-admin.socket → /usr/lib/systemd/system/virtstoraged-admin.socket.
active
active

[crcuser@rh85 ~]$  echo $XDG_RUNTIME_DIR ; echo $DBUS_SESSION_BUS_ADDRESS
/run/user/1001
unix:path=/run/user/1001/bus

[crcuser@rh85 ~]$ ./temp_bootstrap_crc.sh 
Successfully configured skip-check-daemon-systemd-unit to true
Successfully configured skip-check-daemon-systemd-sockets to true
Successfully configured consent-telemetry to no
Changes to configuration property 'cpus' are only applied when the CRC instance is started.
If you already have a running CRC instance, then for this configuration change to take effect, stop the CRC instance with 'crc stop' and restart it with 'crc start'.
Changes to configuration property 'memory' are only applied when the CRC instance is started.
If you already have a running CRC instance, then for this configuration change to take effect, stop the CRC instance with 'crc stop' and restart it with 'crc start'.
Successfully configured pull-secret-file to /home/crcuser/pull-secret.txt
Successfully configured kubeadmin-password to ****
Changes to configuration property 'disk-size' are only applied when the CRC instance is started.
If you already have a running CRC instance, then for this configuration change to take effect, stop the CRC instance with 'crc stop' and restart it with 'crc start'.
Successfully configured enable-cluster-monitoring to true
DEBU CRC version: 2.5.1+3d569b8                   
DEBU OpenShift version: 4.10.18                   
DEBU Podman version: 4.1.0                        
DEBU Running 'crc setup'                          
.. 
 <skipping lines>
..
INFO Starting libvirt 'crc' network               
DEBU Starting libvirt 'crc' network               
DEBU Running 'virsh --connect qemu:///system net-start crc' 
DEBU Running 'virsh --connect qemu:///system net-autostart crc' 
DEBU libvirt 'crc' network started                
INFO Checking if CRC bundle is extracted in '$HOME/.crc' 
INFO Checking if /home/crcuser/.crc/cache/crc_libvirt_4.10.18_amd64.crcbundle exists 
DEBU error getting bundle info for crc_libvirt_4.10.18_amd64.crcbundle: could not find cached bundle info in /home/crcuser/.crc/cache/crc_libvirt_4.10.18_amd64: stat /home/crcuser/.crc/cache/crc_libvirt_4.10.18_amd64: no such file or directory 
DEBU could not find cached bundle info in /home/crcuser/.crc/cache/crc_libvirt_4.10.18_amd64: stat /home/crcuser/.crc/cache/crc_libvirt_4.10.18_amd64: no such file or directory 
INFO Getting bundle for the CRC executable        
DEBU Ensuring directory /home/crcuser/.crc/cache exists 
INFO Downloading crc_libvirt_4.10.18_amd64.crcbundle 
DEBU Downloading https://mirror.openshift.com/pub/openshift-v4/clients/crc/bundles/openshift/4.10.18/crc_libvirt_4.10.18_amd64.crcbundle to /home/crcuser/.crc/cache/crc_libvirt_4.10.18_amd64.crcbundle 
3.13 GiB / 3.13 GiB [----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 40.86 MiB p/s
DEBU Download saved to /home/crcuser/.crc/cache/crc_libvirt_4.10.18_amd64.crcbundle 
INFO Uncompressing /home/crcuser/.crc/cache/crc_libvirt_4.10.18_amd64.crcbundle 
DEBU Uncompressing /home/crcuser/.crc/cache/crc_libvirt_4.10.18_amd64.crcbundle to /home/crcuser/.crc/cache/tmp-extract 
crc.qcow2: 12.45 GiB / 12.45 GiB [-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00%
oc: 117.14 MiB / 117.14 MiB [----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00%
DEBU retry loop: attempt 0                        
Your system is correctly setup for using CRC. Use 'crc start' to start the instance

**Comment by praveenkumar** [comment]
@rscher your latest logs shows that crc is setup correctly and you can start the cluster, anything else is missing?

**Comment by rscher** [comment]
> @rscher your latest logs shows that crc is setup correctly and you can start the cluster, anything else is missing?

hi @praveenkumar , got it all working again.
One thing I noted, which may be specific to our hosting env (nested VM) ...
 the cluster starts up within 3 minutes and I can 'oc login', but the  'crc  start' is still reporting  'cluster degraded' 
 messages for up to ~12 minutes  then finally stabilizes and reports it has started and shows the login info/credentials.
 cluster monitoring is enabled.

**Comment by praveenkumar** [comment]
@rscher `cluster degraded` means some operator still in reconcile state and take bit time to stable, since you have cluster monitoring enabled it might take bit more time in nested environment.

I am closing this issue now.
