### ISSUE TITLE
[BUG] windows msi installer fail to add local user to Hyper-V Administrators group

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/crc#3254]
Testing on a fresh environment:

1. run msi installer 
2. reboot computer
3. run `crc setup`

Expected 

System fully configured and ready to `start crc`

Actual

User is added to Hyper-V Administrator group during `crc setup`, so after finish it asks for a second reboot

**Comment by praveenkumar** [comment]
@adrianriobo FYI, I also hit same bug, will look into it next sprint.
