### ISSUE TITLE
[Epic] CRC with openshift preset on M1/M2

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#3265]
As of now we only support podman preset for M1/M2 but there is no option for user to try openshift preset. We thought since OKD uses FCOS might be able to deliver something for M1/M2 users but as of now OKD doesn't support multi arch. 

- [ ] Check if it is possible to use early bits of RHCOS-9 (if available) to create bundle
- [ ] Try to create add CI job for bundle creation and testing.

**Comment by praveenkumar** [comment]
CRC now support openshift preset for M1/M2 and we create the bundle on a arm64 machine.

**Comment by IBMRob** [comment]
@praveenkumar - The latest release nodes are still saying that only podman is supported - https://access.redhat.com/documentation/en-us/red_hat_openshift_local/2.5/html/release_notes_and_known_issues/minimum-system-requirements_rn-ki

Can you confirm which version includes support?

**Comment by KevinMGranger** [comment]
@IBMRob I don't know which version added it, but I ran the latest version (2.9) and it appears to work.

**Comment by cfergeau** [comment]
This was first added in 2.4.1, see https://crc.dev/blog/posts/2022-08-17-ocp-on-m1/
The release notes on access.redhat.com are unfortunately getting outdated :(
