### ISSUE TITLE
Planned support for OpenShift 4.11

### ISSUE THREAD

**Issue by balpert89** [code-ready/crc#3276]
Hi,

is there already any development towards 4.11 ongoing? According to our TAM the new stable minor version is expected any day now and we want to start updating our dependencies. We use `crc` for our end-to-end tests so we have kind of a dependency here.

Any input would be much appreciated.

Best regards

**Comment by praveenkumar** [comment]
@balpert89 we will do the release of crc as soon as OCP-4.11 goes to publish, internally we are testing out if everything is still working smoothly with `rc` bits.

**Comment by balpert89** [comment]
Wonderful, many thanks for the quick reply :)

**Comment by gbraad** [comment]
We will always try to track the upcoming release and report back about issues during the RC period. This to ensure a swift release with the latest release.

We will release when the OCP release is out ;-) not any time sooner...
