### ISSUE TITLE
[BUG] vsock device is not supported with this QEMU binary

### ISSUE THREAD

**Issue by Kalinins93** [code-ready/crc#3278]
Hello, i try runing crc with network-mode user. After i, get this message and my crc is not running. Failed to create the VM: virError(Code=67, Domain=10, Message='unsupported configuration: vsock device is not supported with this QEMU binary').
Help me, please. I dont know what to do.
### General information

  * OS: Linux Centos 7
  * Hypervisor:Hyper-V 
  * Did you run `crc setup` before starting it (Yes?
  * Running CRC on: Laptop

## CRC version
```bash
CRC version: 2.6.0+d606e64
OpenShift version: 4.10.22
Podman version: 4.1.0

```
  
## CRC status
```bash
DEBU CRC version: 2.6.0+d606e64
DEBU OpenShift version: 4.10.22
DEBU Podman version: 4.1.0
DEBU Running 'crc status'
DEBU Checking file: /home/dev/.crc/machines/crc/.crc-exist
Machine does not exist. Use 'crc start' to create it
```

## CRC config
```bash
[dev@dev-msa ~]$ crc config view
- consent-telemetry                     : yes
- host-network-access                   : true
- network-mode                          : user
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```

### Steps to reproduce

  1. crc delete
  2. crc setup
  3. crc start
  4. -

### Logs
DEBU CRC version: 2.6.0+d606e64
DEBU OpenShift version: 4.10.22
DEBU Podman version: 4.1.0
DEBU Running 'crc start'
DEBU Total memory of system is 16656875520 bytes
DEBU No new version available. The latest version is 2.6.0
DEBU Checking file: /home/dev/.crc/machines/crc/.crc-exist
DEBU Checking if systemd-resolved.service is running
DEBU Running 'systemctl status systemd-resolved.service'
DEBU Command failed: exit status 4
DEBU stdout:
DEBU stderr: Unit systemd-resolved.service could not be found.
INFO Checking if running as non-root
INFO Checking if running inside WSL2
INFO Checking if crc-admin-helper executable is cached
DEBU Running '/home/dev/.crc/bin/crc-admin-helper-linux --version'
DEBU Found crc-admin-helper-linux version 0.0.11
DEBU crc-admin-helper executable already cached
INFO Checking for obsolete admin-helper executable
DEBU Checking if an older admin-helper executable is installed
DEBU No older admin-helper executable found
INFO Checking if running on a supported CPU architecture
DEBU GOARCH is amd64 GOOS is linux
INFO Checking minimum RAM requirements
DEBU Total memory of system is 16656875520 bytes
INFO Checking if crc executable symlink exists
INFO Checking if Virtualization is enabled
DEBU Checking if the vmx/svm flags are present in /proc/cpuinfo
DEBU CPU virtualization flags are good
INFO Checking if KVM is enabled
DEBU Checking if /dev/kvm exists
DEBU /dev/kvm was found
INFO Checking if libvirt is installed
DEBU Checking if 'virsh' is available
DEBU 'virsh' was found in /usr/bin/virsh
DEBU Checking 'virsh capabilities' for libvirtd/qemu availability
DEBU Running 'virsh --readonly --connect qemu:///system capabilities'
DEBU Found x86_64 hypervisor with 'hvm' capabilities
INFO Checking if user is part of libvirt group
DEBU Checking if current user is part of the libvirt group
DEBU Current user is already in the libvirt group
INFO Checking if active user/process is currently part of the libvirt group
INFO Checking if libvirt daemon is running
DEBU Checking if libvirtd service is running
DEBU Running 'systemctl status virtqemud.socket'
DEBU Command failed: exit status 4
DEBU stdout:
DEBU stderr: Unit virtqemud.socket could not be found.
DEBU virtqemud.socket is neither running nor listening
DEBU Running 'systemctl status libvirtd.socket'
DEBU Command failed: exit status 4
DEBU stdout:
DEBU stderr: Unit libvirtd.socket could not be found.
DEBU libvirtd.socket is neither running nor listening
DEBU Running 'systemctl status virtqemud.service'
DEBU Command failed: exit status 4
DEBU stdout:
DEBU stderr: Unit virtqemud.service could not be found.
DEBU virtqemud.service is neither running nor listening
DEBU Running 'systemctl status libvirtd.service'
DEBU libvirtd.service is running
INFO Checking if a supported libvirt version is installed
DEBU Checking if libvirt version is >=3.4.0
DEBU Running 'virsh -v'
INFO Checking if crc-driver-libvirt is installed
DEBU Checking if crc-driver-libvirt is installed
DEBU Running '/home/dev/.crc/bin/crc-driver-libvirt version'
DEBU Found crc-driver-libvirt version 0.13.3
DEBU crc-driver-libvirt is already installed
INFO Checking if crc daemon will be autostarted
WARN systemd --user is not available, crc daemon won't be autostarted and must be run manually before using CRC
INFO Checking if vsock is correctly configured
DEBU Running 'getcap /home/dev/bin/crc'
DEBU Checking file: /home/dev/.crc/machines/crc/.crc-exist
INFO Loading bundle: crc_libvirt_4.10.22_amd64...
DEBU Using secret from configuration
INFO Creating CRC VM for OpenShift 4.10.22...
DEBU Found binary path at /home/dev/.crc/bin/crc-driver-libvirt
DEBU Launching plugin server for driver libvirt
DEBU Plugin server listening at address 127.0.0.1:40728
DEBU () Calling .GetVersion
DEBU Using API Version 1
DEBU () Calling .SetConfigRaw
DEBU () Calling .GetMachineName
DEBU (crc) Calling .GetMachineName
DEBU (crc) Calling .DriverName
DEBU Running pre-create checks...
DEBU (crc) Calling .PreCreateCheck
DEBU (crc) DBG | time="2022-07-27T22:11:35+03:00" level=debug msg="About to check libvirt version"
DEBU (crc) DBG | time="2022-07-27T22:11:35+03:00" level=debug msg="Validating storage pool"
DEBU (crc) DBG | time="2022-07-27T22:11:35+03:00" level=debug msg="Could not find storage pool 'crc', trying to create it"
DEBU (crc) DBG | time="2022-07-27T22:11:35+03:00" level=debug msg="Creating storage pool"
DEBU (crc) DBG | time="2022-07-27T22:11:35+03:00" level=info msg="Creating storage pool with XML <pool type=\"dir\">\n  <name>crc</name>\n  <target>\n    <path>/home/dev/.crc/machines/crc</path>\n  </target>\n</pool>"
DEBU (crc) DBG | time="2022-07-27T22:11:35+03:00" level=debug msg="Activating pool 'crc'"
DEBU (crc) Calling .GetConfigRaw
DEBU Creating machine...
DEBU (crc) Calling .Create
DEBU (crc) DBG | time="2022-07-27T22:11:35+03:00" level=debug msg="Preparing /home/dev/.crc/machines/crc/crc.qcow2 for machine use"
DEBU (crc) DBG | time="2022-07-27T22:11:35+03:00" level=debug msg="image creation took 16.937764ms"
DEBU (crc) DBG | time="2022-07-27T22:11:35+03:00" level=debug msg="Verifying executable bit set on /home/dev/.crc/machines/crc"
DEBU (crc) DBG | time="2022-07-27T22:11:35+03:00" level=debug msg="Verifying executable bit set on /home/dev/.crc/machines"
DEBU (crc) DBG | time="2022-07-27T22:11:35+03:00" level=debug msg="Verifying executable bit set on /home/dev/.crc"
DEBU (crc) DBG | time="2022-07-27T22:11:35+03:00" level=debug msg="Verifying executable bit set on /home/dev"
DEBU (crc) DBG | time="2022-07-27T22:11:35+03:00" level=debug msg="Verifying executable bit set on /home"
DEBU (crc) DBG | time="2022-07-27T22:11:35+03:00" level=debug msg="Defining VM..."
DEBU (crc) DBG | time="2022-07-27T22:11:35+03:00" level=debug msg="Found x86_64 hypervisor with 'hvm' capabilities"
DEBU (crc) DBG | time="2022-07-27T22:11:35+03:00" level=debug msg="No q35 machine type"
DEBU Making call to close driver server
DEBU (crc) Calling .Close
DEBU (crc) DBG | time="2022-07-27T22:11:35+03:00" level=warning msg="Failed to create the VM: virError(Code=67, Domain=10, Message='unsupported configuration: vsock device is not supported with this QEMU binary')"
DEBU (crc) DBG | time="2022-07-27T22:11:35+03:00" level=debug msg="Closing plugin on server side"
DEBU Successfully made call to close driver server
DEBU Making call to close connection to plugin binary
Error creating machine: Error in driver during machine creation: virError(Code=67, Domain=10, Message='unsupported configuration: vsock device is not supported with this QEMU binary')

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

**Comment by praveenkumar** [comment]
@Kalinins93 There is few details which need bit explanation. As per issue you  put following as part of general info
```
OS: Linux Centos 7
Hypervisor:Hyper-V
```

Does that mean you are running the Centos7 on hyperV and then running crc on that machine (nested virtualization setup?)

Also as part of config you selected `user` mode networking, on linux you can also check the default `system` mode networking and see if that works.

**Comment by cfergeau** [comment]
QEMU version would be useful to know, but if possible at all, I'd recommend upgrading to centos8

**Comment by Kalinins93** [comment]
I upgrade centos 7  to centos 8, and all working now. Thank a lot.
