### ISSUE TITLE
Add a config option to enable/disable directory sharing

### ISSUE THREAD

**Issue by anjannath** [code-ready/crc#3285]
While testing on RHEL 8.5 and libvirt 8.0.0 `crc start` ends up with error `Failed to create the VM: virError(Code=67, Domain=10, Message='unsupported configuration: 'virtiofs' requires shared memory')"`

but the podman preset on macOS where this is most beneficial works without any issues we can add a config option `enable-shared-dirs` to provide an option to the user to disable it if they face any issues

**Comment by praveenkumar** [comment]
```
$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.5 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.5 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.5"


$ rpm -qa | grep libvirt
libvirt-daemon-driver-nwfilter-6.0.0-37.module+el8.5.0+12162+40884dd2.x86_64
libvirt-daemon-driver-interface-6.0.0-37.module+el8.5.0+12162+40884dd2.x86_64
libvirt-daemon-driver-storage-gluster-6.0.0-37.module+el8.5.0+12162+40884dd2.x86_64
libvirt-daemon-driver-storage-rbd-6.0.0-37.module+el8.5.0+12162+40884dd2.x86_64
libvirt-daemon-config-network-6.0.0-37.module+el8.5.0+12162+40884dd2.x86_64
libvirt-6.0.0-37.module+el8.5.0+12162+40884dd2.x86_64
libvirt-libs-6.0.0-37.module+el8.5.0+12162+40884dd2.x86_64
libvirt-bash-completion-6.0.0-37.module+el8.5.0+12162+40884dd2.x86_64
libvirt-daemon-driver-storage-core-6.0.0-37.module+el8.5.0+12162+40884dd2.x86_64
libvirt-daemon-driver-secret-6.0.0-37.module+el8.5.0+12162+40884dd2.x86_64
libvirt-daemon-driver-qemu-6.0.0-37.module+el8.5.0+12162+40884dd2.x86_64
libvirt-daemon-config-nwfilter-6.0.0-37.module+el8.5.0+12162+40884dd2.x86_64
libvirt-daemon-driver-storage-logical-6.0.0-37.module+el8.5.0+12162+40884dd2.x86_64
libvirt-daemon-driver-storage-mpath-6.0.0-37.module+el8.5.0+12162+40884dd2.x86_64
libvirt-daemon-driver-storage-disk-6.0.0-37.module+el8.5.0+12162+40884dd2.x86_64
libvirt-daemon-driver-storage-iscsi-6.0.0-37.module+el8.5.0+12162+40884dd2.x86_64
libvirt-daemon-driver-network-6.0.0-37.module+el8.5.0+12162+40884dd2.x86_64
libvirt-daemon-6.0.0-37.module+el8.5.0+12162+40884dd2.x86_64
libvirt-daemon-driver-nodedev-6.0.0-37.module+el8.5.0+12162+40884dd2.x86_64
libvirt-daemon-driver-storage-iscsi-direct-6.0.0-37.module+el8.5.0+12162+40884dd2.x86_64
libvirt-daemon-driver-storage-scsi-6.0.0-37.module+el8.5.0+12162+40884dd2.x86_64
libvirt-daemon-driver-storage-6.0.0-37.module+el8.5.0+12162+40884dd2.x86_64
libvirt-client-6.0.0-37.module+el8.5.0+12162+40884dd2.x86_64
libvirt-daemon-kvm-6.0.0-37.module+el8.5.0+12162+40884dd2.x86_64
libvirt-devel-6.0.0-37.module+el8.5.0+12162+40884dd2.x86_64


$ sudo dnf update libvirt

$ rpm -qa | grep libvirt
libvirt-daemon-8.0.0-5.2.module+el8.6.0+15256+3a0914fe.x86_64
libvirt-daemon-driver-storage-gluster-8.0.0-5.2.module+el8.6.0+15256+3a0914fe.x86_64
libvirt-daemon-driver-storage-iscsi-direct-8.0.0-5.2.module+el8.6.0+15256+3a0914fe.x86_64
libvirt-daemon-driver-storage-8.0.0-5.2.module+el8.6.0+15256+3a0914fe.x86_64
libvirt-8.0.0-5.2.module+el8.6.0+15256+3a0914fe.x86_64
libvirt-libs-8.0.0-5.2.module+el8.6.0+15256+3a0914fe.x86_64
libvirt-daemon-driver-nwfilter-8.0.0-5.2.module+el8.6.0+15256+3a0914fe.x86_64
libvirt-daemon-config-network-8.0.0-5.2.module+el8.6.0+15256+3a0914fe.x86_64
libvirt-daemon-driver-storage-iscsi-8.0.0-5.2.module+el8.6.0+15256+3a0914fe.x86_64
libvirt-daemon-driver-storage-rbd-8.0.0-5.2.module+el8.6.0+15256+3a0914fe.x86_64
libvirt-daemon-driver-nodedev-8.0.0-5.2.module+el8.6.0+15256+3a0914fe.x86_64
libvirt-daemon-driver-network-8.0.0-5.2.module+el8.6.0+15256+3a0914fe.x86_64
libvirt-daemon-driver-interface-8.0.0-5.2.module+el8.6.0+15256+3a0914fe.x86_64
libvirt-daemon-config-nwfilter-8.0.0-5.2.module+el8.6.0+15256+3a0914fe.x86_64
libvirt-daemon-driver-storage-scsi-8.0.0-5.2.module+el8.6.0+15256+3a0914fe.x86_64
libvirt-daemon-driver-storage-mpath-8.0.0-5.2.module+el8.6.0+15256+3a0914fe.x86_64
libvirt-devel-8.0.0-5.2.module+el8.6.0+15256+3a0914fe.x86_64
libvirt-daemon-driver-storage-core-8.0.0-5.2.module+el8.6.0+15256+3a0914fe.x86_64
libvirt-daemon-driver-secret-8.0.0-5.2.module+el8.6.0+15256+3a0914fe.x86_64
libvirt-daemon-driver-qemu-8.0.0-5.2.module+el8.6.0+15256+3a0914fe.x86_64
libvirt-daemon-driver-storage-logical-8.0.0-5.2.module+el8.6.0+15256+3a0914fe.x86_64
libvirt-daemon-driver-storage-disk-8.0.0-5.2.module+el8.6.0+15256+3a0914fe.x86_64
libvirt-client-8.0.0-5.2.module+el8.6.0+15256+3a0914fe.x86_64
libvirt-daemon-kvm-8.0.0-5.2.module+el8.6.0+15256+3a0914fe.x86_64

$ crc setup
$ crc start
[...]
DEBU (crc) DBG | time="2022-08-04T03:51:46Z" level=debug msg="Found x86_64 hypervisor with 'hvm' capabilities" 
DEBU (crc) DBG | time="2022-08-04T03:51:46Z" level=debug msg="Found q35 machine type" 
DEBU (crc) DBG | time="2022-08-04T03:51:46Z" level=warning msg="Failed to create the VM: virError(Code=67, Domain=10, Message='unsupported configuration: 'virtiofs' requires shared memory')" 
```

**Comment by praveenkumar** [comment]
Also I don't want it to put under experiment feature but have a option to disable same way we have some of our skip test for preflight. May be an bool option which default is true but if user doesn't want then set it to false.

**Comment by praveenkumar** [comment]
Another issue which I found is in the Linux the mounted file under container is read only, even you put `rw` as part of mount options. In mac same thing mounted as `rw`. I think for that we can open different issue.

```
$ mkdir test
$ touch test/foo
$ podman-remote run -ti --rm  -v $(pwd)/test:/test busybox
/ # ls /test
foo
/ # cd /test/
/test # touch foobar
touch: foobar: Permission denied
```

**Comment by anjannath** [comment]
> Also I don't want it to put under experiment feature but have a option to disable same way we have some of our skip test for preflight. May be an bool option which default is true but if user doesn't want then set it to false.

okay, so we'll keep this config option around even when these issues are fixed? i was thinking we are adding this config option temporarily and only for linux that's why thought of using the enable-experimental flag.

another question is if we enable it by default then users on rhel 8.5 and older are sure to get into this issue?

**Comment by anjannath** [comment]
> DEBU (crc) DBG | time="2022-08-04T03:51:46Z" level=debug msg="Found x86_64 hypervisor with 'hvm' capabilities" 
DEBU (crc) DBG | time="2022-08-04T03:51:46Z" level=debug msg="Found q35 machine type" 
DEBU (crc) DBG | time="2022-08-04T03:51:46Z" level=warning msg="Failed to create the VM: virError(Code=67, Domain=10, Message='unsupported configuration: 'virtiofs' requires shared memory')" 


the error seems related to the `domain.MemoryBacking`, maybe we can detect this in the `virtiofsSupported` using the domain capabilities

**Comment by praveenkumar** [comment]
> > Also I don't want it to put under experiment feature but have a option to disable same way we have some of our skip test for preflight. May be an bool option which default is true but if user doesn't want then set it to false.
> 
> okay, so we'll keep this config option around even when these issues are fixed? i was thinking we are adding this config option temporarily and only for linux that's why thought of using the enable-experimental flag.

I think it is good to have this config around, if a user don't want to share his Home directory with VM then he should have an option.

> another question is if we enable it by default then users on rhel 8.5 and older are sure to get into this issue?

Yes if he face issue then can disable it and again start.

**Comment by cfergeau** [comment]
Has another issue been opened for the underlying issue (machine driver bug on 8.5)? This issue has been changed from "we have an issue on 8.5" to "let's add an option to workaround this issue", and it's now closed.
For further understanding of what's going on, I'd look at `virsh dumpxml crc`  when this fails, and experiment with direct `virsh edit crc && virsh start crc` until the issue becomes clearer.

**Comment by praveenkumar** [comment]
@cfergeau I didn't create the issue but I didn't know this tracker issue is going to be closed, will create and assign to you.
