### ISSUE TITLE
[BUG] crc setup fails on macOS Monterey with permissions error

### ISSUE THREAD

**Issue by BethGriggs** [code-ready/crc#3304]
Apologies if this has been raised before - I did search and find some similar issues that were closed as stale. I figured I'd create one just to capture what I am seeing.

----
### General information

  * OS: macOS Monterey 12.5
  * Hypervisor: default on macOS?
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop

## CRC version
```bash
# Put `crc version` output here
CRC version: 2.6.0+e7251680
OpenShift version: 4.10.22
Podman version: 4.1.0
```
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
```

## CRC config
```bash
# Put `crc config view` output here
- consent-telemetry                     : yes
```

## Host Operating System
```bash
# put the output of `sw_vers` in case of Mac
12.5
```

### Steps to reproduce

  1. Downloaded and installed from https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/crc/2.6.0/crc-macos-installer.pkg
  2. Run the `Red Hat OpenShift Local` from `Applications`.
  3. Select `OpenShift`, add `Pull Secret`.
  4. Running the install wizard or `crc setup` hits the error shown in the screenshot below regarding permission denied errors for the ` /Users/bgriggs/Library/LaunchAgents/com.redhat.crc.daemon.plist` file. 

### Expected

`crc` installs successfully through the setup wizard or I can run `crc setup` in my terminal. 

### Actual

From command-line: 

```console
crc setup
INFO Using bundle path /Users/bgriggs/.crc/cache/crc_podman_vfkit_4.1.0_amd64.crcbundle 
INFO Checking if running as non-root              
INFO Checking if crc-admin-helper executable is cached 
INFO Checking for obsolete admin-helper executable 
INFO Checking if running on a supported CPU architecture 
INFO Checking minimum RAM requirements            
INFO Checking if crc executable symlink exists    
INFO Checking if running emulated on a M1 CPU     
INFO Checking if vfkit is installed               
INFO Checking if CRC bundle is extracted in '$HOME/.crc' 
INFO Checking if /Users/bgriggs/.crc/cache/crc_podman_vfkit_4.1.0_amd64.crcbundle exists 
INFO Checking if old launchd config for tray and/or daemon exists 
INFO Checking if crc daemon plist file is present and loaded 
INFO Adding crc daemon plist file and loading it  
open /Users/bgriggs/Library/LaunchAgents/com.redhat.crc.daemon.plist: permission denied
```

From the setup wizard:
<img width="838" alt="image (2)" src="https://user-images.githubusercontent.com/8297234/184922128-4cba206c-80c6-436b-b7db-e0aaba758ef3.png">

I managed to work around this problem by manually creating the `/Users/bgriggs/Library/LaunchAgents/com.redhat.crc.daemon.plist` and giving it user local permissions... but it seems by default on my mac that the installer cannot write to that directory.

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
`/Users/bgriggs/Library/LaunchAgents/` This location should be writable by `bgriggs` user can you paste the permission ?

```
$ ls -l /Users/prkumar/Library | grep LaunchAgents
drwx------    3 prkumar  staff     96 Aug  9 15:06 LaunchAgents
```

**Comment by BethGriggs** [comment]
```console
$ ls -al /Users/bgriggs/Library | grep 'LaunchAgents'
drwxr-xr-x    4 root     staff    128 16 Aug 13:14 LaunchAgents
```

FWIW, I do not recall having done anything special with this directory before. For `crc`, I just ran the setup wizard on my system 🤔 Perhaps there was something from an earlier or previous setup that caused `LaunchAgents` to be owned by `root`.

I tried the following and it recreates the directory with the correct permissions and everything works fine:

```
$ mv /Users/bgriggs/Library/LaunchAgents/  /Users/bgriggs/Library/LaunchAgents-old/
$ crc setup
$ ls -al /Users/bgriggs/Library | grep 'LaunchAgents'
drwx------    3 bgriggs  staff     96 17 Aug 12:17 LaunchAgents
```

**Comment by praveenkumar** [comment]
@BethGriggs looks like this is something else (some other software stack) which changed the permission. It is not crc specific issue. I am closing it now, please reopen if you think otherwise.
