### ISSUE TITLE
[BUG] New version 2.7 crc.exe daemon API port is listening only on 127.0.0.1:6443

### ISSUE THREAD

**Issue by izderadicka** [code-ready/crc#3316]
### General information

  * OS: Windows
  * Hypervisor: Hyper-V 
  * Did you run `crc setup` before starting it (Yes/No)? YES
  * Running CRC on: Laptop

## CRC version
2.7
  
## CRC status
NA - downgraded to 1.40

## CRC config
NA - Downgraded to 1.40

## Host Operating System

OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19044 N/A Build 19044

### Steps to reproduce

I upgraded from 1.40 to recent 2.7 version and I lost possibility to connect to API from WSL2 ( WSL2 connectivity is also mentioned at #374).  It did worked with 1.40 (after appropriate network and firewall setup), but is not working in latest version. I did some research and I think it's because crc daemon is listening on 127.0.0.1:6433 now, but in older version it was listening on all IP addresses - e.g. 0.0.0.0:6443

  1.  Uninstall completely old version (also delete $HOME/.crc)
  2.  Install new version 2.7
  3. crc setup && crc start
  4. Everything works fine but I cannot use oc from WSL2 (which was working before) - oc login -u kubeadmin  https://api.crc.testing:6443 times out - and I do have correct record in /etc/localhost.
  5. Checking in admin powershell `netstat -ab`:
   TCP    127.0.0.1:6443           DESKTOP-FU0TMB8:0      LISTENING
 [crc.exe]
6. for ingress ports 80 and 443 crc.exe is still listening on all addresses, but 6443 and 2222 is now on localhost only - probably some security improvement? I was trying to search if there is some configuration for this, but did not find anything.

### Expected
crc.exe  to listen on 0.0.0.0:6443 so I can connect to API from other local switches like WSL2 

### Actual
crc.exe is listening on 127.0.0.1 so it cannot be reached from WSL2 and other networks

**Comment by praveenkumar** [comment]
@izderadicka Hi, Yes this we did because of security reasons, if you want to expose `6443` to all the interfaces then try following steps.

- ssh to the VM using https://github.com/code-ready/crc/wiki/Debugging-guide 

```
<crc-vm> $ curl -X POST -d '{"local":"127.0.0.1:6443"}'  gateway.containers.internal/services/forwarder/unexpose
<crc-vm> $ curl -X POST -d '{"local":":6443","remote":"192.168.127.2:6443"}'  gateway.containers.internal/services/forwarder/expose

<=== check if is it added and expose to all the port ==>
<crc-vm> $ curl gateway.containers.internal/services/forwarder/all | jq .
 {
    "local": ":6443",
    "remote": "192.168.127.2:6443",
    "protocol": "tcp"
  }

```

**Comment by gbraad** [comment]
> downgraded to 1.40

Invalid preconditions as we do not support version other than latest.

As said, this is a security constraint, and since you are using WSL2, you might have to use https://github.com/code-ready/crc/issues/374#issuecomment-803580645 to make communication work properly

**Comment by gbraad** [comment]
If this does not work as expected, please still comment on this issue.

**Comment by izderadicka** [comment]
@gbraad concerning #374 -  I indeed read through and applied network configurations.  
My problem here is - it does not work -  I can use port 80, 443 but not 6443 - because 6443 is exposed to 127.0.0.1 IP only on **crc.exe** program in Windows.
My understanding is that on Windows  all communication is going through this program, which then forwards connections to CRC VM.  If crc.exe  is listening on 6443 port only on 127.0.0.1 then traffic from other switches just cannot be forwarded to it.

So temporarily I downgraded back to version 1.4, where it works. 

@praveenkumar Thanks - but this will open API from VM, right? - it has nothing to do with crc.exe, which is running in Windows as Windows process, or does it?

**Comment by praveenkumar** [comment]
> @praveenkumar Thanks - but this will open API from VM, right? - it has nothing to do with crc.exe, which is running in Windows as Windows process, or does it?

@izderadicka it does open it to the host also (in your case window), try it and check.

**Comment by gbraad** [comment]
> My understanding is that on Windows all communication is going through this program, which then forwards connections to CRC VM. If crc.exe is listening on 6443 port only on 127.0.0.1 then traffic from other switches just cannot be forwarded to it.

Therefore you bind on `0.0.0.0:6433` instead of `127.0.0.1` this however allows it to bind to all interfaces, even external.
