### ISSUE TITLE
OpenShift CRC is being unstable at regular intervals in our local machine.

### ISSUE THREAD

**Issue by saaj562** [code-ready/crc#3326]
OpenShift CRC is being unstable at regular intervals in our local machine. It says while doing oc login: "connection refused". 
We have a machine with the following configuration:
1. CPU- 6 cores
2. RAM- 16GB
3. Storage- 100GB

Please provide any vital suggestions for this problem.

**Comment by praveenkumar** [comment]
@saaj562 please use the issue template https://github.com/code-ready/crc/issues/new/choose (bug report) to create the issue which provide use more information around the host and also what fails for CRC.

Closing this since it have lack of info.
