### ISSUE TITLE
Add preflight check for apps-crc.testing DNS resolution

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#335]
I recently helped someone debug their crc install. The issue was a /etc/NetworkManager/dnsmasq.d/openshift.conf file taking precedence over the crc.conf file that crc installs. This was causing *..apps-crc.testing to resolve to 192.168.126.11 instead of the expected 192.168.130.11. We should have a check resolving `foo.apps-crc.testing` and erroring out if it does not resolve to 192.168.130.11. I'm not sure we can automatically fix this though.

**Comment by gbraad** [comment]
We still have to check for the existence of the file during the setup command to clean the state... and this can be a general command to make sure we are in a consistent state.

the deletion of this file might be included for a short time

**Comment by cfergeau** [comment]
This was addressed in https://github.com/code-ready/crc/commit/6673ade except on macos. See also https://github.com/code-ready/crc/issues/1013
