### ISSUE TITLE
Switching to non-Quay registry such as Artifactory Docker registry

### ISSUE THREAD

**Issue by jauyzed** [code-ready/crc#3359]
Hello! We are using artifactory as image registry but we do not have access to GUI dashboard yet due to .testing TLD issue. Is there a way to configure crc to connect to artifactory registry as default?  

Thanks!

**Comment by praveenkumar** [comment]
https://docs.openshift.com/container-platform/4.11/openshift_images/image-configuration.html#images-configuration-file_image-configuration have all the details and it is not CRC specific query but openshift one.

**Comment by gbraad** [comment]
Closing as this is not CRC-specific
