### ISSUE TITLE
Expose the self-signed to the user

### ISSUE THREAD

**Issue by ctron** [code-ready/crc#3391]
Currently when using CRC, all TLS routes will have the problem that a browser warning pops up and the user has to accept an exception.

This is ok, and due to the nature of self-signed certificates. It needs to be done for every hostname (not CRC host).

However, in some cases it gets really tricky to find out all the URLs/hostnames used by an application. Especially when web-services come into play, the user needs to browse through the requests the browser does, replace `wss` with `https`, open this, accept the exception and ignore the error.

This is all pretty unpractical.

What would help IMHO would be to give the user the ability to import the certificate as a trust anchor. For this however, it would be necessary to: a) let the user know where to find those certificates, and b) write them to the file system in a format the browser can import.

I think that a) could be solved by a command like:

```
$ crc ca
Location of self-signed certificate:
   /home/user/.crc/ca/ca.pem
```

Having this would also allow for other tooling to make use of this (e.g. `update-ca-certificates` or `certuil`), without actually providing any deep integration from `crc`, which might be more complicated.

**Comment by gbraad** [comment]
I would help to allow custom certificates to be included into the environment, or otherwise trust the certificates that are given to the user. The first issue is a dup of #3388. The later are steps that you need to perform based on the browser/system.
