### ISSUE TITLE
Generate rendered pdf from the docs source

### ISSUE THREAD

**Issue by anjannath** [code-ready/crc#361]

**Comment by gbraad** [comment]
I hjave been adding the `asciidoctor-pdf` package into the image, but the Ruby version is too old. Use Fedora instead, WDYT?

**Comment by anjannath** [comment]
Fine by me, lets use the fedora image! I guess @robin-owen and @praveenkumar will also agree!

**Comment by praveenkumar** [comment]
@gbraad which version of ruby it need can we start using https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/ubi8/ruby-25 one?

**Comment by praveenkumar** [comment]
@anjannath @gbraad using below I can easily able to build the image.

```
FROM registry.redhat.io/ubi8/ruby-25
MAINTAINER CodeReady Containers<devtools-cdk@redhat.com>

RUN gem install asciidoctor-pdf --pre

VOLUME /docs
WORKDIR /docs

ENTRYPOINT [ "asciidoctor-pdf" ]
```

**Comment by gbraad** [comment]
right, so you use an alternative image... the UBI.
let's create a dockerfiel for this ...

**Comment by anjannath** [comment]
This is what the generated [doc.pdf](https://github.com/code-ready/crc/files/3533553/doc.pdf) looks like.

/cc @code-ready/crc-devel
