### ISSUE TITLE
Undefined step in integration test

### ISSUE THREAD

**Issue by anjannath** [code-ready/crc#373]
```gherkin
When with up to "10" retries with wait period of "1m" command "crc status" output should not contain "Stopped"
```
The above step is reported as undefined, relevant console logs: https://ci.centos.org/job/codeready-crc-pr/545/console

**Comment by jsliacan** [comment]
@anjannath yes I know. It's because it depends on code-ready/clicumber#8. I've referenced it in the first PR that used it.

**Comment by anjannath** [comment]
@jsliacan Sorry, i missed that PR, will close this, since https://github.com/code-ready/clicumber/pull/8 is merged now!
