### ISSUE TITLE
'crc setup' output with warnings and errors are confusing without saying setup was successful or failed

### ISSUE THREAD

**Issue by dgolovin** [code-ready/crc#379]
I was confused after I ran first time:
``` 
crc setup --vm-driver=hyperv
```

and then saw this output

```
crc setup --vm-driver=hyperv
level=info msg="Caching oc binary"
level=error msg="Error occurred: oc binary is not cached."
level=info msg="Unpacking bundle from the CRC binary"
level=warning msg="CRC bundle is not embedded in the binary, see 'crc help' for more details."
level=info msg="Check Windows 10 release"
level=info msg="Hyper-V installed"
level=info msg="Is user a member of the Hyper-V Administrators group"
level=info msg="Does the Hyper-V virtual switch exist"
```

First I saw the error message, but did't see any statement about how setup went. Was it successful even with error of it failed because of error? It turned out error was not really a problem, but warning was, but I had no clue. I called 'crc help' and got this output.

```
$ crc help
Deploy local instance of an OpenShift 4.x cluster for development purpose

Usage:
  crc [flags]
  crc [command]

Available Commands:
  config      Modifies crc configuration properties.
  delete      Delete cluster
  help        Help about any command
  ip          Get IP of the instance
  oc-env      Sets the path of the 'oc' binary.
  setup       setup hypervisor
  start       start cluster
  status      Display status of the cluster
  stop        Stop cluster
  version     Get CodeReady Container version.

Flags:
  -f, --force              Forcefully perform an action
  -h, --help               help for crc
      --log-level string   log level (e.g. "debug | info | warn | error") (default "info")

Use "crc [command] --help" for more information about a command.
```

It had nothing about my problem 'CRC bundle is not embedded in the binary', so I kept digging and used `crc setup --log-level debug` and got this output

```
crc setup --vm-driver=hyperv --log-level debug
level=info msg="Caching oc binary"
level=debug msg="oc binary already cached"
level=info msg="Unpacking bundle from the CRC binary"
level=debug msg="FindFirstFile C:\\Users\\dgolo\\.crc\\crc_hyperv_4.1.6.crcbundle: The system cannot find the file specified."
level=warning msg="CRC bundle is not embedded in the binary, see 'crc help' for more details."
level=info msg="Check Windows 10 release"
level=info msg="Hyper-V installed"
level=info msg="Is user a member of the Hyper-V Administrators group"
level=debug msg="Always add user"
level=info msg="Does the Hyper-V virtual switch exist"
```

So I realized I would fix it by copying crcbundle file to `~/.crc/` folder and it worked, because warning was gone and surprisingly oc binary error was fixed as well. 

```
$ crc setup --vm-driver=hyperv --log-level debug
level=info msg="Caching oc binary"
level=debug msg="oc binary already cached"
level=info msg="Unpacking bundle from the CRC binary"
level=info msg="Check Windows 10 release"
level=info msg="Hyper-V installed"
level=info msg="Is user a member of the Hyper-V Administrators group"
level=debug msg="Always add user"
level=info msg="Does the Hyper-V virtual switch exist"
```

I know now I should use `--bundle' with start command and first error about oc was not really a error, just check before caching oc in ~/.crc folder.
Do those questions without '?' mean everything is fine or I have to do something? I decided to try it anyway and it worked as expected after I provided Image pull secret.

IHMO it is good, because it works and lets me to use odo with OpenShift 4, but better output would save me a little time for the first try.

**Comment by gbraad** [comment]
This is he reason why we only did an incremental release. this feature is not completely done, although on release we will embed the bundle so this will not cause issues

**Comment by anjannath** [comment]
@gbraad Yes, that is right, once we have the bundle embedded, this `WARN` will not appear. Also we need to put some details about it on `crc -h` or modify the message.
