### ISSUE TITLE
Provide better reporting related to used bundle and expired certificates

### ISSUE THREAD

**Issue by aldettinger** [code-ready/crc#382]
I hope this is the right place to report that crc_libvirt_4.1.6.crcbundle certificates have expired, if not please point me.

Find more details below:
**[user]$ crc setup**
INFO Caching oc binary                            
INFO Setting up virtualization                    
INFO Setting up KVM                               
INFO Installing libvirt service and dependencies  
INFO Adding user to libvirt group                 
INFO Enabling libvirt                             
INFO Starting libvirt service                     
INFO Installing crc-driver-libvirt                
[sudo] password for user: 
[sudo] password for user: 
INFO Setting up libvirt 'crc' network             
INFO Starting libvirt 'crc' network               
INFO Writing Network Manager config for crc       
INFO Writing dnsmasq config for crc               
INFO Unpacking bundle from the CRC binary         
WARN CRC bundle is not embedded in the binary, see 'crc help' for more details. 
**[user]$ crc start -b crc_libvirt_4.1.6.crcbundle**
INFO Checking if oc binary is cached              
INFO Checking if Virtualization is enabled        
INFO Checking if KVM is enabled                   
INFO Checking if libvirt is installed             
INFO Checking if user is part of libvirt group    
INFO Checking if libvirt is enabled               
INFO Checking if libvirt daemon is running        
INFO Checking if crc-driver-libvirt is installed  
INFO Checking if libvirt 'crc' network is available 
INFO Checking if libvirt 'crc' network is active  
INFO Checking if /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf exists 
INFO Checking if /etc/NetworkManager/dnsmasq.d/crc.conf exists 
INFO Checking if CRC bundle is cached in '$HOME/.crc' 
WARN stat /home/user/.crc/crc_libvirt_4.1.6.crcbundle: no such file or directory 
? Copy it from ****
? Image pull secret ****
INFO Extracting the crc_libvirt_4.1.6.crcbundle Bundle tarball ... 
INFO Starting stopped VM ...                      
INFO Verifying validity of the cluster certificates ... 
**ERRO Error occurred: Temporary Error: Certs have expired, they were valid till: 28 Jul 19 09:08 +0000
Temporary Error: Certs have expired, they were valid till: 28 Jul 19 09:08 +0000
Temporary Error: Certs have expired, they were valid till: 28 Jul 19 09:08 +0000
Temporary Error: Certs have expired, they were valid till: 28 Jul 19 09:08 +0000**

**Comment by gbraad** [comment]
@anjannath @tsedmik can you confirm? however we did check this as part of the incremental Hyper-V release and we had 15 days remaining.

**Comment by praveenkumar** [comment]
@aldettinger I am sure the cert is not expired but since you are running an stopped cluster which might using an old version of bundle as your logs says `INFO Starting stopped VM ...` Can you try below.

```
$ crc delete
$ crc start  -b crc_libvirt_4.1.6.crcbundle
```

**Comment by gbraad** [comment]
I have changed the title, as one of the issues here is: `-b` was provided to start a NEW instance, while an existing was present.

I would suggest to tell the user `A bundle is provided, but an existing cluster with version [...] exists`.

Or, on start we should display more detailed information from the metadata to show which cluster version and bundle is used, such as version, build date, etc.

And when expiry is shown, we might also consider showing the bundle creation date again (or some other identifying information)... or refer to the details that were previously shown (as suggested)

**Comment by aldettinger** [comment]
@gbraad , deleting and starting again is indeed working. Many thanks for that tip :+1: 
And  I agree, more information could be helpful, especially something indicating that 2 distinct bundles are at play. Or perharps, -b could override when a new bundle is provided.

**Comment by cfergeau** [comment]
There is now a warning when 2 distinct bundles are being used:
`WARN Bundle 'crc_hyperkit_4.1.14.crcbundle' was requested, but loaded VM is using 'crc_hyperkit_4.1.11.crcbundle' `
