### ISSUE TITLE
Add crc base dir as ~/.crc

### ISSUE THREAD

**Issue by anjannath** [code-ready/crc#40]

**Comment by gbraad** [comment]
In #12 I have already worked on this... although for testing purposes I forced the homedir in `/tmp` by the basedir.

**Comment by gbraad** [comment]
@anjannath make sure you use the right pattern for the description.

**Comment by cfergeau** [comment]
Did you consider using https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html?
logs would go in $XDG_CACHE_HOME/crc/... (usually ~/.cache/crc) and config in $XDG_CONFIG_HOME/crc/... (usually ~/.config/crc)

**Comment by anjannath** [comment]
@cfergeau I haven't looked into this, conforming with the specs is a nice thing, but i guess this will change in case of windows and macOS, (do they also have `$XDG_CONFIG_HOME` and `$XDG_CACHE_HOME` directories?)

**Comment by cfergeau** [comment]
> @cfergeau I haven't looked into this, conforming with the specs is a nice thing, but i guess this will change in case of windows and macOS, (do they also have `$XDG_CONFIG_HOME` and `$XDG_CACHE_HOME` directories?)

 $HOME/.crc is not typical there either ;) I'm not sure what glib is doing on these platforms

**Comment by anjannath** [comment]
> $HOME/.crc is not typical there either ;)

Right for windows, but macOS i am sure others also use this location..

**Comment by cfergeau** [comment]
It seems even on macOS, .crc is not the recommended way https://stackoverflow.com/questions/3373948/equivalents-of-xdg-config-home-and-xdg-data-home-on-mac-os-x#5084892
