### ISSUE TITLE
Add sha256sum for make cross and also for release makefile target.

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#400]
Right now, we are not creating the sha256sum for the cross builds and also for the release target in the Makefile, which we mostly require.

**Comment by anjannath** [comment]
@praveenkumar So we want sha265sum for the `crc` binaries (with the bundle embedded), and also the sha256sum of the resulting tar.gz/zip archives, right?

**Comment by praveenkumar** [comment]
@anjannath we want the sha256sum only for the resulting tar.gz/zip archives that what we are going to publish to internal server.
