### ISSUE TITLE
Adding user to hyper-v admin group always fails

### ISSUE THREAD

**Issue by opuk** [code-ready/crc#421]
When running crc setup I always get this, even tho I have added my self to the group.

I'm running crc in a administrator powershell. When I run it as my self it's unable to get any groups.

Not sure if this could be related to the fact that the system language is Swedish so the group is named a bit differently, but having taken a quick glance it looks like crc should be fetching the built in group name and not hard coded to the English name.

```
INFO Caching oc binary
DEBU oc binary already cached
INFO Unpacking bundle from the CRC binary
DEBU FindFirstFile C:\Users\user\.crc\crc_hyperv_4.1.6.crcbundle: The system cannot find the file specified.
WARN CRC bundle is not embedded in the binary, see 'crc help' for more details.
INFO Check Windows 10 release
INFO Hyper-V installed
INFO Is user a member of the Hyper-V Administrators group
DEBU Always add user
ERRO Error occurred: Error adding user to group
FATA Error adding user to group

```

**Comment by gbraad** [comment]
@cfergeau WDYT?

**Comment by cfergeau** [comment]
Can it be the issue when you need to unlog/relog? This looks like an older binary though? `crc_hyperv_4.1.6.crcbundle` is mentioned in the log.

**Comment by opuk** [comment]
I used the latest built tag at the time. I now see that 0.90 has binaries available that I can test.

FYI I had restarted the computer multiple times when I tried on 0.89. I have also installed CDK successfully which does a similar check.

**Comment by opuk** [comment]
It works with 0.90.

**Comment by gbraad** [comment]
we used elevated privileges to run powershell, but for some reason this
didn't work as expected.
we passed information between retrieval to an admin call, but we have since
moved to using `net` in an elevated session and reading the username from
Go directly.
Glad to hear this works now.
