### ISSUE TITLE
Document how upgrades are supposed to be done

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#422]
User is already using crc 4.1.6
User downloads the all-in-one crc 4.1.9 binary
At the moment, the needed steps are:
- `crc setup` to unpack the new bundle (and potentially adjust configuration)
- `crc delete`, otherwise crc will keep using the 4.1.6 image
- `crc start`
but this is not explicited anywhere. In particular, `crc stop` followed by `crc start` with the new binary will not be enough to start using the new version.

**Comment by robin-owen** [comment]
Maybe I'm misunderstanding, but at the moment, is the `crc setup` step required for binaries that have been downloaded from GitHub releases? Those don't have the bundle embedded, and I don't want to misinform anyone who uses the GitHub-released assets.

Is it generally a good idea to go ahead and run `crc setup` (followed by `crc delete && crc start`) after upgrading the binary in any case (whether we have an embedded bundle or not)?

**Comment by cfergeau** [comment]
> Is it generally a good idea to go ahead and run `crc setup` (followed by `crc delete && crc start`) after upgrading the binary in any case (whether we have an embedded bundle or not)?

At the moment, if you want to keep using a preexisting VM after upgrading the `crc` binary, you should not run `crc setup`. If you want to switch to a new bundle, you should run `crc delete` and `crc setup`. If you used `crc` before beta, you may not be able to keep using a preexisting VM after upgrading the `crc` binary.

**Comment by cfergeau** [comment]
See also https://github.com/code-ready/crc/issues/484

**Comment by ppalaga** [comment]
The official steps to upgrade would be highly appreciated. I'd expect to find them somewhere under https://access.redhat.com/documentation/en-us/red_hat_codeready_containers/1.0/ or even better in the README here on GitHub.

**Comment by gbraad** [comment]
The wording 'upgrade' might cause confusing: We do not upgrade the OpenShift cluster, but rather 'replace' the VM with a new OpenShift cluster. Similarly for the word 'update'. Perhaps 'Instruction on how to use a new cluster' might avoid this.

Note: this 'update'/'scenario' needs to be detailed in a new tasks for automation.

**Comment by praveenkumar** [comment]
Fix by #956
