### ISSUE TITLE
VirtualBox on Windows fails with host-only interface not found error

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#423]
While not supported, we should try to make this at least work or at least describe some of the basic errors somewhere, ... like in this issue.

![image](https://user-images.githubusercontent.com/1894/63242168-0b747380-c289-11e9-9f31-f8b4daa73e0f.png)

**Comment by gbraad** [comment]
```
Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter' (VERR_INTNET_FLT_IF_NOT_FOUND).
Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND).

Result Code: | E_FAIL (0x80004005)
-- | --
Component: | ConsoleWrap
Interface: | IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

```

**Comment by gbraad** [comment]
![image](https://user-images.githubusercontent.com/1894/63320301-f282c580-c34f-11e9-8e1f-9dbab8ccf6a5.png)

**Comment by gbraad** [comment]
After Uninstall, reinstall and reconfigure the network ... I am able to finally recreate the VM. However, I still needed to modify the machine to use the correct Host-only network adapter

**Comment by gbraad** [comment]
I found a way around this... but it needs admin rights (several times). Looking into automating this.

**Comment by anjannath** [comment]
@gbraad This is not needed anymore as VirtualBox is not supported now!

**Comment by gbraad** [comment]
Right... closing
