### ISSUE TITLE
crc.exe status does not work on running instance

### ISSUE THREAD

**Issue by tsedmik** [code-ready/crc#434]
**Environment**
* CRC version - 0.90.0-alpha-4.1.9+b2559b5
* Windows 10 Pro 1903, Hyper-V

If I start CRC and then try to determine it's state with `crc.exe status`, I get the following error:

```
PS C:\Users\Tomáš Sedmík\Downloads\crc-0.90.0-alpha-windows-amd64> .\crc.exe status --log-level=debug
DEBU Unexpected operator status for authentication: Upgradeable
DEBU Unexpected operator status for console: Upgradeable
DEBU Unexpected operator status for kube-apiserver: Upgradeable
DEBU Unexpected operator status for kube-controller-manager: Upgradeable
DEBU Unexpected operator status for kube-scheduler: Upgradeable
DEBU Unexpected operator status for openshift-apiserver: Upgradeable
DEBU Unexpected operator status for openshift-controller-manager: Upgradeable
DEBU Unexpected operator status for service-ca: Upgradeable
DEBU Unexpected operator status for service-catalog-apiserver: Upgradeable
DEBU Unexpected operator status for service-catalog-controller-manager: Upgradeable
ERRO Error occurred: strconv.ParseInt: parsing "df:": invalid syntax
```

**Comment by gbraad** [comment]
This fails somewhere in:

https://github.com/code-ready/crc/blob/f3edeb8afb9732c88a716ab6e6092fde04919074/pkg/crc/cluster/cluster.go#L43-L63

**Comment by gbraad** [comment]
https://github.com/code-ready/crc/blob/f3edeb8afb9732c88a716ab6e6092fde04919074/pkg/crc/cluster/cluster.go#L54

https://github.com/code-ready/crc/blob/f3edeb8afb9732c88a716ab6e6092fde04919074/pkg/crc/cluster/cluster.go#L58

**Comment by anjannath** [comment]
Hmm, there's a difference in the block device's name, in case of windows the device mounted in `/sysroot` is `/dev/sda3` but in case of linux it is `/dev/vda3`. I had hard-coded the device name to be `/dev/vda3` :(

**Comment by cfergeau** [comment]
It seems you are using the device path as an arg to `df`, I think you can use the mountpoint instead, which should be the same on all platforms.
