### ISSUE TITLE
crc.exe oc-env does not work well with special characters in the path

### ISSUE THREAD

**Issue by tsedmik** [code-ready/crc#442]
**Environment**
* CRC version - 0.90.0-alpha-4.1.9+b2559b5
* Windows 10 Pro 1903, Hyper-V
* Home Dir: C:\Users\Tomáš Sedmík\

If I use `crc.exe oc-env` command to put oc binary on PATH, it does not work in case I have some special characters in the path - see:

```
PS C:\devel\crc> crc.exe oc-env
$Env:PATH = "C:\Users\Tomáš Sedmík\.crc\bin;$Env:PATH"
# Run this command to configure your shell:
# & crc oc-env | Invoke-Expression

PS C:\devel\crc> crc.exe oc-env | Invoke-Expression

PS C:\devel\crc> Get-ChildItem Env:PAth

Name                           Value
----                           -----
Path                           C:\Users\Tom├í┼í Sedm├¡k\.crc\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\Program Files\Java\jdk1.8....
```

**Comment by anjannath** [comment]
If we enclose `C:\Users\Tomáš Sedmík\.crc\bin` in a quote and use the following exp, it should work fine.
```
$Env:PATH = "C:\Users\Tomáš Sedmík\.crc\bin";$Env:PATH
```

**Comment by anjannath** [comment]
Root cause is Posh, by default doesn't use UTF-8 encoding. The following helped..
```posh
[Console]::OutputEncoding = [Text.UTF8Encoding]::UTF8; & crc oc-env | Invoke-Expression
```

**Comment by gbraad** [comment]
very generic Windows issue that belongs in troubleshooting. but this would in general not just affect us, but many commands as the whole PowerShell session needs to be using `UTF8Encoding`

**Comment by robin-owen** [comment]
@gbraad Is there a way to use UTF-8 across the entire PowerShell session that we can document, or should we simply document the command @anjannath wrote above ("`[Console]::OutputEncoding = [Text.UTF8Encoding]::UTF8; & crc oc-env | Invoke-Expression`")?

I looked into this some myself, but couldn't find a consistent, clear answer. :\

**Comment by robin-owen** [comment]
This has been documented as a known issue for a very long time now. :)
