### ISSUE TITLE
A few simple questions

### ISSUE THREAD

**Issue by magick93** [code-ready/crc#448]
Hello

At my company, my development team uses `oc cluster up` as a foundational tool. We us this every day. 

We were disappointed to see `oc cluster up` being discontinued, and the `openshift-installer` project having a high barrier to entry, with requirements to install go, terraform and the need to run multiple commands to get Libvirt platform working.

Is the plan to have `crc` replace `oc cluster up`? 
Is it going to be as easy as `oc cluster up`, in particular, will there be just a single command to run, and we wont need to install anything other than `oc`?

Thanks

**Comment by praveenkumar** [comment]
> Is the plan to have crc replace oc cluster up?

`crc` is not a replacement of `oc cluster up` but it is a similar tool as `minishift`, so if you want to do development work for Openshift-4.x then CRC is replacement of `minishift` (which is only used for 3.x side).

> Is it going to be as easy as oc cluster up, in particular, will there be just a single command to run, and we wont need to install anything other than oc?

You need to have `crc` binary and that's all.

**Comment by magick93** [comment]
Thanks @praveenkumar

**Comment by gbraad** [comment]
If questions remain, please re-open this issue.
