### ISSUE TITLE
[fcos] questions about the interface between host and container runtime

### ISSUE THREAD

**Issue by dustymabe** [code-ready/crc#453]
In https://github.com/coreos/fedora-coreos-tracker/issues/231 we had a discussion about the use of varlink on Fedora CoreOS as a remote interface for container management. We'd like to gain a better understanding of how the code-ready-containers project is planning to set up and use this so that we know about this in the future when we make policy decisions about the host. Some questions that come to mind:

- Will you be using ssh as an authentication and transport mechanism?
- If using SSH will you be providing an ssh key via ignition?
- Will you be using the `podman remote` command at all?

In general we're trying to discourage the use of SSH on FCOS, but understand that some tools have been built to assume it exists and are trying to keep track of places we know it is being used for bridging functionality.

cc @praveenkumar @lucab

**Comment by bgilbert** [comment]
Also, if you'll be using SSH and specifying your own key:
- Will you use the `command` keyword in `authorized_keys` so the SSH key can only run varlink?
- Will you create a separate FCOS user that doesn't have sudo access?

**Comment by gbraad** [comment]
Podman support is being worked on. This discussion is mostly happening on #961
