### ISSUE TITLE
Add documentation for VirtualBox

### ISSUE THREAD

**Issue by robin-owen** [code-ready/crc#458]
We need to remove the general recommendation of using `crc start -b _path_to_bundle_` for native hypervisors (libvirt, hyperkit, and Hyper-V), as those will have the bundle embedded in the binary. We need to keep these instructions for VirtualBox, however.

Also, VirtualBox requires `crc start --vm-driver virtualbox`, unlike native hypervisors.

Are there any other considerations for documentation related to VirtualBox?

**Comment by praveenkumar** [comment]
Fixed
