### ISSUE TITLE
Add pre-flight check for NetworkManager

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#459]
After libvirt we check for config files for NetworkManager

https://github.com/code-ready/crc/blob/f185afc39253747c07213ce213fa72b102a5edb6/pkg/crc/preflight/preflight_linux.go#L60

but this assumes that NetworkManager is used. However, it could be people use `network` (rc-scripts) or `systemd-networkd` or try to get this somehow on a headless system. to prevent this now, we should add a test similar to `checkLibvirtEnabled` but with a fix that asks for manual changes (like done with the Windows update) as automagic updates might result in a disconnected state.

**Comment by anjannath** [comment]
Fixed in #461
