### ISSUE TITLE
Deal with 'Upgradeable' status in pkg/crc/oc/clusteroperator.go

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#467]
When running with debug log enabled, I got:
time="2019-08-23T17:37:56+01:00" level=debug msg="Unexpected operator status for console: Upgradeable"

**Comment by praveenkumar** [comment]
@cfergeau we actually ignored that state since we are only take action on `Available`, `Progressing` and `Degraded` . `Upgradeable` is something we can't use it since we can't update in place.

**Comment by cfergeau** [comment]
I'm not suggesting much more than adding an empty `case "Upgradeable"` in order to silence this warning if what we want is to ignore it.

**Comment by cfergeau** [comment]
This was fixed by the commits referenced above.
