### ISSUE TITLE
Setup golang env for the build_docs job

### ISSUE THREAD

**Issue by anjannath** [code-ready/crc#473]
While running the build_docs job in circle ci for #451 it complains about syntax errors in makefile
```
#!/bin/bash -eo pipefail
make build_docs

Makefile:130: *** target pattern contains no '%'.  Stop.
Exited with code 2
```
This is because there's no golang env setup in that machine and `go env` commands are not working.

**Comment by praveenkumar** [comment]
This is fixed by #451
