### ISSUE TITLE
Add basic pre-flight checks and setup (Windows / Virtualbox)

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#48]
Depends on #9

Implement pre-flight checks and setup related to use of Virtualbox on Windows

  * [ ] Check if Virtualbox installed
  * [ ] Check if configured
  * ...

**Comment by cfergeau** [comment]
@gbraad Do we still want this? Or is it now only something we will document, but not automate?

**Comment by anjannath** [comment]
We talked about dropping virtual box support altogether, Closing this!
