### ISSUE TITLE
bundle seems to contain extra /home/core/.ssh/authorized_keys

### ISSUE THREAD

**Issue by AkihiroSuda** [code-ready/crc#486]
The 1.0.0 beta3 bundle seems to contain unexpected `/home/core/.ssh/authorized_keys` on the node.

**Comment by gbraad** [comment]
@praveenkumar can you have a look at this?

**Comment by gbraad** [comment]
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCbZlR0TkP3WK1Qso6H1ouaYop3a9yMBkqwr9BFq2N0QOFPcrq86Mrs9ij769WTmrTT/tTpCVTC9pdBRqUHbEiL/j9DlVtc1eBQB7Fec3/ekVVEv1HUsWM5vz8K6b8hqQIfxY/lbPtDn5x9xzMsd7s0WcNLDnJiagwU/OlSUZE4Oiu1nKSjuU7phzGMGITj8ZuAIWwaxuyOOjnjXbWFiuJiI+UY2abo4ahQJgzv1+A+BYcuITydwhcAnKrjh2hLi714uMQ0hWEtqJnYMdjM7W+BsJafGpe+ivGewGu7A5tloECv25iKFmBU/cqL9CaH+EAtVF9E64lnhqxFjjHvddVJ prkumar@dhcp-10-171-208.osas.lab.eng.rdu2.redhat.com
```

This is the key used to create the image AND to allow our tooling to get access to the VM instance. However, this key to be replaced automatically with #145 (under development).

What other information do you see?

**Comment by AkihiroSuda** [comment]
The key name (`prkumar@...redhat.com`) was confusing, but no problem if the key is actually needed currently and planned to be replaced in #145

**Comment by gbraad** [comment]
I have to admit that the key description `prkumar` is unfortunate, but that is because the CI image generation runs as a user job. Will look into this anyway as it might 'scare' (or confuse) people

**Comment by praveenkumar** [comment]
@gbraad I will have a look how it is happened since we generate the ssh key for every new bundle creation.

**Comment by gbraad** [comment]
It is the key description that gets included.

**Comment by gbraad** [comment]
@praveenkumar use `ssh-keygen -C noname` when generating ?

**Comment by praveenkumar** [comment]
yes, it is unfortunate to have whole public key there.  I will check how to avoid it.

**Comment by gbraad** [comment]
https://github.com/code-ready/snc/blob/56cf67524faa3bbd629ecc9dbbcdab48f7b8de47/snc.sh#L126

```diff
- ssh-keygen -N "" -f id_rsa_crc
+ ssh-keygen -N "" -f id_rsa_crc -C noname
```

**Comment by gbraad** [comment]
Fixed in https://github.com/code-ready/snc/pull/87
