### ISSUE TITLE
`crc delete` should delete /etc/resolver/testing

### ISSUE THREAD

**Issue by AkihiroSuda** [code-ready/crc#487]
On macOS, `/etc/resolver/testing` remains after `crc testing`. It would be great if `crc delete` can remove this file as well as the cluster.

**Comment by cfergeau** [comment]
If we remove after `crc delete`, this means you can't do `crc start`, you will need to run `crc setup` again, which will ask for sudo to recreate it, and then you can do `crc start`. We could make sure /etc/resolver/testing is empty though, similarly to what is requested in issue #296. And an `crc unsetup` command to undo everything which `crc setup` did would be useful too.

**Comment by gbraad** [comment]
We have a generic cleanup task here: #407 This needs some discussion, as it mostly macOS and Linux now that creates 'unwanted' artifacts when CRC is not used.

**Comment by cfergeau** [comment]
And another issue related to cleaning up what `setup` does: https://github.com/code-ready/crc/issues/507

**Comment by gbraad** [comment]
Duplicate of #651
