### ISSUE TITLE
Document the availability of developer user

### ISSUE THREAD

**Issue by anjannath** [code-ready/crc#492]
We now have a `developer` user with password `developer`, this needs to be documented, and maybe the messages printed after start should refer to this instead of using the `kubeadmin` user.

ref: https://github.com/code-ready/crc/issues/395#issuecomment-525689811

**Comment by anjannath** [comment]
> Is the developer user the one that we should generally recommend logging in as after running crc start? 
Yes, but this needs to be also changed in the o/p of `crc start` currently we are printing the `kubeadmin` user credentials, and the `oc login` command also uses the `kubeadmin` user.

**Comment by anjannath** [comment]
the `kubeadmin` user is the cluster admin, kind of the root user for the cluster, it has access to all the namespace, the `developer` user is a bit restricted by default that it does not have access to the existing namespaces, it'll have access to namespaces that are created by himself, but it can also perform admin level actions by impersonating as a cluster admin, by passing in `--as=system:admin` to `oc` commands.

**Comment by cfergeau** [comment]
> What are the primary differences between the `developer` user and the `kubeadmin` user? Why would one be used instead of the other?
> 
> I suppose one of the real questions here is whether or not we should be documenting the `kubeadmin` user at all, and if we do document `kubeadmin`, in what contexts does that user apply?

Is this issue fixed by the commits above? Or do you also want to add the documentation the existence of this user, and when it should be used over admin?

**Comment by cfergeau** [comment]
I have the same interrogations as kevin's regarding developer VS kubeadmin.
When should one be using `kubeadmin`?
When should one be using `developer`?
If I want to create/install an application on my crc cluster, can I do it as `developer` or do I need to be `kubeadmin`?

**Comment by cfergeau** [comment]
From Praveen:
>If a user want to administrate the cluster he/she should use kubeadmin user (like creating new users, setting the roles ..etc, installing some operators ..etc.) Just creating or deploying an application, developer user would be good enough.
