### ISSUE TITLE
Documentation is not intuitive for newcomer

### ISSUE THREAD

**Issue by geerlingguy** [code-ready/crc#493]
I just found out about this project today, and wanted to try it out. Reading through the project README, there was not much helpful information besides "here's how to compile the documentation", and a link to an incomplete guide for developing the CRC containers.

I asked around, and it seems the project documentation is available here: https://code-ready.github.io/crc/

This is exactly what I was looking for, and I would rather not have to compile the documentation to view it locally if I'm just going to check out the project, see the requirements, etc.

Is there any chance that link could be placed in the repository's Website link in the header on GitHub?

<img width="876" alt="Screen Shot 2019-08-28 at 8 18 13 AM" src="https://user-images.githubusercontent.com/481677/63859201-7ea67580-c96c-11e9-9d2f-2f1c22a8e587.png">

Also maybe a link near the top of the README?

**Comment by gbraad** [comment]
The documentation is also included in the archive.
