### ISSUE TITLE
Display openshift version when starting VM

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#498]
Since we now know which bundle a VM is using, when starting up a VM, we can display which openshift version it's running. This should help clear up some potential confusion when the VM already exists.

Ideally, the openshift version a bundle was built from would be part of the bundle metadata. It's not there yet, so we extract it from the bundle name.

**Comment by gbraad** [comment]
> would be part of the bundle metadata

this is the only right place to get this from.
We can not rely on extracting this from the bundle name, as this can be modified by the user when used with `-b` (like eg. with Virtualbox).
