### ISSUE TITLE
If 2 network drivers are enabled and active, the crc setup fails on MacOS

### ISSUE THREAD

**Issue by porcelli** [code-ready/crc#505]
Version: v1.0.0-beta.3-4.1.11

~/D/crc ❯❯❯ ./crc setup
crc - Local OpenShift 4.x cluster
INFO Caching oc binary
ERRO Error occured: Download failed: [Head https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/macosx/oc.tar.gz: dial tcp: lookup mirror.openshift.com on 192.168.130.100:53: read udp 192.168.130.1:61115->192.168.130.100:53: i/o timeout]

**Comment by gbraad** [comment]
It seems you can not download the `oc` client from the mirror.openshift.com servers. It looks like it fails to perform the DNS lookup. Not sure what you mean with 2 network drivers... Rather seems a conflicting DNS setup.

**Comment by gbraad** [comment]
@porcelli any update?

> 192.168.130.100:53: i/o timeout

please verify your network settings. DNS is failing.

**Comment by cfergeau** [comment]
No feedback, closing. Please reopen or open a new issue with more details.
