### ISSUE TITLE
Change the install type for crc so it will list differently to telemeter.

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#508]
We need to change the `install_type` for the crc cluster when it try to register with telemeter. We first have to find out where is that details and how to changes those without affecting the cluster.

**Comment by gbraad** [comment]
@smarterclayton you had an idea about using this to distinguish our installs from other types of clusters?

**Comment by smarterclayton** [comment]
@crawford

**Comment by crawford** [comment]
You can use the `OPENSHIFT_INSTALL_INVOKER` environment variable ([used here](https://github.com/openshift/installer/blob/c7a87b5a60201a22f7b061bb18ed8133460de4b6/pkg/asset/cluster/tfvars.go#L339)) to record that information.

**Comment by gbraad** [comment]
Is there a way to modify this after installation?

**Comment by praveenkumar** [comment]
@crawford So we just need to take care of the invoker and then it is easy for filter from telemeter side? This `OPENSHIFT_INSTALL_INVOKER` we can even set as part of our disk creation to `codeReadyContainer`.

Currently we have below as part of this config map.

```
$ oc get configmaps openshift-install -n openshift-config -oyaml
apiVersion: v1
data:
  invoker: user
  version: unreleased-master-1003-g4edffaead4e6f4d4e539daa1cf7ea3444fe69c49
kind: ConfigMap
metadata:
  creationTimestamp: "2019-08-23T17:32:52Z"
  name: openshift-install
  namespace: openshift-config
  resourceVersion: "169"
  selfLink: /api/v1/namespaces/openshift-config/configmaps/openshift-install
  uid: 09007ae1-c5cc-11e9-a047-52fdfc072182
```

**Comment by gbraad** [comment]
That is the default value as from: https://github.com/openshift/installer/blob/c7a87b5a60201a22f7b061bb18ed8133460de4b6/pkg/asset/cluster/tfvars.go#L338

```
data:
  invoker: user
```

**Comment by crawford** [comment]
@gbraad it is possible to modify the ConfigMap after installation. The updated values will be reflected in telemetry.

@praveenkumar Yep. If you set `OPENSHIFT_INSTALL_INVOKER`, the `data.invoker` field will be set to the custom value in that ConfigMap. You can then use a PromQL query like the following: `count(cluster_installer{invoker="codeReadyContainer"})`

**Comment by praveenkumar** [comment]
This is taken care as part of snc https://github.com/code-ready/snc/pull/91

**Comment by cfergeau** [comment]
And this was merged, so this issue is fixed as well.
