### ISSUE TITLE
Allow crc.testing domain to be changed

### ISSUE THREAD

**Issue by BenHall** [code-ready/crc#512]
Is it possible to change the domain from `crc.testing` to something else?

**Comment by BenHall** [comment]
It looks like they are defined as variables
 
https://github.com/code-ready/crc/blob/8443082ab4a27d594d0143661e0c904867028f6b/pkg/crc/constants/constants.go#L20-L21

Can this be added as an override to https://github.com/code-ready/crc/blob/8956feedb9039841434dd17e8d1e2446e6b49119/cmd/crc/cmd/config/config.go#L26-L31 or is it also hardcoded on the VM side?

**Comment by BenHall** [comment]
It looks like there are more domains defined somewhere, such as `oauth-openshift.apps-crc.testing` but unsure how they are defined.

**Comment by cfergeau** [comment]
The crc.testing domain is something we specify to openshift-install before the VM is even created, so yes, once you have a VM image this is hardcoded. In theory, we could change the generation scripts to use a new domain, and crc would be able to deal with it, but this has never been tested. See ~/.crc/cache/crc_libvirt_4.1.11/crc-bundle-info.json which has all these parameters.

However, a bigger question is why you want to change this?

**Comment by BenHall** [comment]
I would like the dashboard to be routable outside of my local instance

**Comment by gbraad** [comment]
> I would like the dashboard to be routable outside of my local instance

That is a different question to the reported "Allow domain to be changed".

**Comment by gbraad** [comment]
> It looks like they are defined as variables
>
> https://github.com/code-ready/crc/blob/8443082ab4a27d594d0143661e0c904867028f6b/pkg/crc/constants/constants.go#L20-L21

Actually not. As mentioned, they are defined on start. These variables should be changed and refactored to use the metadata when possible. /cc: @code-ready/crc-devel

**Comment by BenHall** [comment]
@gbraad Thanks for the additional info. I was hoping for a quick win but understand it's not the core use-case :)

**Comment by gbraad** [comment]
This is not possible and needs a recreation step of the used cluster images using code-ready/snc. 

> I would like the dashboard to be routable outside of my local instance

This is not the usecase of CRC. Consider using the installer to create this.
