### ISSUE TITLE
crc start fails after crc stop (hosts file not readable/writeable)

### ISSUE THREAD

**Issue by jr00n** [code-ready/crc#513]
Today uses crc init and crc start, crc stop

after a few hours would use crc start, but it's not working anymore

```
INFO Checking if oc binary is cached
INFO Checking if HyperKit is installed
INFO Checking if crc-driver-hyperkit is installed
INFO Checking file permissions for /etc/resolver/testing
INFO Checking file permissions for /etc/hosts
FATA /etc/hosts is not readable/writable by the current user
```
version: 1.0.0-beta.3-4.1.11+e97bf65

**Comment by praveenkumar** [comment]
@jr00n Did you try to use `crc setup` before `crc start` ?

**Comment by gbraad** [comment]
> FATA /etc/hosts is not readable/writable by the current user

this is a check we perform and it fails, saying it does not find the correct permissions. This file needs to be writable by the current user to overcome and issue with `oc`: https://github.com/openshift/origin/issues/23266

As mentioned, please run `crc setup`
