### ISSUE TITLE
Unable to enter pull-secret when using MinTTY during start command: 'Incorrect Function'

### ISSUE THREAD

**Issue by stevef1uk** [code-ready/crc#515]
On a Windows laptop 10 Pro
After running:

```
crc setup
crc start -c 7 -m 13000 --log-level debug
```

I get as far as the prompt for:

```
level=info msg="Does the Hyper-V virtual switch exist"
? Image pull secret [? for help]
level=error msg="Error ocurred: Incorrect function"
```

then it exits without giving me the chance to enter the secret

I am guessing I need to create a network interface for hyperv, but as I can't set the name (unlike minishift) what does it need to be called?

BTW: this worked fine on my iMac

**Comment by cfergeau** [comment]
Not sure how this could be related, but if you run `crc start` with no additional parameters, did it fail the same way?

**Comment by stevef1uk** [comment]
yes

**Comment by stevef1uk** [comment]
I should say that I have run minishift ok on this Windows laptop so hyperv is ok

**Comment by cfergeau** [comment]
What version of Windows is this?

**Comment by stevef1uk** [comment]
Windows 10 Pro Version 1803OS build 17134.959

**Comment by gbraad** [comment]
Which shell are you using?

**Comment by stevef1uk** [comment]
bash (of course ;-)

**Comment by gbraad** [comment]
And that is your problem. Many implementations do not properly support
psuedo terminal. In this case it likely does not work to wait for input,
and therefore that function inside the bash shell fails... Hence the error.
This is not something with CRC. Please use command prompt or powershell as
instructed.

Which bash is used? If WSL, then this will never work properly as the
driver can not communicate, if cygwin then not sure why this fails, if
other ... ?

**Comment by gbraad** [comment]
A probable workaround could be to use the pull-secret-file option to avoid the interactive session. However, other problems might occur as this is an untested setup for CRC. For Minishift I had the time to test more options.

**Comment by stevef1uk** [comment]
Thanks. I was using gitbash, but when I switched to Powershell I was able to run the VM. I may have had to start the VM manually though using Hyper V as I had a few VM error messages on starting 

"creating host: Error creating the VM. Error creating machine: Error in driver during machine creation: exit status 1"

Was slower to start on Windoze than on a Mac though.

**Comment by gbraad** [comment]
The creating might not have successfully finished, so a delete might have helped

Good to hear it works... I will look at gitbash again and perhaps include a note about support or try to get a workaround.

**Comment by gbraad** [comment]
![image](https://user-images.githubusercontent.com/1894/64093476-164ffd80-cd8b-11e9-9819-961127b73255.png)

Which terminal did you use? I guess MinTTY instead of using bash with Command Prompt, right?

**Comment by stevef1uk** [comment]
Sorry, I don't remember seeing that option. I download Git for window and run Git Bash

**Comment by gbraad** [comment]
This option is given during the installation of Git for Windows.

**Comment by gbraad** [comment]
I am able to reproduce this now. Looking into this (re-open).

**Comment by gbraad** [comment]
The issue is with https://github.com/AlecAivazis/survey/tree/v1.8.7

**Comment by gbraad** [comment]
https://github.com/AlecAivazis/survey/issues/148

**Comment by gbraad** [comment]
This can be reproduced with starting `C:\Program Files\Git\usr\bin\mintty.exe` as terminal and then use:

```
$ cmd
Microsoft Windows [Version 10.0.18956.1000]
(c) 2019 Microsoft Corporation. All rights reserved.

c:\Users\gbraad\Downloads>crc.exe start
"crc (6).exe" start
level=info msg="Checking if oc binary is cached"
level=info msg="Checking if CRC bundle is cached in '$HOME/.crc'"
level=info msg="Check Windows 10 release"
level=info msg="Hyper-V installed and operational"
level=info msg="Is user a member of the Hyper-V Administrators group"
level=info msg="Does the Hyper-V virtual switch exist"
Error
CreateFile C:\Users\gbraad\.crc\cache\pullsecret.json: The system cannot find the file specified.? Image pull secret [? for help] HELLLO???

level=error msg="Error occurred: Incorrect function."

```

this concludes this is an issue with MinTTY.

**Comment by gbraad** [comment]
Filed: https://github.com/mintty/mintty/issues/906

**Comment by gbraad** [comment]
This might have been fixed with the latest release of Cygwin. As per [comment](https://github.com/mintty/mintty/issues/906#issuecomment-566297438):

> Cygwin 3.1.0 has been released with ConPTY support. Please recheck.
