### ISSUE TITLE
Improve output of the various 'crc config' subcommands

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#518]
'crc config' output could get several minor improvements:

- the list of config options from `crc config` is not sorted
- `crc config unset` reports an error when unsetting a key with no
value set, but no errors when the key had a default value defined
- `crc config view` formatting is missing a few spaces for perfect alignement
- `crc config view` always shows 'nameserver' and 'pull-secret-file' even when
they are not set

**Comment by praveenkumar** [comment]
Fixed by #519
