### ISSUE TITLE
Console access on windows 

### ISSUE THREAD

**Issue by anpati1** [code-ready/crc#522]
Successfully installed crc on hyper-v which created a crc VM. However, not sure how to access the console https://console-openshift-console.apps-crc.testing or the login domain https://api.crc.testing:6443 from the windows host machine. Isn't 'crc setup' supposed to add DNS entries like it does on the Linux host? Are there any manual DNS entries required?

**Comment by gbraad** [comment]
The namesever is added to the Default Switch (for this you get the UAC admin popup at the end), and this allows you to open the link directly. If not, please check with PowerShell:

```
Get-DNSClientServerAddress "vEthernet (Default Switch)"
```

**Comment by anpati1** [comment]
sorted :) I had another external switch...
