### ISSUE TITLE
Request: Cert configuration instructions for crc instance

### ISSUE THREAD

**Issue by jiekang** [code-ready/crc#532]
I have setup a crc instance and successfully logged in as kubeadmin.

Currently, OperatorHub related containers (project openshift-marketplace) are failing with for example:

```
time="2019-09-03T16:31:58Z" level=error msg="the following error(s) occurred while preparing the download list: Get https://quay.io/cnr/api/v1/packages?namespace=certified-operators: x509: certificate is valid for *.apps-crc.testing, not quay.io" port=50051 type=appregistry
```

Similarly, `oc new-app` attempts against quay.io images show a similar error with the x509 certificate.

I believe I need to configure the cluster, possibly adding a certificate but I'm not sure where or how. Could anyone here provide guidance? Links or instructions would be greatly appreciated, or if this isn't the appropriate place, some direction as to where I should ask this question also helps.

**Comment by praveenkumar** [comment]
@jiekang this shouldn't be the case if you are using latest version of crc. Can you provide following output `crc status --log-level debug` and `crc version` ?

**Comment by jiekang** [comment]
Hi Praveen. Below is the output requested for the current version being used. However I see there is a newer version available. I will try to use that and let you know how it goes in this issue. I am going away for vacation soon though so it may be some time before I respond. Thank you for helping!

```
$ ./crc status --log-level=debug
DEBU Unexpected operator status for authentication: Upgradeable 
DEBU Unexpected operator status for console: Upgradeable 
DEBU Unexpected operator status for kube-apiserver: Upgradeable 
DEBU Unexpected operator status for kube-controller-manager: Upgradeable 
DEBU Unexpected operator status for kube-scheduler: Upgradeable 
DEBU Unexpected operator status for openshift-apiserver: Upgradeable 
DEBU Unexpected operator status for openshift-controller-manager: Upgradeable 
DEBU Unexpected operator status for service-ca: Upgradeable 
DEBU Unexpected operator status for service-catalog-apiserver: Upgradeable 
DEBU Unexpected operator status for service-catalog-controller-manager: Upgradeable 
CRC VM:          Running
OpenShift:       Running (v4.x)
Disk Usage:      19.75GB of 32.2GB (Inside the CRC VM)
Cache Usage:     11.42GB
Cache Directory: <redacted>

$ ./crc version
version: 0.90.0-alpha-4.1.9+b2559b5
```

**Comment by gbraad** [comment]
This version should be usable anymore. It likely has failed a test on startup... as the certificate should be expired and does not get extended currently. Please use the beta release.

**Comment by jiekang** [comment]
I have updated my crc instance by stopping the instance, deleting it and then removing all the contents of `.crc/` before running setup and start using the tarball from:
https://mirror.openshift.com/pub/openshift-v4/clients/crc/1.0.0-beta.3/

Unfortunately, when I view logs for the marketplace-operator pods like certified-operators, community-operators and redhat-operators, I still see a CrashLoopBackOff with logs showing the x509 certificate issue mentioned above. Here is the output now of status and version:

```
$ ./crc version
version: 1.0.0-beta.3-4.1.11+e97bf65

$ ./crc status --log-level=debug
DEBU Unexpected operator status for authentication: Upgradeable 
DEBU Unexpected operator status for console: Upgradeable 
DEBU Unexpected operator status for kube-apiserver: Upgradeable 
DEBU Unexpected operator status for kube-controller-manager: Upgradeable 
DEBU Unexpected operator status for kube-scheduler: Upgradeable 
DEBU Unexpected operator status for openshift-apiserver: Upgradeable 
DEBU Unexpected operator status for openshift-controller-manager: Upgradeable 
DEBU Unexpected operator status for service-ca: Upgradeable 
DEBU Unexpected operator status for service-catalog-apiserver: Upgradeable 
DEBU Unexpected operator status for service-catalog-controller-manager: Upgradeable 
CRC VM:          Running
OpenShift:       Running (v4.x)
Disk Usage:      11.55GB of 32.2GB (Inside the CRC VM)
Cache Usage:     11.03GB
Cache Directory: <redacted>/.crc/cache
```

**Comment by anpati1** [comment]
Hi, My certified-operators, community-operators and redhat-operators- pods keep failing because of  Warning  Unhealthy        22m (x3 over 23m)     kubelet, crc-vsqrt-master-0  Readiness probe failed: timeout: failed to connect service "localhost:50051" within 1s
  Warning  Unhealthy        22m (x3 over 23m)     kubelet, crc-vsqrt-master-0  Liveness probe failed: timeout: failed to connect service "localhost:50051" within 1s
  Warning  BackOff          3m35s (x84 over 22m)  kubelet, crc-vsqrt-master-0  Back-off restarting failed container

**Comment by gbraad** [comment]
@anpati1 that looks like a different issue. Make sure you run the latest version (as image bundles expire after 30 days), then if the issue persists please file a new issue.

**Comment by gbraad** [comment]
> I still see a CrashLoopBackOff with logs showing the x509 certificate issue mentioned above.

Hmmm :-/

**Comment by jiekang** [comment]
My recent attempt in a fresh environment was successful. It looks like my attempts to use firewall-cmd/iptables to route remote requests to the instance weren't correct. Closing.
