### ISSUE TITLE
macOS oc login error: net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by op314** [code-ready/crc#534]
On macOS Mojave (10.14.6) when I run "eval $(crc oc-env) && oc login -u kubeadmin -p xxxxxxxxxxxxxxxx https://api.crc.testing:6443" I get the following error: net/http: TLS handshake timeout

**Comment by praveenkumar** [comment]
@op314 This looks like the either your VM is not up and running or dns failed. Can you provide what is the output of `crc status --log-level debug` ?

**Comment by op314** [comment]
Hi ,
I can connect to the console.
When I run the command `crc status --log-level debug` I get the following output:DEBU Unexpected operator status for authentication: Upgradeable
DEBU Unexpected operator status for console: Upgradeable
DEBU Unexpected operator status for kube-apiserver: Upgradeable
DEBU Unexpected operator status for kube-controller-manager: Upgradeable
DEBU Unexpected operator status for kube-scheduler: Upgradeable
DEBU Unexpected operator status for openshift-apiserver: Upgradeable
DEBU Unexpected operator status for openshift-controller-manager: Upgradeable
DEBU Unexpected operator status for service-ca: Upgradeable
DEBU Unexpected operator status for service-catalog-apiserver: Upgradeable
DEBU Unexpected operator status for service-catalog-controller-manager: Upgradeable
CRC VM:          Running
OpenShift:       Running (v4.x)
Disk Usage:      14.75GB of 32.2GB (Inside the CRC VM)
Cache Usage:     10.48GB
Cache Directory: /Users/peter/.crc/cache

When I do `curl -k https://api.crc.testing:6443` I get:
{
  "paths": [
    "/api",
    "/api/v1",
    "/apis",
    "/apis/",
    "/apis/admissionregistration.k8s.io",
......
}

**Comment by praveenkumar** [comment]
@op314 Can you try below and see if able to connect?

```
$ unset KUBECONFIG
$ eval $(crc oc-env) 
$ oc login -u kubeadmin -p xxxxxxxxxxxxxxxx https://api.crc.testing:6443
```

**Comment by op314** [comment]
I have the same error: net/http: TLS handshake timeout

**Comment by praveenkumar** [comment]
@op314 Are you able to open the web console and login using the `kubeadmin` and the password which is provided? you can use `crc console` to open the browser.

**Comment by op314** [comment]
Yes I can open the web console and login with the user kubeadmin.

**Comment by cfergeau** [comment]
Are you still experiencing that issue with the 1.0.0 or 1.1.0 releases? Could you paste the whole output of crc setup/crc start?

**Comment by cfergeau** [comment]
Closing as this hasn't seen activity in 3 months. Feel free to reopen if you are still experiencing this issue.

**Comment by savonarola27** [comment]
Same problem with crc 1.14.0+36ad776 on macOS Catalina 10.15.6.

Web console (also with Safari) is ok but I get error "error: net/http: TLS handshake timeout" when I try to login via CLI.

Below all the tests required above:

```
~/Utils/OpenShift/crc-macos-1.14.0-amd64 % crc oc-env
~/Utils/OpenShift/crc-macos-1.14.0-amd64 % eval $(crc oc-env)
~/Utils/OpenShift/crc-macos-1.14.0-amd64 % crc oc-env
export PATH="/Users/luca/.crc/bin/oc:$PATH"
# Run this command to configure your shell:
# eval $(crc oc-env)
~/Utils/OpenShift/crc-macos-1.14.0-amd64 % oc login -u kubeadmin -p DhjTx-8gIJC-2h2tK-eksGY https://api.crc.testing:6443
error: net/http: TLS handshake timeout
~/Utils/OpenShift/crc-macos-1.14.0-amd64 % crc status --log-level debug
DEBU CodeReady Containers version: 1.14.0+36ad776
DEBU OpenShift version: 4.5.4 (embedded in binary)
DEBU About to run SSH command with hidden output
DEBU SSH command succeeded
DEBU dns operator is degraded, Reason: NotAllDNSesAvailable
DEBU dns operator is still progressing, Reason: Reconciling
DEBU dns operator not available, Reason: DNSUnavailable
DEBU kube-apiserver operator is still progressing, Reason: NodeInstaller
DEBU kube-scheduler operator is still progressing, Reason: NodeInstaller
DEBU openshift-apiserver operator not available, Reason: APIServerDeployment_NoPod::APIServices_PreconditionNotReady
DEBU operator-lifecycle-manager-packageserver operator not available, Reason:
DEBU operator-lifecycle-manager-packageserver operator is still progressing, Reason:
DEBU About to run SSH command:
df -B1 --output=size,used,target /sysroot | tail -1
DEBU SSH command results: err: <nil>, output: 32720793600 11685629952 /sysroot
CRC VM:          Running
OpenShift:       Degraded
Disk Usage:      11.69GB of 32.72GB (Inside the CRC VM)
Cache Usage:     13.1GB
Cache Directory: /Users/luca/.crc/cache
~/Utils/OpenShift/crc-macos-1.14.0-amd64 % curl -k https://api.crc.testing:6443
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {

  },
  "code": 403
}%                                                                                                                                                              ~/Utils/OpenShift/crc-macos-1.14.0-amd64 % unset KUBECONFIG
~/Utils/OpenShift/crc-macos-1.14.0-amd64 % eval $(crc oc-env)
~/Utils/OpenShift/crc-macos-1.14.0-amd64 % oc login -u kubeadmin -p DhjTx-8gIJC-2h2tK-eksGY https://api.crc.testing:6443
error: net/http: TLS handshake timeout
~/Utils/OpenShift/crc-macos-1.14.0-amd64 %
```

**Comment by praveenkumar** [comment]
@savonarola27 This issue is closed, can you open a new one with the template provided for issue?

**Comment by savonarola27** [comment]
Yes, sure. Sorry.
