### ISSUE TITLE
doc: Section '1.4. Setting up CodeReady Containers' is linux-centric

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#538]
Let's say I'm a Windows user, should this part of the documentation tell me to open cmd.exe or powershell.exe? I also don't need permission to use 'sudo'

**Comment by DustinKingen** [comment]
The add to this it's not documented how Hyper-V should be configured.

```
INFO Caching oc binary
INFO Unpacking bundle from the CRC binary
INFO Check Windows 10 release
INFO Hyper-V installed
INFO Is user a member of the Hyper-V Administrators group
INFO Does the Hyper-V virtual switch exist
ERRO Error occurred: Virtual Switch not found
ERRO Error occurred: Please override the default by adding an external virtual switch and set configuration
FATA Please override the default by adding an external virtual switch and set configuration
```

**Comment by gbraad** [comment]
`crc setup` should not be run as Administrator. You might have to relogin before the user is properly added to the group. This isssue has been reported and we are working on a fix.

**Comment by robin-owen** [comment]
This is done.
