### ISSUE TITLE
Certs have expired

### ISSUE THREAD

**Issue by heiko-braun** [code-ready/crc#548]
What do I need to do in this case?

```
./crc start -b crc_hyperkit_4.1.6.crcbundle 
...
ERRO Error occurred: Certs have expired, they were valid till: 19 Aug 19 06:54 +0000
```

**Comment by praveenkumar** [comment]
@heiko-braun you need to use latest version of CRC from https://cloud.redhat.com/openshift/install/crc/installer-provisioned this page will be always going to provide you the latest bits around crc.

**Comment by gbraad** [comment]
This is expected behaviour the current releases. Closing.
