### ISSUE TITLE
[BUG] macOS -  IP address never found in dhcp leases file Temporary Error: could not find an IP address for <IPv6 address>

### ISSUE THREAD

**Issue by karstengresch** [code-ready/crc#555]
### General information

  * macOS
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it: Yes
  * Static or dynamic networking: Tested both static and dynamic networking.

## CRC version
```bash
version: 1.0.0-beta.3-4.1.11+e97bf65
```
  
## CRC status
```bash
# Put `crc status` output here
```

## CRC config
```bash
- bundle                             : /Users/karsten/.crc/crc_hyperkit_4.1.11.crcbundle
- cpus                               : 4
- memory                             : 8192
- nameserver                         :
- pull-secret-file                   :
- vm-driver                          : hyperkit
- warn-check-bundle-cached           : true
```

## Host Operating System
```bash
roductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G95
```

### Steps to reproduce

  1. ```crc setup```
  2. ```crc start```

### Expected
OCP should start.

### Actual
Getting this expection:

```
INFO Checking if oc binary is cached
INFO Checking if HyperKit is installed
INFO Checking if crc-driver-hyperkit is installed
INFO Checking file permissions for /etc/resolver/testing
INFO Checking file permissions for /etc/hosts
INFO Checking if CRC bundle is cached in '$HOME/.crc'
INFO Loading bundle: crc_hyperkit_4.1.11.crcbundle ...
INFO Creating VM ...
ERRO Error occurred: Error creating host: Error creating the VM. Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary Error: could not find an IP address for e6:c8:98:13:2e:76
hyperkit crashed! command line:
  hyperkit BOOT_IMAGE=/ostree/rhcos-e1b8fa18a8f068bad264a0043d69d8f6d39265d77ab9857d142ab8c65a5ad219/vmlinuz-4.18.0-80.7.2.el8_0.x86_64 console=tty0 console=ttyS0,115200n8 rootflags=defaults,prjquota rw root=UUID=a8fbdcb1-63ea-421e-8f6f-dac9cbbcc822 ostree=/ostree/boot.0/rhcos/e1b8fa18a8f068bad264a0043d69d8f6d39265d77ab9857d142ab8c65a5ad219/0 coreos.oem.id=qemu ignition.platform.id=qemu

```

### Logs
[crc.log](https://gist.github.com/karstengresch/02c1c38e4fc6412e59479aa06da7fbe2)

**Comment by karstengresch** [comment]
Update: Disabled extra firewall (LittleSnitch) - same error message.

**Comment by karstengresch** [comment]
Seems the same problem as in https://github.com/kubernetes/minikube/issues/2430

**Comment by karstengresch** [comment]
Ok, this solved it for me (doh - only xhyve installed, not hyperkit...): Install hyperkit as explained at https://github.com/moby/hyperkit under **Building**.

**Comment by cfergeau** [comment]
> Ok, this solved it for me (doh - only xhyve installed, not hyperkit...): Install hyperkit as explained at https://github.com/moby/hyperkit under **Building**.

Reopening this issue as this should not matter, crc should be downloading its own hyperkit binary during setup, if this did not happen/if this binary was not being used, this is a problem to solve. Do you have an hyperkit binary in ~/.crc/bin?

**Comment by praveenkumar** [comment]
@karstengresch can you provide those information what @cfergeau asked for?

**Comment by cfergeau** [comment]
Closing this bug as the additional information was not provided, and that we did not get additional bug reports about this.

**Comment by mikecroft** [comment]
@cfergeau - bit late to the party but I'm had the same problem as this and managed to stumble over the problem. I have got the hyperkit binary and driver in `~/.crc/bin`. I'm using the latest CRC bundle.

My Mac is on a similar version to OP:

```
  System Version:	macOS 10.14.6 (18G1012)
  Kernel Version:	Darwin 18.7.0
```

The output from crc start is:

```
➜ ~ crc start
INFO Checking if running as non-root              
INFO Checking if oc binary is cached              
INFO Checking if HyperKit is installed            
INFO Checking if crc-driver-hyperkit is installed 
INFO Checking file permissions for /etc/resolver/testing 
INFO Checking file permissions for /etc/hosts     
INFO Extracting bundle: crc_hyperkit_4.2.2.crcbundle ... 
INFO Creating CodeReady Containers VM for OpenShift 4.2.2... 
ERRO Error creating host: Error creating the VM: Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary Error: could not find an IP address for 36:44:21:8d:a4:35
Temporary Error: could not find an IP address for 36:44:21:8d:a4:35
hyperkit crashed! command line:
  hyperkit BOOT_IMAGE=/ostree/rhcos-535c7d9a5caf4cfbf2865579111c3942dd295c120e6776cd0dbe4165179aa351/vmlinuz-4.18.0-80.11.2.el8_0.x86_64 console=tty0 console=ttyS0,115200n8 rootflags=defaults,prjquota rw root=UUID=477c3d77-20c6-4ff3-8bb3-dc2543eedfbd ostree=/ostree/boot.0/rhcos/535c7d9a5caf4cfbf2865579111c3942dd295c120e6776cd0dbe4165179aa351/0 coreos.oem.id=qemu ignition.platform.id=qemu 
```

The solution
----

This is probably not exactly the same as OP's issue but it helped me move forward. I noticed in my CRC config (`crc config view`) that I had fat-fingered my memory setting to be more than I had in my laptop. Correcting it to a more normal value made it start properly.

My _**guess**_ (and it is very much a guess) is that Hyperkit was failing to start but CRC didn't know about it until it checked `/var/db/dhcpd_leases` for network info. I expect OP likely had some other config error which caused Hyperkit to fail to create the VM and that lead to the error above.

Hopefully that's helpful to someone because it certainly lead me down a few incorrect rabbit holes.

**Comment by cfergeau** [comment]
> My _**guess**_ (and it is very much a guess) is that Hyperkit was failing to start but CRC didn't know about it until it checked `/var/db/dhcpd_leases` for network info. I expect OP likely had some other config error which caused Hyperkit to fail to create the VM and that lead to the error above.

Yes, either this, or it notices that it crashes, but reports a wrong error.
