### ISSUE TITLE
[BUG] Unable to start CRC after initial installation seems to complete

### ISSUE THREAD

**Issue by nhasan1** [code-ready/crc#556]
### General information

  * OS: Windows
  * Hypervisor: Hyper-V 
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
# Put `crc version` output here
version: 1.0.0-beta.3-4.1.11+e97bf65
```
  
## CRC status
```bash
# Put `crc status` output here
ERRO Error occurred: Machine "crc" does not exist. Use "crc start" to add a new one.
```

## CRC config
```bash
# Put `crc config view` output here
- bundle                             : C:\Users\nhasan\.crc\crc_hyperv_4.1.11.crcbundle
- cpus                               : 4
- memory                             : 8192
- nameserver                         :
- pull-secret-file                   :
- vm-driver                          : hyperv
- warn-check-bundle-cached           : true
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `sysinfo` in case of Windows
'sysinfo' is not recognized as an internal or external command,
operable program or batch file.
```

### Steps to reproduce

  1. Run crc setup - including check to see if the user is member of the Hyper-V Administrators group
  2. Run crc start Error starting Usre is not part of Hyper-V Administrators group
  3. 
  4. 

### Expected
OpenShift 4 CRC cluster starts

### Actual
C:\WINDOWS\system32>crc start --log-level=debug
INFO Checking if oc binary is cached
DEBU oc binary already cached
INFO Checking if CRC bundle is cached in '$HOME/.crc'
INFO Check Windows 10 release
INFO Hyper-V installed and operational
INFO Is user a member of the Hyper-V Administrators group
ERRO Error occurred: User is not a member of the Hyper-V administrators group
FATA User is not a member of the Hyper-V administrators group

### Logs

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.
[crc.log](https://github.com/code-ready/crc/files/3586076/crc.log)

**Comment by gbraad** [comment]
Did you reboot (or relogin) your machine?

**Comment by nhasan1** [comment]
After rebooting it seems fine. I wasn't able to complete the install due to a disk size issue. I wonder if there is place where we can specify the install directory? 

Also, probably a good idea to update the doc with the restart to avoid these types of questions :)

**Comment by bharatbalothia** [comment]
For me signing out from the current user and signing in back resolved the problem.
