### ISSUE TITLE
[BUG] Cluster start upon first install fails with CSR names (tcp connection error)

### ISSUE THREAD

**Issue by nhasan1** [code-ready/crc#573]
### General information

  * OS:  Windows
  * Hypervisor: Hyper-V 
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
# Put `crc version` output here
version: 1.0.0-beta.3-4.1.11+e97bf65
```
  
## CRC status
```bash
# Put `crc status` output here
C:\Users\nhasan>crc status
CRC VM:          Running
OpenShift:       Running (v4.x)
Disk Usage:      11.22GB of 32.2GB (Inside the CRC VM)
Cache Usage:     11.08GB
Cache Directory: C:\Users\nhasan\.crc\cache
```

## CRC config
```bash
# Put `crc config view` output here
C:\Users\nhasan>crc config view
- bundle                             : C:\Users\nhasan\.crc\crc_hyperv_4.1.11.crcbundle
- cpus                               : 4
- memory                             : 8192
- nameserver                         :
- pull-secret-file                   :
- vm-driver                          : hyperv
- warn-check-bundle-cached           : true
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `sysinfo` in case of Windows
C:\Users\nhasan>sysinfo
'sysinfo' is not recognized as an internal or external command,
operable program or batch file.
```

### Steps to reproduce
  1.  start up crc after install 
  2. Error displays ERRO Error occurred: Error approving the node csr Not able to get csr names (exit status 1 : Unable to connect to the server: dial tcp: lookup api.crc.testing: no such host
)
  3. Console came up and was able to login using the web gui however some of the service are not working (could be related to the error on #2)
  4. Also, notice the dns query failure earlier on - not sure if it is related to the error down the road.

### Expected
Cluster start

### Actual
-- Steps below along with a couple of troubleshooting items I tried. 
C:\Users\nhasan>crc start
INFO Checking if oc binary is cached
INFO Checking if CRC bundle is cached in '$HOME/.crc'
INFO Check Windows 10 release
INFO Hyper-V installed and operational
INFO Is user a member of the Hyper-V Administrators group
INFO Does the Hyper-V virtual switch exist
INFO Loading bundle: crc_hyperv_4.1.11.crcbundle ...
INFO Creating VM ...
INFO Verifying validity of the cluster certificates ...
INFO Check internal and public dns query ...
WARN Failed Public dns query: ssh command error:
command : host -R 3 quay.io
err     : exit status 1
output  : ;; connection timed out; no servers could be reached
 :
INFO Copying kubeconfig file to instance dir ...
INFO Adding user's pull secret and cluster ID ...
INFO Starting OpenShift cluster ... [waiting 3m]
INFO To access the cluster using 'oc', run 'eval $(crc oc-env) && oc login -u kubeadmin -p <redacted> https://api.crc.testing:6443'
INFO Access the OpenShift web-console here: https://console-openshift-console.apps-crc.testing
INFO Login to the console with user: kubeadmin, password: <redacted>
ERRO Error occurred: Error approving the node csr Not able to get csr names (exit status 1 : Unable to connect to the server: dial tcp: lookup api.crc.testing: no such host
)

C:\Users\nhasan>eval $(crc oc-env)
'eval' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\nhasan>
C:\Users\nhasan>oc login -u kubeadmin -p <redacted> https://api.crc.testing:6443'
'oc' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\nhasan>crc oc-env
SET PATH=C:\Users\nhasan\.crc\bin;%PATH%
REM Run this command to configure your shell:
REM     @FOR /f "tokens=*" %i IN ('crc oc-env') DO @call %i

C:\Users\nhasan>oc login -u kubeadmin -p 78UVa-zNj5W-YB62Z-ggxGZ https://api.crc.testing:6443'
'oc' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\nhasan>SET PATH=C:\Users\nhasan\.crc\bin;%PATH%

C:\Users\nhasan>oc login -u kubeadmin -p <redacted> https://api.crc.testing:6443'
error: not a valid URL: parse https://api.crc.testing:6443': invalid port ":6443'" after host

C:\Users\nhasan>oc login -u kubeadmin -p <redacted> https://api.crc.testing
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

error: Seems you passed an HTML page (console?) instead of server URL.
Verify provided address and try again.

### Logs

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by nhasan1** [comment]
Logs attached [crc.log](https://github.com/code-ready/crc/files/3599910/crc.log)

**Comment by pwei1018** [comment]
You can use 'oc start -n 8.8.8.8' to restart your cluster. That should fix your names issue.
