### ISSUE TITLE
VBoxManage.exe cannot open the file crc.disk

### ISSUE THREAD

**Issue by Dynabix** [code-ready/crc#592]
### General information

  * OS: Windows
  * Hypervisor: VirtualBox
  * Did you run `crc setup` before starting it (Yes)?

## CRC version
version: 1.0.0-beta.3-4.1.11+e97bf65
  
## CRC status
CRC VM:          Stopped
OpenShift:       Stopped
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     11.08GB
Cache Directory: C:\Users\David\.crc\cache

## CRC config
- bundle                             : C:\Users\David\.crc\crc_hyperv_4.1.11.crcbundle
- cpus                               : 4
- memory                             : 8192
- nameserver                         :
- pull-secret-file                   :
- vm-driver                          : hyperv
- warn-check-bundle-cached           : true

## Host Operating System
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.17763 N/A Build 17763

## Virtualbox version
6.0.10 r132072

### Steps to reproduce
(crc exe on same disk as home dir as per https://github.com/code-ready/crc/issues/559))
  1. crc setup --vm-driver virtualbox
  2. crc start --vm-driver virtualbox --bundle C:\Users\David\.crc\crc_hyperv_4.1.11.crcbundle
  3. 
  4. 

### Expected
Working VM created in Virtualbox

### Actual
VM created but with error (and therefore not runnable).
The crc.disk is created and had a size of 10.821.632 kB
My Windows disk (C:) has plenty of space left.
Output:
INFO Loading bundle: crc_hyperv_4.1.11.crcbundle ...
INFO Extracting bundle: crc_hyperv_4.1.11.crcbundle ...
INFO Creating VM ...
ERRO Error occurred: Error creating host: Error creating the VM. Error creating machine: Error in driver during machine creation: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe storageattach crc --storagectl SATA --port 0 --device 0 --type hdd --medium C:\Users\David\.crc\machines\crc\crc.disk failed:
VBoxManage.exe: error: Could not open the medium 'C:\Users\David\.crc\machines\crc\crc.disk'.
VBoxManage.exe: error: VD: error VERR_NOT_SUPPORTED opening image file 'C:\Users\David\.crc\machines\crc\crc.disk' (VERR_NOT_SUPPORTED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MediumWrap, interface IMedium, callee IUnknown
VBoxManage.exe: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 191 of file VBoxManageDisk.cpp
 BoxManage.exe: error: Invalid UUID or filename "C:\Users\David\.crc\machines\crc\crc.disk"

### Logs

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by Dynabix** [comment]
This seems to be more of a dociumentation issue. So what I needed to do was to download the Virtualbox bundle from https://mirror.openshift.com/pub/openshift-v4/clients/crc/latest/ and use that instead. That still left me with this issue https://github.com/code-ready/crc/issues/529 but that seems to  be a known problem. It would really help if there was a more step-by-step guide for using crc with Virtualbox.

**Comment by gbraad** [comment]
> It would really help if there was a more step-by-step guide for using crc with Virtualbox.

There will be limited documentation available as this is an unsupported setup. We offer it as many enterprises have this pre-installed... but the performance and resource usage has been proved to be abysmal when compared to native virtualization. Consider this an advanced use-case.
