### ISSUE TITLE
Add basic pre-flight checks and setup (Linux / Libvirt)

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#6]
Depends on: #9 

Which checks are needed for Linux; libvirt?

**Comment by gbraad** [comment]
This needs a tighter integration between the pre-flight check failure and the setup code (for each of the steps).

**Comment by gbraad** [comment]
* Hypervisor setup: libvirt

**Comment by anjannath** [comment]
Checks needed for Linux; libvirt:

* Is virtualization enabled (KVM)
* Is Libvirt installed in the machine
* Is Libvirt enabled
* Is IP forwarding enabled (Why is this required??)
* Libvirt daemon accepting network/tcp connections ( Maybe in a single node setup we don't need this)

* Is `docker-machine-driver-kvm` binary present on path
* Is driver binary executable (provided we'll use the drivers)
* Is `default` pool available
* Does `default` pool have sufficient free space.

---------------------------------------------------------------------
There will be checks which will be required irrespective of the Virtualization platform, like network connectivity to internet, dns resolution, etc.

**Comment by gbraad** [comment]
> Is virtualization enabled (KVM)

check if `/dev/kvm`, check if the virtual extensions (from `/proc/cpuinfo`) and see if BIOS option is enabled.

**Comment by gbraad** [comment]
> Is Libvirt installed in the machine

For MVP focus on Fedora, CentOS and related distros first.... Post MVP we can support other distros

**Comment by gbraad** [comment]
> Is Libvirt enabled

System daemon is up and running.

make sure the user is memer of the libvirt group.... else it is useless to check the daemon state, because user is not able to connect.

**Comment by gbraad** [comment]
Maybe it might be worth looking into using on ly user session to create and start the VM. Maybe @zeenix can help with this.

**Comment by gbraad** [comment]
> Libvirt daemon accepting network/tcp connections ( Maybe in a single node setup we don't need this)

Nope... you are right. At this stage we are only doing the Single-VM option and perhaps and a big perhaps in future we will also do the cluster API, to scale out.

**Comment by gbraad** [comment]
> docker-machine-driver-kvm

maybe we should change the name of the expected driver

**Comment by zeenix** [comment]
> Maybe it might be worth looking into using on ly user session to create and start the VM.

ly?

**Comment by zeenix** [comment]
@gbraad if you meant that I should probably look into using session libvirt instead of system, yeah I'm already on it. The first step would be to add support for creating storage pool in terraform libvirt provider.

**Comment by anjannath** [comment]
@zeenix This came up in regards to defining a network, can we define a network using session libvirt instead of system? if so we don't need to add the user to libvirt group?

**Comment by zeenix** [comment]
@anjannath thanks for the specific context. I think it depends on the network you're defining but I'll check.

**Comment by zeenix** [comment]
So I checked and seems you can't create a bridge network on/from session libvirt (which i suspected) but the thing is that you can create the network on the system libvirt and then use it from VMs in the session libvirt. Actually in GNOME Boxes we used the default bridge created by system libvirt when it's available, while Boxes uses session libvirt for everything. Using the default bridge meant that Boxes didn't need to create a new network and therefore didn't need elevated privileges. While in case of CRC, we do need to at least modify the network, even if we use an existing one and that requires elevated privileges.

I think we should attempt to do something similar in CRC/Installer. I'll need to check how much work it's going to be.
