### ISSUE TITLE
More details needed for how to use `Makefile` for development

### ISSUE THREAD

**Issue by nevermosby** [code-ready/crc#606]
Currently the development guide(https://github.com/code-ready/crc/blob/master/developing.adoc) has few details for how to use `Makefile`. I suggest adding more details for how to do the customized build work based on `Makefile`.

**Comment by cfergeau** [comment]
`make` will build crc and put it in `~/go/bin`, would this be enough details, or is there something else that you wanted to do and would need explanations for?

**Comment by nevermosby** [comment]
Hi @cfergeau thx for reply.
When I run `make`, I got the binary file `crc` in `~/go/bin` as u mentioned, it is about 16M, which is much smaller than the binary I downloaded from [here](https://mirror.openshift.com/pub/openshift-v4/clients/crc/latest/).
So I checked `Makefile`, there are so many `make` targets to use, which confuses me a lot(newbie for `make` stuff). I don't know whether the small binary file is enough for development or I need to run other `make` command to generate the big binary file.
A guide to explain how to run `make` command for development will be nice for me.

**Comment by gbraad** [comment]
The issue with 'much smaller' is that the download contains the image bundle. This is only happening when a release (using `make release`) is performed. for development purpose or changes to CRC, you do not want to embed this bundle each time.

`make cross` creates binaries for each target platform

`make fmt` formats the code for PR to match the coding style

`make lint` and `make gosec` are checks performed on CI for code conformance.

`make clean` get rid of the previous build.

Note: image bundles are created using another repo (`code-ready/snc`), but trust me, you do not want to do this.

**Comment by gbraad** [comment]
Please re-open if unclear. We might update the documentation later to add a more detailed development section, but at this moment we are still busy setting up all the infra for automation, and tools might change or added.

**Comment by nevermosby** [comment]
@gbraad thx for reply and `crc` is a great tool indeed, appreciate you guy's work.
