### ISSUE TITLE
[BUG] Release links are broken

### ISSUE THREAD

**Issue by andyczerwonka** [code-ready/crc#608]
See the release notes.

https://github.com/code-ready/crc/releases

The downloads link returns a 404

![image](https://user-images.githubusercontent.com/138898/65072518-49c78600-d94e-11e9-93b5-e4d6c2068f77.png)

**Comment by praveenkumar** [comment]
@andyczerwonka it is written it will be available on **18th Sep**

**Comment by andyczerwonka** [comment]
Yep, I missed that. Closing.

**Comment by gbraad** [comment]
The message should read `Will be available at:` (not including are) ;-)
