### ISSUE TITLE
Generate release info in JSON format

### ISSUE THREAD

**Issue by anjannath** [code-ready/crc#609]
After a discussion with @praveenkumar on slack, we decided to have the release info (meta-data) file in JSON format and it needs to be generated via calling the `release` target from makefile.

The generated `release-info.json` file would look like:
```json
{	
	"description": "Bringing a minimal OpenShift 4.1 or newer cluster to your local laptop or desktop computer.",
	"version": {
		"crcVersion": "1.0.0-beta.5",
		"gitSha": "f2aa58c"
	},
	"openshiftVersion": "4.1.14" 
}
```

This would be needed for #484

**Comment by cfergeau** [comment]
You could put "openshiftVersion" inside "version" too, but that's mostly bike-shedding ;)

**Comment by gbraad** [comment]
the `release.txt` file has two purposes in this case, to be read by people to know which version `latest` actually points to, and the be machine-parsable. right?

if json, I do not see a need for description, as this is NOT going to be read by a human,

**Comment by anjannath** [comment]
> the release.txt file has two purposes in this case; to be read by people to know which version latest actually points to, and the be machine-parsable. right?

Correct
> if json, I do not see a need for description, as this is NOT going to be read by a human

Its still human readable in json format (the file is relatively smaller)

**Comment by gbraad** [comment]
> Its still human readable in json format (the file is relatively smaller)

```json
{ "comment" : "I do not really agree that the file is still quite readable",
  "reasoning" : "markup, without rendering makes things feel technical",
  "solution" : "go for a simple doc format that can be parsed by a regex",
  "suggestion" : "plain text with a structure, like md or org is also"
}
```

**Comment by praveenkumar** [comment]
We don't need description, `odo` doesn't even have any release.txt file I think we put it there just to make sure later we can easily get the info and display user if they are using an older binary. 

We shouldn't make it too complex, it should match with `crc version` so easy to parse and compare.

```json
{
    "version": "1.0.0-dev+cf25e00"
    "openshiftVersion": "4.1.14"
}
```

**Comment by gbraad** [comment]
So I am not understanding why this needs to be JSON formatted:

```
Version: 1.0.0-dev+cf25e00
OpenShift version: 4.1.14
```

**Comment by praveenkumar** [comment]
@gbraad Why we need this file except serve us a purpose of getting info if there is a new release?  If there is any other purpose of this file which can't be part of release notes/ Readme, I would prefer it to be json (machine readable) format than text file and using regex on that.

**Comment by anjannath** [comment]
There are two use cases, One is for crc to check if a new version is available, the second is when a user, finds out that the binaries are available in mirror.openshift.com, i suspect he'd again go through the whole process in try.openshift.com and would prefer to download from mirror, in that case he'd look in the `release-info.json | release.txt` inside latest to find out what version is the latest release.

So the file needs to be human readable too, and would be better with a description (but to make it simple we can drop it) as he already knows what `crc` does, (new users will most probably come to try.openshift.com). JSON is human readable when its not a very large one, it is OK if it is technical because mostly an advanced user would come to download it from mirror.openshift.com.

**Comment by gbraad** [comment]
fragile? You use a template and have this generated.
JSON does not magically solve these issues

**Comment by gbraad** [comment]
> machines. json will also be easier to extend if need be

you do not solve an issue for possible future needs as they might never get implemented.
a release file does not seem to fit the sha256 usecase, as we already have a file for this.

**Comment by gbraad** [comment]
from chat:

I do not see why this file needs to be json, as this file would be the wrong place to get bundle information from. that exists in the generated bundle metadata... and if needed, we should NOT just inckude that in the bundle archive, but also copy this alongside the bundle.what other information is really relevant to decide if we have a new file... mostly just the crc version and the openshift version (related to the bundle). besides, this file should just be a trigger to us to get a possible new download.but about it being messy or parsing issues... consider that the file NOT being parsable would be the same as the file NOT being available (being offline). either way, we would not have the right information

but if you guys think otherwise, go ahead and add a json file... but I am pretry sure soon we will get a report about people not finding the vrersion info in the `./latest` folder, as people do not tend to open .json or any file that looks like a data file.
