### ISSUE TITLE
crc setup   when run via a process api, not in a tty/pty terminal

### ISSUE THREAD

**Issue by robstryker** [code-ready/crc#632]
### General information

  * OS: Linux / macOS 
  * Hypervisor: default
  * Did you run `crc setup` before starting it (Yes/No)? Issue is with crc setup

## CRC version
```bash
version: 1.0.0-beta.5+f2aa58c
OpenShift version: 4.1.14 (embedded in binary)
```
  
## CRC status
```bash
ERRO Error occurred: Machine "crc" does not exist. Use "crc start" to add a new one. 
```

## CRC config
```bash
# Result is blank
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
NAME=Fedora
VERSION="29 (Workstation Edition)"
ID=fedora
VERSION_ID=29
VERSION_CODENAME=""
PLATFORM_ID="platform:f29"
```

### Steps to reproduce

  1.  Run crc setup via a non-pty non-tty terminal. ie, through Runtime.exec(etc) in java as non-root user
  2.  Expect request for privilege escalation 
  3.  Process stalls for > 2 minutes, then terminates

### Expected
Expect to be prompted for root via sysin / sysout prompts. 

### Actual
level=info msg="Checking if running as non-root"
level=info msg="Caching oc binary"
level=info msg="Setting up virtualization"
level=info msg="Setting up KVM"
level=info msg="Installing libvirt service and dependencies"
level=info msg="Adding user to libvirt group"
level=info msg="Enabling libvirt"
level=info msg="Starting libvirt service"
level=info msg="Installing crc-driver-libvirt"
level=info msg="Removing older system-wide crc-driver-libvirt"
level=info msg="Setting up libvirt 'crc' network"
level=info msg="Starting libvirt 'crc' network"
level=info msg="Checking if NetworkManager is installed"
level=info msg="Checking if NetworkManager service is running"
level=info msg="Writing Network Manager config for crc"
level=info msg="Writing dnsmasq config for crc"
level=info msg="Will use root access: write dnsmasq configuration in /etc/NetworkManager/dnsmasq.d/crc.conf"
level=fatal msg="Failed to write dnsmasq config file: /etc/NetworkManager/dnsmasq.d/crc.conf: Failed writing to file as root: /etc/NetworkManager/dnsmasq.d/crc.conf: : exit status 1"

### Logs

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by cfergeau** [comment]
We are using sudo to try to get root access, I would not be surprised if it's not possible to redirect  stdin/stdout in order to use it.
Do you have any recommendations of how we could handel for priviledge escalation in a way that would work with what you are trying to do? policykit maybe?

**Comment by gbraad** [comment]
Please run `crc setup` from a regular terminal, as the pty support is needed to enter credentials.

I believe `crc start` should work from a non-pty terminal (tested on Windows with git-bash).

**Comment by robstryker** [comment]
It is possible to direct sudo output to standard in / out.  See `man sudo`

```
     -S, --stdin
                 Write the prompt to the standard error and read the password
                 from the standard input instead of using the terminal device.
                 The password must be followed by a newline character.
```

**Comment by gbraad** [comment]
can you detail a little bit more about the expected experience and what therefore is needed from our end?

**Comment by jeffmaury** [comment]
Because we are launching crc through Java `Runtime.exec` method, we have no tty access and adding the `-S` flag when running `sudo` should be ok for us. @robstryker can you confirm ?

**Comment by robstryker** [comment]
It is possible to direct sudo output to standard in / out.  See `man sudo`

```
     -S, --stdin
                 Write the prompt to the standard error and read the password
                 from the standard input instead of using the terminal device.
                 The password must be followed by a newline character.
```

**Comment by robstryker** [comment]
@gbraad  
Current experience:
1) (in java)  use Runtime.exec(etc) to run crc setup
2) When crc attempts to escalate privileges, it fails entirely

Expected experience:
1) (in java)  use Runtime.exec(etc) to run crc setup
2) When crc attempts to escalate privileges, it puts the prompt to the standard output of the process
3) When a password is passed in via standard-in to the process,   crc setup command will properly make use of that input

Solution to get from current experience to expected experience:
1) Anywhere crc setup uses `sudo`,  please use `sudo -S` instead. 
2) Test everything to make sure this solution doesn't break any other expected usecases.

**Comment by cfergeau** [comment]
> Solution to get from current experience to expected experience:
> 
>     1. Anywhere crc setup uses `sudo`,  please use `sudo -S` instead. 
>     2. Test everything to make sure this solution doesn't break any other expected usecases.

Are there any security side-effects to be aware of when doing this?

**Comment by gbraad** [comment]
@robstryker you can use an admin user to run `crc setup`. There is a specific cherck that you can disable which checks for the admin user. But be aware that we prefer to use a regular user as this allows us to determine which user to add to a group.

besides, we do hope a `crc setup` can be run outside of the scope of the IDE as part of a generic installer (or by an admin like in a corporate environment), since you can expect needed reboots. You do not want to be triggered inside the IDE experience.

using stdin and stdout will not work in the case of Windows, since UAC acts as modal on top of the user interface.

**Comment by cfergeau** [comment]
https://twitter.com/MrMohitSuman/status/1300794342408298498 reminded me of this issue, which is impacting that demo Mohit recorded. I would go for an additional `crc setup` argument so that `sudo -S` can be used.

**Comment by guillaumerose** [comment]
Could we have a specific command that only run root commands so that we can do `$ sudo crc setup --root-only` then `$ crc setup` ?

**Comment by cfergeau** [comment]
That could be an option, though some checks have code I'd prefer not to run as root (hyperkit downloading followed by making it suid). It could also be made more complicated if we had some root checks that only make sense after a non-root check/fix, but I cannot think of one for now, so that's purely theoretical ;)
