### ISSUE TITLE
[BUG] Beta5 disk space workaround, unable to extract pod template from type *v1.Node

### ISSUE THREAD

**Issue by tomgeorge** [code-ready/crc#633]
### General information
  * OS: Linux
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
# Put `crc version` output here
version: 1.0.0-beta.5+f2aa58c
OpenShift version: 4.1.14 (embedded in binary)

```
  
## CRC status
```bash
# Put `crc status` output here
CRC VM:          Running
OpenShift:       Running (v4.x)
Disk Usage:      14.36GB of 16.09GB (Inside the CRC VM)
Cache Usage:     26.02GB
Cache Directory: /home/tgeorge/.crc/cache
```

## CRC config
```bash
# Put `crc config view` output here
- cpus                                  : 6
- memory                                : 12288
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
NAME=Fedora
VERSION="30 (Workstation Edition)"
ID=fedora
VERSION_ID=30
VERSION_CODENAME=""
PLATFORM_ID="platform:f30"
PRETTY_NAME="Fedora 30 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:30"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f30/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=30
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=30
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

### Steps to reproduce

  1. `crc setup`
  2. `crc start`
  3. `oc debug node/crc-vsqrt-master-0`
  4. 

### Expected
I get a debug shell to the node and can resize the VM disk.

### Actual
```
λ ~/git/che/deploy/openshift/templates/monitoring/ che-14155* oc debug node/crc-vsqrt-master-0
error: cannot debug crc-vsqrt-master-0: unable to extract pod template from type *v1.Node
```

### Logs

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by gbraad** [comment]
The image by accident got created with only 20GB (default size). We will add a check for this #613 
As mentioned in https://github.com/code-ready/crc/releases/tag/1.0.0-beta.5, there is a workaround:

---

**We found an issue in our bundle for disk image size, please check once https://github.com/code-ready/crc/wiki/Disk-space-issue-with-beta-5-release before using this release**

**Comment by tomgeorge** [comment]
Hi @gbraad, my issue is with the workaround proposed in  https://github.com/code-ready/crc/wiki/Disk-space-issue-with-beta-5-release.  I am unable to run the `oc debug` command as documented in the workaround, and am getting the error as described in the "Actual" section of the above.  

But I am able to run the `oc debug` command now, after recreating the cluster, oddly enough.  I don't think anything changed on my system, though.

**Comment by cballew** [comment]
Sorry to say I get the same results... Can't use the workaround.
