### ISSUE TITLE
oc-env should indicate what to do next

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#636]
On linux/macos, it could also have:
```
echo "You can now login to the OpenShift cluster with `oc login xxx`
```

**Comment by cfergeau** [comment]
It's a bit odd though to show it all the time, as this needs to only be done once.

**Comment by gbraad** [comment]
@cfergeau is this still needed...

also see #708

**Comment by cfergeau** [comment]
>The idea is not for oc-env to provide a user-guide to using the oc command. this is something that should come from documentation and even a higher-level documentation.

I'm fine with that resolution.
