### ISSUE TITLE
Documentation structure

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#64]
Since we know we will release alongside of OpenShift our release schedule is known, however at this point it is not clear what kind of documentation is expected and where this is published. I would suggest to focus first on a getting started guide and then follow-up with detailed documentation.

  * [ ] Getting started guide #65 
  * [ ] contribution guidelines
  * [ ] test strategy (needs input from @tsedmik @jsliacan)
  * [ ] ...

Note: It is best to split this out in several expected tasks. @robin-owen, please do so where you see fit.

**Comment by cfergeau** [comment]
Do we need to keep this open?

**Comment by robin-owen** [comment]
This is done as far as I'm concerned.
