### ISSUE TITLE
[Integration test] `crc stop -f` test should be more generic

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#644]
Right now `crc stop -f` can provide `CodeReady Containers instance stopped` if instance is stopped in required time limit or `CodeReady Containers instance forcefully stopped`if the instance doesn't stop during the time limit. 

Our integration test only check `CodeReady Containers instance stopped` and it make it flaky. We should put a regex in place of absolute string.

- https://regex101.com/r/UkT6En/1

**Comment by jsliacan** [comment]
@praveenkumar, the PR that fixes this issue only changes the instances in the `basic.feature` file. There are some more in the other feature files. Should I submit another PR against this issue or create another issue? Sorry that I didn't get to this on time (before merging).

**Comment by praveenkumar** [comment]
@jsliacan Thanks, I will check on other features and put same and then only close this issue, next time I will remember to add one of you folks as part of the review for any integration PR.
