### ISSUE TITLE
Getting started guide

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#65]
We need a Getting Started Guide to help the user to get up and running in no time.

  * [x] installation of the needed `crc-driver-libvirt` driver plugin
    * [x] actually handled by the `crc setup` command
  * [x] basic usage `crc start`
  * [x] ... note: at this point no other commands exist yet (see command roadmap #70 )
  * [x] use with `oc` (export of `kubeconfig`)

**Comment by robin-owen** [comment]
Looks like we have the `start`, `stop`, and `delete` commands at the moment -- is that correct?

**Comment by gbraad** [comment]
@robin-owen this is correct and `setup` to check and fix issues to make CRC run (note: `start` only checks before running).

**Comment by robin-owen** [comment]
I've built the binary myself and noticed that there's no `setup` command documented in `crc --help`. Is that expected at this time?

**Comment by gbraad** [comment]
I filed an issue for this: #87

**Comment by robin-owen** [comment]
We could also use general troubleshooting information.

AFAIK, the general procedure for troubleshooting is to delete the current VM via `crc delete` and retry with `crc start`. (This is assuming that `crc setup` has already been run and none of the files `crc setup` configures have been modified by the user. At the moment, this would be an advanced use case which we are not planning to document yet.)

Is there any other troubleshooting information for common issues or errors which could be encountered?

**Comment by gbraad** [comment]
After a successful `crc start`, there is a minimum of 4 minutes that you would have to wait for the cluster to start all the needed containers, operators and whatever else is needed until it settles down and can actually serve a request. Note: at the moment we do not yet read the `status` from the cluster so it is kind of a 'fire-and-forget' for now after `crc start` finished.

If the cluster is up, you can use `oc` after doing an `export KUBECONFIG=[..]/kubeconfig` or log into the console with the kubeadmin user. all this information is now in files that are extracted from the image bundle. This can be found at `~/.crc/machines/crc/.../`.

**Comment by gbraad** [comment]
As discussed with @rowen, commands like `crc config set` is now considered to be advanced usage, and likely ONLY necessary to address as part of troubleshooting at this point

**Comment by gbraad** [comment]
Fixed with #109

**Comment by anjannath** [comment]
Fixed in https://github.com/code-ready/crc/commit/e8255c6e10bdbdef19e2455c3c8c0f6bfb0ba3f1
