### ISSUE TITLE
Remove hypervisor string from the validation message.

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#656]
As of now if a user provide the older version of the bundle he/she gets following error, since now our bundle follow all the hypervisor naming we should directly tell them what to use.

```
$ ./crc start -b ~/Downloads/crc_libvirt_4.1.11.crcbundle 
ERRO Error occurred: crc_libvirt_4.1.11.crcbundle bundle is not supported by this binary, you must use crc_<hypervisor>_4.1.14.crcbundle 
```

**Comment by cfergeau** [comment]
On macos and windows, both native and vbox hypervisors can be used. I agree we could make this message better as most of the time we'll have a bundle embedded in the binary and can recommend using this somehow.

**Comment by praveenkumar** [comment]
@cfergeau right, not high priority but in the future we can look it and see how it can be done.

**Comment by cfergeau** [comment]
Now that vbox is gone, much easier to do ;)
