### ISSUE TITLE
Integration tests - allow to run only one feature file

### ISSUE THREAD

**Issue by tsedmik** [code-ready/crc#657]
As far as I know, there is no solution how we can run only one feature file (not all of them)

**Comment by tsedmik** [comment]
Fro example: I want to run only basic integration tests for Windows --> `--godog.tags="@basic && @windows"`

**Comment by jsliacan** [comment]
Exactly @tsedmik , the most stylish solution is what you wrote. But there's no need to add `@platform` tag as that's already there by default [Makefile L123](https://github.com/code-ready/crc/blob/9b0cc45ba9cd50311f34d5f7fa0222e09ee42c7e/Makefile#L123)
```
integration: GODOG_OPTS = --godog.tags=$(GOOS)
```
Any solution is going to require tags in the feature files themselves. Many tags degrade readability so I keep it at minimum (no temporary tags in feature files at this point). When I want to run just one feature file (or 1 scenario), I place some `@onlythis` tag there and add it to GODOG_OPTS var. I think I only did it once, and it worked.

What do you think should be done about this? @cfergeau also came across this inconvenience recently.

**Comment by tsedmik** [comment]
I'm not sure whether passing another tag like `@onlythis` to `GODOG_OPTS` will work. You will override the value `--godog.tags=$(GOOS)`.

**Comment by tsedmik** [comment]
Resolved with #659
