### ISSUE TITLE
Generate documentation

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#66]
We need to generate documentation from the source files. We prefer to use a container for this, however... what will this look like? What source format will be used? Etc.

I suspect we will go with AsciiDoc again, but hopefully with a lightweight container that can be generated easily (container pipeline?)

**Comment by robin-owen** [comment]
Just to confirm, yes, we will be using AsciiDoc (as much as reasonably possible) for markup in the documentation.

**Comment by gbraad** [comment]
I got a basic container now that runs `asciidoctor` and uses `rubygem-coderay` for generating the HTML5 output: https://github.com/gbraad/dockerfile-asciidoctor-centos Not sure what else is needed.

**Comment by gbraad** [comment]
Fixed with #109
