### ISSUE TITLE
Can crc be run in a CentOS box on VirtualBox?

### ISSUE THREAD

**Issue by morningspace** [code-ready/crc#672]
### General information

  * OS: macOS
  * Hypervisor: VirtualBox
  * Did you run `crc setup` before starting it (Yes)?

## CRC version
```bash
# Put the output of `crc version`
$ crc version
version: 1.0.0-beta.5+f2aa58c
OpenShift version: 4.1.14 (embedded in binary)
```
  
## CRC status
```bash
# Put the output of `crc status`
$ crc status
ERRO Error occurred: Machine "crc" does not exist. Use "crc start" to add a new one.
```

## CRC config
```bash
# Put the output of `crc config view`
```

## Host Operating System
```bash
# put the output of `sw_vers` in case of Mac
sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G3025
```

### Steps to reproduce

  1. Launch a CentOS box using vagrant + virtualbox
  2. Go into CentOS box and run crc setup
  3. It failed and report:
```
INFO Checking if running as non-root              
INFO Caching oc binary                            
INFO Setting up virtualization                    
FATA You need to enable virtualization in BIOS    
```

Still new to crc, but just would like to know if that's possible to run crc in a CentOS box running on VirtualBox.

**Comment by cfergeau** [comment]
> FATA You need to enable virtualization in BIOS    
For this error, you'd need to enable link:https://docs.oracle.com/cd/E97728_01/F12469/html/nested-virt.html[nested virtualization] in virtualbox

**Comment by cfergeau** [comment]
Closing as this issue is not something crc can/should fix

**Comment by morningspace** [comment]
@cfergeau Thanks for your quick response! So, it appears that I need to find other ways as it's said the nested virtualization is only for AMD at the moment, not for Intel... while my Mac uses Intel...

**Comment by cfergeau** [comment]
We provide native macos crc binaries, as well as an unsupported virtualbox crc disk image, do you have any specific requirement to use crc  from a linux host?

**Comment by morningspace** [comment]
Hi @cfergeau I'd like to embed crc into my [lab-k8s-playground](https://github.com/morningspace/lab-k8s-playground), and it's supposed to support mult-OS, such as MacOS, Ubuntu, CentOS, RHEL. So, I'd like to automate, test, verify crc, and other apps deployment such as Istio, API Connect on top of crc on CentOS... Also, our CI/CD env is linux-based...

While I don't have CentOS at hand, that's why I was trying to install it using VirtualBox:-)

**Comment by snowch** [comment]
> We provide native macos crc binaries, as well as an unsupported virtualbox crc disk image, do you have any specific requirement to use crc from a linux host?

After a few days of failing to run crc on my mac, a self contained virtualbox image would have been a nice solution.

**Comment by morningspace** [comment]
@snowch According to #838, it appears the virtualbox support is deprecated and removed from the official crc distributions.
