### ISSUE TITLE
Change crc log file permission before uploading to centos CI artifact server

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#674]
Right now the `crc.log` file have `0600` as file permission but when we upload same file to the centos CI artifact server then this file get `permission denied` during browsing http://artifacts.ci.centos.org/minishift/crc/pr/670/crc_2019_09_30_10_54_11.log

We need to change the permission of that file `0644` before upload.

**Comment by anjannath** [comment]
Fixed in https://github.com/code-ready/crc/commit/7f501486b434b5afec12a5ce2e048e45539ae4f9
