### ISSUE TITLE
Is there a reason why 'crc status' returns exit code 1 when not started/stopped

### ISSUE THREAD

**Issue by odockal** [code-ready/crc#678]
### General information
I have called crc setup and then I would expect crc status to inform it is not run, but this should not be considered error, should it?

  * OS: any
  * Hypervisor: any
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```
version: 1.0.0-rc.0+34371d3
```
  
## CRC status
```
ERRO Error occurred: Machine "crc" does not exist. Use "crc start" to add a new one. 
```

### Steps to reproduce

  1. 
  2. 
  3. 
  4. 

### Logs

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by cardil** [comment]
In my opinion it should return `!= 0`. This behavior is described in System V services status standard. It then was incorporated to SystemD. Using this exit status other scripts can know if given service is started or not (without needing to parse console output).

It is good practice to follow those standards on this.

Here is report from my SystemD:

```
$ systemctl status io.podman.service
● io.podman.service - Podman Remote API Service
   Loaded: loaded (/usr/lib/systemd/system/io.podman.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:podman-varlink(1)
$ echo $?
3
$ systemctl status libvirtd.service
● libvirtd.service - Virtualization daemon
   Loaded: loaded (/lib/systemd/system/libvirtd.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-09-28 23:01:08 CEST; 2 days ago
     Docs: man:libvirtd(8)
           https://libvirt.org
 Main PID: 2204 (libvirtd)
    Tasks: 22 (limit: 32768)
   CGroup: /system.slice/libvirtd.service
           ├─2204 /usr/sbin/libvirtd
           ├─3649 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/lib/lib
           ├─3650 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/lib/lib
           ├─3818 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/crc.conf --leasefile-ro --dhcp-script=/usr/lib/libvirt
           └─3819 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/crc.conf --leasefile-ro --dhcp-script=/usr/lib/libvirt

paź 01 13:46:39 ksuszynski-gs70 dnsmasq-dhcp[3818]: DHCPDISCOVER(crc) 52:fd:fc:07:21:82
$ echo $?
0
```

**Comment by gbraad** [comment]
I am confused about the suggestion... the title suggests different from the explaination. you would like to have a return code other than `0` when there is no VM (or not started). Right?

**Comment by odockal** [comment]
You are right, It is not precise definition, though. I was hoping in always return code 0 as you are trying to find out the status. Which could be one of X states it is in [not initialized, stopped, started for example]. It should not return any other value unless command itself thrown an error for some reason. That was the request about. 

But @cardil brought quite good argument about why is it the way it is now. I cannot argue with it.
