### ISSUE TITLE
`crc config view` no longer shows default values

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#684]
This is an intended side-effect of `Issue #518: config: Only return changed keys from AllConfigs()` but I'm no longer sure it's a good thing, as this prevents the user from seeing the default number of cpus/memory/... which is going to be used (remove ~/.crc/crc.json first for testing).
Probably better to revert this for now, and to add an integration check to detect this.

**Comment by praveenkumar** [comment]
This is the intended behavior, I like it that way. `crc config view` only show the details which user set not the default one.

**Comment by praveenkumar** [comment]
Closing it with wontfix label.
