### ISSUE TITLE
Registry not accessible

### ISSUE THREAD

**Issue by deevya2000** [code-ready/crc#687]
I have setup CRC on CentOS VM by following the instructions. But I am not able to create any applications from the UI as the build pods are failing.

Events:
  Type     Reason     Age   From                         Message
  ----     ------     ----  ----                         -------
  Normal   Scheduled  37s   default-scheduler            Successfully assigned demo/cakephp-ex-gitphp-2-build to crc-chc9n-master-0
  Normal   Pulling    27s   kubelet, crc-chc9n-master-0  Pulling image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:1b276d8c89d5553213211d75efc5f4455fe1855c0a31a2dc5a685db69d7480ce"
  Warning  Failed     7s    kubelet, crc-chc9n-master-0  Failed to pull image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:1b276d8c89d5553213211d75efc5f4455fe1855c0a31a2dc5a685db69d7480ce": rpc error: code = Unknown desc = pinging docker registry returned: Get https://quay.io/v2/: net/http: TLS handshake timeout
  Warning  Failed     7s    kubelet, crc-chc9n-master-0  Error: ErrImagePull
  Normal   BackOff    4s    kubelet, crc-chc9n-master-0  Back-off pulling image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:1b276d8c89d5553213211d75efc5f4455fe1855c0a31a2dc5a685db69d7480ce"
  Warning  Failed     4s    kubelet, crc-chc9n-master-0  Error: ImagePullBackOff

However I am able to curl to https://quay.io/v2/ from my terminal

**Comment by praveenkumar** [comment]
@deevya2000 this might be the problem that VM doesn't have access to external network, can you provide some more details around which host os you have which version of crc, we have a bug template but looks like you didn't use it.

**Comment by praveenkumar** [comment]
@deevya2000 Since we didn't get any update from some time now, let us know if that still an issue for you. Closing it as of now.
