### ISSUE TITLE
Rewrite diskspace wiki page in a more generic way (FAQ)

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#690]
the current page https://github.com/code-ready/crc/wiki/Disk-space-issue-with-beta-5-release is written for beta5, and therefore includes a static password and a node reference that does not exist in newer deployments. we should rewrite this in a more generic way that gets the kubeadmin password and the master node identity. this way we can include it as a FAQ entry.

**Comment by gbraad** [comment]
For linux it is easy to also describe how to enlarge the containing disk image, but how about Windows and macOS? We might need to direct them to qemu-img tooling for macOS and the management interface/powershell on Windows.

**Comment by gbraad** [comment]
See https://github.com/code-ready/crc/issues/127#issuecomment-493429805 for more info. This needs to be documented in some form before we can add a command.

**Comment by cfergeau** [comment]
Regarding disk resizing, I don't know how to do it on OS where virt-resize don't run. Maybe through qemu-img and running some commands in the running VM?
