### ISSUE TITLE
[BUG] CRC failed to restart when use virtualbox

### ISSUE THREAD

**Issue by morningspace** [code-ready/crc#691]
CRC failed to restart when use virtualbox on MacOS. When run crc start for the first time, it works, but after I run crc down then start, it failed at the step verifying validity of the cluster certificates, with below error message:
ERRO Error occurred: Error getting the IP: Could not find matching IP for MAC address 08002746a861

### General information

  * OS: macOS
  * Hypervisor: VirtualBox
  * Did you run `crc setup` before starting it (Yes)?

## CRC version
```bash
# Put `crc version` output here
version: 1.0.0-rc.0+34371d3
OpenShift version: 4.2.0-0.nightly-2019-09-26-192831 (embedded in binary)
```
  
## CRC status
```bash
# Put `crc status` output here
ERRO Error occurred: The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port?
 - exit status 1 
```

## CRC config
```bash
# Put `crc config view` output here
- cpus                                  : 4
- memory                                : 8192
```

## Host Operating System
```bash
# put the output of `sw_vers` in case of Mac
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G3025
```

### Steps to reproduce

  1. crc setup
  2. crc start --vm-driver virtualbox --bundle crc_virtualbox_4.2.0-0.nightly-2019-09-26-192831.crcbundle
  3. crc stop
  4. crc start --vm-driver virtualbox --bundle crc_virtualbox_4.2.0-0.nightly-2019-09-26-192831.crcbundle
```
INFO Checking if running as non-root              
INFO Checking if oc binary is cached              
INFO Checking if VirtualBox is Installed          
INFO Checking file permissions for /etc/resolver/testing 
INFO Checking file permissions for /etc/hosts     
INFO Starting CodeReady Containers VM for OpenShift 4.2.0-0.nightly-2019-09-26-192831... 
INFO Verifying validity of the cluster certificates ... 
ERRO Error occurred: Error getting the IP: Could not find matching IP for MAC address 08002746a861 
```

### Expected
Restart success

### Actual
Restart fail after run `crc stop`, then `crc start`

### Logs

https://gist.github.com/morningspace/af11f1af69c75001472a58a6eabe1ed2

**Comment by gbraad** [comment]
Virtualbox is not a supported hypervisor. We offer a driver in case an alternative solution is needed. At te moment we can not assign bandwidth to work on issues related to this driver. If you can help pinpointing where this happens, that would be really helpful.

**Comment by milan496** [comment]
I tried a workaround for this a it works for me:
crc stop
cd ~/.crc/cache/*
mv id_rsa_crc id_rsa_crc.ori
cp -p ../../machines/crc/id_rsa ./id_rsa_crc
# now you can restart
crc start -d virtualbox -b <path2virtualboxbundle>

**Comment by gbraad** [comment]
Aha, we have dealt with the shared ssh key, which now on start gets replaced, and this might not have been handled (at all or incorrectly) in the vbox driver.

@praveenkumar WDYT?

**Comment by gbraad** [comment]
this might be related to the following change: https://github.com/code-ready/machine/commit/f976ca771389098ad50d005b2f41808c9ebd3f3c

**Comment by morningspace** [comment]
Just quick update... I've verified the workaround mentioned above did work... thanks @milan496 
I will try to read the code and see if it's easy to fix when I have time :-)

**Comment by gbraad** [comment]
With #838 VirtualBox support will be removed
