### ISSUE TITLE
Add basic pre-flight checks and setup (macOS / VirtualBox)

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#7]
Depends on: #9 

Which checks are needed for macOS (VB);

  * [x] virtualbox installed
  * [x] virtualbox usable
  * ... and so on

**Comment by gbraad** [comment]
This needs a tighter integration between the pre-flight check failure and the setup code (for each of the steps).

**Comment by gbraad** [comment]
* Hypervisor setup: Hyperkit

**Comment by anjannath** [comment]
Checks needed for macOS; hyperkit:

* Is hyperkit binary present on path
* Is the `docker-machine-driver-hyperkit` present on path
* Are the permissions for the driver binary properly set

/cc @praveenkumar

**Comment by anjannath** [comment]
> make sure we can detect improperly uninstalled VirtualBox

@gbraad I thought this was only problematic for the `xhyve` driver, is that not the case?

**Comment by gbraad** [comment]
We will work on this driver after #6 is done

**Comment by anjannath** [comment]
Done via #59
