### ISSUE TITLE
Cannot build application/pod from catalog

### ISSUE THREAD

**Issue by milan496** [code-ready/crc#701]
### General information

  * OS:  macOS 
  * Hypervisor:  hyperkit
  * Did you run `crc setup` before starting it (Yes/No)?Yes

## CRC version
```bash
version: 1.0.0-rc.0+34371d3
OpenShift version: 4.2.0-0.nightly-2019-09-26-192831 (embedded in binary)
  
## CRC status
```bash
# Put the output of `crc status`
crc status
CRC VM:          Running
OpenShift:       Running (v4.2.0-0.nightly-2019-09-26-192831)
Disk Usage:      14.13GB of 32.2GB (Inside the CRC VM)
Cache Usage:     11.71GB

## CRC config
```bash
# Put the output of `crc config view`
nothing displayed

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G95

### Steps to reproduce

  1. crc start --log-level debug
  2. crc console
  3. on webconsole
select project
tab worloads
click add other content
from catalog
choose apache httpd
create application
try from sample plus check route
create
click on pod name
pod info shows "Build  #1 is pending
Builds>build details tab logs - log is loading  message for ever
  4. 
ssh -q -i ~/.crc/machines/crc/id_rsa core@192.168.64.7
ping www.google.com # now answer from ping
### Expected


### Actual


### Logs

You can start crc with `crc start --log-level debug` to collect logs.
-- in crc.log there are repated messages:
time="2019-10-09T15:18:27+02:00" level=debug msg="Unexpected operator status for insights: Disabled"
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
@milan496 `ping www.google.com # now answer from ping` you mean `not answer from ping` ?

**Comment by milan496** [comment]
> @milan496 `ping www.google.com # now answer from ping` you mean `not answer from ping` ?

Yes. Not answer from Ping

**Comment by praveenkumar** [comment]
@milan496 that mean the dns is broken in the VM and not able to route the traffic to outside world, by any chance you are on the VPN? if not can you try to delete and start again?

**Comment by milan496** [comment]
> @milan496 that mean the dns is broken in the VM and not able to route the traffic to outside world, by any chance you are on the VPN? if not can you try to delete and start again?

Hello, yes yesterday I was on VPN, today I tested not being on VPN, first on MacOS using virtual box driver - and it was success - I was able to deploy simple Apache application and I got answers from pinging to www.google.com and other internet url from inside crc VM. Then I installed arc using HyperKit - and in this configuration I still have problem to ping from inside arc VM to google.com:
Milans-MBP:crc-macos-1.0.0-rc.0-amd64 milanrafaj$ crc start -p ../pull-secret
INFO Checking if running as non-root              
INFO Checking if oc binary is cached              
INFO Checking if HyperKit is installed            
INFO Checking if crc-driver-hyperkit is installed 
INFO Checking file permissions for /etc/resolver/testing 
INFO Checking file permissions for /etc/hosts     
INFO Loading bundle: crc_hyperkit_4.2.0-0.nightly-2019-09-26-192831.crcbundle ... 
INFO Creating CodeReady Containers VM for OpenShift 4.2.0-0.nightly-2019-09-26-192831... 
INFO Verifying validity of the cluster certificates ... 
INFO Restarting the host network                  
INFO Check internal and public dns query ...      
INFO Copying kubeconfig file to instance dir ...  
INFO Adding user's pull secret and cluster ID ... 
INFO Starting OpenShift cluster ... [waiting 3m]  
INFO                                              
INFO To access the cluster, first set up your environment by following 'crc oc-env' instructions 
INFO Then you can access it by running 'oc login -u developer -p developer https://api.crc.testing:6443' 
INFO To login as an admin, username is 'kubeadmin' and password is F44En-Xau6V-jQuyb-yuMXB 
INFO                                              
INFO You can now run 'crc console' and use these credentials to access the OpenShift web console 
CodeReady Containers instance is running
Milans-MBP:crc-macos-1.0.0-rc.0-amd64 milanrafaj$ ssh -q -i ~/.crc/machines/crc/id_rsa core@192.168.64.9
The authenticity of host '192.168.64.9 (192.168.64.9)' can't be established.
ECDSA key fingerprint is SHA256:zOtYrk7pHgAMf0kilRnMgyhA3BHNYfKxsKEfAKXZOqQ.
Are you sure you want to continue connecting (yes/no)? yes
Red Hat Enterprise Linux CoreOS 42.80.20190925.2
WARNING: Direct SSH access to machines is not recommended.

---
[core@crc-chc9n-master-0 ~]$ ping 192.168.64.9  ## trying local its
PING 192.168.64.9 (192.168.64.9) 56(84) bytes of data.
64 bytes from 192.168.64.9: icmp_seq=1 ttl=64 time=0.138 ms
64 bytes from 192.168.64.9: icmp_seq=2 ttl=64 time=0.052 ms
[core@crc-chc9n-master-0 ~]$ ping www.google.com  ### now trying to access google.com
PING www.google.com (172.217.23.228) 56(84) bytes of data.
^C
--- www.google.com ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 31ms

[core@crc-chc9n-master-0 ~]$ ping 172.217.23.228
PING 172.217.23.228 (172.217.23.228) 56(84) bytes of data.
172.217.23.228^C
--- 172.217.23.228 ping statistics ---
6 packets transmitted, 0 received, 100% packet loss, time 129ms

[core@crc-chc9n-master-0 ~]$ exit
logout
Milans-MBP:crc-macos-1.0.0-rc.0-amd64 milanrafaj$ crc status
CRC VM:          Running
OpenShift:       Running (v4.2.0-0.nightly-2019-09-26-192831)
Disk Usage:      13.05GB of 32.2GB (Inside the CRC VM)
Cache Usage:     11.71GB

**Comment by milan496** [comment]
I have an update - reinstall arc, not being on VPN, ping from inside still not working but curl "http://www.google.com" returned response therefore I open crc console and install simple Apache http in new projects and now it succeeded. So issued was solved by avoiding run crc on VPN.

**Comment by praveenkumar** [comment]
@milan496 There is still some work need to be done to have the `vpn` to be worked with crc. Good to know that it works for you by avoiding run of crc on vpn.

**Comment by praveenkumar** [comment]
I am going to close this issue since we have plan to document it meanwhile https://github.com/code-ready/crc/issues/384
