### ISSUE TITLE
Clarification: Each released crc binary expires after 30 days

### ISSUE THREAD

**Issue by heiko-braun** [code-ready/crc#702]
This get's in the way for people who actively use CRC as a development tool. Here often customization are done, that need to be restored every 30 days. 

- Is there any way to prevent the use of certificates or rely on long lasting ones?
- What are the certs used for?

**Comment by cfergeau** [comment]
The certs are used to encryt external and internal cluster communication (eg communication from oc to the cluster, or communication between the various operators/services), and unfortunately, we cannot easily ask openshift to use longer ones.

**Comment by gbraad** [comment]
This is related to #11. Please comment on that issue instead

**Comment by gbraad** [comment]
And yes, we share your point of view and are continually discussing this ... even late last night, hoping to make a development profile possible that might extend or make cert rotation unnecessary. This will be done as part of the OpenShift enhancement process.
