### ISSUE TITLE
[BUG] Cannot instantiate postgresql 9.6 instance

### ISSUE THREAD

**Issue by phantomjinx** [code-ready/crc#706]
### General information

  * OS: Linux
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
# Put `crc version` output here
version: 1.0.0-rc.0+34371d3
OpenShift version: 4.2.0-0.nightly-2019-09-26-192831 (embedded in binary)
```
  
## CRC status
```bash
# Put `crc status` output here
CRC VM:          Running
OpenShift:       Running (v4.2.0-0.nightly-2019-09-26-192831)
Disk Usage:      17.83GB of 32.2GB (Inside the CRC VM)
Cache Usage:     15.95GB
Cache Directory: /home/phantomjinx/.crc/cache
```

## CRC config
```bash
# Put `crc config view` output here
- cpus                                  : 4
- memory                                : 12288
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
NAME=Fedora
VERSION="29 (Twenty Nine)"
ID=fedora
VERSION_ID=29
VERSION_CODENAME=""
PLATFORM_ID="platform:f29"
PRETTY_NAME="Fedora 29 (Twenty Nine)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:29"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f29/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=29
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=29
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"

# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```

### Steps to reproduce

  1. Create project
  2. Open console, go to +Add & select Database
  3. Select Postgresql
  4. Click Instantiate Template

### Expected
New instance of postgresql database pod should be running

### Actual
- Pod fails to start and is listed and 'unschedulable'
- Clicking on pod's events show '0/1 nodes are available: 1 Insufficient memory.'
- Single master node reports resources as:
```
status:
  capacity:
    cpu: '4'
    hugepages-1Gi: '0'
    hugepages-2Mi: '0'
    memory: 7778264Ki
    pods: '250'
  allocatable:
    cpu: 3500m
    hugepages-1Gi: '0'
    hugepages-2Mi: '0'
    memory: 7163864Ki
    pods: '250'
```

### Logs
Nothing in logs pertaining to postgresql or 'insufficent memory'

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by cfergeau** [comment]
Can you try `crc delete && crc config set memory 16000 && crc start` and try again to create your postgresql instance?

**Comment by phantomjinx** [comment]
That seemed to do the trick. Curious why 12GB was not enough memory, especially as [docs](https://code-ready.github.io/crc/) require only 8GB?

**Comment by praveenkumar** [comment]
@phantomjinx so I also tried something below and able to make it work with 8GB only, did you also have other workloads on that cluster?

Postgresql template suppose to have maximum memory limit `512Mi` and this amount of memory should be available by default until you have other workload is running.
```
$ oc get template  postgresql-persistent -n openshift -o yaml | grep -n2 -i memory
135-          resources:
136-            limits:
137:              memory: ${MEMORY_LIMIT}
138-          securityContext:
139-            capabilities: {}
--
163-  status: {}
164-parameters:
165:- description: Maximum amount of memory the container can use.
166:  displayName: Memory Limit
167:  name: MEMORY_LIMIT
168-  required: true
169-  value: 512Mi

$ oc new-project testdb
$ oc new-app postgresql-persistent
$ oc get all
NAME                      READY   STATUS      RESTARTS   AGE
pod/postgresql-1-deploy   0/1     Completed   0          46m
pod/postgresql-1-v9mmx    1/1     Running     0          45m

NAME                                 DESIRED   CURRENT   READY   AGE
replicationcontroller/postgresql-1   1         1         1       46m

NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/postgresql   ClusterIP   172.30.46.41   <none>        5432/TCP   46m

NAME                                            REVISION   DESIRED   CURRENT   TRIGGERED BY
deploymentconfig.apps.openshift.io/postgresql   1          1         1         config,image(postgresql:10)

$ oc get pods postgresql-1-v9mmx -o=json | jq '.spec.containers[0].resources'
{
  "limits": {
    "memory": "512Mi"
  },
  "requests": {
    "memory": "512Mi"
  }
}
```

**Comment by gbraad** [comment]
@praveenkumar can you confirm the `DiskUsage` on your end with `crc status` ?

**Comment by praveenkumar** [comment]
@gbraad Disk space is enough for running only the posgresql container.
```
$ ./crc status
CRC VM:          Running
OpenShift:       Running (v4.2.0-rc.1)
Disk Usage:      11.88GB of 32.2GB (Inside the CRC VM)
Cache Usage:     10.95GB
Cache Directory: /home/prkumar/.crc/cache
```

**Comment by gbraad** [comment]
> Disk Usage:      17.83GB of 32.2GB (Inside the CRC VM)

> Disk Usage:      11.88GB of 32.2GB (Inside the CRC VM)

The reporter surely had more running or stored inside the VM.

**Comment by gbraad** [comment]
@phantomjinx please describe the other workload or images that might be there and after this can you run the test on a new CRC instance? (removing the previous one)

**Comment by phantomjinx** [comment]
Originally I had begun to install syndesis which has
- syndesis-db (based on image of postgresql)
- oauth-proxy
- prometheus
- syndesis-operator

So naturally, that failed to bring up the syndesis-db due to postgresql
Tried to bring up postgesql 9.6 image on its own & that failed
Cleared out the project several times and tried postgresql on its own & failed
Deleted crc entirely and upped mem to 16GB & works
Syndesis is not big & shkuld no way have resulted in insufficient memory especially when nothing else is running.
Maybe crc did not like the 12GB memoey setting?
Wonder if (this)[https://github.com/kubernetes/kubernetes/issues/45237] might have had a bearing?

**Comment by gbraad** [comment]
Syndesis runs prometheus which is know to need more than the default 8GB assignment.

So you hadn't tried Postgresql by itself on a new instance of CRC with the default assignment of 8GB of memory, right? 

The issue you refer to is from a long time ago. If so, this would certainly have been reported more than once.

**Comment by phantomjinx** [comment]
That is does but having installed evrrything now with 16GB of memory, everything comes up fine.
Just to higlight:
I never ran crc with the default 8GB. I ran into problems with 12GB.
I deleted everything in the project and ran only postgresql & it still would not execute.



On 11 October 2019 16:20:10 BST, Gerard Braad <notifications@github.com> wrote:
>Syndesis runs prometheus which is know to need more than the default
>8GB assignment.
>
>So you hadn't tried Postgresql by itself on a new instance of CRC with
>the default assignment of 8GB of memory, right? 
>
>The issue you refer to is from a long time ago. If so, this would
>certainly have been reported more than once.
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/code-ready/crc/issues/706#issuecomment-541108241

-- 
P. G. Richardson
* Ty-Carreg Barn, Penyrheol, Pontypool, Torfaen. UK
* 01495 762483
* p.g.richardson@phantomjinx.co.uk

**Comment by gbraad** [comment]
> I deleted everything in the project and ran only postgresql & it still would not execute.

Not sure about what remained behind or caused the scheduler to not see the freed resources. This is more of an issue with OpenShift itself and would appreciate if you reported it there also. 

Not sure why, but we are able to schedule postgresql with 8GB :-/

**Comment by gbraad** [comment]
I will mark the issue as closed as you are able to run the actual container,

Resources might be contrained, but this is documented on how to solve and also discussed in other issues to see what can be done to lower the memory usage, however these involve discussions with the OpenShift team.
