### ISSUE TITLE
RFE: Directly provide environment setting instructions

### ISSUE THREAD

**Issue by zeenix** [code-ready/crc#708]
On successfully cluster creation `crc` says:

```
INFO To access the cluster, first set up your environment by following 'crc oc-env' instructions 
```

which is very nice but I think it would be better if we directly provided the instructions instead of asking to run a command.

**Comment by gbraad** [comment]
>  it would be better if we directly provided the instructions

Not sure what you mean. We 'provide te instructions' to run a command. We can not alter the environment settings, since this is perhaps, from experience, something that people wanna run in a separate prompt/terminal or happens by the tooling, like the adapter.

**Comment by cfergeau** [comment]
Since `oc-env` is a one line "export PATH=...", I think Zeeshan was suggesting we can mention this one-liner at the end of `crc start` rather than adding an extra step.
With https://github.com/code-ready/crc/issues/887 solved, in some setups `crc oc-env` will no longer be a one-liner.

**Comment by gbraad** [comment]
Can you please clarify the issue? is this still needed?

**Comment by cfergeau** [comment]
This issue is still about https://github.com/code-ready/crc/issues/708#issuecomment-566441108
Since now we're also setting the proxy environment when a proxy is enabled, `oc-env` is no longer always a one-liner, so this issue is less relevant now.
