### ISSUE TITLE
The messages from the crc CLI can be worded better

### ISSUE THREAD

**Issue by syedriko** [code-ready/crc#714]
I would like to propose improvements in style and readability of the messages produced by the crc CLI.

### General information

  * OS: Fedora 30
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
$ ./crc version
version: 1.0.0-rc.0+34371d3
OpenShift version: 4.2.0-0.nightly-2019-09-26-192831 (embedded in binary)
$ 
```
  
## CRC status
```bash
$ ./crc status
ERRO Error occurred: Machine "crc" does not exist. Use "crc start" to add a new one. 
$ 
```

## CRC config
```bash
$ ./crc config view
$ 
```

## Host Operating System
```bash
$ cat /etc/os-release
NAME=Fedora
VERSION="30 (Workstation Edition)"
ID=fedora
VERSION_ID=30
VERSION_CODENAME=""
PLATFORM_ID="platform:f30"
PRETTY_NAME="Fedora 30 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:30"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f30/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=30
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=30
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
$ 
```

### Steps to reproduce
Run the crc commands, observe the produced messages

### Expected
The messages produced by the crc tool are consistent in style with the other OpenShift CLI tools and are readable

**Comment by gbraad** [comment]
> Run the crc commands, observe the produced messages
> The messages produced by the crc tool are consistent in style with the
other OpenShift CLI tools and are readable

I am sorry, but this report is unclear. Can you provide a clear example of
what you mean? The output is consistent with what we used to have with
Minishift. Surely improvements are possible, but without a clear
indication, we would not understand what you consider is inconsistent with
'other OpenShift CLI tools'.

**Comment by gbraad** [comment]
Please make sure that fixes that aren't related to the issue (CLI output) are is a separate commit, such as Makefile and CONTRIBUTING.adoc changes. However, the CONTRIBUTING is not a grammatical issue, but a passive voice.

**Comment by gbraad** [comment]
@syedriko Thanks for the suggestions... We will have to discuss what to do, as we officially passed our code-freeze, but also need to have them verified with the documentation; @robin-owen.

@code-ready/crc-devel Please have a look and confirm or request changes ASAP.

**Comment by syedriko** [comment]
Here's an example. oc --help describes commands with the plain verb form or a noun, capitalized, with no trailing period:
```
$ ~/.crc/bin/oc --help
...
Basic Commands:
  login           Log in to a server
  new-project     Request a new project
  new-app         Create a new application
  status          Show an overview of the current project
  project         Switch to another project
  projects        Display existing projects
  explain         Documentation of resources
```

There's no such consistency with crc:
```
$ ./crc --help
...
Available Commands:
  config      Modifies crc configuration properties.
  console     Opens or displays the OpenShift Web Console URL.
  delete      Delete cluster
  help        Help about any command
  ip          Get IP of the instance
  oc-env      Sets the path of the 'oc' binary.
  setup       setup hypervisor
  start       start cluster
  status      Display status of the cluster
  stop        Stop cluster
  version     Get CodeReady Container version.
```

**Comment by syedriko** [comment]
Another example:

Present behavior:
```
$ ./crc config get memory
Config property 'memory' does not exist
$ 

$ ./crc config get foo
Config property 'foo' does not exist
$ 
```
There's no diferency between known and unknown configuration properties. It is not clear if foo was not previously set or there's no such configuration property in the first place. The proposed PR changes this to
```
$ crc config get memory
Configuration property 'memory' is not set
$ crc config get foo
crc does not understand configuration property 'foo'
$ 
```
which arguably explains things better.

**Comment by syedriko** [comment]
Another example, this time on validation of configuration settings.
```
$ ./crc config set memory 100
ERRO Error occurred: Memory required >=8192       
Config value is invalid: 100, Expected: Memory required >=8192
$ 
```
The proposed PR changes this to

```
[syedriko@localhost crc]$ crc config set memory 100
ERRO required memory in MiB >= 8192               
Value '100' for configuration property 'memory' is invalid, reason: required memory in MiB >= 8192
[syedriko@localhost crc]$ 
```
, which IMO reads better. It would be even better to get rid of the

```
ERRO required memory in MiB >= 8192
```
log message as it looks odd here, but there're other situations, such as

```
$ crc start -d foo
ERRO Unsupported driver: foo, use '--vm-driver' option to provide a supported driver [libvirt] 
$ 
```

where these are the only error messages produced.

**Comment by syedriko** [comment]
Handling of a missing configuration property value:

Presently:

```
$ ./crc config set memory
Please provide a configuration property and value to set
$ 
```

The proposed change tells the user exactly what to do:
```
$ crc config set memory
Please provide a configuration property and its value as in 'crc config set KEY VALUE'
$ 
```

**Comment by syedriko** [comment]
Presently:

```
Error Writing config to file %s
```

Proposed change fixes capitalization, removes jargon and adds delimiters around the file name to make it clear what it is, since there's a good chance this message will be seen when an odd value is specified for the config file name.
 
```
Error writing configuration to file '%s'
```

**Comment by syedriko** [comment]
Presently:
```
Failed internal dns query
...
Failed Public dns query
```

Suggested change:
```
Failed internal DNS query:
...
Failed public DNS query:
```

DNS is a well established initialism.

**Comment by syedriko** [comment]
Presently:
```
No new version available, latest version at mirror is %s
```
A user wouldn't know what mirror this is.

**Comment by gbraad** [comment]
We had spent time on the pre-flights, but not generic messages. So in
short it was not really aligning messages with other CLI tools, but
more a consistent look and feel like capitalization, word choice, etc.

On Mon, Oct 14, 2019 at 10:26 AM Sergey Yedrikov
<notifications@github.com> wrote:
>
> Presently:
>
> No new version available, latest version at mirror is %s
>
> A user wouldn't know what mirror this is.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by gbraad** [comment]
'at mirror'is unnecessary information. we should redirect the user to
the landing page if possible.

On Mon, Oct 14, 2019 at 11:24 AM Gerard Braad <me@gbraad.nl> wrote:
>
> We had spent time on the pre-flights, but not generic messages. So in
> short it was not really aligning messages with other CLI tools, but
> more a consistent look and feel like capitalization, word choice, etc.
>
> On Mon, Oct 14, 2019 at 10:26 AM Sergey Yedrikov
> <notifications@github.com> wrote:
> >
> > Presently:
> >
> > No new version available, latest version at mirror is %s
> >
> > A user wouldn't know what mirror this is.
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
>
>
>
> --
>
>    Gerard Braad | http://gbraad.nl
>    [ Doing Open Source Matters ]



-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]
