### ISSUE TITLE
dashboard reports wrong free/used cluster memory and storage

### ISSUE THREAD

**Issue by rbaumgar** [code-ready/crc#725]
### General information

  * OS: Linux 
  * Hypervisor: KVM 
  * Did you run `crc setup` before starting it (Yes)?

## CRC version
```bash
version: 1.0.0-rc.0+34371d3
OpenShift version: 4.2.0-0.nightly-2019-09-26-192831 (embedded in binary)
```
  
## CRC status
```bash
CRC VM:          Running
OpenShift:       Stopped
Disk Usage:      15.28GB of 32.2GB (Inside the CRC VM)
Cache Usage:     31.01GB
Cache Directory: /home/rbaumgar/.crc/cache
```

## CRC config
```bash
CRC VM:          Running
OpenShift:       Stopped
Disk Usage:      15.28GB of 32.2GB (Inside the CRC VM)
Cache Usage:     31.01GB
Cache Directory: /home/rbaumgar/.crc/cache
```

## Host Operating System
```bash
NAME="Red Hat Enterprise Linux Workstation"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Workstation"
VARIANT_ID="workstation"
VERSION_ID="7.6"
PRETTY_NAME="Employee SKU"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:workstation"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"
```

### Steps to reproduce

  1. crc start -n 8.8.8.8 -m 12288
  2. oc login -u kubeadmin
  3. oc scale --replicas=1 statefulset --all -n openshift-monitoring; oc scale --replicas=1 deployment --all -n openshift-monitoring
  4. oc console (login with kubeadmin)

### Expected
see a dashboard with the right memory free/used...

### Actual
see a dashboard where only 600MB are used
![Screenshot from 2019-10-15 14-11-05](https://user-images.githubusercontent.com/19689547/66830891-d0c04c00-ef56-11e9-97c9-291e09107c59.png)

node is reporting 8GB are used!
![Screenshot from 2019-10-15 14-12-08](https://user-images.githubusercontent.com/19689547/66830940-e766a300-ef56-11e9-8657-701650bc4e2b.png)

### Logs
oc describe node
...
Addresses:
  InternalIP:  192.168.130.11
  Hostname:    crc-chc9n-master-0
Capacity:
 cpu:            4
 hugepages-1Gi:  0
 hugepages-2Mi:  0
 memory:         11716820Ki
 pods:           250
Allocatable:
 cpu:            3500m
 hugepages-1Gi:  0
 hugepages-2Mi:  0
 memory:         11102420Ki
 pods:           250
...
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests      Limits
  cpu                3380m (96%)   700m (20%)
  memory             9659Mi (89%)  687Mi (6%)
  ephemeral-storage  0 (0%)        0 (0%)

**Comment by rbaumgar** [comment]
Storage is also wrong, because I have only 32Gb of disk in my crc...

**Comment by anjannath** [comment]
Thanks @rbaumgar for the report, we disable monitoring operator by default, so we have not noticed this before.

Is it only with a `crc` cluster or have you also seen this on a cluster deployed with installer on AWS or from try.openshift.com?

**Comment by praveenkumar** [comment]
@rbaumgar This is not the CRC issue but mostly openshift monitoring side, better to file it to respective origin repo with the details https://github.com/openshift/cluster-monitoring-operator . Also better to check if this operator function as expected with single node cluster.

**Comment by rbaumgar** [comment]
@praveenkumar good idea. But cluuster-monitoring works at least on 4.2.0
