### ISSUE TITLE
OperatorSources errors for marketplace-operators

### ISSUE THREAD

**Issue by gmurray88** [code-ready/crc#734]
Thanks for addressing this issue #732 . If the operators have been enabled, then shouldn't the results of >"oc get opsrc -n openshift-marketplaceOperator Sources" show STATUS/MESSAGE of "Succeeded / The object has been successfully reconciled".

My results are:
"Configuring / Get https://quay.io/cnr/api/v1/packages?namespace=certified-operators: dial tcp: lookup quay.io on 172.30.0.10:53: server misbehaving"

The logs for the pod shows apparent issue resolving the package:

certified-operators-6db888f478-xlw8n    1/1     Running   3          20d
community-operators-79c9d7f5f8-rf4bt    1/1     Running   3          20d
marketplace-operator-7fd7d89795-2rjj9   1/1     Running   3          20d
redhat-operators-78f7b4b78f-trczw       1/1     Running   3          20d

C:\Users\GlennNonAdmin>oc logs certified-operators-6db888f478-xlw8n -n openshift-marketplace

time="2019-10-17T16:53:30Z" level=info msg="Using in-cluster kube client config" port=50051 type=appregistry
time="2019-10-17T16:53:37Z" level=info msg="operator source(s) specified are - [https://quay.io/cnr|certified-operators]" port=50051 type=appregistry
time="2019-10-17T16:53:37Z" level=info msg="package(s) specified are - kubeturbo-certified,storageos,insightedge-operator,instana-agent,mariadb,sematext,cic-operator,newrelic-infrastructure,synopsys-certified,percona-xtradb-cluster-operator-certified,percona-server-mongodb-operator-certified,appsody-operator-certified,federatorai-certified,twistlock-certified,couchdb-operator-certified,planetscale-certified,robin-operator,appdynamics-operator,memql-certified,portworx-certified,t8c-certified,anchore-engine,crunchy-postgres-operator,joget-openshift-operator,presto-operator,mongodb-enterprise,hazelcast-enterprise-certified,openunison-ocp-certified,kong,couchbase-enterprise-certified,sysdig-certified,nuodb-ce-certified,oneagent-certified,orca,aqua-certified,tidb-operator-certified,cpx-cic-operator,seldon-operator-certified" port=50051 type=appregistry
time="2019-10-17T16:53:37Z" level=info msg="input has been sanitized" port=50051 type=appregistry
time="2019-10-17T16:53:37Z" level=info msg="sources: [https://quay.io/cnr/certified-operators]" port=50051 type=appregistry
time="2019-10-17T16:53:37Z" level=info msg="packages: [kubeturbo-certified storageos insightedge-operator instana-agent mariadb sematext cic-operator newrelic-infrastructure synopsys-certified percona-xtradb-cluster-operator-certified percona-server-mongodb-operator-certified appsody-operator-certified federatorai-certified twistlock-certified couchdb-operator-certified planetscale-certified robin-operator appdynamics-operator memql-certified portworx-certified t8c-certified anchore-engine crunchy-postgres-operator joget-openshift-operator presto-operator mongodb-enterprise hazelcast-enterprise-certified openunison-ocp-certified kong couchbase-enterprise-certified sysdig-certified nuodb-ce-certified oneagent-certified orca aqua-certified tidb-operator-certified cpx-cic-operator seldon-operator-certified]" port=50051 type=appregistry
time="2019-10-17T16:54:07Z" level=info msg="skipping operator source due to error: https://quay.io/cnr/certified-operators" port=50051 type=appregistry
time="2019-10-17T16:54:07Z" level=info msg="the following packages could not be resolved: map[anchore-engine:false appdynamics-operator:false appsody-operator-certified:false aqua-certified:false cic-operator:false couchbase-enterprise-certified:false couchdb-operator-certified:false cpx-cic-operator:false crunchy-postgres-operator:false federatorai-certified:false hazelcast-enterprise-certified:false insightedge-operator:false instana-agent:false joget-openshift-operator:false kong:false kubeturbo-certified:false mariadb:false memql-certified:false mongodb-enterprise:false newrelic-infrastructure:false nuodb-ce-certified:false oneagent-certified:false openunison-ocp-certified:false orca:false percona-server-mongodb-operator-certified:false percona-xtradb-cluster-operator-certified:false planetscale-certified:false portworx-certified:false presto-operator:false robin-operator:false seldon-operator-certified:false sematext:false storageos:false synopsys-certified:false sysdig-certified:false t8c-certified:false tidb-operator-certified:false twistlock-certified:false]" port=50051 type=appregistry
time="2019-10-17T16:54:07Z" level=info msg="download list is empty, bailing out: [kubeturbo-certified storageos insightedge-operator instana-agent mariadb sematext cic-operator newrelic-infrastructure synopsys-certified percona-xtradb-cluster-operator-certified percona-server-mongodb-operator-certified appsody-operator-certified federatorai-certified twistlock-certified couchdb-operator-certified planetscale-certified robin-operator appdynamics-operator memql-certified portworx-certified t8c-certified anchore-engine crunchy-postgres-operator joget-openshift-operator presto-operator mongodb-enterprise hazelcast-enterprise-certified openunison-ocp-certified kong couchbase-enterprise-certified sysdig-certified nuodb-ce-certified oneagent-certified orca aqua-certified tidb-operator-certified cpx-cic-operator seldon-operator-certified]" port=50051 type=appregistry
time="2019-10-17T16:54:07Z" level=info msg="download complete - 0 repositories have been downloaded" port=50051 type=appregistry
time="2019-10-17T16:54:07Z" level=info msg="No operator manifest decoded" port=50051 type=appregistry
time="2019-10-17T16:54:07Z" level=info msg="decoded 0 flattened and 0 nested operator manifest(s)" port=50051 type=appregistry
time="2019-10-17T16:54:07Z" level=error msg="the following error(s) occurred while preparing the download list: Get https://quay.io/cnr/api/v1/packages?media_type=helm&namespace=certified-operators: dial tcp: i/o timeout" port=50051 type=appregistry
time="2019-10-17T16:54:07Z" level=error msg="stat failed on target directory[downloaded] - stat downloaded: no such file or directory" port=50051 type=appregistry
time="2019-10-17T16:54:07Z" level=warning msg="strict mode disabled" error="error loading manifests from appregistry: [error downloading manifests: Get https://quay.io/cnr/api/v1/packages?media_type=helm&namespace=certified-operators: dial tcp: i/o timeout, error loading operator manifests: stat downloaded: no such file or directory]" port=50051 type=appregistry
time="2019-10-17T16:54:07Z" level=info msg="serving registry" port=50051 type=appregistry

https://github.com/code-ready/crc/issues/732

**Comment by praveenkumar** [comment]
@gmurray88 This looks like we had issue with bundle since it is produced by using nightly bits of 4.2, please wait for till 23 Oct, we are planning to release new bits which will have fix for this issue.

**Comment by praveenkumar** [comment]
@jsliacan We need to add a integration test for it so we know it doesn't happen.
```
$ oc get opsrc -n openshift-marketplace
NAME                  TYPE          ENDPOINT              REGISTRY              DISPLAYNAME           PUBLISHER   STATUS      MESSAGE                                       AGE
certified-operators   appregistry   https://quay.io/cnr   certified-operators   Certified Operators   Red Hat     Succeeded   The object has been successfully reconciled   47h
community-operators   appregistry   https://quay.io/cnr   community-operators   Community Operators   Red Hat     Succeeded   The object has been successfully reconciled   47h
redhat-operators      appregistry   https://quay.io/cnr   redhat-operators      Red Hat Operators     Red Hat     Succeeded   The object has been successfully reconciled   47h
```

**Comment by cfergeau** [comment]
The integration test is tracked in #786 if I'm not mistaken, closing.
