### ISSUE TITLE
Cluster reports to be in error state / operators are running in degraded state

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#741]
Due to recent changes to OpenShift 4.2, the "Cluster Health" will be reported on the Dashboard / console. And looks as follows:

![image](https://user-images.githubusercontent.com/1894/67103234-519d7300-f1f7-11e9-9060-850c31977be1.png)

and reads: "Red Hat OpenShift Container Platform is in an error state". This message is incorrectly reported for CRC usage. We purposely disable the `monitoring` and `machine-config` operators to preserve resources, however OpenShift itself will therefore conclude the cluster is in a degraded or unhealthy state.

Although we have added documentation around this, a user, newcomer or familiar to CRC, might believe the server is unusable. It is therefore adviced to add a message to the end of the `crc start` output.

**Comment by bingws** [comment]
So, how add a message to the end of the crc start output?
