### ISSUE TITLE
Investigating fallback option to use goodhosts on Windows

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#757]
Like in the macOS start, we might want to investigate and use goodhosts to set entries in the `hosts` file for: `oauth`, `api` entries. This might also help those with VirtualBox [Ref: #751] without impacting us (as this does not affect the Hyper-V setup).

**Comment by cfergeau** [comment]
We do this on macos to workaround the fact that `oc` is not built natively and is not using /etc/resolver/. For this limited use case, `oauth` and `api` entries are enough.
Adding entries to /etc/hosts on Windows would be fairly limited as only a very small set of domains would be accessible.

**Comment by gbraad** [comment]
See #756, as although people 'expect' us to automate this, just documenting this might be the alternative approach. Maintaining consistency and adding entries for `apps` is hard to realise.

**Comment by gbraad** [comment]
With recent decisions we do not work on this.
