### ISSUE TITLE
Default Switch using special characters might fail start (VM creation in driver)

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#758]
In Swedish the Default Switch is named "Standardväxel" which might cause issues upon creation of the VM.

![image](https://user-images.githubusercontent.com/1894/67356432-bd336780-f58c-11e9-8ffe-976ba0c80ad9.png)

```
INFO Creating CodeReady Containers VM for OpenShift 4.2.0-0.nightly-2019-09-26-192831...

ERRO Error occurred: Error creating host: Error creating the VM. Error with pre-create check: "virtual switch \"Standardv�xel\" not found"
```

**Comment by gbraad** [comment]
Along the way I will refactor and perhaps even remove some code related to 'choosing the Virtual Switch': https://github.com/code-ready/machine/blob/0fde37b5d95b668d82659ec4aa1d60b054a08e46/drivers/hyperv/hyperv.go#L179 as the code still picks up the first one by default?

**Comment by gbraad** [comment]
Force encoding with `[Console]::OutputEncoding = [Text.Encoding]::UTF8;` for now ...

**Comment by gbraad** [comment]
@robin-owen What about documentation around this? As a known issue we can detail that this can happen. However, it is solved now and will be fixed in the next release.

**Comment by robin-owen** [comment]
@gbraad Is there a workaround for this issue other than setting the OS language to English?

**Comment by gbraad** [comment]
@robin-owen there is, in the form of a new release. this change has been merged and 'should' work.
