### ISSUE TITLE
On Windows the binary will have unexpected behaviour when run from non-WINDRIVE

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#764]
On Windows we have an issue with libmachine that causes the driver to fail when the crc executable is started from a network driver, like `H:`, `U:`, `X:`. The user would have to place the binary in a locatlon on `%WINDRIVE%`, which mostly means `C:`, like `C:\temp`, `C:\Users\[username]\Desktop\`, `C:\Applications\`, etc.

**Comment by gbraad** [comment]
@robin-owen This is a known issue

**Comment by Snackin** [comment]
👍 upvote please.

**Comment by gorantornqvist** [comment]
Guess this was never fixed...?

**Comment by squarism** [comment]
crc 1.9 seems to fill a 50gb /home.  I wonder if it just fills whatever it can.

```
INFO Creating CodeReady Containers VM for OpenShift 4.3.10...
ERRO Error creating host: Error creating the VM: Error creating machine: Error in driver during machine creation: write /home/$HOME/.crc/machines/crc/crc.tmp544243483: no space left on device
```

**Comment by praveenkumar** [comment]
@squarism it might be old bundle are part of `cache` directory, can you try to list the cache directory and try again?

```
$ crc delete --clear-cache
$ crc setup
$ crc start
```

**Comment by squarism** [comment]
The docs say 35 GB of storage space for install.  37gb is too close to this documented requirement, of course, you know, computers.  So I did some symlink tricks and it worked.  Thanks for the additional command flag example.  It took a few `setup` and `start` iterations (this seems to be normal for our team across machines) but eventually worked.
