### ISSUE TITLE
Remove the unnecessary preflight checks for linux hosts

### ISSUE THREAD

**Issue by anjannath** [code-ready/crc#77]
There are some preflight checks and setup which are not required:

1. default pool's availability and free space.
2. any others..

should be done after #63 is merged.

**Comment by gbraad** [comment]
I am still considering how to handle some of the preflight checks that are
directly related to the driver.
I believe they should be handled by the actual driver

**Comment by gbraad** [comment]
I am still considering how to handle some of the preflight checks that are directly related to the driver. I believe they should be handled by the actual driver

  * [ ] existence of the network requested
