### ISSUE TITLE
Docker login to registry fails with certificate signed by unknown authority.

### ISSUE THREAD

**Issue by sanguptaibm** [code-ready/crc#775]
### General information

  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / Hyper-V / VirtualBox / hyperkit
  * Did you run `crc setup` before starting it (Yes/No)?

## CRC version
```bash
# Put the output of `crc version`
crc version: 1.0.0+575079b
OpenShift version: 4.2.0 (embedded in binary)
  
## CRC status
```bash
# Put the output of `crc status`
CRC VM:          Running
OpenShift:       Running (v4.2.0)
Disk Usage:      18.87GB of 32.2GB (Inside the CRC VM)
Cache Usage:     9.608GB
Cache Directory: /Users/sandipgupta/.crc/cache

## CRC config
```bash
# Put the output of `crc config view`
Empty

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F203


### Steps to reproduce

oc login -u kubeadmin
oc policy add-role-to-user registry-viewer developer
oc policy add-role-to-user registry-editor developer
oc logout
oc login -u developer -p developer
docker login -u developer -p $(oc whoami -t) default-route-openshift-image-registry.apps-crc.testing

WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://default-route-openshift-image-registry.apps-crc.testing/v2/: x509: certificate signed by unknown authority

### Expected
Login Success

### Actual

WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://default-route-openshift-image-registry.apps-crc.testing/v2/: x509: certificate signed by unknown authority

### Logs

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by sanguptaibm** [comment]
After Trying various options. The below command helped resolve the issue.

oc extract secret/router-ca --keys=tls.crt -n openshift-ingress-operator
cp tls.crt /etc/docker/certs.d/default-route-openshift-image-registry.apps-crc.testing/
restart docker
docker login -u developer -p $(oc whoami -t) default-route-openshift-image-registry.apps-crc.testing
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded

**Comment by sanguptaibm** [comment]
I had another problem where oc login was giving the same X509 certificate signed by unknown authority.

The below commands helped to resolve this error also. 

oc rsh -n openshift-authentication oauth-openshift-bf85b7fc-f2r8g cat /run/secrets/kubernetes.io/serviceaccount/ca.crt > ingress-ca.crt
oc login -u username -p password https://api.example.local:6443 --certificate-authority=ingress-ca.crt
Login success

**Comment by sanguptaibm** [comment]
Hi,

I pushed the image to the Openshift registry
docker push default-route-openshift-image-registry.apps-crc.testing/test/mqadvdev

When I login to the Developer perspective of the OC Web console to deploy an image from the above internal registry, I am getting the same error on the browser. 

Pls help.



![Screenshot 2019-10-26_14-16-07-310](https://user-images.githubusercontent.com/17850970/67616873-30daac00-f7fb-11e9-95b8-b2da8e9fab04.png)

**Comment by cfergeau** [comment]
> I had another problem where oc login was giving the same X509 certificate signed by unknown authority.
> 
> The below commands helped to resolve this error also.
> 
> ```
> $ oc rsh -n openshift-authentication oauth-openshift-bf85b7fc-f2r8g 
> $ cat /run/secrets/kubernetes.io/serviceaccount/ca.crt > ingress-ca.crt
> $ oc login -u username -p password https://api.example.local:6443 --certificate-authority=ingress-ca.crt
> Login success
> ```

Is the use of `api.example.local` in that oc login command a typo in the bug report, or is this what you tried to use? crc uses `api.crc.testing`

**Comment by praveenkumar** [comment]
@sanguptaibm Also can you try following command to see if that is able to work? `image-registry.openshift-image-registry.svc` is internal service for registry which have valid certs.

```
$ oc run --image=image-registry.openshift-image-registry.svc:5000/test/mqadvdev
```

**Comment by sanguptaibm** [comment]
@praveenkumar: I had used the the https://api.crc.testing:6443.

**Comment by sanguptaibm** [comment]
> > I had another problem where oc login was giving the same X509 certificate signed by unknown authority.
> > The below commands helped to resolve this error also.
> > ```
> > $ oc rsh -n openshift-authentication oauth-openshift-bf85b7fc-f2r8g 
> > $ cat /run/secrets/kubernetes.io/serviceaccount/ca.crt > ingress-ca.crt
> > $ oc login -u username -p password https://api.example.local:6443 --certificate-authority=ingress-ca.crt
> > Login success
> > ```
> 
> Is the use of `api.example.local` in that oc login command a typo in the bug report, or is this what you tried to use? crc uses `api.crc.testing`

I had used the the https://api.crc.testing:6443.

**Comment by sanguptaibm** [comment]
> image-registry.openshift-image-registry.svc:5000

@praveenkumar : I was able to create the container successfully using the internal registry option as suggested by you. Thanks.

oc run --image=image-registry.openshift-image-registry.svc:5000/test/mqadvdev
