### ISSUE TITLE
Should 'crc start' fail when cluster does not have external connectivity?

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#778]
machine.go currently has:
```
        if queryOutput, err := dns.CheckCRCPublicDNSReachable(servicePostStartConfig); err != nil {
               logging.Warnf("Failed public DNS query: %v : %s", err, queryOutput)
        }
```

Shouldn't this issue be more critical as it's unlikely the resulting cluster is going to be functional enough?

**Comment by gbraad** [comment]
No, as when people are in an air-gapped environment, or not connected to the internet, startup should no tbe prevented.
