### ISSUE TITLE
Pulling images from registry.redhat.io that requires authentication

### ISSUE THREAD

**Issue by tqvarnst** [code-ready/crc#781]
### General information

  * OS: AFAIK ALL, but only verified on MacOS X Catalina
  * Hypervisor: AFAIK ALL, but only verifies with HyperKit
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
crc version: 1.0.0+575079b
OpenShift version: 4.2.0 (embedded in binary)
```
  
## CRC status
```bash
CRC VM:          Running
OpenShift:       Running (v4.2.0)
Disk Usage:      9.834GB of 32.2GB (Inside the CRC VM)
Cache Usage:     9.608GB
```

## CRC config
```bash
No output
```

## Host Operating System
```bash
ProductName:	Mac OS X
ProductVersion:	10.15
BuildVersion:	19A603
```

### Steps to reproduce

  1. crc start -pull-secret ~/Downloads/pull-secret.txt
  2. crc oc-env
  3. oc login
  4. oc new-project test
  5. oc import-image openjdk/openjdk-11-rhel8 --from=registry.redhat.io/openjdk/openjdk-11-rhel8 --confirm

### Expected
Since I already provided a pull secret I would expect that pull secret to be configured cluster wide so that I as a developer don't have to create pull-secrets. 

### Actual
 ```
> oc import-image openjdk/openjdk-11-rhel8 --from=registry.redhat.io/openjdk/openjdk-11-rhel8 --confirm
error: tag latest failed: Internal error occurred: Get https://registry.redhat.io/v2/openjdk/openjdk-11-rhel8/manifests/latest: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
imagestream.image.openshift.io/openjdk-11-rhel8 imported with errors

Name:			openjdk-11-rhel8
Namespace:		test
Created:		Less than a second ago
Labels:			<none>
Annotations:		openshift.io/image.dockerRepositoryCheck=2019-10-29T16:00:35Z
Image Repository:	image-registry.openshift-image-registry.svc:5000/test/openjdk-11-rhel8
Image Lookup:		local=false
Unique Images:		0
Tags:			1

latest
  tagged from registry.redhat.io/openjdk/openjdk-11-rhel8

  ! error: Import failed (InternalError): Internal error occurred: Get https://registry.redhat.io/v2/openjdk/openjdk-11-rhel8/manifests/latest: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
      Less than a second ago
 ```

### Logs

N/A

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by gbraad** [comment]
Ref: https://github.com/code-ready/crc/issues/779#issuecomment-547674500

> For registry.connect.redhat.com, registry.redhat.io there is a much longer base64 string, which may be not ok.

Perhaps there is something wrong with the pull-secret. Please report this on Bugzilla.

**Comment by praveenkumar** [comment]
@tqvarnst pull secrets which you define during start doesn't work across the namespaces. I tried to use the `openshift` namespace which contains the imagestream and templates and it works without any issue. If you really need it to work with a different namespace then you can reference it.

```
$ oc import-image openjdk/openjdk-11-rhel8 --from=registry.redhat.io/openjdk/openjdk-11-rhel8 --confirm -n openshift
imagestream.image.openshift.io/openjdk-11-rhel8 imported

Name:			openjdk-11-rhel8
Namespace:		openshift
Created:		Less than a second ago
Labels:			<none>
Annotations:		openshift.io/image.dockerRepositoryCheck=2019-10-30T06:41:30Z
Image Repository:	image-registry.openshift-image-registry.svc:5000/openshift/openjdk-11-rhel8
Image Lookup:		local=false
Unique Images:		1
Tags:			1

latest
  tagged from registry.redhat.io/openjdk/openjdk-11-rhel8

  * registry.redhat.io/openjdk/openjdk-11-rhel8@sha256:8d2177bdfc307bb023ce8b9438f2c1d4bd024fb15049a50e2672aa8c7fa69745
      Less than a second ago
[...]
```

**Comment by gbraad** [comment]
Is this a change in behaviour from previous versions of OpenShift? Also, this is not a CRC issue... though seems several people stumble into this and expect this to: 'just works'.

**Comment by tqvarnst** [comment]
The difference here is that CRC is self-maintained and targeted to developers. Quarkus is one of the MW runtimes where we need to use the openjdk11-rhel8 image. However, the result here is that we would require a much more complex guide for how to deploy Quarkus onto OpenShift and CRC compared to other Kubernetes distribution. This would potentially be a disqualifying factor for us to recommend CRC to Quarkus developers, which will in the end also hurt OpenShift. 

@sspeiche: FYI, I will sync this with Max as well, but Quarkus is not the only runtime that is affected by this, eventually all images which require authentication will fail.

**Comment by gbraad** [comment]
>  the result here is that we would require a much more complex guide for how to deploy Quarkus onto OpenShift and CRC compared to other Kubernetes distribution.

This is related to OpenShift and not CRC. It is not good for us to implement features that are non-standard with an OpenShift cluster. This is what happened with `oc cluster up` and `minishift` and should not be repeated.

**Comment by sspeiche** [comment]
@tqvarnst agree this should be easier. 

There are few things to work out to make this better:

- Ship quarkus image/image-stream predefined with the OpenShift install, to avoid any of this. This work is underway
- Define a better way to propogate the pull secret post-install to the cluster. This not a unique issue with CRC, perhaps someone can write a simple script to help, though I agree with @gbraad we need the platform to be able to handle this properly. We should open a https://github.com/openshift/enhancements or what ever is needed to track that with OpenShift.

**Comment by tqvarnst** [comment]
Thanks Steve! 
What worries me with the first point is that if we ship with Quarkus images then we cannot update these images as Quarkus evolves without waiting for new CRC release. Quarkus is still in a fast evolution phase and will continue that even after it is productized, so aligning CRC releases with certain versions of Quarkus is not going to be very practical.

I can open the ticket with OpenShift, but it would be good if you could help with also backing that ticket to give it higher visibility.

**Comment by sspeiche** [comment]
Agree we need to have the images updating.

We can take the action to create the enhancement, we already have a somethings on our plate from a CRC / developer point of view we are raising. Thanks

**Comment by tqvarnst** [comment]
Thanks. Please let me know when you have created the enhancement.

**Comment by gbraad** [comment]
The enhancement should be created by those who have an interest in the
change or functionality.

Although I believe this could and should be easier, it is part of how the
finegrained permission model of OpenShift works. And the solution would be
to, as described earlier, import the image from the namespace. This can
easily be automated by a script or an instruction.

**Comment by cfergeau** [comment]
@tqvarnst have you created this enhancement request? I'll close this bug on crc side as there is nothing specific to crc to be done.

**Comment by rogeriob2br** [comment]
> oc import-image openjdk / openjdk-11-rhel8 --de = registry.redhat.io / openjdk / openjdk-11-rhel8 --confirme
> Como mencionado por @praveenkumar

Hi in the first message this was done. 
I have the same problem.
I tried import the CamelK image, tagged from registry.redhat.io/fuse7-tech-preview/fuse-camel-k, but this doesnt work:
```

latest
  tagged from registry.redhat.io/fuse7-tech-preview/fuse-camel-k

  ! error: Import failed (InternalError): Internal error occurred: registry.redhat.io/fuse7-tech-preview/fuse-camel-k:latest: Get https://registry.redhat.io/v2/: dial tcp: lookup registry.redhat.io on 172.30.0.10:53: server misbehaving
```
I need recreate the secret of redhat io in the every new projects?
