### ISSUE TITLE
Need to assign more than 12G to run the bookinfo example, is this right?

### ISSUE THREAD

**Issue by DhruvM1994** [code-ready/crc#783]
### General information

  * OS: Windows
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it (Yes/No)?

## CRC version
```bash
crc version: 1.0.0+575079b
OpenShift version: 4.2.0 (embedded in binary)
```
  
## CRC status
```bash
CRC VM:          Running
OpenShift:       Running (v4.2.0)
Disk Usage:      14.83GB of 32.2GB (Inside the CRC VM)
Cache Usage:     10.14GB
```

## CRC config
```bash
- cpus                                      : 4
- memory                                : 12288

```

### Steps to reproduce

  1. Follow the instrcutions for settig up OpenShift service mesh under https://docs.openshift.com/container-platform/4.1/service_mesh/service_mesh_install/installing-ossm.html
  2. Deploy the bookinfo example from https://docs.openshift.com/container-platform/4.2/service_mesh/service_mesh_day_two/ossm-example-bookinfo.html
  

### Expected
All container should be ready.

### Actual
While trying to deploy the bookinfo example using the link above not all containers are ready. Some are "pending" and "Unschedulable", maybe due to "Insufficient memory", as stated in the events section in the OpenShift Web Console.

As described above I am assigning 12GB of RAM and 4 virtual CPUs, which might not be enough.
Do I need additional hardware resources for deploying the above example?

**Comment by gbraad** [comment]
8GB is the lower limit of what a simple application needs with the OpenShift Control Plane. But you might run into memory issues as OpenShift 4 needs a lot of resources... have you tried to assign more?

**Comment by DhruvM1994** [comment]
Referring to the bookinfo example from above I tried to configure all pods (istio and bookinfo) in the same project. Then, all pods are running.

However, if I try to configure the istio-related pods in a different project, then some bookinfo-related pods are "pending" and "unschedulable", due to "insufficient cpu", as stated above.
I tried to allocate more than 4 virtual cpus using:

```
$crc config set cpus 8
```
After the configuration change  the follwing error is shown:
```
Error in dirver during machine creation.
```
Therefore, I assume that I cannot allocate more cpu resources.

**Comment by gbraad** [comment]
> Error in dirver during machine creation.

This is because you can not assign more vCPUs than actual CPU cores you have. Hyper-V is VERY picky about this... it will not overcommit (and also not when it have not enough resources due to CPU affinity/pinning).
