### ISSUE TITLE
Add hostname details to dhcp section `crc` libvirt network

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#79]
As of now we put `host mac='52:fd:fc:07:21:82' name='crc' ip='192.168.126.11'/>` is the  entry we have for dhcp section of crc network in case of libvirt. Here `name=crc` should be the proper hostname of the image which we create and this details is supplied by bundle metadata so this need our libvirt driver to be updated so it will update the network as per metadata.

**Comment by gbraad** [comment]
depends on #34

**Comment by gbraad** [comment]
Depends on #34

**Comment by anjannath** [comment]
Fixed in https://github.com/code-ready/crc/commit/1e19504bf29e3238e8d8ee2d5bf9614347d4653b
