### ISSUE TITLE
Spike: Investigate non-VM-based solution

### ISSUE THREAD

**Issue by zeenix** [code-ready/crc#793]
Users and potential users have asked for a CRC that doesn't use VMs and hence is lighter. While there is no empirical evidence that I know if a non-VM based solution will actually be significantly (enough) lighter but we can't be sure until we try things out. There are a bunch of solutions these days out there for k8s cluster orchestration on laptops that run nodes as containers and hence the reason why users ask for this as it's at least theoretically possible to implement such a solution.

I propose a spike where I investigate this option a bit. The target goals would be to get:

- [ ] RHCOS running successfully on a container.
- [ ] modify cluster-api-provider-libvirt to create worker nodes through this method.

IMO this will give us a good idea about how hard exactly this task will be, if we decide to pursue this.

**Comment by gbraad** [comment]
the risk we of this approach is that we are creating a non-standard approach to how the cluster runs; in that case we end up in a non-production like environment and might end up with issues that a regular cluster will not have. this would be no better than the `oc cluster up` approach as performed by Minishift. It might be helpful to have a look at the BYO- approach where RHEL is used as the base platform?

Be aware, that this means we have to rely on a container runtime that is out of our control. It might also only work for a subset of our target platforms and the therefore the need of maintaining multiple methods in our codebase.
