### ISSUE TITLE
Systemtray (Windows)

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#795]
Tasks
-----

  * [x] service #796
  * [x] system tray entry
    * [x] allow to start cluster
    * [x] allow to stop cluster
    * [x] represent cluster state
    ~~opt. start terminal with oc environment set~~
    * [x] allow to set configurations (#1246)

**Comment by anjannath** [comment]
Few issues with the setup:
1. Daemon service is not writing the logs to `~/.crc/crcd.log` haven't able to figure out why.
2. in total now we get 6 UAC prompts which gets a bit annoying. (for the daemon service installation and starting it)
3. To install the daemon service we need the user's password, so the user gets a prompt to enter their password during setup.

With the above issues present, the PR filed for this,  can install the service and the tray.

**Comment by gbraad** [comment]
@anjannath can you add issue numbers for those about config, etc?

**Comment by anjannath** [comment]
@gbraad Linked to #1246 pr for the config api for daemon, the other related issues are part of the tray repo, which i think are listed in a card in the project board so will update it there.

**Comment by anjannath** [comment]
Issue for the config window: https://github.com/code-ready/tray-windows/issues/5
