### ISSUE TITLE
Why is crc restarting all my networks on macOS?

### ISSUE THREAD

**Issue by kadel** [code-ready/crc#797]
I'm running crc on Mac. 
Each time I start CRC it restarts all my networks. 
This is a little bit annoying as it interrupts other work that I'm doing at the same time :-(

Is there a way to start crc without disconnecting me from the internet?

**Comment by cfergeau** [comment]
It should only be doing that after a 'crc delete && crc start' cycle, not on 'crc stop && crc start'. Are you seeing the network restart more often than that? We haven't figured out yet a better way of triggering a reload of `/etc/resolver/testing`

**Comment by kadel** [comment]
You are right, I've been running `crc delete && crc start` quite a lot as I was testing something where I always needed a fresh cluster.

**Comment by cfergeau** [comment]
Issue #798 could be a way around this problem to minimize even more the number of network restarts.

**Comment by gbraad** [comment]
#798 might move this to the setup phase, but a restart (once) is at least needed

**Comment by cfergeau** [comment]
Duplicate of #322
