### ISSUE TITLE
hyperkit: Always reuse the same UUID for the VM

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#798]
At the moment, each time we recreate the crc VM (after a crc delete), we generate a new random UUID for the VM. This causes the VM mac address to change, so it gets a new IP address. When this happens, we need to reload /etc/resolver/testing, which we do by restarting the network, which can have side effects on other processes running at the same time.
Since we are only running once crc instance at a time, we could always reuse the same UUID, which would minimize the number of network restarts which are needed.
See also https://github.com/code-ready/crc/issues/797 and https://github.com/code-ready/crc/issues/322

**Comment by praveenkumar** [comment]
Fixed by #805
