### ISSUE TITLE
Do not notify that a newer version is available when running git snapshots

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#806]
At the moment, our version check triggers for git versions, and tells us a newer version is available, even if the latest official build is probably older than the git version.

**Comment by cfergeau** [comment]
For the latest 2 releases, git version was raised right after release, which is a way of avoiding this issue.

**Comment by gbraad** [comment]
@cfergeau is this still relevant?

**Comment by cfergeau** [comment]
We can keep this closed as this is handled better.
