### ISSUE TITLE
Folders holding released binaries are named inconsistently across platforms

### ISSUE THREAD

**Issue by jsliacan** [code-ready/crc#824]
### General information

  * OS: Linux / macOS / Windows

### Description

When unpacking embedded binaries, these are the resulting folders for respective platforms
- linux: `crc-linux-1.1.0-amd64`
- windows: `crc-windows-1.1.0-dev-amd64`
- darwin:  `crc-macos-1.0.0-dev-amd64`

The problem is that the name of the folder cannot be constructed from CRC version directly as it is `1.0.0` or `1.1.0-dev` depending on the platform. Given that this is about the same version of CRC, at least one folder is named incorrectly.

**Comment by praveenkumar** [comment]
@jsliacan @tsedmik From where are you getting the inconsistency since I just tried the current master with `make release` and generated tarball have consist across the distribution.

```
$ ls -l
total 25944
drwxr-xr-x  5 prkumar  wheel      160 Nov 22 10:01 crc-linux-1.1.0-dev-amd64
-rw-r--r--  1 prkumar  wheel  3508168 Nov 22 10:02 crc-linux-amd64.tar.xz

drwxr-xr-x  5 prkumar  wheel      160 Nov 22 10:01 crc-macos-1.1.0-dev-amd64
-rw-r--r--  1 prkumar  wheel  3847240 Nov 22 10:01 crc-macos-amd64.tar.xz

drwxr-xr-x  5 prkumar  wheel      160 Nov 22 10:02 crc-windows-1.1.0-dev-amd64
-rw-r--r--  1 prkumar  wheel  4851925 Nov 22 10:02 crc-windows-amd64.zip
```

**Comment by gbraad** [comment]
@praveenkumar did you also try to unpack the binary again? let's move the archives to temp and see what the directories are after the extraction

**Comment by jsliacan** [comment]
@praveenkumar, as @gbraad says. We took the released binary packed as `tar.xz` from the builds and after unpacking, linux folder lacks the `-dev` part. I didn't have time to recheck because my download is really slow, but taking it from here should confirm this: https://mirror.openshift.com/pub/openshift-v4/clients/crc/1.1.0/. Thanks!

**Comment by jsliacan** [comment]
Cannot replicate now. Probably user error.
