### ISSUE TITLE
CodeReady Containers does not include the WildFly image stream by default

### ISSUE THREAD

**Issue by yersan** [code-ready/crc#825]
Hello,

CodeReady Containers does not include the WildFly image stream by default;  it has to be imported manually after starting the cluster:

```bash
oc import-image wildfly --confirm \--from quay.io/wildfly/wildfly-centos7 --insecure -n openshift
```

I'm not sure what it is needed to accomplish it, so the following is some information related to these images:

- There is one WildFly release every 3 months
- The images are deployed on https://quay.io/organization/wildfly
- There are two image streams available for WildFly; a builder image and a runtime image (used in chained builds)
- There is only one image template to create a chained build.
- The images and template resources are available here:
   - https://github.com/wildfly/wildfly-s2i/tree/current/imagestreams
   - https://github.com/wildfly/wildfly-s2i/blob/current/templates/wildfly-s2i-chained-build-template.yml

Can the WildFly images and template be included by default in CRC?

Thanks!

**Comment by cfergeau** [comment]
Are they included by default with an OpenShift 4 install, but missing from CodeReady Containers releases? If yes, then it's indeed a bug in CodeReady Containers that we need to fix. If they are not included by default in OpenShift 4 either, then CodeReady Containers is not going to include them either, our goal is to be as close as possible to a standard OpenShift 4 install.

**Comment by gbraad** [comment]
AFAIK they aren't included in a cluster installed using the OpenShift installer.

I will close as invalid unless otherwise indicated by a reference or resource that shows they should be available.

**Comment by gbraad** [comment]
> Can the WildFly images and template be included by default in CRC?

We will not provide these by default. We could however, link to instructions on how to get these installed/deployed onto a cluster. But this feels more like something the development tools around `odo` or adapters could do better, especially when integrated with the IDE.
