### ISSUE TITLE
[BUG] Use docker instead podman in the Makefile

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#833]
podman have `podman-docker` package for fedora/rhel/centos side which symlink the docker command to podman. In the mac if someone try to build the release bits it always have to through the error since the podman command is not available. I think better to have `docker` in the makefile without breaking it for Mac atleast.

**Comment by cfergeau** [comment]
On linux, going podman->docker is a step backward, so nack from me :)

**Comment by praveenkumar** [comment]
@cfergeau I am not saying that go back to `docker` for linux, in our distro we already have podman symlink to docker.

**Comment by kdubois** [comment]
> podman have `docker-podman` package for fedora/rhel/centos side which symlink the docker command to podman. In the mac if someone try to build the release bits it always have to through the error since the podman command is not available. I think better to have `docker` in the makefile without breaking it for Mac atleast.

FYI the package is `podman-docker` :)

**Comment by praveenkumar** [comment]
> FYI the package is podman-docker :)

@kdubois updated Thanks 👍

**Comment by rhatdan** [comment]
Podman is available via brew.  And should be able to work over varlink to the CRC if ssh connection can be estabilished.

**Comment by gbraad** [comment]
Leaving as-is (closed) as it seems not have been brought up again
