### ISSUE TITLE
Error creating host: Error creating new host: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s

### ISSUE THREAD

**Issue by jhoeflaken** [code-ready/crc#834]
### General information

  * OS: Windows
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
crc version: 1.1.0+95966a9
```
  
## CRC status
```bash
Machine 'crc' does not exist. Use 'crc start' to create it.
```

## CRC config
```bash
```

## Host Operating System
```bash
Time Zone:                 (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
Total Physical Memory:     32,649 MB
Available Physical Memory: 24,883 MB
Virtual Memory: Max Size:  37,513 MB
Virtual Memory: Available: 29,775 MB
Virtual Memory: In Use:    7,738 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    vened.nl
Logon Server:              \\NL024-ADS-001
Hotfix(s):                 10 Hotfix(s) Installed.
                           [01]: KB4514366
                           [02]: KB4470788
                           [03]: KB4489907
                           [04]: KB4503308
                           [05]: KB4504369
                           [06]: KB4509095
                           [07]: KB4512577
                           [08]: KB4516115
                           [09]: KB4521862
                           [10]: KB4519338
Network Card(s):           9 NIC(s) Installed.
                           [01]: Intel(R) Dual Band Wireless-AC 8260
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.178.1
                                 IP address(es)
                                 [01]: 192.168.178.26
                                 [02]: fe80::25e3:3371:3d58:83b4
                           [02]: Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows x64

                                 Connection Name: Ethernet 2
                                 Status:          Hardware not present
                           [03]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (OpenShift)
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.163.254
                                 IP address(es)
                                 [01]: 192.168.163.1
                                 [02]: fe80::1985:d943:f64a:1a4c
                           [04]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (Default Switch)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 172.17.90.161
                                 [02]: fe80::e8dc:c08a:2755:57b7
                           [05]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (DockerNAT)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 10.0.75.1
                                 [02]: fe80::9091:32aa:121f:bdf5
                           [06]: VMware Virtual Ethernet Adapter for VMnet1
                                 Connection Name: VMware Network Adapter VMnet1
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.80.254
                                 IP address(es)
                                 [01]: 192.168.80.1
                                 [02]: fe80::adcf:a23f:c700:bf87
                           [07]: Intel(R) Ethernet Connection (2) I219-LM
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [08]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [09]: VMware Virtual Ethernet Adapter for VMnet8
                                 Connection Name: VMware Network Adapter VMnet8
                                 DHCP Enabled:    Yes
                                 DHCP Server:     N/A
                                 IP address(es)
```

### Steps to reproduce

  1. `crc setup`
  2. `crc start -p pull_secret.txt`

### Expected
CRC statring

### Actual
Exception
```
INFO Checking if running as normal user
INFO Checking if oc binary is cached
INFO Check Windows 10 release
INFO Hyper-V installed and operational
INFO Is user a member of the Hyper-V Administrators group
INFO Does the Hyper-V virtual switch exist
INFO Loading bundle: crc_hyperv_4.2.2.crcbundle ...
INFO Creating CodeReady Containers VM for OpenShift 4.2.2...
ERRO Error creating host: Error creating new host: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s
```

**Comment by gbraad** [comment]
> ERRO Error creating host: Error creating new host: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s

There can be many reasons to this... but since it shows 'Faile dto dial the plugin server' I and I see `Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows x64` I believe you tried to start the cluster while being connected to the VPN. Please disconnect and try again.

**Comment by gbraad** [comment]
Note: You also have VMware installed. Be aware this might cause issues for Hyper-V as the hypervisor needs exclusive access to the Virtualization Extensions.

**Comment by gbraad** [comment]
What is the use of `vEthernet (OpenShift)` ?

**Comment by jhoeflaken** [comment]
Hello @gbraad 



> 
> 
> > ERRO Error creating host: Error creating new host: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s
> 
> There can be many reasons to this... but since it shows 'Faile dto dial the plugin server' I and I see `Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows x64` I believe you tried to start the cluster while being connected to the VPN. Please disconnect and try again.

I was not connected to the VPN when I started the cluster. Looks like it is an anti-virus (firewall/Symantic Endpoint Protection) issue, because when I am on the corporate network I am able to bypass this problem. Then however, I have the problem that I cannnot run as Administrator but get a message that I need to be an Administrator to execute Hyper-V commands. I am a member of the Hyper-V Administrators group (it passes that check). 

> 
> 
> Note: You also have VMware installed. Be aware this might cause issues for Hyper-V as the hypervisor needs exclusive access to the Virtualization Extensions.

I installed VMWare for the VMNet8 network adapter which is far more reliable when it comes to expose a VM to the outside world in my experience. I use this adapter with the Hyper-V OpenShift Switch to assign a static IP-address to my oc cluster up OpenShift v3.11 VM. With this adapter I have no issues with the anti-virus (Symantic Endpoint Protection) and can swith networks without any impact on the OpenShift v3.11 cluster running in the VM; both corporate and none-corporate networks.

Thnx.

**Comment by jhoeflaken** [comment]
Resolved it disabling the user administrator check and running crc as Administrator.

`crc config set skip-check-administrator-user true`

**Comment by gbraad** [comment]
> I installed VMWare for the VMNet8 network adapter which is far more reliable when it comes to expose a VM to the outside world in my experience. 

Have you tried to use a TUN/TAP device? This would have the same effect and is a much smaller to deal with ...

**Comment by gbraad** [comment]
>  I have the problem that I cannnot run as Administrator but get a message that I need to be an Administrator to execute Hyper-V commands. I am a member of the Hyper-V Administrators group (it passes that check).

Is this the same issue as #742 ?

**Comment by jhoeflaken** [comment]
> 
> 
> > I installed VMWare for the VMNet8 network adapter which is far more reliable when it comes to expose a VM to the outside world in my experience.
> 
> Have you tried to use a TUN/TAP device? This would have the same effect and is a much smaller to deal with ...

Could get this to work. Installed device just said not connected. I use Wifi connection only.



> 
> 
> > I have the problem that I cannnot run as Administrator but get a message that I need to be an Administrator to execute Hyper-V commands. I am a member of the Hyper-V Administrators group (it passes that check).
> 
> Is this the same issue as #742 ?

Could be, but I also noticed that with the normal Default Switch it didn't work (even when Administrator). So the solution for me was both: VMWare vmnet8 virtual ethernet adapter and run crc as Administrator.

Kind regards.

**Comment by gbraad** [comment]
It looks like an issue with the default switch? (sounds like an old issue when LCOW was used witrh a Docker preview).

You can create an override network/virtual switch named `crc` that you can configure yourself.
