### ISSUE TITLE
Allow custom directories for Setup and Start

### ISSUE THREAD

**Issue by Snackin** [code-ready/crc#835]
I searched the issues list and did not see this, so I apologize if this is a duplicate.

Hyper-V on Windows cannot use a mapped drive for virtual disk image storage, BUT my home directory on my corporate laptop uses a mapped drive for its storage.

So, when I use 'CRC start', the Powershell command tries to mount a virtual machine image from that mapped drive and Hyper-V throws an error.

Here's the relevant Log:

Creating machine...
(crc) Calling .Create
(crc) Downloading X:\.crc\cache\crc.vhdx from file://X:/.crc/cache/crc_hyperv_4.2.2/crc.vhdx...
(crc) Creating VM...
(crc) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive [Console]::OutputEncoding = [Text.Encoding]::UTF8; (Hyper-V\Get-VMSwitch).Name
(crc) DBG | [stdout =====>] : DockerNAT
(crc) DBG | Default Switch
(crc) DBG | 
(crc) DBG | [stderr =====>] : 
(crc) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Hyper-V\New-VM crc -Path 'X:\.crc\machines\crc' -SwitchName 'Default Switch' -MemoryStartupBytes 8192MB
(crc) Using switch "Default Switch"
(crc) DBG | [stdout =====>] : 
(crc) DBG | [stderr =====>] : Hyper-V\New-VM : Failed to create a new virtual machine.
(crc) DBG | 'crc' failed to realize.
(crc) DBG | Failed to change Smart Paging location to 'X:\.crc\machines\crc\crc'.
(crc) DBG | At line:1 char:1
(crc) DBG | + Hyper-V\New-VM crc -Path 'X:\.crc\machines\crc' -SwitchName 'Default  ...
(crc) DBG | + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
(crc) DBG |     + CategoryInfo          : ObjectNotFound: (:) [New-VM], VirtualizationException
(crc) DBG |     + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.NewVM
(crc) DBG |  
(crc) DBG | 

Note, if I change the drive letter to a local drive, the powershell command succeeds.

What I would like to do is to be able to give parameters to CRC Setup and CRC Start to override some of the defaults so I can use my filesystem the way I want instead of being forced to use my HOME directory.

Thanks.

**Comment by praveenkumar** [comment]
This is duplicate for https://github.com/code-ready/crc/issues/764
