### ISSUE TITLE
Use tagged image for recovery process instead fetching from internet

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#840]
Right now https://github.com/code-ready/crc/blob/master/pkg/crc/machine/cert-renewal.go#L66-L77 we are trying to fetch the image content from internet but since https://github.com/code-ready/snc/pull/132 is in and we already tag that image so we don't need to fetch it from internet anymore.

**Comment by cfergeau** [comment]
`kaoImage := "openshift/cert-recovery"` should do the trick.

**Comment by praveenkumar** [comment]
Fixed by #842
