### ISSUE TITLE
[Integration] Add integration test for cert recovery process

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#843]
We need to add integration step to verify the cert recovery process is working as expected. To achieve it we will need to upload another bundle to GCP which have the expired cert and this bundle should be consumed during this integration test step.

**Comment by cfergeau** [comment]
Ideally we'd be testing 2 different scenarios, one is the one you describe, the other one would be "crc start was run once, and then the certs expired while the machine was shut off, and we want to restart it"

**Comment by jsliacan** [comment]
Still in the works. Reopening...

**Comment by cfergeau** [comment]
Useful trick from slack:
> I was able to get a failed renewal.
    blocked UDP port 123 out of my local gateway
    sudo date -s "9 JULY 2020 11:11:11"
    downloaded/extracted crc-1.10
    crc delete <just in case i had an old one>
    crc setup
    crc start -c 8 -m 25000 ...
    /fail

**Comment by btannous** [comment]
https://libvirt.org/formatnwfilter.html @cfergeau mentioned this on slack. =)

**Comment by cfergeau** [comment]
I added more details around nwfilters in https://github.com/code-ready/crc/issues/1242#issuecomment-629698002

**Comment by praveenkumar** [comment]
Basic test is already added for cert recovery, we can try to add some more like deploy an application.
