### ISSUE TITLE
Ensure Hyper-V management service is running

### ISSUE THREAD

**Issue by hisureshk** [code-ready/crc#850]
I am trying to setup crc in windows 10 but failed. Find below the logs when run with debug.

>crc setup --log-level debug

```
INFO Checking if running as normal user
INFO Caching oc binary
DEBU oc binary already cached
INFO Unpacking bundle from the CRC binary
INFO Check Windows 10 release
INFO Hyper-V installed
ERRO Hyper-V Virtual Machine Management service not running
DEBU Hyper-V Virtual Machine Management service not running
INFO Will run as admin: enable Hyper-V
ERRO Please reboot your system
INFO Is user a member of the Hyper-V Administrators group
INFO Does the Hyper-V virtual switch exist
DEBU exit status 1
ERRO Failed checking if Hyper-V Default Switch exists
DEBU Failed checking if Hyper-V Default Switch exists
ERRO Unable to perform Hyper-V administrative commands. Please make sure to re-login or reboot your system
FATA Unable to perform Hyper-V administrative commands. Please make sure to re-login or reboot your system
```

Kindly advice.

Thanks,

**Comment by gbraad** [comment]
Please reboot your machibe as instructed,

**Comment by hisureshk** [comment]
I did reboot the machine and tried the same command again but getting the same error. Kindly let me know what additional information is needed.

**Comment by gbraad** [comment]
The original bug report contained additional notes about the commands to run to obtain these.

Please share the version of Windows you try this with; `systeminfo` and output of `crc setup`.

**Comment by gbraad** [comment]
Can you also try `net start "Hyper-V Virtual Machine Management"` and run `crc setup` ?
Do you have other hypervisors installed perhaps, like VMware or VirtualBox?

**Comment by gbraad** [comment]
Reproducible as by stopping the `vmms`:

```
C:\Users\gbraad\Downloads>crc setup
INFO Checking if running as normal user
INFO Caching oc binary
INFO Unpacking bundle from the CRC binary
INFO Check Windows 10 release
INFO Hyper-V installed
ERRO Hyper-V Virtual Machine Management service not running
INFO Will run as admin: enable Hyper-V
ERRO Please reboot your system
INFO Is user a member of the Hyper-V Administrators group
INFO Does the Hyper-V virtual switch exist
ERRO Virtual Switch not found
ERRO Unable to perform Hyper-V administrative commands. Please make sure to re-login or reboot your system
FATA Unable to perform Hyper-V administrative commands. Please make sure to re-login or reboot your system

C:\Users\gbraad\Downloads>net start "Hyper-V Virtual Machine Management"
The Hyper-V Virtual Machine Management service is starting.
The Hyper-V Virtual Machine Management service was started successfully.


C:\Users\gbraad\Downloads>crc setup
INFO Checking if running as normal user
INFO Caching oc binary
INFO Unpacking bundle from the CRC binary
INFO Check Windows 10 release
INFO Hyper-V installed
INFO Is user a member of the Hyper-V Administrators group
INFO Does the Hyper-V virtual switch exist
INFO Found Virtual Switch to use: Default Switch
Setup is complete, you can now run 'crc start -b $bundlename' to start the OpenShift cluster
```

**Comment by gbraad** [comment]
I added a new pre-flight check that handles this situation. We did check the service state, but didn't fix it.

**Comment by hisureshk** [comment]
Thank You very much for the update.  I was trying to start the hyper-v service as below but getting error.
 
>net start "Hyper-V Virtual Machine Management"
The service name is invalid.

More help is available by typing NET HELPMSG 2185.

I had in my system virtual box, so I uninstalled and tried again but with same result.  If not Hyper-V, are there other alternatives that we could leverage?

Thanks ahead

**Comment by Amallard** [comment]
I have a similar issue and don't know how to resolve. I'm running Windows 10 Home. I enabled Intel Virtualization through BIOS. Running `crc setup` I get the following errors:

```
C:\OpenShift>crc setup
INFO Checking if running as normal user
INFO Caching oc binary
INFO Unpacking bundle from the CRC binary
INFO Check Windows 10 release
INFO Hyper-V installed
ERRO Hyper-V Virtual Machine Management service not running
INFO Will run as admin: enable Hyper-V
ERRO Please reboot your system
INFO Is user a member of the Hyper-V Administrators group
INFO Does the Hyper-V virtual switch exist
ERRO Virtual Switch not found
ERRO Unable to perform Hyper-V administrative commands. Please make sure to re-login or reboot your system
FATA Unable to perform Hyper-V administrative commands. Please make sure to re-login or reboot your system
```

When running `net start "Hyper-V Virtual Machine Management"` I get the following error:

```
C:\OpenShift>net start "Hyper-V Virtual Machine Management"
The service name is invalid.

More help is available by typing NET HELPMSG 2185.
```

**Comment by agendartobias** [comment]
We had the same error, this happens because you user in not added to usergroup "Hyper-V Administrators". You must add it manualy. Follow this:

1. Click Start > Control Panel > Administration Tools > Computer Management. The Computer Management window opens.
2. Click System Tools > Local Users and Groups > Groups. The list of groups opens.
3. Double-click the Hyper-V Administrators group. The Hyper-V Administrators Properties window opens.
4. Click Add. The Select Users or Groups window opens.
5. In the Enter the object names to select field, enter the user account name to whom you want to assign permissions, and then click OK.
6. Click Apply, and then click OK.

**Comment by Jupiops** [comment]
Press Win + R shortcut keys on your keyboard and type the following in the run box: `lusrmgr.msc`


>     2. Click System Tools > Local Users and Groups > Groups. The list of groups opens.
> 
>     3. Double-click the Hyper-V Administrators group. The Hyper-V Administrators Properties window opens.
> 
>     4. Click Add. The Select Users or Groups window opens.
> 
>     5. In the Enter the object names to select field, enter the user account name to whom you want to assign permissions, and then click OK.
> 
>     6. Click Apply, and then click OK.

**Comment by jawand** [comment]
> We had the same error, this happens because you user in not added to usergroup "Hyper-V Administrators". You must add it manualy. Follow this:
> 
> 1. Click Start > Control Panel > Administration Tools > Computer Management. The Computer Management window opens.
> 2. Click System Tools > Local Users and Groups > Groups. The list of groups opens.
> 3. Double-click the Hyper-V Administrators group. The Hyper-V Administrators Properties window opens.
> 4. Click Add. The Select Users or Groups window opens.
> 5. In the Enter the object names to select field, enter the user account name to whom you want to assign permissions, and then click OK.
> 6. Click Apply, and then click OK.

After doing these steps I just had to restart the machine. & voila it worked. 🐱‍👤🐱‍👤

**Comment by gbraad** [comment]
Why doesn't `crc setup` not work for you? Can you provide debug information so this can be fixed as this should be happening automated.

**Comment by nddipiazza** [comment]
I got this error, restarted as it said to do, then ran `crc setup` again , and it worked.

**Comment by harpritsinghsokhi** [comment]
I get the below error for hyper V, not able to enable it, could you suggest ?

C:\Program Files\Red Hat OpenShift Local>crc start
INFO Checking if running in a shell with administrator rights
INFO Checking Windows release
INFO Checking Windows edition
INFO Checking if Hyper-V is installed and operational
WARN Preflight checks failed during `crc start`, please try to run `crc setup` first in case you haven't done so yet
Hyper-V management service not available

C:\Program Files\Red Hat OpenShift Local>


I guess the below output would help as well.



C:\Program Files\Red Hat OpenShift Local>crc console --credentials
Machine does not exist. Use 'crc start' to create it


C:\Program Files\Red Hat OpenShift Local>crc start
INFO Checking if running in a shell with administrator rights
INFO Checking Windows release
INFO Checking Windows edition
INFO Checking if Hyper-V is installed and operational
WARN Preflight checks failed during `crc start`, please try to run `crc setup` first in case you haven't done so yet
Hyper-V management service not available

C:\Program Files\Red Hat OpenShift Local>crc setup
INFO Using bundle path C:\Users\luckie\.crc\cache\crc_hyperv_4.11.13_amd64.crcbundle
INFO Checking if current user is in Hyper-V Admins group
INFO Checking if CRC bundle is extracted in '$HOME/.crc'
INFO Checking if C:\Users\luckie\.crc\cache\crc_hyperv_4.11.13_amd64.crcbundle exists
INFO Checking if the daemon task is installed
INFO Checking if the daemon task is running
INFO Checking admin helper service is running
Your system is correctly setup for using CRC. Use 'crc start' to start the instance

C:\Program Files\Red Hat OpenShift Local>

**Comment by praveenkumar** [comment]
@harpritsinghsokhi If that still issue for you, please create a new issue instead of putting comment to a close one.
