### ISSUE TITLE
Add host->cluster DNS checks

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#854]
At the moment we check VM->cluster DNS, VM->external DNS, but I could not find a startup check that the host can resolve `api.crc.testing` and `non-existing-app.apps-crc.testing` after the dnsmasq container was started.
We should add such a check, and verify that it matches the VM IP. Not sure whether this should abort `crc start` or just be a warning though.

----

  * [ ] check `api.crc.testing`
  * [ ] check `foo.crc-apps.testing`

**Comment by gbraad** [comment]
Unfortunately this check has been reverted.

**Comment by cfergeau** [comment]
This was reverted because of https://github.com/code-ready/crc/issues/893
Since our builds have CGO_ENABLED=0, the binary does not make use of `/etc/resolver/` for DNS resolution, but relies on hardcoded entries in `/etc/hosts`, so checking for foo.crc.testing fails.

**Comment by cfergeau** [comment]
As indicated in #918, for now we could have a check for only `api.crc.testing`.
Regarding the check for `foo.crc-apps.testing`, we can do it only on linux/windows to avoid the issue we have on macos

**Comment by gbraad** [comment]
See first message
