### ISSUE TITLE
[BUG] 'Do you want to force power off' question is not displayed properly

### ISSUE THREAD

**Issue by flozzone** [code-ready/crc#862]
### General information

  * OS: Linux 
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
./crc version
crc version: 1.2.0+c2e3c0f
OpenShift version: 4.2.8 (embedded in binary)
```
  
## CRC status
```bash
./crc status
CRC VM:          Stopped
OpenShift:       Stopped
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     22.4GB
Cache Directory: /home/florin/.crc/cache
```

## CRC config
```bash
./crc config view
- skip-check-crc-dnsmasq-file           : false
- skip-check-network-manager-config     : false
```

## Host Operating System
```bash
cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### Other infos

Was using zsh in terminator

### Steps to reproduce

  1. crc start
  2. crc stop 

### Expected
Actually stop the vm or print the following string in time:
```Do you want to force power off? [y/N]:```

### Actual
When vm doesn't get stopped normally, the string ```Do you want to force power off? [y/N]:``` hangs somewhere in a buffer and is not displayed on the terminal. When 'crc stop' times out and exits, the force-power-off string is displayed (but too late to actually force power off).

### Logs
```
➜  crc-linux-1.2.0-amd64 ./crc stop
Stopping the OpenShift cluster, this may take a few minutes...


ERRO VM Failed to gracefully shutdown, try the kill command 
Do you want to force power off? [y/N]: %
➜  crc-linux-1.2.0-amd64
```

This is the output when "blindly" pressing y:
```
➜  crc-linux-1.2.0-amd64 ./crc stop                                       
Stopping the OpenShift cluster, this may take a few minutes...

y
y
Y
Stopped the OpenShift cluster
➜  crc-linux-1.2.0-amd64
```

**Comment by praveenkumar** [comment]
@flozzone This is not bug, The way `crc stop` works is, first it try to make sure the VM should shutdown gracefully with a timeout of 2 min if VM is still running then it prompt user for force power off and user can select `y/n`.  Do you have any suggestion how messaging could be better?

**Comment by flozzone** [comment]
I should have described this better. `crc stop` does what it should, but the message
```
ERRO VM Failed to gracefully shutdown, try the kill command 
Do you want to force power off? [y/N]: %
```
appeared after the `crc stop` process exited. Because the string itself hung in an output buffer.
Means some timeout time passed because no key was pressed. Its kind of hard to reproduce this, because I don't know how to bring `crc stop` into the state where it fails to shutdown gracefully.

Any hints how to reproduce such a behaviour?
