### ISSUE TITLE
crc 1.2.0 macos Mojave 10.14.6, crc throws x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by jepries** [code-ready/crc#864]
pulled crc 1.2.0 from https://cloud.redhat.com/openshift/install/crc/installer-provisioned

installed.  CRC Setup fine.  crc start throws

INFO Starting OpenShift cluster ... [waiting 3m]  
ERRO Error approving the node csr Not able to get csr names (exit status 1 : Unable to connect to the server: x509: certificate signed by unknown authority
) 

OS: Mojave 10.14.6 - 36G/i9

    $sw_vers
    ProductName:	Mac OS X
    ProductVersion:	10.14.6
    BuildVersion:	18G1012`

    $crc version
    crc version: 1.2.0+c2e3c0f
    OpenShift version: 4.2.8 (embedded in binary)

    $ crc status
    ERRO Unable to connect to the server: x509: certificate signed by unknown authority
    - exit status 1

    $crc config view

returns nothing

Steps to reproduce: New MAC.

installed hyperkit as per https://github.com/moby/hyperkit - did not install qcow support

installed crc as per https://cloud.redhat.com/openshift/install/crc/installer-provisioned, verified downloaded latest crc, 1.2.0

untar, put in in path: i.e.

`export PATH=$PATH:~/hyperkit/hyperkit/build:~/openshift/crc-macos-1.2.0-amd64/`

crc setup
crc start

debug log file from crc start --log-level debug

    $ cat crc.log
    time="2019-12-03T20:42:08-05:00" level=info msg="Checking if running as non-root"
    time="2019-12-03T20:42:08-05:00" level=info msg="Caching oc binary"
    time="2019-12-03T20:42:08-05:00" level=debug msg="oc binary is not cached"
    time="2019-12-03T20:42:08-05:00" level=debug msg="Downloading oc"
    time="2019-12-03T20:42:08-05:00" level=debug msg="Downloading https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/macosx/oc.tar.gz to /var/folders/bs/12mhh7rx3vd56947kn6kzvcjvf9wmb/T/crc213841797"
    time="2019-12-03T20:42:39-05:00" level=debug msg="Download saved to /var/folders/bs/12mhh7rx3vd56947kn6kzvcjvf9wmb/T/crc213841797/oc.tar.gz"
    time="2019-12-03T20:42:39-05:00" level=debug msg="Uncompressing /var/folders/bs/12mhh7rx3vd56947kn6kzvcjvf9wmb/T/crc213841797/oc.tar.gz to /var/folders/bs/12mhh7rx3vd56947kn6kzvcjvf9wmb/T/crc213841797"
    time="2019-12-03T20:42:39-05:00" level=debug msg="Copying '/var/folders/bs/12mhh7rx3vd56947kn6kzvcjvf9wmb/T/crc213841797/oc' to '/Users/v795363/.crc/bin/oc'"
    time="2019-12-03T20:42:40-05:00" level=debug msg="oc binary cached"
    time="2019-12-03T20:42:40-05:00" level=info msg="Setting up virtualization with HyperKit"
    time="2019-12-03T20:42:40-05:00" level=debug msg="Checking if hyperkit is installed"
    time="2019-12-03T20:42:40-05:00" level=debug msg="/Users/v795363/.crc/bin/hyperkit not executable"
    time="2019-12-03T20:42:40-05:00" level=debug msg="no such file or directory"
    time="2019-12-03T20:42:40-05:00" level=debug msg="Downloading https://github.com/code-ready/machine-driver-hyperkit/releases/download/v0.12.6/hyperkit to /Users/v795363/.crc/bin"
    time="2019-12-03T20:42:47-05:00" level=debug msg="Download saved to /Users/v795363/.crc/bin/hyperkit"
    time="2019-12-03T20:42:47-05:00" level=debug msg="Making /Users/v795363/.crc/bin/hyperkit suid"
    time="2019-12-03T20:42:47-05:00" level=info msg="Will use root access: change ownership of /Users/v795363/.crc/bin/hyperkit"
    time="2019-12-03T20:42:59-05:00" level=info msg="Will use root access: set suid for /Users/v795363/.crc/bin/hyperkit"
    time="2019-12-03T20:43:08-05:00" level=info msg="Installing crc-machine-hyperkit"
    time="2019-12-03T20:43:08-05:00" level=debug msg="Checking if crc-driver-hyperkit is installed"
    time="2019-12-03T20:43:08-05:00" level=debug msg="no such file or directory"
    time="2019-12-03T20:43:08-05:00" level=debug msg="Downloading https://github.com/code-ready/machine-driver-hyperkit/releases/download/v0.12.6/crc-driver-hyperkit to /Users/v795363/.crc/bin"
    time="2019-12-03T20:43:21-05:00" level=debug msg="Download saved to /Users/v795363/.crc/bin/crc-driver-hyperkit"
    time="2019-12-03T20:43:21-05:00" level=debug msg="Making /Users/v795363/.crc/bin/crc-driver-hyperkit suid"
    time="2019-12-03T20:43:21-05:00" level=info msg="Will use root access: change ownership of /Users/v795363/.crc/bin/crc-driver-hyperkit"
    time="2019-12-03T20:43:21-05:00" level=info msg="Will use root access: set suid for /Users/v795363/.crc/bin/crc-driver-hyperkit"
    time="2019-12-03T20:43:30-05:00" level=info msg="Setting file permissions for /etc/resolver/testing"
    time="2019-12-03T20:43:30-05:00" level=info msg="Setting file permissions for /etc/hosts"
    time="2019-12-03T20:43:30-05:00" level=info msg="Unpacking bundle from the CRC binary"
    time="2019-12-03T20:43:30-05:00" level=debug msg="stat /Users/v795363/.crc/cache/crc_hyperkit_4.2.8.crcbundle: no such file or directory"
    time="2019-12-03T20:44:17-05:00" level=debug msg="No new version available. The latest version is 1.2.0"
    time="2019-12-03T20:44:17-05:00" level=info msg="Checking if running as non-root"
    time="2019-12-03T20:44:17-05:00" level=info msg="Checking if oc binary is cached"
    time="2019-12-03T20:44:17-05:00" level=debug msg="oc binary already cached"
    time="2019-12-03T20:44:17-05:00" level=info msg="Checking if HyperKit is installed"
    time="2019-12-03T20:44:17-05:00" level=debug msg="Checking if hyperkit is installed"
    time="2019-12-03T20:44:17-05:00" level=info msg="Checking if crc-driver-hyperkit is installed"
    time="2019-12-03T20:44:17-05:00" level=debug msg="Checking if crc-driver-hyperkit is installed"
    time="2019-12-03T20:44:17-05:00" level=debug msg="crc-driver-hyperkit is already installed in /Users/v795363/.crc/bin/crc-driver-hyperkit"
    time="2019-12-03T20:44:17-05:00" level=info msg="Checking file permissions for /etc/resolver/testing"
    time="2019-12-03T20:44:17-05:00" level=info msg="Checking file permissions for /etc/hosts"
    time="2019-12-03T20:44:29-05:00" level=info msg="Extracting bundle: crc_hyperkit_4.2.8.crcbundle ..."
    time="2019-12-03T20:44:29-05:00" level=debug msg="Uncompressing /Users/v795363/.crc/cache/crc_hyperkit_4.2.8.crcbundle to /Users/v795363/.crc/cache"
    time="2019-12-03T20:47:11-05:00" level=info msg="Creating CodeReady Containers VM for OpenShift 4.2.8..."
    time="2019-12-03T20:47:19-05:00" level=debug msg="Waiting until ssh is available"
    time="2019-12-03T20:47:30-05:00" level=info msg="Verifying validity of the cluster certificates ..."
    time="2019-12-03T20:47:33-05:00" level=debug msg="Updating api.crc.testing to 192.168.64.2 in /etc/hosts file"
    time="2019-12-03T20:47:33-05:00" level=debug msg="Updating oauth-openshift.apps-crc.testing to 192.168.64.2 in /etc/hosts file"
    time="2019-12-03T20:47:33-05:00" level=info msg="Network restart not needed"
    time="2019-12-03T20:47:35-05:00" level=info msg="Check internal and public DNS query ..."
    time="2019-12-03T20:47:36-05:00" level=info msg="Copying kubeconfig file to instance dir ..."
    time="2019-12-03T20:47:36-05:00" level=debug msg="Copying '/Users/v795363/.crc/cache/crc_hyperkit_4.2.8/kubeconfig' to '/Users/v795363/.crc/machines/crc/kubeconfig'"
    time="2019-12-03T20:47:36-05:00" level=debug msg="Output is : {\"auths\":{\"cloud.openshift.com\":{\"auth\":\"b...\"},\"registry.connect.redhat.com\":{\"auth\":\"NjQ.....\"},\"registry.redhat.io\":{\"auth\":\".....\"}}}"
    time="2019-12-03T20:47:36-05:00" level=info msg="Adding user's pull secret and cluster ID ..."
    time="2019-12-03T20:47:37-05:00" level=debug msg="Output is : apiVersion: v1\ndata:\n  .dockerconfigjson: eyJhdXRocyI6eyJjbG91ZC5vcGVuc2hpZnQuY29tIjp7ImF1dGgiOiJiM0JsYm5Ob2FXWjBMWEpsYkdW....NVIydEhkV1pEYlRWTVRqVjFaM05qV0hrdyIsImVtYWlsIjoiam9obi5wcmllc0B2ZXJpem9uLmNvbSJ9fX0=\nkind: Secret\nmetadata:\n  name: pull-secret\n  namespace: openshift-config\ntype: kubernetes.io/dockerconfigjson"
    time="2019-12-03T20:48:06-05:00" level=debug msg="Output of timeout 80 bash -c 'until oc --config /tmp/kubeconfig replace -f /tmp/pull-secret.yaml 2>/dev/null 1>&2; \\\ndo echo \"Waiting for recovery apiserver to come up.\"; sleep 1; done': Waiting for recovery apiserver to come up.\nWaiting for recovery apiserver to come up."
    time="2019-12-03T20:48:37-05:00" level=debug msg="Output of timeout 80 bash -c 'until oc --config /tmp/kubeconfig patch clusterversion version -p '\"'\"'{\"spec\":{\"clusterID\":\"ea549af3-0914-4a5b-9a2a-e4727c79edaa\"}}'\"'\"' --type merge 2>/dev/null 1>&2; \\\ndo echo \"Waiting for recovery apiserver to come up.\"; sleep 1; done': "
    time="2019-12-03T20:49:37-05:00" level=debug msg="Output of bash -c 'sudo crictl stopp $(sudo crictl pods -q) &&\\\nsudo crictl rmp $(sudo crictl pods -q)': "
    time="2019-12-03T20:49:37-05:00" level=debug msg="error: Temporary Error: ssh command error:\ncommand : bash -c 'sudo crictl stopp $(sudo crictl pods -q) &&\\\nsudo crictl rmp $(sudo crictl pods -q)'\nerr     : exit status 1\noutput  : Stopped sandbox d9ff10e77b0b2f528c76e1c18801bd88b1ad5b7445eb99516bf39bcea0d3666e\nStopped sandbox 119eb84b844e5dbc3c288aa12d07c6e34e27ed756e64302c09854b62e316290b\nStopped sandbox 7be776bccc656ea9406627156cda89dc00e66bf4fafb4c74c53d5330a19a5062\nStopped sandbox 679adf006167fa8fd73f63eaf66306e24776971e36935ba8366bd62b03430d92\nStopped sandbox 3df7c45a081997fab90b86dd2f0d19c7663a94a4327ea876e210840ace4e74a3\nStopped sandbox 9b19f93e58a37357a36bb81334ea897aaddb01d9530bedcff516cd81c573322c\nStopped sandbox f60e88158b9c86f07001882338f9aabbe507a00f125e1ecdfc7ce44a958b3328\nStopped sandbox 4891dc67e695bf48bcdeb9accd26b4bff4f2e25ca29f371462f300c2e14182a6\nStopped sandbox b5f4d6d112c3099fed18193bbd45398e2ca3efbbe53673d5e6bcc500307d86dd\nStopped sandbox a69ab882041252ae5139b823e779677c8b57c8dc4612939e50d45899d443f554\nStopped sandbox 3d903e56310335141d56f70fd4a1d2e0809c9ab73ee38f6dedba1a10cd2cba59\nStopped sandbox a6254032a44c9ea9e4c3143fdeb1546120e322ff5e58ad79f182d799aa5697a5\nStopped sandbox aaa1026e560b547e8bd2304980c00ae175274ebe3d6e9bef239c8196a7e63ca4\nStopped sandbox 94b67371bf41a00dad4b06ca51a6df3ec68d009df6b63bac8fbf30747524f13a\nStopped sandbox e784173abcc5ebd75d1a3a020c8acfce6dad06d135de946a0cec35183fa2d299\nStopped sandbox 76810f0329627e5b69c2319e78b0badd8b5402ae301e1d304930157b547b2322\nStopped sandbox 5e62c1fbf2602c9e36613360620bbb07d28db69a113459fb3670c918cf69331f\nStopped sandbox cb63682ca94619baf45d102b84edccb077d15ab30ebba36465353631ede42d18\nStopped sandbox c5927edea97a75d628e280ba8b765c50a309b3b57d0c9d68f6e677f670122f8a\nStopped sandbox 0d75ec03714e6d811251a8a00895c32616825c7499359a2f1b3fa625e1549a1c\nStopped sandbox ce1bbfb8c33d7172b08578c2f4d9ea358fb45f868cf508e67c954bac80412bd9\nStopped sandbox 8b9495604ae902432474431e67c35db0380e83cb25b6ae9a4850ec65072df34e\nStopped sandbox 7508cd4d0813e715bb7240ef0711526c6759a892e278128930ef1d161f01d604\nStopped sandbox 63c64ae3b9aa23ea305c27742032791348fbbee0882d64af2530ca62480acffc\nStopped sandbox c9cbdedfe5d76c4bbfbf1a13b365199b5779a6f4b95d80de22e55af881ee37af\nStopped sandbox 6c8c63666009d4490b987dd6453e47c7183c014a316d8340363f4384191db3f2\nStopped sandbox f89f9ae281a6ceb68293559b6f083452ea150b4139b9b0f7ea7eb9988d5e7cf3\nStopped sandbox 61e972f699cec286e01f453a63c687db34d9ba44ab08c8aed3da2704116a5d7d\nStopped sandbox aff02b9f628fc56e539b515ab74dfa6f640232eb77d8039f148393c7f3b47fca\nStopped sandbox e28d8e26eeb7c0e87aa372a1919407e78a0ea2dc73f38a75f5799c19404a107d\nStopped sandbox 18d8095929aa0632492bebeda6d2086c79a5789333ef739e8e7b2a8139d58a5c\nStopped sandbox f8882d8a35e6729b263d5d21e9ccc524bd4bdf3102c9436049ba1cd985e82837\nStopped sandbox 50d5f377c23f9be1bd3600c337d55456a0a46bdc565a2cd9aae952bf4f5ee400\nStopped sandbox 1feac2160e6019a66c3605ff9346a7ef67d81878b23e91939f9bdba16bfb4055\nStopped sandbox dfd5b36a0b711e69295f7694ed197adb02edb46eb867d28c26d7a96484cc9880\nStopped sandbox f71f7a08e705c3e95c37b099b3af197bd31612b9bf31a80ab94e3768695cc9b6\nStopped sandbox fa7b35f04d1f0b9a0bc0c4d9e1c7142b15a7d98f1157c4db89dcee825edceb2b\nStopped sandbox b2e97d12b2f4faf816e3c7209d03e1c0616f4498f9342b5b7c0fbe808a9da09f\nStopped sandbox cff314010ba1bc0184f8f20335ae38eaae3deb8222cf37b99d6547988d3ca0d1\nStopped sandbox 7c99eb2e56113c9c7f67489938086635e3a3b18393f674f8a7fdf4e4f26ca048\nStopped sandbox ba1b00725d09521693014fcca8949b512b9e6ddc85a2df0952989e73e816d150\nStopped sandbox 03349ad1a857944b3b76deb82334aefb38405f9c19be341c04d2793564918aef\nStopped sandbox 56449796ac4b39b6870f5d60fd365a9e769100c99a397de4cbcd10a342dfa050\nStopped sandbox bbcb1c7da0ac4bb25bb2b41c9ad89c6ad7702872928dbb652026ec06623229dc\ntime=\"2019-12-04T01:49:36Z\" level=fatal msg=\"removing the pod sandbox \\\"23f83aedaca6aca592610ae684958c2db797f3799014a896e0f3c199351ac486\\\" failed: rpc error: code = Unknown desc = failed to remove pod sandbox 23f83aedaca6aca592610ae684958c2db797f3799014a896e0f3c199351ac486: unlinkat /var/run/containers/storage/overlay-containers/23f83aedaca6aca592610ae684958c2db797f3799014a896e0f3c199351ac486/userdata/shm: device or resource busy\"\n - sleeping 2s"
    time="2019-12-03T20:49:39-05:00" level=debug msg="retry loop 1"
    time="2019-12-03T20:49:41-05:00" level=debug msg="Output of bash -c 'sudo crictl stopp $(sudo crictl pods -q) &&\\\nsudo crictl rmp $(sudo crictl pods -q)': Stopped sandbox 23f83aedaca6aca592610ae684958c2db797f3799014a896e0f3c199351ac486\nStopped sandbox 77c661b1d7639c6ddfe1387e10df9d167a1bb06ddd1b36fa03c090009fc81597\nStopped sandbox d9ff10e77b0b2f528c76e1c18801bd88b1ad5b7445eb99516bf39bcea0d3666e\nStopped sandbox 119eb84b844e5dbc3c288aa12d07c6e34e27ed756e64302c09854b62e316290b\nStopped sandbox 7be776bccc656ea9406627156cda89dc00e66bf4fafb4c74c53d5330a19a5062\nStopped sandbox 679adf006167fa8fd73f63eaf66306e24776971e36935ba8366bd62b03430d92\nStopped sandbox 3df7c45a081997fab90b86dd2f0d19c7663a94a4327ea876e210840ace4e74a3\nStopped sandbox 9b19f93e58a37357a36bb81334ea897aaddb01d9530bedcff516cd81c573322c\nStopped sandbox f60e88158b9c86f07001882338f9aabbe507a00f125e1ecdfc7ce44a958b3328\nStopped sandbox 4891dc67e695bf48bcdeb9accd26b4bff4f2e25ca29f371462f300c2e14182a6\nStopped sandbox b5f4d6d112c3099fed18193bbd45398e2ca3efbbe53673d5e6bcc500307d86dd\nStopped sandbox a69ab882041252ae5139b823e779677c8b57c8dc4612939e50d45899d443f554\nStopped sandbox 3d903e56310335141d56f70fd4a1d2e0809c9ab73ee38f6dedba1a10cd2cba59\nStopped sandbox a6254032a44c9ea9e4c3143fdeb1546120e322ff5e58ad79f182d799aa5697a5\nStopped sandbox aaa1026e560b547e8bd2304980c00ae175274ebe3d6e9bef239c8196a7e63ca4\nStopped sandbox 94b67371bf41a00dad4b06ca51a6df3ec68d009df6b63bac8fbf30747524f13a\nStopped sandbox e784173abcc5ebd75d1a3a020c8acfce6dad06d135de946a0cec35183fa2d299\nStopped sandbox 76810f0329627e5b69c2319e78b0badd8b5402ae301e1d304930157b547b2322\nStopped sandbox 5e62c1fbf2602c9e36613360620bbb07d28db69a113459fb3670c918cf69331f\nStopped sandbox cb63682ca94619baf45d102b84edccb077d15ab30ebba36465353631ede42d18\nStopped sandbox c5927edea97a75d628e280ba8b765c50a309b3b57d0c9d68f6e677f670122f8a\nStopped sandbox 0d75ec03714e6d811251a8a00895c32616825c7499359a2f1b3fa625e1549a1c\nStopped sandbox ce1bbfb8c33d7172b08578c2f4d9ea358fb45f868cf508e67c954bac80412bd9\nStopped sandbox 8b9495604ae902432474431e67c35db0380e83cb25b6ae9a4850ec65072df34e\nStopped sandbox 7508cd4d0813e715bb7240ef0711526c6759a892e278128930ef1d161f01d604\nStopped sandbox 63c64ae3b9aa23ea305c27742032791348fbbee0882d64af2530ca62480acffc\nStopped sandbox c9cbdedfe5d76c4bbfbf1a13b365199b5779a6f4b95d80de22e55af881ee37af\nStopped sandbox 6c8c63666009d4490b987dd6453e47c7183c014a316d8340363f4384191db3f2\nStopped sandbox f89f9ae281a6ceb68293559b6f083452ea150b4139b9b0f7ea7eb9988d5e7cf3\nStopped sandbox 61e972f699cec286e01f453a63c687db34d9ba44ab08c8aed3da2704116a5d7d\nStopped sandbox aff02b9f628fc56e539b515ab74dfa6f640232eb77d8039f148393c7f3b47fca\nStopped sandbox e28d8e26eeb7c0e87aa372a1919407e78a0ea2dc73f38a75f5799c19404a107d\nStopped sandbox 18d8095929aa0632492bebeda6d2086c79a5789333ef739e8e7b2a8139d58a5c\nStopped sandbox f8882d8a35e6729b263d5d21e9ccc524bd4bdf3102c9436049ba1cd985e82837\nStopped sandbox 50d5f377c23f9be1bd3600c337d55456a0a46bdc565a2cd9aae952bf4f5ee400\nStopped sandbox 1feac2160e6019a66c3605ff9346a7ef67d81878b23e91939f9bdba16bfb4055\nStopped sandbox dfd5b36a0b711e69295f7694ed197adb02edb46eb867d28c26d7a96484cc9880\nStopped sandbox f71f7a08e705c3e95c37b099b3af197bd31612b9bf31a80ab94e3768695cc9b6\nStopped sandbox fa7b35f04d1f0b9a0bc0c4d9e1c7142b15a7d98f1157c4db89dcee825edceb2b\nStopped sandbox b2e97d12b2f4faf816e3c7209d03e1c0616f4498f9342b5b7c0fbe808a9da09f\nStopped sandbox cff314010ba1bc0184f8f20335ae38eaae3deb8222cf37b99d6547988d3ca0d1\nStopped sandbox 7c99eb2e56113c9c7f67489938086635e3a3b18393f674f8a7fdf4e4f26ca048\nStopped sandbox ba1b00725d09521693014fcca8949b512b9e6ddc85a2df0952989e73e816d150\nStopped sandbox 03349ad1a857944b3b76deb82334aefb38405f9c19be341c04d2793564918aef\nStopped sandbox 56449796ac4b39b6870f5d60fd365a9e769100c99a397de4cbcd10a342dfa050\nStopped sandbox bbcb1c7da0ac4bb25bb2b41c9ad89c6ad7702872928dbb652026ec06623229dc\nRemoved sandbox 23f83aedaca6aca592610ae684958c2db797f3799014a896e0f3c199351ac486\nRemoved sandbox 77c661b1d7639c6ddfe1387e10df9d167a1bb06ddd1b36fa03c090009fc81597\nRemoved sandbox d9ff10e77b0b2f528c76e1c18801bd88b1ad5b7445eb99516bf39bcea0d3666e\nRemoved sandbox 119eb84b844e5dbc3c288aa12d07c6e34e27ed756e64302c09854b62e316290b\nRemoved sandbox 7be776bccc656ea9406627156cda89dc00e66bf4fafb4c74c53d5330a19a5062\nRemoved sandbox 679adf006167fa8fd73f63eaf66306e24776971e36935ba8366bd62b03430d92\nRemoved sandbox 3df7c45a081997fab90b86dd2f0d19c7663a94a4327ea876e210840ace4e74a3\nRemoved sandbox 9b19f93e58a37357a36bb81334ea897aaddb01d9530bedcff516cd81c573322c\nRemoved sandbox f60e88158b9c86f07001882338f9aabbe507a00f125e1ecdfc7ce44a958b3328\nRemoved sandbox 4891dc67e695bf48bcdeb9accd26b4bff4f2e25ca29f371462f300c2e14182a6\nRemoved sandbox b5f4d6d112c3099fed18193bbd45398e2ca3efbbe53673d5e6bcc500307d86dd\nRemoved sandbox a69ab882041252ae5139b823e779677c8b57c8dc4612939e50d45899d443f554\nRemoved sandbox 3d903e56310335141d56f70fd4a1d2e0809c9ab73ee38f6dedba1a10cd2cba59\nRemoved sandbox a6254032a44c9ea9e4c3143fdeb1546120e322ff5e58ad79f182d799aa5697a5\nRemoved sandbox aaa1026e560b547e8bd2304980c00ae175274ebe3d6e9bef239c8196a7e63ca4\nRemoved sandbox 94b67371bf41a00dad4b06ca51a6df3ec68d009df6b63bac8fbf30747524f13a\nRemoved sandbox e784173abcc5ebd75d1a3a020c8acfce6dad06d135de946a0cec35183fa2d299\nRemoved sandbox 76810f0329627e5b69c2319e78b0badd8b5402ae301e1d304930157b547b2322\nRemoved sandbox 5e62c1fbf2602c9e36613360620bbb07d28db69a113459fb3670c918cf69331f\nRemoved sandbox cb63682ca94619baf45d102b84edccb077d15ab30ebba36465353631ede42d18\nRemoved sandbox c5927edea97a75d628e280ba8b765c50a309b3b57d0c9d68f6e677f670122f8a\nRemoved sandbox 0d75ec03714e6d811251a8a00895c32616825c7499359a2f1b3fa625e1549a1c\nRemoved sandbox ce1bbfb8c33d7172b08578c2f4d9ea358fb45f868cf508e67c954bac80412bd9\nRemoved sandbox 8b9495604ae902432474431e67c35db0380e83cb25b6ae9a4850ec65072df34e\nRemoved sandbox 7508cd4d0813e715bb7240ef0711526c6759a892e278128930ef1d161f01d604\nRemoved sandbox 63c64ae3b9aa23ea305c27742032791348fbbee0882d64af2530ca62480acffc\nRemoved sandbox c9cbdedfe5d76c4bbfbf1a13b365199b5779a6f4b95d80de22e55af881ee37af\nRemoved sandbox 6c8c63666009d4490b987dd6453e47c7183c014a316d8340363f4384191db3f2\nRemoved sandbox f89f9ae281a6ceb68293559b6f083452ea150b4139b9b0f7ea7eb9988d5e7cf3\nRemoved sandbox 61e972f699cec286e01f453a63c687db34d9ba44ab08c8aed3da2704116a5d7d\nRemoved sandbox aff02b9f628fc56e539b515ab74dfa6f640232eb77d8039f148393c7f3b47fca\nRemoved sandbox e28d8e26eeb7c0e87aa372a1919407e78a0ea2dc73f38a75f5799c19404a107d\nRemoved sandbox 18d8095929aa0632492bebeda6d2086c79a5789333ef739e8e7b2a8139d58a5c\nRemoved sandbox f8882d8a35e6729b263d5d21e9ccc524bd4bdf3102c9436049ba1cd985e82837\nRemoved sandbox 50d5f377c23f9be1bd3600c337d55456a0a46bdc565a2cd9aae952bf4f5ee400\nRemoved sandbox 1feac2160e6019a66c3605ff9346a7ef67d81878b23e91939f9bdba16bfb4055\nRemoved sandbox dfd5b36a0b711e69295f7694ed197adb02edb46eb867d28c26d7a96484cc9880\nRemoved sandbox f71f7a08e705c3e95c37b099b3af197bd31612b9bf31a80ab94e3768695cc9b6\nRemoved sandbox fa7b35f04d1f0b9a0bc0c4d9e1c7142b15a7d98f1157c4db89dcee825edceb2b\nRemoved sandbox b2e97d12b2f4faf816e3c7209d03e1c0616f4498f9342b5b7c0fbe808a9da09f\nRemoved sandbox cff314010ba1bc0184f8f20335ae38eaae3deb8222cf37b99d6547988d3ca0d1\nRemoved sandbox 7c99eb2e56113c9c7f67489938086635e3a3b18393f674f8a7fdf4e4f26ca048\nRemoved sandbox ba1b00725d09521693014fcca8949b512b9e6ddc85a2df0952989e73e816d150\nRemoved sandbox 03349ad1a857944b3b76deb82334aefb38405f9c19be341c04d2793564918aef\nRemoved sandbox 56449796ac4b39b6870f5d60fd365a9e769100c99a397de4cbcd10a342dfa050\nRemoved sandbox bbcb1c7da0ac4bb25bb2b41c9ad89c6ad7702872928dbb652026ec06623229dc"
    time="2019-12-03T20:49:41-05:00" level=debug msg="Output is : {\"auths\":{\"cloud.openshift.com\":{\"auth\":\"b3B...\"},\"registry.connect.redhat.com\":{\"auth\":\"Nj...\"},\"registry.redhat.io\":{\"auth\":\"NjQ3MzkwNH.....\"}}}"
    time="2019-12-03T20:50:02-05:00" level=info msg="Starting OpenShift cluster ... [waiting 3m]"
    time="2019-12-03T20:53:04-05:00" level=error msg="Error approving the node csr Not able to get csr names (exit status 1 : Unable to connect to the server: x509: certificate signed by unknown authority\n)"
    time="2019-12-03T21:04:14-05:00" level=error msg="Unable to connect to the server: x509: certificate signed by unknown authority\n - exit status 1"`

**Comment by jepries** [comment]
UPDATE.  I repeated all steps, only this time, I unset my https_proxy and http_proxy just before executing crc start.

I have to have the proxy to get the software and allow crc setup to install the driver.

    unset https_proxy
    unset http_proxy
    crc start

IT WORKS.  

You cannot do crc start with environment varialbes https_proxy and http_proxy set!

**Comment by praveenkumar** [comment]
@jepries We are working on the proxy support right now, Good to know you have a proxied environment, once we have something ready with proxy, will let you know and hope you can able to perform a test for us :)

**Comment by jepries** [comment]
@praveenkumar you bet! Im just happy I did that 1 last test :).

I also had to add the local address to my network settings DNS resolvers to get the console to resolve, but that was easy to find compared to unsetting the proxy lol

**Comment by gbraad** [comment]
This is not related to the proxy support of CRC. In other words, `oc` seems to obey proxies, but this causes the traffic to be resigned/or terminated wrongly. Iwould expect `no_proxy` should be set for `.testing`. If `oc` does not use this, it should be filed against the client.

**Comment by jepries** [comment]
@gbraad is correct.  I added a NO_PROXY=.testing to my environment and "crc start" started fine.

    $ crc start
    INFO Checking if running as non-root              
    INFO Checking if oc binary is cached              
    INFO Checking if HyperKit is installed            
    INFO Checking if crc-driver-hyperkit is installed 
    INFO Checking file permissions for /etc/resolver/testing 
    INFO Checking file permissions for /etc/hosts     
    INFO Starting CodeReady Containers VM for OpenShift 4.2.8... 
    INFO Verifying validity of the cluster certificates ... 
    INFO Network restart not needed                   
    INFO Check internal and public DNS query ...      
    INFO Starting OpenShift cluster ... [waiting 3m]  
    INFO                                              
    INFO To access the cluster, first set up your environment by following 'crc oc-env' instructions 
    INFO Then you can access it by running 'oc login -u developer -p developer https://api.crc.testing:6443' 
    INFO To login as an admin, username is 'kubeadmin' and password is Uxxxx-hxxxx-Jxxxx-8xxxx 
    INFO                                              
    INFO You can now run 'crc console' and use these credentials to access the OpenShift web console 
    Started the OpenShift cluster
    WARN The cluster might report a degraded or error state. This is expected since several operators have been disabled to lower the resource usage. For more information, please consult the documentation 
    $ env | grep -i proxy
    NO_PROXY=.testing
    http_proxy=desktop.proxy.xyzcorp.com:5150
    https_proxy=desktop.proxy.xyzcorp.com:5150
    $

**Comment by praveenkumar** [comment]
closing this issue since proxy feature is tracked #337

**Comment by gkrnlr** [comment]
There is problem re-directing to the crc console after crc start, even after setting the IP in wifi setting also unable to open the console.

When I ran below 2 commands then only I was able to open the console.
sudo ifconfig en0 down
sudo ifconfig en0 up

Probably I have to change the setting in chrome browser, as John Pries suggested when I met him.

**Comment by cfergeau** [comment]
@gkrnlr  I don't think this is related to this bug report, please open a new issue so that this can be investigated/tracked properly.
