### ISSUE TITLE
Should not try renewal process on older bundles

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#867]
The renewal process will throw errors with older bundles, we should only try to run it when the `cert-recovery` image is present (which will correspond to 4.2.8 bundles or newer).

**Comment by praveenkumar** [comment]
@cfergeau that is by default since older bundle is bound to the older release which doesn't have renewal code so how it start renewal process? I think @jsliacan compiled using older version so get that issue.

**Comment by cfergeau** [comment]
Still feels slightly more robust to have proper error reporting even in cases which should not happen. Here we are relying on checks in totally different parts of the code, having an explicit check in the cert renewal code doesnot hurt imo.
