### ISSUE TITLE
Bundle 'crc_hyperkit_4.2.8.crcbundle' was requested, but the existing VM is using 'crc_hyperkit_4.2.2.crcbundle' 

### ISSUE THREAD

**Issue by erpenbach** [code-ready/crc#870]
Environment info   
  System Version:	macOS 10.15.1 (19B88)
  Kernel Version:	Darwin 19.0.0

Running as non-root

Downloaded and extracted CRC 1.2 (crc-macos-amd64.tar.xz) from https://cloud.redhat.com/openshift/install/crc/installer-provisioned.

After adding the extracted location to my path, I ran 'crc setup'
mbp-3:crc-macos-1.2.0-amd64 user1$ crc setup
INFO Checking if running as non-root              
INFO Caching oc binary                            
INFO Setting up virtualization with HyperKit      
INFO Installing crc-machine-hyperkit              
INFO Setting file permissions for /etc/resolver/testing 
INFO Setting file permissions for /etc/hosts      
INFO Unpacking bundle from the CRC binary         
Setup is complete, you can now run 'crc start' to start the OpenShift cluster

Then ran 'crc start'

mbp-3:crc-macos-1.2.0-amd64 user1$ crc start
INFO Checking if running as non-root              
INFO Checking if oc binary is cached              
INFO Checking if HyperKit is installed            
INFO Checking if crc-driver-hyperkit is installed 
INFO Checking file permissions for /etc/resolver/testing 
INFO Checking file permissions for /etc/hosts     
FATA Bundle 'crc_hyperkit_4.2.8.crcbundle' was requested, but the existing VM is using 'crc_hyperkit_4.2.2.crcbundle'

**Comment by cfergeau** [comment]
You have an existing VM using an older bundle, you can remove it using `crc delete`. This is one part of crc which needs to be polished. We cannot remove it automatically as it may contain user data.
