### ISSUE TITLE
CRC setup fails on Hyper-v virtual switch

### ISSUE THREAD

**Issue by BrianGos** [code-ready/crc#876]
### General information

Hi, I seem to be running into a common error (based on issue search) with the Hyper-V virtual switch. during CRC setup. I have relogged & rebooted. I appear to be a user in Hyper-V admin group. Hyper-V service also appears to be running.

PS C:\Users\bgoslin\OpenShift\CRC\crc-windows-1.2.0-amd64> net start "Hyper-V Virtual Machine Management"
The requested service has already been started.

  * OS: Windows
  * Hypervisor: Hyper-V 
  * Did you run `crc setup` before starting it (Yes/No)? yes

PS C:\Users\bgoslin\OpenShift\CRC\crc-windows-1.2.0-amd64> .\crc setup  --log-level debug
INFO Checking if running as normal user
INFO Caching oc binary
DEBU oc binary already cached
INFO Unpacking bundle from the CRC binary
INFO Check Windows 10 release
INFO Hyper-V installed
INFO Is user a member of the Hyper-V Administrators group
INFO Does the Hyper-V virtual switch exist
ERRO Virtual Switch not found
DEBU Virtual Switch not found
ERRO Unable to perform Hyper-V administrative commands. Please make sure to re-login or reboot your system
FATA Unable to perform Hyper-V administrative commands. Please make sure to re-login or reboot your system

## CRC version
PS C:\Users\bgoslin\OpenShift\CRC\crc-windows-1.2.0-amd64> .\crc version
crc version: 1.2.0+c2e3c0f
OpenShift version: 4.2.8 (embedded in binary)
  
## CRC status
```bash
# Put the output of `crc status`
```

## CRC config
```bash
# Put the output of `crc config view`
```

## Host Operating System
Host Name:                 DUBLPJCVGQV2
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          
Registered Organization:   
Product ID:                00329-00000-00003-AA627
Original Install Date:     25/06/2019, 09:16:52
System Boot Time:          09/12/2019, 21:20:39
System Manufacturer:       Dell Inc.
System Model:              Precision 5530
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 10 GenuineIntel ~2592 Mhz
BIOS Version:              Dell Inc. 1.8.1, 01/02/2019
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-gb;English (United Kingdom)
Input Locale:              en-gb;English (United Kingdom)
Time Zone:                 (UTC+00:00) Dublin, Edinburgh, Lisbon, London
Total Physical Memory:     16,095 MB
Available Physical Memory: 9,930 MB
Virtual Memory: Max Size:  18,527 MB
Virtual Memory: Available: 10,577 MB
Virtual Memory: In Use:    7,950 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    
Logon Server:              
Hotfix(s):                 10 Hotfix(s) Installed.
                           [01]: KB4514366
                           [02]: KB4470788
                           [03]: KB4487038
                           [04]: KB4504369
                           [05]: KB4509095
                           [06]: KB4512577
                           [07]: KB4512937
                           [08]: KB4516115
                           [09]: KB4523204
                           [10]: KB4523205
Network Card(s):           3 NIC(s) Installed.
                           [01]: Intel(R) Wireless-AC 9260
                                 Connection Name: WiFi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.0.1
                                 IP address(es)
                                 [01]: 192.168.0.45
                                 [02]: fe80::2966:3d7f:6725:9e58
                                 [03]: 2a02:8084:8081:c080:65da:c7b9:f62c:8d3f
                                 [04]: 2a02:8084:8081:c080:2966:3d7f:6725:9e58
                           [02]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [03]: Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows x64
                                 Connection Name: Ethernet 2
                                 Status:          Hardware not present
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

### Steps to reproduce

  1. run .\crc setup
  2. 
  3. 
  4. 

### Expected
CRC setup completes successfully

### Actual
CRC setup fails

### Logs

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by anjannath** [comment]
@BrianGos From Windows version 1709 there is a `Default Switch` present which is created when you install Hyper-V, but you don't have that. at least from the `systeminfo` you provided this seems to be the case.

Can you check in the Hyper-V management GUI under the Virtual switch manager if the switch is there.

**Comment by BrianGos** [comment]
@anjannath Thank you. Creating the external switch manually seems to have worked well.

PS C:\users\bgoslin\OneDrive - daa> cd C:\Users\bgoslin\OpenShift\CRC\crc-windows-1.2.0-amd64
PS C:\Users\bgoslin\OpenShift\CRC\crc-windows-1.2.0-amd64> .\crc setup
INFO Checking if running as normal user
INFO Caching oc binary
INFO Unpacking bundle from the CRC binary
INFO Check Windows 10 release
INFO Hyper-V installed
INFO Is user a member of the Hyper-V Administrators group
INFO Does the Hyper-V virtual switch exist
INFO Found Virtual Switch to use: crc
Setup is complete, you can now run 'crc start' to start the OpenShift cluster

**Comment by praveenkumar** [comment]
@BrianGos Since it is worked for you,  can we close this issue?

**Comment by BrianGos** [comment]
@praveenkumar Please do. Thanks for the help!

**Comment by gbraad** [comment]
This needs some coordination when it comes to documenthing this. Ideally we want to avoid this situation, but perhaps a code change to the preflight might be needed to make people attentive of the fact a virtual switch needs to be created.

for the creation process; would this be automated or manual? we can automate the process, as we can provide a selection of interface and then create an external switch for this. although, we do not have any verification checks in place.

If manually created, we need to be clear about the need of a DHCP server on the network segment. Again, we do not check for this.

**Comment by lydodg** [comment]
I'm running into the same issue - I have verified my account is part of the local hyper-v administrators group, and I still get the below.

PS C:\crc> .\crc.exe setup --log-level debug
INFO Checking if oc binary is cached
DEBU oc binary already cached
INFO Checking if CRC bundle is cached in '$HOME/.crc'
INFO Checking if running as normal user
INFO Checking Windows 10 release
INFO Checking if Hyper-V is installed and operational
INFO Checking if user is a member of the Hyper-V Administrators group
DEBU User is not a member of the Hyper-V administrators group
INFO Adding user to the Hyper-V Administrators group
INFO Will run as admin: add user to hyperv admins group
INFO Checking if Hyper-V service is enabled
INFO Checking if the Hyper-V virtual switch exist
DEBU Virtual Switch not found
ERRO Unable to perform Hyper-V administrative commands. Please make sure to re-login or reboot your system
FATA Unable to perform Hyper-V administrative commands. Please make sure to re-login or reboot your system

Windows 10 enterprise - and I have the built in Default Switch *and* a second switch named *crc* that's external.

**Comment by lydodg** [comment]
Sorry running 1.6 should have mentioned.

**Comment by tarilabs** [comment]
I've landed here as I've searched for
```
INFO Checking if the Hyper-V virtual switch exist
```
since `crc setup` was hung there.

I am not sure I will ever be able to reproduce, but to un-stuck it, I simply opened the Hyper-V Manager and as I was fiddling with trying to add a new Virtual Switch, the `crc setup` completed with: 

```
INFO Found Virtual Switch to use: Default Switch
Setup is complete, you can now run 'crc start' to start the OpenShift cluster
```

I don't know if simply opening the GUI somehow triggered something in the background which enabled the `cec setup` to complete, or it was me fiddling with the add/remove Virtual Switch panel, but hey... I thought worthy for reporting it :) 

Win 10 Pro Version 2004 OS Build 19041.685 Experience Pack 120.2212.551.0

**Comment by gbraad** [comment]
you can not add your own 'Default Switch'. it either exists or you can create a 'crc' named override switch, but this means you have to provide your own DHCP and DNS servers on the same segment.

likely what happened is that your hadn't finalized the Hyper-V install with a reboot.
