### ISSUE TITLE
Add `oc login` command to output to allow copy-paste scenario

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#878]
```
Given a user
   starts CRC
     when ends succesful
     then he wants to copy-paste credentials to login to dashboard
```

**Comment by praveenkumar** [comment]
PR is merged now.

**Comment by gbraad** [comment]
@jsliacan can you help with describing issues as a testable scenario (in cucumber), so we can easily talk about them and/or automate the tests

**Comment by jsliacan** [comment]
Copy-paste is a clicking business, but I assume that if we checked that the output contains something that *can* be copied (& pasted), then we've tested the important part. So something like this would work out-of-the-box:
```
Scenario Outline: Start CRC
    Given executing "crc setup" succeeds
    When starting CRC with default bundle and hypervisor "<vm-driver>" succeeds
    Then stdout should contain "Started the OpenShift cluster"
    And stdout should match "<regex matching oc login command to copy&paste>"
```
Essentially, we'd just insert the last line into existing start scenario. Is that what you had in mind @gbraad?
