### ISSUE TITLE
Update README to reflect automatic cert renewal 

### ISSUE THREAD

**Issue by CoaxVex** [code-ready/crc#880]
As of release 1.2.0, crc has built in certificate renewal. (See https://github.com/code-ready/crc/issues/11)

The README has a note at the top that instructs users they need to reinstall their code ready binary and virtual machine every month. Since this is no longer the case, the README should be updated.
(Remove the note or update it with information about the new behaviour)

**Comment by cfergeau** [comment]
This is fixed by https://github.com/code-ready/crc/commit/e017d31325cb2cefcbde906949f8c36433f2534c
