### ISSUE TITLE
CircleCI build process not working as expected

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#89]
Binaries resulting from Circle CI can not run properly:

```
crc - Local OpenShift 4.0 clusters
INFO  Checking if Virtualization is enabled       
INFO  Checking if KVM is enabled                  
INFO  Checking if Libvirt is installed            
INFO  Checking if user is part of libvirt group   
FATAL user: GroupIds requires cgo    
```

**Comment by gbraad** [comment]
See https://github.com/golang/go/issues/19395

We need to modify the `Makefile` to allow `CGO_ENABLED=1` when doing cross-compile

**Comment by praveenkumar** [comment]
This is not because of the `CGO` but looks like we didn't use `-static` ldflags when generating the binary, we should use that.
