### ISSUE TITLE
Customize router in CRC

### ISSUE THREAD

**Issue by rh-fr** [code-ready/crc#895]
### General information

  * OS: Linux
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? yes

## CRC version
```bash
crc version: 1.2.0+c2e3c0f
OpenShift version: 4.2.8 (embedded in binary)
```
  
## CRC status
```bash
CRC VM:          Running
OpenShift:       Running (v4.2.8)
Disk Usage:      11.14GB of 32.2GB (Inside the CRC VM)
Cache Usage:     11.01GB
Cache Directory: /home/riso/.crc/cache
```

## CRC config
```bash
- skip-check-crc-dnsmasq-file           : true
- skip-check-network-manager-config     : true
- skip-check-network-manager-installed  : true
- skip-check-network-manager-running    : true
```

## Host Operating System
```bash
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
```

Hello, I am quite new in OpenShift and not sure if this is the proper place where to ask questions. 

I installed CRC on Ubuntu after few workarounds it works fine. I am surprise, if there is any way how I could customize router in CRC, or add 2nd. router. I can not find any documentation about this topic for OpenShift 4, just for openshift 3 (https://docs.openshift.com/container-platform/3.11/install_config/router/customized_haproxy_router.html). Also I would like to try if I can use nginx as a router with my custom module. Thanks for help

**Comment by praveenkumar** [comment]
This is not related to crc, please ask it either https://github.com/openshift/origin/issues or may be send a mail to openshift-user ML. There is lot of changes happen from 3.x to 4.x . Closing this issue from CRC side.
