### ISSUE TITLE
Add/Install the tray as part of crc setup on macOS

### ISSUE THREAD

**Issue by anjannath** [code-ready/crc#896]
We have to integrate the tray with crc. For this on macOS we can create and add _launchd_ scripts to auto start the daemon and tray app as part of `crc setup`.

https://medium.com/swlh/how-to-use-launchd-to-run-services-in-macos-b972ed1e352

**Comment by sspeiche** [comment]
Is this related or a subtask of https://github.com/code-ready/crc/issues/723 ?

**Comment by anjannath** [comment]
@sspeiche Yes, to be worked on after #861 is in
