### ISSUE TITLE
NodePort doesn't work in CodeReady Container

### ISSUE THREAD

**Issue by barryzhounb** [code-ready/crc#906]
### General information

  * OS: CentOS 8.0
  * Hypervisor: KVM / Hyper-V / hyperkit
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```crc version
crc version: 1.2.0+c2e3c0f
OpenShift version: 4.2.8 (embedded in binary)
```
  
## CRC status
```crc status
CRC VM:          Running
OpenShift:       Running (v4.2.8)
Disk Usage:      17.65GB of 32.2GB (Inside the CRC VM)
Cache Usage:     11.01GB
Cache Directory: /home/crcuser/.crc/cache
```

## CRC config
```crc config view

```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```

### Steps to reproduce

  1.  Run a pod for my small app
Run a TCP server app written by Java on CRC. The TCP Server is listening on port 7777 and receive a client TCP connect request from outside of CRC.

Check pod status, it runs well.
```
$ oc get pods -o wide
NAME READY   STATUS    RESTARTS   AGE     IP   NODE         NOMINATED NODE   READINESS GATES
tcpserver-57c9b44748-k9dxg 1/1 Running 0  113m 10.128.0.229  crc-2n9vw-master-0 <none>  <none>
```
Go inside pod, check pod is running and listeningport 7777.
```
$ oc rsh tcpserver-57c9b44748-k9dxg
sh-4.2$ netstat -nap | grep 7777
tcp6       0      0 127.0.0.1:7777      :::*     LISTEN      1/java   
```
  2. Start a service and use NodePort to listening client from outside of CRC
The following is service definition.
```
apiVersion: v1
kind: Service
metadata:
  name: tcpserver-ingress
  labels:
    app: tcpserver
spec:
  selector:
    app: tcpserver
  type: NodePort
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
      nodePort: 31777
```
 
Check service status, it runs well, and NodePort is 31777
```
$ oc describe svc tcpserver-ingress
Name:                     tcpserver-ingress
Namespace:                myproject
Labels:                   app=tcpserver
Annotations:              <none>
Selector:                 app=tcpserver
Type:                     NodePort
IP:                       172.30.149.98
Port:                     <unset>  7777/TCP
TargetPort:               7777/TCP
NodePort:                 <unset>  31777/TCP
Endpoints:                10.128.0.229:7777
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

```
$ oc get svc
NAME               TYPE     CLUSTER-IP      EXTERNAL-IP   PORT(S)                   AGE
tcpserver-ingres  NodePort    172.30.149.98   <none>      7777:31777/TCP            18m
```
  3.  Access service from outside
Firstly, get Node IP via the following command. Node IP is 192.168.130.11.
```
$ oc get nodes -o wide
NAME                 STATUS   ROLES           AGE   VERSION             INTERNAL-IP      EXTERNAL-IP   OS-IMAGE                                                   KERNEL-VERSION                CONTAINER-RUNTIME
crc-2n9vw-master-0   Ready    master,worker   26d   v1.14.6+6ac6aa4b0   192.168.130.11   <none>        Red Hat Enterprise Linux CoreOS 42.81.20191119.1 (Ootpa)   4.18.0-147.0.3.el8_1.x86_64   cri-o://1.14.11-0.24.dev.rhaos4.2.gitc41de67.el8

```

Then, my client will connect service on CRC with ip 192.168.130.11 and NodePort 31777.

### Expected
Client from outside of CRC should access service on CRC via port 31777

### Actual
client failed to connect service.
On CentOS VM, try to check if 31777 is exposed, run command "netstat -nap | grep 31777", nothing is here. That means service port 31777 doesn't open.

### Logs

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
@barryzhounb CRC runs a VM which to create openshift cluster so when you created a nodeport service that means on the CRC VM that port is exposed and on the host (where crc is running) this can be accessible. 

Try to access it from your CentOS VM using the CRC ip `192.168.130.11` and exposed port `31777` and this should work. 

You are trying to access that service from a different host which have no idea about openshift cluster running by CRC.

**Comment by barryzhounb** [comment]
@praveenkumar I did access that service from CentOS VM, it failed. I tried to see port 31777 on CentOS VM, it doesn't open. So it is quite weird. Do you have any idea how to troubleshoot it?

**Comment by cfergeau** [comment]
You may need to adjust firewall rules for the libvirt zone with firewallcmd if you want to access an unusual port.
I'd troubleshoot with `nc -v`, first on  the host, then if it doesn't work, in the crc VM itself (`oc debug node...` + `nc -v`).

**Comment by barryzhounb** [comment]
Thanks help. The issue was caused by app. Now NodePort works well.

Close this issue.
