### ISSUE TITLE
Could not support deploy existing image which comes from self-signed certificate image registry

### ISSUE THREAD

**Issue by mransonwang** [code-ready/crc#909]
### General information

  * OS: Linux
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
# Put the output of `crc version`
crc version: 1.3.0+918756b
OpenShift version: 4.2.10 (embedded in binary)

  
## CRC status
# Put the output of `crc status`
CRC VM:          Running
OpenShift:       Running (v4.2.10)
Disk Usage:      13.23GB of 32.2GB (Inside the CRC VM)
Cache Usage:     13.75GB
Cache Directory: /home/fwang/.crc/cache

## CRC config
# Put the output of `crc config view`
- http-proxy                            : http://192.168.190.139:8118
- https-proxy                           : http://192.168.190.139:8118
- no-proxy                              : 192.168.190.0,192.168.190.1,192.168.190.2,192.168.190.3,192.168.190.4,192.168.190.5,192.168.190.6,192.168.190.7,192.168.190.8,192.168.190.9,192.168.190.10,192.168.190.11,192.168.190.12,192.168.190.13,192.168.190.14,192.168.190.15,192.168.190.16,192.168.190.17,192.168.190.18,192.168.190.19,192.168.190.20,192.168.190.21,192.168.190.22,192.168.190.23,192.168.190.24,192.168.190.25,192.168.190.26,192.168.190.27,192.168.190.28,192.168.190.29,192.168.190.30,192.168.190.31,192.168.190.32,192.168.190.33,192.168.190.34,192.168.190.35,192.168.190.36,192.168.190.37,192.168.190.38,192.168.190.39,192.168.190.40,192.168.190.41,192.168.190.42,192.168.190.43,192.168.190.44,192.168.190.45,192.168.190.46,192.168.190.47,192.168.190.48,192.168.190.49,192.168.190.50,192.168.190.51,192.168.190.52,192.168.190.53,192.168.190.54,192.168.190.55,192.168.190.56,192.168.190.57,192.168.190.58,192.168.190.59,192.168.190.60,192.168.190.61,192.168.190.62,192.168.190.63,192.168.190.64,192.168.190.65,192.168.190.66,192.168.190.67,192.168.190.68,192.168.190.69,192.168.190.70,192.168.190.71,192.168.190.72,192.168.190.73,192.168.190.74,192.168.190.75,192.168.190.76,192.168.190.77,192.168.190.78,192.168.190.79,192.168.190.80,192.168.190.81,192.168.190.82,192.168.190.83,192.168.190.84,192.168.190.85,192.168.190.86,192.168.190.87,192.168.190.88,192.168.190.89,192.168.190.90,192.168.190.91,192.168.190.92,192.168.190.93,192.168.190.94,192.168.190.95,192.168.190.96,192.168.190.97,192.168.190.98,192.168.190.99,192.168.190.100,192.168.190.101,192.168.190.102,192.168.190.103,192.168.190.104,192.168.190.105,192.168.190.106,192.168.190.107,192.168.190.108,192.168.190.109,192.168.190.110,192.168.190.111,192.168.190.112,192.168.190.113,192.168.190.114,192.168.190.115,192.168.190.116,192.168.190.117,192.168.190.118,192.168.190.119,192.168.190.120,192.168.190.121,192.168.190.122,192.168.190.123,192.168.190.124,192.168.190.125,192.168.190.126,192.168.190.127,192.168.190.128,192.168.190.129,192.168.190.130,192.168.190.131,192.168.190.132,192.168.190.133,192.168.190.134,192.168.190.135,192.168.190.136,192.168.190.137,192.168.190.138,192.168.190.139,192.168.190.140,192.168.190.141,192.168.190.142,192.168.190.143,192.168.190.144,192.168.190.145,192.168.190.146,192.168.190.147,192.168.190.148,192.168.190.149,192.168.190.150,192.168.190.151,192.168.190.152,192.168.190.153,192.168.190.154,192.168.190.155,192.168.190.156,192.168.190.157,192.168.190.158,192.168.190.159,192.168.190.160,192.168.190.161,192.168.190.162,192.168.190.163,192.168.190.164,192.168.190.165,192.168.190.166,192.168.190.167,192.168.190.168,192.168.190.169,192.168.190.170,192.168.190.171,192.168.190.172,192.168.190.173,192.168.190.174,192.168.190.175,192.168.190.176,192.168.190.177,192.168.190.178,192.168.190.179,192.168.190.180,192.168.190.181,192.168.190.182,192.168.190.183,192.168.190.184,192.168.190.185,192.168.190.186,192.168.190.187,192.168.190.188,192.168.190.189,192.168.190.190,192.168.190.191,192.168.190.192,192.168.190.193,192.168.190.194,192.168.190.195,192.168.190.196,192.168.190.197,192.168.190.198,192.168.190.199,192.168.190.200,192.168.190.201,192.168.190.202,192.168.190.203,192.168.190.204,192.168.190.205,192.168.190.206,192.168.190.207,192.168.190.208,192.168.190.209,192.168.190.210,192.168.190.211,192.168.190.212,192.168.190.213,192.168.190.214,192.168.190.215,192.168.190.216,192.168.190.217,192.168.190.218,192.168.190.219,192.168.190.220,192.168.190.221,192.168.190.222,192.168.190.223,192.168.190.224,192.168.190.225,192.168.190.226,192.168.190.227,192.168.190.228,192.168.190.229,192.168.190.230,192.168.190.231,192.168.190.232,192.168.190.233,192.168.190.234,192.168.190.235,192.168.190.236,192.168.190.237,192.168.190.238,192.168.190.239,192.168.190.240,192.168.190.241,192.168.190.242,192.168.190.243,192.168.190.244,192.168.190.245,192.168.190.246,192.168.190.247,192.168.190.248,192.168.190.249,192.168.190.250,192.168.190.251,192.168.190.252,192.168.190.253,192.168.190.254,192.168.190.255,192.168.130.0,192.168.130.1,192.168.130.2,192.168.130.3,192.168.130.4,192.168.130.5,192.168.130.6,192.168.130.7,192.168.130.8,192.168.130.9,192.168.130.10,192.168.130.11,192.168.130.12,192.168.130.13,192.168.130.14,192.168.130.15,192.168.130.16,192.168.130.17,192.168.130.18,192.168.130.19,192.168.130.20,192.168.130.21,192.168.130.22,192.168.130.23,192.168.130.24,192.168.130.25,192.168.130.26,192.168.130.27,192.168.130.28,192.168.130.29,192.168.130.30,192.168.130.31,192.168.130.32,192.168.130.33,192.168.130.34,192.168.130.35,192.168.130.36,192.168.130.37,192.168.130.38,192.168.130.39,192.168.130.40,192.168.130.41,192.168.130.42,192.168.130.43,192.168.130.44,192.168.130.45,192.168.130.46,192.168.130.47,192.168.130.48,192.168.130.49,192.168.130.50,192.168.130.51,192.168.130.52,192.168.130.53,192.168.130.54,192.168.130.55,192.168.130.56,192.168.130.57,192.168.130.58,192.168.130.59,192.168.130.60,192.168.130.61,192.168.130.62,192.168.130.63,192.168.130.64,192.168.130.65,192.168.130.66,192.168.130.67,192.168.130.68,192.168.130.69,192.168.130.70,192.168.130.71,192.168.130.72,192.168.130.73,192.168.130.74,192.168.130.75,192.168.130.76,192.168.130.77,192.168.130.78,192.168.130.79,192.168.130.80,192.168.130.81,192.168.130.82,192.168.130.83,192.168.130.84,192.168.130.85,192.168.130.86,192.168.130.87,192.168.130.88,192.168.130.89,192.168.130.90,192.168.130.91,192.168.130.92,192.168.130.93,192.168.130.94,192.168.130.95,192.168.130.96,192.168.130.97,192.168.130.98,192.168.130.99,192.168.130.100,192.168.130.101,192.168.130.102,192.168.130.103,192.168.130.104,192.168.130.105,192.168.130.106,192.168.130.107,192.168.130.108,192.168.130.109,192.168.130.110,192.168.130.111,192.168.130.112,192.168.130.113,192.168.130.114,192.168.130.115,192.168.130.116,192.168.130.117,192.168.130.118,192.168.130.119,192.168.130.120,192.168.130.121,192.168.130.122,192.168.130.123,192.168.130.124,192.168.130.125,192.168.130.126,192.168.130.127,192.168.130.128,192.168.130.129,192.168.130.130,192.168.130.131,192.168.130.132,192.168.130.133,192.168.130.134,192.168.130.135,192.168.130.136,192.168.130.137,192.168.130.138,192.168.130.139,192.168.130.140,192.168.130.141,192.168.130.142,192.168.130.143,192.168.130.144,192.168.130.145,192.168.130.146,192.168.130.147,192.168.130.148,192.168.130.149,192.168.130.150,192.168.130.151,192.168.130.152,192.168.130.153,192.168.130.154,192.168.130.155,192.168.130.156,192.168.130.157,192.168.130.158,192.168.130.159,192.168.130.160,192.168.130.161,192.168.130.162,192.168.130.163,192.168.130.164,192.168.130.165,192.168.130.166,192.168.130.167,192.168.130.168,192.168.130.169,192.168.130.170,192.168.130.171,192.168.130.172,192.168.130.173,192.168.130.174,192.168.130.175,192.168.130.176,192.168.130.177,192.168.130.178,192.168.130.179,192.168.130.180,192.168.130.181,192.168.130.182,192.168.130.183,192.168.130.184,192.168.130.185,192.168.130.186,192.168.130.187,192.168.130.188,192.168.130.189,192.168.130.190,192.168.130.191,192.168.130.192,192.168.130.193,192.168.130.194,192.168.130.195,192.168.130.196,192.168.130.197,192.168.130.198,192.168.130.199,192.168.130.200,192.168.130.201,192.168.130.202,192.168.130.203,192.168.130.204,192.168.130.205,192.168.130.206,192.168.130.207,192.168.130.208,192.168.130.209,192.168.130.210,192.168.130.211,192.168.130.212,192.168.130.213,192.168.130.214,192.168.130.215,192.168.130.216,192.168.130.217,192.168.130.218,192.168.130.219,192.168.130.220,192.168.130.221,192.168.130.222,192.168.130.223,192.168.130.224,192.168.130.225,192.168.130.226,192.168.130.227,192.168.130.228,192.168.130.229,192.168.130.230,192.168.130.231,192.168.130.232,192.168.130.233,192.168.130.234,192.168.130.235,192.168.130.236,192.168.130.237,192.168.130.238,192.168.130.239,192.168.130.240,192.168.130.241,192.168.130.242,192.168.130.243,192.168.130.244,192.168.130.245,192.168.130.246,192.168.130.247,192.168.130.248,192.168.130.249,192.168.130.250,192.168.130.251,192.168.130.252,192.168.130.253,192.168.130.254,192.168.130.255,127.0.0.1,localhost,.cluster.local,.svc,.crc.testing,.apps-crc.testing

## Host Operating System
# Put the output of `cat /etc/os-release` in case of Linux
NAME="Red Hat Enterprise Linux"
VERSION="8.0 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.0"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.0 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.0:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.0
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.0"

### Steps to reproduce

  1. Login web console at https://console-openshift-console.apps-crc.testing/
  2. Switch to Developer console
  3. Select Deploy an existing image from an image registry
  4. Input an image URL which is hosted by self-signed certificate image regisry, for example registry.example.com/springboot-helloworld:v1.0, the page will show "Could not load image metadata" message, which means not support self-signed certificate image registry

### Expected

Support deploy existing image from an self-signed certificate image registry

### Logs

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
@mransonwang You need to create a pull secret for pulling an image from the private registry https://docs.openshift.com/container-platform/4.2/openshift_images/managing-images/using-image-pull-secrets.html#images-allow-pods-to-reference-images-from-secure-registries_using-image-pull-secrets , let us know if that helps.

**Comment by mransonwang** [comment]
> 
> 
> @mransonwang You need to create a pull secret for pulling an image from the private registry https://docs.openshift.com/container-platform/4.2/openshift_images/managing-images/using-image-pull-secrets.html#images-allow-pods-to-reference-images-from-secure-registries_using-image-pull-secrets , let us know if that helps.

Actually there's no secret in the private registry, the registry just uses a self-signed certificate to provide https access, no other authentication mechanism. I could use podman pull command with no secret to pull the image successfully.
