### ISSUE TITLE
Build Kernel Modules for Code-Ready Containers

### ISSUE THREAD

**Issue by yanniszark** [code-ready/crc#911]
### General information

I want to use CodeReady Containers to check if a software is compatible with Openshift.
Said software needs to install a kernel module.
In order to install the kernel module, I need to build it with the host machine's (CRC VM) kernel headers.
However, kernel headers are missing in the CRC VM and there is no package manager to retrieve them inside the CRC VM.
AFAIK, the CRC VM uses RHEL, which doesn't provide kernel headers without a paid subscription.

### Expected

To be able to build a kernel module for the CRC VM.

### Actual

Didn't find any kernel headers or package manager to install them inside the VM.

### Additional

I used version `1.2.0-4.2.8`.
I would appreaciate any information on how to make this work.

**Comment by gbraad** [comment]
This is rather an issue related to the installer and associated CoreOS
image: @ashcrow Any idea?

**Comment by ashcrow** [comment]
@dustymabe has some really awesome work related to this.

**Comment by gbraad** [comment]
I'll expect to hear from him after the holidays... I'll ping him ...

**Comment by gbraad** [comment]
We discussed this and several things will be brought up; like headers and development need an entitlement, and not being available in the developer subscription?

Some of the tests and work can be found here: https://github.com/dustymabe/kmods-via-containers

**Comment by cfergeau** [comment]
Regarding the availability of the kernel headers, I created a RH developer subscription, and I can find the kernel headers which should match what is used by crc at https://access.redhat.com/downloads/content/kernel-headers/4.18.0-147.0.3.el8_1/x86_64/fd431d51/package

Then as Gerard's said, integration of kernel module builds in openshift is work in progress at the moment.

**Comment by gbraad** [comment]
Note: RHCOS does come with a ostree command to perform a layered installation, but this is not meant to create a 'wrokstation'-like OS to perform builds. This should best be tried from a UBI image or a container from which the result gets used.
