### ISSUE TITLE
Ubuntu installation instructions needed.

### ISSUE THREAD

**Issue by lebrisg** [code-ready/crc#917]
### General information

  * OS: Linux (Ubuntu 18.04+)
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes

Would it be possible to get the instructions to install CRC on Ubuntu (18.04+)?

**Comment by praveenkumar** [comment]
Can you check https://github.com/code-ready/crc/issues/549 one, it does have lot of comments around what manual steps need for ubuntu.

**Comment by gbraad** [comment]
It would be helpful if you can verify these comments and provide the needed
steps. This way we can update the install process. We had conflicting
results when it comes to usage of NetworkManager and networkd.

**Comment by lebrisg** [comment]
I removed all libvirt, qemu-kvm packages and any traces of crc configuration.
Then, I followed praveenkumar's instructions:

-------------------------------------------------------------------------------------
Install required libvirt and dnsmasq packages.

$ sudo apt-get update
$ sudo apt-get install qemu-kvm libvirt-daemon libvirt-daemon-system dnsmasq

Edit the DNS address for resolved service so dns can be run parallel to resolv service. Here we need to un-comment the DNS and add the IP.

$ sudo vi /etc/systemd/resolved.conf
[Resolve]
DNS=127.0.0.2

Change the listen address for dnsmasq.conf, listen-address field should be uncommented and have 127.0.0.2 as IP.

Tell dnsmasq to ignore systemd-resolved to prevent a loop. Check IGNORE_RESOLVCONF should be set to yes

$ cat /etc/default/dnsmasq 
# This file has five functions: 
# 1) to completely disable starting dnsmasq, 
# 2) to set DOMAIN_SUFFIX by running `dnsdomainname` 
# 3) to select an alternative config file
#    by setting DNSMASQ_OPTS to --conf-file=<file>
# 4) to tell dnsmasq to read the files in /etc/dnsmasq.d for
#    more configuration variables.
# 5) to stop the resolvconf package from controlling dnsmasq's
#    idea of which upstream nameservers to use.
# For upgraders from very old versions, all the shell variables set 
# here in previous versions are still honored by the init script
# so if you just keep your old version of this file nothing will break.

DOMAIN_SUFFIX=``
#DNSMASQ_OPTS="--conf-file=/etc/dnsmasq.alt"

# Whether or not to run the dnsmasq daemon; set to 0 to disable.
ENABLED=1

# By default search this drop directory for configuration options.
# Libvirt leaves a file here to make the system dnsmasq play nice.
# Comment out this line if you don't want this. The dpkg-* are file
# endings which cause dnsmasq to skip that file. This avoids pulling
# in backups made by dpkg.
CONFIG_DIR=/etc/dnsmasq.d,.dpkg-dist,.dpkg-old,.dpkg-new

# If the resolvconf package is installed, dnsmasq will use its output 
# rather than the contents of /etc/resolv.conf to find upstream 
# nameservers. Uncommenting this line inhibits this behaviour.
# Note that including a "resolv-file=<filename>" line in 
# /etc/dnsmasq.conf is not enough to override resolvconf if it is
# installed: the line below must be uncommented.
IGNORE_RESOLVCONF=yes

Add crc.conf file to dnsmasq config file.

$ sudo vi /etc/dnsmasq.d/crc.conf 
server=/crc.testing/192.168.130.1
address=/apps-crc.testing/192.168.130.11

Now you have to restart the dnsmasq and resolved service.

$ sudo systemctl restart systemd-resolved
$ sudo systemctl restart dnsmasq

-------------------------------------------------------------------------------------
At the end, as dnsmasq didn't start (it was masked), I had to run the following commands:
$ sudo systemctl unmask dnsmasq
$ sudo systemctl start dnsmasq
$ crc setup
$ crc start

Now, it seems to work (crc console works) but I have no idea of the correctness of the DNS configuration.
When I run 'netstat -ntpl', I got the following result:
# netstat -ntpl
tcp        0      0 127.0.0.1:5900          0.0.0.0:*               LISTEN      2805/qemu-system-x8 
tcp        0      0 127.0.1.1:53              0.0.0.0:*               LISTEN      2610/dnsmasq        
tcp        0      0 192.168.130.1:53      0.0.0.0:*               LISTEN      2480/dnsmasq        
tcp        0      0 192.168.122.1:53      0.0.0.0:*               LISTEN      1187/dnsmasq        
tcp        0      0 127.0.0.53:53            0.0.0.0:*               LISTEN      653/systemd-resolve 
tcp        0      0 127.0.0.1:631            0.0.0.0:*               LISTEN      923/cupsd           
tcp6      0      0 ::1:631                       :::*                        LISTEN      923/cupsd           

127.0.0.2 doesn't appear anywhere!

**Comment by cfergeau** [comment]
https://labs.consol.de/devops/linux/2019/11/29/codeready-containers-on-ubuntu.html which is linked in #549 has a much simpler solution to the DNS setup.

**Comment by matihost** [comment]
I prefer not disable systemd-resolved on Ubuntu as it is vital Ubuntu service. 

My cheat sheet - works for me under Ubuntu 19.10
```
sudo apt install qemu-kvm libvirt-daemon libvirt-daemon-system network-manager dnsmasq 
sudo usermod -aG libvirt $(whoami) 
 
# reboot to groups change takes effect
reboot

# check whether virt is working, I have IOMMU warning but works
virt-host-validate


cat << EOF | sudo tee /etc/default/dnsmasq > /dev/null  
DOMAIN_SUFFIX=`` 
ENABLED=1 
CONFIG_DIR=/etc/dnsmasq.d,.dpkg-dist,.dpkg-old,.dpkg-new 
IGNORE_RESOLVCONF=yes 
EOF 

  

cat << EOF | sudo tee /etc/dnsmasq.d/crc.conf > /dev/null  
server=/crc.testing/192.168.130.1 
address=/apps-crc.testing/192.168.130.11 
EOF 

cat << EOF | sudo tee /etc/systemd/resolved.conf > /dev/null  
[Resolve] 
DNS=127.0.0.2 
Domains=apps-crc.testing 
EOF 

sudo systemctl restart systemd-resolved 
sudo systemctl restart dnsmasq 

 
mkdir -p ~/tmp && cd ~/tmp && curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/crc/latest/crc-linux-amd64.tar.xz && tar -Jxvf crc-linux-amd64.tar.xz && mv crc-linux*/crc ~/bin/ && rm -rf ~/tmp 
 
Download pull secret from: 
https://cloud.redhat.com/openshift/install/crc/installer-provisioned 
and story it under ~/.crc-pull-secret 

crc setup 

# default 8192 leads to some OutOfMemory for some pods
# debug prints a lot, but allows to react if something is wrong....
crc start -m 10240 -p ~/.crc-pull-secret --log-level debug


# obtain credentials and then connect to Web console 
crc console --credentials 
crc console 
 
# use correct oc client
eval   $(crc oc-env) 

 

# use kubeconfig provided and bare kubectl 
[ -e $HOME/.crc/machines/crc/kubeconfig ] && echo 'export  KUBECONFIG=$HOME/.kube/config:$HOME/.crc/machines/crc/kubeconfig' >> ~/.bashrc 

bash 
kubectl config use-context admin
kubectl get po --all-namespaces
```

**Comment by praveenkumar** [comment]
@matihost thanks for putting the instruction can you please add this comment to https://github.com/code-ready/crc/issues/549 here also.

**Comment by cfergeau** [comment]
ubuntu support has been added a few releases ago, closing this.
