### ISSUE TITLE
Implement DNS checks for api. from host

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#918]
At the moment we have seen some recurring issues regarding the api endpoint not being reachable. This is likely an issue with the DNS, but unsure what causes this. A simple check to verify this from the host might aid in pinpointing this ahead of time.

**Comment by cfergeau** [comment]
Duplicate of #854

**Comment by gbraad** [comment]
Can we modify the title of #854 to better reflect changes that need to happen? I'll close this issue, but we need a clrar overview of needed tests in that issue.
