### ISSUE TITLE
Investigate how to integrate/accommodate the use of Odo

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#923]
At the moment we have a short statement in the docs related to accessing the cluster in which we describe `odo`. However, I think we can do a better job.

Changes possible could be to enhance the documentation, but also code changes, such as adding an alias to `oc-env` as `odo-env` for those who never used `oc`, but are `odo` users... perhaps embedding the binary, etc.

**Comment by gbraad** [comment]
@code-ready/crc-devel WDYT?

**Comment by cfergeau** [comment]
*if* we choose to embed `odo`, then having `oc odo-env` makes sense. If `odo` is not embedded, I don't think `odo-env` is very useful, the user installed `odo` themselves, so in my opinion it's up to them to do the needed configuration for the cluster they want to use.

I would not go too far with enhancing the documentation, as we don't want to have too much overlap with preexisting openshift documentation. Blog posts/videos showing how to use `odo` with `crc` sounds good though.

**Comment by gbraad** [comment]
@robin-owen agreed that the documentation should not retell the same story. If some other documentation exists (and does in the form of `odo`'s docs) we should refer to this.

**Comment by gbraad** [comment]
Blog posts and videos is something we could discuss with the odo team.
