### ISSUE TITLE
Handle the install on Windows Enterprise (checks + docs)

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#924]
Installing and usage on Win 10 Home and Pro works more-or-less out of the box. In a corporate environment, they might end up with a machine that runs Enterprise edition (this is not uncommon). The way Enterprise works is different, not an out-of-the-box experience. The Virtual Switch must be set up manually.

If there’s a switch named `crc`, we will use this. This is not properly documented, though it has been mentioned in release notes. Additional section for this might be needed.

During pre-flights we can detect 'Enterprise' and inform the user of this need when the switch check is performed.

**Comment by hetzbh** [comment]
Actually, at the moment, if your Windows 10 pro is connected to AD and you're logged in with the AD credentials, it fails to detect virtual switch and gives false errors about permissions (even if you're a user who's in the AD a member of Administrators group)

**Comment by gbraad** [comment]
@hetzbh this is a different issue: #742. Debug information or additional notes are appreciated, however a workaround for this is available.

**Comment by gbraad** [comment]
Prevent the creation of a VSwitch named "Default Switch" #965

**Comment by gbraad** [comment]
To my surprise the 1903 version of Win10 Enterprise does come witrh the Default Switch
