### ISSUE TITLE
Remove `vm-driver` flag from setup command

### ISSUE THREAD

**Issue by anjannath** [code-ready/crc#966]
We no longer need this flag as only the default drivers are supported.

**Comment by ildar** [comment]
> We no longer need this flag as only the default drivers are supported.

What was the reasoning?

**Comment by guillaumerose** [comment]
docker-machine is a dead project. It doesn't evolve and is full of bugs. Without this constraint, we can diverge and refactor the code.

**Comment by ildar** [comment]
I see. Thanks.
Though having hypervisor choice is nice in many cases.

**Comment by ildar** [comment]
BTW docker-machine was revived in a fork. And Minikube still uses it with a
changed upstream repo: https://github.com/kubernetes/minikube/issues/3019
So libmachine may still work out well. (emm, I'm not 100% sure though :))

**Comment by guillaumerose** [comment]
Yes that's why there are really happy now with the docker driver :)
It delegates all the VM work to Docker Desktop.
