### ISSUE TITLE
[BUG] `crc start` fails at adding pull secret and crc VM shuts off

### ISSUE THREAD

**Issue by omkensey** [code-ready/crc#968]
### General information

  * OS: Linux
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
crc version: 1.4.0+d5bb3a3
OpenShift version: 4.2.13 (embedded in binary)
```
  
## CRC status
```bash
CRC VM:          Stopped
OpenShift:       Stopped
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     13.23GB
Cache Directory: /home/kensey/.crc/cache
```

## CRC config
```bash
[no output]
```

## Host Operating System
```bash
NAME=Fedora
VERSION="31 (Workstation Edition)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

### Steps to reproduce

  1. Download the crc release
  2. Go through the setup from https://code-ready.github.io/crc/
  3. During `crc start`, the VM starts but at the `Adding user's pull secret` step, the VM shuts down and the start process hangs.

### Expected
Successful start

### Actual
Start failed

### Logs
https://gist.github.com/omkensey/f73f9cb07a1987f27bbf78284a4e1e92

**Comment by gbraad** [comment]
```
Using SSH client type: external
Using SSH private key: /home/kensey/.crc/machines/crc/id_rsa (-rw-------)
&{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null core@192.168.130.11 -o IdentitiesOnly=yes -i /home/kensey/.crc/machines/crc/id_rsa -p 22] /usr/bin/ssh <nil>}
DEBU About to run SSH command:
sudo systemctl -f start kubelet 
DEBU SSH cmd err, output: <nil>:                  
INFO Adding user's pull secret ...                
(crc) Calling .GetSSHHostname
(crc) DBG | GetIP called for crc
(crc) DBG | Getting current state...
(crc) DBG | IP address: 192.168.130.11
(crc) Calling .GetSSHPort
(crc) Calling .GetSSHKeyPath
(crc) Calling .GetSSHKeyPath
(crc) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /home/kensey/.crc/machines/crc/id_rsa (-rw-------)
&{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null core@192.168.130.11 -o IdentitiesOnly=yes -i /home/kensey/.crc/machines/crc/id_rsa -p 22] /usr/bin/ssh <nil>}
DEBU About to run SSH command with hidden output  
DEBU The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port? 
DEBU error: Temporary Error: exit status 1 - sleeping 1s 
DEBU retry loop 1                                 
DEBU The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port? 
DEBU error: Temporary Error: exit status 1 - sleeping 1s 
[and so on through more retry loops]
```


can you check with `host api.crc.testing` if you get the expected `192.168.130.11` as a result?

**Comment by praveenkumar** [comment]
I can see in the logs following which means it able to resolve the crc domain from the host, how much time you waited before this exist sometime this step can take 30-40 retry so need to wait until it exit with errror.

```
INFO Check DNS query from host ...                
DEBU api.crc.testing resolved to [192.168.130.11] 
DEBU foo.apps-crc.testing resolved to [192.168.130.11] 
```

**Comment by cfergeau** [comment]
When you say "the VM shuts down", did you check with `virsh -c qemu:///system list` that it's no longer running? Or did you check this differently?

**Comment by omkensey** [comment]
Current status:

I ran `crc start` and got an unsuccessful start (see below for details on that).  Then I ran `crc delete` and `crc start` again and got further than I have up to this point, but it failed again.  The logs go past inserting the pull secret this time, up to this point:

```
INFO Starting OpenShift cluster ... [waiting 3m]  
DEBU Unable to connect to the server: dial tcp: lookup api.crc.testing on 127.0.0.1:53: read udp 127.0.0.1:54786->127.0.0.1:53: i/o timeout 
DEBU error: Temporary Error: exit status 1 - sleeping 1s 
DEBU retry loop 1                                 
DEBU Unable to connect to the server: dial tcp: lookup api.crc.testing on 127.0.0.1:53: read udp 127.0.0.1:35907->127.0.0.1:53: i/o timeout 
DEBU error: Temporary Error: exit status 1 - sleeping 1s 
DEBU retry loop 2                                 
DEBU Unable to connect to the server: dial tcp: lookup api.crc.testing on 127.0.0.1:53: read udp 127.0.0.1:43654->127.0.0.1:53: i/o timeout 
DEBU error: Temporary Error: exit status 1 - sleeping 1s 
DEBU retry loop 3                                 
DEBU Unable to connect to the server: dial tcp: lookup api.crc.testing on 127.0.0.1:53: read udp 127.0.0.1:60717->127.0.0.1:53: i/o timeout 
DEBU error: Temporary Error: exit status 1 - sleeping 1s 
DEBU retry loop 4                                 
DEBU Unable to connect to the server: dial tcp: lookup api.crc.testing on 127.0.0.1:53: read udp 127.0.0.1:57246->127.0.0.1:53: i/o timeout 
DEBU error: Temporary Error: exit status 1 - sleeping 1s 
DEBU retry loop 5                                 
DEBU Unable to connect to the server: dial tcp: lookup api.crc.testing on 127.0.0.1:53: read udp 127.0.0.1:33400->127.0.0.1:53: i/o timeout 
DEBU error: Temporary Error: exit status 1 - sleeping 1s 
DEBU retry loop 6                                 
DEBU Unable to connect to the server: dial tcp: lookup api.crc.testing on 127.0.0.1:53: read udp 127.0.0.1:57999->127.0.0.1:53: i/o timeout 
DEBU error: Temporary Error: exit status 1 - sleeping 1s 
DEBU retry loop 7                                 
DEBU Unable to connect to the server: dial tcp: lookup api.crc.testing on 127.0.0.1:53: read udp 127.0.0.1:42306->127.0.0.1:53: i/o timeout 
DEBU error: Temporary Error: exit status 1 - sleeping 1s 
DEBU retry loop 8
```

I can give the full debug logs if needed, but this may be more useful: libvirtd is throwing EOF errors and other errors about the crc VM.  Here are the libvirtd journal entries from today through the most recent start that is still retry-looping:

```
Jan 28 12:20:29 genesis-device dnsmasq[389423]: reading /etc/resolv.conf
Jan 28 12:20:29 genesis-device dnsmasq[389423]: using nameserver 127.0.0.1#53
Jan 28 12:20:29 genesis-device dnsmasq[1268]: reading /etc/resolv.conf
Jan 28 12:20:29 genesis-device dnsmasq[1268]: using nameserver 127.0.0.1#53
Jan 28 12:20:36 genesis-device dnsmasq[389423]: reading /etc/resolv.conf
Jan 28 12:20:36 genesis-device dnsmasq[389423]: using nameserver 127.0.0.1#53
Jan 28 12:20:36 genesis-device dnsmasq[1268]: reading /etc/resolv.conf
Jan 28 12:20:36 genesis-device dnsmasq[1268]: using nameserver 127.0.0.1#53
Jan 28 12:22:40 genesis-device libvirtd[388725]: Domain id=8 name='crc' uuid=87686b44-bddc-40a5-b951-a621ee876f0e is tainted: host-cpu
Jan 28 12:22:50 genesis-device dnsmasq-dhcp[389423]: DHCPDISCOVER(crc) 52:fd:fc:07:21:82
Jan 28 12:22:50 genesis-device dnsmasq-dhcp[389423]: DHCPOFFER(crc) 192.168.130.11 52:fd:fc:07:21:82
Jan 28 12:22:50 genesis-device dnsmasq-dhcp[389423]: DHCPREQUEST(crc) 192.168.130.11 52:fd:fc:07:21:82
Jan 28 12:22:50 genesis-device dnsmasq-dhcp[389423]: DHCPACK(crc) 192.168.130.11 52:fd:fc:07:21:82 crc-k4zmd-master-0
Jan 28 12:23:54 genesis-device libvirtd[388725]: internal error: End of file from qemu monitor
Jan 28 12:34:07 genesis-device libvirtd[388725]: Domain id=9 name='crc' uuid=87686b44-bddc-40a5-b951-a621ee876f0e is tainted: host-cpu
Jan 28 12:34:16 genesis-device dnsmasq-dhcp[389423]: DHCPREQUEST(crc) 192.168.130.11 52:fd:fc:07:21:82
Jan 28 12:34:16 genesis-device dnsmasq-dhcp[389423]: DHCPACK(crc) 192.168.130.11 52:fd:fc:07:21:82 crc-k4zmd-master-0
Jan 28 12:34:34 genesis-device libvirtd[388725]: End of file while reading data: Input/output error
Jan 28 12:34:34 genesis-device libvirtd[388725]: End of file while reading data: Input/output error
Jan 28 12:42:22 genesis-device libvirtd[388725]: End of file while reading data: Input/output error
Jan 28 12:43:03 genesis-device libvirtd[388725]: Domain id=10 name='crc' uuid=37845ab1-4630-4a0b-94fb-266f703ae7d9 is tainted: host-cpu
Jan 28 12:43:13 genesis-device dnsmasq-dhcp[389423]: DHCPDISCOVER(crc) 52:fd:fc:07:21:82
Jan 28 12:43:13 genesis-device dnsmasq-dhcp[389423]: DHCPOFFER(crc) 192.168.130.11 52:fd:fc:07:21:82
Jan 28 12:43:13 genesis-device dnsmasq-dhcp[389423]: DHCPREQUEST(crc) 192.168.130.11 52:fd:fc:07:21:82
Jan 28 12:43:13 genesis-device dnsmasq-dhcp[389423]: DHCPACK(crc) 192.168.130.11 52:fd:fc:07:21:82 crc-k4zmd-master-0
Jan 28 12:45:37 genesis-device libvirtd[388725]: internal error: End of file from qemu monitor

```

> can you check with `host api.crc.testing` if you get the expected `192.168.130.11` as a result?

Currently after another attempt, `host api.crc.testing` is reporting `;; connection timed out; no servers could be reached`, but DNS works for other things so I assume that's just dnsmasq passing along the errors it's getting about upstream resolvers.

> > [and so on through more retry loops]
> 
> Please, do not edit the log files (except for removing information you wish to obfuscate), but it is an indication to how many times it has been retried and therefore an indication of time, such as settling the load or operators inside the cluster.

At that point it just sat there looping through retries with nothing else in between.

> I can see in the logs following which means it able to resolve the crc domain from the host, how much time you waited before this exit, sometime this step can take 30-40 retry so need to wait until it exit with errror.
> 
> ```
> INFO Check DNS query from host ...                
> DEBU api.crc.testing resolved to [192.168.130.11] 
> DEBU foo.apps-crc.testing resolved to [192.168.130.11] 
> ```

I let it get to 9 retries before I killed it -- the VM wasn't starting up and there was no indication it was ever going to either progress or time out.

> When you say "the VM shuts down", did you check with `virsh -c qemu:///system list` that it's no longer running? Or did you check this differently?

I had virt-manager open and in view already and could see it go from running to shut down in the window.

-----

Retrying today, I'm getting inconsistent behavior.  The first `crc start` got up to "Updating cluster info" before it spit out usage errors regarding `crictl stopp` and `crictl rmp` and erroring out:

```
INFO Adding user's pull secret ...                
(crc) Calling .GetSSHHostname
(crc) DBG | GetIP called for crc
(crc) DBG | Getting current state...
(crc) DBG | IP address: 192.168.130.11
(crc) Calling .GetSSHPort
(crc) Calling .GetSSHKeyPath
(crc) Calling .GetSSHKeyPath
(crc) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /home/kensey/.crc/machines/crc/id_rsa (-rw-------)
&{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null core@192.168.130.11 -o IdentitiesOnly=yes -i /home/kensey/.crc/machines/crc/id_rsa -p 22] /usr/bin/ssh <nil>}
DEBU About to run SSH command with hidden output  
DEBU The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port? 
DEBU error: Temporary Error: exit status 1 - sleeping 1s 
DEBU retry loop 1                                 
DEBU The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port? 
DEBU error: Temporary Error: exit status 1 - sleeping 1s 
DEBU retry loop 2                                 
DEBU The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port? 
DEBU error: Temporary Error: exit status 1 - sleeping 1s 
DEBU retry loop 3                                 
DEBU NAME                       TYPE                                  DATA   AGE
builder-dockercfg-shq7l    kubernetes.io/dockercfg               1      24d
builder-token-cq6pb        kubernetes.io/service-account-token   4      24d
builder-token-thzfk        kubernetes.io/service-account-token   4      24d
default-dockercfg-5sx9j    kubernetes.io/dockercfg               1      24d
default-token-4tggf        kubernetes.io/service-account-token   4      24d
default-token-bcfxc        kubernetes.io/service-account-token   4      24d
deployer-dockercfg-lxbqf   kubernetes.io/dockercfg               1      24d
deployer-token-44p5k       kubernetes.io/service-account-token   4      24d
deployer-token-mv55b       kubernetes.io/service-account-token   4      24d 
INFO Updating cluster ID ...                      
DEBU NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version             False       True          24d     Unable to apply 4.2.13: the cluster operator monitoring is degraded 
(crc) Calling .GetSSHHostname
(crc) DBG | GetIP called for crc
(crc) DBG | Getting current state...
(crc) DBG | IP address: 192.168.130.11
(crc) Calling .GetSSHPort
(crc) Calling .GetSSHKeyPath
(crc) Calling .GetSSHKeyPath
(crc) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /home/kensey/.crc/machines/crc/id_rsa (-rw-------)
&{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null core@192.168.130.11 -o IdentitiesOnly=yes -i /home/kensey/.crc/machines/crc/id_rsa -p 22] /usr/bin/ssh <nil>}
DEBU About to run SSH command:
sudo systemctl -f stop kubelet 
DEBU SSH cmd err, output: <nil>:                  
(crc) Calling .GetSSHHostname
(crc) DBG | GetIP called for crc
(crc) DBG | Getting current state...
(crc) DBG | IP address: 192.168.130.11
(crc) Calling .GetSSHPort
(crc) Calling .GetSSHKeyPath
(crc) Calling .GetSSHKeyPath
(crc) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /home/kensey/.crc/machines/crc/id_rsa (-rw-------)
&{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null core@192.168.130.11 -o IdentitiesOnly=yes -i /home/kensey/.crc/machines/crc/id_rsa -p 22] /usr/bin/ssh <nil>}
DEBU About to run SSH command:
bash -c 'sudo crictl stopp $(sudo crictl pods -q) && sudo crictl rmp $(sudo crictl pods -q)' 
DEBU SSH cmd err, output: <nil>: time="2020-01-28T17:34:32Z" level=fatal msg="failed to connect: failed to connect: context deadline exceeded"
NAME:
   crictl stopp - Stop one or more running pods

USAGE:
   crictl stopp POD-ID [POD-ID...]
time="2020-01-28T17:34:34Z" level=fatal msg="failed to connect: failed to connect: context deadline exceeded"
NAME:
   crictl rmp - Remove one or more pods

USAGE:
   crictl rmp POD-ID [POD-ID...] 
DEBU Output of bash -c 'sudo crictl stopp $(sudo crictl pods -q) && sudo crictl rmp $(sudo crictl pods -q)': time="2020-01-28T17:34:32Z" level=fatal msg="failed to connect: failed to connect: context deadline exceeded"
NAME:
   crictl stopp - Stop one or more running pods

USAGE:
   crictl stopp POD-ID [POD-ID...]
time="2020-01-28T17:34:34Z" level=fatal msg="failed to connect: failed to connect: context deadline exceeded"
NAME:
   crictl rmp - Remove one or more pods

USAGE:
   crictl rmp POD-ID [POD-ID...] 
ERRO Error Setting cluster config: Failed to update cluster ID: Failed to update cluster ID exit status 1: Unable to connect to the server: dial tcp: lookup api.crc.testing on 127.0.0.1:53: read udp 127.0.0.1:36426->127.0.0.1:53: i/o timeout 
Making call to close driver server
(crc) Calling .Close
Successfully made call to close driver server
Making call to close connection to plugin binary
Making call to close driver server
(crc) Calling .Close
(crc) DBG | Closing plugin on server side
Successfully made call to close driver server
Making call to close connection to plugin binary
```

I ran `crc delete` and `crc start` again and got all the way through it waiting to start the OpenShift cluster but then the VM shut down again.

**Comment by omkensey** [comment]
More progress, but it's still kind of iffy.  I noticed my laptop was a little busier than I thought it was, so I freed up a bunch of memory and the install process runs to completion now.  However, although I was able to log in and use it enough to verify that things work fine, the VM still shut off unexpectedly without warning, with libvirtd throwing those end-of-file errors.

Could memory ballooning be the issue here?  Not so much the ballooning itself, but that it's trying to balloon up to the maximum size, ballooning fails, and the domain gets hard-stopped.

**Comment by praveenkumar** [comment]
@omkensey what is your host specification can you put `free -g` output, if your host is already under load then it might cause issue to the CRC VM.

**Comment by cfergeau** [comment]
> Current status:
> 
> I ran `crc start` and got an unsuccessful start (see below for details on that). Then I ran `crc delete` and `crc start` again and got further than I have up to this point, but it failed again. The logs go past inserting the pull secret this time, up to this point:
> 
> ```
> INFO Starting OpenShift cluster ... [waiting 3m]  
> DEBU Unable to connect to the server: dial tcp: lookup api.crc.testing on 127.0.0.1:53: read udp 127.0.0.1:54786->127.0.0.1:53: i/o timeout 
> DEBU error: Temporary Error: exit status 1 - sleeping 1s 
> DEBU retry loop 1                                 
> DEBU Unable to connect to the server: dial tcp: lookup api.crc.testing on 127.0.0.1:53: read udp 127.0.0.1:35907->127.0.0.1:53: i/o timeout 
> DEBU error: Temporary Error: exit status 1 - sleeping 1s 
> DEBU retry loop 2                                 
> DEBU Unable to connect to the server: dial tcp: lookup api.crc.testing on 127.0.0.1:53: read udp 127.0.0.1:43654->127.0.0.1:53: i/o timeout 
> DEBU error: Temporary Error: exit status 1 - sleeping 1s 
> DEBU retry loop 3                                 
> DEBU Unable to connect to the server: dial tcp: lookup api.crc.testing on 127.0.0.1:53: read udp 127.0.0.1:60717->127.0.0.1:53: i/o timeout 
> DEBU error: Temporary Error: exit status 1 - sleeping 1s 
> DEBU retry loop 4                                 
> DEBU Unable to connect to the server: dial tcp: lookup api.crc.testing on 127.0.0.1:53: read udp 127.0.0.1:57246->127.0.0.1:53: i/o timeout 
> DEBU error: Temporary Error: exit status 1 - sleeping 1s 
> DEBU retry loop 5                                 
> DEBU Unable to connect to the server: dial tcp: lookup api.crc.testing on 127.0.0.1:53: read udp 127.0.0.1:33400->127.0.0.1:53: i/o timeout 
> DEBU error: Temporary Error: exit status 1 - sleeping 1s 
> DEBU retry loop 6                                 
> DEBU Unable to connect to the server: dial tcp: lookup api.crc.testing on 127.0.0.1:53: read udp 127.0.0.1:57999->127.0.0.1:53: i/o timeout 
> DEBU error: Temporary Error: exit status 1 - sleeping 1s 
> DEBU retry loop 7                                 
> DEBU Unable to connect to the server: dial tcp: lookup api.crc.testing on 127.0.0.1:53: read udp 127.0.0.1:42306->127.0.0.1:53: i/o timeout 
> DEBU error: Temporary Error: exit status 1 - sleeping 1s 
> DEBU retry loop 8
> ```
> 
> I can give the full debug logs if needed, but this may be more useful: libvirtd is throwing EOF errors and other errors about the crc VM. Here are the libvirtd journal entries from today through the most recent start that is still retry-looping:
> 
> ```
> Jan 28 12:20:29 genesis-device dnsmasq[389423]: reading /etc/resolv.conf
> Jan 28 12:20:29 genesis-device dnsmasq[389423]: using nameserver 127.0.0.1#53
> Jan 28 12:20:29 genesis-device dnsmasq[1268]: reading /etc/resolv.conf
> Jan 28 12:20:29 genesis-device dnsmasq[1268]: using nameserver 127.0.0.1#53
> Jan 28 12:20:36 genesis-device dnsmasq[389423]: reading /etc/resolv.conf
> Jan 28 12:20:36 genesis-device dnsmasq[389423]: using nameserver 127.0.0.1#53
> Jan 28 12:20:36 genesis-device dnsmasq[1268]: reading /etc/resolv.conf
> Jan 28 12:20:36 genesis-device dnsmasq[1268]: using nameserver 127.0.0.1#53
> Jan 28 12:22:40 genesis-device libvirtd[388725]: Domain id=8 name='crc' uuid=87686b44-bddc-40a5-b951-a621ee876f0e is tainted: host-cpu
> Jan 28 12:22:50 genesis-device dnsmasq-dhcp[389423]: DHCPDISCOVER(crc) 52:fd:fc:07:21:82
> Jan 28 12:22:50 genesis-device dnsmasq-dhcp[389423]: DHCPOFFER(crc) 192.168.130.11 52:fd:fc:07:21:82
> Jan 28 12:22:50 genesis-device dnsmasq-dhcp[389423]: DHCPREQUEST(crc) 192.168.130.11 52:fd:fc:07:21:82
> Jan 28 12:22:50 genesis-device dnsmasq-dhcp[389423]: DHCPACK(crc) 192.168.130.11 52:fd:fc:07:21:82 crc-k4zmd-master-0
> Jan 28 12:23:54 genesis-device libvirtd[388725]: internal error: End of file from qemu monitor
> Jan 28 12:34:07 genesis-device libvirtd[388725]: Domain id=9 name='crc' uuid=87686b44-bddc-40a5-b951-a621ee876f0e is tainted: host-cpu
> Jan 28 12:34:16 genesis-device dnsmasq-dhcp[389423]: DHCPREQUEST(crc) 192.168.130.11 52:fd:fc:07:21:82
> Jan 28 12:34:16 genesis-device dnsmasq-dhcp[389423]: DHCPACK(crc) 192.168.130.11 52:fd:fc:07:21:82 crc-k4zmd-master-0
> Jan 28 12:34:34 genesis-device libvirtd[388725]: End of file while reading data: Input/output error
> Jan 28 12:34:34 genesis-device libvirtd[388725]: End of file while reading data: Input/output error
> Jan 28 12:42:22 genesis-device libvirtd[388725]: End of file while reading data: Input/output error
> Jan 28 12:43:03 genesis-device libvirtd[388725]: Domain id=10 name='crc' uuid=37845ab1-4630-4a0b-94fb-266f703ae7d9 is tainted: host-cpu
> Jan 28 12:43:13 genesis-device dnsmasq-dhcp[389423]: DHCPDISCOVER(crc) 52:fd:fc:07:21:82
> Jan 28 12:43:13 genesis-device dnsmasq-dhcp[389423]: DHCPOFFER(crc) 192.168.130.11 52:fd:fc:07:21:82
> Jan 28 12:43:13 genesis-device dnsmasq-dhcp[389423]: DHCPREQUEST(crc) 192.168.130.11 52:fd:fc:07:21:82
> Jan 28 12:43:13 genesis-device dnsmasq-dhcp[389423]: DHCPACK(crc) 192.168.130.11 52:fd:fc:07:21:82 crc-k4zmd-master-0
> Jan 28 12:45:37 genesis-device libvirtd[388725]: internal error: End of file from qemu monitor
> ```
> 
> > can you check with `host api.crc.testing` if you get the expected `192.168.130.11` as a result?
> 
> Currently after another attempt, `host api.crc.testing` is reporting `;; connection timed out; no servers could be reached`, but DNS works for other things so I assume that's just dnsmasq passing along the errors it's getting about upstream resolvers.
> 
> > > [and so on through more retry loops]
> > 
> > 
> > Please, do not edit the log files (except for removing information you wish to obfuscate), but it is an indication to how many times it has been retried and therefore an indication of time, such as settling the load or operators inside the cluster.
> 
> At that point it just sat there looping through retries with nothing else in between.
> 
> > I can see in the logs following which means it able to resolve the crc domain from the host, how much time you waited before this exit, sometime this step can take 30-40 retry so need to wait until it exit with errror.
> > ```
> > INFO Check DNS query from host ...                
> > DEBU api.crc.testing resolved to [192.168.130.11] 
> > DEBU foo.apps-crc.testing resolved to [192.168.130.11] 
> > ```
> 
> I let it get to 9 retries before I killed it -- the VM wasn't starting up and there was no indication it was ever going to either progress or time out.
> 
> > When you say "the VM shuts down", did you check with `virsh -c qemu:///system list` that it's no longer running? Or did you check this differently?
> 
> I had virt-manager open and in view already and could see it go from running to shut down in the window.
> 
> Retrying today, I'm getting inconsistent behavior. The first `crc start` got up to "Updating cluster info" before it spit out usage errors regarding `crictl stopp` and `crictl rmp` and erroring out:
> 
> ```
> INFO Adding user's pull secret ...                
> (crc) Calling .GetSSHHostname
> (crc) DBG | GetIP called for crc
> (crc) DBG | Getting current state...
> (crc) DBG | IP address: 192.168.130.11
> (crc) Calling .GetSSHPort
> (crc) Calling .GetSSHKeyPath
> (crc) Calling .GetSSHKeyPath
> (crc) Calling .GetSSHUsername
> Using SSH client type: external
> Using SSH private key: /home/kensey/.crc/machines/crc/id_rsa (-rw-------)
> &{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null core@192.168.130.11 -o IdentitiesOnly=yes -i /home/kensey/.crc/machines/crc/id_rsa -p 22] /usr/bin/ssh <nil>}
> DEBU About to run SSH command with hidden output  
> DEBU The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port? 
> DEBU error: Temporary Error: exit status 1 - sleeping 1s 
> DEBU retry loop 1                                 
> DEBU The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port? 
> DEBU error: Temporary Error: exit status 1 - sleeping 1s 
> DEBU retry loop 2                                 
> DEBU The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port? 
> DEBU error: Temporary Error: exit status 1 - sleeping 1s 
> DEBU retry loop 3                                 
> DEBU NAME                       TYPE                                  DATA   AGE
> builder-dockercfg-shq7l    kubernetes.io/dockercfg               1      24d
> builder-token-cq6pb        kubernetes.io/service-account-token   4      24d
> builder-token-thzfk        kubernetes.io/service-account-token   4      24d
> default-dockercfg-5sx9j    kubernetes.io/dockercfg               1      24d
> default-token-4tggf        kubernetes.io/service-account-token   4      24d
> default-token-bcfxc        kubernetes.io/service-account-token   4      24d
> deployer-dockercfg-lxbqf   kubernetes.io/dockercfg               1      24d
> deployer-token-44p5k       kubernetes.io/service-account-token   4      24d
> deployer-token-mv55b       kubernetes.io/service-account-token   4      24d 
> INFO Updating cluster ID ...                      
> DEBU NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
> version             False       True          24d     Unable to apply 4.2.13: the cluster operator monitoring is degraded 
> (crc) Calling .GetSSHHostname
> (crc) DBG | GetIP called for crc
> (crc) DBG | Getting current state...
> (crc) DBG | IP address: 192.168.130.11
> (crc) Calling .GetSSHPort
> (crc) Calling .GetSSHKeyPath
> (crc) Calling .GetSSHKeyPath
> (crc) Calling .GetSSHUsername
> Using SSH client type: external
> Using SSH private key: /home/kensey/.crc/machines/crc/id_rsa (-rw-------)
> &{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null core@192.168.130.11 -o IdentitiesOnly=yes -i /home/kensey/.crc/machines/crc/id_rsa -p 22] /usr/bin/ssh <nil>}
> DEBU About to run SSH command:
> sudo systemctl -f stop kubelet 
> DEBU SSH cmd err, output: <nil>:                  
> (crc) Calling .GetSSHHostname
> (crc) DBG | GetIP called for crc
> (crc) DBG | Getting current state...
> (crc) DBG | IP address: 192.168.130.11
> (crc) Calling .GetSSHPort
> (crc) Calling .GetSSHKeyPath
> (crc) Calling .GetSSHKeyPath
> (crc) Calling .GetSSHUsername
> Using SSH client type: external
> Using SSH private key: /home/kensey/.crc/machines/crc/id_rsa (-rw-------)
> &{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null core@192.168.130.11 -o IdentitiesOnly=yes -i /home/kensey/.crc/machines/crc/id_rsa -p 22] /usr/bin/ssh <nil>}
> DEBU About to run SSH command:
> bash -c 'sudo crictl stopp $(sudo crictl pods -q) && sudo crictl rmp $(sudo crictl pods -q)' 
> DEBU SSH cmd err, output: <nil>: time="2020-01-28T17:34:32Z" level=fatal msg="failed to connect: failed to connect: context deadline exceeded"
> NAME:
>    crictl stopp - Stop one or more running pods
> 
> USAGE:
>    crictl stopp POD-ID [POD-ID...]
> time="2020-01-28T17:34:34Z" level=fatal msg="failed to connect: failed to connect: context deadline exceeded"
> NAME:
>    crictl rmp - Remove one or more pods
> 
> USAGE:
>    crictl rmp POD-ID [POD-ID...] 
> DEBU Output of bash -c 'sudo crictl stopp $(sudo crictl pods -q) && sudo crictl rmp $(sudo crictl pods -q)': time="2020-01-28T17:34:32Z" level=fatal msg="failed to connect: failed to connect: context deadline exceeded"
> NAME:
>    crictl stopp - Stop one or more running pods
> 
> USAGE:
>    crictl stopp POD-ID [POD-ID...]
> time="2020-01-28T17:34:34Z" level=fatal msg="failed to connect: failed to connect: context deadline exceeded"
> NAME:
>    crictl rmp - Remove one or more pods
> 
> USAGE:
>    crictl rmp POD-ID [POD-ID...] 
> ERRO Error Setting cluster config: Failed to update cluster ID: Failed to update cluster ID exit status 1: Unable to connect to the server: dial tcp: lookup api.crc.testing on 127.0.0.1:53: read udp 127.0.0.1:36426->127.0.0.1:53: i/o timeout 
> Making call to close driver server
> (crc) Calling .Close
> Successfully made call to close driver server
> Making call to close connection to plugin binary
> Making call to close driver server
> (crc) Calling .Close
> (crc) DBG | Closing plugin on server side
> Successfully made call to close driver server
> Making call to close connection to plugin binary
> ```
> 
> I ran `crc delete` and `crc start` again and got all the way through it waiting to start the OpenShift cluster but then the VM shut down again.

There might be hints in libvirt logs in `/var/log/libvirt`. I'd also check if it's the OOM killer triggering

**Comment by omkensey** [comment]
Nothing relevant inside the VM -- it runs as normal right up till it stops.  libvirtd's logs don't show OOM kills but the logs in /var/lib/libvirtqemu/crc.log do show shutdowns because of signal 15 from a process ID that is libvirtd.

After a fresh boot with plenty of memory free I had the VM running what seemed to be reliably (I need to exercise it some more to be sure though).  So it looks like this issue may have been due to memory pressure -- but I wonder if there is a more graceful/informative way to handle that.

**Comment by cfergeau** [comment]
On Wed, Jan 29, 2020 at 11:47:43AM -0800, Joe Thompson wrote:
> Nothing relevant inside the VM -- it runs as normal right up till it stops.  libvirtd's logs don't show OOM kills but the logs in /var/lib/libvirtqemu/crc.log do show shutdowns because of signal 15 from a process ID that is libvirtd.
> 
Can you also check libvirtd.log if it's libvirtd forcefully killing the
VM?
