### ISSUE TITLE
Create separate pkg for different Linux distro specific pre-flight and setup 

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#97]
As of now we are only targeting `Fedora/CentOS/RHEL` as part of our setup command and even some of the preflight test cases. Moving forward we should group it then distro specific so it would be easy. Might be just create a common interface and the each distro can implement those functions.

**Comment by gbraad** [comment]
See: https://github.com/code-ready/crc/issues/185#issuecomment-499122791

**Comment by gbraad** [comment]
We likely need to use `lsb_release -i` to determine the distro we are running on.

**Comment by gbraad** [comment]
#190

**Comment by guillaumerose** [comment]
With Ubuntu support we have this now, kind of.
