### ISSUE TITLE
[BUG] Failing ERRO Failed to query DNS from host: lookup api.crc.testing on 192.168.1.1:53: no such host

### ISSUE THREAD

**Issue by paoloantinori** [code-ready/crc#976]
### General information

  * OS: Linux
  * Hypervisor: KVM 
  * Did you run `crc setup` before starting it (Yes/No)? YES

## CRC version
```bash
crc version: 1.4.0+d5bb3a3
OpenShift version: 4.2.13 (embedded in binary)

```
  
## CRC status
```bash
ERRO error: stat /home/pantinor/.crc/machines/crc/kubeconfig: no such file or directory
 - exit status 1 

```

## CRC config
```bash
[EMPTY]
```

## Host Operating System
```bash
NAME=Fedora
VERSION="31 (Workstation Edition)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation

```

### Steps to reproduce

  1. `./crc start --log-level debug`
  2. 
  3. 
  4. 

### Logs

https://gist.github.com/paoloantinori/7aa43fe441a8ff2ca2bb4605c981d897

**Comment by praveenkumar** [comment]
@paoloantinori As per following in the logs I think some issue with your dnsmasq side.
```
ERRO Failed to query DNS from host: lookup api.crc.testing on 192.168.1.1:53: no such host 
```

Can you check if there is another testing domain under `/etc/NetworkManager/dnsmasq.d/` directory. If you have multiple files make sure you only keep the `crc.conf` and also reload the network manager daemon using `systemctl reload NetworkManager`.

```
$ ls /etc/NetworkManager/dnsmasq.d/
crc.conf

$ cat /etc/NetworkManager/dnsmasq.d/crc.conf 
server=/apps-crc.testing/192.168.130.11
server=/crc.testing/192.168.130.11

```

**Comment by paoloantinori** [comment]
Hi @praveenkumar thanks for your comment.

This is what I see:

```
16:14:36 (..-linux-1.4.0-amd64)$ ll /etc/NetworkManager/dnsmasq.d/
total 4.0K
-rw-r--r--. 1 root root 75 Jan 28 14:27 crc.conf
```

```
16:15:27 (..-linux-1.4.0-amd64)$ cat /etc/NetworkManager/dnsmasq.d/crc.conf 
server=/apps-crc.testing/192.168.130.11
server=/crc.testing/192.168.130.11
```

Tried to delete cluster, even re-run setup, reload NetworkManager but I have the same exact error there.

**Comment by cfergeau** [comment]
does /etc/resolv.conf reference 192.168.1.1?

**Comment by paoloantinori** [comment]
It does:
```
11:48:19 (..-linux-1.4.0-amd64)$ cat /etc/resolv.conf
# Generated by NetworkManager
search station
nameserver 192.168.1.1
```

**Comment by praveenkumar** [comment]
@paoloantinori if you run crc setup it should change that entry something following or you are running a local dnsmasq server for some other task?

```
$ cat /etc/resolv.conf
# Generated by NetworkManager
search station
nameserver 127.0.0.1
```

**Comment by johnpoth** [comment]
Experiencing same behavior on CentOS Linux release 7.7.1908 (Core)

**Comment by cfergeau** [comment]
Please provide `crc setup --log-level debug` output, `crc config view` output, and any special networking configuration you might have done.

**Comment by johnpoth** [comment]
Hi @cfergeau, thanks for the reply!

As requested:

`crc setup --log-level debug` [output](https://gist.github.com/johnpoth/ef3cad8b952cc10a1c38feba03724757#file-crc-setup-log-level-debug)

`crc config view ` ouput is empty

`crc start --log-level debug` [output](https://gist.github.com/johnpoth/178992091bdb676e45ad8eb90af8f974)

I am not aware of any special networking configuration.

Thanks !

**Comment by praveenkumar** [comment]
@johnpoth as per start logs I can see `ERRO Failed to query DNS from host: lookup api.crc.testing on 10.38.5.26:53: no such host ` which means it might be issue that your dnsmasq is not running with networkManager. what is the outout of following ?

```
$ ls /etc/NetworkManager/conf.d
$ ls /etc/NetworkManager/dnsmasq.d/
$ cat /etc/resolv.conf
```

**Comment by johnpoth** [comment]
Hi @praveenkumar, thanks for your reply!

As requested:

`ls /etc/NetworkManager/conf.d`
`crc-libvirt-dnsmasq.conf  crc-nm-dnsmasq.conf`

`ls /etc/NetworkManager/dnsmasq.d/`
`crc.conf`

`cat /etc/resolv.conf`
`# Generated by NetworkManager`
`search redhat.com cdg.redhat.com win.redhat.com`
`nameserver 10.38.5.26`
`nameserver 10.35.255.14`
`nameserver 10.11.5.19`

Thanks !

**Comment by praveenkumar** [comment]
@johnpoth can you remove `crc-libvirt-dnsmasq.conf` from following directory `/crc-libvirt-dnsmasq.conf` looks like you have and old config.

@johnpoth also as per your logs, looks like the NM manager didn't start the dnsmasq and hence you are seeing that issue. 

```
cat /etc/resolv.conf
# Generated by NetworkManager
search redhat.com cdg.redhat.com win.redhat.com
nameserver 10.38.5.26
nameserver 10.35.255.14
nameserver 10.11.5.19
```
which should be something like
```
$ cat /etc/resolv.conf 
# Generated by NetworkManager
search redhat.com
nameserver 127.0.0.1
```

Also can you provide us following commad the logs in the gist?
```
$ journalctl -b 0 -u NetworkManager
```

**Comment by johnpoth** [comment]
@praveenkumar thanks for the reply! I've deleted `/crc-libvirt-dnsmasq.conf/crc-libvirt-dnsmasq.conf`

`journalctl -b 0 -u NetworkManager` [output](https://gist.github.com/johnpoth/13c2995657fcd7f511ed4b790d706603)

**Comment by cfergeau** [comment]
NetworkManager starts dnsmasq, but:
```
Feb 13 14:52:48 localhost.localdomain NetworkManager[2442]: <info>  [1581601968.0475] dns-plugin[0x5570865b7850]: starting dnsmasq...
Feb 13 14:52:48 localhost.localdomain dnsmasq[5026]: listening on lo(#1): 127.0.0.1
Feb 13 14:52:48 localhost.localdomain NetworkManager[2442]: <warn>  [1581601968.0597] dns-mgr: could not commit DNS changes: Failed to rename file “/etc/resolv.conf.PBVXF0” to “/etc/resolv.conf”: g_rename() failed: Permission denied
```

Is there anything special with the permissions of your resolv.conf? Maybe some selinux issue?

**Comment by johnpoth** [comment]
Hi @cfergeau @praveenkumar, after playing with my network settings, it seems crc is working! Thanks a lot!

**Comment by paoloantinori** [comment]
Hi, I'm back at this. I've revied my network config but couldn't find anything strange.

See most recent logs:

https://gist.github.com/paoloantinori/65205b531b4d0f9380acce27fcdf6aa0

```bash
11:49:17 (..-linux-1.6.0-amd64)$ cat /etc/resolv.conf
# Generated by NetworkManager
search station
nameserver 192.168.1.1

11:51:43 (..-linux-1.6.0-amd64)$ systemctl status dnsmasq.service 
● dnsmasq.service - DNS caching server.
   Loaded: loaded (/usr/lib/systemd/system/dnsmasq.service; disabled; vendor preset: disabled)
   Active: inactive (dead)

11:52:07 (..-linux-1.6.0-amd64)$ ls /etc/NetworkManager/dnsmasq.d/
crc.conf

11:52:28 (..-linux-1.6.0-amd64)$ cat /etc/NetworkManager/dnsmasq.d/crc.conf 
server=/apps-crc.testing/192.168.130.11
server=/crc.testing/192.168.130.11

11:52:47 (..-linux-1.6.0-amd64)$ ps aux | ag dnsmas
dnsmasq     2640  0.0  0.0  22936  2272 ?        S    11:09   0:00 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
root        2641  0.0  0.0  22832    40 ?        S    11:09   0:00 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
dnsmasq     2685  0.0  0.0  22860  1940 ?        S    11:09   0:00 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/docker-machines.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
root        2686  0.0  0.0  22832   196 ?        S    11:09   0:00 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/docker-machines.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
dnsmasq     2732  0.0  0.0  22860  1992 ?        S    11:09   0:00 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/crc.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
root        2733  0.0  0.0  22832  1632 ?        S    11:09   0:00 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/crc.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper

```


Any clue on how to debug this further?

**Comment by cfergeau** [comment]
Network Manager's dnsmasq instance does not seem to be started, can you enable `level=TRACE` in `/etc/NetworkManager/NetworkManager.conf`, restart NetworkManager with systemctl, and provide `journalctl -b 0 -u NetworkManager` ?

**Comment by paoloantinori** [comment]
Thanks for the help.

here you go: https://gist.github.com/paoloantinori/9c1ef02e9490e78dc496846c8455a618

**Comment by cfergeau** [comment]
```
Feb 19 15:01:24 trane NetworkManager[21058]: dnsmasq: failed to create listening socket for 127.0.0.1: Address already in use
```
This seems to be why NM's dnsmasq instance is not running, do you know what is listening on 127.0.0.1:53?

**Comment by paoloantinori** [comment]
```bash
15:59:18 (..-linux-1.6.0-amd64)$ sudo netstat -putan | ag 127.0.0.1:53
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      2452/unbound        

15:59:44 (..-linux-1.6.0-amd64)$ ps aux | ag 2452
unbound     2452  0.0  0.0 266492 29256 ?        Ssl  11:09   0:01 /usr/sbin/unbound -d

```

no clue what is supposed to do

**Comment by cfergeau** [comment]
That's a DNS server, but I don't know why it's installed/running on your machine
https://nlnetlabs.nl/projects/unbound/about/

**Comment by paoloantinori** [comment]
Thank you, that was it.

Thank you everyone involved with this remote debugging activity! Much appreciated! 🙏

I don't think there is a way to generalize, but maybe a useful FAQ could be: verify you don't have any other process listening on `127.0.0.1:53`
