### ISSUE TITLE
OKD-based, registration-free version of CRC

### ISSUE THREAD

**Issue by omkensey** [code-ready/crc#977]
Creating this issue per request of vrutkovs at https://kubernetes.slack.com/archives/C6BRQSH2S/p1580198984018400?thread_ts=1580180011.017200&cid=C6BRQSH2S

### Expected
An OKD-based version of CRC is available that does not require portal registration or authenticating to a container registry to start up.

### Actual
Using CRC requires setting up a Red Hat portal account to download the `crc` release and the necessary pull secret to pull the OpenShift containers from the authenticated Red Hat container registry.

**Comment by vrutkovs** [comment]
OKD releases (not yet released officially) - https://origin-release.svc.ci.openshift.org/

* Based on OCP 4.4 nightlies
* Fedora CoreOS base + machine-os-content
* Forked MCO (`fcos` branch)
* Forked installer (`fcos` branch)

**Comment by gbraad** [comment]
We have been looking into this and had many discussions to allow for an OKD-based release. However, s you can see, this is at the moment still based on forks instead of upstreamed code. This is why this can, at this point in time, still not be considered for release. We are however working on this.

Thanks @vrutkovs for the heads up ;-)!

**Comment by gbraad** [comment]
@vrutkovs any updates?

**Comment by anjannath** [comment]
We made some progress to have OKD based, registration free _bundles_ (one still need to manually change things in crc to use those bundles). the scripts in our snc repo needed minimal changes during my testing to successfully generate OKD bundles. PR in snc repo https://github.com/code-ready/snc/pull/216

overview of the changes i did to the scripts:
- No need to remove the pull-secret config and file, as we inject a dummy pull-secret for okd installation
- Switch the mirror to download okd bits
- Change the ostree hash greping pattern, it starts with fedora-coreos in okd (we need these info to use the image with hyperkit)
- The root partition is not luks-encryption ready in focs, so modify guestfish commands accordingly (createdisk.sh)

**Comment by guillaumerose** [comment]
Related to https://github.com/openshift/community/issues/54

**Comment by guillaumerose** [comment]
OKD release of CRC is available here: https://www.okd.io/crc.html

The UX around the pull secret need to be enhanced but it's fully functionnal.

**Comment by gbraad** [comment]
Currently @cgruver handles this. Closing the issue as this needs a very differently timeline now.
