### ISSUE TITLE
Unable to use OpenShift 4.3 for CRC

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#978]
Currently we are unable to produce usable images for CRC that run OpenShift 4.3. Details for this can be found in: https://bugzilla.redhat.com/show_bug.cgi?id=1795163

If you need to run 4.3, please consider using the installer to create a regular cluster (avoiding to set up a SNC).

**Comment by tmds** [comment]
@gbraad I'd like to run OpenShift 4.3 on my dev machine and found this issue.
Any recommendation on how I can run 4.3 (other can `crc`)?
Do you think there will be a version of `crc` soon that supports 4.3?

**Comment by gbraad** [comment]
We have a workaround that is planned for the coming release. Code freeze is this Friday.

**Comment by praveenkumar** [comment]
I am closing this issue since now we have a workaround which works for 4.3.x and also made a release.

**Comment by gbraad** [comment]
We still have issues with 4.3.x and 4.4 that are tracked on our projects boards https://github.com/code-ready/crc/projects/24
