### ISSUE TITLE
[Integration] Tests too impatient when checking crc status

### ISSUE THREAD

**Issue by jsliacan** [code-ready/crc#983]
Extend the wait time in `Start CRC` scenario in all `story_*` feature files. Tests sometimes fail due to timeout (`crc status` check passes right in the next scenario, so it is an actual timeout). Suggesting to change the number of tries and wait periods from 4x2mins to 15x1min. 

See attached screenshot when this was the cause of a failed test.

![Screenshot from 2020-01-30 15-10-04](https://user-images.githubusercontent.com/2056138/73456725-ab731480-4372-11ea-9e6b-16d671faadbf.png)

**Comment by gbraad** [comment]
Optimistic is a better term to describe this.

However, we should not have to wait multiple times, but wait until something happened and break when it didn't happen in time. Concept of retry is flawed anyway as we do not really retry the action from CRC such as calling the same action; we merely wait for a certain state to eventually be consistent.

**Comment by jsliacan** [comment]
> Optimistic is a better term

Haha

@gbraad about the latter: true, but...

> we should not have to wait multiple times, but wait until something happened and break when it didn't happen in time

We basically do that. One can understand 15x1min wait as a 15min wait (and break if not satisfied by that point) with an option to leave the step earlier if satisfied earlier. This saves test time on "good days" :).

> we do not really retry the action from CRC such as calling the same action; we merely wait for a certain state to eventually be consistent

I see how retry is misleading, but we're merely retrying the checks of the state (re-checking), not retrying to make the state consistent. Seems just an issue with phrasing, not the actual content of the test step. Do I understand you correctly?

**Comment by gbraad** [comment]
Right. The wording "retry" for me would have retriggered the action for CRC and not just testing ;-)

But each time we have a wait statement in our tests I grinch... We should have to be able to do a better job.

**Comment by anjannath** [comment]
@jsliacan Is this still an issue?

**Comment by jsliacan** [comment]
Nope, closed is OK. Thanks.
