### ISSUE TITLE
[BUG] Operatorhub is not working correctly

### ISSUE THREAD

**Issue by crobby** [code-ready/crc#989]
### General information

  * OS: Linux / macOS / Windows:  Linux (Fedora 31)
  * Hypervisor: KVM / Hyper-V / hyperkit: KVM
  * Did you run `crc setup` before starting it (Yes/No)?  Yes

## CRC version
```bash
crc version: 1.4.0+d5bb3a3
OpenShift version: 4.2.13 (embedded in binary)
```
  
## CRC status
```bash
CRC VM:          Running
OpenShift:       Running (v4.2.13)
Disk Usage:      11.65GB of 48.3GB (Inside the CRC VM)
Cache Usage:     26.98GB
Cache Directory: /home/croberts/.crc/cache
```

## CRC config
```bash
- cpus                                  : 6
- memory                                : 16384
```

## Host Operating System
```bash
NAME=Fedora
VERSION="31 (Workstation Edition)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

### Steps to reproduce

  1.   crc setup
  2.   crc start
  3.   login as kubeadmin
  4.  oc get opsrc -n openshift-marketplace

### Expected
Should see no errors

### Actual
oc get opsrc -n openshift-marketplace
NAME                  TYPE          ENDPOINT              REGISTRY              DISPLAYNAME           PUBLISHER   STATUS        MESSAGE                                                                                            AGE
certified-operators   appregistry   https://quay.io/cnr   certified-operators   Certified Operators   Red Hat     Configuring   Get https://quay.io/cnr/api/v1/packages?namespace=certified-operators: context deadline exceeded   31d
community-operators   appregistry   https://quay.io/cnr   community-operators   Community Operators   Red Hat     Configuring   Get https://quay.io/cnr/api/v1/packages?namespace=community-operators: context deadline exceeded   31d
redhat-operators      appregistry   https://quay.io/cnr   redhat-operators      Red Hat Operators     Red Hat     Configuring   Get https://quay.io/cnr/api/v1/packages?namespace=redhat-operators: context deadline exceeded      31d

**Comment by cfergeau** [comment]
Are you running behind a proxy? Could you try with 1.5.0 which was released a few days ago?

**Comment by crobby** [comment]
Not behind a proxy.

**Comment by crobby** [comment]
Where can I find the 1.5.0 package?  Not seeing it on the "releases" on github.

**Comment by cfergeau** [comment]
should be accessible from https://cloud.redhat.com/openshift/install/crc/installer-provisioned

**Comment by crobby** [comment]
Seems to work in 1.5.0.  Thanks for steering me in the right direction.

**Comment by gbraad** [comment]
Can the issue be closed?

**Comment by crobby** [comment]
Sure
