### ISSUE TITLE
Cannot setup on Windows 10 Enterprise Build 18363

### ISSUE THREAD

**Issue by vanuatoo** [code-ready/crc#991]
```
systeminfo shows the following flags
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes
```

when I run crc setup it outputs
```
crc setup --log-level debug
INFO Checking if oc binary is cached
DEBU oc binary already cached
INFO Checking if CRC bundle is cached in '$HOME/.crc'
INFO Checking if running as normal user
INFO Checking Windows 10 release
INFO Checking if Hyper-V is installed and operational
ERRO Hyper-V not installed
DEBU Hyper-V not installed
INFO Installing Hyper-V
INFO Will run as admin: enable Hyper-V
ERRO Please reboot your system
INFO Checking if user is a member of the Hyper-V Administrators group
INFO Checking if Hyper-V service is enabled
INFO Checking if the Hyper-V virtual switch exist
INFO Found Virtual Switch to use: Default Switch
Setup is complete, you can now run 'crc start' to start the OpenShift cluster
```

I rebooted but after crc start it shows
```
crc start --log-level debug
DEBU No new version available. The latest version is 1.5.0
INFO Checking if oc binary is cached
DEBU oc binary already cached
INFO Checking if running as normal user
INFO Checking Windows 10 release
INFO Checking if Hyper-V is installed and operational
ERRO Hyper-V not installed
DEBU Hyper-V not installed
FATA Hyper-V not installed
```

**Comment by gbraad** [comment]
Can you check if all the services are running? Which version of Windows 10?

Note: Build `18363` is release `1909`, so this should be supported.

**Comment by vanuatoo** [comment]
I've got Hyper-V Host Compute Service and Hyper-V Virtual Machine Management running.

**Comment by istyf** [comment]
I am also trying to get CRC up and running on Windows 10 Enterprise and it is a bit of a rough experience so far. Hyper-V has not given me this type of issues though.

What does systeminfo tell you now about Hyper-V?
On my machine it says:
_Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed._
So if your systeminfo still lists requirements I would guess that something didn't work out quite right when crc tried to enable it.

When I installed CRC I enabled Hyper-V separately before running crc setup. What result do you get if you open a PowerShell in admin mode and run:
_Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All_ and reboot when asked to?

**Comment by gbraad** [comment]
> Hyper-V Requirements: A hypervisor has been detected. Features required for Hyper-V will not be displayed.

This is how systeminfo reports this, even when Hyper-V is installed. However, make sure you have NO other hypervisor installed when attempting to use Hyper-V. it will fail when something like VMware is used.

**Comment by gbraad** [comment]
The existence of the Hypervisor is checked with: `@(Get-Wmiobject Win32_ComputerSystem).HypervisorPresent` So if this returns false, there is nothing available for us to use. It might be this call fails due to missing permissions?

If so, you can try to skip this check.

**Comment by gbraad** [comment]
```
PS> crc config set skip-check-hyperv-installed true
```

**Comment by vanuatoo** [comment]
INFO Extracting bundle: crc_hyperv_4.2.14.crcbundle ...
INFO Creating CodeReady Containers VM for OpenShift 4.2.14-x86_64...
ERRO Error creating host: Error creating the VM: Error creating machine: Error in driver during machine creation: open /Users/<my user>/.crc/cache/crc_hyperv_4.2.14/crc.vhdx: The system cannot find the path specified.

**Comment by istyf** [comment]
I have had a couple of errors like that and the workaround has been to manually delete the VM using the Hyper-V Manager and start over with _crc delete -f_. I have a feeling that if _crc start_ fails, then crc can end up in an inconsistent state.
